### ISSUE TITLE
Unclear Install Instructions

### ISSUE THREAD

**Issue by johan-lejdung** [lllyasviel/Fooocus#10]
Hey, this project looks really cool and I want to try it out. 

You pride yourself in being easy to install and get going
> Fooocus has simplified the installation. Between pressing "download" and generating the first image, the number of needed mouse clicks is strictly limited to less than 3. Minimal GPU memory requirement is 4GB (Nvidia).

But I'm unable to progress. I uncompressed the file and I cannot find any `run.bat` file as you mention. There are however two `run_cpu.bat` and one for NVidia GPU as well, but not in the root folder. Are those the ones you are supposed to run?

Even when I run the GPU one (since I have AMD), it just pauses and then exits. Mentioning that main.py is not in the folder.

Would you mind making the `run.bat` step more clear so I can progress?

**Comment by K1ngOfCurses** [comment]
bro its as easy as he said to download, if you dont see ther run.bat then download it again, before you even uncompress it you should see it.
![image](https://github.com/lllyasviel/Fooocus/assets/142113064/6b30a349-4abb-4cff-b210-5bc2b94eb95f)

**Comment by johan-lejdung** [comment]
😳 you are absolutely right! 

I didn't see the extra files and foolishly assumed it was only one folder extracted! My bad.

Thanks for the clarification 🙏

**Comment by K1ngOfCurses** [comment]
no worries it happens all good
