### ISSUE TITLE
fooocus局部重绘的功能是否可同时考虑图像提示和换脸功能？

### ISSUE THREAD

**Issue by kenic123** [lllyasviel/Fooocus#1000]
目前局部重绘功能没办法使用图像提示和换脸，不知道是出于什么原因考虑，个人认为，在局部重绘的时候指定相应的图像参考或是脸部作为参考，这似乎是可行的，而且需求很大。但目前却无法操作，或许是已经有了类似的功能我不知道？请指点

**Comment by metercai** [comment]
在高级设置的开发者模型里面有相应开关，如图：
<img width="416" alt="" src="https://github.com/lllyasviel/Fooocus/assets/5652458/c15a615f-507e-4276-8b55-c92cfa96f573">
