### ISSUE TITLE
FaceSwap makes Colab crash

### ISSUE THREAD

**Issue by garysassano** [lllyasviel/Fooocus#1001]
**Describe the problem**
Whenever I attempt to utilize the advanced FaceSwap feature within the Image Prompt tab, it consistently causes the Colab notebook to crash.

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

**Comment by tbuyle** [comment]
Try changing the last line of the colab with :

!python entry_with_update.py --share --preset --always-high-vram --all-in-fp16

See also https://github.com/lllyasviel/Fooocus/issues/1377

**Comment by mashb1t** [comment]
see https://github.com/lllyasviel/Fooocus/issues/1377#issuecomment-1853958551
