### ISSUE TITLE
The denoise strength adjustment does not work.

### ISSUE THREAD

**Issue by Woukim** [lllyasviel/Fooocus#1006]
**Describe the problem**
![image](https://github.com/lllyasviel/Fooocus/assets/138323639/5504e068-cf83-40a8-a542-8d2d504cbb7d)
The denoise strenght adjustment does not work.

**Full Console Log**
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 3.0
[Parameters] Seed = 2810170068671896994
[Fooocus] Downloading control models ...
[Fooocus] Loading control models ...
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] girl wearing light summed dress, passionate, intricate, elegant, highly detailed, extremely scientific, sharp focus, cool color, enhanced, very coherent, radiant colors, inspired, sweet, cute, symmetry, perfect, full artistic, positive, imagined, professional, attractive, delicate, beautiful, pretty, dramatic ambient background, thought, atmosphere, surreal, imposing, divine, cinematic
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Image processing ...
Detected 1 faces
Requested to load Resampler
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.45 seconds
Requested to load To_KV
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 5.77 seconds
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1152, 896)
Preparation time: 32.81 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 1713.307541847229

**Comment by mashb1t** [comment]
Tested with latest version of Fooocus and it is working, but setting Inpaint Denoising Strength = 0 does in fact cause a `ZeroDivisionError`.
Make sure you really did inpaint (draw a mask), if not it will use the default value 1.
