### ISSUE TITLE
Selecting a model other than xl will cause the program to freeze.

### ISSUE THREAD

**Issue by 812913329** [lllyasviel/Fooocus#1017]
Sometimes if you don't pay attention to the selection, the entire task will be stuck, causing the program to wait forever, and you must restart to solve it.

  raise NotImplementedError(error_message)
NotImplementedError: You have selected base model other than SDXL. This is not supported yet.
Total time: 4.08 seconds

**Comment by mashb1t** [comment]
Does not freeze anymore, see https://github.com/lllyasviel/Fooocus/issues/1392 and https://github.com/lllyasviel/Fooocus/commit/323af5667a4f1a168cc31864aa9883b52dfb38bf
