### ISSUE TITLE
【translators】add translators 

### ISSUE THREAD

**Issue by favouriter** [lllyasviel/Fooocus#1024]
```python
# update webui.py
import translators as ts
from functools import lru_cache

@lru_cache(maxsize=16, typed=False)
def translator2en(text):
    try:
        return ts.translate_text(text,to_language='en')
    except Exception as e:
        return text

def generate_clicked(*args):
    args = (translator2en(args[0]),*args[1:])

```

**Comment by xhoxye** [comment]
How do I use these codes?

**Comment by favouriter** [comment]
edit webui.py file
```python
import gradio as gr
import random
import os
import time
import shared
import modules.config
import fooocus_version
import modules.html
import modules.async_worker as worker
import modules.constants as constants
import modules.flags as flags
import modules.gradio_hijack as grh
import modules.advanced_parameters as advanced_parameters
import modules.style_sorter as style_sorter
import args_manager
import copy

from modules.sdxl_styles import legal_style_names
from modules.private_logger import get_current_html_path
from modules.ui_gradio_extensions import reload_javascript
from modules.auth import auth_enabled, check_auth
# Add these two libraries
import translators as ts
from functools import lru_cache

# Translate the text into English
@lru_cache(maxsize=16, typed=False)
def translator2en(text):
    try:
        return ts.translate_text(text, to_language='en')
    except Exception as e:
        return text

def generate_clicked(*args):
    args = (translator2en(args[0]),*args[1:]) # Add this line of code to translate the input text into English,
    import fcbh.model_management as model_management

    with model_management.interrupt_processing_mutex:
        model_management.interrupt_processing = False

    # outputs=[progress_html, progress_window, progress_gallery, gallery]
``

**Comment by xhoxye** [comment]
Using pytorch cross attention
E:\AI\Fooocus\Fooocus21791\python_embeded\lib\site-packages\translators\apis.py:152: UserWarning: Unable to find server backend.

  warnings.warn('Unable to find server backend.\n')
Please input your server region need to visit:
eg: [England, China, ...]
Refiner unloaded.
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra keys {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: E:\AI\Fooocus\Fooocus21791\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [E:\AI\Fooocus\Fooocus21791\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [E:\AI\Fooocus\Fooocus21791\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [E:\AI\Fooocus\Fooocus21791\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.41 seconds
'NoneType' object has no attribute 'local_url'

**Comment by favouriter** [comment]
Project ：[translators](https://github.com/UlionTse/translators)
This is a free online translation library, Currently, I am using it normally，There are 36 translation APIs available，I am in China and using Baidu Translate is relatively stable，

```python
import gradio as gr
import random
import os
import time
import shared
import modules.config
import fooocus_version
import modules.html
import modules.async_worker as worker
import modules.constants as constants
import modules.flags as flags
import modules.gradio_hijack as grh
import modules.advanced_parameters as advanced_parameters
import modules.style_sorter as style_sorter
import args_manager
import copy

from modules.sdxl_styles import legal_style_names
from modules.private_logger import get_current_html_path
from modules.ui_gradio_extensions import reload_javascript
from modules.auth import auth_enabled, check_auth
# Add these two libraries
import translators as ts
from functools import lru_cache

# Translate the text into English
@lru_cache(maxsize=16, typed=False)
def translator2en(text):
    try:
        # I am in China and using Baidu Translate is relatively stable
        return ts.translate_text(text,  translator='baidu', to_language='en')
    except Exception as e:
        return text

def generate_clicked(*args):
    args = (translator2en(args[0]),*args[1:]) # Add this line of code to translate the input text into English,
    import fcbh.model_management as model_management

    with model_management.interrupt_processing_mutex:
        model_management.interrupt_processing = False

    # outputs=[progress_html, progress_window, progress_gallery, gallery]

    execution_start_time = time.perf_counter()
    task = worker.AsyncTask(args=list(args))
    finished = False

    yield gr.update(visible=True, value=modules.html.make_progress_html(1, 'Waiting for task to start ...')), \
        gr.update(visible=True, value=None), \
        gr.update(visible=False, value=None), \
        gr.update(visible=False)

    worker.async_tasks.append(task)

    while not finished:
        time.sleep(0.01)
        if len(task.yields) > 0:
            flag, product = task.yields.pop(0)
            if flag == 'preview':

                # help bad internet connection by skipping duplicated preview
                if len(task.yields) > 0:  # if we have the next item
                    if task.yields[0][0] == 'preview':   # if the next item is also a preview
                        # print('Skipped one preview for better internet connection.')
                        continue

                percentage, title, image = product
                yield gr.update(visible=True, value=modules.html.make_progress_html(percentage, title)), \
                    gr.update(visible=True, value=image) if image is not None else gr.update(), \
                    gr.update(), \
                    gr.update(visible=False)
            if flag == 'results':
                yield gr.update(visible=True), \
                    gr.update(visible=True), \
                    gr.update(visible=True, value=product), \
                    gr.update(visible=False)
            if flag == 'finish':
                yield gr.update(visible=False), \
                    gr.update(visible=False), \
                    gr.update(visible=False), \
                    gr.update(visible=True, value=product)
                finished = True

    execution_time = time.perf_counter() - execution_start_time
    print(f'Total time: {execution_time:.2f} seconds')
    return
```

**Comment by xhoxye** [comment]
我也在国内，它是否要安装什么环境？
# Add these two libraries
import translators as ts
from functools import lru_cache
这两个库不需要安装吗

**Comment by favouriter** [comment]
pip install --upgrade translators
第一个需要安装，第二个不需要

**Comment by xhoxye** [comment]
非常感谢，在安装translators库之后，终于可以使用了。
不知道这个联网翻译插口，有什么数量次数的限制没有？

**Comment by favouriter** [comment]
个人免费使用应该没问题，限制使用频率，我们这种项目每秒还不到一次，@lru_cache(maxsize=16, typed=False)注解缓存最近16条翻译内容，maxsize也可以自己调整，重复生成也不会触发翻译API

**Comment by favouriter** [comment]
translator2en同时也考虑到翻译出异常的问题，翻译失败就返回原文

**Comment by xhoxye** [comment]
Token indices sequence length is longer than the specified maximum sequence length for this model (143 > 77). Running this sequence through the model will result in indexing errors
句子的长度不能太长。

**Comment by favouriter** [comment]
我刚才测试了一下百度翻译，ts.translate_text(text,  translator='baidu', to_language='en')，输入内容超过500个汉字，也能成果翻译，可以尝试以下不同的翻译服务

**Comment by xhoxye** [comment]
的确个人免费使用，还勉强可以，合并到main里用的人多了问题会更多。
目前我使用中发现的一些小的问题，比如：
单次超过长度，或其他原因，出错后的处理，翻译服务的切换处理
中英文混编的处理，因为一些lora有触发词

**Comment by metercai** [comment]
这个场景在线接口不太合适，还是离线模型的自翻译比较好控制。

**Comment by xhoxye** [comment]
如果要合并，还得考虑其他语种，不然没用，最好是通过选项来设置切换，包括切换语种，切换翻译引擎，切换在线和离线模型。
If you want to merge, you have to consider other languages, otherwise it is useless,
It is best to set up the switch through the options, including switching languages, switching translation engines, and switching online and offline models.

**Comment by favouriter** [comment]
这个项目让我体验到比stable-diffusion-webui更简洁、轻量，考虑到离线模型会占用GPU显存资源，所以我才用在线翻译，可以考虑完善翻译功能，我想到了几个方案以供参考
1、这个项目有个启动参数：language，如果指定语言可以进行翻译
2、单独指定一个translate启动参数
3、界面设置加上翻译选项，如果选择“无”则不进行在线翻译，如果选择翻译服务名称，调用相应的翻译服务，ts.translate_text(text, translator=service_name, to_language='en')

**Comment by xhoxye** [comment]
更简洁、轻量，离线都是这个项目的宗旨，但在翻译这里可能有点冲突。
但我还是倾向通过选项进行设置，当然能设置默认语言更好。
Being more concise, lightweight, and offline are all part of this project, but it can be a bit of a conflict when it comes to translation.
But I still prefer to set it through the options, of course it would be better to set the default language

**Comment by favouriter** [comment]
可以，无论怎么抉择，我都支持你，感谢你的无私贡献

**Comment by favouriter** [comment]
这个项目已经支持国际化语言，界面支持多语言，但是输入内容不支持，一个平面设计师第一次看到中文界面的系统，他肯定认为这个系统支持中文，如果一个系统界面支持中文，但是输入描述不支持中文，这个产品设计非常反人类，我认为多语言问题要么不做，要么做彻底，像其他在线版AI作图一样，不要让使用者有过多的思考及操作，傻瓜式的拿来即用，让更多国家和地区的人员都能通过自己掌握的自然语言生成图片，况且在启动参数加上可选项，依然可以保持界面的简洁

**Comment by favouriter** [comment]
如果输入支持翻译，那么这个项目将简单到会用键盘就行

**Comment by Phrixus2023** [comment]
> 这个项目已经支持国际化语言，界面支持多语言，但是输入内容不支持，一个平面设计师第一次看到中文界面的系统，他肯定认为这个系统支持中文，如果一个系统界面支持中文，但是输入描述不支持中文，这个产品设计非常反人类，我认为多语言问题要么不做，要么做彻底，像其他在线版AI作图一样，不要让使用者有过多的思考及操作，傻瓜式的拿来即用，让更多国家和地区的人员都能通过自己掌握的自然语言生成图片，况且在复用国际化启动参数，依然可以保持界面的简洁性

目前方案就2个，一个是使用翻译大模型，如果是这样其实对使用者的硬件需求又提升了，第二个就是使用在线翻译，但是谁能扛得住那么大的翻译需求呢?费用谁来出呢？如果这两个必要问题解决了，那么翻译问题就都不是问题，更何况翻译还有翻译错误的问题，比如试过配合通配符使用：一顶_color_帽子，翻译很容易把帽子识别为复数，那就会导致出图错误，还有输入全身翻译却给的是另一个答案，反正这事不是单方面想的那么简单，需要统筹考虑，但是可以确定的是目前精准度最高的提示词语言就是英语。

**Comment by favouriter** [comment]
> > 这个项目已经支持国际化语言，界面支持多语言，但是输入内容不支持，一个平面设计师第一次看到中文界面的系统，他肯定认为这个系统支持中文，如果一个系统界面支持中文，但是输入描述不支持中文，这个产品设计非常反人类，我认为多语言问题要么不做，要么做彻底，像其他在线版AI作图一样，不要让使用者有过多的思考及操作，傻瓜式的拿来即用，让更多国家和地区的人员都能通过自己掌握的自然语言生成图片，况且在复用国际化启动参数，依然可以保持界面的简洁性
> 
> 目前方案就2个，一个是使用翻译大模型，如果是这样其实对使用者的硬件需求又提升了，第二个就是使用在线翻译，但是谁能扛得住那么大的翻译需求呢?费用谁来出呢？如果这两个必要问题解决了，那么翻译问题就都不是问题，更何况翻译还有翻译错误的问题，比如试过配合通配符使用：一顶_color_帽子，翻译很容易把帽子识别为复数，那就会导致出图错误，还有输入全身翻译却给的是另一个答案，反正这事不是单方面想的那么简单，需要统筹考虑，但是可以确定的是目前精准度最高的提示词语言就是英语。

对很多设计师而言，能翻译已经精准很多了，这个翻译库是免费的，退一步讲，如果翻译不精准也可以直接输入英文原文，这种情况翻译工具给的也是原文，翻译失败返回的也是原文，精通提示词的设计师不影响，小白体验也有所提升，如果感觉不是很精准，请输入英文提示词，高手使用英文提示词，小白简单到会用键盘就行，这样可以接纳更多的新手，也可以让更多的新手了解这个项目并循循渐进的学习精通这个项目

**Comment by Phrixus2023** [comment]
> > > 这个项目已经支持国际化语言，界面支持多语言，但是输入内容不支持，一个平面设计师第一次看到中文界面的系统，他肯定认为这个系统支持中文，如果一个系统界面支持中文，但是输入描述不支持中文，这个产品设计非常反人类，我认为多语言问题要么不做，要么做彻底，像其他在线版AI作图一样，不要让使用者有过多的思考及操作，傻瓜式的拿来即用，让更多国家和地区的人员都能通过自己掌握的自然语言生成图片，况且在复用国际化启动参数，依然可以保持界面的简洁性
> > 
> > 
> > 目前方案就2个，一个是使用翻译大模型，如果是这样其实对使用者的硬件需求又提升了，第二个就是使用在线翻译，但是谁能扛得住那么大的翻译需求呢?费用谁来出呢？如果这两个必要问题解决了，那么翻译问题就都不是问题，更何况翻译还有翻译错误的问题，比如试过配合通配符使用：一顶_color_帽子，翻译很容易把帽子识别为复数，那就会导致出图错误，还有输入全身翻译却给的是另一个答案，反正这事不是单方面想的那么简单，需要统筹考虑，但是可以确定的是目前精准度最高的提示词语言就是英语。
> 
> 对很多设计师而言，能翻译已经精准很多了，这个翻译库是免费的，退一步讲，如果翻译不精准也可以直接输入英文原文，这种情况翻译工具给的也是原文，翻译失败返回的也是原文，精通提示词的设计师不影响，小白体验也有所提升，如果感觉不是很精准，请输入英文提示词，高手使用英文提示词，小白简单到会用键盘就行，这样可以接纳更多的新手，也可以让更多的新手了解这个项目并循循渐进的学习精通这个项目

嗨，看作者决断吧，我其实就是用的自己的翻译接口，也共享给了别人，我亲眼看到对方在使用过程中在翻译不准确的时候自然忽略掉可能是翻译的问题，将问题归结为是出图不够好的问题，这个就是属于技术提供和使用者的意识和认知差异，所看作者怎么考虑吧，我自己使用翻译接口情况下能解决八成左右的提示词问题，剩下1.9成就是翻译不准确的问题，最后0.1成是有的时候接口连通失败。但最大的问题就是使用超量就要开始花钱了。

**Comment by favouriter** [comment]
> > Fooocus是走简洁路线的，不是给用户增加过多的选项负担，如果不考虑这些我相信作者早就可以把一堆功能添加进去了，有的时候需要思考下，虽然我们很热心的建议增加这样那样的功能，但是最后跟stablediffusion又有什么区别呢？我觉得作者在维持项目核心理念这方面做得非常好，并不是一味的受建议引导，这需要非常清晰的权衡。
> 
> 简洁、易用、离线等等都是作者的理念，一些有冲突的选择，需要作者自己去平衡，所有才有了分支和审查。 简洁不等同于功能少，多一个功能有时是为了更易用。
> 
> 翻译不准确这个问题，就算你是英语母语使用者，一样也有专业术语，和普通用语描述不准确的问题， 所以我才说最好是有选项设置，让用户知道自己在做什么， 如果翻译只在后台，简洁易用到让用户无感，可能会出现你说的情况“在使用过程中在翻译不准确的时候自然忽略掉可能是翻译的问题，将问题归结为是出图不够好的问题，”以为模型原生能理解中文。 所以我个人认为有几个重点： 1、让用户知道他在翻译 2、让用户知道翻译是否生效（控制台打印信息是其中一种方式） 3、让用户可以选择使用哪个翻译引擎，包括不同的在线翻译引擎和在线或离线的（all in one我认为比较完美的一种，但可能对fooocus来说太过繁杂） 4、或者程序能在翻译接口出错时顺滑的自动切换到让用户无感

这个思虑比较周期

**Comment by Phrixus2023** [comment]
其实看看stability发布了日语版的sdxl大模型，说不定哪天就发布了中文版sdxl大模型，一切都会变得越来越简便

**Comment by favouriter** [comment]
> 其实看看stability发布了日语版的sdxl大模型，说不定哪天就发布了中文版sdxl大模型，一切都会变得越来越简便

也有可能变得复杂，使用不同的模型，输入不同的语言，很难记住哪些模型应该使用哪些语言，这样的话翻译更有必要，创建一个字典，记录模型对应的输入语言，输入任何语言翻译成模型匹配的语言

**Comment by ffdown** [comment]
вот Вам человек сделал рабочий переводчик без всяких там танцев с бубнами! [https://github.com/AlekPet/Fooocus_Extensions_AlekPet](https://github.com/AlekPet/Fooocus_Extensions_AlekPet)

**Comment by favouriter** [comment]
> вот Вам человек сделал рабочий переводчик без всяких там танцев с бубнами!https://github.com/AlekPet/Fooocus_Extensions_AlekPet

👏👏👏

**Comment by mashb1t** [comment]
Duplicate of https://github.com/lllyasviel/Fooocus/issues/983, implemented in https://github.com/lllyasviel/Fooocus/pull/1039
