### ISSUE TITLE
[FEATURE REQUEST] Activation text for LoRAs

### ISSUE THREAD

**Issue by pralium444** [lllyasviel/Fooocus#1026]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the idea you'd like**
A simple field appears when i select the lora, i fill the field with the activation text, it stores it somewhere...and everytime i choose this lora, the activation text is automatically pasted in positive prompt

nice UI ! thanks for making it
Love

**Comment by mashb1t** [comment]
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1476, continuing there.
