### ISSUE TITLE
Is there a way to integrate and use the LCM mode

### ISSUE THREAD

**Issue by libai-lab** [lllyasviel/Fooocus#1028]
Is there a way to integrate and use the LCM model? It can be used on the CPU, and it only takes a few minutes for me to generate images. If it is on the GPU, it only takes less than 2 seconds. If your model is relatively streamlined, it should be faster. Is there a way to integrate it

**Comment by kubilaykilinc** [comment]
Actually Fooocus has LCM

version 2.1.799
Added 'Extreme Speed' performance mode (based on LCM). The previous complicated settings are not needed now.

version 2.1.798
added lcm scheduler - LCM may need to set both sampler and scheduler to "lcm". Other than that, see the description in 2.1.782 logs.

https://github.com/lllyasviel/Fooocus/blob/main/update_log.md

**Comment by selim-yildirim** [comment]
Hello, how can I update?

**Comment by mashb1t** [comment]
@selim-yildirim Fooocus should update automatically when starting it with entry_with_update.py. If this doesn't work you may have to pull the git repository manually by executing `git pull` in your Fooocus folder or set it up from scratch again using one of the available methods described in https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#download.
