### ISSUE TITLE
could not connect to display【ubuntu 22.04 】

### ISSUE THREAD

**Issue by wangmingjunabc** [lllyasviel/Fooocus#103]
when generating a picture, met following errror:

/root/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
  0%|                                                                                                                                  | 0/30 [00:00<?, ?it/s]/root/anaconda3/envs/fooocus/lib/python3.10/site-packages/torchsde/_brownian/brownian_interval.py:594: UserWarning: Should have tb<=t1 but got tb=14.614643096923828 and t1=14.614643.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
  3%|████                                                                                                                      | 1/30 [00:03<01:42,  3.55s/it]qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/root/anaconda3/envs/fooocus/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

**Comment by mashb1t** [comment]
We haven't experienced this kind of error since quite a while now. Please try again with the latest version of Fooocus and feel free to reopen if still relevant.
