### ISSUE TITLE
[Feature Request] Add support for the increasingly popular Stable Video Diffusion (SVD) models.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [lllyasviel/Fooocus#1031]
As the title says; Add support for the increasingly popular Stable Video Diffusion (SVD) models.

**Comment by mashb1t** [comment]
Currently Fooocus is a tool handling only SDXL, not even SD 1.5 or 2.1. I am not sure if this is on the agenda, but let's see.

**Comment by Fenfel** [comment]
I'd be very happy with that given Fooocus' general approach to performance quality. It would be interesting to see a gen-2 analog that would come close to its upscaling and interpolation quality
