### ISSUE TITLE
Missing config.json file ,again

### ISSUE THREAD

**Issue by 2631792752** [lllyasviel/Fooocus#1042]
> I had the same issue as I'm using a symlink to the models folder (from a comfy install) - long story short a git pull didn't correctly updated the models folder so I was missing all the new files added to it. Look under prompt_expansion/fooocus_expansion in this repository for the missing files.

I have encountered almost the same problem. I used a symbolic link to point to a model in another hard drive that is different from Focus, which makes it unable to work. Even if using a separate path to load foocus_ Expansion can also lead to such errors.How can I solve this problem

_Originally posted by @2631792752 in https://github.com/lllyasviel/Fooocus/issues/341#issuecomment-1826726292_

**Comment by VisualFox** [comment]
I'm probably a little late to reply - the way I solved it: I made a little script that:
a) delete the symbolic link
b) run git pull
c) use rsync or similar to copy the missing files from the repository to where I actually store my models
d) recreate the symbolic link

I hope that will help

I'm actually using this script for other application, such as confyui as the same issue can happen (added files in the models folder).
