### ISSUE TITLE
Request a solution to the problem of the sharpness of landscape pictures

### ISSUE THREAD

**Issue by lijie5555698** [lllyasviel/Fooocus#1048]
问题已经解决 请求删除帖子 Problem solved. Request to delete post.

**Comment by lijie5555698** [comment]
![2023-11-27_18-55-57_5552](https://github.com/lllyasviel/Fooocus/assets/133008437/d532736a-f8a7-40ba-94ec-e0de4059b39f)
![3333](https://github.com/lllyasviel/Fooocus/assets/133008437/0ebe707e-73bd-438a-9269-f99a3bd3032d)
My computer configuration and video card 4060TI 16g

**Comment by lijie5555698** [comment]
![2023-11-28_14-53-14_8401](https://github.com/lllyasviel/Fooocus/assets/133008437/8e264b27-a62d-4ab4-9f5e-bc54650f9bae)
![2023-11-28_14-54-37_8617](https://github.com/lllyasviel/Fooocus/assets/133008437/cecd3fa0-4d65-4b5c-a8d9-3aece2029f01)
![2023-11-28_15-42-57_1542](https://github.com/lllyasviel/Fooocus/assets/133008437/c3da818e-53f8-4721-9ff2-c6fa5ee1a91f)
This is an image generated by an older version. Can you tell me how to get to this level of color, saturation in the new version. The new version is very powerful. But it has lost clarity and saturation. I'd like to know how to do it. Thank you. Love you

**Comment by xhoxye** [comment]
It may be started by running the old preset.
`    .\python_embeded\python.exe -s Fooocus\launch.py --language cn --theme dark --preset sai
    pause`
