### ISSUE TITLE
RTX 2060 CUDA problem after recent update

### ISSUE THREAD

**Issue by AFOLcast** [lllyasviel/Fooocus#1051]
**Describe the problem**
Everything was fine. Then I didn't use Foocus for about a week. Since I updated Tuesday or Wednesday of last week, I either get timeout errors or it never finishes loading Postitive Prompt #1. This is the most recent run.

MSI Creator 15, Windows 11
Nvidia RTX 2060
I run AfterBurner. I've tried with and without, same problems.

Boy, I've begun to count on Fooocus as my main machine for images. I hope someone can help.

D:\Foocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset anime
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'anime']
Loaded preset: D:\Foocus\Fooocus\presets\anime.json
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 6144 MB, total RAM 16200 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 2060 : native
VAE dtype: torch.float32
Using xformers cross attention
model_type EPS
adm 0
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra keys {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Refiner model loaded: D:\Foocus\Fooocus\models\checkpoints\DreamShaper_8_pruned.safetensors
model_type EPS
adm 2816
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra keys {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: D:\Foocus\Fooocus\models\checkpoints\bluePencilXL_v050.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.5], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [D:\Foocus\Fooocus\models\checkpoints\bluePencilXL_v050.safetensors].
Loaded LoRA [D:\Foocus\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [D:\Foocus\Fooocus\models\checkpoints\bluePencilXL_v050.safetensors] with 788 keys at weight 0.5.
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.5], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [D:\Foocus\Fooocus\models\checkpoints\DreamShaper_8_pruned.safetensors].
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 1.68 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
Enter LCM mode.
[Fooocus] Downloading LCM components ...
Refiner disabled in LCM mode.
[Parameters] Adaptive CFG = 1.0
[Parameters] Sharpness = 0.0
[Parameters] ADM Scale = 1.0 : 1.0 : 0.0
[Parameters] CFG = 1.0
[Parameters] Seed = 8277140641892079793
[Parameters] Sampler = lcm - lcm
[Parameters] Steps = 8 - 8
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.5], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0], ('sdxl_lcm_lora.safetensors', 1.0)] for model [D:\Foocus\Fooocus\models\checkpoints\bluePencilXL_v050.safetensors].
Loaded LoRA [D:\Foocus\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [D:\Foocus\Fooocus\models\checkpoints\bluePencilXL_v050.safetensors] with 788 keys at weight 0.5.
Loaded LoRA [D:\Foocus\Fooocus\models\loras\sdxl_lcm_lora.safetensors] for UNet [D:\Foocus\Fooocus\models\checkpoints\bluePencilXL_v050.safetensors] with 788 keys at weight 1.0.
Requested to load SDXLClipModel
Loading 1 new model
unload clone 1
[Fooocus Model Management] Moving model(s) has taken 2.21 seconds
[Fooocus] Processing prompts ...
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.19 seconds
Traceback (most recent call last):
  File "D:\Foocus\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "D:\Foocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Foocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Foocus\Fooocus\modules\async_worker.py", line 413, in handler
    t['c'] = pipeline.clip_encode(texts=t['positive'], pool_top_k=t['positive_top_k'])
  File "D:\Foocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Foocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Foocus\Fooocus\modules\default_pipeline.py", line 190, in clip_encode
    cond, pooled = clip_encode_single(final_clip, text)
  File "D:\Foocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Foocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Foocus\Fooocus\modules\default_pipeline.py", line 148, in clip_encode_single
    result = clip.encode_from_tokens(tokens, return_pooled=True)
  File "D:\Foocus\Fooocus\backend\headless\fcbh\sd.py", line 131, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
  File "D:\Foocus\Fooocus\backend\headless\fcbh\sdxl_clip.py", line 54, in encode_token_weights
    g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
  File "D:\Foocus\Fooocus\modules\patch.py", line 278, in encode_token_weights_patched_with_a1111_method
    out, pooled = self.encode(to_encode)
  File "D:\Foocus\Fooocus\backend\headless\fcbh\sd1_clip.py", line 211, in encode
    return self(tokens)
  File "D:\Foocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Foocus\Fooocus\backend\headless\fcbh\sd1_clip.py", line 189, in forward
    outputs = self.transformer(input_ids=tokens, attention_mask=attention_mask, output_hidden_states=self.layer=="hidden")
  File "D:\Foocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Foocus\python_embeded\lib\site-packages\transformers\models\clip\modeling_clip.py", line 822, in forward
    return self.text_model(
  File "D:\Foocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Foocus\python_embeded\lib\site-packages\transformers\models\clip\modeling_clip.py", line 757, in forward
    input_ids.to(dtype=torch.int, device=last_hidden_state.device).argmax(dim=-1),
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Requested to load GPT2LMHeadModel
Loading 1 new model
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Foocus\Fooocus\modules\async_worker.py", line 809, in worker
    pipeline.prepare_text_encoder(async_call=True)
  File "D:\Foocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Foocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Foocus\Fooocus\modules\default_pipeline.py", line 211, in prepare_text_encoder
    fcbh.model_management.load_models_gpu([final_clip.patcher, final_expansion.patcher])
  File "D:\Foocus\Fooocus\modules\patch.py", line 494, in patched_load_models_gpu
    y = fcbh.model_management.load_models_gpu_origin(*args, **kwargs)
  File "D:\Foocus\Fooocus\backend\headless\fcbh\model_management.py", line 388, in load_models_gpu
    free_memory(total_memory_required[device] * 1.3 + extra_mem, device, models_already_loaded)
  File "D:\Foocus\Fooocus\backend\headless\fcbh\model_management.py", line 348, in free_memory
    mem_free_total, mem_free_torch = get_free_memory(device, torch_free_too=True)
  File "D:\Foocus\Fooocus\backend\headless\fcbh\model_management.py", line 592, in get_free_memory
    mem_free_cuda, _ = torch.cuda.mem_get_info(dev)
  File "D:\Foocus\python_embeded\lib\site-packages\torch\cuda\memory.py", line 618, in mem_get_info
Total time: 319.75 seconds
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by eikaramba** [comment]
same error on nvidia 3090, windows 10 x64, latest nvidia driver, cuda 12 installed.

**Comment by stubkan** [comment]
Try rolling back to version 2.1.703

Which is this commit https://github.com/lllyasviel/Fooocus/tree/9660daff94b4d0f282567b96b3d387817818a4b3

Recent versions have several issues with memory management.

**Comment by AFOLcast** [comment]
I've tried to find out how to launch without updating. I made this solution work once. But next time I launched I was screwed. How do you modify the .bat file?

**Comment by stubkan** [comment]
entry_with_update.py is updating like the file says, so dont run that

try just starting launch.py, though if you are starting it manually, you might need to load the foooocus_env venv first

I dont have .bat on my system only .sh so I cannot see whats in that

**Comment by AFOLcast** [comment]
Thanks! You've given the best help so far. I tried installing the patch at the link above. It worked for a few days, then there was an update. Stopped working.

Today I tried installing the patch again. Didn't work. I tried changing the .bat file to launch.py, but it failed.

Here is the original .bat file. Maybe you can see how we can change it to stop updating?


.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset anime %*
pause

**Comment by AFOLcast** [comment]
Here's the script for entry_with_update

import os
import sys


root = os.path.dirname(os.path.abspath(__file__))
sys.path.append(root)
os.chdir(root)


try:
    import pygit2
    pygit2.option(pygit2.GIT_OPT_SET_OWNER_VALIDATION, 0)

    repo = pygit2.Repository(os.path.abspath(os.path.dirname(__file__)))

    branch_name = repo.head.shorthand

    remote_name = 'origin'
    remote = repo.remotes[remote_name]

    remote.fetch()

    local_branch_ref = f'refs/heads/{branch_name}'
    local_branch = repo.lookup_reference(local_branch_ref)

    remote_reference = f'refs/remotes/{remote_name}/{branch_name}'
    remote_commit = repo.revparse_single(remote_reference)

    merge_result, _ = repo.merge_analysis(remote_commit.id)

    if merge_result & pygit2.GIT_MERGE_ANALYSIS_UP_TO_DATE:
        print("Already up-to-date")
    elif merge_result & pygit2.GIT_MERGE_ANALYSIS_FASTFORWARD:
        local_branch.set_target(remote_commit.id)
        repo.head.set_target(remote_commit.id)
        repo.checkout_tree(repo.get(remote_commit.id))
        repo.reset(local_branch.target, pygit2.GIT_RESET_HARD)
        print("Fast-forward merge")
    elif merge_result & pygit2.GIT_MERGE_ANALYSIS_NORMAL:
        print("Update failed - Did you modified any file?")
except Exception as e:
    print('Update failed.')
    print(str(e))

print('Update succeeded.')
from launch import *

**Comment by stubkan** [comment]
dont use those files

just python.exe launch.py

**Comment by acvcleitao** [comment]
+1

**Comment by ShubhamBhanot29** [comment]
@stubkan @AFOLcast Hey would you not mind telling me , how to get .zip file for window for that 2.1.703 version?
I dont know how to get older zip for windows because atleast i am getting one error in window after showing half blurred image , where as linux i am getting many weird errors

**Comment by AFOLcast** [comment]
It's unfortunate comments disappeared. I'm really lost now. I've tried everything to get Fooocus to run on my machine like it used to. The last time I got results was on 11/28. I used the old xtransformers as suggested. Here's the log:

2023-11-28_15-01-51_1716.png

Prompt:

Negative Prompt: unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label

Fooocus V2 Expansion:

Styles: ['Fooocus V2', 'Fooocus Photograph', 'Fooocus Negative'], Performance: Quality

Resolution: (3536, 1984), Sharpness: 3

Guidance Scale: 3, ADM Guidance: (1.5, 0.8, 0.3)

Base Model: juggernautXL_version6Rundiffusion.safetensors, Refiner Model: None

Refiner Switch: 0.9, Sampler: dpmpp_2m_sde_gpu

Scheduler: karras, Seed: 164706322227898777

LoRA [sd_xl_offset_example-lora_1.0.safetensors] weight: 0.1, LoRA [add-detail-xl.safetensors] weight: 0.25

LoRA [xl_more_art-full_v1.safetensors] weight: 0.25,



2023-11-28_14-47-53_8129.png

Prompt:

Negative Prompt: unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label

Fooocus V2 Expansion:

Styles: ['Fooocus V2', 'Fooocus Photograph', 'Fooocus Negative'], Performance: Quality

Resolution: (3536, 1984), Sharpness: 3

Guidance Scale: 3, ADM Guidance: (1.5, 0.8, 0.3)

Base Model: juggernautXL_version6Rundiffusion.safetensors, Refiner Model: None

Refiner Switch: 0.9, Sampler: dpmpp_2m_sde_gpu

Scheduler: karras, Seed: 164706322227898776

LoRA [sd_xl_offset_example-lora_1.0.safetensors] weight: 0.1, LoRA [add-detail-xl.safetensors] weight: 0.25

LoRA [xl_more_art-full_v1.safetensors] weight: 0.25,



2023-11-28_14-32-58_6960.png

Prompt:

Negative Prompt: unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label

Fooocus V2 Expansion:

Styles: ['Fooocus V2', 'Fooocus Photograph', 'Fooocus Negative'], Performance: Quality

Resolution: (3536, 1984), Sharpness: 3

Guidance Scale: 3, ADM Guidance: (1.5, 0.8, 0.3)

Base Model: juggernautXL_version6Rundiffusion.safetensors, Refiner Model: DreamShaper_8_pruned.safetensors

Refiner Switch: 0.9, Sampler: dpmpp_2m_sde_gpu

Scheduler: karras, Seed: 6203301018344342760

LoRA [sd_xl_offset_example-lora_1.0.safetensors] weight: 0.25, LoRA [add-detail-xl.safetensors] weight: 0.25



2023-11-28_14-22-26_6241.png

Prompt:

Negative Prompt: unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label

Fooocus V2 Expansion:

Styles: ['Fooocus V2', 'Fooocus Photograph', 'Fooocus Negative'], Performance: Quality

Resolution: (3536, 1984), Sharpness: 3

Guidance Scale: 3, ADM Guidance: (1.5, 0.8, 0.3)

Base Model: juggernautXL_version6Rundiffusion.safetensors, Refiner Model: DreamShaper_8_pruned.safetensors

Refiner Switch: 0.9, Sampler: dpmpp_2m_sde_gpu

Scheduler: karras, Seed: 6203301018344342759

LoRA [sd_xl_offset_example-lora_1.0.safetensors] weight: 0.25, LoRA [add-detail-xl.safetensors] weight: 0.25



2023-11-28_14-06-08_1742.png

Prompt:

Negative Prompt: unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label

Fooocus V2 Expansion:

Styles: ['Fooocus V2', 'Fooocus Photograph', 'Fooocus Negative'], Performance: Speed

Resolution: (3536, 1984), Sharpness: 2

Guidance Scale: 3, ADM Guidance: (1.5, 0.8, 0.3)

Base Model: juggernautXL_version6Rundiffusion.safetensors, Refiner Model: DreamShaper_8_pruned.safetensors

Refiner Switch: 0.8, Sampler: dpmpp_2m_sde_gpu

Scheduler: karras, Seed: 6428068312079717363

LoRA [sd_xl_offset_example-lora_1.0.safetensors] weight: 0.25, LoRA [add-detail-xl.safetensors] weight: 0.5



2023-11-28_14-00-28_8468.png

Prompt:

Negative Prompt: unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label

Fooocus V2 Expansion:

Styles: ['Fooocus V2', 'Fooocus Photograph', 'Fooocus Negative'], Performance: Speed

Resolution: (3536, 1984), Sharpness: 2

Guidance Scale: 3, ADM Guidance: (1.5, 0.8, 0.3)

Base Model: juggernautXL_version6Rundiffusion.safetensors, Refiner Model: DreamShaper_8_pruned.safetensors

Refiner Switch: 0.8, Sampler: dpmpp_2m_sde_gpu

Scheduler: karras, Seed: 6428068312079717362

LoRA [sd_xl_offset_example-lora_1.0.safetensors] weight: 0.25, LoRA [add-detail-xl.safetensors] weight: 0.5



2023-11-28_13-42-45_7527.png

Prompt:

Negative Prompt: unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label

Fooocus V2 Expansion:

Styles: ['Fooocus V2', 'Fooocus Photograph', 'Fooocus Negative'], Performance: Speed

Resolution: (1768, 992), Sharpness: 2

Guidance Scale: 3, ADM Guidance: (1.5, 0.8, 0.3)

Base Model: realisticStockPhoto_v10.safetensors, Refiner Model: None

Refiner Switch: 0.5, Sampler: dpmpp_2m_sde_gpu

Scheduler: karras, Seed: 227090093299087744

LoRA [SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] weight: 0.25,



2023-11-28_13-22-40_2118.png

Prompt:

Negative Prompt: (embedding:unaestheticXLv31:0.8), low quality, watermark

Fooocus V2 Expansion:

Styles: ['Fooocus V2', 'Fooocus Masterpiece', 'SAI Anime', 'SAI Digital Art', 'SAI Enhance', 'SAI Fantasy Art'], Performance: Extreme Speed

Resolution: (1768, 992), Sharpness: 0.0

Guidance Scale: 1.0, ADM Guidance: (1.0, 1.0, 0.0)

Base Model: bluePencilXL_v050.safetensors, Refiner Model: None

Refiner Switch: 1.0, Sampler: lcm

Scheduler: lcm, Seed: 3333355426078829622

LoRA [sd_xl_offset_example-lora_1.0.safetensors] weight: 0.5, LoRA [sdxl_lcm_lora.safetensors] weight: 1.0



Fooocus Log 2023-11-28 (private)

All images do not contain any hidden data.


Today I tried for the last time, I guess to do a clean install of 2.1.791. As has happened so far, it runs. Once. Then gets stuck in a number of places. Here's the log from today. IF ANYONE could help? I really depend on Fooocus... or at least did for a couple of months..


D:\Fooocus>.\python_embeded\python.exe -s Fooocus\launch.py --preset anime
[System ARGV] ['Fooocus\\launch.py', '--preset', 'anime']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.791
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total VRAM 6144 MB, total RAM 16200 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : native
VAE dtype: torch.float32
Using xformers cross attention
model_type EPS
adm 0
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
Visited extra keys: {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Refiner model loaded: D:\Fooocus\Fooocus\models\checkpoints\DreamShaper_8_pruned.safetensors
model_type EPS
adm 2816
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
Visited extra keys: {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: D:\Fooocus\Fooocus\models\checkpoints\bluePencilXL_v050.safetensors
Request to load LoRAs [('sd_xl_offset_example-lora_1.0.safetensors', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5)] for model [D:\Fooocus\Fooocus\models\checkpoints\bluePencilXL_v050.safetensors].
Loaded LoRA [D:\Fooocus\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for model [D:\Fooocus\Fooocus\models\checkpoints\bluePencilXL_v050.safetensors] with 788 keys at weight 0.5.
Request to load LoRAs [('sd_xl_offset_example-lora_1.0.safetensors', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5)] for model [D:\Fooocus\Fooocus\models\checkpoints\DreamShaper_8_pruned.safetensors].
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.92 seconds
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 7.0
[Parameters] Seed = 8772597745022207838
[Fooocus] Downloading upscale models ...
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 18 - 12
[Fooocus] Initializing ...
[Fooocus] Loading models ...
[Fooocus] Processing prompts ...
[Fooocus] Encoding positive #1 ...
Traceback (most recent call last):
  File "D:\Fooocus\Fooocus\modules\async_worker.py", line 668, in worker
    handler(task)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\Fooocus\modules\async_worker.py", line 351, in handler
    t['c'] = pipeline.clip_encode(texts=t['positive'], pool_top_k=t['positive_top_k'])
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\Fooocus\modules\default_pipeline.py", line 151, in clip_encode
    cond, pooled = clip_encode_single(final_clip, text)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\Fooocus\modules\default_pipeline.py", line 128, in clip_encode_single
    result = clip.encode_from_tokens(tokens, return_pooled=True)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\sd.py", line 133, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\sdxl_clip.py", line 54, in encode_token_weights
    g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
  File "D:\Fooocus\Fooocus\modules\patch.py", line 274, in encode_token_weights_patched_with_a1111_method
    out, pooled = self.encode(to_encode)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\sd1_clip.py", line 211, in encode
    return self(tokens)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\sd1_clip.py", line 189, in forward
    outputs = self.transformer(input_ids=tokens, attention_mask=attention_mask, output_hidden_states=self.layer=="hidden")
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\transformers\models\clip\modeling_clip.py", line 822, in forward
    return self.text_model(
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\transformers\models\clip\modeling_clip.py", line 757, in forward
    input_ids.to(dtype=torch.int, device=last_hidden_state.device).argmax(dim=-1),
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Fooocus\Fooocus\modules\async_worker.py", line 675, in worker
    pipeline.prepare_text_encoder(async_call=True)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\Fooocus\modules\default_pipeline.py", line 172, in prepare_text_encoder
    fcbh.model_management.load_models_gpu([final_clip.patcher, final_expansion.patcher])
  File "D:\Fooocus\Fooocus\modules\patch.py", line 444, in patched_load_models_gpu
    y = fcbh.model_management.load_models_gpu_origin(*args, **kwargs)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\model_management.py", line 372, in load_models_gpu
    free_memory(extra_mem, d, models_already_loaded)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\model_management.py", line 330, in free_memory
    if get_free_memory(device) > memory_required:
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\model_management.py", line 573, in get_free_memory
    mem_free_cuda, _ = torch.cuda.mem_get_info(dev)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\cuda\memory.py", line 618, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Total time: 898.90 seconds

**Comment by AFOLcast** [comment]
I have two open issues on this. Is there no help?
