### ISSUE TITLE
Web server

### ISSUE THREAD

**Issue by ItsNoted** [lllyasviel/Fooocus#1052]
Is there a way to make Fooocus run on a web server so I can access it anywhere on my network other than only localhost? My main pc is in the basement but I’d love to be able to generate images on my laptop upstairs remotely.

**Comment by MattLLLLL** [comment]
Right-click to open run.bat and select edit, add in python entry_with_update.py "--listen"

**Comment by ItsNoted** [comment]
> Right-click to open run.bat and select edit, add in ---> python entry_with_update.py --listen
> 
> And make sure the firewall is turned off

Worked well thank you!
