### ISSUE TITLE
Model order issues

### ISSUE THREAD

**Issue by beck-8** [lllyasviel/Fooocus#1055]
https://github.com/lllyasviel/Fooocus/blob/cca0ca704a713ab153938e78de6787609c723cad/modules/util.py#L167
Why did write that? This will result in a wrong order.
![image](https://github.com/lllyasviel/Fooocus/assets/34204218/a9006892-bfa2-4ecb-825d-0c262de3ff70)

**Comment by mashb1t** [comment]
You could have also just created the PR, but sb else did in the meantime ^^
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1618.
