### ISSUE TITLE
My VRAM mode: normal and high 

### ISSUE THREAD

**Issue by abomonov** [lllyasviel/Fooocus#1056]
Hi. I have a 6 gb vram being used to generate, but I have a rtx 3060 12 gb. How can i increase the generation speed? But when I change it and then start focus, It restore this file
 If lowvram_available and total_vram <= 4096:
        print("Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram")
        set_vram_to = VRAMState.LOW_VRAM

**Comment by mashb1t** [comment]
You can use `--always-high-vram` in your entrypoint (launch command / run.bat script / etc.), which prevents models from being offloaded to RAM, but you can not boost the performance more without sacrificing image quality.
Your GPU processing power is the limiting factor, not your VRAM.
