### ISSUE TITLE
Gradio duplication of images in system AppData folder  

### ISSUE THREAD

**Issue by sgfx** [lllyasviel/Fooocus#1057]
**Describe the problem**
I'm uncertain if it qualifies as a bug, but there's definitely an issue. Gradio seems to be copying every image  rendered into the AppData folder. Specifically, it goes to Local > Temp > gradio, and within that, it creates a new folder (named as a lot of random digits) for each image, then naming each image file simply as 'image.png'. Totally useless.

I discovered that this has resulted in more than 15GB of duplicate images on my system drive, which is problematic. I use a separate media drive to avoid cluttering my system drive with useless files.

**Comment by midareashi** [comment]
Gradio generates the temp folders and files for the gallery image in base.py. The output image created by Fooocus is in private_logger.py which also generates the log.html file. If you want to turn off the temp image (this will break the image in the gallery view) then you can update python_embeded\Lib\site-packages\gradio\components\base.py

```
    def pil_to_temp_file(self, img: _Image.Image, dir: str, format="png") -> str:
        bytes_data = processing_utils.encode_pil_to_bytes(img, format)
        temp_dir = Path(dir) / self.hash_bytes(bytes_data)
        #temp_dir.mkdir(exist_ok=True, parents=True)
        filename = str(temp_dir / f"image.{format}")
        #img.save(filename, pnginfo=processing_utils.get_pil_metadata(img))
        return filename
```

**Comment by midareashi** [comment]
Those are the images Gradio uses for the gallery update. There are different images saved by Fooocus when the log.html file generates. If you turn off those images you won't get any final images in Gradio. It would be nice if there was a cleanup step at startup that removed those images so the folder doesn't get too large. I found 6GB of images in mine when I first noticed.

**Comment by mashb1t** [comment]
Thank you for the hint, put on backlog.
You can already define a different path for temporary images, see https://github.com/lllyasviel/Fooocus/issues/1195.

**Comment by mashb1t** [comment]
closing in favor of https://github.com/lllyasviel/Fooocus/issues/1924
