### ISSUE TITLE
Switch preset without restarting the app

### ISSUE THREAD

**Issue by libersoft-org** [lllyasviel/Fooocus#1058]
Please add an option to switch preset in web UI without having to restart the app.

**Comment by metercai** [comment]
Switch preset can be through the topbar in this version: https://github.com/metercai/SimpleSDXL
![SimpleSDXL_en](https://github.com/lllyasviel/Fooocus/assets/5652458/7896d8df-09a3-437c-b0d0-4195e7074631)

**Comment by metercai** [comment]
This version is just an enhanced version of Fooocus, adding some features that lllyasviel didn't have time to or didn't pay attention to, fully compatible with it, and upgraded synchronously.

**Comment by metercai** [comment]
now，easily generate own preset based on the current configuration and parameters with SimpleSDXL.

**Comment by mashb1t** [comment]
Feature is ready for review in PR https://github.com/lllyasviel/Fooocus/pull/1570
