### ISSUE TITLE
Refiner Swap

### ISSUE THREAD

**Issue by kubilaykilinc** [lllyasviel/Fooocus#106]
** When i generate image i am getting this line :
100%|██████████████████████████████████████████████████████████████████████████████████| 60/60 [00:51<00:00,  1.16it/s]
 67%|██████████████████████████████████████████████████████▋                           | 40/60 [00:33<00:16,  1.21it/s]Refiner swapped.
 
 ** I am getting this error when i generate first image.
 -------------------------------------------------------------------------
 App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
E:\SD-AI\Focus\python_embeded\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
  0%|                                                                                           | 0/60 [00:00<?, ?it/s]E:\SD-AI\Focus\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py:594: UserWarning: Should have tb<=t1 but got tb=14.614643096923828 and t1=14.614643.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
 67%|██████████████████████████████████████████████████████▋                           | 40/60 [00:38<00:16,  1.21it/s]Refiner swapped.
 97%|███████████████████████████████████████████████████████████████████████████████▎  | 58/60 [00:55<00:01,  1.13it/s]E:\SD-AI\Focus\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py:585: UserWarning: Should have ta>=t0 but got ta=0.02916753850877285 and t0=0.029168.
  warnings.warn(f"Should have ta>=t0 but got ta={ta} and t0={self._start}.")
 ---------------------------------------------------------------------------
 
 ** I am choosing quality option, but images has poor quality and eye / face deformations.
 
 Windows 11 - 32 GB Ram - 12 GB Vram Nvidia
 I am using default SDXL base model and refiner
 sd_xl_base_1.0_0.9vae.safetensors
 sd_xl_refiner_1.0_0.9vae.safetensors

**Comment by kubilaykilinc** [comment]
I fixed. I am using :
sdXL_v10VAEFix.safetensors
and sdXL_v10RefinerVAEFix.safetensors as refiner
every image perfect and i am not getting any error.

**Comment by LittleTerry** [comment]
> I fixed. I am using : sdXL_v10VAEFix.safetensors and sdXL_v10RefinerVAEFix.safetensors as refiner every image perfect and i am not getting any error.

Hi, I have the same problem. Where are those two files?

**Comment by ultimatech-cn** [comment]
> I fixed. I am using : sdXL_v10VAEFix.safetensors and sdXL_v10RefinerVAEFix.safetensors as refiner every image perfect and i am not getting any error.

where did you download these two image?

**Comment by ultimatech-cn** [comment]
Finally，I found it at https://civitai.com/models/101055?modelVersionId=128080.
