### ISSUE TITLE
Add a custom resolution - width and height sliders

### ISSUE THREAD

**Issue by libersoft-org** [lllyasviel/Fooocus#1061]
Please add a possibility to choose a custom width and height of resolution - like 2 sliders.

Thank you.

**Comment by kubilaykilinc** [comment]
But it should be only on "advanced mode"

**Comment by libersoft-org** [comment]
> But it should be only on "advanced mode"

For me, preset tons of resolutions doesnt make much sense, it's much much better to set my own. Actually I don't like any of those preset. And Full HD+ resolutions are missing completely.

**Comment by cvinker** [comment]
This is already a feature, enable advanced mode and look for enable developer debug, then look for this:
![image](https://github.com/lllyasviel/Fooocus/assets/13070943/37221493-16a1-4753-991a-65ff9c0be301)

**Comment by xhoxye** [comment]
> > But it should be only on "advanced mode"但它应该只在“高级模式”上
> 
> For me, preset tons of resolutions doesnt make much sense, it's much much better to set my own. Actually I don't like any of those preset. And Full HD+ resolutions are missing completely.对我来说，预设大量的分辨率没有多大意义，最好自己设置。实际上，我不喜欢这些预设中的任何一个。并且完全缺少Full HD+分辨率。

In order to produce better images, understand SDXL's position encoding

**Comment by mashb1t** [comment]
also see discussion in https://github.com/lllyasviel/Fooocus/pull/1617
