### ISSUE TITLE
Where can i disable the prompt expansion feedback? I don't want it to show up in my backend.

### ISSUE THREAD

**Issue by rvdd1962** [lllyasviel/Fooocus#1066]
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] Christmas scene from the ratatouille movie, cook (bald head with beard wearing glasses) is smiling showing his white nice teeth, holding a plate of roasted turkey in his hands. High resolution, high detailed, ultra sharp, color photo, masterpiece in style of Pixar toon style, perfect composition, vivid colors, clear background, dynamic dramatic cinematic light, ambient
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
--
I can't find any setting to disable the prompt expansion. Can you give my direction why to disable it so the backend won't display it anymore? Thx

**Comment by lllyasviel** [comment]
you can turn off Fooocus V2 in Style

**Comment by JustinG4** [comment]
@lllyasviel if I turn off Fooocus V2 is prompt expansion the only thing I'll lose?

**Comment by SanderBouwhuis** [comment]
I'm curious about this too. The prompt expansion is very annoying.
