### ISSUE TITLE
Support for dpmpp_3m_sde_gpu sampler

### ISSUE THREAD

**Issue by MoonRide303** [lllyasviel/Fooocus#107]
I've noticed dpmpp_3m_sde_gpu sampler was recently added to ComfyUI. It looks like good alternative for dpmpp_2m_sde_gpu, and I wanted to check it out with Fooocus - so I ported it into Fooocus code base.

Sample outputs from `photography of a modern sports car` prompt below.

seed 0, dpmpp_2m_sde_gpu:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/154d7d4c-9d2b-4eb7-aa2d-803abed0d7a3)

seed 0, dpmpp_3m_sde_gpu:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/ac2fa9ba-f84a-405d-b5dd-c3309bab9694)

seed 1, dpmpp_2m_sde_gpu:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/e46d3209-e28e-4e4b-a7cb-e1a8193fcdd8)

seed 1, dpmpp_3m_sde_gpu:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/c958e552-9fb7-46a8-9cc5-6192e4ae56cf)

**Comment by MoonRide303** [comment]
@lllyasviel Could you please check out my pull request? I've also added non-GPU variants of the SDE 2M and SDE 3M samplers to pull request - they're interesting alternatives, and might be also useful for comparing outputs with A1111 web UI, or ComfyUI (A1111 currently supports only non-GPU samplers).

seed 0, dpmpp_2m_sde:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/8aff3ff8-0382-4078-bf3c-7f3448665cc5)

seed 0, dpmpp_3m_sde:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/3ef06fad-dd88-4503-af94-ee825c9338ee)

seed 1, dpmpp_2m_sde:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/f8876116-534b-4f08-962a-183ba63b0447)

seed 1, dpmpp_3m_sde:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/d2016669-33ff-4d2f-ba1f-3514b27b91c7)

**Comment by lllyasviel** [comment]
we will update dependency and check it in a monthly or half-monthly way. This will be looked at in the next dependency check.

**Comment by MoonRide303** [comment]
@lllyasviel It's not just dependency, but also few lines in Fooocus code - to make sampler selection available in the UI (in Advanced settings), and then pass it to the pipeline. Currently it can be merged cleanly, later on (with more commits on main) some conflicts might appear.

**Comment by Crazy-CYZ** [comment]
Does the default sampler still exist?

**Comment by MoonRide303** [comment]
@Crazy-CYZ yes, default sampler (dpmpp_2m_sde_gpu) is still there, and remains the default - I've put the selection UI in the Advanced settings section:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/1efb0bad-71b0-4c0b-aea6-08ae821131ab)

**Comment by lllyasviel** [comment]
Unfortunately, Fooocus will be a relatively managed project.
Everything in the advanced setting will (1) pair with comprehensive document to explain their effect and (2) be tested comprehensively with all other tricks combined and make sure that their quality is good enough even.
Because of these reasons, we are not likely to support arbitrary samplers.

**Comment by MoonRide303** [comment]
@lllyasviel They are the same SDE samplers family you already use (from ComfyUI repository). I don't see how "dpmpp_3m_sde_gpu" or "dpmpp_2m_sde" is arbitrary and low quality, and "dpmpp_2m_sde_gpu" from the same source is not - I tested it on multiple prompts (in Fooocus, so it included optimizations done here), and they look like viable high quality alternatives to me. 3M variants were recently added to A1111 (dev branch), too. Could you explain how you evaluated this, and why you consider "dpmpp_2m_sde_gpu" superior choice?

I really like the idea of integrated base + refiner sampler in Fooocus, and that you picked solid default settings that give pretty nice good output on average - that's good stuff. Making default interface understandable and usable by let's say 10yo kids - that's really good decision, too. But having to edit the code every time a bit more advanced prompter wants to see output from alternative sampler with comparable quality - that isn't really user friendly.

If your goal is Fooocus to be the tool ONLY for kids, and don't want to see basic settings like that even in advanced section, then I guess people like me will simply have to maintain their own forks, and work on those.

PS Another missing setting like that is number of steps, and CFG. Different base and LoRA models (and even prompts) will often have different optimal (allowing to generate best looking output) values of steps and CFG. I did a lot of tests like that in A1111 using X/Y/Z plots, and (sadly) hard-coding single sampler, CFG and step values doesn't allow you to automatically get best output for given prompt, model and LoRA combination.

**Comment by lllyasviel** [comment]
Thanks for the constructive considerations. We will re-evaluate their importance in the future, but we will be extremely careful about adding anything to the UI, even if they are in the most nested advanced tab.

**Comment by MoonRide303** [comment]
@lllyasviel I kinda understand your approach, too. For example A1111 - as powerful as it is - can be also intimidating and scary for people without prior SD knowledge, due to sheer amount of available options. Clean and fast SD interface where prompter can focus on prompting is a good idea - but for me, even just from prompter perspective stuff like steps / CFG / switch are essential - for example when you get almost perfect image, and all you need is a bit higher or lower CFG, or a few more (or less) steps to see what you really wanted.

That's kinda design decision, and you're right those should be taken carefully - so for now, I will just maintain those few extra settings (samplers, steps, cfg, full resolution list) on my own repository, as [moonride-main](https://github.com/MoonRide303/Fooocus/tree/moonride-main) branch).

Btw. I also separated Models and Advanced settings (it looked a bit weird to have both Tab and section of it named "Advanced"), so currently it looks like that on my fork:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/e5fe8b39-fd71-4c1c-b09d-80576496cb15)

**Comment by Crazy-CYZ** [comment]
How can I utilize your branch? When there are updates to "fooocus," will your branch also receive updates?

**Comment by MoonRide303** [comment]
@Crazy-CYZ You can simply `git clone https://github.com/MoonRide303/Fooocus.git` - I just changed default branch to `moonride-main` on my fork.

**Comment by barepixels** [comment]
I just did git clone.  Happy to see the option to save to PNG.  Got error  
ModuleNotFoundError: No module named 'comfy'

**Comment by MoonRide303** [comment]
@barepixels I am running latest version just fine, so I suppose it might be something related to checking out respositories (missing comfy repo), or mixing versions (I can see paths from vanilla Fooocus release). Try cloning into clean folder, and then just run "python launch.py".

Also in future if it's anything related to my fork (though I am not sure in this case - there are already some issues related to checking out here, like #148), then just report it to me via https://github.com/MoonRide303/Fooocus/issues.

**Comment by barepixels** [comment]
I found your proper instruction and it's all working.  thank you so much.  from now on will post feedback at right place https://github.com/MoonRide303/Fooocus/

**Comment by xiaoyoucheng** [comment]
> Thanks for the constructive considerations. We will re-evaluate their importance in the future, but we will be extremely careful about adding anything to the UI, even if they are in the most nested advanced tab.

Perhaps you can add parameters to the startup command to allow users who need more customized settings to enable more options by carrying parameters when starting. This way, a clean and simple interface can still be provided to general users.

**Comment by MoonRide303** [comment]
Closing - it seems it's not aligned with vanilla Fooocus philosophy, so there is no need for this issue to hang around.
