### ISSUE TITLE
using the same face to generate new images

### ISSUE THREAD

**Issue by ManishAradwad** [lllyasviel/Fooocus#1072]
I'm trying to use fooocus for creating professional grade linkedin profile pictures. i tried using my images as input and the generated images are great. But the face is different. I'm relatively new to this. How can i create the images with the same face??

**Comment by Phrixus2023** [comment]
here it is https://www.youtube.com/watch?v=wOBcNPFuB70

**Comment by stubkan** [comment]
I have a lot of difficulty with faceswap too, it seems not possible to faceswap correctly.  I think they should remove it and put roop/reactor/faceswaplab instead.

You might have to use a different webui that supports roop/reactor/faceswaplab plugin instead unfortunately
