### ISSUE TITLE
It takes forever for the task to start

### ISSUE THREAD

**Issue by azhanmd** [lllyasviel/Fooocus#1074]
**Describe the problem**
When I try to run 'python entry_with_update.py', It takes me to the GUI. When I click on generate after entering my prompt, It takes forever to start the task. Could I get some help with this?

**Full Console Log**
TypeError: a.default.detectStore(...) is undefined[h1-check.js:1:1301]

**Comment by SaggioVecchino** [comment]
Same for me here, I'm passing behind a docker container, I don't know if it has something to do with that.

**Comment by Windynik** [comment]
Same here

**Comment by i-am-phenomenal** [comment]
I am facing the same issue. Is it because the GPU has 4GB or less?

**Comment by chris-cozy** [comment]
> I am facing the same issue. Is it because the GPU has 4GB or less? It also gives me this error on my console before I enter any prompt
> 
> Traceback (most recent call last): File "C:\Users\chat2\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner self.run() File "C:\Users\chat2\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run self._target(*self._args, **self._kwargs) File "C:\code\Fooocus\modules\async_worker.py", line 25, in worker import modules.default_pipeline as pipeline File "C:\code\Fooocus\modules\default_pipeline.py", line 1, in import modules.core as core File "C:\code\Fooocus\modules\core.py", line 1, in from modules.patch import patch_all File "C:\code\Fooocus\modules\patch.py", line 10, in import modules.anisotropic as anisotropic File "C:\code\Fooocus\modules\anisotropic.py", line 10, in def _compute_zero_padding(kernel_size: tuple[int, int] | int) -> tuple[int, int]: TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'type'

I had the same issue, and realized it was due to running the venv on a newer python version which no longer supports the '|' operator, which is heavily used in the code. Re-running the venv with python 3.10.0, which supports that operator, solved the problem for me. Hopefully it works for you as well :)

**Comment by eimamac** [comment]
similar solution worked for me as @chris-cozy
I'm on Windows.
-Uninstall python 3.9 (delete the folder in (C:\Users\[user]\AppData\Local\Programs\Python)
-Install python 3.11 (for some reason the newest 3.12 didnt work) 
-Add new dir to PATH
-Redo all the installation steps for Fooocus 

hope that helps someone

**Comment by Hamma111** [comment]
while doing the setup, use `python3` to run all commands instead of `python` to use same python consistently

**Comment by Leyntur** [comment]
> use `python3`

Can you please describe how to do this? Cause i'm having the same problem of the task start taking ages but I'm not really sure on how to use python3

**Comment by me0mar** [comment]
> similar solution worked for me as @chris-cozy I'm on Windows. -Uninstall python 3.9 (delete the folder in (C:\Users[user]\AppData\Local\Programs\Python) -Install python 3.11 (for some reason the newest 3.12 didnt work) -Add new dir to PATH -Redo all the installation steps for Fooocus
> 
> hope that helps someone

on Linux, the issue persists. running Python 3.11.6

**Comment by hazardland** [comment]
> similar solution worked for me as @chris-cozy I'm on Windows. -Uninstall python 3.9 (delete the folder in (C:\Users[user]\AppData\Local\Programs\Python) -Install python 3.11 (for some reason the newest 3.12 didnt work) -Add new dir to PATH -Redo all the installation steps for Fooocus
> 
> hope that helps someone

It helped this particular startup error aka ```_compute_zero_padding(kernel_size: tuple[int, int] | int) -> tuple[int, int]: TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'type'```

 I am using Python 3.11.6 now migrated from Python 3.9

**Comment by ZowWeb** [comment]
> > Issue also occurs on MacOS. Running Python version 3.9.6
> 
> Solved this by installing Python 3.10.13 (`brew install python@3.10`) and then using the `python3.10` command instead of `python` or `python3`.

worked for me as well, thanks

**Comment by mashb1t** [comment]
Solution: Please use Python 3.10.
