### ISSUE TITLE
Exception in thread Thread-2

### ISSUE THREAD

**Issue by SharjeelArif** [lllyasviel/Fooocus#1085]
Having this error when I run py entry_with_update.py. The URL opens in the browser but it does not generate the any images and gets stuck on any prompt. 
![image](https://github.com/lllyasviel/Fooocus/assets/63645297/7158b319-ba20-44c9-8f2d-ec6fd69f0640)

(fo_env) PS C:\Users\RBTG\fo_env> cd fooocus
(fo_env) PS C:\Users\RBTG\fo_env\fooocus> py entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 8191 MB, total RAM 32678 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\RBTG\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\RBTG\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\RBTG\fo_env\fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "C:\Users\RBTG\fo_env\fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "C:\Users\RBTG\fo_env\fooocus\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "C:\Users\RBTG\fo_env\fooocus\modules\patch.py", line 10, in <module>
    import modules.anisotropic as anisotropic
  File "C:\Users\RBTG\fo_env\fooocus\modules\anisotropic.py", line 10, in <module>
    def _compute_zero_padding(kernel_size: tuple[int, int] | int) -> tuple[int, int]:
TypeError: 'type' object is not subscriptable

**Comment by emilmammadov** [comment]
Same issue here

**Comment by emilmammadov** [comment]
Found the solution. I was using python 3.9 and I upgrading it to 3.11 solved the issue

**Comment by emilmammadov** [comment]
@Lobstergoat Upgrade python version to 3.11 and then remove the environment and recreate it. Cause environment will stay with the same version. And please type 'python --version' inside of the environment to see the python version.

**Comment by Lobstergoat** [comment]
@emilmammadov 
Ok thank you, will try now 👍 
And I just tried updating the version from within the env using the config file and path to the version its using and it breaks it lol

**Comment by mashb1t** [comment]
Please make sure to use Python 3.10. if manually upgrading your native python version doesn't work please consider using the zip file installation method with embedded python 3.10 in https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windows.
