### ISSUE TITLE
Way Overcooked now, how can i get back to previous version ?

### ISSUE THREAD

**Issue by Mekurri2006** [lllyasviel/Fooocus#109]
Help, everything was great with my guys yesterday, dialed in my prompt exactly how i wanted around version 1.0.20, updated today to 1.0.28 now its a disaster and nothing i do changes the plasticness overcooked look of my guys...
How do i go back to previous version ? or option to turn off whatever has been turned on since version 1.0.20 ?
Thanks!
Previously :+1: 
![GoodImage2](https://github.com/lllyasviel/Fooocus/assets/4709231/6d243ad1-884b-43a3-8edd-6b1a326dee6c)
Today :-1: 
![BadImage2](https://github.com/lllyasviel/Fooocus/assets/4709231/8f742735-b7c4-498e-b1bc-1c8a48808234)

**Comment by lllyasviel** [comment]
oh my god this is overcooked.
Do you have prompts and so that we can take a look which part is wrong

**Comment by lllyasviel** [comment]
Hi we corrected the problem. See if fixed in 1.0.29. Run.bat to update

**Comment by That-Dude** [comment]
> 

Much better, at least for me. Thanks for a quick update @lllyasviel - loving you work.

**Comment by Mekurri2006** [comment]
Awesome, Thank you @lllyasviel great stuff mate,,, fixed in 1.0.29
All is good in the world again hehehe
Cheers.

![Cheers](https://github.com/lllyasviel/Fooocus/assets/4709231/debebe27-9467-4762-ae75-8bcc38d9ebd0)
