### ISSUE TITLE
WebUI doesn’t show Input Image widget

### ISSUE THREAD

**Issue by cacilhas** [lllyasviel/Fooocus#1090]
**Describe the problem**
When I click the “Input Image” checkbox, nothing happens. The JS inspect console, it shows the error:

```
Uncaught (in promise) ReferenceError: viewer_to_bottom is not defined
    at eval (eval at <anonymous> (Blocks.svelte:68:25), <anonymous>:3:35)
    at Object.eval [as frontend_fn] (eval at <anonymous> (Blocks.svelte:68:25), <anonymous>:3:114)
    at we (Blocks.svelte:366:6)
```

**Full Console Log**
No new logs from server.

**Comment by abhemanyus** [comment]
I am getting the same error

**Comment by abhemanyus** [comment]
After looking into it further, it seems to be caused because the server refuses to send some of the files to the browser, returning a 403 "File not allowed" error message instead. Might be some permission issue, checking it.

**Comment by abhemanyus** [comment]
Okay, that was a rather disturbing fix. Looks like Fooocus inherited gradio's path-mishandling behavior, as seen here https://github.com/gradio-app/gradio/issues/5407. And related to this as well https://github.com/lllyasviel/Fooocus/issues/907
Either set relative paths in all the settings, or don't have the application within a path tree containing a .dot folder.
Won't share any more details, will cause further confusion. This should be handled by the maintainers themselves for greater clarity.

**Comment by projectclarke** [comment]
I have this issue

**Comment by CarryPotterVI** [comment]
i also have this issue, is there a solution to this?

**Comment by mashb1t** [comment]
Solution: see https://github.com/lllyasviel/Fooocus/issues/1379 (https://github.com/lllyasviel/Fooocus/issues/1379#issuecomment-1859847504)
