### ISSUE TITLE
Image generation fails on "Moving to GPU"

### ISSUE THREAD

**Issue by DylanBozarth** [lllyasviel/Fooocus#1092]
Image generation fails, takes about the same amount of time each time. 
Installed on Arch linux using Python Venv method. 
![test](https://github.com/lllyasviel/Fooocus/assets/53990914/eab87c8a-50e1-42c0-aff0-91a19c99ad39)
Anyone have any idea what is happening? 

**Full Console Log**
python entry_with_update.py --preset realistic
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--preset', 'realistic']
Loaded preset: /home/bruh/Documents/AI/Fooocus/presets/realistic.json
Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
ATTENTION: default value of option mesa_glthread overridden by environment.
Total VRAM 4080 MB, total RAM 31948 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
Set vram state to: LOW_VRAM
Disabling smart memory management
Device: cuda:0 AMD Radeon RX 6500 XT : native
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Refiner unloaded.
model_type EPS
adm 2816
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
extra keys {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: /home/bruh/Documents/AI/Fooocus/models/checkpoints/realisticStockPhoto_v10.safetensors
Request to load LoRAs [['SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 0.25], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/home/bruh/Documents/AI/Fooocus/models/checkpoints/realisticStockPhoto_v10.safetensors].
Loaded LoRA [/home/bruh/Documents/AI/Fooocus/models/loras/SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for UNet [/home/bruh/Documents/AI/Fooocus/models/checkpoints/realisticStockPhoto_v10.safetensors] with 788 keys at weight 0.25.
Loaded LoRA [/home/bruh/Documents/AI/Fooocus/models/loras/SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for CLIP [/home/bruh/Documents/AI/Fooocus/models/checkpoints/realisticStockPhoto_v10.safetensors] with 264 keys at weight 0.25.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cpu, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.97 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 3.0
[Parameters] Seed = 2641080382862384140
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] test, vibrant, inspired, highly detailed, intricate, epic composition, magical atmosphere, cinematic light, directed, vivid, beautiful, stunning, symmetry, full color, coherent, great, expressive, perfect, artistic, thought, iconic, amazing, creative, best, awesome, gorgeous, cool, marvelous, colossal, glorious, pure, illuminated, flowing, bright, wonderful
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] test, cinematic, highly detailed, intricate, elegant, light shining, sharp focus, fair quality, dynamic illumination, professional composition, dramatic, thought, fine detail, clear, crisp, ambient color, beautiful, epic, grand, awesome, atmosphere, bright, vivid, romantic, enhanced, symmetry, determined, illuminated, pretty, attractive, depicted, full, artistic, deep
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1152, 896)
Preparation time: 5.14 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
fish: Job 1, 'python entry_with_update.py --p…' terminated by signal SIGSEGV (Address boundary error)

**Comment by mashb1t** [comment]
As of https://github.com/lllyasviel/Fooocus/commit/8e62a72a63b30a3067d1a1bc3f8d226824bd9283 (latest Fooocus version 2.1.857) AMD with >= 8GB VRAM is now supported, before it was 16GB VRAM minimum.
You have to have at least 8GB of VRAM in order to use Fooocus with AMD GPU acceleration. As of https://www.amd.com/de/products/graphics/amd-radeon-rx-6500-xt your graphics card has up to 8GB VRAM. make sure to allocate all of it.
Feel free to use `--always-cpu` instead if this shouldn't work.
