### ISSUE TITLE
Does anyone know how to have dynamic poses when using faceswap?

### ISSUE THREAD

**Issue by arthurmeb** [lllyasviel/Fooocus#1094]
**Is your feature request related to a problem? Please describe.**
Whenever I use faceswap for character consistency, all the generations will have the same flat forward-facing look from the base faceswap image. It's really hard to get other poses or just have the character not always looking straight at the camera. You can somewhat bypass this by using additional input images, but it's not consistent and isn't very user friendly for my users

**Describe the idea you'd like**
A way for faceswap to only really affect the face and not the whole composition of the image. Maybe I need to tweak my settings? Any recommendations??

**Comment by arthurmeb** [comment]
> https://www.youtube.com/watch?v=wOBcNPFuB70

Any english translation?

**Comment by Bullrich** [comment]
> **Describe the idea you'd like** A way for faceswap to only really affect the face and not the whole composition of the image. Maybe I need to tweak my settings? Any recommendations??

I'm with you there, trying quite hard to make my models look into different directions. I can get a picture from the back, but anything that involves showing the face, makes it immediately look at the camera (even if it involves rotating the neck 180 degrees).

On top of this, how do you make your models close their eyes? I'm struggling with this too

**Comment by mashb1t** [comment]
See PR https://github.com/lllyasviel/Fooocus/pull/529 or https://github.com/lllyasviel/Fooocus/pull/1645 to generate an image and override a face with only inpaint.

FaceSwap isn't supported in combination with other image input modification methods. Sorry 😞.
You can try OpenPose in the fork https://github.com/fenneishi/Fooocus-ControlNet-SDXL though.
