### ISSUE TITLE
Does the generation of these images take a lot of time for everyone?

### ISSUE THREAD

**Issue by azhanmd** [lllyasviel/Fooocus#1099]
**Describe the problem**
The generation of my images, on default settings, takes me about 30 minutes, which in turn ends up consuming a lot of energy. I am unsure if it is my network speed that is causing this issue or if it is the application itself. Is it the same for everyone? If not, is there any way to speed up this process without losing quality?

**Comment by godart-corentin** [comment]
With my computer and a RTX 3080, it takes 10s to generate each image.

**Comment by dan4ik94** [comment]
@azhanmd You should post your PC's configuration first. It takes 16s on my 3060.

**Comment by daniellambert95** [comment]
@dan4ik94 It's taking close to an hour per image for me, maybe more.

Macbook Pro M2, 16GB. 

Do you know how I could speed this up?

**Comment by thouravi** [comment]
Two images are taking me 600 seconds (10 minutes) of time with a GTX 1660 Ti.
Not efficient at all.

**Comment by scroogemcfawk** [comment]
On my laptop 3060 image generation itself doesn't take too long (about 1-2 minutes per image with Quality preset), but moving model to memory is Really heavy for my machine (sometimes takes several minutes and during that the whole system is just suffering)

**Comment by colingoodman** [comment]
> buy a windows computer

The OS has nothing to do with it, image generation is fine on Linux with a proper GPU.

**Comment by Phrixus2023** [comment]
> > buy a windows computer
> 
> The OS has nothing to do with it, image generation is fine on Linux with a proper GPU.
I saw someone using an Apple computer.

**Comment by daniellambert95** [comment]
Has anyone connected an eGPU to their Macbook? I'm thinking of investing in one but I would like to know if would speed up the processing time for Fooocus.

**Comment by ThomasP1988** [comment]
M2 pro 16GB and it's very slow for me as well, 130s/it

**Comment by daniellambert95** [comment]
@ThomasP1988 hey Thomas, is it 2minutes per image? Did you change any configuration? I have the same specs but it's taking 1hr+

**Comment by ThomasP1988** [comment]
I wish, but it is 130s/it meaning that it's very slow, same duration than you

**Comment by mengusabah** [comment]
I've also tried on M2 using MPS device acceleration. It takes approximately 1 hour to generate an image. The speed difference is really huge. Isn't there a faster way?

**Comment by thouravi** [comment]
Going to try ComfyUI or A1111's repo for SD. No support or help was found from Fooocus team or contributors.

**Comment by ThomasP1988** [comment]
Apple just released "an array framework for machine learning on Apple silicon" with SD example: https://github.com/ml-explore/mlx-examples/tree/main/stable_diffusion

Haven't tried yet but could be a solution

**Comment by mashb1t** [comment]
We do now have a Mac section in the readme. Please follow https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#mac if this is still relevant and set `--disable-offload-from-vram` if needed.

**Comment by Yobro7292** [comment]
> @dan4ik94 It's taking close to an hour per image for me, maybe more.
> 
> Macbook Pro M2, 16GB.
> 
> Do you know how I could speed this up?

I am using M3 8gb ram still taking 10 mins

**Comment by mashb1t** [comment]
M1 Macbook Pro 32GB RAM, ~2-3min per image. Strongly recommend 32GB RAM or more as swap is really slow, even with an NVMe SSD.

**Comment by lgwjames** [comment]
> **Describe the problem** The generation of my images, on default settings, takes me about 30 minutes, which in turn ends up consuming a lot of energy. I am unsure if it is my network speed that is causing this issue or if it is the application itself. Is it the same for everyone? If not, is there any way to speed up this process without losing quality?

i just got a 12gb rtx 3060 and will be doing this to test.
waiting on my case/holder

https://www.aliexpress.com/item/1005002802776587.html?spm=a2g0o.order_list.order_list_main.5.47871802NCGUAs
