### ISSUE TITLE
FOOOCUS CLOSING AUTOMATICALLY ON KUBUNTU LINUX ON 1650TI AND 8GB RAM

### ISSUE THREAD

**Issue by kingmehar** [lllyasviel/Fooocus#1101]
FOOOCUS CLOSES AUTOMATICALLY (THE TERMINAL CLOSES) AND THE WEBUI SAYS CONNECTION TIMED OUT
**Full Console Log**

IT WAS VERY HARD TO GET LOGS BECAUSE THE KONSOLE ALSO CLOSED BUT I WAS ABLE TO GET IT SOMEHOW
```
To create a public link, set `share=True` in `launch()`.
Total VRAM 3904 MB, total RAM 7769 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
Set vram state to: LOW_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce GTX 1650 Ti : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
model_type EPS
```
AND THEN FOOOCUS CLOSES

**Comment by andjim** [comment]
I'm having the same issue.  It works for a really short time and then stops. I'm running it on WLS2 Ubuntu

```
Already up-to-date
Update succeeded.
[System ARGV] [entry_with_update.py, --listen]
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.1.824
Running on local URL:  http://0.0.0.0:7865

To create a public link, set share=True in launch().
Total VRAM 6144 MB, total RAM 7904 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce GTX 1660 Ti : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
model_type EPS
adm 2816
Killed
```

**Comment by Croninja** [comment]
Similar issue here essentially just silently exits every time when attempting to start it up. 

Using Windows with a Ryzen 5900X + 3080 FE. Not getting any apparent error indicating what the issue might be:

```
PS D:\Resources\AI\Fooocus> .\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 10240 MB, total RAM 32675 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 3080 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
PS D:\Resources\AI\Fooocus>
```

**Comment by salatfreak** [comment]
The models need an insane amount of RAM and the program will be terminated, once the available RAM is filled. On my debian machine with 15 GB of free RAM I needed to mount a 24 GB swap file for it to run without problems. So if you configure swap of about 40 GB minus available RAM, you should be safe.

**Comment by Misza508** [comment]
I've had the same issue after increasing the swap it starts working

**Comment by LeonIsLeet** [comment]
It's because you are running out of swap. I had a similar issue, I fixed it with creating about 20 Gigs of swap memory. You could create one with the following commands

`sudo fallocate -l <size-in-gigabytes>G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
`

**Comment by lllyasviel** [comment]
yes see also https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
