### ISSUE TITLE
run foocus in a laptop

### ISSUE THREAD

**Issue by Kowiste** [lllyasviel/Fooocus#1107]
Hi, my laptop have a intel card, is possible to run foocus? If is, how can i configure it ? right now i have error when try to generate becaus doesnt have nvidia drivers.

**Comment by badaramoni** [comment]
> I have same issue, Macbook pro I5

its work on macbook pro

**Comment by mashb1t** [comment]
This is currently not possible, see https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement
Intel ARC support is handled here: https://github.com/lllyasviel/Fooocus/issues/1470

In the meantime, you can use `--always-cpu`.
