### ISSUE TITLE
DefaultCPUAllocator: not enough memory: you tried to allocate 6553600 bytes.

### ISSUE THREAD

**Issue by syedhammad74** [lllyasviel/Fooocus#1110]
```
Using directml with device:
Total VRAM 1024 MB, total RAM 16310 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: privateuseone
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Refiner unloaded.
```
im using amd ryzen 5700x and amd radeon 6700xt

**Comment by AlexPerni** [comment]
Did you manage to solve this issue?

**Comment by DosenSuppe** [comment]
Well, that was weird. After I wrote my comment, I restarted the application. It started with no errors, and everything worked. As I began to generate an image and write another comment about it, my PC received an OutOfMemory Bluescreen, ironically.
