### ISSUE TITLE
AMD Windows There is not enough GPU video memory available! (using 6GB of VRAM)

### ISSUE THREAD

**Issue by IdentifiedBody** [lllyasviel/Fooocus#1115]
**Describe the problem**
Even after allocating 6 GB of VRAM, it says that there is not enough GPU memory available.

keep in mind before i had a problem with torch and changed this:
.\python_embeded\Lib\site-packages\torchsde_brownian\brownian_interval.py

Line 32

generator = torch.Generator(device).manual_seed(int(seed))
to

generator = torch.Generator().manual_seed(int(seed))

So i dont know if those two are correlating.

**Full Console Log**

ERROR diffusion_model.output_blocks.1.1.transformer_blocks.2.ff.net.0.proj.weight Could not allocate tensor with 52428800 bytes. There is not enough GPU video memory available!
Traceback (most recent call last):
  File "D:\AITOOLbusiness\Tool\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AITOOLbusiness\Tool\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AITOOLbusiness\Tool\Fooocus\modules\default_pipeline.py", line 361, in process_diffusion
    sampled_latent = core.ksampler(
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AITOOLbusiness\Tool\Fooocus\modules\core.py", line 315, in ksampler
    samples = fcbh.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\AITOOLbusiness\Tool\Fooocus\backend\headless\fcbh\sample.py", line 93, in sample
    real_model, positive_copy, negative_copy, noise_mask, models = prepare_sampling(model, noise.shape, positive, negative, noise_mask)
  File "D:\AITOOLbusiness\Tool\Fooocus\backend\headless\fcbh\sample.py", line 86, in prepare_sampling
    fcbh.model_management.load_models_gpu([model] + models, model.memory_required(noise_shape) + inference_memory)
  File "D:\AITOOLbusiness\Tool\Fooocus\modules\patch.py", line 494, in patched_load_models_gpu
    y = fcbh.model_management.load_models_gpu_origin(*args, **kwargs)
  File "D:\AITOOLbusiness\Tool\Fooocus\backend\headless\fcbh\model_management.py", line 410, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
  File "D:\AITOOLbusiness\Tool\Fooocus\backend\headless\fcbh\model_management.py", line 293, in model_load
    raise e
  File "D:\AITOOLbusiness\Tool\Fooocus\backend\headless\fcbh\model_management.py", line 289, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to) #TODO: do something with loras and offloading to CPU
  File "D:\AITOOLbusiness\Tool\Fooocus\backend\headless\fcbh\model_patcher.py", line 191, in patch_model
    temp_weight = fcbh.model_management.cast_to_device(weight, device_to, torch.float32, copy=True)
  File "D:\AITOOLbusiness\Tool\Fooocus\backend\headless\fcbh\model_management.py", line 532, in cast_to_device
    return tensor.to(device, copy=copy).to(dtype)
RuntimeError: Could not allocate tensor with 26214400 bytes. There is not enough GPU video memory available!
Total time: 307.81 seconds

**Comment by lorenzoagb** [comment]
Same here

**Comment by rafaelrovira** [comment]
same here

**Comment by hansanaCham** [comment]
same hear i have rx580 8gb

**Comment by axnix** [comment]
+with rx570 8gb

**Comment by creix** [comment]
+1 rx580 8gb

**Comment by AlexPerni** [comment]
Same here, I'm using Radeon RX Vega 56 on Windows 10.
GPU has 8GB and 16GB of VRAM. 
But in the beginning, it only shows 1GB of VRAM. Can I change this setting somewhere? 
Or perhaps the GPU is not correctly recognized?

> Using directml with device:
> Total VRAM 1024 MB, total RAM 32694 MB
> Set vram state to: NORMAL_VRAM
> Disabling smart memory management
> Device: privateuseone

**Comment by axnix** [comment]
> Same here, I'm using Radeon RX Vega 56 on Windows 10. GPU has 8GB and 16GB of VRAM. But in the beginning, it only shows 1GB of VRAM. Can I change this setting somewhere? Or perhaps the GPU is not correctly recognized?
> 
> > Using directml with device:
> > Total VRAM 1024 MB, total RAM 32694 MB
> > Set vram state to: NORMAL_VRAM
> > Disabling smart memory management
> > Device: privateuseone

You can fix it like this: https://github.com/lllyasviel/Fooocus/issues/624#issuecomment-1833571337
But for me (win10,rx570 8gb) it didn't help. I'm still running to error of the thread-issue "There is not enough GPU video memory available!"

**Comment by DeimaD** [comment]
Same with RX580 8gb

**Comment by PowerZones** [comment]
same RX580 8gb tried both fixes still getting same error

**Comment by xzxz520cs** [comment]
6900XT also has this error
RuntimeError: Could not allocate tensor with 1073741824 bytes. There is not enough GPU video memory available!
Total time: 319.37 seconds

**Comment by AlexeyJersey** [comment]
Same here RX5700 8gb

**Comment by stubkan** [comment]
If starting in normal vram mode is not working, try low vram mode

![image](https://github.com/lllyasviel/Fooocus/assets/34361592/ae865779-b767-4f9d-9f6a-9857f9a55b6f)

If issues are persisting, there is a memory bug in the latest versions - mostly shows up when you try to generate an image using an input image or lora.

Try rolling back to version 2.1.703

Which is this commit https://github.com/lllyasviel/Fooocus/tree/9660daff94b4d0f282567b96b3d387817818a4b3

**Comment by xzxz520cs** [comment]
The issue with the 6900XT has temporarily not occurred after updating the driver to 23.12.1 and setting --normalvram, but I have not conducted extensive testing.

**Comment by itoch** [comment]
Same here! Rx 6500 xt

**Comment by Niccocande** [comment]
> If starting in normal vram mode is not working, try low vram mode
> 
> ![image](https://private-user-images.githubusercontent.com/34361592/289276937-ae865779-b767-4f9d-9f6a-9857f9a55b6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTM0NjIsIm5iZiI6MTcwMjMxMzE2MiwicGF0aCI6Ii8zNDM2MTU5Mi8yODkyNzY5MzctYWU4NjU3NzktYjc2Ny00ZjlkLTlmNmEtOTg1N2Y5YTU1YjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE2NDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmOGM4Mzg5NTBhZjg3NWQ5OWE4ZmRhMDcwZmYzMGMwM2VhOGIxM2I2ZjgyYjVjNmJiMGM5OWE3MmU5YzczNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RDokCyyhSm7yqwvLsoKCHx0bK53DDNLsffqC2nnYtq8)
> 
> If issues are persisting, there is a memory bug in the latest versions - mostly shows up when you try to generate an image using an input image or lora.
> 
> Try rolling back to version 2.1.703
> 
> Which is this commit https://github.com/lllyasviel/Fooocus/tree/9660daff94b4d0f282567b96b3d387817818a4b3

I guess the download page doesn't exist anymore? I can't download it

**Comment by stubkan** [comment]
git clone to your drive

then

git reset 9660daf

to revert local copy to that commit

**Comment by abel-haj** [comment]
Same here! I have RX 580 8GB!
I am stuck between these errors: **Torch not compiled with CUDA enabled** and **There is not enough GPU video memory available!**

**Comment by lllyasviel** [comment]
hi we have updated the spec doc to clear confusion. see also:

https://github.com/lllyasviel/Fooocus#minimal-requirement

**Comment by EonRipster** [comment]
So if you are running windows and and AMD GPU that card needs a minimum of 16GB?

**Comment by xzxz520cs** [comment]
> The issue with the 6900XT has temporarily not occurred after updating the driver to 23.12.1 and setting --normalvram, but I have not conducted extensive testing.

RuntimeError: Could not allocate tensor with 1073741824 bytes. There is not enough GPU video memory available!

After multiple image generations (probably clicking generate more than 20 times), this problem still occurs. Restarting the computer can solve the problem, but restarting fooocus cannot solve this problem.

**Comment by xzxz520cs** [comment]
After the error, there is a chance of success by clicking generations several times. Is this an error in some kind of memory scheduling?

**Comment by mashb1t** [comment]
As of https://github.com/lllyasviel/Fooocus/commit/8e62a72a63b30a3067d1a1bc3f8d226824bd9283 AMD with >= 8GB VRAM is now supported.
Please try with min. 8GB VRAM allocated.

**Comment by mashb1t** [comment]
Closing as stale, feel free to reopen when providing new information if this is still relevant :)
