### ISSUE TITLE
AMD 7800xt WinError 126 module could not be found

### ISSUE THREAD

**Issue by eaglestorm** [lllyasviel/Fooocus#1119]
**Describe the problem**
Tried running Fooocus on Windows 10 with AMD 7800xt and it fails with the below error.  I'm thinking it might be related to directml support for my GPU as it tried installing this seperately based on these instructions https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-windows and also got errors.  Any help would be good.

**Full Console Log**
E:\Fooocus>set path=C:\Program Files\Eclipse Adoptium\jdk-11.0.16.8-hotspot\bin;C:\tools\ruby30\bin;C:\Program Files\Microsoft\jdk-16.0.2.7-hotspot\bin;C:\Program Files\Microsoft\jdk-17.0.0.35-hotspot\bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\bitem\AppData\Local\Microsoft\WindowsApps;C:\Users\bitem\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\Gauge\bin;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\dotnet\;C:\PROGRA~1\Red Gate\Flyway Desktop\;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\nodejs\;C:\Program Files\RedHat\Podman\;C:\Users\bitem\.cargo\bin;C:\Users\bitem\AppData\Local\Microsoft\WindowsApps;;C:\Users\bitem\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\GitHub CLI\;C:\Users\bitem\.dotnet\tools;C:\Users\bitem\AppData\Local\JetBrains\Toolbox\scripts;C:\Users\bitem\.dotnet\tools;C:\Program Files\liquibase;C:\Users\bitem\AppData\Roaming\npm;E:\Fooocus\python_embeded\Scripts

E:\Fooocus>.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
Found existing installation: torch 2.0.0
Uninstalling torch-2.0.0:
  Successfully uninstalled torch-2.0.0
Found existing installation: torchvision 0.15.1
Uninstalling torchvision-0.15.1:
  Successfully uninstalled torchvision-0.15.1
WARNING: Skipping torchaudio as it is not installed.
WARNING: Skipping torchtext as it is not installed.
WARNING: Skipping functorch as it is not installed.
WARNING: Skipping xformers as it is not installed.

E:\Fooocus>.\python_embeded\python.exe -m pip install -v torch-directml
Using pip 23.3.1 from E:\Fooocus\python_embeded\lib\site-packages\pip (python 3.10)
Requirement already satisfied: torch-directml in e:\fooocus\python_embeded\lib\site-packages (0.2.0.dev230426)
Collecting torch==2.0.0 (from torch-directml)
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting torchvision==0.15.1 (from torch-directml)
  Using cached torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
Requirement already satisfied: filelock in e:\fooocus\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.12.2)
Requirement already satisfied: typing-extensions in e:\fooocus\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (4.7.1)
Requirement already satisfied: sympy in e:\fooocus\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (1.12)
Requirement already satisfied: networkx in e:\fooocus\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.1)
Requirement already satisfied: jinja2 in e:\fooocus\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.1.2)
Requirement already satisfied: numpy in e:\fooocus\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (1.23.5)
Requirement already satisfied: requests in e:\fooocus\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in e:\fooocus\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (9.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\fooocus\python_embeded\lib\site-packages (from jinja2->torch==2.0.0->torch-directml) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\fooocus\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in e:\fooocus\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\fooocus\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in e:\fooocus\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (2023.5.7)
Requirement already satisfied: mpmath>=0.19 in e:\fooocus\python_embeded\lib\site-packages (from sympy->torch==2.0.0->torch-directml) (1.3.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: torch, torchvision
Successfully installed torch-2.0.0 torchvision-0.15.1

E:\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--directml']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.824
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "E:\Fooocus\Fooocus\modules\async_worker.py", line 20, in worker
    import torch
  File "E:\Fooocus\python_embeded\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "E:\Fooocus\python_embeded\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.

**Comment by mashb1t** [comment]
Please reinstall torch in your venv, there seems to be the file `caffe2_nvrtc.dll` missing.
