### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by runew0lf** [lllyasviel/Fooocus#112]
Would there be a way of storing the styles in a csv / json so we can manually add our own? instead of in just one huge python file?

Also do you have a discord as im sure people would love to offer eachother hints and tips about it.

**Comment by XHJ-Studio** [comment]
> 
As someone who utilizes Stable diffusion for assisting in product design and is also an avid user of Discord and various other social media platforms, I strongly agree with the viewpoint that social media platforms can amplify the voices of a small portion of the community, even though they may not represent the majority.

**Comment by Koshel4** [comment]
Why not to add possibility to cancel image generation if I see that image generating is not what I want?

**Comment by trltzy** [comment]
Is there a space that we can exchange our tips of prompts and experience? thanks a lot

**Comment by WavedirectTel** [comment]
maybe an unofficial one started by someone else?

**Comment by silvncr** [comment]
> maybe an unofficial one started by someone else?

i would be interested in part-time moderation if anyone does this

**Comment by random9brat** [comment]
Im having the same issue... even tho my `python3 --version`  is ok in cmd

**Comment by ItsNoted** [comment]
> maybe an unofficial one started by someone else?

There is a subreddit. https://www.reddit.com/r/fooocus/

**Comment by raochinmay6** [comment]
Please I need help why everytime I run and get error see the pic and please help I'm not coding person so please explain easy 🙏🏻
![IMG-20240223-WA0008](https://github.com/lllyasviel/Fooocus/assets/160831464/fb2d58fe-cfc5-4908-9d31-2ffd92b68db5)
![IMG-20240223-WA0007](https://github.com/lllyasviel/Fooocus/assets/160831464/0d453bf0-197f-4f13-aa26-3fddc2aecc1e)

**Comment by DSV68609** [comment]
Can you help me with this run error? I'm very stuck on this RuntimeError.
RuntimeError: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

**Comment by DSV68609** [comment]
I already updated the GPU driver but I have no idea on PyTorrch and CUDA driver.

**Comment by umarmnaq** [comment]
If I create an unofficial server, will that be OK? (Provided I explicitly state that it is an unofficial server)

**Comment by Addy0102** [comment]
I am running this live on Colab. I keep getting the JSON error, and when i try to reopen with colab, it says runtime error, and asks me to download a cuda gpu...Please help me, I also cannot download this to run locally, it is too large for my computer

**Comment by martinenkoEduard** [comment]
> No we will not have discord servers.
> 
> Discord server will introduce a major bias towards a small number of users with larger voice but ignore the majority users in industry who really create daily contents. A discord also introduces a minor bias toward English-speaking users. I have witnessed these biases kill many great projects first hand.
> 
> We will observe the community not only in English speaking users, but also community in Japanese, Chinese, Korea, Russia, Spanish to improve the project and get feedbacks internationally.
> 
> Custom style may be supported in the future after we find a way to balance the UI simplicity.

Really good explanation! Applauds!
