### ISSUE TITLE
Does this have an API?

### ISSUE THREAD

**Issue by ChibiWaifuDev** [lllyasviel/Fooocus#1120]
Is there way to generate and show the output through an api with this app?

**Comment by agrogov** [comment]
At the bottom of the page click on `Use via API` and you can use Gradio API
<img width="348" alt="image" src="https://github.com/lllyasviel/Fooocus/assets/5955205/8576fbac-33a7-48d0-850d-6c428b3161dc">

**Comment by agrogov** [comment]
@BlitzJB just click on it, there would be kinda swagger with examples

**Comment by mashb1t** [comment]
There also is https://github.com/konieshadow/Fooocus-API if you're looking for a REST API.
