### ISSUE TITLE
Cancel Queue

### ISSUE THREAD

**Issue by moritz-t-w** [lllyasviel/Fooocus#1121]
**Is your feature request related to a problem? Please describe.**
When I click "Generate" and then I'm put in the queue but I give up and now my images are still gonna be generated, even tho I left 
**Describe the idea you'd like**
Keep the "Stop" button or add a "Cancel" button while in queue

**Comment by mashb1t** [comment]
In the latest versin of Fooocus the buttons are displayed while being in the queue.
