### ISSUE TITLE
Taking more than 5 minutes for image generation

### ISSUE THREAD

**Issue by thouravi** [lllyasviel/Fooocus#1125]
**Describe the problem**
I am using this on Windows 11 with GTX 1660 Ti, it's taking more than 5 minutes to generate 1 single image.
Even moving the model has taken 140 seconds.

![image](https://github.com/lllyasviel/Fooocus/assets/15676184/7fcfe540-2723-4c27-951d-5b6697f3e873)

**Full Console Log**
```
To create a public link, set `share=True` in `launch()`.
Total VRAM 6144 MB, total RAM 16208 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce GTX 1660 Ti : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra keys {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: D:\Fooocus_win64_2-1-791\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [D:\Fooocus_win64_2-1-791\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [D:\Fooocus_win64_2-1-791\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [D:\Fooocus_win64_2-1-791\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cpu, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 2036027638734274833
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 2.71 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 3160.044695854187
[Fooocus Model Management] Moving model(s) has taken 141.65 seconds
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [03:17<00:00,  6.59s/it]
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2023-12-02\log.html
Generating and saving time: 344.76 seconds
Total time: 364.21 seconds

```

**Comment by NotAdityaPawar** [comment]
For me it took more than 20 mins, yours is actually fast

**Comment by jaxparrow07** [comment]
Mine was within a minute, I'm using a 3060

**Comment by thouravi** [comment]
**I have tried using the NVIDIA 531.18 Drivers. No improvements in the generation.**
@lllyasviel any other fix?

**Comment by mirek190** [comment]
> I noticed that the model need to move to GPU every prompt. Don't know why the app reload the model each time. That's why it's taking so long ![Capture](https://private-user-images.githubusercontent.com/26477048/287460620-eb3b3b49-927d-4fd0-b4b1-6704cf4e408c.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NTU4ODEsIm5iZiI6MTcwMTU1NTU4MSwicGF0aCI6Ii8yNjQ3NzA0OC8yODc0NjA2MjAtZWIzYjNiNDktOTI3ZC00ZmQwLWI0YjEtNjcwNGNmNGU0MDhjLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDIyMTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NGFiYzc1MTEzYmU4N2MxNmI5N2RiYWY2YzFlNmRjNTZhNzQwYWE5M2JjOWJjNjM5NTMwYTEwZmI5M2ZiMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VgDztcVAIa7QunJLmuueLkRkE4HPcEQYLmf3_HFnpAI)

Are you using HDD ?
If you had nvmie SDD even moving 20 GB into vram takes 3 seconds

**Comment by superkido511** [comment]
> > I noticed that the model need to move to GPU every prompt. Don't know why the app reload the model each time. That's why it's taking so long ![Capture](https://private-user-images.githubusercontent.com/26477048/287460620-eb3b3b49-927d-4fd0-b4b1-6704cf4e408c.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NTU4ODEsIm5iZiI6MTcwMTU1NTU4MSwicGF0aCI6Ii8yNjQ3NzA0OC8yODc0NjA2MjAtZWIzYjNiNDktOTI3ZC00ZmQwLWI0YjEtNjcwNGNmNGU0MDhjLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDIyMTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NGFiYzc1MTEzYmU4N2MxNmI5N2RiYWY2YzFlNmRjNTZhNzQwYWE5M2JjOWJjNjM5NTMwYTEwZmI5M2ZiMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VgDztcVAIa7QunJLmuueLkRkE4HPcEQYLmf3_HFnpAI)
> 
> Are you using HDD ? If you had nvmie SDD even moving 20 GB into vram takes 3 seconds

I am. But why can the models stay in the VRAM instead of reloading every prompt? I don't have this issue with A1111, Comfy

**Comment by thouravi** [comment]
Going to try ComfyUI or A1111's repo for SD. No support or help was found from Fooocus team or contributors.
