### ISSUE TITLE
Is there a config or flag to decide which GPU used to generate the image?

### ISSUE THREAD

**Issue by jonathantyar** [lllyasviel/Fooocus#1132]
It's normal when i tried to run it on my computer, but when doing it on laptop with both integrated graphics and extended one (rx 6800m) i check the task manager that whenever i run bat file, only integrated graphics working not the extended one. is there any config i need to so only extended graphics is the one doing the work?
![image](https://github.com/lllyasviel/Fooocus/assets/19704585/eabbbd06-5d2b-43c9-8b38-7ab327358773)

and the VRAM is 0 when trying to run, is these expected or i missing something? Thank you
![image](https://github.com/lllyasviel/Fooocus/assets/19704585/a0ef3400-60fb-46e6-8fc2-b839b1158793)

**Comment by cemalley** [comment]
having the same issue, it's only using integrated graphics not my RTX 3070.

**Comment by cemalley** [comment]
I was able to change my gpu settings to prioritize performance over battery and now it's using both integrated & 3070 (even though it was connected to power the whole time).

**Comment by lllyasviel** [comment]
there is `--gpu-device-id DEVICE_ID` but may only works for selecting CUDA devices..
