### ISSUE TITLE
MPS backend out of memory

### ISSUE THREAD

**Issue by GondorGitaros** [lllyasviel/Fooocus#1139]
**Describe the problem**
I have a Macbook pro M2 and i get this error with both "python entry_with_update.py" and "python entry_with_update.py --enable-smart-memory" command

**Full Console Log**
RuntimeError: MPS backend out of memory (MPS allocated: 8.89 GB, other allocations: 172.98 MB, max allowed: 9.07 GB). Tried to allocate 6.25 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
Total time: 129.38 seconds

**Comment by kabasele243** [comment]
I'm getting the same error.

**Comment by GondorGitaros** [comment]
I consider myself as a noob bc I don't know where to type PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0

**Comment by GondorGitaros** [comment]
https://github.com/lllyasviel/Fooocus/discussions/1156 It worked for me

**Comment by GondorGitaros** [comment]
LMK if it solved your problem too!!!
