### ISSUE TITLE
Fooocus Advanced 2

### ISSUE THREAD

**Issue by psale** [lllyasviel/Fooocus#1140]
I have a pt file trained on my images, can I put it in or load it and use it?

**Comment by mashb1t** [comment]
You can put it in `Fooocus/models/prompt_expansion` and change the name of the model in https://github.com/lllyasviel/Fooocus/blob/eb0b4d51ef3f46f57d7f20e870aa89a4b5de48ef/launch.py#L84-L86.
Give it a try.
