### ISSUE TITLE
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party..

### ISSUE THREAD

**Issue by Skai7** [lllyasviel/Fooocus#1147]
Hello Guys.
This is the error I'm getting when I am trying to use the image prompt issue

urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Total time: 21.12 seconds

Do you happen to know what could be the problem?

thanks in advance!

**Comment by mashb1t** [comment]
> Open this link: https://huggingface.co/lllyasviel/misc/resolve/main/ip-adapter-plus-face_sdxl_vit-h.bin Download the model manually, without changing its name, to `Fooocus_win64_2-1-791\Fooocus\models\controlnet`

This and please check your system swap, see https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#winerror-10060
