### ISSUE TITLE
How does faceswapping feature works?

### ISSUE THREAD

**Issue by MrlolDev** [lllyasviel/Fooocus#1148]
Hello, I would like to know what is the function FaceSwap based on. Since I tried a lot of service with similar configurations and I didn't get similar results

**Comment by Nerual-Dreming** [comment]
It's not FaceSwap, for some reasons it's IP-Adapter Face. it doesn't work the way you expect it to.

**Comment by MrlolDev** [comment]
Do you know some serverless service that provides similar results? They are really good and i wanted to use it in my product

**Comment by stubkan** [comment]
Yes, the faceswap included in Fooocus works very badly.  I never can get the face to look like anyone properly.  

I think they should remove faceswap and put roop / reactor / faceswaplab instead.

You can use those on another webui that supports them and it will have excellent results

**Comment by mashb1t** [comment]
Issue has been answered, closing.
