### ISSUE TITLE
ValueError: [Errno 2] No such file or directory: '/content/Fooocus/models/upscale_models/fooocus_upscaler_s409985e5.bin'

### ISSUE THREAD

**Issue by tralala87** [lllyasviel/Fooocus#1149]
When running inpaint and making corrections to the image, I get:
ValueError: [Errno 2] No such file or directory: '/content/Fooocus/models/upscale_models/fooocus_upscaler_s409985e5.bin'

**Comment by mrstask** [comment]
same for me, I am using google collab

**Comment by teanijarv** [comment]
same here

**Comment by xChAmeLIoNz** [comment]
> **Just download the upscaler package explisitly** @teanijarv @tralala87 !pip install pygit2==1.12.2 %cd /content !git clone https://github.com/lllyasviel/Fooocus.git
> 
> %cd /content/Fooocus/models/upscale_models/ !wget -O fooocus_upscaler_s409985e5.bin https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_upscaler_s409985e5.bin?download=true
> 
> %cd /content/Fooocus !python entry_with_update.py --share

Worked. Thanks.

**Comment by Fafukee** [comment]
> **Just download the upscaler package explisitly** @teanijarv @tralala87 !pip install pygit2==1.12.2 %cd /content !git clone https://github.com/lllyasviel/Fooocus.git
> 
> %cd /content/Fooocus/models/upscale_models/ !wget -O fooocus_upscaler_s409985e5.bin https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_upscaler_s409985e5.bin?download=true
> 
> %cd /content/Fooocus !python entry_with_update.py --share

@mrstask sorry but how exactly I do this ?
