### ISSUE TITLE
Can you include  fantasticmix_v65.safetensors?

### ISSUE THREAD

**Issue by iRumba** [lllyasviel/Fooocus#1166]
**Is your feature request related to a problem? Please describe.**
Hi. I want to get seamless textures, but I can't 

I read here https://www.nextdiffusion.ai/tutorials/how-to-make-seamless-textures-with-ai-stable-diffusion that it possible with fantasticmix_v65.safetensors

I have link https://huggingface.co/digiplay/fantasticmix_v65_test/blob/main/fantasticmix_v65.safetensors

**Comment by mashb1t** [comment]
Choosing models included in the default presets follows a strict performance monitoring of various models.
Also see https://github.com/lllyasviel/Fooocus/discussions/808#discussioncomment-7417540

As the checkpoint has "test" in the title i assume that it is not a final model (yet).
Closing this issue.
