### ISSUE TITLE
这个如何进行启动，我下载的项目没有exe文件呀

### ISSUE THREAD

**Issue by wang1024it** [lllyasviel/Fooocus#1170]
**Describe the problem**

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.
与Windows相同。下载软件，编辑内容为run.bat：

.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
.\python_embeded\python.exe -m pip install torch-directml
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml
pause
然后运行run.bat​​。

然而，AMD 主动经过研究测试。AMD支持一个测试阶段。

使用python entry_with_update.py --preset anime或python entry_with_update.py --preset realistic用于Fooocus动漫/现实版。

**Comment by mashb1t** [comment]
Please execute run.bat after doing the changes.
