### ISSUE TITLE
Is it possible to share checkpoints with other UI?

### ISSUE THREAD

**Issue by IamTirion** [lllyasviel/Fooocus#1171]
**Is your feature request related to a problem? Please describe.**
I wish to share checkpoints that I have downloaded for other UIs so I don't have to keep multiple copies of them. Is that possible?

**Comment by fmiguelcosta** [comment]
You can change the path to your models in /Fooocus/config.txt. I'm trying to do the same (sharing checkpoints with [RuinedFooocus](https://github.com/runew0lf/RuinedFooocus)), the checkpoint and output work fine, but I'm enable to change the loras path, keeps getting the original one.

**Comment by IamTirion** [comment]
Alright, thanks.

**Comment by IamTirion** [comment]
Wait sorry. Is it possible to add more than one file path for each sector? I added a file path for loras after the comma, but I failed to get it work.

**Comment by fmiguelcosta** [comment]
this is mine

```javascript
{
    "path_checkpoints": "E:\\sdmodels\\checkpoints",
    "path_loras": "E:\\sdmodels\\loras",
    "path_embeddings": "E:\\Fooocus_win64_2-1-791\\Fooocus\\models\\embeddings",
    "path_vae_approx": "E:\\Fooocus_win64_2-1-791\\Fooocus\\models\\vae_approx",
    "path_upscale_models": "E:\\Fooocus_win64_2-1-791\\Fooocus\\models\\upscale_models",
    "path_inpaint": "E:\\Fooocus_win64_2-1-791\\Fooocus\\models\\inpaint",
    "path_controlnet": "E:\\Fooocus_win64_2-1-791\\Fooocus\\models\\controlnet",
    "path_clip_vision": "E:\\Fooocus_win64_2-1-791\\Fooocus\\models\\clip_vision",
    "path_fooocus_expansion": "E:\\Fooocus_win64_2-1-791\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
    "path_outputs": "E:\\sdmodels\\outputs"
}
``` 
as you can see you can individualy change the path to all this folders

**Comment by IamTirion** [comment]
> {
    "path_checkpoints": ["D:\\Fooocus\\Fooocus\\models\\checkpoints", "D:\\A1111 Web UI Autoinstaller\\stable-diffusion-webui\\models\\Stable-diffusion",
    "path_loras": "D:\\Fooocus\\Fooocus\\models\\loras", "D:\\A1111 Web UI Autoinstaller\\stable-diffusion-webui\\models\\Lora",
    "path_embeddings": "D:\\Fooocus\\Fooocus\\models\\embeddings",
    "path_vae_approx": "D:\\Fooocus\\Fooocus\\models\\vae_approx",
    "path_upscale_models": "D:\\Fooocus\\Fooocus\\models\\upscale_models",
    "path_inpaint": "D:\\Fooocus\\Fooocus\\models\\inpaint",
    "path_controlnet": "D:\\Fooocus\\Fooocus\\models\\controlnet",
    "path_clip_vision": "D:\\Fooocus\\Fooocus\\models\\clip_vision",
    "path_fooocus_expansion": "D:\\Fooocus\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
    "path_outputs": "D:\\Fooocus\\Fooocus\\outputs"
}

And this is mine. Sorry if I wasn't clear about what I want to do. I want to add multiple paths for the checkpoints or loras. You may ask why I don't just put all the checkpoints and loras together. Well, some softwares such as Krita that has a Stable Diffusion plugin only work with certain UIs, so I need to keep the checkpoints or loras in their respective folders.

**Comment by fmiguelcosta** [comment]
You need to put the checkpoints and loras in the same place, and change both softwares to that point. if you canot change paths in Krita, use krita dirs move your models to that dir, and put that on the config.txt

**Comment by dooglewoogle** [comment]
I have the same issue, ended up making this:
https://github.com/lllyasviel/Fooocus/pull/1256
@IamTirion That config you posted is exactly how it works.

**Comment by IamTirion** [comment]
> I have the same issue, ended up making this: #1256 @IamTirion That config you posted is exactly how it works.

Well it didn't work for me.

**Comment by mashb1t** [comment]
Multiple location support is added in PR https://github.com/lllyasviel/Fooocus/pull/1256
