### ISSUE TITLE
Faceswap feature causes the app to crash on Google Colab

### ISSUE THREAD

**Issue by ruipedrodias94** [lllyasviel/Fooocus#1175]
**Describe the problem**
When trying to use Faceswap feature in Google Colab, the app crashes. 

**Full Console Log**
`Image generated with private log at: /content/Fooocus/outputs/2023-12-04/log.html
Generating and saving time: 30.31 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.85 seconds
Total time: 70.66 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 51281143977912873
[Fooocus] Downloading control models ...
[Fooocus] Loading control models ...
^C`

**Comment by cad1231** [comment]
If you are using the free version of Google Colab, there is not enough RAM for faceswap. You need the paid version, and then go to 'change runtime type' and make sure that 'high RAM' is turned on. You don't need to change anything else. 50 compute units that you get with a monthly subscription should last you 20-30 hours of processing time.

**Comment by RukshanJS** [comment]
> If you are using the free version of Google Colab, there is not enough RAM for faceswap. You need the paid version, and then go to 'change runtime type' and make sure that 'high RAM' is turned on. You don't need to change anything else. 50 compute units that you get with a monthly subscription should last you 20-30 hours of processing time.

That's a nice answer. Could someone kindly add this to the Readme under the colab section?

**Comment by tbuyle** [comment]
Try changing the last line of the colab with :

`!python entry_with_update.py --share --preset --always-high-vram --all-in-fp16`

See also https://github.com/lllyasviel/Fooocus/issues/1377

**Comment by Damarcreative** [comment]
Always monitor RAM and GPU usage,
By default, using normal VRAM will make your RAM full and will stop.
since GPU usage is quite low, try adding `--highvram` parameter this will decrease RAM usage and increase GPU slightly.
![Screenshot from 2023-12-25 11-08-45](https://github.com/lllyasviel/Fooocus/assets/106896172/8f46c16f-2ece-41e0-b9de-12b5e9f862c2)
