### ISSUE TITLE
No module named 'pygit2'

### ISSUE THREAD

**Issue by komisia** [lllyasviel/Fooocus#1177]
Hi,

I have **pygit2** issue on launch

command "**python3 entry_with_update.py**" returns this:

```
Update failed.
No module named 'pygit2'
Update succeeded.
[System ARGV] ['entry_with_update.py', '--listen']
Traceback (most recent call last):
  File "entry_with_update.py", line 46, in <module>
    from launch import *
  File "/home/paperspace/Fooocus/launch.py", line 22, in <module>
    from modules.config import path_checkpoints, path_loras, path_vae_approx, path_fooocus_expansion, \
  File "/home/paperspace/Fooocus/modules/config.py", line 7, in <module>
    import modules.sdxl_styles
  File "/home/paperspace/Fooocus/modules/sdxl_styles.py", line 5, in <module>
    from modules.util import get_files_from_folder
  File "/home/paperspace/Fooocus/modules/util.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

- Python 3.8.10
- Ubuntu 20.04

**Comment by Crncodesallsortsofthings** [comment]
I had the same issue, it originates from an error when running pip install -r requirements_versions.txt. Cython 3.0.0 incompatibility has caused this error in the past, but I'm not sure as to whether this is the case this time.

**Comment by dgelormini** [comment]
On my Mac, it seems like this was an issue with python 3.12. I ran `python3.11 entry_with_update.py` and it worked 🤷

**Comment by johnnyhperkins** [comment]
I had to install two missing modules with pip (for me it was `pygit2` then `packaging`). After that I ran and it started but with an error. I closed, reran, and now it's working

**Comment by dmitrysinev** [comment]
I had this problem on my MacM1
I just forgot to run conda: `conda activate Fooocus`
Once I ran it, everything worked!

**Comment by mashb1t** [comment]
Make sure to use Python 3.10 (3.11 might also work, but not officially supported) with the latest version of Fooocus.

**Comment by DimplesApplepie** [comment]
> On my M1 Macbook pro, it seems like this was an issue with python 3.12. I ran `python3.11 entry_with_update.py` and it worked 🤷

you're my hero ! works to for my mac mini M2 pro, I was stuck on that stuff for hours lol
