### ISSUE TITLE
Why am I getting a Certificate_Verify_Failed error when runnig entry_with_update?

### ISSUE THREAD

**Issue by bostrovsky** [lllyasviel/Fooocus#1188]
On a M1 Mac. I'm sure this is a dumb thing but I don/'t know where to tell it to ignore the verify.  How do I get past this?

Thx

**Comment by Thribs** [comment]
had this issue on a Windows machine

**Comment by Thribs** [comment]
not really a solution. More like a work-around.
Since The problem happened downloading the [checkpoint model](https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_version6Rundiffusion.safetensors), I downloaded it manually and it worked

**Comment by mashb1t** [comment]
Please use the latest version of Fooocus and follow https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#ssl-certificate_verify_failed
