### ISSUE TITLE
No Cuda GPU available Runtime Error

### ISSUE THREAD

**Issue by Greczy** [lllyasviel/Fooocus#1189]
Whenever i run any of the launcher it starts as normal but as soons as is start generating i get a runtime error: no cuda gp available. My gpu in this setup is a 1060 6gb and my i am getting this wrong but his gpu has somecuda cores. I am kinda confused why it tells me there are no cuda GPUS available. Ram is DDR4 16gb and i am using an i5-6500.
Thanks in advance.
![Unbenannt](https://github.com/lllyasviel/Fooocus/assets/99214010/e9f7d0d8-9d62-414e-b9b8-f62a4276ae50)

**Comment by Greczy** [comment]
So i fixed it. My PC simply shut down my gpu due to some error just needed to reactivate in the device manager.

**Comment by tabasc** [comment]
I have the same issue and my GPU is fully functional.

**Comment by pidori-ne-poluchat-parol** [comment]
I just changed my old nvidia geforce gt 1030 graphics card to vioco rx 580 8gb and I have this problem, I don't know how to solve it...

**Comment by hpbdesign1esOG** [comment]
Hi all,
I get this error too: RuntimeError: NO CUDA GPUs are available

Any solution please, exept a nother card?

Kind regards
Hans Peter Betzler

**Comment by pidori-ne-poluchat-parol** [comment]
> Hi all, I get this error too: RuntimeError: NO CUDA GPUs are available
> 
> Any solution please, exept a nother card?
> 
> Kind regards Hans Peter Betzler

I got an error after installing the amd graphics card, and the readmi wrote that I need to add part of the code to the run file, so what does my realistic look like:
![image](https://github.com/lllyasviel/Fooocus/assets/145602254/d32f70e9-f62d-4a97-b92b-53155698dd50)
