### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by lqz2** [lllyasviel/Fooocus#1191]
May I ask how the python_embeded folder is obtained in the windows version deployment, I would like to try to deploy some models in a similar way.

**Comment by mashb1t** [comment]
You can simply download and use Fooocus with the zip file from https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windows.
Embedded Pyhon Wiki for further stand-alone embedded usage: https://wiki.python.org/moin/EmbeddedPython
