### ISSUE TITLE
Temp files kept stored in /var/folders/ are not cleaned on quit

### ISSUE THREAD

**Issue by basvdijk** [lllyasviel/Fooocus#1195]
**Describe the problem**
All generated images are found in the `output` folder. However it turns out that on my Mac the temporarily files are still in the `/var/folders/7x/qp92ltkd4glfhjc8d2lyb0m00000gn/T/gradio`

![image](https://github.com/lllyasviel/Fooocus/assets/644550/5a2a7173-13f6-467b-a94d-0627034a3915)

**Full Console Log**
n/a

**Comment by mashb1t** [comment]
Nothing to worry about. If you do nothing, system processes will periodically clean these folders of files that have not been accessed for three days, so you should not have have to do anything, unless you are running very low on storage.

See explanation in https://magnusviri.com/what-is-var-folders.html and https://macpaw.com/how-to/access-var-folder-mac

**Comment by basvdijk** [comment]
Generating lots of images easily eats lots of disk space. I would prefer another location which I can for example symlink to an external disk. Now I am forced to dig in the var folder.

**Comment by mashb1t** [comment]
Please test if setting the arg `--temp-path` works for you.
See https://github.com/lllyasviel/Fooocus/blob/main/ldm_patched/modules/args_parser.py#L43
