### ISSUE TITLE
Unable to generate image in Fooocus.

### ISSUE THREAD

**Issue by danteocualesjr** [lllyasviel/Fooocus#1196]
**Describe the problem**
I've tried using Fooocus today. I followed the steps here and downloaded SDXL (I'm using Mac): https://github.com/lllyasviel/Fooocus

When running the 'python entry_with_update.py' command, it takes me to http://127.0.0.1:7865/ but when clicking on "Generate", no image is generated (see screenshot below).

<img width="1792" alt="Screenshot 2023-12-05 at 3 55 09 PM" src="https://github.com/lllyasviel/Fooocus/assets/35713996/c6a341d6-36f6-4f6a-80b5-627e85476aa1">

**Full Console Log**
RuntimeError: MPS backend out of memory (MPS allocated: 6.49 GB, other allocations: 298.97 MB, max allowed: 6.77 GB). Tried to allocate 20.00 KB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
Total time: 57.06 seconds

**Comment by Krupakar-Reddy-S** [comment]
I am new to using Fooocus, but i think this just means that your system does not have enough memory to load the dependent ML modules like Pytorch or the image generation Model itself, or your OS has restricted its memory usage.

**Comment by danteocualesjr** [comment]
Do you know how I can free up my memory? These are the specs in my MacBook:

Memory: 16 GB 2667 MHz DDR4
Storage: 306.27 GB available of 499.96 GB

Looks like I have enough space so I'm confused why it's throwing an error.

**Comment by mohanvaidya** [comment]
After running the run.bat it downloaded a 6.64G file and now it took me to Fooocus 2.1.854 and when generating an image it shows an error. please tell me how I can fix this error.
![Screenshot (41)](https://github.com/lllyasviel/Fooocus/assets/131249018/66c48ada-209d-446b-8d7a-661c062dfabb)

**Comment by Amit30swgoh** [comment]
> After running the run.bat it downloaded a 6.64G file and now it took me to Fooocus 2.1.854 and when generating an image it shows an error. please tell me how I can fix this error. ![Screenshot (41)](https://private-user-images.githubusercontent.com/131249018/292408302-66c48ada-209d-446b-8d7a-661c062dfabb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MjU1MzUsIm5iZiI6MTcwMzQyNTIzNSwicGF0aCI6Ii8xMzEyNDkwMTgvMjkyNDA4MzAyLTY2YzQ4YWRhLTIwOWQtNDQ2Yi04ZDdhLTY2MWMwNjJkZmFiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxMzQwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzdiOGQ1OTA2MjQxNWNjMWMwMDVlYjNiZGY3Nzk4YmQ3ZDQ0ZGYzMWNlZGZhNDUzOTE2MDFmYjY3OTEwNDU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-ib6bpPXg19CJ_c6Q-B1FeD0es1frKJrkdqxoh7NN9I)

same problem and noone heres help

**Comment by Amit30swgoh** [comment]
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/187d628e-c09e-4bd0-9baa-0c1f832d2d7f)
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/c0df623e-c7b1-456f-8d47-24ddcab55c20)
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/4564c73d-e201-4c94-859d-3b83a7414c99)
 anyone in the world ever had or know or can help about this problem ? do i need to send you 1000$ to help me ?

**Comment by mashb1t** [comment]
Solution: see https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#system-swap and https://github.com/lllyasviel/Fooocus/issues/1139
@Amit30swgoh 1000$ pls XD

**Comment by Amit30swgoh** [comment]
> Solution: see https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#system-swap and #1139 @Amit30swgoh 1000$ pls XD

Ohhh its old msg didnt close it 1000$ 💕💕💕
