### ISSUE TITLE
Image generation saving location

### ISSUE THREAD

**Issue by shutter-cat** [lllyasviel/Fooocus#12]
Can we have default image generation save location to app folder? I find it very inconvenient that it just save everything in gradio temp, if there some option that i'm missing please let me know.

**Comment by lllyasviel** [comment]
fixed in 1.0.16
https://github.com/lllyasviel/Fooocus/blob/main/update_log.md
launch with "run.bat" to update

**Comment by shutter-cat** [comment]
> fixed in 1.0.16 https://github.com/lllyasviel/Fooocus/blob/main/update_log.md launch with "run.bat" to update

great, thanks for your work!
