### ISSUE TITLE
Line breaks in prompt words convert commas into semicolons, resulting in semantic changes

### ISSUE THREAD

**Issue by xhoxye** [lllyasviel/Fooocus#1200]
**Describe the problem**
Line breaks in prompt words convert commas into semicolons, resulting in semantic changes

**Full Console Log**

**Comment by mashb1t** [comment]
Please elaborate and add a screenshot / your meta data to be able to support you better.

**Comment by xhoxye** [comment]
After the version is updated, there are changes,"/n"

**Comment by mashb1t** [comment]
> Please elaborate and add a screenshot / your meta data to be able to support you better.

I don't get it, do you mean the changes to the meta data copy function in https://github.com/lllyasviel/Fooocus/commit/cce73d28b49a0dabecd45caa8eacc28e72c15ac6?
Please point me to the changes which are not working for you or provid a screenshot. Thanks.

**Comment by xhoxye** [comment]
Thankfully, the new version doesn't have this problem anymore.
