### ISSUE TITLE
Where can I find the log?

### ISSUE THREAD

**Issue by cheshirecat8** [lllyasviel/Fooocus#1207]
I keep getting errors while trying to generate an image but the cmd doesn't describe the problem, it just stops and says "press any key to continue" . Where can I find a full log for each of my attempts?

**Comment by mashb1t** [comment]
The terminal is the log. If this is still relevant, please provide the full terminal output in order to be able to determine next steps and to help you.

**Comment by mashb1t** [comment]
Closing as stale, feel free to reopen when providing new information.
