### ISSUE TITLE
AttributeError: property 'mode' of 'JpegImageFile' object has no setter

### ISSUE THREAD

**Issue by Kunapoo88** [lllyasviel/Fooocus#1211]
**Describe the problem**
After program starts and I add my prompt and reference image and then hit generate I get an error on screen (no image just error)

**Full Console Log**
AttributeError: property 'mode' of 'JpegImageFile' object has no setter

**Comment by Kunapoo88** [comment]
Fix the issue; recompiled the project; there were some missing dependencies... 0;)

**Comment by BKazimy** [comment]
how did you installed the dependencies?
