### ISSUE TITLE
Loading 1 New Model on Each Generation

### ISSUE THREAD

**Issue by Astra060** [lllyasviel/Fooocus#1212]
Hello everyone. The project is great but has a great problem, for me it loads the model *each time* I generate a new image. I get it if you want to use less system resources, however loading the model in each time is the most time consuming part of this program for me right now. Having a flag which prevents this would be really welcome.

**Comment by mashb1t** [comment]
@Astra060 this can be prevented by using teh existing args (flags) `--always-gpu` or `--always-high-vram`, depending on your GPU VRAM. I'd recommend to have at least 12GB VRAM to effectively benefit from either option.
See https://github.com/lllyasviel/Fooocus/blob/main/ldm_patched/modules/args_parser.py#L96-L97
