### ISSUE TITLE
What is the best way to generate a 1920x1080 image?

### ISSUE THREAD

**Issue by IamTirion** [lllyasviel/Fooocus#1215]
Sorry I am a bit new to this. What is the best way to generate a 1920x1080 image? Like, which resolution should I start from? Then, should I outpaint to 1920x1080? Or should I upscale and crop? Personally my experience with cropping is bad because you may cut away areas you want.

**Comment by PumpkinSheee** [comment]
open developer tools and scroll till u see soming along the lines of "bypass width limit" or something like that, below it should be a vertical one too, its automatically on -1 so just set width to 1920 and height to 1080 and yeah

**Comment by IamTirion** [comment]
Ok thanks, but is that the best way to get a 1920x1080 image? I heard it's best to start with a resolution that SDXL was trained on and then use outpainting or upscaling to get the resolution I want.

**Comment by PumpkinSheee** [comment]
I mean it worked fine for me, imo it is the best way

**Comment by mashb1t** [comment]
> Ok thanks, but is that the best way to get a 1920x1080 image? I heard it's best to start with a resolution that SDXL was trained on and then use outpainting or upscaling to get the resolution I want.

Exactly this. You can find more information here: https://github.com/lllyasviel/Fooocus/pull/1617
