### ISSUE TITLE
It just sits on "Waiting for task to start"

### ISSUE THREAD

**Issue by yellowskipants** [lllyasviel/Fooocus#1216]
Having the same problem here, anybody got a fix for "Waiting for task to start"?

_Originally posted by @GlennWoodward in https://github.com/lllyasviel/Fooocus/issues/129#issuecomment-1838380550_

**Comment by isThatAFife** [comment]
Same issue here.

**Comment by YancyFrySr** [comment]
same here

**Comment by skclayton** [comment]
^

**Comment by akreil** [comment]
I had the same(?) issue while I was trying this application for the first time.

I had downloaded the installation folder, unzipped it, then run the run.bat file.
A console indicated that it was downloading the models, then "App started successful.  Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865".
At that moment, my web browser was displaying the application web page.
I typed some key word then press Generate.
It got stuck with the message "Waiting for task to start".

Well, the console was still opened, so I tried to just press Enter in that console and it unlocked the "tasks".
=> Problem solved for me. (I don't know if your problem was the same)

I would suggest to the developers to add a little message "Press Enter to continue" after the message "App started successful. [...]" :-).

**Comment by brinkqiang** [comment]
可能不识别中文？

**Comment by sonusingh** [comment]
I am using LambdaLabs with public link on gradio.live and it is stuck on "waiting for task to start"

**Comment by Virtuxdev** [comment]
> Having the same problem here, anybody got a fix for "Waiting for task to start"?
> 
> _Originally posted by @GlennWoodward in [#129 (comment)](https://github.com/lllyasviel/Fooocus/pull/129#issuecomment-1838380550)_

hey, i have the same problem, but usin a custom model checkpoint, when i use any model that is not juggernaut it just sits on "Waiting for task to start", using juggernaut didnt have problems at all.

**Comment by IamTirion** [comment]
> > Having the same problem here, anybody got a fix for "Waiting for task to start"?
> > _Originally posted by @GlennWoodward in [#129 (comment)](https://github.com/lllyasviel/Fooocus/pull/129#issuecomment-1838380550)_
> 
> hey, i have the same problem, but using a custom model checkpoint, when i use any model that is not juggernaut it just sits on "Waiting for task to start", using juggernaut didnt have problems at all.

I have this problem while using Juggernaut.

**Comment by lllyasviel** [comment]
hello, one may look at https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
or if still does not work, paste full log for us to take a look

**Comment by IamTirion** [comment]
> hello, one may look at https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md or if still does not work, paste full log for us to take a look

It does not work for me. I have already increased my System Swap to 40Gb. However, in Automatic1111, disabling the memmapping for safetensors worked for me. May I ask if such option exists in Fooocus?

**Comment by IamTirion** [comment]
Enter LCM mode.
[Fooocus] Downloading LCM components ...
[Parameters] Adaptive CFG = 1.0
[Parameters] Sharpness = 0.0
[Parameters] ADM Scale = 1.0 : 1.0 : 0.0
[Parameters] CFG = 1.0
[Parameters] Seed = 1389215022623263936
[Parameters] Sampler = lcm - lcm
[Parameters] Steps = 8 - 8
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['conditioner.embedders.0.logit_scale', 'conditioner.embedders.0.text_projection', 'conditioner.embedders.1.model.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Base model loaded: D:\Fooocus\Fooocus\models\checkpoints\albedobaseXL_v13.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0], ('sdxl_lcm_lora.safetensors', 1.0)] for model [D:\Fooocus\Fooocus\models\checkpoints\albedobaseXL_v13.safetensors].
Loaded LoRA [D:\Fooocus\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [D:\Fooocus\Fooocus\models\checkpoints\albedobaseXL_v13.safetensors] with 788 keys at weight 0.1.
Loaded LoRA [D:\Fooocus\Fooocus\models\loras\sdxl_lcm_lora.safetensors] for UNet [D:\Fooocus\Fooocus\models\checkpoints\albedobaseXL_v13.safetensors] with 788 keys at weight 1.0.
Requested to load SDXLClipModel
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.65 seconds
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] Eva Green, very coherent, symmetry, charismatic, sharp focus, cinematic, highly detailed, elegant, creative, color deep background, light great composition, intricate, innocent, novel, romantic, stunning, aesthetic, fine, sublime, extremely inspirational, beautiful, epic, artistic, inspiring, thoughtful, vibrant, best, awesome, perfect, singular, cute, brilliant, inspired
[Fooocus] Encoding positive #1 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1080, 1920)
Preparation time: 231.73 seconds
Using lcm scheduler.
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.39970141649246216, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 2.02 seconds
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.39it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.18 seconds
Image generated with private log at: D:\Fooocus\Fooocus\outputs\2023-12-13\log.html
Generating and saving time: 12.05 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.64 seconds
Total time: 245.78 seconds

**Comment by lllyasviel** [comment]
log indicates that the hdd disk is too old and may have some problems 
put the model on a healthy disk may help but the best is using ssd 
@IamTirion

**Comment by IamTirion** [comment]
> log indicates that the hdd disk is too old and may have some problems put the model on a healthy disk may help but the best is using ssd @IamTirion

Oh ok. Thank you so much. Indeed my entire computer is like 5 years old. Is that pretty old?

**Comment by minchan-developer** [comment]
i have the same issue it says " waiting for the task to start" here is my log

D:\Downloads\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.855
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 4096 MB, total RAM 15791 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --always-normal-vram
Set vram state to: LOW_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce GTX 1650 : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816

**Comment by mashb1t** [comment]
@ronnyskog @minchan-developer The reason why your disks are highly being used is that your VRAM is most likely exhausted (4GB switching to low vram mode automatically) and your RAM is outsourced to swap.
Please check if it works after a few minutes or if Fooocus crashes and keep us posted.

**Comment by AnatoliW** [comment]
Having same Issue with Mac M2 Pro

**Comment by kirannadukandi** [comment]
Running Fooocus on my old i3 provessor with Nvidia MX130. 8 Gb RAM. Had the same issue of "witing for the process to start" and it waits for ever. Then I teied the --always-low-vram. This took it to next step to UNet and keeps halting there indefnitely. Waited a day and half to see if there could be any possible progress but no hope. 

I was not ready to give up so tried to run it with AMD argument in the run.bat file

 .\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
.\python_embeded\python.exe -m pip install torch-directml
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml
pause 

and it worked. But its veeeeery veeeery slow.

**Comment by mashb1t** [comment]
Gist: use GPU with sufficient VRAM / power and when using swap, best use an SSD.

**Comment by valerymihaylov** [comment]
I have the same problem, stuck on Waiting for task to start ... In the console I have this error:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/valery/Downloads/Projects/ai/Fooocus/modules/async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "/Users/valery/Downloads/Projects/ai/Fooocus/modules/default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "/Users/valery/Downloads/Projects/ai/Fooocus/modules/core.py", line 1, in <module>
    from modules.patch import patch_all
  File "/Users/valery/Downloads/Projects/ai/Fooocus/modules/patch.py", line 8, in <module>
    import modules.anisotropic as anisotropic
  File "/Users/valery/Downloads/Projects/ai/Fooocus/modules/anisotropic.py", line 10, in <module>
    def _compute_zero_padding(kernel_size: tuple[int, int] | int) -> tuple[int, int]:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'type'

**Comment by mashb1t** [comment]
@valerymihaylov you have to use min. Python 3.10

**Comment by yaohuiwu** [comment]
> I had the same(?) issue while I was trying this application for the first time.
> 
> I had downloaded the installation folder, unzipped it, then run the run.bat file. A console indicated that it was downloading the models, then "App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865". At that moment, my web browser was displaying the application web page. I typed some key words then press Generate. It got stuck with the message "Waiting for task to start".
> 
> Well, the console was still opened, so I tried to just press Enter in that console and it unlocked the "tasks". => Problem solved for me. (I don't know if your problem was the same)
> 
> I would suggest to the developers to add a little message "Press Enter to continue" after the message "App started successful. [...]" :-).

I enter a ctrl + C and then it's suddenly starting to generate the image for me.

**Comment by afterploid** [comment]
Similar problem, the computer is not weak, configuration:
Core i9 12900HX
RAM 64gb
Dedicated NVME SSD 512GB only for SIMPLESDXL
Nvidia RTX4060ti 16gb VRAM
![Screenshot_1](https://github.com/user-attachments/assets/003e8f00-846c-4be1-bd88-b04e9136f71f)
