### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

### ISSUE THREAD

**Issue by MiroslavGeorigev** [lllyasviel/Fooocus#1227]
Is there a way to use Fooocus from an Intel GPU. Was looking in the read.me section, but found no information about it. 
Thanks in advance!

**Comment by Manraj-Mann** [comment]
same issue as @MiroslavGeorigev

**Comment by ezrabehr** [comment]
same here

**Comment by mashb1t** [comment]
Please follow https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
