### ISSUE TITLE
Creating variation from my images

### ISSUE THREAD

**Issue by lastshepherd** [lllyasviel/Fooocus#1233]
Is there a possibility to create variations based on the 50 HQ self-portrait images that I have?

**Comment by acvcleitao** [comment]
yes, click on input image, bellow the text prompt, and a "upscale or variation" tab should pop up. Insert an image there and use the other 50 HQ as a LoRa, it should do the trick

**Comment by renant** [comment]
> @renant please check out the tutorials on https://github.com/bmaltais/kohya_ss

Thanks @mashb1t !

In the meantime, I made my LoRa with kohya_ss, but I didn't understand how to use it.
