### ISSUE TITLE
Question. Fooocus and Vast.ai

### ISSUE THREAD

**Issue by Acero-AD** [lllyasviel/Fooocus#1234]
Hi!

Does anyone have a template for using Fooocus in vast.ai? I see they have for stable diffusion web ui but I prefer fooocus simplicity.

**Comment by mashb1t** [comment]
In https://cloud.vast.ai/templates/  you can find 5 templates for Fooocus, the one from ashleykza/fooocus (on the bottom, named Cuda:12.0.1-Devel-Ubuntu20.04)
uses https://github.com/ashleykleynhans/fooocus-docker, which you might try.

**Comment by robballantyne** [comment]
This repo has cloud compatible docker images with Auth etc https://github.com/ai-dock/fooocus
