### ISSUE TITLE
Lora's arent working

### ISSUE THREAD

**Issue by Toiletduck34** [lllyasviel/Fooocus#1238]
I have been creating my own or downloading Lora's from Civitai to test and no matter the strength or promps i add they are not effecting the outcome of the generated image.  

is there something i am missing that i need to activate? Yes i am selecting them in advanced settings.

**Comment by Dsnaps77** [comment]
Im having the same issue. No matter how many loras i try I still cant get them to work. No error message or anything.

**Comment by stubkan** [comment]
Make sure you are using SD XL loras since Fooocus comes with Juggernaut which is SDXL base model.

95% of loras on civitai are for SD 1.5, are you checking for that?

**Comment by Dsnaps77** [comment]
Stubkan thank you so much for the reply. I had no idea it couldnt read SD 1.5 loras :( any advice or a website that could possibly provide more sdxl loras? Or a way to convert them? Thanks again

**Comment by stubkan** [comment]
civitai does have sdxl loras, just look for the XL on the thumbnail

![image](https://github.com/lllyasviel/Fooocus/assets/34361592/3502affd-ac16-4358-b3f6-9ea4143af88e)

1 and 2 are XL but 3 is not

![image](https://github.com/lllyasviel/Fooocus/assets/34361592/259b7f53-f384-472d-9f46-81fecdaffb17)

Also the model info card will tell you which base model it used (SDXL)

**Comment by Dsnaps77** [comment]
You are flipping awesome thank you. Ill give it a shot today!

**Comment by GodJami** [comment]
I can't get SD 1.5 to work either but on their update log it says: "2.1.782 is mainly an update for a new LoRA system that supports both SDXL loras and SD1.5 loras."
So SD 1.5 loras should work normally?

**Comment by stubkan** [comment]
You only can use SDXL loras with SDXL base model, the default model is Juggernaut which is a SDXL model.

Make sure you are selecting a SD 1.5 base model when you try to use SD 1.5 loras.

**Comment by lllyasviel** [comment]
SD 1.5 loras are supported if you use SD1.5 as refiner.

**Comment by gabrielmicko** [comment]
> I can't get SD 1.5 to work either but on their update log it says: "2.1.782 is mainly an update for a new LoRA system that supports both SDXL loras and SD1.5 loras." So SD 1.5 loras should work normally?
It doesn't work for me either I would be interested to know, if I am doing something wrong or how to make it work.

**Comment by mashb1t** [comment]
As of my latest test, SD 1.5 LoRAs do work to an extend but in general the generated image quality is nowhere close to using another project with native SD 1.5 support such as A1111 or Comfy.
You can override these settigns to make it work best:
* Refiner Switch At (set as low as possibvle or override in Developer Debug Mode with "Forced Overwrite of Refiner Switch Step" = 1
* Forced Overwrite of Generating Width => 512 / 768
* Forced Overwrite of Generating Height => 512 / 768

**Comment by theredwillow** [comment]
The refiner trick doesn't work unless you have enough GPU VRAM to hold both models, even if you have it set to much smaller. This makes the tool impossible to use. I will be making the switch to a different WebUI until SD1.5 is supported.

**Comment by Chrisocal21** [comment]
Trying to add loras to the model folder but just shows a circle with a x or doesn't show the paste button.. I also have two folders for fooocus one has the Run files in it that i cannot edit or paste the loras into and the other one i can paste the loras into but there is no run. and last i checked they didn't pick up the loras i placed in it... anyone see this before? any help is greatly appreciated

**Comment by mashb1t** [comment]
I can't really follow your description as your message is a bit cryptic to me. Please find the LoRAs folder in models > loras or if you changed it in the config to put your files there.
If you need further assistance please open a discussion in the Q&A category.

**Comment by airevolution69** [comment]
Hey guys, I've been running the program on Colab, I've been trying to use different Loras, but when I try to generate an image I get this error: 

ValueError: Error while deserializing header: MetadataIncompleteBuffer
File corrupted: /content/Fooocus/models/loras/2FingersSDXL_v03.safetensors 
Fooocus has tried to move the corrupted file to /content/Fooocus/models/loras/2FingersSDXL_v03.safetensors.corrupted 
You may try again now and Fooocus will download models again. 


I just added the loras file on the loras folder inside models, then select it on the dropdown menu in models, tried to generate the image, but didn't get any result and the above error message in the console. 

Any help would be really appreciated, thank you

**Comment by mashb1t** [comment]
> ValueError: Error while deserializing header: MetadataIncompleteBuffer

@airevolution69 the LoRA doesn't seem to follow standards for metadata description as you can see in the error message. Please ensure it's been trained correctly and follows an official metadata format.
