### ISSUE TITLE
Slow image generation, wish to confirm only

### ISSUE THREAD

**Issue by AnmolSaksena** [lllyasviel/Fooocus#1240]
the problem is pretty simple, it takes about 12-15 minutes for fooocus realistic to generate one image
my specs are as follows-
24gb ram
geforce gtx 1650 Ti
i just want to be sure that this is the fault of my laptop and not something i'm doing wrong
it takes a long time to shift the model to gpu, but it makes the image pretty fast, how can i decrease the time for the shift?

**Comment by abomonov** [comment]
The problem is in your video card, you need a video card helper for example rtx 3060 12gb + CUDA the speed of picture generation will be up to 1-2 minutes.

**Comment by mashb1t** [comment]
As soon as your VRAM is fully used the system memory will be used, which is significantly slower (talking about 80x slower).
Your 1650 TI only has 4GB of VRAM, which means that more than half of the needed capacity is moved to RAM.
For SDXL it's recommended to use at least a GPU with 8GB of VRAM to keep the model on the GPU memory at the time of generation.
Using --lowvram might only help so much and is enabled by default, if Fooocus detects that you have too little VRAM for normal mode, but still might not be enough for you to be able to reasonably use Fooocus.

**Comment by AnmolSaksena** [comment]
thanks, in that case, i'm okay with it, it's not the fastest in the world, but it produces really good images
