### ISSUE TITLE
Not sure what I am doing wrong but getting connection errored out again and again

### ISSUE THREAD

**Issue by dhruvbaslas** [lllyasviel/Fooocus#1244]
![image](https://github.com/lllyasviel/Fooocus/assets/26743929/88321a70-28fc-4ff6-a785-9863cffa03df)

**Comment by Ragnarok700** [comment]
> What's the CLI output

You can see bunch more details of us having this issue over here at https://github.com/lllyasviel/Fooocus/issues/1112

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
