### ISSUE TITLE
Fooocus will never add anything to your generated image file.

### ISSUE THREAD

**Issue by lllyasviel** [lllyasviel/Fooocus#125]
This is an announcement that Fooocus will not implement png meta (recording the prompts and parameters in your png file). The reasons are:

1. Whether or not to record/share prompts is user’s freedom. Although a small group of advanced fans are familiar with Automatic1111/ComfyUI’s features to record prompts in images, a dominant majority of real users from industry and entertainment do not know this. Writing prompts and configurations to the image will damage those majority people’s privacy, rights, and well-being.

2. The format of PNG meta has been abused by many SD software to bind users with specific tools. This is contradictory to Fooocus’s call for “exploring new mediums of thought and expanding the imaginative powers of the human species”. Fooocus is committed to eliminate the barriers between different software/workflows and encouraging users to share prompts (or random seeds) directly by writing it down in texts.

Revision 2023 Aug 16:

We appreciate community feedbacks and please take a look at the new feature ["Fooocus Private Log"](https://github.com/lllyasviel/Fooocus/discussions/160).

**Comment by theelefant** [comment]
If there's no intention to embed the generation parameters within the PNGs (though I'm unclear on the reasoning you provided above), it would be beneficial to have access to the seed used for the images, especially since it's not currently visible in the UI.

**Comment by lllyasviel** [comment]
seed restoring will be implemented soon hopefully

**Comment by lllyasviel** [comment]
> Too bad, this is a must have feature for me that could be opt-in. Imo it makes no difference for other tools if there's metadata or not as they can't import either. I'll still recommend Fooocus to people who want something super easy to use.

Thanks for the feedback! 
We want to make sure that every time you open Fooocus, everything is absolutely private and clean.

**Comment by MonsterAzi** [comment]
This makes it difficult to recreate images, figure out why one worked, or share prompts with others. And yes, you could just manually write down the prompts, loras, resolution, and seed down every single time you generate an image, but this is obviously difficult and would go against the goal of ease-of-use.

I understand the privacy concerns, but it should at least be an option one can turn on, if they want. I am very disappointed and hope this feature is reconsidered.

**Comment by ke1ne** [comment]
@lllyasviel with no forcing at all, as some alternative, I would humbly propose to generate some txt with the same filename or json (history?)
thanks for your work!

**Comment by Acephalia** [comment]
> @lllyasviel with no forcing at all, as some alternative, I would humbly propose to generate some txt with the same filename or json (history?)
> thanks for your work!

+1 

@lllyasviel I can understand and accept your reasoning not to embed details within a file. 

However having the data saved somewhere a user can access privately is invaluable given the nature of the whole shebang. Giving a user the choice whether to save this data will further strengthen your position (imho) as opposed to a hard cap no. 

After all choice is what empowers us to explore and shape our imaginative worlds and every explorer needs a log. :)

**Comment by Kizzyme** [comment]
I appreciate the privacy.  thank you @lllyasviel

**Comment by barepixels** [comment]
If you don't want the meta, all you have to do is open and save with Photoshop.  It will replace with Adobe meta.
How about having a checkmark, save meta, yes or no.

Meta is very important to remember and continue the project months from now.  Am getting older, and can't remember how I did what last month.

**Comment by poweredjj** [comment]
Well, I had fun generating great images, while waiting for generation data saving feature.
You could add a switch somewhere inside "advanced" options - this way you would not force anyone to use it.

So... I sure hope that A1111 / Comfyui will reach this kinda quality soon.

**Comment by tamal777** [comment]
Just make an option in the advance settings which we can toggle ON or OFF. I like you use the metadata to track my prompts and settings for the images I have generated.

**Comment by That-Dude** [comment]
I understand the privacy concern, and I fully agree that privacy should always be the default.

But making this an optional advanced feature (with warning message), or writing the data to a separate json file should be an option for creatives that need to keep track of their settings.

Generating a prompt to create an image that you love can be hard work, and losing that data is painful. It also makes it much harder to share prompts online, which is how many  of use get started.

**Comment by MoonRide303** [comment]
@lllyasviel It's OK to have it disabled by default, but it's also OK - for people who consiously want that - to save their prompt in the output file, and not have to manually copy-paste prompt, seed, and other settings. When it's implemented as opt-in (disabled by default, like in my pull request above) it doesn't violate user privacy, and is useful quality-of-life feature.

For people interested in having more configuration options - I merged that change into my fork ([moonride-main](https://github.com/MoonRide303/Fooocus/tree/moonride-main)).

**Comment by shingo1228** [comment]
I agree with the idea of not embedding meta-information in the generated image file, and I suggest that it be stored in a json file with the same file name as the generated image. "[pull-request #154 ](https://github.com/lllyasviel/Fooocus/pull/154)"
However, I thought it would be better to do the specific implementation in "async_worker.py" like @MoonRide303 's implementation."[pull-request #152 ](https://github.com/lllyasviel/Fooocus/pull/152)"

**Comment by shingo1228** [comment]
> Please don't do the store in a json. It's messy having to manage double the number of files

Hmmm, you make a good point. We certainly generate a lot of image files.

**Comment by MoonRide303** [comment]
@shingo1228 I updated my pull request to include your idea, and all 3 options are now available depending on what you need - saving metadata disabled (the default), saving it in separate JSON file, and embedding it in PNG file.

**Comment by lllyasviel** [comment]
Revision 2023 Aug 16:

We appreciate community feedbacks and please take a look at the new feature ["Fooocus Private Log"](https://github.com/lllyasviel/Fooocus/discussions/160).

**Comment by That-Dude** [comment]
> Revision 2023 Aug 16:
> 
> 
> 
> We appreciate community feedbacks and please take a look at the new feature ["Fooocus Private Log"](https://github.com/lllyasviel/Fooocus/discussions/160).

This is ok but lacks the portability of embedded metadata. If one generates 200 images each day how does that work with the log expanding? Is it a scalable solution and transportable solution? EXIF is a well established standard and your dropping in favour of a proprietary option.

The proposed solution above already makes embedding metadata optional and disabled by default. If it needs to be secured further make the feature accessible only via a command line argument like a1111 and the "--allow-unsafe-plugins" option. 

As for not locking users into a proprietary system, the JSON format in the above solution is already universal. If it's added to the EXIF 'comment' field it's accessible in the file properties on all systems.

**Comment by lllyasviel** [comment]
This log can also do Ctrl+F; very convenient.

**Comment by That-Dude** [comment]
> This log can also do Ctrl+F; very convenient.

Sure thats a positive!

Do you have a view on the other points I raised?
