### ISSUE TITLE
Image Auto Save

### ISSUE THREAD

**Issue by AlbertDulaev** [lllyasviel/Fooocus#1250]
Is it possible to somehow automatically save images after generation to a folder specified to me, like in A1111? 

If this is not possible now, will it appear this function in future updates?)

**Comment by ForgetfulWasAria** [comment]
Neither of these is exactly what you're asking for but:
1) If you click on any generated image, in the upper right hand corner is a download button that should put the image where your browser downloads images
2) Inside of the folder Fooocus is another folder Fooocus and in that folder is a config.txt and config_modification_tutorial.txt. The line you want to change is path_outputs.  Here's mine.
```
"path_outputs": "A:\\ai_stuff\\outputs",
```

**Comment by mashb1t** [comment]
By default all images are saved to the outputs folder, so this is already implemented and working.
