### ISSUE TITLE
Best way to replace faceswap but keep everything else the same

### ISSUE THREAD

**Issue by nftcharm** [lllyasviel/Fooocus#1252]
Hello! 

I have two images where I want to swap the face of the first image with the face on the second image. I want to keep the second image how it is, besides the face. Background, Lighting, and the body should be the same. Or as similar as possible. 

How can I do that? Any tips?

Currently, I am uploading my two images at "input image". For the image where I want to replace the face, I'm using PyraCanny and for the image where I just want the face, I am selecting "Face Swap". I'm keeping the default settings in terms of weight and "Stop at". 

_Btw: What is "stop at" actually?_

And I am adding no prompt message. 
The result is most of the time an entirely different background or completely different clothes

**Comment by Phrixus2023** [comment]
https://www.youtube.com/watch?v=wOBcNPFuB70&t=29s

**Comment by kmastra** [comment]
@Phrixus2023 thanks looks very interesting!
His gui seems to have one more tab in advanced setting and one more checkbox right after prompt entry box, any ideas why?

**Comment by Phrixus2023** [comment]
> @Phrixus2023 thanks looks very interesting! Your gui seems to have one more tab in advanced setting and one more checkbox right after prompt entry box, any ideas why?

That's a community and resource feature for Chinese users, don't worry about it!

**Comment by Featurz** [comment]
Hello guys, I have followed the video but really I can't obtain my face swap like 100% real picture of me. Cause I use a picture of me and despite my tentative to make a face swap of me, the face is not like 100% my real face and idk why. I need to find the good setting for making it, any ideas friends ?

**Comment by stubkan** [comment]
Its faceswap.  Its not very good at all, impossible for me to get any faceswap that actually looks like the person.

I think faceswap should be removed and roop / reactor / faceswaplab is put in instead.

**Comment by Featurz** [comment]
Ok my bro thanks for your answer, how did they do for making the AI influencer Aitana ? Because the faceswap on her is good : https://www.instagram.com/fit_aitana/

**Comment by mashb1t** [comment]
See https://github.com/lllyasviel/Fooocus/issues/1329
