### ISSUE TITLE
Stuck at adm 2816

### ISSUE THREAD

**Issue by je4550** [lllyasviel/Fooocus#1254]
**Describe the problem**
execute run_realistic.bat
gets stuck on adm 2816

![image](https://github.com/lllyasviel/Fooocus/assets/2000975/07ad57e1-d3f8-492c-95f8-4829b7d7c2a0)

**Comment by mjunaidabbasi** [comment]
same here.,

**Comment by hash-mc** [comment]
same here

**Comment by mashb1t** [comment]
Please fimd the solution here: https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#adm-2816-then-stuck
