### ISSUE TITLE
Inpaint not showing up!

### ISSUE THREAD

**Issue by CarryPotterVI** [lllyasviel/Fooocus#1255]
**the problem**
Hi, i installed with the windows installer and downloaded the inpaint patch
if i click the input nothing happens.

with prompt
![Screenshot 2023-12-07 011901](https://github.com/lllyasviel/Fooocus/assets/102734489/d1ab0bb0-0836-4ae9-a040-513b06b902fc)

after run.batch
![Screenshot 2023-12-07 011625](https://github.com/lllyasviel/Fooocus/assets/102734489/7c83e3bb-9ba0-4d77-ae61-8312285a6fa7)

**Full Console Log after run.batch**
C:\#1.AI\Foocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 8192 MB, total RAM 32628 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra keys {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: C:\#1.AI\Foocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [C:\#1.AI\Foocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
iffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.36 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865

**Comment by mashb1t** [comment]
@CarryPotterVI please check your browser console, it seems like you either disabled JavaScript or there is a JS issue which prevents further scripts to be executed (see also non-styled radio button texts)

**Comment by CarryPotterVI** [comment]
I solved it. i reinstalled it and it seems like it doesn't work well when the path has a dot or a space in it.
