### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by KOWDOO** [lllyasviel/Fooocus#1258]
i'm on windows 10 
i think i installed everything correctly 
i'm not using any VPN or PROXY

![error2](https://github.com/lllyasviel/Fooocus/assets/150936272/af1eb55a-f076-4fc6-b72c-ddea066dae9d)

**Comment by Ragnarok700** [comment]
@KOWDOO same issue (duplicate) as reported here: https://github.com/lllyasviel/Fooocus/issues/1112

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
