### ISSUE TITLE
Error connected out  3X

### ISSUE THREAD

**Issue by v0in** [lllyasviel/Fooocus#1264]
**Describe the problem**

I keep getting this error (*Error connected out *) every time I try to generate a photo while it is moving model to GPU
I have 8GB of RAM, using a GTX 1650super 4GB. 

**Full Console Log**
![log](https://github.com/lllyasviel/Fooocus/assets/34402575/8fcdbc97-9caa-42a9-bfc4-10c94a2139bf)

additionally there is this in browser console
![image](https://github.com/lllyasviel/Fooocus/assets/34402575/06a50bd3-e341-4853-91ab-3a6836309d1f)

**Comment by mashb1t** [comment]
Please check if your swap had been set up as mentioned in https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md.

**Comment by v0in** [comment]
> Please check if your swap had been set up as mentioned in https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md.

 Thanks a lot. I adjusted the swap and it works now
