### ISSUE TITLE
Still don't understand where to type PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0  to disable the upper limit to fix the problem

### ISSUE THREAD

**Issue by briandamkroger21** [lllyasviel/Fooocus#1271]
### Discussed in https://github.com/lllyasviel/Fooocus/discussions/1156

<div type='discussions-op-text'>

<sup>Originally posted by **GondorGitaros** December  3, 2023</sup>
I am a total noob and I don't know where to type PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 and i get this error:

RuntimeError: MPS backend out of memory (MPS allocated: 8.89 GB, other allocations: 172.98 MB, max allowed: 9.07 GB). Tried to allocate 6.25 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
Total time: 129.38 seconds

</div>

**Comment by xeosnar** [comment]
add os.environ["PYTORCH_MPS_HIGH_WATERMARK_RATIO"] = "0.0" below os.environ["GRADIO_SERVER_PORT"] = "7865" in lunch.py file

**Comment by briandamkroger21** [comment]
Thanks, but I can't find the string 
"os.environ["GRADIO_SERVER_PORT'] = "7865"
in any of the "launch.py" files on my MAC

**Comment by mashb1t** [comment]
@briandamkroger21 it is in https://github.com/lllyasviel/Fooocus/blob/eb0b4d51ef3f46f57d7f20e870aa89a4b5de48ef/launch.py#L13.
I assume you found it by now, closing this issue.

**Comment by ratheraarif** [comment]
try this `export PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0`
