### ISSUE TITLE
Consistent images generation

### ISSUE THREAD

**Issue by IamTirion** [lllyasviel/Fooocus#1272]
I'm not sure if this is the right place to ask as this may be outside the scope of what a UI can do. If so, please point me to the right place to post this request.

I have tried to use Fooocus to generate images that I can tell a story with, but I haven't had much luck. I wondered if this is beyond the current capabilities of Stable Diffusion, or if I just don't know how to use it. Anyway, I came across this paper:
https://storygpt-v.s3.amazonaws.com/index.html

It seems to be pretty close to what I need. Is this something that can be implemented in ControlNet, or does it require fundamental changes in Stable Diffusion?

**Comment by mashb1t** [comment]
Stable Diffusion can only handle the image generation part but doesn't have context of what was input before. It could be done by using an LLM to keep the context and write a prompt for Stable Diffusion.
There already is a SD integration via API for https://github.com/oobabooga/text-generation-webui which might peak your interest and which already can write pretty good prompts for SD, but in Fooocus there is (currently) no support for LLMs.
Hope this helps!

**Comment by mashb1t** [comment]
either that or a LLM loaded in additon to a Stable Diffusion model, which would probably need another 7GB of VRAM (4 bit quantization of a 7b model)
