### ISSUE TITLE
Connection errored out (Model Pauses Automatically)

### ISSUE THREAD

**Issue by QUASARsX** [lllyasviel/Fooocus#1274]
![Screenshot (31)](https://github.com/lllyasviel/Fooocus/assets/78943868/7302f212-6152-4b2b-a2a8-9d032de303cf)

D:\Focuz\Fooocus_win64_2-1-791>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 4096 MB, total RAM 8076 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
Set vram state to: LOW_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce 940MX : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.

D:\Focuz\Fooocus_win64_2-1-791>pause
Press any key to continue . . .

**Comment by hewhoisgone** [comment]
same issue as well

**Comment by utkarshdeepak** [comment]
same issue

**Comment by annuraggg** [comment]
same issue

**Comment by VictorJacques** [comment]
same thing, any fixes?

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
