### ISSUE TITLE
ERROR RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from

### ISSUE THREAD

**Issue by SHOSHINXX** [lllyasviel/Fooocus#1276]
Hey peeps, yesterday and the days before i was able to make Images with the Collab. Today i get always errors "RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from". The last days i even dont had a NVIDIA driver installed or something else. I even used it on the Macbook and it worked perfectly. Does someone know if there was an Update or why its not working anymore?

Thanks everyone <3

**Comment by manunelly** [comment]
So when i open the collab with my Mac and share the link to my Desktop Computer its working. I dont get why :<

**Comment by deksone** [comment]
i also have this issue on windows have you figured out a work around?

**Comment by manunelly** [comment]
Not really yet. Probably they Updated something? I mean yesterday it worked great but today it doenst

**Comment by deksone** [comment]
just tried this link still has an error for nvidia drivers

**Comment by WebDevRavi** [comment]
is there any solution for this like how to make it work without drivers

**Comment by SHOSHINXX** [comment]
Damn i am sorry deksone for that. 
You can try to download also Pinokio and download Fooocus there, maybe this will work for you both?

**Comment by mashb1t** [comment]
Colab is working fine, please make sure to use an instanve eith a GPU (e.g. T4).
Can you please double-check and also confirm that it's working?

**Comment by mashb1t** [comment]
closing as stale, feel free to reopen when providing new information
