### ISSUE TITLE
I open any of the 3 bat files nothing happens

### ISSUE THREAD

**Issue by viplaya78921** [lllyasviel/Fooocus#1291]
I open the bat file, any of the 3, it says click to continue, I click, window closes and nothing happens. 

What should I do,
thanks

**Comment by SecHex** [comment]
Which OS?

**Comment by muneebxhasan** [comment]
same issue Windows 11 23H2

<img width="946" alt="Screenshot 2023-12-10 144808" src="https://github.com/lllyasviel/Fooocus/assets/83118183/70f8d411-845c-412e-9c8e-f0590adee3e2">
<img width="450" alt="Screenshot 2023-12-10 144947" src="https://github.com/lllyasviel/Fooocus/assets/83118183/bf8cbd72-5735-49a2-a7a2-fea089e802de">

**Comment by VictorJacques** [comment]
same here

**Comment by mashb1t** [comment]
Please provide the full terminal output as we're not able to help you without knowing more information. Thanks.

**Comment by mashb1t** [comment]
Closing as stale, feel free to reopen when providing new information. Thanks!
