### ISSUE TITLE
Issue on first run

### ISSUE THREAD

**Issue by Sierbahnn** [lllyasviel/Fooocus#130]
I have downloaded the files, and the models, putting them in the checkpoints-folder as instructed. 
Then I ran the run.bat and got an error. 

![Screenshot 2023-08-15 213904](https://github.com/lllyasviel/Fooocus/assets/68108749/20767076-6af4-4447-a038-53cea3be6c02)

It is stating that a folder does not exist or is not empty, and no, it does exist and it is not empty, because it wasn't empty when I unpacked the archive, and the download seems to be the one I just completed. Why is it doing this again?

Am I doing something wrong or is there some issue here?

**Comment by vo1d-null** [comment]
If its the first time you ran run.bat even though you have downloaded the files,the script will check for the files and the files themself.I think it is performing a scan,because when i downloaded and put the files it was the same for me.It said downloading ,but in reality it did not download the files again,it just perfomed a simple scan.

**Comment by Sierbahnn** [comment]
So the line "is now owned by current user" is of no concern?
And the "git clone failed" is just a placeholder, and I should just wait for the download?

**Comment by Sierbahnn** [comment]
It has now been running for over 6 hours, the Task Manager telling me that it is using just under 10% of my CPU, but the prompt remains the same. It does not appear to have done anything at all.
What is going on here?

I am on Windows 10, by the way.

**Comment by Sierbahnn** [comment]
It has been running for 16 hours and still no progress.
I am going to close it down, remove the files and start over, and see if it works better, but at this point I am assuming something is very broken.

**Comment by lllyasviel** [comment]
See also https://github.com/lllyasviel/Fooocus/issues/148

**Comment by Sierbahnn** [comment]
I removed the files, re-downloaded it and I get the exact same issue.

**Comment by lllyasviel** [comment]
Why the work path is system32? It should be in Fooocus folder

**Comment by Sierbahnn** [comment]
I have no idea. All I did was press the run.bat. Was I supposed to put fooocus in the system32? That seems weird and was not in any of the instructions.

**Comment by mashb1t** [comment]
I assume this is not relevant anymore, but the ssolution for @Sierbahnn would be not tu run the run.bat as admin / in a terminal with elevated permissions. original issue has been resolved, closing now.
