### ISSUE TITLE
Post-use network issues

### ISSUE THREAD

**Issue by Captain-Redeem** [lllyasviel/Fooocus#1301]
After using the tool, my network speed on device reduced to a nimble 1MB/s. Please perform a security check of this tool to evaluate the security of this tool.

**Comment by mashb1t** [comment]
@Captain-Redeem do you use a metered network connection? It might be possible that your carrier / ISP is now restricting your bandwidth due to Fooocus downloading necessary libraries and model(s) for the initial setup.

**Comment by Captain-Redeem** [comment]
> @Captain-Redeem do you use a metered network connection? It might be possible that your carrier / ISP is now restricting your bandwidth due to reaching your limit as Fooocus was downloading ~10GB of necessary libraries and model(s) for the initial setup.

Not really, it is unlimited usage at a limited speed and far more than what I am getting

**Comment by mashb1t** [comment]
Fooocus should have nothing to do with the situation you're experiencing.
Please do a speed test at https://speedtest.net to check your bandwidth again. Have you changed anything else concerning your network setup since the installation?

**Comment by mashb1t** [comment]
Issue is stale, closing for now
