### ISSUE TITLE
Change Temporary Folder for generating the image

### ISSUE THREAD

**Issue by EnBi81** [lllyasviel/Fooocus#1307]
Hi,

I have installed the Fooocus, and tried to generate an image, and the program fills up around at least 16-20 GB of space with temporary files. This is a problem for me, since I don't have that much free space left on my C: drive. Although I have initialized the application on my A: drive, all the config properties point to the A: drive, the program still uses the C: drive while generating the image.

Is there a possibility to change the Temporary folder of the app somewhere in the config?

**Comment by mashb1t** [comment]
@EnBi81 Can you please elaborate what you mean by "temporary files"?
Please double check if you have adjusted the paths in your config.txt file correctly (not the config_modification_tutorial.txt file).
Thanks!

**Comment by mashb1t** [comment]
@EnBi81 you can always change your temp file path by using `--temp-path TEMP_PATH`.

**Comment by pablootero-cl** [comment]
> Hi,
> 
> I have installed the Fooocus, and tried to generate an image, and the program fills up around at least 16-20 GB of space with temporary files. This is a problem for me, since I don't have that much free space left on my C: drive. Although I have initialized the application on my A: drive, all the config properties point to the A: drive, the program still uses the C: drive while generating the image.
> 
> Is there a possibility to change the Temporary folder of the app somewhere in the config?

**You looking for this file "config_modification_tutorial.txt" Line 26 

change: C for D or other disk
 "temp_path": "C:\\Users\\xxxx\\AppData\\Local\\Temp\\fooocus",**
