### ISSUE TITLE
Set Gradio analytics_enabled to false

### ISSUE THREAD

**Issue by rrdd** [lllyasviel/Fooocus#1312]
Would be great to set analytics_enabled to false instead true in current config. Necessary for EU Region.

Should be possible as mentiond here.
https://www.gradio.app/docs/interface

Was not able to find the Interface init in the code.

Thank You

**Comment by mashb1t** [comment]
as of https://github.com/gradio-app/gradio/pull/947/files there ar two options:

1. launch is in https://github.com/lllyasviel/Fooocus/blob/main/webui.py#L522, where analytics_enabled="False" can be added
2. env vars are in https://github.com/lllyasviel/Fooocus/blob/main/launch.py#L12, where GRADIO_ANALYTICS_ENABLED can be added as "False"

I'd propose to add the env var to not additionally clutter launch arguments. What do you think?
