### ISSUE TITLE
RuntimeError: The NVIDIA driver on your system is too old (found version 11040)

### ISSUE THREAD

**Issue by Abh3201** [lllyasviel/Fooocus#1313]
RuntimeError: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

Ubuntu 21.04
Nvidia GeForce RTX 3050 laptop GPU

-nvidia-smi

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.86       Driver Version: 470.86       CUDA Version: 11.4
|-------------------------------+----------------------+----------------------+

**Comment by fedyfausto** [comment]
i have same issue, any solution?
