### ISSUE TITLE
Change hair color

### ISSUE THREAD

**Issue by RandyBoBandy024** [lllyasviel/Fooocus#1317]
I was able to change hair color on my model but i can't do it anymore, no matter what i'm trying. Any help?

**Comment by mashb1t** [comment]
You can always give the hair color in your prompt a higher weight or use inpainting to fix parts of an image.
Example: "green hair" => "(green hair:1.2)"
Also see https://stable-diffusion-art.com/prompt-guide/ to get started.

Please keep in mind that this is a place to ask questions specific to the project and code, not a channel for general prompt support. Please ask such kind of quesions with the addition of some context on https://civitai.com/ or Reddit.
