### ISSUE TITLE
Images still adding things I specifically add to negative prompt. Any tips?

### ISSUE THREAD

**Issue by ItsNoted** [lllyasviel/Fooocus#1319]
**Describe the problem**
I add several words that describe what not to add in the negative prompt and it always adds them regardless.

Example: teeth, tooth, open mouth. Always get portraits with buck teeth protruding out of the mouth haha.

**Comment by mashb1t** [comment]
same as here, but for negative prompt: https://github.com/lllyasviel/Fooocus/issues/1317#issuecomment-1849084481
