### ISSUE TITLE
Styles not loading on google colab 

### ISSUE THREAD

**Issue by haik74** [lllyasviel/Fooocus#1326]
**Describe the problem**
I try to add styles to my prompt, and not working , its only generat the defult one.  
I am using google colab free account. 
**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

**Comment by mashb1t** [comment]
Please make sure to select only the styles that you want to apply to an image. Fooocus will then apply these styles to every image when clicking generate, not generate one / multiple image per style.
