### ISSUE TITLE
Define the desired image size

### ISSUE THREAD

**Issue by monkrus** [lllyasviel/Fooocus#1328]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

How can I accurately define the desired image size in a prompt, such as full-body, medium shot, or close-up, when creating prompts for Fooocus?”

**Comment by rubenmejiac** [comment]
Some guidance and ideas on the subject here:
[https://weirdwonderfulai.art/resources/sdxl-guide-to-camera-framing-and-angle/](https://weirdwonderfulai.art/resources/sdxl-guide-to-camera-framing-and-angle/)

**Comment by monkrus** [comment]
Since the website above is not always loading properly : 
**Framing and angle:**
extreme close-up
close-up
medium close-up
medium shot
long shot
establishing shot
medium-full shot
full shot
upper body shot
full body shot

**Camera angles/position:**

front view bilaterally symmetrical
side view
back view
from above
from below
from behind
wide-angle view
fisheyes view
macro view
overhead shot
top-down
bird`s eyes view
high angle
slightly above
straight on
hero view
low view
selfie
