### ISSUE TITLE
Create an Aitana AI influencer (SETTINGS)

### ISSUE THREAD

**Issue by Featurz** [lllyasviel/Fooocus#1329]
Hey guys, how did they do for making the AI influencer Aitana ? Because the faceswap on her is good : https://www.instagram.com/fit_aitana/

And I can't reproduce a faceswap as good as her, when I doing it, the face is not the same.. :(

Bests,

**Comment by mashb1t** [comment]
Most likely with a refined LoRA created by using images resembling the target person the most.
You can also check out https://youtu.be/ky5ZB-mqZKM

**Comment by Featurz** [comment]
Yes thanks a lot haha, that's the video I was triing to make but I can't have the same face on my faceswap unfortunatly.

Also I will try your method with LoRA and I hope this will work with multiple target images.

Thanks a lot friend :)

**Comment by Featurz** [comment]
I found this : https://www.youtube.com/watch?v=DD7d62nYfUk&ab_channel=AntalphaAI

**Comment by mashb1t** [comment]
there are very detailed tutorials available in https://github.com/bmaltais/kohya_ss?tab=readme-ov-file#tutorials

**Comment by monkrus** [comment]
This issue is closed, but I still wonder: how did they achieve the correct writing for the brands she is wearing.

**Comment by mashb1t** [comment]
Most likely inpainting with very many iterations or plain old Photoshop.
There also is a LoRA for text which could have been used: https://civitai.com/models/176555

**Comment by monkrus** [comment]
With technology zooming ahead, let's dive into the crystal ball of AI influencer evolution. Picture this:

-Crispier visuals, jaw-dropping videos, and audio.
-Chatbots crafting social media posts and engaging in chats.
-A tangled web of AI influencers teaming up and sparking off each other's brilliance.
-Personal influencers stepping up as your motivational sidekick, making sure you stay on top of your game.
