### ISSUE TITLE
Force download of LuggernautXL while it's already downloaded

### ISSUE THREAD

**Issue by Pk13Dev** [lllyasviel/Fooocus#1338]
Everytime after running the run.bat file juggernautXL is downloaded which is blocking me from using fooocus in general. I downloaded the latest version of juggernautXL myself, put it into the checkpoints folder and run.bat forces another juggernautXL download. Fix?

If it's necessary, i have an AMD gpu and this is the code in run.bat

```
 .\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
.\python_embeded\python.exe -m pip install torch-directml
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml
pause
```

**Comment by Pk13Dev** [comment]
> Not sure what's wrong but you can get rid of that by opening **Fooocus\presets\default.json** in a text editor. edit
> 
> `"checkpoint_downloads": { "juggernautXL_version6Rundiffusion.safetensors": "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_version6Rundiffusion.safetensors" }`
> 
> to
> 
> `"checkpoint_downloads": {}`

After changing the code JuggernautXL is still being force downloaded

**Comment by lllyasviel** [comment]
you can rename v7 to

juggernautXL_version6Rundiffusion

to avoid the download of v6

the v7 is still under user study. we update models or versions only if a model really outperform existing models in a large enough user study.
