### ISSUE TITLE
Feature request: Prompt que

### ISSUE THREAD

**Issue by GerardPSU** [lllyasviel/Fooocus#134]
Is it possible to add a feature where you can que prompts, it takes a while for images to generate so if I want to test various styles I can que them to be generate next.

**Comment by a77lic7ion** [comment]
Yes please or even a prompt box of 5 prompts to run one after the other please

**Comment by mashb1t** [comment]
See https://github.com/lllyasviel/Fooocus/issues/1664, closing as duplicate. Community members have already provided some code snippets, feel free to check them out!
