### ISSUE TITLE
Limit VRAM usage at cost of performance?

### ISSUE THREAD

**Issue by Phunite** [lllyasviel/Fooocus#1343]
Is it possible to set VRAM to low? I rather it takes longer to generate the pictures rather than crash. 
I have a 1080 Ti 11GB VRAM and it keeps crashing for me. 

![image](https://github.com/lllyasviel/Fooocus/assets/42948246/190a1768-940f-4c65-8596-a970eec09c1b)

**Comment by KeenanFernandes2000** [comment]
Yeah, I would like to know as well, I wouldn't mind waiting longer for the image if it means I can use the rest of my pc

**Comment by mashb1t** [comment]
You can set the arg `--always-low-vram`  to enforce low vram mode.
See https://github.com/lllyasviel/Fooocus/blob/main/ldm_patched/modules/args_parser.py#L99
