### ISSUE TITLE
[Q] What are the best LLMs for expanding and rewriting prompts?

### ISSUE THREAD

**Issue by NightMachinery** [lllyasviel/Fooocus#1345]
What are the best LLMs for expanding and rewriting prompts?

I know some general leaderboards:
- https://huggingface.co/spaces/lmsys/chatbot-arena-leaderboard
- https://evalplus.github.io/leaderboard.html

but I haven’t seen any benchmarks on the LLM’s capabilities for text2image prompt rewriting. I don’t even know of any specific finetunes for this.

**Comment by mashb1t** [comment]
Currently Fooocus uses a variant of GPT2, as it's easy to use, local, fast and low in resource consumption.
See https://github.com/lllyasviel/Fooocus/blob/eb0b4d51ef3f46f57d7f20e870aa89a4b5de48ef/launch.py#L84-L86
URL to model: https://huggingface.co/lllyasviel/misc/blob/main/fooocus_expansion.bin
Feel free to run the benchmarks yourself if you want to. Please keep in mind that the use case of this model is highly specific.
