### ISSUE TITLE
SSL Certificate verification fail

### ISSUE THREAD

**Issue by martinosmartinos** [lllyasviel/Fooocus#1347]
After downloading and installing what's needed on Mac I get an error while executing **python entry_with_update.py** or **entry_with_update.py --enable-smart-memory**:

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>

Please advise.

**Comment by mashb1t** [comment]
related to https://github.com/lllyasviel/Fooocus/issues/1311
