### ISSUE TITLE
Change number of steps and CFG?

### ISSUE THREAD

**Issue by Echolink50** [lllyasviel/Fooocus#1352]
Seems like a silly question but I just can't find where to set the amount of steps and CFG. I see speed, quality, extreme speed, which seem to change the steps but I would like to put in a specific amount. Is it in a config file or is it in the UI? Thanks everyone

**Comment by lllyasviel** [comment]
cfg is `guidance scale` in advanced

you can change step in `advanced` -> `dev tools` but these are dangerous settings that may make results worse.

in most cases, if you are able to get good results by changing steps, then you can try restart fooocus and do not change anything - you will find results are even better in default setting without any change to those things.

**Comment by Echolink50** [comment]
I am experimenting with some turbo models and LCM Loras. They don't like high steps in some cases. Is the step number in advanced named something else? I must have overlooked it somehow. Thanks

**Comment by lllyasviel** [comment]
yes you can change step in `advanced` -> `dev tools` -> `Forced Overwrite of Sampling Step`

**Comment by Echolink50** [comment]
Ahhhh. Will check it out. Thanks making for Fooocus also. I have A1111,
Comfyui, and just recently tried Fooocus. It's fast and handy for
inpainting and outpainting. Not a big deal but can Fooocus do batch img2img
by the way?

**Comment by mashb1t** [comment]
@Echolink50 Currently Fooocus can't handle batch img2img in UI, but you can use the API to do so if you're familiar with the Gradio API (Websocket).
For a REST implementation this repository might be helpful: https://github.com/konieshadow/Fooocus-API

**Comment by DefamationStation** [comment]
> yes you can change step in `advanced` -> `dev tools` -> `Forced Overwrite of Sampling Step`



> cfg is `guidance scale` in advanced
> 
> you can change step in `advanced` -> `dev tools` but these are dangerous settings that may make results worse.
> 
> in most cases, if you are able to get good results by changing steps, then you can try restart fooocus and do not change anything - you will find results are even better in default setting without any change to those things.

Hello, can you please consider making these parameters much more easier to access? Switching between SDXL and Lightning models right now is very cumbersome because Lightning needs 4-6 steps to produce a good image, it gets ruined at 60.

**Comment by mashb1t** [comment]
@DefamationStation please consider creating an own preset for lightning. You can continue the discussion in https://github.com/lllyasviel/Fooocus/discussions/2318 and find settings there.
Also check out https://github.com/mashb1t/Fooocus/blob/main/presets/lightning.json

**Comment by 45353535** [comment]
Please help me with instructions on how to run Defooocus via Zluda on the Rx6900xt &

**Comment by mashb1t** [comment]
@45353535 please ask this in the DeFooocus repository, not here.

**Comment by 45353535** [comment]
al bul repozıtorıı qaıda Men munda birinshi siltemeni tastaımyn

**Comment by mashb1t** [comment]
@45353535 https://letmegooglethat.com/?q=DeFooocus
