### ISSUE TITLE
Please change Vary (Subtle)/Vary (Strong) denoising strength to a slider or number field

### ISSUE THREAD

**Issue by CrackerHax** [lllyasviel/Fooocus#1358]
**Is your feature request related to a problem? Please describe.**
Two settings is not enough, end up having to send an image through Vary (Subtle) many times to get what I need.

**Describe the idea you'd like**
A number or slider for Vary (denoising strength)

**Comment by lllyasviel** [comment]
duplicated with https://github.com/lllyasviel/Fooocus/discussions/1011 :

if you know what you are doing, go to `advanced` -> `dev tool` -> `force overwrite of denoising strength of vary`

(but many people do not know what they are doing, and their knowledges learned from SD1.5 just does not work in SDXL)
(SDXL latent is 1.384x smaller range and 2x larger, which means SDXL's denoise strength 0.25 will behave similar to strength 0.05 in SD1.5, SDXL's denoise strength 0.5 will behave similar to strength 0.2 in SD1.5)
(so, consider twice if you really know what you are doing)
