### ISSUE TITLE
n 

### ISSUE THREAD

**Issue by msteele3** [lllyasviel/Fooocus#1366]

**Comment by qicuili** [comment]
你这个要将图片base64编码
image_path='/Users/Fooocus/outputs/2023-12-10/2023-12-10_17-30-04_1575.png'
 with open(image_path, 'rb') as image_file:
    image_data = image_file.read()
    base64_image = 'data:image/png;base64,'+base64.b64encode(image_data).decode('utf-8')

**Comment by msteele3** [comment]
> 你这个要将图片base64编码 image_path='/Users/Fooocus/outputs/2023-12-10/2023-12-10_17-30-04_1575.png' with open(image_path, 'rb') as image_file: image_data = image_file.read() base64_image = 'data:image/png;base64,'+base64.b64encode(image_data).decode('utf-8')

Thanks, this worked!
