### ISSUE TITLE
will this ever support img2img or ControlNet?

### ISSUE THREAD

**Issue by Compviztr** [lllyasviel/Fooocus#137]
Or should users seek other tool for those capabilities?

**Comment by darrylsepeda** [comment]
can't wait for img2img in Fooocus

**Comment by MoonRide303** [comment]
@Compviztr @darrylsepeda I've just implemented initial version of simple img2img on [my fork](https://github.com/MoonRide303/Fooocus-MRE) (commit [62d801b](https://github.com/MoonRide303/Fooocus-MRE/commit/62d801b5f29316f78f65ce90d7f3dffe897dac89)) - feel free to check it out, and let me know if works for you.

I have no plans for ControlNets, but as we already have support for Control-LoRAs in ComfyUI (used as backend for ComfyUI) it might be doable :).

**Comment by MoonRide303** [comment]
@darrylsepeda Theoretically it would be possible (Comfy engine used by Fooocus supports inpainting), BUT problem here is that SDXL itself doesn't really support inpainting, yet - we'd need dedicated SDXL inpainting model for that (similarily as it was done in case of SD 1.x / 2.x). See diffusers [issue #4392](https://github.com/huggingface/diffusers/issues/4392) and [this comment](https://github.com/huggingface/diffusers/issues/4392#issuecomment-1664248008) of mine illustrating the difference.

**Comment by darrylsepeda** [comment]
thanks @MoonRide303 for the explanation.

but I wonder how can I use the inpainting mode with other SDXL model? you mentioned that we need a dedicated SDXL inpainting model, so the inpainting model will automatically generated through the prompt?

**Comment by MoonRide303** [comment]
@darrylsepeda I didn't look into embeddings, yet - they might be not loaded.

**Comment by MoonRide303** [comment]
@darrylsepeda Embeddings are now working on my fork ([Fooocus-MRE](https://github.com/MoonRide303/Fooocus-MRE)).

@lllyasviel If you want this in vanilla, you can take a look at commit [cf3ac75](https://github.com/MoonRide303/Fooocus-MRE/commit/cf3ac75b03e6ed27bf9a157000d6af0833879be1) - it's kinda trivial change, embedding_directory parameter was missing in load_checkpoint_guess_config() call.

**Comment by darrylsepeda** [comment]
WOW, thats really great @MoonRide303 !! I'll try tonight! awesome work!

**Comment by darrylsepeda** [comment]
> @Compviztr @darrylsepeda Control-LoRA: Canny Edge available in [Fooocus-MRE](https://github.com/MoonRide303/Fooocus-MRE) (commit [36f3614](https://github.com/MoonRide303/Fooocus-MRE/commit/36f3614e19075f71e70f7791c345a29d6f7ff4ad)). Can be used in both txt2img and img2img modes.
> 
> Sample input and output: ![image](https://user-images.githubusercontent.com/130458190/264376467-4ab05a4a-600f-4277-a487-293db7220ccd.png) -> ![image](https://user-images.githubusercontent.com/130458190/264376523-54f4c32f-5fc4-413b-af36-4ccd94045896.png)

Cool!

**Comment by darrylsepeda** [comment]
@MoonRide303 out of curiosity, I encounter this using Fooocus and ComfyUI, do you know what's wrong?
I can only use a few checkpoints from whatever checkpoints I have.
![image](https://github.com/lllyasviel/Fooocus/assets/5493333/6f2f3ff6-a27e-4efc-9550-37c18911768f)

**Comment by MoonRide303** [comment]
@darrylsepeda Fooocus (and Fooocus-MRE) are UIs dedicated to SDXL, and variants of it.

ComfyUI (used as backend in Fooocus) can use also SD 1.5 / 2.1, but lllyasviel didn't want to support multiple model families - it would complicate code base and the UI, so I understand this decision (different generations of SD have different optimal resolutions, might not be compatible with the same supplementary models (like ControlNets / Control-LoRAs), etc.).

**Comment by darrylsepeda** [comment]
do you have references where can I learn about SD families?
sometimes I also wonder if using more than 5 loras will make the result more great (I modified mine).
also, things that confuse me like some loras and other things could be defined via text, while some of it should be defined from specific field. one of them should be enough?

**Comment by MoonRide303** [comment]
@darrylsepeda SDXL is latest generation, so in as long as you have reasonable computer (8+ GB VRAM, 32 GB RAM), then I'd recommend sticking to SDXL (and it's finetuned variants).

As for using multiple LoRAs I'd be careful - not all of them will be compatible, so using more of them not necesarilly will result in better output image. It's a bit like with the prompts - shorter and simpler prompts might yield better results than long and over-complicated ones.

LoRA vs text - LoRAs will react to trigger words on which they were trained - those triggers are usually provided by given LoRA author.
