### ISSUE TITLE
Need a dark mode

### ISSUE THREAD

**Issue by Leroy-X** [lllyasviel/Fooocus#1370]
**Is your feature request related to a problem? Please describe.**

**Describe the idea you'd like**
I see that many examples of screenshots are in dark mode. I don’t know how to implement it. Maybe setting the system to dark mode can be used, but the global one is not friendly. I tried the browser extension Dark reader, and the results were terrible.

I hope there is a dark mode button, thank you very much.

**Comment by Leroy-X** [comment]
Luckily I found this #327

**Comment by Xiaolifeijian** [comment]
Add -- theme=dark to the startup file.
example: .\python_embeded\python.exe -s Fooocus\entry_with_update.py --language zh_CN --theme=dark%*
pause

**Comment by Leroy-X** [comment]
Thanks :P
