### ISSUE TITLE
The requirements and version with torchvision and torchaudio are not proper and causing problem.

### ISSUE THREAD

**Issue by ShubhamX-AI** [lllyasviel/Fooocus#1371]
torchsde==0.2.5
einops==0.4.1
transformers==4.30.2
safetensors==0.3.1
accelerate==0.21.0
pyyaml==6.0
Pillow==9.2.0
scipy==1.9.3
tqdm==4.64.1
psutil==5.9.5
numpy
pytorch_lightning==1.9.4
omegaconf==2.2.3
gradio==3.41.2
pygit2==1.12.2
opencv-contrib-python==4.8.0.74
httpx==0.24.1
timm==0.9.2
boltons>=20.2.1
...........................................................................................................................................................................................................................................................

And the ( torchvision torchaudio ) should be compatible with CUDA and should be downloaded from the PyTorch website Like - ( pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 )

..............................................................................................................................................................................................................................................................

These changes must be done or It is giving an error.

**Comment by lllyasviel** [comment]
do you follow official installation guide or install in your own unofficial way? do you have log of error?

**Comment by ShubhamX-AI** [comment]
Yes, I have followed. Still, It was giving the error while installing the
specific requirements that were given, and while running the
"entry_with_update.py" it was also giving the error for torchvision and
torchaudio .

**Comment by lllyasviel** [comment]
what Operating System are you using?

**Comment by ShubhamX-AI** [comment]
Windows 11

**Comment by lllyasviel** [comment]
Hi,

if you are using Windows 11 and facing problems about installing torchvision and torchaudio, then you are not following official installation guide.

We have never released any Windows installation guide that requires user to install any python packages.

See also https://github.com/lllyasviel/Fooocus#windows

**Comment by ShubhamX-AI** [comment]
Yeah, But we can use it in Windows by slightly changing the requirements
with torchvision and torchaudio like the way it is given. You should add a
Windows version because of the larger audience.

**Comment by lllyasviel** [comment]
Closed as User Mistake.

Feel free to reopen if having more enquiries.

**Comment by snigdhasjg** [comment]
I used this settings while creating conda virtual env

```yaml
name: fooocus
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip=23.0
  - packaging
  - pytorch==1.13.1
  - torchvision==0.14.1
  - torchaudio==0.13.1
  - pytorch-cuda=11.7
```
