### ISSUE TITLE
Runs on CPU and not GPU

### ISSUE THREAD

**Issue by Vigneshkumar212** [lllyasviel/Fooocus#1372]
hey, im new to this and dont really know much, i downloaded as shown on the readme page and ran the run.bat file... it started working but its slow i think its running on the cpu and gpu, before this i followed a video and got an error telling torch not compiled with cuda and also installed cuda from nvidia... is there a way to resolve this issue?
![image](https://github.com/lllyasviel/Fooocus/assets/60309361/c15f0296-3839-4a9f-b129-5f98ccec33e3)
this is my cpu and gpu usage when rending the image.

**Comment by travismailsa** [comment]
I also just installed and tried testing and seems to be using CPU

**Comment by Zetagron** [comment]
same problem. it's using cpu and not gpu.

**Comment by Vigneshkumar212** [comment]
Hey, thanks for the help.
I ran the command as you had instructed but I think there are a few dependency issues,

`DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063`

I'll maybe wait a little longer for a newer version of [Fooocus](https://github.com/lllyasviel/Fooocus) before running this command again. 
Thanks again!

**Comment by Vigneshkumar212** [comment]
Ohk, thanks for the help!

**Comment by ankit097967** [comment]
The same problem do not know what to do, CPU Usage is 100% but GPU is not being used.

**Comment by robcabob1** [comment]
mine randomly chooses GPU or CPU each startup. it's literally different every time. I think that is ridiculous
!
