### ISSUE TITLE
Input image not working

### ISSUE THREAD

**Issue by 616MadMax** [lllyasviel/Fooocus#1379]
Can anyone help me to fix this? In google collabs is working, but i dont want to use this way cuz i cant use my checkpoints and loras... 
My pc
![image](https://github.com/lllyasviel/Fooocus/assets/119917039/974ead62-61b1-4cde-861e-b05b1e99b96b)
My pc
![image](https://github.com/lllyasviel/Fooocus/assets/119917039/7ea798b9-8541-434f-a116-e2cc74c72cfc)
Collabs
![image](https://github.com/lllyasviel/Fooocus/assets/119917039/98eb26b0-7a6b-4b20-88c4-8aee36fefe47)
Collabs
![image](https://github.com/lllyasviel/Fooocus/assets/119917039/3e08371b-6660-4cf6-b0f9-ec1436858a5c)

**Comment by lllyasviel** [comment]
do you see errors like connection errored out?
see also common problems here https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

**Comment by 616MadMax** [comment]
> do you see errors like connection errored out?
> 
> see also common problems here https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

Nope... is nothing happening i just click on input image and nothing happens, if i press on advanced is working, i tried to reinstall and still nothing...

**Comment by lllyasviel** [comment]
do you closed the console?

**Comment by 616MadMax** [comment]
No :)))

**Comment by 616MadMax** [comment]
Like i cba with this problem, im thinking to reinstall the windows but im afraid to get same problem :/

**Comment by 616MadMax** [comment]
I forgot to mention, yesterday was working fine!!!

**Comment by lllyasviel** [comment]
what browser you are using? have you tried chrome?

**Comment by 616MadMax** [comment]
Ahm im using opera gx, if i press f12 where? In browser tab?

**Comment by 616MadMax** [comment]
Im downloading chrome now, but idk if is a problem with browser cuz yesterday was working fine

**Comment by lllyasviel** [comment]
paste full log of your fooocus console and a screenshot of browser dev tool. in chrome it is f12

**Comment by 616MadMax** [comment]
Oh, wait is working now with chrome...

**Comment by 616MadMax** [comment]
Well thank you, idk what problem have opera gx 😅

**Comment by lllyasviel** [comment]
thanks and if possible please also let me know what is wrong with opera.

I read opera gx and it says it is a browser with some constraints and funcs removed to make other games faster. so perhaps something is removed.

**Comment by 616MadMax** [comment]
Yea maybe, this is the reason why im using opera gx, low resources :)

**Comment by karatepicke** [comment]
Hi @lllyasviel,

I'm having the same issue and can confirm the input image checkbox does not reveal the bottom panel. Tried in Firefox v120.0.1 and Chrome v120.0.6099.109.

There is a reference error: 

Uncaught (in promise) ReferenceError: viewer_to_bottom is not defined (when checking "Input Image") and
Uncaught (in promise) ReferenceError: viewer_to_top is not defined (when unchecking "Input Image")

See the attached image:

![fooocus_ref_error_input_image](https://github.com/lllyasviel/Fooocus/assets/35921524/0aa6efa5-dc5d-4f48-8b3b-10f429c7fe34)

**Comment by suhassalian27** [comment]
Hi @karatepicke , this workaround does show the options, but there is no functionality, nothing works. I tried doing face swaps, but all it did was run the prompt without using the image.

**Comment by karatepicke** [comment]
Hi @suhassalian27 you're right. I just double checked in it does indeed not accept/process the images. Guess we'll have to wait for an official fix :/

**Comment by suhassalian27** [comment]
@karatepicke It's working for me now, I just moved it from drive A to C.

**Comment by 1varunvc** [comment]
Hello @lllyasviel 

The bug is reproducible for me as well. It wasn't, until two days back, and I didn't pull the latest code.

The following screenshots are from Google Colab, running the latest code for Fooocus with no change in the `config.txt` file. It throws `Uncaught (in promise) ReferenceError: viewer_to_bottom is not defined` upon toggling the checkbox for 'Input Image.'

I'm on Brave browser. (And I was on the same browser two days back.)

1. ✅ Input Image ✅ Advanced
![Screenshot 2024-02-04 at 4 23 53 AM](https://github.com/lllyasviel/Fooocus/assets/71169556/fdc4f6d8-340b-4513-8050-1555898e1f8a)

2. ✅ Input Image
![Screenshot 2024-02-04 at 4 24 01 AM](https://github.com/lllyasviel/Fooocus/assets/71169556/7036eb4e-5422-4783-9912-763d21a47742)

3. ✅ Input Image (Console)
![Screenshot 2024-02-04 at 4 33 37 AM](https://github.com/lllyasviel/Fooocus/assets/71169556/238bbcb4-a077-497e-817e-de7e80ab82d6)

Console Log:
```
19d928b237ceff6130.gradio.live/:56 
        
        
       GET https://19d928b237ceff6130.gradio.live/file=/content/drive/.shortcut-targets-by-id/1omkN6AI3D-vzLBtXcQoPrFp8FwwAy-0T/Drive%20for%20Colab/Fooocus/javascript/script.js?1707000100.0 net::ERR_ABORTED 403 (Forbidden)
19d928b237ceff6130.gradio.live/:57 
        
        
       GET https://19d928b237ceff6130.gradio.live/file=/content/drive/.shortcut-targets-by-id/1omkN6AI3D-vzLBtXcQoPrFp8FwwAy-0T/Drive%20for%20Colab/Fooocus/javascript/contextMenus.js?1707000100.0 net::ERR_ABORTED 403 (Forbidden)
19d928b237ceff6130.gradio.live/:61 
        
        
       GET https://19d928b237ceff6130.gradio.live/file=/content/drive/.shortcut-targets-by-id/1omkN6AI3D-vzLBtXcQoPrFp8FwwAy-0T/Drive%20for%20Colab/Fooocus/javascript/viewer.js?1707000100.0 net::ERR_ABORTED 403 (Forbidden)
19d928b237ceff6130.gradio.live/:62 
        
        
       GET https://19d928b237ceff6130.gradio.live/file=/content/drive/.shortcut-targets-by-id/1omkN6AI3D-vzLBtXcQoPrFp8FwwAy-0T/Drive%20for%20Colab/Fooocus/javascript/imageviewer.js?1707000100.0 net::ERR_ABORTED 403 (Forbidden)
19d928b237ceff6130.gradio.live/:60 
        
        
       GET https://19d928b237ceff6130.gradio.live/file=/content/drive/.shortcut-targets-by-id/1omkN6AI3D-vzLBtXcQoPrFp8FwwAy-0T/Drive%20for%20Colab/Fooocus/javascript/edit-attention.js?1707000100.0 net::ERR_ABORTED 403 (Forbidden)
19d928b237ceff6130.gradio.live/:92 
        
        
       GET https://19d928b237ceff6130.gradio.live/file=/content/drive/.shortcut-targets-by-id/1omkN6AI3D-vzLBtXcQoPrFp8FwwAy-0T/Drive%20for%20Colab/Fooocus/css/style.css?1707000100.0 net::ERR_ABORTED 403 (Forbidden)
19d928b237ceff6130.gradio.live/:59 
        
        
       GET https://19d928b237ceff6130.gradio.live/file=/content/drive/.shortcut-targets-by-id/1omkN6AI3D-vzLBtXcQoPrFp8FwwAy-0T/Drive%20for%20Colab/Fooocus/javascript/zoom.js?1707000100.0 net::ERR_ABORTED 403 (Forbidden)
19d928b237ceff6130.gradio.live/:58 
        
        
       GET https://19d928b237ceff6130.gradio.live/file=/content/drive/.shortcut-targets-by-id/1omkN6AI3D-vzLBtXcQoPrFp8FwwAy-0T/Drive%20for%20Colab/Fooocus/javascript/localization.js?1707000100.0 net::ERR_ABORTED 403 (Forbidden)
19d928b237ceff6130.gradio.live/:1 Autofocus processing was blocked because a document already has a focused element.
VM215:3 Uncaught (in promise) ReferenceError: viewer_to_bottom is not defined
    at eval (eval at <anonymous> (Blocks.svelte:68:25), <anonymous>:3:35)
    at Object.eval [as frontend_fn] (eval at <anonymous> (Blocks.svelte:68:25), <anonymous>:3:114)
    at we (Blocks.svelte:366:6)
eval @ VM215:3
eval @ VM215:3
we @ Blocks.svelte:366
Promise.then (async)
we @ Blocks.svelte:371
await in we (async)
(anonymous) @ Blocks.svelte:551
(anonymous) @ Blocks.svelte:550
dispatch @ gradio_helper.ts:31
N @ InteractiveCheckbox.svelte:38
(anonymous) @ lifecycle.js:105
(anonymous) @ lifecycle.js:104
l @ Checkbox.svelte:17
E.a.$$.update @ Checkbox.svelte:25
Zi @ scheduler.js:115
Bo @ scheduler.js:79
Promise.then (async)
To @ scheduler.js:20
ea @ Component.js:79
(anonymous) @ Component.js:127
v @ Render.svelte:72
r @ Render.svelte:80
(anonymous) @ Component.js:126
S @ InteractiveCheckbox.svelte:25
k @ InteractiveCheckbox.svelte:31
(anonymous) @ Component.js:126
g @ Checkbox.svelte:32
Show less
```

You may be seeing `.shortcut-targets-by-id/1omkN6AI3D-vzLBtXcQoPrFp8FwwAy-0T` in the 403 error. Please note that I see this error even when I don't use a shortcut folder, but a regular one from the mounted Google Drive, as in the screenshot below. It's likely to be unrelated.

![Screenshot 2024-02-04 at 4 45 35 AM](https://github.com/lllyasviel/Fooocus/assets/71169556/27a1e0fd-3d12-4081-9d8c-0d33df306af9)

**Comment by 1varunvc** [comment]
> @karatepicke It's working for me now, I just moved it from drive A to C.

@suhassalian27, could you please elaborate what you mean to say here?

**Comment by mashb1t** [comment]
@616MadMax currently doing issue cleanup. Is this issue still present for you using the latest version of Fooocus and are you using valid paths without special characters / a dot or can this issue be closed?

**Comment by Exordio** [comment]
I'm running Linux and it doesn't work the same way. When requesting a page, it clearly cannot receive some files. Why this was done this way is unclear.

![image](https://github.com/lllyasviel/Fooocus/assets/45700369/9fa95298-f9ca-40c9-9b66-31b94155c971)

![image](https://github.com/lllyasviel/Fooocus/assets/45700369/324dc5df-47d3-4d7b-9e50-9aa1b4a6514e)

**Comment by Exordio** [comment]
This was resolved after I removed the points from the path. But the import system, of course, my respects (sarcasm)
