### ISSUE TITLE
[Feature Request] - Add optional path for refiners

### ISSUE THREAD

**Issue by d8ahazard** [lllyasviel/Fooocus#1383]
**Is your feature request related to a problem? Please describe.**
Presently, refiners are just stored along-side checkpoints. I keep mine sorted with sdxl and v1 in separate folders. So, to use a v1x model as a refiner, I'd have to change a bit of mapping.

**Describe the idea you'd like**
Add a new, optional path to config.txt for a directory to use for refiners. If none is specified, just look in the normal models path?

**Comment by CodeZ1LLa** [comment]
+

**Comment by mashb1t** [comment]
Sorry for the late reply. Model paths can be arrays since a few releases ago, so it's pretty easy to just use a separate folder for refiners only.

**Comment by d8ahazard** [comment]
> Sorry for the late reply. Model paths can be arrays since a few releases ago, so it's pretty easy to just use a separate folder for refiners only.

But does that still show all the models in both the checkpoint and refiner selections, or can you specify which go where?

The request (and corresponding PR) were meant to make it so that we can map V1.5 models *only* as refiners.

**Comment by mashb1t** [comment]
you can still select both and as there is no logic attached to differentiate between 1.5 and XL the two paths are the only differentiator. I get the reason but you can also use XL models as refiner and they would have to be duplicated. While i totally get the intention, sowing all models is currently just more convenient for the average user.

also see https://github.com/mashb1t/Fooocus/pull/2 for an attempt to filter by name, which then was discarded.
