### ISSUE TITLE
Chat GPT2 ?

### ISSUE THREAD

**Issue by 616MadMax** [lllyasviel/Fooocus#1384]
Why chat GPT2? maybe a upgrade when we can pay for chat GPT4 bcs i know this is more advanced :/
![Screenshot_310](https://github.com/lllyasviel/Fooocus/assets/119917039/d8980789-93af-48f3-854c-4433455d5d2b)

**Comment by lllyasviel** [comment]
Fooocus GPT2 is carefully designed to improve visual quality, while at the same time, do not add random unwanted objects or any style bias to the generating process. Even ChatGPT/GPT4 cannot compete with Fooocus GPT2 in this very specific problem with such special needs.
