### ISSUE TITLE
question:  How to save some loading time ?

### ISSUE THREAD

**Issue by xddun** [lllyasviel/Fooocus#1390]
Thank you for your project!

I found that Fooocus does not rely heavily on graphics memory, 
and every time it needs to load or unload the model file. 

I want the model to always be in graphics memory, which can save some loading time. 

How do I need to do this?

**Comment by lllyasviel** [comment]
hi you can use `--disable-offload-from-vram`
see also all flags
https://github.com/lllyasviel/Fooocus#all-cmd-flags

**Comment by xddun** [comment]
good idea! 

I using this project https://github.com/konieshadow/Fooocus-API, I will study how it is operated.

thank you!

**Comment by mashb1t** [comment]
No, offloading will happen if too little VRAM is available to keep everything loaded.
See https://github.com/lllyasviel/Fooocus/blob/main/ldm_patched/modules/model_management.py#L337-L339
