### ISSUE TITLE
GPU low usage

### ISSUE THREAD

**Issue by Kralg** [lllyasviel/Fooocus#1393]
Hello,
Thank you for nice repository and your work.
I am starting testing the program on the laptop, and I noticed that the resources are not fully used. Can you write do you know how to increase the usage? 

![foocus_performance](https://github.com/lllyasviel/Fooocus/assets/26962388/eccb7f20-5160-4907-bc5b-678d8a3cc68b)
![foocus_performance_2](https://github.com/lllyasviel/Fooocus/assets/26962388/7593af9a-9af2-4b02-b9ef-4aea54147528)

**Comment by vanguard-bit** [comment]
Maybe turn off all the "Battery Saving" features 
or always use it while charging (my laptop doesnt want to run the gpu fan properly on battery)

**Comment by Kralg** [comment]
Hi, thank you, yes the laptop is plugged and set to "Best performance", but as in the pictures the resources are not fully used.

**Comment by mashb1t** [comment]
You're running in low vram mode, which is the bottleneck for your GPU (vram is outsourced to RAM to make it possible to generate images in the first place on your machine). Write speed to and read speed from RAM are heavily limiting your GPU.
Sorry to say this, but this can only be solved by upgrading your hardware.
