### ISSUE TITLE
How to get image Url and where it Url generate 

### ISSUE THREAD

**Issue by TeachMeHacking** [lllyasviel/Fooocus#1395]
@lllyasviel 
How to I get Generated Image Url in code?

**Comment by mashb1t** [comment]
You'll have to built the URL yourself by using the filename of the generated file or NamedTemporaryFile before image logging (if enabled). See https://github.com/lllyasviel/Fooocus/blob/main/modules/private_logger.py#L14-L25
Example:
https://f489ca7f48cb5ae7a1.gradio.live/file=/content/Fooocus/outputs/2023-12-29/2023-12-29_01-11-52_2188.png
