### ISSUE TITLE
Is PyraCanny not compatible with the SD 1.5 model?

### ISSUE THREAD

**Issue by RexLeeGrey** [lllyasviel/Fooocus#1399]
Does PyraCanny in the image prompt only work for the SDXL model? I set the refiner to the SD 1.5 model, and the generated image showed significant changes, completely inconsistent with the sketch I provided.

**Comment by IPv6** [comment]
Seems so - SDXL controlnets influence SDXL part of the pipeline only.

Would be cool to have SD1.5 controlnet that applied at refiner stage with SD1.5 model

**Comment by VladimirYugay** [comment]
And how to enable pyracanny in the latest windows version?
