### ISSUE TITLE
Not enough on 4GB vRAM

### ISSUE THREAD

**Issue by p0mad** [lllyasviel/Fooocus#14]
Hi, unlike the instructions that says it works on 4GB VRAM, but i'm using GTX 850 which is 4GB vram and i got not enough memory!
![image](https://github.com/lllyasviel/Fooocus/assets/131435526/76b45d1b-7e93-4fd8-9ef0-3a8c8296fb0b)
![image](https://github.com/lllyasviel/Fooocus/assets/131435526/fb3cc260-bc75-4946-8267-6c8c356c054f)

**Comment by Tigwin** [comment]
I have a 3080FE and it has 10gb of ram. I think we need a medram setting cause it takes a looooong time to render some stuff. But if I keep it simple (low poly, "whale"), it renders about as fast as I'd expect.

**Comment by NoMansPC** [comment]
It eats up almost all of my RAM too, making my computer unusable. Sadly, for now, buying a new card is still the proper way to use SDXL.

**Comment by Tigwin** [comment]
I just found out a temp fix for the vram issue on my desktop. Disable the video card then enable it, freed up almost half my vram:

Get-PnpDevice -FriendlyName "NVIDIA GeForce RTX 3080" | Disable-PnpDevice
Sleep -Seconds 5
Get-PnpDevice -FriendlyName "NVIDIA GeForce RTX 3080" | Enable-PnpDevice

**Comment by iLKke** [comment]
Fails for me the same way as for the OP.
I have 16GB RAM and an GTX 1050 Ti with 4GB VRAM
I noticed that it will gobble all of free space on C: that (cca 7GB) before failing due to not enough memory.

**Comment by sangshuduo** [comment]
I have 32GB RAM and an 3050Ti with 4GB VRAM. Wish it can be supported.

**Comment by AiSaurabhPatil** [comment]
It's working in my case 
I have 16GB RAM and Nvidia GTX 1650 with 4GB VRAM 
example : 
![2023-08-14_12-49-52_6503](https://github.com/lllyasviel/Fooocus/assets/65061918/c22b6265-0246-4f10-ad03-151ef411c7fa)

**Comment by iLKke** [comment]
OK as suspected, I needed to free up a ton of disk space and now it works. 
The error message was misleading as it's not VRAM or RAM but disk space that was causing it to fail.

**Comment by lllyasviel** [comment]
Both GTX 1650 and 850 has 4GB vram, but it seems that 1650 works and is "smarter" to use vram in more efficiency way.
Probably 850 is really very difficult to support. We will probably add some descriptions in the Readme to make it clearer

**Comment by mimze** [comment]
16GB of RAM and 4GB of VRAM (GTX 950m). I get no errors but it just gets stuck when I hit Generate.

**Comment by game-alle** [comment]
I have an rtx 3050ti, and it's just stuck in this state and not progressing.
![565437575](https://github.com/lllyasviel/Fooocus/assets/109752637/bbfd175c-60bd-4fb6-a498-8eb7dceec960)
![54365465](https://github.com/lllyasviel/Fooocus/assets/109752637/ada30514-df42-451d-9423-e2a7c2eed915)

**Comment by xjdeng** [comment]
Also fails on mine: GTX 960M, 4GB VRAM, 16 GB RAM:

![image](https://github.com/lllyasviel/Fooocus/assets/17135596/a1a24783-bd48-4aaa-9513-3a91a28d537b)

```
D:\JJ\python\Fooocus_win64_2-1-791>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset realistic
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'realistic']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.802
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 4096 MB, total RAM 16250 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
Set vram state to: LOW_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce GTX 960M : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra keys {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: D:\JJ\python\Fooocus_win64_2-1-791\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors
Request to load LoRAs [('SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 0.25), ('None', 0.25), ('None', 0.25), ('None', 0.25), ('None', 0.25)] for model [D:\JJ\python\Fooocus_win64_2-1-791\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors].
Loaded LoRA [D:\JJ\python\Fooocus_win64_2-1-791\Fooocus\models\loras\SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for model [D:\JJ\python\Fooocus_win64_2-1-791\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors] with 1052 keys at weight 0.25.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cpu, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 10.48 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 3.0
[Parameters] Seed = 7801272631270716136
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] cat, cinematic, complex, highly detailed, extremely, sharp focus, beautiful, stunning composition, symmetry, great colors, aesthetic, very inspirational, colorful, deep color, inspiring, original, full bright, lovely, cute, artistic, intricate, elegant, perfect light, fine detail, clear, ambient background, professional, creative, positive, amazing, pure, wonderful, unique
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] cat, very coherent, cute, cinematic, detailed, intricate, stunning, highly refined, epic composition, magical atmosphere, full color, elegant, luxury, amazing detail, professional, winning, thoughtful, calm, beautiful, unique, best, awesome, perfect, ambient light, shining, illuminated, translucent, fine, artistic, pure, positive, attractive, creative, vibrant
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
Preparation time: 41.61 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.02916753850877285, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model

D:\JJ\python\Fooocus_win64_2-1-791>pause
Press any key to continue . . .
```

**Comment by lllyasviel** [comment]
Yes I should modify the Readme to say that the 4GB VRAM needs to have an GPU Arch to support float16.

But how can GTX 960M and SDXL be put in one same sentence

**Comment by xjdeng** [comment]
> Yes I should modify the Readme to say that the 4GB VRAM needs to have an GPU Arch to support float16.
> 
> But how can GTX 960M and SDXL be put in one same sentence

Because

1. SDXL and 4 GB VRAM were in the same sentence in the repo
2. The 960M worked fine with fp16 1.5  models

Now it's entirely possible it's another issue and I can accept that. But it seems this repo is implying it'll work with all 4 GB Nvidia GPUs when I've found a countetexample: my old laptop's.

**Comment by AFOLcast** [comment]
There's a note I found buried on the GitHub about new versions not working
with "old" computers. I downloaded the patch and installed.

Now my RTX 2060 works again.

**Comment by rohanmandrekar** [comment]
> Fails for me the same way as for the OP. I have 16GB RAM and an GTX 1050 Ti with 4GB VRAM I noticed that it will gobble all of free space on C: that (cca 7GB) before failing due to not enough memory.

same issue. any way I can prevent it from using space on C drive?

**Comment by mashb1t** [comment]
You can not as when VRAM is exhausted RAM is used and when RAM is (near) full the swap is used.
Preventing offliading from GPU is possible, but you'll not be able to run Fooocus then.
See https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

**Comment by cp818** [comment]
> > Fails for me the same way as for the OP. I have 16GB RAM and an GTX 1050 Ti with 4GB VRAM I noticed that it will gobble all of free space on C: that (cca 7GB) before failing due to not enough memory.
> 
> same issue. any way I can prevent it from using space on C drive?

> Same here too. no clear instructions?

**Comment by mashb1t** [comment]
@cp818 let's do not revive a 4 months old thread, please open a discussion or a new issue and provide all necessary information such as terminal output, hardware specs etc.
