### ISSUE TITLE
Fooocus Style Reference (184 styles updated)

### ISSUE THREAD

**Issue by Semonxue** [lllyasviel/Fooocus#140]
Thank you @lllyasviel , Fooocus is great and easy to use , styles are great.
I made a Fooocus style reference , so I can visually decide which style to use. 

👉🏻 https://docs.google.com/spreadsheets/d/1AF5bd-fALxlu0lguZQiQVn1yZwxUiBJGyh2eyJJWl74/edit#gid=0

Any suggestion please leave comment.

**Comment by djdance** [comment]
great! that's what I long waited for!

**Comment by jil49300** [comment]
Hello Semonxue,
Thank you so very much for your hard work and share.
This is very valuable !
Coul you please tell us which checkpoint you did use for you image examples ?
thank you

**Comment by Semonxue** [comment]
> Hello Semonxue, Thank you so very much for your hard work and share. This is very valuable ! Coul you please tell us which checkpoint you did use for you image examples ? thank you

I use default sdxl base/refiner/vae models.

**Comment by PangFayue-stack** [comment]
> Hello Semonxue, Thank you so very much for your hard work and share. This is very valuable ! Coul you please tell us which checkpoint you did use for you image examples ? thank you
Hello jiil49300,
Did you mean you have other checkpoint?If yes,can you share with us?
thank you

**Comment by cjj1977** [comment]
@Semonxue thanks for the reference. It's really useful. I did find it takes a while to load; I'm guessing that the example images are SDXL sized? Since they're much smaller within the document I wonder if they can be made smaller so the file loads faster?

**Comment by easyspace** [comment]
Amazing Work @Semonxue !

**Comment by simartem** [comment]
> Thank you @lllyasviel , Fooocus is great and easy to use , styles are great. I made a Fooocus style reference , so I can visually decide which style to use.
> 
> 👉🏻 https://docs.google.com/spreadsheets/d/1AF5bd-fALxlu0lguZQiQVn1yZwxUiBJGyh2eyJJWl74/edit#gid=0
> 
> Any suggestion please leave comment.

Thank you for the effort. How did you manage to get the prompts of the each style ?

**Comment by Semonxue** [comment]
> > Thank you @lllyasviel , Fooocus is great and easy to use , styles are great. I made a Fooocus style reference , so I can visually decide which style to use.
> > 👉🏻 https://docs.google.com/spreadsheets/d/1AF5bd-fALxlu0lguZQiQVn1yZwxUiBJGyh2eyJJWl74/edit#gid=0
> > Any suggestion please leave comment.
> 
> Thank you for the effort. How did you manage to get the prompts of the each style ?

Thank you. I got style from folder `/sdxl_styles/*.json`.

**Comment by mashb1t** [comment]
Thank you very much, will reference this and https://github.com/lllyasviel/Fooocus/discussions/143 in the future! Much appreciated!

**Comment by MaksG0** [comment]
Visual Aspect Ratios
[FOOOCUS Aspect Ratios.pdf](https://github.com/lllyasviel/Fooocus/files/13981466/FOOOCUS.Aspect.Ratios.pdf)

**Comment by Ritavdas** [comment]
Great job !, did you find a way to keep the body of the person consistent

**Comment by Pixie86** [comment]
hey. Unfortunately I cannot download the file. Is there any way?

**Comment by aficana** [comment]
thanks for the reference. It's really useful.
