### ISSUE TITLE
Option to log console output when running headless

### ISSUE THREAD

**Issue by SpcCw** [lllyasviel/Fooocus#1415]
I run Fooocus on another Windows machine with `--listen` option so I can use it remotely and I set it to automatically launch on startup in scheduler task. It works just great except I can't figure out how to capture console output to some log file so if it crashes or something weird happens it can be reviewed.

Usual redirect like `command > file.log` results in empty file.

It would be great to have an optional argument like `--log file.log` which would then write all console messages to it so it could be viewed remotely for diagnostics.

**Comment by mashb1t** [comment]
A workaround would be to use docker compose with the file log driver.
Dockerfile: see https://github.com/lllyasviel/Fooocus/pull/1154

**Comment by mashb1t** [comment]
@SpcCw The secret to make it work is to either flush Python buffer or not use any.
`-u` does the trick here to disable the buffer altogether:
` .\python_embeded\python.exe -u -s Fooocus\entry_with_update.py`

This may cause issue though. See https://www.baeldung.com/linux/python-buffering-and-tee


You can also use PowerShell with Tee-Object in combination with `-u`. Tested and it's working with `.\python_embeded\python.exe -u -s Fooocus\entry_with_update.py -- listen | Tee-Object -FilePath "output.log"`
See https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/tee-object?view=powershell-7.4#example-1-output-processes-to-a-file-and-to-the-console
