### ISSUE TITLE
This is lobe-ui, combined with "Fooocus" should work well

### ISSUE THREAD

**Issue by twitf** [lllyasviel/Fooocus#1417]
This is a UI library specially used for AIGC applications. This is amazing. Combined with "Fooocus", it should work well. You can take a look.

lobe-ui
https://github.com/lobehub/lobe-ui

**Comment by mashb1t** [comment]
Fooocus is built on Gradio. Completely refactoring to lobe-ui would mean a very high time invest - time which is most likely better spent developing new features.
Closing this issue for now, but nevertheless: thank you for the idea!
