### ISSUE TITLE
always-gpu tensor error in inpaint mode

### ISSUE THREAD

**Issue by doer20** [lllyasviel/Fooocus#1419]
[Fooocus Model Management] Moving model(s) has taken 0.50 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 3.0
[Parameters] Seed = 3427956263218991440
[Fooocus] Downloading inpainter ...
[Inpaint] Current inpaint model is /Fooocus/models/inpaint/inpaint_v26.fooocus.patch
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Synthetic Refiner Activated
Synthetic Refiner Activated
Request to load LoRAs [['SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 0.25], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/data/models/Stable-diffusion/xl/realisticStockPhoto_v10.safetensors].
Loaded LoRA [/Fooocus/models/loras/SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for UNet [/data/models/Stable-diffusion/xl/realisticStockPhoto_v10.safetensors] with 788 keys at weight 0.25.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] a girl, full focus, cute, intricate, expressive, highly detailed, sharp focused, cinematic, new creative color, elegant, fashionable, beautiful, futuristic, colors spread, symmetry, light, fine detail, joyful, amazing, glowing, attractive, pretty, noble, perfect, lucid, thought, winning, complex, artistic, iconic, clear, brilliant, epic, shining
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] a girl, very serious, full focus, elegant, intricate, dramatic bright colors, highly detailed, innocent, mystical, enchanted, magic, scenic background, professional, artistic, winning, best, fair, beautiful, cinematic, great composition, original, dynamic, exciting, attractive, creative, positive, lively, awesome, symmetry, perfect, pretty, rational, healthy, pure
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Fooocus] Image processing ...
Upscaling image with shape (661, 661, 3) ...
[Fooocus] VAE Inpaint encoding ...
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.18 seconds
[Fooocus] VAE encoding ...
Traceback (most recent call last):
  File "/Fooocus/modules/async_worker.py", line 803, in worker
    handler(task)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Fooocus/modules/async_worker.py", line 598, in handler
    pipeline.final_unet = inpaint_worker.current_task.patch(
  File "/Fooocus/modules/inpaint_worker.py", line 195, in patch
    feed = torch.cat([
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument tensors in method wrapper_CUDA_cat)
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models

**Comment by doer20** [comment]
Seem like inpaint_mask tensor is on device:cpu. But in always-gpu mode, vae encoded latent_inpaint tensor is on cuda.

**Comment by lllyasviel** [comment]
try 2.1.841
