### ISSUE TITLE
A option to use seed numbers

### ISSUE THREAD

**Issue by vanguard-bit** [lllyasviel/Fooocus#1422]
Most of the apis like webui supports using seeds to generate the same image
The log does an amazing job of keeping tabs of styles so if there is option to use seed it would be wonderful.

I would like something similar to webui's way of using seeds so we can build over a image or just an option bar to use the seed.

**Comment by lllyasviel** [comment]
in ui uncheck random
in log there is seed

**Comment by vanguard-bit** [comment]
I totally missed it
Thankyou so much
