### ISSUE TITLE
Large aspect ratio image cut in InPaint zoom

### ISSUE THREAD

**Issue by neckaros** [lllyasviel/Fooocus#1427]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
If you have a large image in the inpaint and you zoom with "S" key it is cut

![image](https://github.com/lllyasviel/Fooocus/assets/7789770/b3860949-f7fc-4912-b2f9-56bcbc6e893b)

Step to reproduce: 

- in advanced choose aspect ratio 3:1

- generate without any prompt
- Move to InPaint tab and drag the generated image
- over the inpaint and press S key

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/pull/1428
