### ISSUE TITLE
Quality is getting worse!

### ISSUE THREAD

**Issue by tralala87** [lllyasviel/Fooocus#1434]
I have noticed, that the quality of images when generating people is getting worse. When I ran the colab 1 week ago, the image was sharp and no deformities, now it is horrible, blurry, a lot of small defects.

**Comment by lllyasviel** [comment]
hi recently changes only effect float point processing and some seeds will have random differences (but not better or worse). No changes are related to image quality.

you may give more detailed examples for us to look into it, or use previous versions [here]( https://github.com/lllyasviel/Fooocus/discussions/1405)

**Comment by tralala87** [comment]
Solved it.
