### ISSUE TITLE
Please roll-back this release its not working on intel

### ISSUE THREAD

**Issue by rvdd1962** [lllyasviel/Fooocus#1435]
Why did you change all the names of the extra parameters. It was --cpu and not it is --aways-cpu etc.
Good thing i saved my old Fooocus setup cos the new release just keeps giving cuda errors. CPU only mode won't start!

**Comment by lllyasviel** [comment]
Hi in recent version we begin to officially support cmd flags. You may also use previous versions [here]( https://github.com/lllyasviel/Fooocus/discussions/1405)

**Comment by agilepeter** [comment]
This broke for mac intel... When cmd flags?

**Comment by lllyasviel** [comment]
hi mac intel is not supported. Current support for MPS M1/M2 is experimental.
See also https://github.com/divamgupta/diffusionbee-stable-diffusion-ui

**Comment by rvdd1962** [comment]
I'm back now on running version 2.1.823. Glad i've made a backup before installing and testing the new version.
I'm not running on a Intel MAC btw. I'm running your nice software in an Intel Based Cloud service. 
I have both Fooocus (version 2.1.823) and Stable diffusion Webui with OpenVino (Intel) in my cloud enviroment up and running. 
Stable diffusion takes just under 2 minutes for rendering 1024x1024, Fooocus takes double the time for same resolution (20 steps). I had to make a few chances in your code to get the nasty INFO log messages out and do automatic clean-up for the gradio/tmp directory after each image rendering. I rely heavly on good rendered images for my work. I don't mind waiting on the rendering on just the CPU cores. Those basterds i've got are fricking fast and alot of RAM is avaible for heavy render tasks.
I like the good outpainting in Fooocus for extending images, Fooocus is the best at that job.
Also face-swap is very good in Fooocus, nearly pergect.
And i use Fooocus alot  to give my nice subtle variations (the way Midjourney does) for inspiration.
So nice work on Fooocus guys, don't get me wrong ... i was just a tiny bit disappointed after installing the new update.

**Comment by rvdd1962** [comment]
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
Fooocus version: 2.1.823
Home directory is /home/ua425c61a1b86c4b52a620ba6ef2eae6 and tmp is /home/ua425c61a1b86c4b52a620ba6ef2eae6/Fooocus/tmp
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 515700 MB, total RAM 515700 MB
xformers version: 0.0.23
Set vram state to: DISABLED
Disabling smart memory management
Device: cpu
VAE dtype: torch.float32
Using split optimization for cross attention
Refiner unloaded.
model_type EPS
adm 2816
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE

**Comment by rvdd1962** [comment]
![Screen-1](https://github.com/lllyasviel/Fooocus/assets/149718040/dccbbd7f-7d86-4b1c-846c-425e7fd54214)
![Screen-3](https://github.com/lllyasviel/Fooocus/assets/149718040/76f5ee10-7e24-49fc-a593-9535a0425d86)
![Screen-4](https://github.com/lllyasviel/Fooocus/assets/149718040/3ac12595-9645-489f-9b9a-785f0fb9c455)

**Comment by lllyasviel** [comment]
thanks for the input!

you may paste full log with error from latest version

or this issue will not have sufficient info for dev to look into.

**Comment by rvdd1962** [comment]
Okay i do that tomorrow, i've to reinstall the new version and will grab the errors as they come along.
OpenVino support in Fooocus would be nice in the next year, as you can see its 2/3 faster on CPU's (LCM not counted) just basic rendering 20 steps high-res. For my work I rely on my laptop and take it with me when visiting clients, its not a render beast machine. So I just access my Intel based Cloud service for any rendering while i'm there to show them some ideas for the projects i'm working on. I like the simple and effective interface of Fooocus, it doesn't scare the customer so much ;-).

**Comment by rvdd1962** [comment]
Okay i'v managed to get the render time down from 8 minutes to just 2 minutes ... so Fooocus on cpu is now just as fast as Stable diffusion webui with OpenVino. I will tweak some more to see if i can squize more juice out of of Fooocus, maybe i'll even more faster render time.
![Render-time](https://github.com/lllyasviel/Fooocus/assets/149718040/9e0d8ed8-5f4a-459f-be21-836548567654)
