### ISSUE TITLE
Add a "Mask Image Input" for inpainting feature.

### ISSUE THREAD

**Issue by YuWongXX** [lllyasviel/Fooocus#1438]
Add a "Mask Image Input" for inpainting feature.

**Comment by kubilaykilinc** [comment]
I wrote before this. I hope it can be

**Comment by mashb1t** [comment]
Duplicate of https://github.com/lllyasviel/Fooocus/issues/879, implemented in PRs https://github.com/lllyasviel/Fooocus/pull/529 and https://github.com/lllyasviel/Fooocus/pull/1126
