### ISSUE TITLE
[Feature Request] Windows CLI terminal text displayed in the browser 

### ISSUE THREAD

**Issue by xx88xx** [lllyasviel/Fooocus#1439]
I'm running the install remotely and don't have access to the original machine. It would be super useful to display the windows CLI terminal info in browser to know if fooocus has stalled or what not.

Ie. This information:

![image](https://github.com/lllyasviel/Fooocus/assets/60696375/ddde376e-d29a-4230-a4e7-df7312aeb7af)

**Comment by mashb1t** [comment]
This isn't easily possible as all occurences of `print` will have to be wrapped with a function which then also saves to a file and extend Fooocus to show that file im the browser OR always update the gradio UI when primting to console, which is only possible with a huge codebase refactoring.

You can already use RDP to connect to your Windows instance remotely to see the output of your terminal, given you have enabled port forwarding for 3389 (TCP and UDP).

relates to https://github.com/lllyasviel/Fooocus/issues/1415 (kind of) if you want to use another workaround by using Docker and a static file server for the Docker log file output.

**Comment by SpcCw** [comment]
Another workaround which I currently use:
- [install SSH server](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=gui) on Windows machine
- connect and run Fooocus in SSH

Works fine and doesn't block existing user session so someone else can work on the PC without any interference. Also it is faster to start, less resource heavy and somewhat easier to secure if external access required.

Limitations: if session drops the application can drop as well and you have to start the app manually.

I usually run Fooocus as scheduled task and relaunch it via SSH if it crashes systematically so I can see what causes it.
