### ISSUE TITLE
Unable to re-generate the same image

### ISSUE THREAD

**Issue by That-Dude** [lllyasviel/Fooocus#144]
I am unable to re-generate the same image, even though my parameters do not change.

Prompt: cat
Style: none
Negative: empty
Seed: 2269664799
Size: 1024 x 1024
Lora: none
Sampling sharpness: 0

--
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 1.0.31
Inference Engine exists.
Inference Engine checkout finished.
Running on local URL:  http://0.0.0.0:7860
Total VRAM 24576 MB, total RAM 31893 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention

**Comment by runew0lf** [comment]
The seed is greater than the maximum of 1024 *1024 * 1024(1,073,741,824 maximum seed number) so it changes it to a random number
