### ISSUE TITLE
Change color of inpaint mouse cursor

### ISSUE THREAD

**Issue by rrdd** [lllyasviel/Fooocus#1443]
Is it possible to change the cursor color for inpainting or marking images? This would be especially useful for bright images.

Is it necessary to make the outlines of the markings very precise?

Thank You

**Comment by mashb1t** [comment]
> Is it possible to change the cursor color for inpainting or marking images? This would be especially useful for bright images.

Currently this is only possible by changing the brush_color in the code here: https://github.com/lllyasviel/Fooocus/blob/main/webui.py#L189

> Is it necessary to make the outlines of the markings very precise?

Yes, you have to be pretty precise, but SD might be a bit forgiving. Fooocus currently does not add a threshold to the inpaint mask.

Hope this helps!
