### ISSUE TITLE
Cant use api in python to get image

### ISSUE THREAD

**Issue by Syndicateeee** [lllyasviel/Fooocus#1451]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
I want to use the api of Fooocus to generate an image in python. The said way in the api docs (fn_index: 31) is not working because of the formatting in "704×1408 <span style="color: grey;"> ∣ 1:2</span>". When i copy it python has two strings "704×1408 <span style=" and "> ∣ 1:2</span>" but  color: grey; in the middle is left out of the string. Please help me out.

**Comment by mashb1t** [comment]
Escaping the string like this should work for you: ``"1024×1024 <span style=\"color: grey;\"> ∣ 1:1</span>"``

**Comment by miraculix95** [comment]
You are talking about fn_index: 30, correct?
I have corrected for the issue but I still did not get it to work. It would be great if someone could provide a working minimal example.

**Comment by Syndicateeee** [comment]
Im using `https://github.com/konieshadow/Fooocus-API`now this worked for me thanks all.

**Comment by miraculix95** [comment]
Can you give a simple python code example for the generation of a simple image?
I find the explanation on Fooocus-API also lacking.
Thanks :)

**Comment by Syndicateeee** [comment]
[get_image.txt](https://github.com/lllyasviel/Fooocus/files/13751717/get_image.txt)
There you go, make sure to run the Fooocus-Api server before executing this script
