### ISSUE TITLE
Styles problem

### ISSUE THREAD

**Issue by AdamKnappZ** [lllyasviel/Fooocus#1452]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
In the style section when i use the comic book one, sometimes the A.I gives me an image that's okay but sometimes it just gives me an image that's far away from being a comic book one, i made sure myself of turning off any other style but it's still not working at all...

**Comment by lllyasviel** [comment]
show examples

**Comment by AdamKnappZ** [comment]
<img width="545" alt="Captura de pantalla 2023-12-17 202527" src="https://github.com/lllyasviel/Fooocus/assets/102090580/ea491167-e040-44a0-8abb-a18d124f06a5">
<img width="257" alt="Captura de pantalla 2023-12-17 202534" src="https://github.com/lllyasviel/Fooocus/assets/102090580/551f4ff9-ac65-46b3-82d3-284ab5eca30f">
<img width="252" alt="Captura de pantalla 2023-12-17 202541" src="https://github.com/lllyasviel/Fooocus/assets/102090580/1fe264ee-f910-4b7b-b3a9-ba7e5dc42406">


**The image i got:** 

<img width="245" alt="Captura de pantalla 2023-12-17 202646" src="https://github.com/lllyasviel/Fooocus/assets/102090580/171343af-6526-4f73-b15e-a86c328a17d6">

I've tried with SAI Comic book style but i get the same result.

**Comment by lllyasviel** [comment]
this is wierd. what does this image look like in history log?

**Comment by AdamKnappZ** [comment]
It looks like this: 


<img width="947" alt="Captura de pantalla 2023-12-17 210438" src="https://github.com/lllyasviel/Fooocus/assets/102090580/12d21902-3411-475b-b2b8-df547341b548">

**Comment by lllyasviel** [comment]
I can reproduce this problem. This is in juggernautXL and can also be reproduced in other software. Perhaps try another model..

**Comment by AdamKnappZ** [comment]
If i'd like to generate comic images, which model would you recommend me?, i've tried SDXL base model but faces are absolutely HORRIBLE.. and as you didn't put after detailer inside foocus it's kinda difficult

**Comment by lllyasviel** [comment]
hi

for face detail see also https://github.com/lllyasviel/Fooocus/discussions/414#detail

**Comment by AdamKnappZ** [comment]
It gives me this error: 

<img width="657" alt="Captura de pantalla 2023-12-17 234021" src="https://github.com/lllyasviel/Fooocus/assets/102090580/ebeb6a8d-a9aa-4788-94eb-64765a6eafc8">
<img width="933" alt="Captura de pantalla 2023-12-17 234030" src="https://github.com/lllyasviel/Fooocus/assets/102090580/140b6a01-8b2a-4452-a32f-70bb68d87acb">

**Comment by AdamKnappZ** [comment]
Forget it, i fixed it, thanks!!!

**Comment by artinfbi** [comment]
how did you fixed it
