### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by laradascom** [lllyasviel/Fooocus#1466]
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
![image](https://github.com/lllyasviel/Fooocus/assets/143678013/f963922d-1f20-42f6-a555-89705073b9fa)

**Comment by mashb1t** [comment]
Please provide more information about your system specs, especially your GPU.

**Comment by dafour34** [comment]
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz 
![system spe](https://github.com/lllyasviel/Fooocus/assets/91681888/ffbfd1db-e39a-4e47-b691-e3919749e8c2)

This is my spec , will i be able to run Fooocus ? ( Sorry a bit noob there )

**Comment by mashb1t** [comment]
You do not have a graphics card (GPU), which means you have to run Fooocus solely on your processor (CPU) by using `--always-cpu` instead. This will be very slow (min. 19x slower than 30xx) and you might experience stuttering on your Laptop during generation.

**Comment by mashb1t** [comment]
@laradascom please change the instance in Colab to T4 or better, just tested again and it will work then.

**Comment by charliekayaker** [comment]
> @laradascom please change the instance in Colab to T4 or better, just tested again and it will work then.

Hi, how can i do it ? I have the same problem.

**Comment by mashb1t** [comment]
@charliekayaker upper right, click 🔻, change runtime type to T4. This may depend on the availability in your region.

**Comment by charliekayaker** [comment]
Oh, I am running it from its "run.bat" i don't know how can i change it from it. Anyway i will seek it.

**Comment by charliekayaker** [comment]
Sorry, I was reviewing my computer, and i have a good gpu, but no geforce. 

![image](https://github.com/lllyasviel/Fooocus/assets/53378855/c7aafae1-2699-4965-9830-e785d04ac0db)

I am lauching from here
![image](https://github.com/lllyasviel/Fooocus/assets/53378855/c87a3f73-0909-417f-87cb-444e634a170b)

Please, anybody could help me? Thanks

**Comment by mashb1t** [comment]
@charliekayaker https://github.com/lllyasviel/Fooocus/pull/2120/files

**Comment by charliekayaker** [comment]
@mashb1t first of all, thanks. I maked the installer.bat an i ran it. then i modified the run.bat like it mention. I try three time to run, run.bat, and i got   
  raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Maybe could i indicate, compile with cuda ?

**Comment by charliekayaker** [comment]
I try with the both ways for windows and intel graphics. But i can get it.

![image](https://github.com/lllyasviel/Fooocus/assets/53378855/55620ffd-f0b5-4026-bffd-36f318fa964e)

**Comment by charliekayaker** [comment]
Anybody could help me? I followed every step in the PR mentioned, I try to reinstall pytorch with CUDA support but i can get it. The only way is --always-cpu but i have INTEL GPU powerful

**Comment by mashb1t** [comment]
@charliekayaker as you've already started doing, please move over the discussion to https://github.com/lllyasviel/Fooocus/pull/2120

**Comment by mmsonder** [comment]
Hi, I already setup Pinokio.ia and Stable Diffusion web UI to my laptop  (Intel core i7-7500 with Intel HD Graphics 620). When I open and try to generate a photo Stable Diffusion web UI says that "RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx". But my computer has not got NVIDIA GPU. What should I do? If you give clear instruction to me I will be glad. 

Just one info when I setup Stable Diffusion web UI, it was gave the same error and just I modified "webui-user.bat" file like this:
Just I modified "set COMMANDLINE_ARGS=--skip-torch-cuda-test" 

![image](https://github.com/user-attachments/assets/334594d0-7ce5-4bae-a351-d85c08883cb6)
 
![image](https://github.com/user-attachments/assets/9372f266-9fc0-4d95-b652-2e2e8e8b762d)

**Comment by mashb1t** [comment]
@mmsonder i'm sorry, but as you can see in the readme, your computer does not fulfill the minimum system requirements. Feel free to only use CPU though.

**Comment by mmsonder** [comment]
> @mmsonder i'm sorry, but as you can see in the readme, your computer does not fulfill the minimum system requirements. Feel free to only use CPU though.

Thanks @mashb1t but how could I do this? Whic file or which line should I modify? I don't know whow could I do it.

**Comment by mmsonder** [comment]
> Stable Diffusion web UI

Dear @mashb1t Yes it is Stable Diffusion web UI and I have a problem with this. But I don't have run.bat file in the folder. 
Which file should I modified?
![image](https://github.com/user-attachments/assets/3dd11f4c-d75e-452c-bd5d-d5803e664536)

**Comment by mashb1t** [comment]
@mmsonder please ask your questions in https://github.com/AUTOMATIC1111/stable-diffusion-webui. Thread closed.
