### ISSUE TITLE
make it intel gpu friendly

### ISSUE THREAD

**Issue by imscartissue** [lllyasviel/Fooocus#1470]
make it intel gpu friendly

**Comment by dafour34** [comment]
Sorry i m a total noob but trying to work this out . Is 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz usable ? thanks !
![system spe](https://github.com/lllyasviel/Fooocus/assets/91681888/2bf2f5a1-aa54-4fab-8775-6d1e5f9c7545)

**Comment by flandweber** [comment]
> Sorry i m a total noob but trying to work this out . Is 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz 2.80 GHz usable ? 

Yes, the device that you showed is the processor (cpu). 
What is vendor-specific is the gpu.

**Comment by mashb1t** [comment]
@imscartissue just to make sure, you mean Intel ARC GPUs and not Intel integrated graphics, right?

**Comment by mashb1t** [comment]
closing as stale, please feel free to reopen when you have further feedback.
