### ISSUE TITLE
Can't use Blender or Daz3d renders as input for PyraCanny or CPDS

### ISSUE THREAD

**Issue by IamTirion** [lllyasviel/Fooocus#1473]
Hello, I'm trying to set up specific camera angles, character poses, depth of the scene, so I used Blender and Daz3d. But the renders from both softwares did not work well with PyraCanny or CPDS. For PyraCanny, the final image didn't follow the input image at all. For CPDS, it's heavily affected by the lighting of the input image, and the result looked terrible. does anybody know the reason for this? I didn't save the images, but I can re-create them as examples if needed.

**Comment by IamTirion** [comment]
Actually I think I found out the problem. I believe this is a limitation of the current models. The character or the person must be in the centre of the image for it to be used as an image prompt for PyraCanny, from my experience. Also the lighting from the image is for some reason used in CPDS, which shouldn't be the case because I think it should work similarly to a depth map? Unless the lighting affects how it interprets the image as a depth map, which does make sense I guess.

**Comment by R4290N** [comment]
No, you're wrong. CPDS doesn't work with depth map, it works with contrast and so copies the lighting accordingly.

**Comment by IamTirion** [comment]
> No, you're wrong. CPDS doesn't work with depth map, it works with contrast and so copies the lighting accordingly.

Thank you. I misunderstood the paper then sorry.
