### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by kenchambers** [lllyasviel/Fooocus#1479]
**Is your feature request related to a problem? Please describe.**

Greetings! I am unable to figure out how to "generate" using a negative prompt.

steps to run the problem: 
1. i click on run.bat

I can't seem to find the negative prompt anywhere.

I see in the readme for this repo that you have instructions for : 

A config flag, but I use the bat file to run.

`--no | Advanced -> Negative Prompt`

Please help ! Thank you

**Describe the idea you'd like**
A clear and concise description of how to use the negative prompt (using the GUI)

**Comment by Evoxus** [comment]
Hey @kenchambers that isn't saying there is a config flag, that is the comparison between Midjourney and Fooocus. In the Fooocus webui there is an advanced check box below the positive prompt input that opens the side panel (as seen in the screenshot below) where you can find the negative prompt input. Hope this helps and happy generating!
![Screenshot_20231217_181751](https://github.com/lllyasviel/Fooocus/assets/29982962/d626139b-7c26-4477-8f18-9fc6b970e10f)

**Comment by simartem** [comment]
is it possible to control the weight of the negative prompt ? Most of the times my negative prompts are disregarded

**Comment by kenchambers** [comment]
thank you for explanation @Evoxus 

appreciate the teams punctuality and response time!
