### ISSUE TITLE
repository path is not owned by the current user

### ISSUE THREAD

**Issue by AytoMaximo** [lllyasviel/Fooocus#148]
Hi!

Running the .bat file is not working for me. [comfyanonymous/ComfyUI](https://github.com/comfyanonymous/ComfyUI) is not available for download for some reason. 

![image](https://github.com/lllyasviel/Fooocus/assets/14392087/f5dbd0cb-27f1-40e6-a775-5ad383f25e8b)

**Comment by lllyasviel** [comment]
Many users have witness the problem "repository path is not owned by the current user".
But we cannot reproduce this problem in any machines. The tests pasted on my 4 windows devices with or without Git installed.
Any help is extremely appreciated, if someone can help us to find the steps to reproduce this problem on our machine.

**Comment by AytoMaximo** [comment]
> Many users have witness the problem "repository path is not owned by the current user". But we cannot reproduce this problem in any machines. The tests pasted on my 4 windows devices with or without Git installed. Any help is extremely appreciated, if someone can help us to find the steps to reproduce this problem on our machine.

Thank you for the answer! Can I overcome this issue by manually downloading the target repository using my Git client and placing it in the 'Fooocus\repositories\ComfyUI-from-StabilityAI-Official' directory? I'm at the step where I am trying to modify the 'entry_with_update.py' script so that it does not delete and re-download this repository.

**Comment by lllyasviel** [comment]
If you know what you are doing, you can follow the linux guide. But all future updates will need manual git pull

**Comment by lllyasviel** [comment]
And all files are already distrubuted inside the 7z package, so that even if the git fails, the app will still work. You may have edited some files or used other method to download the App.

**Comment by lllyasviel** [comment]
And if someone how to solve this problem or how to make this problem reproducible, please let me know as soon as possible.

**Comment by AytoMaximo** [comment]
> all files are already distributed inside the 7z package

I simply clicked here and extracted all files 
![image](https://github.com/lllyasviel/Fooocus/assets/14392087/b1096867-2484-4c3d-8c14-8e1788afa43d)

**Comment by lllyasviel** [comment]
If that is true, you can even run without internet if the models are already here. Run without internet is also tested extensively and there is no reason for lack of dependency if git fails.

**Comment by AytoMaximo** [comment]
> If that is true, you can even run without internet if the models are already here

The issue is that after extracting the 7Z file, the files are indeed present, but running the .bat file erases everything in the 'Fooocus\repositories\ComfyUI-from-StabilityAI-Official' folder and attempts to re-download them.

**Comment by AytoMaximo** [comment]
> Please let me know if someone has ideas

Hey, I have a clue. I think the issue is related to the drive's file system type. I have a problem with exFAT, but unzipping to the NTFS file system causes no problems.

**Comment by rraihansaputra** [comment]
confirming @AytoMaximo; i had this issue the first day the repo was released but solved it by extracting and running on NTFS instead of exFAT. This is related to the git command.

I _think_ i'm running the first release with the `import cuda_malloc` commented out without issues.

**Comment by Guillaume-Fgt** [comment]
> Many users have witness the problem "repository path is not owned by the current user". But we cannot reproduce this problem on any machines. The tests passed on my 4 windows devices with or without Git installed. Any help is extremely appreciated, if someone can help us to find the steps to reproduce this problem on our machine.

I didn't have any trouble on my machine but I successfully reproduce it by doing the following steps:
- run a Command Prompt **as administrator**
- git clone Fooocus repo. Once finished, if you right click on the Fooocus dir created ==>Security tab ==>advanced button. The owner of the folder should be `Administrators`.
- create a venv, install pygit2 and run `entry_with_update.py`

console message:

> Update failed.
> f:\Fooocus: repository path 'f:/Fooocus/' is not owned by current user
> Update succeeded.

**Comment by AytoMaximo** [comment]
> > Many users have witness the problem "repository path is not owned by the current user". But we cannot reproduce this problem on any machines. The tests passed on my 4 windows devices with or without Git installed. Any help is extremely appreciated, if someone can help us to find the steps to reproduce this problem on our machine.
> 
> I didn't have any trouble on my machine but I successfully reproduce it by doing the following steps:
> 
> * run a Command Prompt **as administrator**
> * git clone Fooocus repo. Once finished, if you right click on the Fooocus dir created ==>Security tab ==>advanced button. The owner of the folder should be `Administrators`.
> * as a local user, create a venv, install pygit2 and run `entry_with_update.py`
> 
> console message:
> 
> > Update failed.
> > f:\Fooocus: repository path 'f:/Fooocus/' is not owned by current user
> > Update succeeded.

Agreed, after chatting with ChatGPT yesterday, we came to the same conclusion: the exFAT drive type does not allow privilege control over files and folders, unlike NTFS. That's why you are facing some access problems.

**Comment by Guillaume-Fgt** [comment]
In my case, I used a USB stick formatted in NTFS. But I voluntary gave the ownership of the repo folder to an other account (admin). Maybe this mechanism is done automatically in other file system formats.

**Comment by AytoMaximo** [comment]
I'd really like to know how to overcome this exFAT limitation, because I intentionally bought a large external SSD to host big ML models.

**Comment by rraihansaputra** [comment]
@AytoMaximo maybe you can try just extracting the repository first, then link/alias (I'm not sure what the term is for windows) the Fooocus/models directory to your external drive before running the .bat?

**Comment by AytoMaximo** [comment]
> @AytoMaximo maybe you can try just extracting the repository first, then link/alias (I'm not sure what the term is for windows) the Fooocus/models directory to your external drive before running the .bat?

I wonder, If the batch file starts with erasing this directory, wouldn't it do the same with the alias?

**Comment by rraihansaputra** [comment]
Yes, I suggest placing the checkpoints on the exFAT drive and leaving Foocus on the NTFS drive. The .bat only deletes the repository directory as far as i know.

**Comment by lllyasviel** [comment]
I made a new package in 1.0.35 https://github.com/lllyasviel/Fooocus/releases/tag/1.0.35
Hopefully this is solved
Someone please test

**Comment by kirbykirby** [comment]
> I made a new package in 1.0.35 https://github.com/lllyasviel/Fooocus/releases/tag/1.0.35 Hopefully this is solved Someone please test

I run it on an external SSD with exFAT format. Same cuda_malloc issue. It ran smoothly before 1.032 update.

**Comment by jw408** [comment]
> I made a new package in 1.0.35 https://github.com/lllyasviel/Fooocus/releases/tag/1.0.35 Hopefully this is solved Someone please test

Tried and no dice, same error (linux/venv; WSL2) - https://github.com/lllyasviel/Fooocus/issues/169#issuecomment-1684033119

**Comment by jw408** [comment]
Found a solution for people having this problem, see this other thread https://github.com/lllyasviel/Fooocus/issues/169#issuecomment-1684033119

**Comment by CCC197** [comment]
![微信图片_20231106114935](https://github.com/lllyasviel/Fooocus/assets/149988515/8bfc5315-e845-4175-a711-4b40900a075a)有没有大佬知道这是怎么回事
