### ISSUE TITLE
Add custom output path to allowed paths

### ISSUE THREAD

**Issue by koriekhov** [lllyasviel/Fooocus#1485]
**Description**
If I set custom Output folder, the History Log becomes inaccessible. Browser showing error output:
{"detail":"File not allowed: F:/Projects/AI/Support/Output/txt2img/2023-12-18/log.html."}

I can fix this by adding "allowed_paths" to gradio launch() method, but it will be overwritten with each update.

**Proposition**
Maybe its worth of adding something like launch(allowed_paths = custom_output_path) ?

**Comment by lllyasviel** [comment]
this is planned but have some security considerations since some people share public link to internet and this may cause problem to their file security

**Comment by koriekhov** [comment]
Oh, ok, I see. Makes sence.
Thank you.

**Comment by dhlsam** [comment]
> **Description** If I set custom Output folder, the History Log becomes inaccessible. Browser showing error output: {"detail":"File not allowed: F:/Projects/AI/Support/Output/txt2img/2023-12-18/log.html."}
> 
> I can fix this by adding "allowed_paths" to gradio launch() method, but it will be overwritten with each update.
> 
> **Proposition** Maybe its worth of adding something like launch(allowed_paths = custom_output_path) ?

same problem {"detail":"File not allowed: F:/Projects/AI/Support/Output/txt2img/2023-12-18/log.html."}
how to adding "allowed_paths" to gradio launch() 😊 rookies here
