### ISSUE TITLE
Proxy Work Around

### ISSUE THREAD

**Issue by jordanbr20** [lllyasviel/Fooocus#1491]
If a proxy is on, the Application does not work, please provide a proxy server list exception that the application uses so that it can be added to manual proxy setups in order to use the application and have proxy on at the same time.

**Comment by mashb1t** [comment]
Please provide some more insights into what you mean by 
> If a proxy is on, the Application does not work

We do not maintain a proxy server list exception. 
I'd suggest an iterative approach: You can check which download URL (or whatever issue with the app you have) doesn't work and then add it to your proxy server exception list.
Thank you for your feedback.

**Comment by mashb1t** [comment]
Closing as stale. Feel free to reopen when providing new information.
