### ISSUE TITLE
consistent face

### ISSUE THREAD

**Issue by thomasmechanix** [lllyasviel/Fooocus#1494]
Dear all, I've been trying to work out how to generate consistent face character using Fooocus but failed to do so. Can I suggest a real faceswap feature that allows say multiple uploads of character A (same person, different photo samples), and B (a pose e.g. crossed arms). Also when I set weight=2 in faceswap, two heads are showing up.

**Is your feature request related to a problem? Please describe.**

**Describe the idea you'd like**

**Comment by mashb1t** [comment]
this is a perfect use case for https://github.com/lllyasviel/Fooocus/issues/1522, which we might implement in the future.
