### ISSUE TITLE
Is there any option to generate all styles with the given prompt ?

### ISSUE THREAD

**Issue by simartem** [lllyasviel/Fooocus#1496]
Is there any option to generate all of the styles available on Fooocus ?
For example : I want to give a prompt "retro american car" , and generate seperately each of the styles. 185 images for example.

**Comment by mashb1t** [comment]
No, there currently isn't. You might be able to do it by writing a script using the Fooocus Gradio API though.

**Comment by simartem** [comment]
> No, there currently isn't. You might be able to do it by writing a script using the Fooocus Gradio API though.

Thank you for your response. I wish i had a chance to write but i am not that expert. I used to write code in other platforms such as C# etc.. but i am not really into py things. If you can redirect me to a source, i will try because i really would have this process automated.. In a1111 i have an extension SDXL style and it generates all the styles just one enabled box.

**Comment by mashb1t** [comment]
You can do it via API (e.g. https://github.com/konieshadow/Fooocus-API as wrapper or the Gradio API in Fooocus directly) or extend the webui.py by e.g. adding a new button which then itself iterates over the styles, updates the UI and triggers the click on generate for each style (via JS or Python).

REST API: https://m.youtube.com/watch?v=-mN3VyJuCjM
Gradio: https://www.gradio.app/
Generate Button: https://github.com/lllyasviel/Fooocus/blob/main/webui.py#L560
Trigger a button via JS in Gradio: https://github.com/lllyasviel/Fooocus/pull/1043/files#diff-e093b909cce8fa9f0d7a77571607f8a1f9733c18d6e68ca2d03699c962df6fb5R514

**Comment by mashb1t** [comment]
Good News: A solution to your problem can be found in https://github.com/lllyasviel/Fooocus/issues/1664, specifically https://github.com/lllyasviel/Fooocus/issues/1664#issuecomment-1873379637!
THis has not yet been officially implemented, but is usable.

**Comment by agarwalanant** [comment]
It is because too many people are trying to access the API and the worker queue has reached it's limits. The only work around is to deploy on private replicate endpoint or wait for queue to be empty.
