### ISSUE TITLE
Feature Request   Remember settings

### ISSUE THREAD

**Issue by jlitz** [lllyasviel/Fooocus#150]
have to reload advanced setttings everytime

**Comment by barepixels** [comment]
Does anyone use Fooocus without Advance checked at all?

**Comment by MoonRide303** [comment]
@jlitz You can check out [my fork](https://github.com/MoonRide303/Fooocus-MRE) - if you want to have advanced mode enabled by default, then you just set `"advanced_mode": true` in settings.json. You can customize default values of all UI setting, this way.

**Comment by jlitz** [comment]
tnx  tho  a save settings  button may be easier than screwing with json files coonstantly

**Comment by mashb1t** [comment]
There are actually a lot of issues like this, see in https://github.com/lllyasviel/Fooocus/issues/692 (https://github.com/lllyasviel/Fooocus/issues/692#issuecomment-1873365427) or https://github.com/lllyasviel/Fooocus/issues/1622. Closing this one, focusing on https://github.com/lllyasviel/Fooocus/issues/1622
