### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Rafi1018** [lllyasviel/Fooocus#1501]
Getting this error
"RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 52428800 bytes."

I'm using the latest version of Fooocus & downloaded according to the AMD GPU. It isn't a problem if it runs slow so how can I solve it & use it?

Like allocating more VRAM or to run it with CPU ?

**Comment by Rafi1018** [comment]
bump

**Comment by tearno** [comment]
It looks like a **RAM** issue.

Thus, I would recommend you to take a look at the following guide on System Swap in Troubleshoot:
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#system-swap

Let me know if this helps!
