### ISSUE TITLE
AMD not working for windows

### ISSUE THREAD

**Issue by samrluxford** [lllyasviel/Fooocus#1502]
Hi the problem I am having is that after looking into the problem I believe has to do with the AMD on windows, that's what I have and after looking into it found that was a problem that might occur I was unable to find a solution to it though and when I look at the console I see that it should work from this code I found on a previous commit. The only thing I get coming up when I hit generate is error at the moment with no more information.
`    import torch 

    def detect_gpu_type():
        if torch.cuda.is_available():
            gpu_name = torch.cuda.get_device_name(0)  
            if "NVIDIA" in gpu_name:
                return "NVIDIA GPU"
            elif "Radeon" in gpu_name:
                return "AMD GPU"
            else:
                return "Unknown GPU Type"
        else:
            return "No GPU Available"

    gpu_type = detect_gpu_type()
    print("Detected GPU Type:", gpu_type)`

C:\Users\Luxford\Desktop\Fooocus files>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset realistic
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'realistic']
Loaded preset: C:\Users\Luxford\Desktop\Fooocus files\Fooocus\presets\realistic.json
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.853
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\Luxford\Desktop\Fooocus files\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "C:\Users\Luxford\Desktop\Fooocus files\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "C:\Users\Luxford\Desktop\Fooocus files\Fooocus\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "C:\Users\Luxford\Desktop\Fooocus files\Fooocus\modules\patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "C:\Users\Luxford\Desktop\Fooocus files\Fooocus\ldm_patched\modules\model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "C:\Users\Luxford\Desktop\Fooocus files\Fooocus\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 18, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "C:\Users\Luxford\Desktop\Fooocus files\Fooocus\ldm_patched\ldm\modules\attention.py", line 12, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "C:\Users\Luxford\Desktop\Fooocus files\Fooocus\ldm_patched\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "C:\Users\Luxford\Desktop\Fooocus files\Fooocus\ldm_patched\modules\model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\Luxford\Desktop\Fooocus files\Fooocus\ldm_patched\modules\model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\Luxford\Desktop\Fooocus files\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\Luxford\Desktop\Fooocus files\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by Rafi1018** [comment]
edit your run.bat with this

.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
.\python_embeded\python.exe -m pip install torch-directml
python entry_with_update.py --directml --preset realistic
pause

**Comment by samrluxford** [comment]
I edited the batch file like you said but i now unfortunately get this instead also I am using the run_realistic sorry for not mentioning before.


C:\Users\Luxford\Desktop\Fooocus files>.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
Found existing installation: torch 2.0.0
Uninstalling torch-2.0.0:
  Successfully uninstalled torch-2.0.0
Found existing installation: torchvision 0.15.1
Uninstalling torchvision-0.15.1:
  Successfully uninstalled torchvision-0.15.1
WARNING: Skipping torchaudio as it is not installed.
WARNING: Skipping torchtext as it is not installed.
WARNING: Skipping functorch as it is not installed.
WARNING: Skipping xformers as it is not installed.

C:\Users\Luxford\Desktop\Fooocus files>.\python_embeded\python.exe -m pip install torch-directml
Requirement already satisfied: torch-directml in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (0.2.0.dev230426)
Collecting torch==2.0.0 (from torch-directml)
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting torchvision==0.15.1 (from torch-directml)
  Using cached torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
Requirement already satisfied: filelock in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.12.2)
Requirement already satisfied: typing-extensions in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (4.7.1)
Requirement already satisfied: sympy in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (1.12)
Requirement already satisfied: networkx in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.1)
Requirement already satisfied: jinja2 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.1.2)
Requirement already satisfied: numpy in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (1.23.5)
Requirement already satisfied: requests in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (9.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from jinja2->torch==2.0.0->torch-directml) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (2023.5.7)
Requirement already satisfied: mpmath>=0.19 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from sympy->torch==2.0.0->torch-directml) (1.3.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: torch, torchvision
  WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'C:\Users\Luxford\Desktop\Fooocus files\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed torch-2.0.0 torchvision-0.15.1

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\Luxford\Desktop\Fooocus files\python_embeded\python.exe -m pip install --upgrade pip

C:\Users\Luxford\Desktop\Fooocus files>python entry_with_update.py --directml --preset realistic
'python' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Luxford\Desktop\Fooocus files>pause
Press any key to continue . . .

**Comment by willywwang** [comment]
you need to add python to your path in window. when you install python, check the box that says add system paths or something along those lines.

**Comment by samrluxford** [comment]
Thanks I hadn't ticked that box on the install but after doing that I am having a problem with it not find in the files with in the files in the folders Fooocus and python_embed. Is there anyway to fix this preferably without putting all the files in the same folder as the batch files otherwise it will be fairly disorganised or is that my only option?


C:\Users\Luxford\Desktop\Fooocus files>.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
Found existing installation: torch 2.0.0
Uninstalling torch-2.0.0:
  Successfully uninstalled torch-2.0.0
Found existing installation: torchvision 0.15.1
Uninstalling torchvision-0.15.1:
  Successfully uninstalled torchvision-0.15.1
WARNING: Skipping torchaudio as it is not installed.
WARNING: Skipping torchtext as it is not installed.
WARNING: Skipping functorch as it is not installed.
WARNING: Skipping xformers as it is not installed.

C:\Users\Luxford\Desktop\Fooocus files>.\python_embeded\python.exe -m pip install torch-directml
Requirement already satisfied: torch-directml in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (0.2.0.dev230426)
Collecting torch==2.0.0 (from torch-directml)
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting torchvision==0.15.1 (from torch-directml)
  Using cached torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
Requirement already satisfied: filelock in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.12.2)
Requirement already satisfied: typing-extensions in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (4.7.1)
Requirement already satisfied: sympy in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (1.12)
Requirement already satisfied: networkx in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.1)
Requirement already satisfied: jinja2 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.1.2)
Requirement already satisfied: numpy in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (1.23.5)
Requirement already satisfied: requests in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (9.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from jinja2->torch==2.0.0->torch-directml) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (2023.5.7)
Requirement already satisfied: mpmath>=0.19 in c:\users\luxford\desktop\fooocus files\python_embeded\lib\site-packages (from sympy->torch==2.0.0->torch-directml) (1.3.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: torch, torchvision
  WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'C:\Users\Luxford\Desktop\Fooocus files\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed torch-2.0.0 torchvision-0.15.1

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\Luxford\Desktop\Fooocus files\python_embeded\python.exe -m pip install --upgrade pip

C:\Users\Luxford\Desktop\Fooocus files>python entry_with_update.py --directml
python: can't open file 'C:\\Users\\Luxford\\Desktop\\Fooocus files\\entry_with_update.py': [Errno 2] No such file or directory

C:\Users\Luxford\Desktop\Fooocus files>pause
Press any key to continue . . .

**Comment by lllyasviel** [comment]
hi 

if you meet

`python is not recognized as an internal or external command,`

or 

`No such file or directory`

or 

`Found no NVIDIA driver on your system.`

or 

`Torch not compiled with CUDA`

Then it means you are not following official installation guides, or mislead by wrong internet tutorials or wrong response of other users.

We cannot offer any help if users intentionally ignore official installation guides.

See also

https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windowsamd-gpus

https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement

https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

**Comment by Rafi1018** [comment]
> C:\Users\Luxford\Desktop\Fooocus files>python entry_with_update.py --directml python: can't open file 'C:\Users\Luxford\Desktop\Fooocus files\entry_with_update.py': [Errno 2] No such file or directory
> 
> C:\Users\Luxford\Desktop\Fooocus files>pause Press any key to continue . . .


You need to add .\ before python here actually

**Comment by willywwang** [comment]
i think he means after but yeah `python .\entry_with_update.py --directml` should do the trick for you!

**Comment by samrluxford** [comment]
Yes that fixed thankyou very much for the help.
