### ISSUE TITLE
Launching Fooocus command not working - macOS

### ISSUE THREAD

**Issue by dirtyj375** [lllyasviel/Fooocus#1504]
First - completely new to all of this, but I'm wanting to learn. 

I installed Fooocus and used it basically all day yesterday - no problems at all. It's been great. Learned a lot.

Today, I'm attempting to jump back in, and in [the guide](https://github.com/lllyasviel/Fooocus) I'm reading "Launch Fooocus by running 'python entry_with_update.py'", but I'm getting "python: can't open file '/Users/myuser/entry_with_update.py': [Errno 2] No such file or directory". 

The "entry_with_update.py" file does exist, but the file path to it is /Users/myuser/Fooocus/entry_with_update.py. The command is pointing to the file as if it's in my user folder, but it's in the Fooocus folder which within my user folder. 

I'm assuming I just don't know what I'm doing, but I can't find anything that point to me as the issue. 

Running macOS 14.2 if relevant

Please help, and thank you!

**Comment by eddyizm** [comment]
Can you show your terminal window? What directory are you in? 
run `pwd` to see where are you at. 
then `ls` 
and then the command you are running. Sounds like you are in the wrong directory.

**Comment by dirtyj375** [comment]
Here's what I see:

(base) myuser@My-M1-MacBook-Pro ~ % pwd
/Users/myuser
(base) myuser@my-M1-MacBook-Pro ~ % ls
Applications				Movies
CXPBottles				Music
Desktop					Pictures
Documents				Public
Downloads				checktestmo2
Fooocus					miniconda3
Library					tmp
Miniconda3-latest-MacOSX-arm64.sh	?Library
(base) myuser@my-M1-MacBook-Pro ~ %

**Comment by eddyizm** [comment]
so it looks like you are in your home directory but haven't changed into the `Fooocus` directory. 
Step 4 in the guide -> `cd Fooocus`
Then you got to set up the environment as stated in the directions. Please detail what you did, how far you got and the error messages otherwise we won't be able to help you. Showing what you struggle with can help us update the guide. 

I set up Fooocus on a M1 macbook today but didn't use conda, just straight python with an activated environment and install the requirements in there. Not sure if that is easier than the conda route but I always see people struggle with conda.

**Comment by dirtyj375** [comment]
Okay, the first time I followed all steps and it worked just fine without issue. It was only after I had terminated the process (closed Terminal) and had wanted to launch Fooocus the next day that I ran into the issue. I had assumed thereafter that I would only need step 7 since I'm a novice at this and didn't realize that at a minimum I needed to change my directory back to Fooocus.

After reading your response I open Terminal, typed 'cd fooocus' to change the working directory, then used 'python entry_with_update.py' to launch Fooocus, which launched the site in my browser as it did before, however when typing a prompt to test it now gets stuck on "waiting for task to start" and doesn't seem to move forward. 

Attached is what I see in Terminal:
[Terminal Saved Output.txt](https://github.com/lllyasviel/Fooocus/files/13728551/Terminal.Saved.Output.txt)


To be clear, each and every time that I want to launch Fooocus, are those the only two steps that I need - step 3 and step 7, or do I have to run all of the steps every time?

**Comment by eddyizm** [comment]
You are calling the python command and passing the file name, so yes if that helps you, or make yourself a shortcut that will let you call it from anywhere in your terminal. 
I also noticed you got an error with the incorrect numpy version. That may be causing your issue and will need to be addressed.

**Comment by mashb1t** [comment]
@dirtyj375 You're using Python 3.11 while Python 3.10 has been tested positively (at least on Windows), this might be a factor.
As @eddyizm already mentioend please also check your numpy version and make sure it's one of the supported ones (see in your terminal output)

**Comment by mashb1t** [comment]
closing as stale, feel free to reopen when providing new information
