### ISSUE TITLE
How to get a 'public link' for WebUi

### ISSUE THREAD

**Issue by Zetto12** [lllyasviel/Fooocus#1509]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
When starting Fooocus using the run.bat it makes the WebUI available on http://127.0.0.1:7865 which works great when you are working on the PC that runs Fooocus however I would like to expose the server to the whole network so every machine on the network can access via http://IPofPCthatrunsFooocus:7865.

In the initial log it says 'To create a public link, set `share=True` in `launch()`.'

Where do I find launch()?

Thank you

**Comment by vicento** [comment]
also looking for this info

**Comment by vanguard-bit** [comment]
It depends what you want
1) if you want a gradio link with a ssl certificate do the above guy suggested
2) if you want only access it with your personal network do this
    `python entry_with_update.py --[your network ip address]`

**Comment by ItsNoted** [comment]
Just add --listen to the bat file you're running.

Here's mine:
```
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --listen
```

**Comment by tearno** [comment]
**You can also get a public link by the following steps:**

**1)** Open webui file with any text editor (e.g `nano webui.py`)
**2)** Find a line at the bottom `shared.gradio_root.launch(`
**3)** Look for `share=` and replace the text an equal sign with `True`

Now, after starting Fooocus, you will get a public link in the following message:

**_Running on public URL:{your public link}_**

Hope this helps🙂

**Comment by mashb1t** [comment]
> **1)** Open webui file with any text editor (e.g `nano webui.py`) **2)** Find a line at the bottom `shared.gradio_root.launch(` **3)** Look for `share=` and replace the text after an equal sign with `True`

this does exactly the same as https://github.com/lllyasviel/Fooocus/issues/1509#issuecomment-1863372725 but with more steps and having to deal with code changes ^^

**Comment by tearno** [comment]
> > **3)** Look for `share=` and replace the text after an equal sign with `True`
> 
> this does exactly the same as [#1509 (comment)](https://github.com/lllyasviel/Fooocus/issues/1509#issuecomment-1863372725) but with more steps and having to deal with code changes ^^

These are **both correct** ways of solving the issue, that's why I used "also" In my message🙂 
I hope you remember that there're various people watching this repo. Thus, I find it helpful to provide multiple solutions😉

**Comment by Zetto12** [comment]
Thank you everyone, I only now got to try it and adding --listen to run batch file does exactly what I wanted.

**Comment by AgentHitmanFaris** [comment]
open webui.py in the Fooocus folder 
replace
```shared.gradio_root.launch(
    inbrowser=args_manager.args.in_browser,
    server_name=args_manager.args.listen,
    server_port=args_manager.args.port,
    share=args_manager.args.share,
    auth=check_auth if (args_manager.args.share or args_manager.args.listen) and auth_enabled else None,
    blocked_paths=[constants.AUTH_FILENAME]
```
to 

```shared.gradio_root.launch(
    inbrowser=args_manager.args.in_browser,
    server_name=args_manager.args.listen,
    server_port=args_manager.args.port,
    share=True,
    auth=check_auth if (args_manager.args.share or args_manager.args.listen) and auth_enabled else None,
    blocked_paths=[constants.AUTH_FILENAME]

**Comment by mashb1t** [comment]
@AgentHitmanFaris please use --share instead of modifying the code
