### ISSUE TITLE
Inpainting Autodetect Feature like ClipSeg

### ISSUE THREAD

**Issue by bsormagec** [lllyasviel/Fooocus#1516]
**Is your feature request related to a problem? Please describe.**
I mostly use Fooocus from its API, but for the masking feature, I have to manually perform certain tasks. It's difficult to achieve the desired outcome just by using the API, especially if the image was created during the last prompt.

**Describe the idea you'd like**
When I am working on ComfyUI, I handle a certain task using SAM or ClipSEG. I am wondering if there is a way to select an option from a dropdown menu or input a command to recognize an image and use the selected area as a mask for inpainting. Is this possible? It would be great if it is possible.

**Comment by mashb1t** [comment]
Fooocus doesn't support inapint masks (yet), but https://github.com/fenneishi/Fooocus-ControlNet-SDXL does. Please check it out.

**Comment by bsormagec** [comment]
> Fooocus doesn't support inapint masks (yet), but https://github.com/fenneishi/Fooocus-ControlNet-SDXL does. Please check it out.

Thanks man

**Comment by bsormagec** [comment]
> Fooocus doesn't support inpaint masks (yet), but https://github.com/fenneishi/Fooocus-ControlNet-SDXL does. Please check it out.

When i check that repository i am not sure it is stable and has faceswap feature too. The main reason i am using fooocus is faceswap its really good on that. 👍🏻
