### ISSUE TITLE
Drag-and-drop does not work for Input Image

### ISSUE THREAD

**Issue by sunghin** [lllyasviel/Fooocus#1520]
[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

Drag-and-drop (Drag above image to here) does not work for Input Image in Chrome Version 120.0.6099.109

**Comment by mashb1t** [comment]
> This also happens when accessing Fooocus remotely from another client or via Docker, which is to be expected, as the temp file paths used in the Browser can't be resolved that way.
Are you using Fooocus locally in the browser on the same machine or remotely?

https://github.com/lllyasviel/Fooocus/issues/1425#issuecomment-1858758760

**Comment by sunghin** [comment]
Thanks for pointing that out - I am using Fooocus remotely. Is there any way to fix temp file paths?

**Comment by mashb1t** [comment]
No, you have to download the images in order to be able to drop them into image fields again.
