### ISSUE TITLE
Problem launching Fooocus on M1 Mac 

### ISSUE THREAD

**Issue by kle-ron** [lllyasviel/Fooocus#1523]
I discovered and used Fooocus for about a week on my M1 Mac without any issues but I can't launch it as of this morning. I get this error on my Terminal, and have no idea what to do. Any help is much appreciated.

NotADirectoryError: [Errno 20] Not a directory: '/Users/eresen/miniconda3/lib/python3.11/site-packages/jsonschema_specifications/schemas/.DS_Store'

**Comment by rottitime** [comment]
I think you should uninstall anaconda and reinstall it using the guide here: https://developer.apple.com/metal/pytorch/

**Comment by kle-ron** [comment]
That did the trick.. Thanks a lot!
