### ISSUE TITLE
Error while trying to perform "Inpaint/Outpaint -> Improve detail"

### ISSUE THREAD

**Issue by s4ff0x** [lllyasviel/Fooocus#1524]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
If we try to run "Inpaint/Outpaint -> Improve detail" error occurs (But if firstly try to run "Inpaint/Outpaint -> Inpaint/Outpaint" model download correctly and everything works)
<img width="1037" alt="image" src="https://github.com/lllyasviel/Fooocus/assets/46251157/717760d9-08f5-434f-b4a7-c7c4e099a20a">

**Full Console Log**

[Fooocus] Image processing ...
Upscaling image with shape (425, 425, 3) ...
Traceback (most recent call last):
  File "/workspace/Fooocus/modules/patch.py", line 459, in loader
    result = original_loader(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/Fooocus/models/upscale_models/fooocus_upscaler_s409985e5.bin'

**Comment by willywwang** [comment]
assuming you're using collab need to add a few lines.

```!pip install pygit2==1.12.2
%cd /content
!git clone https://github.com/lllyasviel/Fooocus.git
%cd /content/Fooocus/models/upscale_models/
!wget -O fooocus_upscaler_s409985e5.bin https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_upscaler_s409985e5.bin?download=true
%cd /content/Fooocus
!python entry_with_update.py --share```

**Comment by mashb1t** [comment]
se solution in https://github.com/lllyasviel/Fooocus/issues/1149#issuecomment-1845145703
