### ISSUE TITLE
Add copy to clipboard in plaintext for image details

### ISSUE THREAD

**Issue by ItsNoted** [lllyasviel/Fooocus#1527]
Add copy to clipboard in plaintext for image details

A button we can click to copy to clipboard all of the image details shown in the log output file. If not on the log page then on the app itself.

The quick copying of these settings enables us to share our work methods with others in the community more smoothly, thereby assisting them in a more efficient and effective way.

![chrome_ybBu4Zoryf](https://github.com/lllyasviel/Fooocus/assets/57927413/a1ad7fa5-5a99-43e5-8420-e2c4aeb055de)

![chrome_6zslF9Z3UD](https://github.com/lllyasviel/Fooocus/assets/57927413/ded36d98-377a-4130-b20f-01defbee1e6b)

When I copy the text manually from the log file it looks like a garbled mess. See example below.

```
Prompt | Cute troll with fluffy long spiked hair wearing a ugly Christmas sweater. snow falling down and troll village in the background. full body
-- | --
Negative Prompt |  
Fooocus V2 Expansion | Cute troll with fluffy long spiked hair wearing a ugly Christmas sweater. snow falling down and troll village in the background. full body, intricate, elegant, highly detailed, sharp focus, illuminated, sunny, magical, scenic, artistic, true colors, deep aesthetic, very inspirational, cute, cozy, inspired, original, fine detail, professional, winning, enhanced, polished
Styles | ['SAI Photographic', 'Fooocus V2', 'Artstyle Hyperrealism', 'MRE Artistic Vision']
Performance | Quality
Resolution | (1024, 1024)
Sharpness | 3
Guidance Scale | 1.7
ADM Guidance | (1.5, 0.8, 0.3)
Base Model | dreamshaperXL_turboDpmppSDEKarras.safetensors
Refiner Model | None
Refiner Switch | 0.5
Sampler | dpmpp_sde
Scheduler | karras
Seed | 5044578018584347060
Version | v2.1.853
```

**Comment by Brian-Flannery** [comment]
How would you like the text to be formatted?  IMO the log output looks pretty easy to understand.

**Comment by flanneryhbh** [comment]
How would you like the text to be formatted? IMO the log output looks pretty easy to understand.

**Comment by ItsNoted** [comment]
> How would you like the text to be formatted? IMO the log output looks pretty easy to understand.

Yes, the log looks great, not denying that. However, when I copy and paste it, it looks messy and hard to understand.

More like it was in the previous version

```
Prompt: candid photo of a 7 year old red head precious moment looking girl smiling wearing a pink cute, furry animal hoodie with ears, a fluffy hoodie sweater

Negative Prompt: blue eyes

Fooocus V2 Expansion:

Styles: ['Fooocus Masterpiece'], Performance: Quality

Resolution: (1024, 1024), Sharpness: 3

Guidance Scale: 1, ADM Guidance: (1.5, 0.8, 0.3)

Base Model: turbovisionxlSuperFastXLBasedOnNew_tvxlV32Bakedvae.safetensors, Refiner Model: None

Refiner Switch: 0.5, Sampler: dpmpp_sde

Scheduler: karras, Seed: 8120950360366292174
```

**Comment by lllyasviel** [comment]
I can reproduce the problem. will add to next version

**Comment by lllyasviel** [comment]
added in 2.1.854

**Comment by ItsNoted** [comment]
> added in 2.1.854

Thank you! Where can I find this version?

**Comment by mashb1t** [comment]
@ItsNoted it's not (yet) tagged but you can find the commits here: https://github.com/lllyasviel/Fooocus/commit/f7bb578a1409b1f96aff534ff5ed2bd10502296f

To use this specific version, check out the repository and change your git HEAD to this commit.

**Comment by ItsNoted** [comment]
> @ItsNoted it's not (yet) tagged but you can find the commits here: [f7bb578](https://github.com/lllyasviel/Fooocus/commit/f7bb578a1409b1f96aff534ff5ed2bd10502296f)
> 
> To use this specific version, check out the repository and change your git HEAD to this commit.

Thank you! I'll close this since it is complete.
