### ISSUE TITLE
Enhancement Request - Gradio Text to Image Generation

### ISSUE THREAD

**Issue by Damarcreative** [lllyasviel/Fooocus#1530]
**Is your feature request related to a problem? Please describe.**

**Describe the idea you'd like**

Currently, the image generation process in the user interface (UI) appears to fetch images sequentially, one at a time, following a strict step-by-step order from the API. While this ensures a linear progression, it can result in UI delays, especially when the generation process is complete, and the UI is still fetching images for intermediate steps.

I propose the implementation of a feature that allows for a more efficient and dynamic image loading process in the UI. Specifically, I suggest the ability to skip fetching intermediate steps in the UI once the generation process is complete. This way, the UI can directly display the final or relevant steps without waiting for the sequential loading of all intermediate images.

To achieve this, the following modifications could be considered:

1. Asynchronous Image Loading: Implement asynchronous image loading in the UI to allow for parallel fetching of images rather than a strict sequential order.
2. Console Log Synchronization: Ensure that the console log accurately reflects the order of completed steps, aiding in providing real-time feedback to the user.
3. Completion Notification: Consider adding a completion notification in the UI or console to indicate when the entire generation process is finished.

I believe that implementing these enhancements will significantly improve the user experience by reducing unnecessary delays in the UI and providing more immediate feedback on the progress of the image generation process.

**Comment by guardianofthesea** [comment]
Your problem will mostly be an issue when using Fooocus over a public link, if you're running it locally there will be no delays.

There is a work around to your problem, you can select "Disable Preview" from "Developer Debug Mode", and now only the final images from the generation process will be displayed when the process is complete.
(Advanced->Advanced->Developer Debug Mode->Disable Preview)

![image](https://github.com/lllyasviel/Fooocus/assets/97708395/e8eca76e-f97e-4d37-a84e-ae51e85f7cb1)
