### ISSUE TITLE
inpaint changing background does not modify the picture

### ISSUE THREAD

**Issue by Kralg** [lllyasviel/Fooocus#1535]
Hello,

I am trying to change background of the picture. I read about inpaint and Modify content dropdown option.
I type in the bottom prompt to change the background to white room, but I get images with micro changes at the top, you can see that in one picture I got somewhat a new object..: 
![image](https://github.com/lllyasviel/Fooocus/assets/26962388/6c24fd68-7c31-45cc-938d-b2f2ec118f2d)

Can you please write how should the change background work and what prompt to write in this case?

**Comment by simartem** [comment]
![image](https://github.com/lllyasviel/Fooocus/assets/148996864/2fb10a1c-f061-4761-a6ff-b82c9263b49a)

follow instructions from the screenshot. change the prompt with the desired result

**Comment by Kralg** [comment]
Hi,

Thank you for the answer. 
I tried to change it to Inpaint or Outpaint and wrote "white wall" and I am getting some kind of brown wooden plate instead, what am I doing wrong? 
![image](https://github.com/lllyasviel/Fooocus/assets/26962388/d3d7f29e-9147-47fb-8d59-cd3c96f51613)

**Comment by Kralg** [comment]
I also selected outpaint directions Left, Right, Top, Bottom (Prompt: white wall ) and result still something with wood:
![image](https://github.com/lllyasviel/Fooocus/assets/26962388/b8f80ac9-b0c5-4fe4-85c6-c959f08c3940)

**Comment by lllyasviel** [comment]
See also "Advanced: Add New Objects / Change Background"
from
https://github.com/lllyasviel/Fooocus/discussions/414

**Comment by Kralg** [comment]
Hi, thanks, but do you see anything wrong I am doing? 
I also checked this description before, but dont understand what is the problem here. 
Only thing that I see is this: This "modification" mode will completely ignore original content and is good at handling images with solid color backgrounds like. Does this mean that it completely cannot handle change background when it is not white?

As a work around: can I do something opposite mark the central object and write to place it on some another picture?

**Comment by lllyasviel** [comment]
hi

please follow the guide "Advanced: Add New Objects / Change Background"
from
https://github.com/lllyasviel/Fooocus/discussions/414

to achieve your goal.

thanks!

**Comment by Kralg** [comment]
Thanks I managed to change it however I can see that it still was kind of trying to do some circular patterns around, however one picture I managed to get on white kind of table. Thanks.
