### ISSUE TITLE
**When downloading in cmd stuck at 100%**

### ISSUE THREAD

**Issue by Mohamed1Taha** [lllyasviel/Fooocus#1536]
**When downloading in cmd stuck on 100%**
![fooocus](https://github.com/lllyasviel/Fooocus/assets/89176289/334a033e-afe3-4bdf-86b1-f68aa15f3b19)
i left it for a day and still nothing and tried it twice same problem

**Comment by siriume** [comment]
Manually download [this](https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_version6Rundiffusion.safetensors) to `Fooocus/models/checkpoints/`
