### ISSUE TITLE
What is the "stop at" parameter for?

### ISSUE THREAD

**Issue by actopozipc** [lllyasviel/Fooocus#1538]
What is the "stop at" parameter for at image prompts?  
In general, is there a guide for what the parameters exactly mean?

**Comment by xx88xx** [comment]
I'm curious what this means also

**Comment by flanneryhbh** [comment]
If I'm understanding correctly, it controls at what percent of completion the control net stop taking the input image into consideration.  Check out the "Ending ControlNet step" part from here (you can't control the start in fooocus):
https://stable-diffusion-art.com/controlnet/

**Comment by jepjoo** [comment]
Correct. If stop at is 0.5, the image prompt will only be in effect for the first half on generation.
