### ISSUE TITLE
Ability to save and load a workflows / load workflow from image

### ISSUE THREAD

**Issue by xx88xx** [lllyasviel/Fooocus#1539]
In comfyUI I can save and load my own workflows so I can resume work or go back to and old session with lots of unique parameters (that take lots of time to experiment and hone in).

Or even better (also in ComfyUI) I can drag a image I generated in ComfyUI and it repopulates the UI with my old session used for the generation of that photo.

I'd be good to have the same functionality so you can go back and experiment with old sessions and old generations. Currently it's frustrating to start from scratch each session and rely on screenshots of the interface to go back/remember my previously used sessions.

**Comment by jepjoo** [comment]
This sort of functionality was just added 10h ago.

Your log files will now have a button to copy settings of a previously generated image and you can paste that into prompt and copy the settings over. Very useful.

https://github.com/lllyasviel/Fooocus/commit/f7bb578a1409b1f96aff534ff5ed2bd10502296f
