### ISSUE TITLE
Paste images to Input Image from Windows clipboard.

### ISSUE THREAD

**Issue by E2GO** [lllyasviel/Fooocus#1544]
It's simple as that - could be nice to have a feature to **paste images to** the image field of **InputImage**.

It's a usual workflow to make some adjustments\iterations with Photoshop, for example, and when I need to get this edited image in **InputImage** I should save it as file before and then drop\browse for it for Fooocus. In A1111 I mostly doing it with simple ctrl-v right from Photoshop file so no additional images done. Just hover over window where I need this image and press ctrl-v. 

Thanks in advance!

**Comment by mashb1t** [comment]
see https://github.com/lllyasviel/Fooocus/issues/1012

**Comment by E2GO** [comment]
Thanks for redirection! Looks like a working solution.
