### ISSUE TITLE
[Potential, need investigation] First image in batch is always better

### ISSUE THREAD

**Issue by Volnovik** [lllyasviel/Fooocus#1545]
Purely anecdotal evidence.

Feels like most of the time first image is way better then any other in batch. FreeU is enabled. Feels like FreeU is applied only to the first generation in batch. 

I've got no idea how to check it properly. Using Fooocus on Windows 10.

**Comment by mashb1t** [comment]
Just checked, can confirm that FreeU is applied (and overshooting) correctly on all images of a batch (set to extremes).
![image](https://github.com/lllyasviel/Fooocus/assets/9307310/9136600d-2ded-4ecd-8455-e7aa0dcf6775)
