### ISSUE TITLE
Crash after 15 seconds of running

### ISSUE THREAD

**Issue by IRaizyrI** [lllyasviel/Fooocus#1546]
**Describe the problem**
Fooocus crashes without any error messages after running for 10-15 seconds. Started using bat file. Nothing changed in configs. It might help that I have 2 gpu's plugged in, 1050ti and 970? Also I would love to use memory of both if it's possible.

**Full Console Log**
C:\Users\Raizyr\Desktop\NN\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.854
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 4096 MB, total RAM 32718 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --always-normal-vram
Set vram state to: LOW_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce GTX 970 : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE

C:\Users\Raizyr\Desktop\NN\Fooocus_win64_2-1-831>pause
Press any key to continue . . .

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
