### ISSUE TITLE
get all  images

### ISSUE THREAD

**Issue by JONEmoad** [lllyasviel/Fooocus#1549]
Can I view/get all the images that have been generated from the web  UI or API, as I want to display the pictures on my phone that I have worked on previously

**Comment by JONEmoad** [comment]
I know that the images are located in the output folder, but I want to display all the images from a mobile phone, for example. Is there a way to display all the images that have been generated from the WEB UI or API? This would be useful if I want to connect to my server from anywhere when I don't have my laptop with me

**Comment by eddyizm** [comment]
I pull the images I like to my lightroom library and export the results there to a photoprism instance that I have with a public URL. I would bet a small script to move the images to some storage location would be the easiest way, eg move them to a dropbox/google drive/apple folder so you can view/share them on your phone.

![image](https://github.com/lllyasviel/Fooocus/assets/12236892/2b2d0f88-b10f-4f0d-b62c-76d5e9268a7e)

**Comment by ItsNoted** [comment]
> I pull the images I like to my lightroom library and export the results there to a photoprism instance that I have with a public URL. I would bet a small script to move the images to some storage location would be the easiest way, eg move them to a dropbox/google drive/apple folder so you can view/share them on your phone.
> 
> ![image](https://private-user-images.githubusercontent.com/12236892/292577484-2b2d0f88-b10f-4f0d-b62c-76d5e9268a7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNzkxNDksIm5iZiI6MTcwMzI3ODg0OSwicGF0aCI6Ii8xMjIzNjg5Mi8yOTI1Nzc0ODQtMmIyZDBmODgtYjEwZi00ZjBkLWI2MmMtNzZkNWU5MjY4YTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIxMDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNjM2OTYwYTFhMGU1MTRhNzk4ZmQyYzE4Mjc2ZTZjYWI2M2QxMzNhNjJhMjNkNDg5NTg5M2I4NWFiODhmNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j8UOspwwYjVCBM4whmDrjnuSBzyBCiOstcBXZsEwCCY)

I was going to suggest this. Use maybe google drive to automatically pull image from any directory on your PC to their server. I wish there was a image gallery made specifically for AI images where we can add prompts and settings that are easily copyable.

**Comment by mashb1t** [comment]
Do you mean a publicly or privately hosted gallery?
For public sharing i'd recommend https://civitai.com/images and https://www.artstation.com/
For private sharing i personally use https://github.com/LycheeOrg/Lychee ([my gallery](https://gallery.mashb1t.de/gallery/q0-72LItF8vSI6dDLwyC5V7N)), which also has support for meta data (but i don't use this feature). This is not specifically for AI art but in general for posting various kinds of photos.
Hope this helps!

**Comment by ItsNoted** [comment]
> Do you mean a publicly or privately hosted gallery? For public sharing i'd recommend https://civitai.com/images and https://www.artstation.com/ For private sharing i personally use https://github.com/LycheeOrg/Lychee ([my gallery](https://gallery.mashb1t.de/gallery/q0-72LItF8vSI6dDLwyC5V7N)), which also has support for meta data (but i don't use this feature). This is not specifically for AI art but in general for posting various kinds of photos. Hope this helps!

I mean something I can self host like Lychee. It's nice but not exactly great for adding prompts and other settings used in the workflow. I've scoured all the self hosted image galleries I know of and all of them are great but lack the functionality of this use case.

**Comment by mashb1t** [comment]
I sadly don't think we can find a solution to your specific needs here => Closing this issue.
Maybe you can update us if you find a perfect match!

**Comment by mashb1t** [comment]
@ItsNoted a near perfect match might be wandb, but it's a cloud service 🌧️ 
see https://github.com/lllyasviel/Fooocus/pull/373 & https://github.com/wandb/wandb
