### ISSUE TITLE
App freezes on 4GB card but not on 8GB

### ISSUE THREAD

**Issue by LordMilutin** [lllyasviel/Fooocus#1552]
Hello.
I have successfully run this software on machine A (32GB RAM + 8GB RTX). Generations work flawlessly.

However, on machine B (16GB RAM + 4GB GTX), I run the software and enter the prompt, but it always gets stuck with the message "sending to GPU". 

4GB should work as well. 

Did anyone run it successfully on such a card, and if so, how?

Are there any settings that need to be set?

Thanks!

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus#minimal-requirement

**Comment by LordMilutin** [comment]
Thanks!
