### ISSUE TITLE
Disable automatic download of default models

### ISSUE THREAD

**Issue by erenv32** [lllyasviel/Fooocus#1563]
How can I disable automatic download of default models? Because I updated juggernautXL model to v7 but when I start run.bat its download v6 automatically. I have limited storage so is there any way to disable that?

**Comment by mashb1t** [comment]
@erenv32 adjusting your default preset https://github.com/lllyasviel/Fooocus/blob/main/presets/default.json#L2 to juggernaut v7 will prevent v6 from being downloaded.
Hope this helps!

**Comment by erenv32** [comment]
I edited the default preset file but it still downloads when I run run.bat.

**Comment by mashb1t** [comment]
the model can also be set in your config.txt file, key default_model. You might also have to change it there to ensure v6 isn't downoaded anymore.
Reference: https://github.com/lllyasviel/Fooocus/blob/main/modules/config.py#L156

**Comment by erenv32** [comment]
> the model can also be set in your config.txt file, key default_model. You might also have to change it there to ensure v6 isn't downoaded anymore. Reference: https://github.com/lllyasviel/Fooocus/blob/main/modules/config.py#L156

No, it didn't work.

**Comment by mashb1t** [comment]
Please also check key checkpoint_downloads in your config.txt.
If that doesn't eork: are you still using the deprecated config format?

In general, there are only a few occurrences in the code:
https://github.com/search?q=repo%3Alllyasviel%2FFooocus+juggernautXL_version6Rundiffusion.safetensors&type=code

**Comment by erenv32** [comment]
> Please also check key checkpoint_downloads in your config.txt. If that doesn't work: are you still using the deprecated config format?
> 
> In general, there are only a few occurrences in the code: https://github.com/search?q=repo%3Alllyasviel%2FFooocus+juggernautXL_version6Rundiffusion.safetensors&type=code

It didn't work but I changed the name of the v7 model to v6 and that solved my problem. Now I can use the v7 model, only the name appears as v6. Thank you for your help.

**Comment by simartem** [comment]
There is no way to prevent default model download. renaming is the only way and you pointed it out on your own.

**Comment by lllyasviel** [comment]
see also https://github.com/lllyasviel/Fooocus#customization for disable model downloading

**Comment by green-anger** [comment]
The option for skipping downloading is not in the docs, at least I couldn't find it at the moment of writing this. Looking at `launch.py` in `def download_models` there's block:
```py
    if args.disable_preset_download:
        print('Skipped model download.')
        return default_model, checkpoint_downloads
```
So, I presume --disable_preset_download is the option.

**Comment by JakeSSRN** [comment]
> The option for skipping downloading is not in the docs, at least I couldn't find it at the moment of writing this. Looking at `launch.py` in `def download_models` there's block:
> 
> ```python
>     if args.disable_preset_download:
>         print('Skipped model download.')
>         return default_model, checkpoint_downloads
> ```
> 
> So, I presume --disable_preset_download is the option.

Passing this argument creates an unrecognized argument error, unfortunately. Changing the config.txt model download link to a nonexistent URL also causes an error.

**Comment by Melyyn** [comment]
> ```python
> disable_preset_download
> ```

could you please spcify where exactly to use  `--disable-preset-download`, in a bat file somwhere?

**Comment by Melyyn** [comment]
> > The option for skipping downloading is not in the docs, at least I couldn't find it at the moment of writing this. Looking at `launch.py` in `def download_models` there's block:
> > ```python
> >     if args.disable_preset_download:
> >         print('Skipped model download.')
> >         return default_model, checkpoint_downloads
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So, I presume --disable_preset_download is the option.
> 
> The argument to pass is --disable-preset-download. This works.

could you please specify where exactly to use  `--disable-preset-download`, in a bat file somewhere?

**Comment by AkSinghSidhu** [comment]
> > > The option for skipping downloading is not in the docs, at least I couldn't find it at the moment of writing this. Looking at `launch.py` in `def download_models` there's block:
> > > ```python
> > >     if args.disable_preset_download:
> > >         print('Skipped model download.')
> > >         return default_model, checkpoint_downloads
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So, I presume --disable_preset_download is the option.
> > 
> > 
> > The argument to pass is --disable-preset-download. This works.
> 
> could you please specify where exactly to use `--disable-preset-download`, in a bat file somewhere?

Open the run.bat in notepad, in first line after the Fooocus\entry_with_update.py add a space and paste --disable-preset-download. Done
