### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by AdamKnappZ** [lllyasviel/Fooocus#1568]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
I don't know if this is possible, but can i use SD 1.5 models instead of SDXL model or it only works for SDXL models?

**Comment by mashb1t** [comment]
Fooocus is an interface designed to work only with SDXL models, but supports SDXL + 1.5 refiners.
What you can do as a workaround is to use a SDXL base model and switch to a SD 1.5 refiner as early as possible (0.1).
Give it a try :)
