### ISSUE TITLE
faceSwap error in google colab 

### ISSUE THREAD

**Issue by oscody** [lllyasviel/Fooocus#1574]
<img width="1017" alt="Screenshot 2023-12-20 at 7 11 07 AM" src="https://github.com/lllyasviel/Fooocus/assets/24750008/a8f19d55-ac7d-4c74-b6ed-a20fd5c3188c">

<img width="1308" alt="Screenshot 2023-12-20 at 7 10 39 AM" src="https://github.com/lllyasviel/Fooocus/assets/24750008/46721214-28b5-4117-962a-5fe07112063f">

<img width="1265" alt="Screenshot 2023-12-20 at 7 10 30 AM" src="https://github.com/lllyasviel/Fooocus/assets/24750008/de051831-553a-4844-a5e1-d66f76564ee9">

**Comment by Amit30swgoh** [comment]
have exactley the same massage one word "ERROR" no only on google colabe also on my machine .
why theres no explenation about this error how can we know whats the problem?!

**Comment by mashb1t** [comment]
please check https://github.com/lllyasviel/Fooocus/issues/1558#issuecomment-1868166226
