### ISSUE TITLE
"Error" when clicking on "Generate"

### ISSUE THREAD

**Issue by Amit30swgoh** [lllyasviel/Fooocus#1577]
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/d43b203b-e87c-416c-8be7-98a4fb1da204)

**Comment by depletedboi** [comment]
have the same

**Comment by mashb1t** [comment]
please check the console output and follow https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

**Comment by Amit30swgoh** [comment]
> have the same. i have rtx 3060 mobile (acer nitro 5)
> 
> edit: i think you need to install cuda from nvidia site, uninstall torch in python envrionment, reinstall it with cuda support

Ty friend but im useing old laptop no gpu i have built in Intel HD ready u think thats whats makes the error? And if so can i use something like google colab or something?

**Comment by mashb1t** [comment]
you can use `--always-cpu` in your entrypoint script to only use CPU, even without having to have a GPU.
Minimum system requirements are listed here:
https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement

Feel free to check them and if your laptop does not meet them you can always fall back to using a cloud instance.

**Comment by Amit30swgoh** [comment]
> you can use `--always-cpu` in your entrypoint script to only use CPU, even without having to have a GPU. Minimum system requirements are listed here: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement
> 
> Feel free to check them and if your laptop does not meet them you can always fall back to using a cloud instance.

First of all ty very much.
Sexcond, please let me know since im new in this what im doing is to enter the local ip browsee so im not sure how and where to enter the command u mentioened ty again

**Comment by mashb1t** [comment]
@Amit30swgoh please modify the arguments in your run.bat or in whatever script you execute to start Fooocus.

See https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#all-cmd-flags or find other examples how to set this in the readme file in this repository

**Comment by Abraxas08** [comment]
@mashb1t So I am starting fooocus with entry_with_update.py, is this a mistake? I can't find run.bat. So when I go to cmd and type `start entry_with_update.py --always-cpu`, it looks like its working, but after 3 seconds of running a prompt the python window closes and then the error comes up again, and if i start it in visual studio code, i don't know how to modify the arguments, can you please help me with this?

**Comment by mashb1t** [comment]
@Abraxas08 the run.bat file is the one from the official installer with exactly 2 lines of code (paraphrased below):
1. python3 entry_with_update.py <args here>
2. pause

The `pause` causes the terminal to wait for input after the occurrence of errors in Fooocus, so you're able to see them. I'd highly encourage you to create such a script to see the error outputs of Fooocus without it automatically closing the terminal.
I am not too familiar with VS Code (using JetBrains products professionally and at home), but there also is a terminal which you can use to execute your script (i assume).
Please check the output of the terminal and make sure you have set up Swap as described in the troubleshooting guide here: https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
Hope this enabled you to be able to start debugging!
