### ISSUE TITLE
Input image checkbox error

### ISSUE THREAD

**Issue by willko22** [lllyasviel/Fooocus#1582]
Hello. Happy holidays.

I'm on a windows.
This happens both in Opera and Chrome.

The issue is when I tick "input image" nothing shows up.
I looked into the browser console and each time I tick the "input image" I get this error:
![image](https://github.com/lllyasviel/Fooocus/assets/63810279/9ce74653-e78b-41d1-8714-92acb55ab0c3)
What do you think I should do to fix this?

also on the start of Fooocus I get this errors: 
![image](https://github.com/lllyasviel/Fooocus/assets/63810279/04f6aa70-ccde-4611-8528-76a22ca6bf68)

**Comment by mashb1t** [comment]
Are you using the latest version of Fooocus (2.1.85) and are you running it on your local machine or a Windows server, potentially behind a proxy or with basic auth enabled?

**Comment by willko22** [comment]
Im running it localy but now that im looking i have version 2.1.831.
Is there some autonatic update or i need to download new version and move all custome files? (Presets, models…)

**Comment by willko22** [comment]
I have downloaded newest version 2.1.851 and there is still same error

**Comment by mashb1t** [comment]
run.bat should already be calling entry_with_update.py. If this doesn't update the code, please open a terminal in your Fooocus folder and run `git pull` manually. You may also stash/reset your changes if that is not possible and you have some.

When you have the latest version, please check the terminal output and post it here for further analysis. Thanks!

**Comment by mashb1t** [comment]
Solution (workaround until fixed): see https://github.com/lllyasviel/Fooocus/issues/1379 (https://github.com/lllyasviel/Fooocus/issues/1379#issuecomment-1859847504)
