### ISSUE TITLE
Fooocus colab.research.google.com/drive .gradio.live Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by Amit30swgoh** [lllyasviel/Fooocus#1583]
My problem .gradio.live i get this error:

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

https://colab.research.google.com/drive

!pip install pygit2==1.12.2
%cd /content
!git clone https://github.com/lllyasviel/Fooocus.git
%cd /content/Fooocus
!python entry_with_update.py --share

I dont understand why and if i need driver for google colab how i download what to write and where please?

.gradio.live

**Comment by mashb1t** [comment]
please make sure to use a GPU instance (e.g. colab T4) or follow the answers of your other issue
https://github.com/lllyasviel/Fooocus/issues/1577
