### ISSUE TITLE
HOW NOT TO DOWNLOAD MODELS EVERY TIME I ENTER COLLAB??? ITS MORE THAN 20) GB!!

### ISSUE THREAD

**Issue by Amit30swgoh** [lllyasviel/Fooocus#1584]
HOW NOT TO DOWNLOAD MODELS EVERY TIME I ENTER COLLAB??? ITS MORE THAN 20) GB!!

**Comment by mashb1t** [comment]
Google Colab offers cloud instances. As soon as yiu terminate your session, the server content will also be deleted. It is inevitable that you need to download everything anew for each separate cloud instance.
Make sure you rather restart Fooocus (if it crashes), not directly terminate the Colab session.

**Comment by Amit30swgoh** [comment]
> Google Colab offers cloud instances. As soon as you terminate your session, the server content will also be deleted. It is inevitable that you need to download everything anew for each separate cloud instance. Make sure you rather restart Fooocus (if it crashes), not directly terminate the Colab session.
> 
> EDIT: Please keep a respectful tone and do not spam issues. Thank you.

sorry was frustrated i respect alot . and ty for the answer. btw when you say restart and not terminatine could you please explain me ty

**Comment by Amit30swgoh** [comment]
> Google Colab offers cloud instances. As soon as you terminate your session, the server content will also be deleted. It is inevitable that you need to download everything anew for each separate cloud instance. Make sure you rather restart Fooocus (if it crashes), not directly terminate the Colab session.
> 
> EDIT: Please keep a respectful tone and do not spam issues. Thank you.

![image](https://github.com/lllyasviel/Fooocus/assets/42430868/8247e251-3130-4451-a065-32fb5271a525)

**Comment by mashb1t** [comment]
What i was referring to is to just to rather click on the spinning stop icon on the left in Colab and then pressing play again instead of reloading the whole tab, which is then disconnecting you from the session and kills your cloud instance.

You will also notice that models are only downloaded in the first execution, as they are persisted within your session.
In the 2nd execution there will not be any model download.

(What i like to do is to separate the entry_with_update.py execution from the rest to be able to restart even faster)

1st execution:
![screencapture-colab-research-google-github-lllyasviel-Fooocus-blob-main-fooocus-colab-ipynb-2023-12-25-23_18_47](https://github.com/lllyasviel/Fooocus/assets/9307310/58bf7d9a-57cb-4cb1-80c6-e4117b851f0f)

2nd execution: 
![screencapture-colab-research-google-github-lllyasviel-Fooocus-blob-main-fooocus-colab-ipynb-2023-12-25-23_21_27](https://github.com/lllyasviel/Fooocus/assets/9307310/90d0144f-438b-4615-9847-6d6f82c6b8fc)

Hope this helps and happy AI'ing!

**Comment by Amit30swgoh** [comment]
> What i was referring to is to just to rather click on the spinning stop icon on the left in Colab and then pressing play again instead of reloading the whole tab, which is then disconnecting you from the session and kills your cloud instance.
> 
> You will also notice that models are only downloaded in the first execution, as they are persisted within your session. In the 2nd execution there will not be any model download.
> 
> (What i like to do is to separate the entry_with_update.py execution from the rest to be able to restart even faster)
> 
> 1st execution: ![screencapture-colab-research-google-github-lllyasviel-Fooocus-blob-main-fooocus-colab-ipynb-2023-12-25-23_18_47](https://private-user-images.githubusercontent.com/9307310/292781020-58bf7d9a-57cb-4cb1-80c6-e4117b851f0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NTAxMTAsIm5iZiI6MTcwMzU0OTgxMCwicGF0aCI6Ii85MzA3MzEwLzI5Mjc4MTAyMC01OGJmN2Q5YS01N2NiLTRjYjEtODBjNi1lNDExN2I4NTFmMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMDAxNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU3MDRjYzI4MDg2OGIzYmNiMDIyNWNlNDYwZjVkMDI4YTY4YTE1NzlhMjU1NzFiN2RjY2I3MDRiY2IwMzZkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SLH1v8dMxa-zemUfS_Iry9dMU9hb2bZwgKI566e1jBE)
> 
> 2nd execution: ![screencapture-colab-research-google-github-lllyasviel-Fooocus-blob-main-fooocus-colab-ipynb-2023-12-25-23_21_27](https://private-user-images.githubusercontent.com/9307310/292781040-90d0144f-438b-4615-9847-6d6f82c6b8fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NTAxMTAsIm5iZiI6MTcwMzU0OTgxMCwicGF0aCI6Ii85MzA3MzEwLzI5Mjc4MTA0MC05MGQwMTQ0Zi00MzhiLTQ2MTUtOTg0Ny02ZDZmODJjNmI4ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMDAxNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODBjNThkN2QzZjY2Mjg4MDA0MDZmMGQ3YjMwZDI5NDYwNjgwZjVlOTQ4YzQ2MTk3NTJhYmYxZjQ5MzUzNzU4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CzPvwSxeU4_Ar2M-lL5gI7zQ2a5fmRvPBLW6Cr3_TD0)
> 
> Hope this helps and happy AI'ing!

ty btw bro do you know how to fix this: 
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/3b977325-c8eb-4806-a55a-975ec072c6e2)

**Comment by mashb1t** [comment]
As stated in the error message, i'd advise you to manually delete the model using the Colab file explorer and restart Fooocus, so it can download the file again.

**Comment by ItsCrea** [comment]
Try t[his](https://youtu.be/EIWZ6u0o4dc?si=110ZtwYjaFx8DYbY)

**Comment by Amit30swgoh** [comment]
> Try t[his](https://youtu.be/EIWZ6u0o4dc?si=110ZtwYjaFx8DYbY)

Ty :) and its also for free colab user?
