### ISSUE TITLE
Refresh all files doesn't work anymore

### ISSUE THREAD

**Issue by dlebouc** [lllyasviel/Fooocus#1588]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

With the Colab, in Advanced / Models tab, the refresh all file is not working anymore (Fooocus 2.1.855).
I checked the HTML code with Inspector and no action is associated (see screenshots).
Thanks in advance.
<img width="771" alt="Capture d’écran 2023-12-25 à 21 16 21" src="https://github.com/lllyasviel/Fooocus/assets/44457612/983ae924-638f-4614-a3ba-f135ffe4133f">
<img width="422" alt="Capture d’écran 2023-12-25 à 21 16 40" src="https://github.com/lllyasviel/Fooocus/assets/44457612/3303552f-fa22-4b47-b2d6-1fdc0095e160">

**Comment by mashb1t** [comment]
The button is indeed working as intended and the correct action is called. You can find the click action here:
https://github.com/lllyasviel/Fooocus/blob/main/webui.py#L456
Are you experiencing some issues, e.g. http response code 500 or similar, when checking your browser network tab?

**Comment by dlebouc** [comment]
Hi
In fact nothing happens. When you look of what is exchanged on the network after clicking (see screen copy), the only file is called predict. When you look at its content you have only {"detail":"Method Not Allowed"}
<img width="1433" alt="Capture d’écran 2023-12-26 à 10 42 34" src="https://github.com/lllyasviel/Fooocus/assets/44457612/6aa605be-58c8-442a-979d-8d0408ba82df">

**Comment by mashb1t** [comment]
I double-checked and refresh works on my machine as well as in Colab checking out main with latest commit https://github.com/lllyasviel/Fooocus/commit/7b5bced6c2e98efa5c013624f6466ed0ba76970c (same version you're using i assume).
You can also check the latest Fooocus version in Colab here: https://colab.research.google.com/github/lllyasviel/Fooocus/blob/main/fooocus_colab.ipynb

It does not seem to be a network issue as the predict request is sent and received correctly.
Do you have any local changes? If yes, please make sure to revert them and check again.

**Comment by dlebouc** [comment]
i just retried and it works! Very strange
