### ISSUE TITLE
Did something change with mixing inpaint and image prompt?

### ISSUE THREAD

**Issue by kenchambers** [lllyasviel/Fooocus#1593]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**

When using "mixing inpaint and image prompt" for face swap (see image) I noticed about 70% through, it stops using the face swap- and starts to revert to the original image. It did not used to do this, it only recently started doing it.

Is something wrong with my settings?

<img width="441" alt="Screen Shot 2023-12-25 at 8 59 38 PM" src="https://github.com/lllyasviel/Fooocus/assets/10778319/8dec19be-944f-4c2b-bc28-5a5d6ae4955c">

<img width="465" alt="Screen Shot 2023-12-25 at 9 00 54 PM" src="https://github.com/lllyasviel/Fooocus/assets/10778319/a50361c8-59e7-43a3-84a1-a188b32a64c3">

I've tried to set stop at and weight both to one, but its the same result.

https://github.com/lllyasviel/Fooocus/assets/10778319/6082877d-699a-434c-9627-d68b3a51ad55

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

**Comment by mashb1t** [comment]
ip_stop determines the duration of the image prompt, so this should have worked.
I can also confirm that ip_stop is working for FaceSwap on my machine.
Please check again in Colab or on your machine to determine if your settings are somehow a factor.

**Comment by mashb1t** [comment]
closing as stale, feel free to reopen when providing new information

**Comment by BenjaminCharlton** [comment]
Oh yes! Exactly this. I've got the exact same issue. I followed all the advice suggested here (all together, one at a time, and in various combinations) but it didn't help so far: https://github.com/lllyasviel/Fooocus/discussions/1376

The preview images look really promisingly similar to the image prompt until around step 19-25 then all of a sudden it changes to a totally different person.

**Comment by mashb1t** [comment]
@BenjaminCharlton please check if https://github.com/lllyasviel/Fooocus/pull/2165 helps.

**Comment by BenjaminCharlton** [comment]
Fantastically fast response, thank you, @mashb1t !
What action would I need to take to try the update in the conversation you linked to?

Perhaps if, when setting up my Virtual Machine, I need to change this line to get a different branch of the code?

git clone https://github.com/lllyasviel/Fooocus.git

**Comment by mashb1t** [comment]
@BenjaminCharlton i was hinting at the vhanges of the PR, please apply them manually and check if this works better for you: https://github.com/lllyasviel/Fooocus/pull/2165/files#diff-64c538b31e5ff03a06701a56b8033cdcf31b656d50075e9d2f25f30e3ca6ed6aR307

This changes the (synthetic) refiner switch to 0.8 instead 0.5.

**Comment by BenjaminCharlton** [comment]
**Thank you,** got it! Yes 0.8 seems to work better and 0.9 even better-er-er.

For anybody struggling with this, here's the workaround:

1) Navigate to the Fooocus root folder. If you're on a Virtual Machine, launch Jupyter Lab and use the file browser there.
2) Go to the /modules folder and open up async_worker.py
3) Go to line 307 (or thereabouts. Mine was 309 but I was using another branch of the code) and look for: refiner_switch = 0.5
4) Change it to 0.8 (or even higher. I have to admit I quite liked 0.9)
5) I relaunched the Fooocus UI at this point. I don't know if that's necessary or not.
6) Retry the Faceswap combined with Image Prompt.

That stopped the face getting close to what you want and then suddenly morphing into a totally different person. However, I still find a two step process is necessary to really nail it:

1) Use _In-paint Outpaint_ Mode and _Extreme speed_ to get 4-6 heads on the body. Choose one that's roughly the right size and position with roughly the right hairstyle. Drag the output into the _Inpaint_ input.
2) Change from _Extreme Speed_ to _Quality_. Change from _Inpaint Outpaint_ mode to _Improve Detail_ mode. Re-run the generation with hopefully acceptable results second time around.

**Comment by Amit30swgoh** [comment]
> **Thank you,** got it! Yes 0.8 seems to work better and 0.9 even better-er-er.
> 
> For anybody struggling with this, here's the workaround:
> 
> 1. Navigate to the Fooocus root folder. If you're on a Virtual Machine, launch Jupyter Lab and use the file browser there.
> 2. Go to the /modules folder and open up async_worker.py
> 3. Go to line 307 (or thereabouts. Mine was 309 but I was using another branch of the code) and look for: refiner_switch = 0.5
> 4. Change it to 0.8 (or even higher. I have to admit I quite liked 0.9)
> 5. I relaunched the Fooocus UI at this point. I don't know if that's necessary or not.
> 6. Retry the Faceswap combined with Image Prompt. Better increase your Faceswap _Weight_ and _Stop-At_ to 1.
> 
> That stopped the face getting close to what you want and then suddenly morphing into a totally different person. However, I still find a two step process is necessary to really nail it:
> 
> 1. Use _In-paint Outpaint_ Mode and _Extreme speed_ to get 4-6 heads on the body. Choose one that's roughly the right size and position with roughly the right hairstyle. Drag the output into the _Inpaint_ input.
> 2. Change from _Extreme Speed_ to _Quality_. Change from _Inpaint Outpaint_ mode to _Improve Detail_ mode. Re-run the generation with hopefully acceptable results second time around.

nice ty!
