### ISSUE TITLE
1006 Connection Error only when using Input Image

### ISSUE THREAD

**Issue by abrajamcm** [lllyasviel/Fooocus#1594]
1006 Connection Error only when using Input Image

**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
When using "Input Image" feature, uploads a JPG or PNG or drag-and-drop photo, then after Generate button click. I'm getting an Error, Error: Connection Errored out. or simply the timer starts and the nothing happens. 
On the Command Prompt Window it shows the code 1006, which per the troubleshoot indicates could be System Swap. 
I have tried everything and still nothing works.
- Changed the System Swap to SSD, Automatically managed, or forced a minimum 40GB and max 60GB
- Reinstalled everything
- Downloaded all models again
- Added the inPaint model manually because it didn't download it automatically
- Turned off Antivirus, Firewall and VPN
- Tried on Chrome primarly, but also Edge

Any help is welcome, I have tried several ways and can't find a way to make it work.

Thanks in advance!

**Full Console Log**
```html
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.855
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 8191 MB, total RAM 16284 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: C:\Users\User\Documents\Software\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [C:\Users\User\Documents\Software\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors].
Loaded LoRA [C:\Users\User\Documents\Software\Fooocus_win64_2-1-831\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\Users\User\Documents\Software\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.94 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
1006
``` 

https://github.com/lllyasviel/Fooocus/assets/10326984/fb201470-cb24-4429-8252-9b16a33547cd

![Fooocus-issue-0](https://github.com/lllyasviel/Fooocus/assets/10326984/0e04f71e-2b58-4e38-940d-8c55e7ecc942)

**Comment by mashb1t** [comment]
> Finally, note that you need to restart computer to activate any changes in system swap.

Just to make sure: did you also restart your computer after doing the changes?

**Comment by abrajamcm** [comment]
> > Finally, note that you need to restart computer to activate any changes in system swap.
> 
> Just to make sure: did you also restart your computer after doing the changes?

Yes, I did restart

**Comment by abrajamcm** [comment]
UPDATE: Issue fixed by @digitpmedia

Need to add code to the file python_embeded/Lib/site-packages/gradio/networking.py

https://github.com/lllyasviel/Fooocus/issues/1231#issuecomment-1869525420
