### ISSUE TITLE
  which Base model SDXL work on Colab Gradia please?

### ISSUE THREAD

**Issue by Amit30swgoh** [lllyasviel/Fooocus#1595]
Hello,
it says SDXL only so I was trying to use Turbo sdxl as a fast base model and it did not work
also I'd like to know how can I know which Lora will work please.
![Screenshot_20231226_095501_Chrome](https://github.com/lllyasviel/Fooocus/assets/42430868/a71fde76-fd7e-447a-be94-2d7ecde8ba4b)
Thanks!

**Comment by mashb1t** [comment]
Please elaborate "did not work".
Keep in mind that you have to change a few more thngs to correctly set all arguments for SDXL Turbo, see https://github.com/lllyasviel/Fooocus/pull/1580

Fooocus is compatible with all SDXL models and LoRAs, which you can filter for in civitai.com by selecting all Base model filters prefixed with "SDXL".

**Comment by Amit30swgoh** [comment]
> Please elaborate "did not work". Keep in mind that you have to change a few more things to correctly set all arguments for SDXL Turbo, see #1580
> 
> Fooocus is compatible with all SDXL models and LoRAs, which you can filter for in civitai.com by selecting all Base model filters prefixed with "SDXL".

thanks

**Comment by Amit30swgoh** [comment]
> Please elaborate "did not work". Keep in mind that you have to change a few more things to correctly set all arguments for SDXL Turbo, see #1580
> 
> Fooocus is compatible with all SDXL models and LoRAs, which you can filter for in civitai.com by selecting all Base model filters prefixed with "SDXL".
perhaps u familiar for better alternative than colab since it kee0s shutting down especially if I use Lora it seems to be unstable

**Comment by mashb1t** [comment]
1. stability has most likely to do with server specs, always-vram will cause the VRAM to be maximally used as models/vae/text encoders/rec. do not unload. Make sure you have enough vram available before setting this option.
2. most likely yes. Other alternatives are e.g. https://rundiffusion.com/ or https://www.runpod.io/.

Btw these questions have nothing to do with the original "issue", please consider moving this kind of questions to the community tab https://github.com/lllyasviel/Fooocus/discussions and close solved issues. Thanks!
