### ISSUE TITLE
VERY SLOW model loading time up to 285 seconds?? Something happened?

### ISSUE THREAD

**Issue by LIQUIDMIND111** [lllyasviel/Fooocus#1597]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.
So i am doing image input, i know it takes MORE time to load everything when using mage prompt, but its ridiculous today and i have been doing the same process for a month now, and its today the problem....... I know i have LOW VRAM, but still it always loaded FASTER than now.... and iterations were 1.62 per second, now its more than 2

**Describe the problem**
![Screenshot 2023-12-26 051346](https://github.com/lllyasviel/Fooocus/assets/112510084/250f6f62-d02b-447e-a568-a73156d00d49)

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

**Comment by LIQUIDMIND111** [comment]
FUNNY, the next round loaded GREAT....... look:

Requested to load SDXL
Loading 1 new model
loading in lowvram mode 3098.414963722229
[Fooocus Model Management] Moving model(s) has taken 285.08 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [01:29<00:00,  2.99s/it]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.09 seconds
Image generated with private log at: C:\TEMP\FOCUS\Fooocus\outputs\2023-12-26\log.html
Generating and saving time: 387.28 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 3089.94140625
[Fooocus Model Management] Moving model(s) has taken 31.10 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:52<00:00,  1.73s/it]
Requested to load AutoencoderKL

**Comment by LIQUIDMIND111** [comment]
Do XFORMERS work in fooocus?

**Comment by LIQUIDMIND111** [comment]
seems its a LORA that delays the loading...... never mind, but let me know if this  runs on pytorch 2.1 or 2.2 and if it needs xformers activated instead of pytorch attention on a LOW VRAM computer.... 6GB

**Comment by mashb1t** [comment]
Fooocus uses torch-2.1.0+cu121.
You can check if running the app with `--disable-xformers` or any of the specific attention modes from https://github.com/lllyasviel/Fooocus/blob/main/ldm_patched/modules/args_parser.py#L89-L91 works better for you.

**Comment by LIQUIDMIND111** [comment]
> Fooocus uses torch-2.1.0+cu121, see here:
> 
> https://github.com/lllyasviel/Fooocus/blob/7b5bced6c2e98efa5c013624f6466ed0ba76970c/launch.py#L35
> 
> 
> You can check if running the app with `--disable-xformers` or any of the specific attention modes from https://github.com/lllyasviel/Fooocus/blob/main/ldm_patched/modules/args_parser.py#L89-L91 works better for you.

ah great i will take a look then, thanks

**Comment by LIQUIDMIND111** [comment]
> Fooocus uses torch-2.1.0+cu121, see here:
> 
> https://github.com/lllyasviel/Fooocus/blob/7b5bced6c2e98efa5c013624f6466ed0ba76970c/launch.py#L35
> 
> 
> You can check if running the app with `--disable-xformers` or any of the specific attention modes from https://github.com/lllyasviel/Fooocus/blob/main/ldm_patched/modules/args_parser.py#L89-L91 works better for you.

i notice some PEOPLE that are not so close to the image, but you can see their faces well, sometimes has EYES issues...... can this be fixed with a sort of FACE RESTORER in INPAINT or any other way inside foocus?

**Comment by mashb1t** [comment]
There already is an inpainting method for faces available. Please select this one instead of the general inpainting option and test if it works for you.

**Comment by LIQUIDMIND111** [comment]
> There already is an inpainting method for faces available. Please select this one instead of the general inpainting option and test if it works for you.

ok so, i go to INPAINT select the second option that says FACE and HAND ETC, and this should work? Should i add the INPAINT prompt like “FACE” or “better face” or nothing at all, besides the main prompt? or i need to add the secondary prompt on INPAINT?

**Comment by mashb1t** [comment]
just try both and use e.g. one of the presets on thr face inpaint option. Stick with whatever suits you best.

**Comment by LIQUIDMIND111** [comment]
> just try both and use e.g. one of the presets on the face inpaint option. Stick with whatever suits you best.

ok, sorry for so many questions, just making sure you need to be more detailed than in automatic1111 in which you can fix a face with face-restorer like codeformer, apart from inpainting.... so here the process can be done but different.... there are no "face restorers" like gfpgan etc on focus......

**Comment by LIQUIDMIND111** [comment]
> just try both and use e.g. one of the presets on the face inpaint option. Stick with whatever suits you best.

does --always-offload-from-vram means that after generations, it will OFFLOAD the vram, the LOAD again in next generation?:

**Comment by mashb1t** [comment]
Yes.

https://github.com/lllyasviel/Fooocus/blob/7b5bced6c2e98efa5c013624f6466ed0ba76970c/ldm_patched/modules/model_management.py#L337 and below
