### ISSUE TITLE
API support please

### ISSUE THREAD

**Issue by Charuru** [lllyasviel/Fooocus#16]

**Comment by Semonxue** [comment]
I need this too

**Comment by shirubei** [comment]
You can find "use via API" link at the left bottom of WebUI. 
But it's still has an error. #172

**Comment by ycc1519202717** [comment]
Does anyone know how to call its API?

**Comment by shirubei** [comment]
> Does anyone know how to call its API?

http://127.0.0.1:7860/   click "Use via API" at the bottom, the page has everything all you need

**Comment by JubileusDeus** [comment]
What if I want to use the API using something other than Python and Javascript ?
I currently want to run experiments using Flutter but the API do not provide a way to do it ! Or I can be missing something.

**Comment by gerardosabetta** [comment]
FWIW this repo allows you to use fooocus via API https://github.com/konieshadow/Fooocus-API you can run it on docker or on the replicate platform
