### ISSUE TITLE
Model downloader ignores symlink

### ISSUE THREAD

**Issue by tcmaps** [lllyasviel/Fooocus#161]
I ln-s linked both sdxl models from another location, however the script tries to download it again.
```
jovyan:~/workspace/Fooocus$ ls -lah models/checkpoints/
total 8.0K
drwxr-sr-x  2 jovyan jovyan 4.0K Aug 16 20:15 .
drwxr-sr-x 17 jovyan jovyan 4.0K Aug 16 20:15 ..
lrwxrwxrwx  1 jovyan jovyan   33 Aug 16 20:15 sd_xl_base_1.0_0.9vae.safetensors -> sd_xl_base_1.0_0.9vae.safetensors
lrwxrwxrwx  1 jovyan jovyan   36 Aug 16 20:20 sd_xl_refiner_1.0_0.9vae.safetensors -> sd_xl_refiner_1.0_0.9vae.safetensors
jovyan:~/workspace/Fooocus$ python launch.py --listen --port 8000
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0]
Fooocus version: 1.0.31
Inference Engine exists.
Inference Engine checkout finished.
Downloading: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0_0.9vae.safetensors" to /home/jovyan/workspace/Fooocus/models/checkpoints/sd_xl_base_1.0_0.9vae.safetensors
```

**Comment by Neverdusk** [comment]
I have a similar issue, but it might be because I renamed the models. It would definitely be nice if there was a setting or launch argument to prevent automatically downloading the base and refiner - if there isn't one already.

**Comment by mashb1t** [comment]
There is now! Please check https://github.com/lllyasviel/Fooocus/issues/1564 (https://github.com/lllyasviel/Fooocus/issues/1564#issuecomment-1868537206) and find existing presets here: https://github.com/lllyasviel/Fooocus/tree/main/presets
