### ISSUE TITLE
Add IP-Adapter-FaceID for face swapping  

### ISSUE THREAD

**Issue by nottengame** [lllyasviel/Fooocus#1611]
Hello! It would be great to add implementation of this face swapping method. 
https://huggingface.co/h94/IP-Adapter-FaceID
It uses insightface for swapping and seems to be very precise. 

Here is some demo video with comfyUI implementation of it 
https://www.youtube.com/watch?v=jSu_tKfg5rI&t=22s

btw. Thank You for Fooocus! It is the best SD UI in my opinion! 
Keep it rolling and happy holidays!

**Comment by nottengame** [comment]
I saw that this has already been discussed in [this topic](https://github.com/lllyasviel/Fooocus/issues/1522) 

So that seems that implementing this feature will be more complex than I thought. But since ReActor or Roop, uses the same insightface method for facial features extraction, and works fine within auto1111, it is still possible to implement. 
Correct me if I am wrong.

**Comment by mashb1t** [comment]
Closed (for now), we're still keeping an eye out when other SDXL solutions come out.

**Comment by IAn2018cs** [comment]
SDXL: https://huggingface.co/h94/IP-Adapter-FaceID/blob/main/ip-adapter-faceid_sdxl.bin
