### ISSUE TITLE
希望能在ipaint的同时加入imageprompt或者faceswap

### ISSUE THREAD

**Issue by MeterLong** [lllyasviel/Fooocus#1613]
现在inpaint作为一个功能单独出现，但在某些特定场景并不能很好的生成理想图片，是否能在inpaint的同时加入imageprompt或者faceswap以及canny等控制呢，多个控一起来绘制一幅图

**Comment by mashb1t** [comment]
This is currently not possible in Fooocus. Please check out https://github.com/fenneishi/Fooocus-ControlNet-SDXL, but i assume it's also not possible there.

**Comment by MeterLong** [comment]
> 目前这在 Fooocus 中是不可能的。请查看https://github.com/fenneishi/Fooocus-ControlNet-SDXL，但我认为那里也是不可能的。

能简单说一下原因吗，您提到的项目之前我也一直在使用，我fork主分支和那个项目的分支进行融合改造，我注意到Fooocus在XL平台用的自己训练的的inpaint模型，是跟这个有关系吗？在这个模型发挥作用的时候unet里面无法用其他的controlnet模型进行引导吗？另外这个项目已经很久不更新了，它的作者也不维护了好像，谢谢您

**Comment by mashb1t** [comment]
@MeterLong i actually only found out recently that there is an option to make it work. I knew that it obviously was possible in Comfy, but wasn't aware of any possibility in Fooocus. Please find the checkbox "Mixing Image Prompt and Inpaint" in Advanced > Advanced > Developer Debug Mode.
See https://github.com/lllyasviel/Fooocus/blob/main/webui.py#L390C39-L390C39

Please let me know if this works for you!

lllyasviel is taking a break from developing Fooocus as announced in https://github.com/lllyasviel/Fooocus/blob/main/update_log.md?plain=1#L1 to fo(oo)cus on other projects but will be back in "in mid or late" January. In generally, he's providing support and maintaining the code base as good as possible. Support for AMD 8GB VRAM GPUs has only been added recently, but i agree that features / PRs are starting to pile up.

This is one of the reasons why i took over issue cleanup to really be able to only concentrate on the important bugs / enhancements. Also see https://github.com/lllyasviel/Fooocus/discussions/1704
