### ISSUE TITLE
inpaint/out paint when modify content  unexpected token doctype is not a valid jason 

### ISSUE THREAD

**Issue by Amit30swgoh** [lllyasviel/Fooocus#1614]
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/8c4c78aa-e802-4ebb-8033-232e504c2c37)

**Comment by Amit30swgoh** [comment]
> ![image](https://private-user-images.githubusercontent.com/42430868/293029638-8c4c78aa-e802-4ebb-8033-232e504c2c37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2Nzk4MzMsIm5iZiI6MTcwMzY3OTUzMywicGF0aCI6Ii80MjQzMDg2OC8yOTMwMjk2MzgtOGM0Yzc4YWEtZTgwMi00ZWJiLTgwMzMtMjMyZTUwNGMyYzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEyMTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZTE0MzAwMzU5MzMyOWE1Y2NjMzg2ZGM4OWNhYTg1MzUzZjIyODk3NjQ1OWEwODBhYzkwMDRiYTI0MTU1MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3jXXSK4UGlcnQteNzTse6POkkstsB85--hkxWPYtIxg)

![image](https://github.com/lllyasviel/Fooocus/assets/42430868/35d5a42a-8833-4d90-91ba-e5e1dbb21387)
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/65140c6b-2973-4656-ac62-add0a4501544)
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/a74c6b52-fb09-4a16-87ec-7afea87e2c09)
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/faf3c9d9-b609-4fcc-b754-302565e7d709)
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/39dccd44-cf43-4db2-813d-174a4ab9b6fc)

**Comment by mashb1t** [comment]
As always, please provide the console log so we can better figure out potential issues from the output.
Please also check your browser network tab and provide the response content of the failing predict request. The reason could be an error output in the websocket connection, which then would show up there.

**Comment by Amit30swgoh** [comment]
> As always, please provide the console log so we can better figure out potential issues from the output. Please also check your browser network tab and provide the response content of the failing predict request. The reason could be an error output in the websocket connection, which then would show up there.

Sorry im nee in this what does it means console log?

**Comment by mashb1t** [comment]
please provide the Fooocus console output (terminal) and the browser response of the failing request

**Comment by Amit30swgoh** [comment]
> please provide the Fooocus console output (terminal) and the browser response of the failing request

Ohh ok will do next time  see it bte do u know if there is a good working lora for dreamshaperxl turbo?

**Comment by mashb1t** [comment]
In general, SDXL Turbo and fine-tuned models work with all SDXL LoRAs. For removing objects you're better off  using inpainting with "Modify Content (add objects, change background, etc.)".

**Comment by Amit30swgoh** [comment]
> In general, SDXL Turbo and fine-tuned models work with all SDXL LoRAs. For removing objects you're better off using inpainting with "Modify Content (add objects, change background, etc.)".

Ty closeing the post ty u so mich for all the help do u have discord?

**Comment by mashb1t** [comment]
For personal stuff yes, but not for Fooocus. https://github.com/lllyasviel/Fooocus/issues/112#issuecomment-1679220756
