### ISSUE TITLE
Ability to remove background blur

### ISSUE THREAD

**Issue by monkrus** [lllyasviel/Fooocus#1625]
**Is your feature request related to a problem? Please describe.**
At the moment, most of the images with default settings come with a blurry background.

**Describe the idea you'd like**
Add an option to adjust the focus of the background.

**Comment by mashb1t** [comment]
You can use the negative prompt to achieve this by using e.g. "narrow depth of field", "blurred background", etc.

**Comment by monkrus** [comment]
@mashb1t I apologize, but it seems like adding those keywords did not make a great difference. 
Allow me to share image created with the negative prompt with recommended keywords.

**I use Fooocus V2, Fooocus Enhance, Fooocus Sharp, and Fooocus Photograph with Speed settings.**
"Japanese girl standing under the sakura tree"
The example below uses **narrow depth of field, blurred background**

 I also played with adding keywords like **DoF, Bokeh, background blur** but with no significant result.

![Added_negative_prompt](https://github.com/lllyasviel/Fooocus/assets/12500447/2cde4add-eb50-4212-bf57-5c9506d8a6df)


Negative prompt : close up, two heads, two faces, plastic, Deformed, blurry, bad anatomy, bad eyes, crossed eyes, disfigured, poorly drawn face, mutation, mutated, ((extra limb)), ugly, poorly drawn hands, missing limb, blurry, floating limbs, disconnected limbs, malformed hands, blur, out of focus, long neck, long body, ((((mutated hands and fingers)))), (((out of frame))), blender, doll, cropped, low-res, close-up, poorly-drawn face, out of frame double, two heads, blurred, ugly, disfigured, too many fingers, deformed, repetitive, black and white, grainy, extra limbs, bad anatomyHigh pass filter, airbrush, portrait, zoomed, soft light, smooth skin, closeup, deformed, extra limbs, extra fingers, mutated hands, bad anatomy, bad proportions, blind, bad eyes, ugly eyes, dead eyes, blur, vignette, out of shot, out of focus, gaussian, closeup, monochrome, grainy, noisy, text, writing, watermark, logo, oversaturation, over saturation, over shadow,(((deformed iris))), narrow depth of field, blurred background,

**Comment by mashb1t** [comment]
@monkrus the situation in your case is tricky because both the positive and negative prompt are very long, so individual keyword strength is less taken into account. You may be able to achieve better by reducing the amount of prompt tokens or by giving the new non-blur background prompt additions a higher strength.
Example: 
(narrow depth of field, blurred background:1.5)
Please provide some feedback if this helped.

**Comment by mashb1t** [comment]
@monkrus as far as i can see the result of @poor7 is getting close to what you're trying to achieve. Based on that, you can now try to gradially increase the amount of prompts again until you're satisfied (if not already) with the result.
Does this solve your issue? If yes, feel free to close it or provide information for further assistance.

**Comment by monkrus** [comment]
The answer could not be more satisfying.  Just a quick question before I close it: is DreamShaper XL Turbo model a part of the Fooocus? If not , could it be added?

**Comment by mashb1t** [comment]
Perfect, glad to hear. 
DreamShaper XL Turbo has already been tested and when PR https://github.com/lllyasviel/Fooocus/pull/1580 is merged you can directly use it.

**Comment by Nicotiraboschi** [comment]
Wow great. Which model?

**Comment by poor7** [comment]
> Which model?

If I understood the question correctly. This was the default model juggernautXL_version6Rundiffusion.safetensors
