### ISSUE TITLE
ImportError: cannot import name 'UnidentifiedImageError' from 'PIL' (unknown location)

### ISSUE THREAD

**Issue by Crazy-CYZ** [lllyasviel/Fooocus#1626]
**Please help, suddenly an error occurs and cannot be used.**

![微信截图_20231228145928](https://github.com/lllyasviel/Fooocus/assets/89187812/6b05a8c1-4cf7-4478-8947-a56dd5ddfa6a)

**Comment by mashb1t** [comment]
Please make sure the class "UnidentifiedImageError exists and you not accidentally deleted it.
If it doesn't exist you may rename the PIL folder and do one of the two things:
1. restart Fooocus. It will try to download all dependencies again.
2. manually open a terminal, activate the venv and install Pillow again.

**Comment by Crazy-CYZ** [comment]
> Please make sure the class "UnidentifiedImageError exists and you not accidentally deleted it. If it doesn't exist you may rename the PIL folder and do one of the two things:
> 
> 1. restart Fooocus. It will try to download all dependencies again.
> 2. manually open a terminal, activate the venv and install Pillow again.

**Thank you very much. I deleted the PIL folder and reinstalled it, which successfully solved the problem.**
