### ISSUE TITLE
Bug: "Stop" button not clickable when "Generate", "Skip" and "Stop" buttons show at the same time in "Image Prompt"

### ISSUE THREAD

**Issue by Minekonst** [lllyasviel/Fooocus#1630]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
"Generate", "Skip" and "Stop" can show at time which results in the "Stop" button not being clickable because it is behind behind the "Image Prompt" element where the 4 images can be selected. Setting the z-index by hand in the dev tools of the browser is a temporary solution to be able to click the button.

It has to do with changing the images in the "Image Prompt" tab while a generation is currently running. It seems to me the "Generate" button should not show, because an generation is still running.
I was unable to find a consistent way to reproduce this bug but is has happened to me already a number of times - I will post again if I find a way to reproduce it.

**Comment by mashb1t** [comment]
@Minekonst Thank you for reporting the issue. I
assume this is also related to the PR https://github.com/lllyasviel/Fooocus/pull/1578, where the behaviour is consistently reproducible. Can you please confirm?
If this is the case we might have to consider to hide the "Generate" button while generating (default before meta data copy) instead of just disabling it.

**Comment by LIQUIDMIND111** [comment]
i have the same issue confirmed...... the ONLY workaround is click SKIP, but if you have 20 generations, you need to click SKIP 20 times to STOP..... bummer.,

**Comment by LIQUIDMIND111** [comment]
> @Minekonst Thank you for reporting the issue. I assume this is also related to the PR #1578, where the behaviour is consistently reproducible. Can you please confirm? If this is the case we might have to consider to hide the "Generate" button while generating (default before meta data copy) instead of just disabling it.

confirmed

**Comment by Minekonst** [comment]
Yes can also confirm that. I saw it already got merged - thanks for the fast work!

**Comment by mashb1t** [comment]
@Minekonst Yes but wait a minute, your issue has not yet been solved right? Only showing as disabled for in-generation meta data inserts is included in the PR. Please check again and consider repoening this issue if it isn't fixed 100%, thanks.

**Comment by Minekonst** [comment]
Ok, I check again and reopen if it is not resolved

**Comment by mashb1t** [comment]
Can confirm that the generate button now stays hidden when loading parameters while generating.
