### ISSUE TITLE
Infinite ammount of requested images to diffuse

### ISSUE THREAD

**Issue by NoPreserveR00t** [lllyasviel/Fooocus#1637]
I don't quite understand why is there limit to only 32 images, I couldn't find this setting in the source code of web GUI, so I had to develop web proxy to send automated requests. 
![image](https://github.com/lllyasviel/Fooocus/assets/139932267/92d3fd37-366f-4344-bf50-891b71a403fa)

**Comment by mashb1t** [comment]
As https://github.com/lllyasviel/Fooocus/pull/1616 has been merged today you can modify the maximum in your config to basically max integer value. Please find Gradio limitations in the PR. You can also right-click generate to generate forever.

**Comment by NoPreserveR00t** [comment]
Edited this string in webui.py
 "image_number = gr.Slider(label='Image Number', minimum=1,
_**maximum=32**_, step=1", value=modules.config.default_image_number)
Thank you.

**Comment by mashb1t** [comment]
Perfect! You can pull Fooocus any time to get the lastest adjustments, just then adjust the config instead.
