### ISSUE TITLE
How to set Fooocus up on Replit as a standalone Repl?

### ISSUE THREAD

**Issue by vanetreg** [lllyasviel/Fooocus#1650]
Since Fooocus app at Gradio link doesn't work (image generation drops error with default settings), also free Colab doesn't have sufficient resources, I decided to install Fooocus to Replit, but by default the app is available at either localhost or at a 3-day-live Gradio link.
How should I set this up to be available on Replit, where and what should I modify?
Thanks!

**Comment by eddyizm** [comment]
I don't have any answers to your Replit question unfortunately, however I've been using free colab without much issue successfully. The only difficulty is getting the output images which just takes a zip command and then manual download.

**Comment by vanetreg** [comment]
> ...however I've been using free colab without much issue successfully. 
When I use input image, app crashes on free Colab for me.

**Comment by eddyizm** [comment]
> > ...however I've been using free colab without much issue successfully.
> 
> When I use input image, app crashes on free Colab for me.

ok, I think I had this issue as well. I believe it is a known bug that has already been opened in another issue. There's a few things generally associated with the input image and dragging a resulting image back into the input image that has a similar issue. I should have put a caveat that it generally works but not every single feature. However the speed makes up for it in my case. Good luck!

**Comment by mashb1t** [comment]
@vanetreg @eddyizm this is not a bug but a limitation of RAM, mentioned in this discussion: https://github.com/lllyasviel/Fooocus/discussions/74#discussioncomment-7966878
Dragging images down from generated results to input image doesn't work on Colab as it's a remote server and zemp pazhs do not work here.
See https://github.com/lllyasviel/Fooocus/issues/1425

**Comment by eddyizm** [comment]
@mashb1t thanks that is good to know. Should still be able to manually download the image and then use it as a regular input image right?

**Comment by vanetreg** [comment]
> @vanetreg @eddyizm this is not a bug but a limitation of RAM, mentioned in this discussion: [#74 (reply in thread)](https://github.com/lllyasviel/Fooocus/discussions/74#discussioncomment-7966878) Dragging images down from generated results to input image doesn't work on Colab as it's a remote server and temp paths do not work here. See #1425

I - as the original poster - never have written the issue related to generated image dragged down to input image.
I was trying to do face swap with input image and prompt and it didn't work on free Colab.

Note: I didn't report a bug, but **asked how to set Fooocus up on Replit** ( I don't want to buy a gamer / Apple laptop ), but it's offed... :)

**Comment by mashb1t** [comment]
@vanetreg yeah, sorry for getting off-topic. I couldn't find anything for Replit, bot for replicate.com though ^^
@eddyizm last off-topic comment: no, input image is not working on Colab (Free), only with higher RAM in Colab (Paid).

**Comment by mashb1t** [comment]
@vanetreg did you find a solution? I mean, basically it's a docker setup with a container, right?
You might be able to build the container with the help of changes in https://github.com/lllyasviel/Fooocus/pull/1418

**Comment by vanetreg** [comment]
Hi @mashb1t 
no, I've set it up on payed Google Colab.
Replit doesn't provide optionally GPU as of now.
