### ISSUE TITLE
module not found error: no module named fcbh.checkpoint_pickle

### ISSUE THREAD

**Issue by LilyK21** [lllyasviel/Fooocus#1656]
Hi, 

So, I have been using fooocus for a while now. Love it, but I am an average Joe. I do not know anything about the backend of this nor would I understand it if you explained it. I barely know how to use git hub. Ok, now that that is out of the way, I am unable to use fooocus due to an error. The Gradio launcher comes up but says error and the cmd prompt seems to say that it can't find a fcbh checkpoint pickle; have no idea what this means. I will insert some screenshots. Please help me and thanks in advance.  

<img width="456" alt="image" src="https://github.com/lllyasviel/Fooocus/assets/105465689/5758aa27-6ae0-4dc8-b204-f0beebf36ee1">

![image](https://github.com/lllyasviel/Fooocus/assets/105465689/7f048506-16fb-440d-8896-47f432f2d118)

**Comment by mashb1t** [comment]
Please make sure you're using the latest version of Fooocus (2.1.856), as fcbh has been exchanged with / renamed to ldm, and provide the full terminal output.
To do so, please use entry_with_update.py as your entrypoint or go to your Fooocus folder (the one where entry_with_update.py is located) and execute zhe command `git pull` in this directory. If there are errors you may have to reset your local changey if you have any, but let's check together after you tried this.
Looking forward to your feedback and the full teminal output.

**Comment by LilyK21** [comment]
OK. Thanks for getting back to me so quickly. So, I did a git pull on the fooocus folder where the entry_with_update foldeer is located in my file explorer. It says that it ia slready up-to-date. 

<img width="1104" alt="image" src="https://github.com/lllyasviel/Fooocus/assets/105465689/5062d041-e9b4-46be-8eea-8699f6ddb3ec">


And no it doesnt seem ithat I am runnimg the latest version. It says I am running version 2.1.824.

**Comment by mashb1t** [comment]
Please make sure you're not using your fork or another origin as git repository. You can check the URL with `git remote -v`.
If this is not the official Fooocus repository URL (https://github.com/lllyasviel/Fooocus.git or git@github.com:lllyasviel/Fooocus.git) make sure to pull/merge the main branchof Fooocus into your fork or reset the URL to an official one and pull again.
If this doesn't help it could be easiest for you to set up Fooocus from scratch eith the official zip for windows again (see [here](https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#download)) and check if this solves your issues.

**Comment by LilyK21** [comment]
> Please make sure you're not using your fork or another origin as git repository. You can check the URL with `git remote -v`. If this is not the official Fooocus repository URL (https://github.com/lllyasviel/Fooocus.git or [git@github.com](mailto:git@github.com):lllyasviel/Fooocus.git) make sure to pull/merge the main branch of Fooocus into your fork or reset the URL to an official one and pull again. If this doesn't help it could be easiest for you to set up Fooocus from scratch with the official zip for windows again (see [here](https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#download)) and check if this solves your issues.

**Comment by LilyK21** [comment]
i just went ahead and reinstalled it. seems to have worked. thank you!
