### ISSUE TITLE
Problems remain

### ISSUE THREAD

**Issue by outsami-9527** [lllyasviel/Fooocus#1661]
https://github.com/lllyasviel/Fooocus/issues/1396

Whether it's speed or quality or LCM.

**Comment by mashb1t** [comment]
https://github.com/lllyasviel/Fooocus/pull/1013 has not yet been merged. Please wait for the review or copy the code of the PR to your local installation. Be aware that you thrn have to solve Merge Vonflicts on updates manually.

Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/948
