### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by mihirgarg01** [lllyasviel/Fooocus#1665]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
GUI and program wont launch in general due to numpy not being found. On windows 10 using Python 3.10.11. I tried using run.bat but got the same error.

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.
PS C:\Users\hepmihir\Desktop\code\Fooocus_win64_2-1-831\Fooocus> python entry_with_update.py
Fast-forward merge
Update succeeded.
[System ARGV] ['entry_with_update.py']
Traceback (most recent call last):
  File "C:\Users\hepmihir\Desktop\code\Fooocus_win64_2-1-831\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Users\hepmihir\Desktop\code\Fooocus_win64_2-1-831\Fooocus\launch.py", line 24, in <module>
    from modules.config import path_checkpoints, path_loras, path_vae_approx, path_fooocus_expansion, \
  File "C:\Users\hepmihir\Desktop\code\Fooocus_win64_2-1-831\Fooocus\modules\config.py", line 7, in <module>
    import modules.sdxl_styles
  File "C:\Users\hepmihir\Desktop\code\Fooocus_win64_2-1-831\Fooocus\modules\sdxl_styles.py", line 5, in <module>
    from modules.util import get_files_from_folder
  File "C:\Users\hepmihir\Desktop\code\Fooocus_win64_2-1-831\Fooocus\modules\util.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
PS C:\Users\hepmihir\Desktop\code\Fooocus_win64_2-1-831\Fooocus> 
PS C:\Users\hepmihir\Desktop\code\Fooocus_win64_2-1-831\Fooocus> python --version
Python 3.10.11

Any help is apreciated!

**Comment by mihirgarg01** [comment]
Fixed by running pip install pygit2, pip install numpy, and pip install Image (run in Powershell)

pip install image fixed a ModuleNotFound error for PIL.

**Solution**: Upon realizing running `pip3 install -r requirements_versions.txt` was a thing, it uninstalled numpy and pygit2, probably because it was the wrong version or something. 

I did get a bunch of source warnings, but since I'm not on linux I wasn't able to use source.

**Comment by mashb1t** [comment]
Glad you found a solution already.
Please be advised that the easies and most stable way to run Fooocus on Windows is by using the pre-packaged zip file including a virtual env and bundled python 3.10.
You can find it here: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windows

**Comment by mihirgarg01** [comment]
Thanks for your help! The reason I reported the issue was because I followed the windows install instructions to a dot, but I still received those errors. The only variation I had was using python locally, but it was version 3.10.11. Again the core issue was that dependencies weren't being downloaded or run by the script.
