### ISSUE TITLE
Out of Memory Issue in Colab Pro after a couple dozen generations

### ISSUE THREAD

**Issue by arlojeremy** [lllyasviel/Fooocus#167]
First of all, love this, but on the official colab I run into an outofmemory error after a certain number of generations, as if VRAM is filling up after every generation:

`
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 14.01 GiB
Requested               : 58.50 MiB
Device limit            : 14.75 GiB
Free (according to CUDA): 2.81 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
`

Any ideas?

**Comment by arlojeremy** [comment]
Sorry, having formatting issues....🤷‍♂️

**Comment by barepixels** [comment]
Sort of related I think.  With A1111 the batch size depends on how much vram you have BUT if you use "Generate Forever" vram doesn't affect.  I generated over 500 images last night using "Generate Forever" feature in a1111.  I have a 3070 8gigs

**Comment by Kaneki010** [comment]
i think the probelm is related to vram handling specifically in colab , focus seems to not free up the vram after an image generation and after a few more images , focus fills the entire available vram so it just stops

**Comment by arlojeremy** [comment]
I've been busy but I forked it and added a new command line option to force
normalram. I think it's been working good so far?

**Comment by mashb1t** [comment]
Hey, please find a solution in https://github.com/lllyasviel/Fooocus/issues/1619#issuecomment-1870704863 and try again with the latest Fooocus version.
