### ISSUE TITLE
Error on preset "Turbo"

### ISSUE THREAD

**Issue by Amit30swgoh** [lllyasviel/Fooocus#1670]
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/157d663d-0db8-48a8-8901-02e33d68c445)
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/823b69cf-46e6-49a2-a2f8-79335b616e75)

**Comment by eddyizm** [comment]
where are you getting this repo from? The code in this repo doesn't have the `turbo` preset, only some of the forks. (I added it to mine). There seems to be another issue from your screenshot so you may need to refer to the codebase/fork you are using.

**Comment by Amit30swgoh** [comment]
> where are you getting this repo from? The code in this repo doesn't have the `turbo` preset, only some of the forks. (I added it to mine). There seems to be another issue from your screenshot so you may need to refer to the codebase/fork you are using.

i clicked saved a copy in drive, then when run all again and tried to switch to turbo got the red Errror

**Comment by eddyizm** [comment]
The turbo preset doesn't exist in the main repo, so I ask where did clone the repo you are working on? Can you verify the turbo preset is in the folder?

**Comment by Amit30swgoh** [comment]
> The turbo preset doesn't exist in the main repo, so I ask where did clone the repo you are working on? Can you verify the turbo preset is in the folder?

https://github.com/mashb1t/Fooocus

**Comment by eddyizm** [comment]
That is a different repo. Probably need to check over there. 
For what it's worth, I have the turbo preset working but as I mentioned above, there's a different issue in your screenshot that is unrelated to the turbo.

**Comment by Amit30swgoh** [comment]
> That is a different repo. Probably need to check over there. For what it's worth, I have the turbo preset working but as I mentioned above, there's a different issue in your screenshot that is unrelated to the turbo.

please share with me ty!

**Comment by mashb1t** [comment]
@Amit30swgoh the issue you're describing is not related to this repository. Please open an issue in the fork https://github.com/mashb1t/Fooocus.

**Comment by mashb1t** [comment]
@Amit30swgoh as you didn't create an issue in my repository i'd like to inform you that the bug has been fixed. Please pull again, thx.
