### ISSUE TITLE
failed to get the Python codec

### ISSUE THREAD

**Issue by mihirgarg01** [lllyasviel/Fooocus#1672]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
I reported a bug yesterday but it was resolved by running `pip3 install -r requirements_versions.txt`. However this isn't a part of the official installation guide for Windows. I extracted everything from the zip, then ran run.bat and got this error. 

As mentioned before, my solution was running pip3 install. I'm still looking for a way use run.bat instead though. Thanks!

**Full Console Log**
C:\Users\hepmihir\Desktop\code\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '.\python_embeded\python.exe'
  isolated = 1
  environment = 1
  user site = 0
  import site = 1
  sys._base_executable = 'C:\\Users\\hepmihir\\Desktop\\code\\Fooocus_win64_2-1-831\\python_embeded\\python.exe'
  sys.base_prefix = 'C:\\Users\\hepmihir\\Desktop\\code\\Fooocus_win64_2-1-831\\python_embeded'
  sys.base_exec_prefix = 'C:\\Users\\hepmihir\\Desktop\\code\\Fooocus_win64_2-1-831\\python_embeded'
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\Users\\hepmihir\\Desktop\\code\\Fooocus_win64_2-1-831\\python_embeded\\python.exe'
  sys.prefix = 'C:\\Users\\hepmihir\\Desktop\\code\\Fooocus_win64_2-1-831\\python_embeded'
  sys.exec_prefix = 'C:\\Users\\hepmihir\\Desktop\\code\\Fooocus_win64_2-1-831\\python_embeded'
  sys.path = [
    'C:\\Users\\hepmihir\\Desktop\\code\\Fooocus_win64_2-1-831\\python_embeded\\../ComfyUI',
    'C:\\Users\\hepmihir\\Desktop\\code\\Fooocus_win64_2-1-831\\python_embeded\\python310.zip',
    'C:\\Users\\hepmihir\\Desktop\\code\\Fooocus_win64_2-1-831\\python_embeded',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007a18 (most recent call first):
  <no Python frame>

C:\Users\hepmihir\Desktop\code\Fooocus_win64_2-1-831>pause

**Comment by mashb1t** [comment]
Did you by chance run `pip3 install -r requirements_versions.txt` not in venv but with your system-wide installed python version, which might differ?
Please run `python --version` and if this differs from the bundled version 3.10.11 you might have to activate venv and run `pip3 install -r requirements_versions.txt` again to make sure you're using compatible package versions.

**Comment by mihirgarg01** [comment]
Yea I was running `python .\entry_with_update.py` in PowerShell. I double checked my python version and it's 3.10.11. I ran the startup command without using venv, and got that module not found error. Running with venv gave the same error.

**Comment by mihirgarg01** [comment]
Just re-tried everything. Steps to re-create bug:

1. Downloaded the zip (Fooocus_win64_2-1-831.7z)
2. Unzipped to ~/Desktop/Fooocus_win64_2-1-831 using winRAR
3. Ran run.bat
4. Received Exact same error as before (ModuleNotFoundError: No module named 'encodings')

**Comment by mashb1t** [comment]
will try tomorrow, thank you for the feedback!

**Comment by mihirgarg01** [comment]
Should probably note I'm using a 1660 ti with 6gb of VRAM. Just saw that it might not work. It worked for me yesterday though, just not today.

**Comment by mashb1t** [comment]
Works without issues for me when downloading the current zip file https://github.com/lllyasviel/Fooocus/releases/download/release/Fooocus_win64_2-1-831.7z.
Please set up Fooocus again from scratch, there might have been an issue.

Make sure you use the official zip file.

This is my output:

```
C:\Users\manuel\Downloads\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Fast-forward merge
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.860
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_version6Rundiffusion.safetensors" to C:\Users\manuel\Downloads\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors

100%|██████████████████████████████████████████████████████████████████████████████| 6.62G/6.62G [01:01<00:00, 115MB/s]
Total VRAM 10240 MB, total RAM 32693 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : native
VAE dtype: torch.bfloat16
Running on local URL:  http://127.0.0.1:7865
Using pytorch cross attention

To create a public link, set `share=True` in `launch()`.
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: C:\Users\manuel\Downloads\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [C:\Users\manuel\Downloads\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [C:\Users\manuel\Downloads\Fooocus_win64_2-1-831\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\Users\manuel\Downloads\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.47 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
```
