### ISSUE TITLE
PC unexpectedly shuts off while installing model files

### ISSUE THREAD

**Issue by SHEHAN025** [lllyasviel/Fooocus#1674]
My PC is running on Windows 10 and has a 16GB RAM. Graphic card is Zotac 1660 Super 6GB. I think the system requirements are enough, but my PC shuts off abruptly while installing the model files somewhere around the end, like, 4 to 5GB (of 6.62GB installation). I can see the installed files so far have been stored as the folder size become larger. And when try to reinstall, it keeps happening over and over. What should i do?

**Comment by SHEHAN025** [comment]
@mashb1t can you provide me some solution, please?

**Comment by mashb1t** [comment]
This seems like a hardware issue to me. Please consult a diagnostics tool or use hardware monitoring to check if your CPU is overheating and check in the Windows event log if there are any critical system errors.
Do you have similar errors when doenloading large files from another source?
This should have nothing to do with Fooocus.

**Comment by mashb1t** [comment]
Are you still actively debugging this matter or have you found a solution?
