### ISSUE TITLE
Get higher resolution images of the single steps.

### ISSUE THREAD

**Issue by hswlab** [lllyasviel/Fooocus#1676]
I would like to make time-lapse animations of the generated images. Is there a specific folder, where to find the steps of the generated images in a higher resolution?

**Comment by mashb1t** [comment]
These temporary inages are not saved in a higher resolution. What you can do is to use a fixed seed and manually override the amount of steps, generating one image for each step in full resolution.
Ypu can do so in Advanced > Advanced > Developer Debug Mode > Forced Overwrite of Sampling Step.
Keep in mind that you'll have to deactivate the style "Fooocus V2" for this as it adds different extra keywords, which might differ for each run.
