### ISSUE TITLE
Very long upscaling on AMD

### ISSUE THREAD

**Issue by Waklaidan** [lllyasviel/Fooocus#1689]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
Very long upscaling. When i do upscale to 2x it takes 700 seconds when regular image generation takes 60
I have amd 6600xt
**Full Console Log**
```
HSA_OVERRIDE_GFX_VERSION=10.3.0 python3 entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
Fooocus version: 2.1.859
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 8176 MB, total RAM 15901 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 AMD Radeon RX 6600 XT : native
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --attention-split
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: /home/smooth/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/home/smooth/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [/home/smooth/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/home/smooth/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.76 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 6381012367455673301
[Fooocus] Downloading upscale models ...
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 18 - 9
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Image processing ...
[Fooocus] Upscaling image from (873, 618) ...
Upscaling image with shape (873, 618, 3) ...
Image upscaled.
[Fooocus] VAE encoding ...
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.36 seconds
Final resolution is (1744, 1232).
[Parameters] Denoising Strength = 0.382
[Parameters] Initial Latent shape: torch.Size([1, 4, 218, 154])
Preparation time: 562.69 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 0.5689725279808044
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.01 seconds
100%|███████████████████████████████████████████| 18/18 [01:55<00:00,  6.42s/it]
Requested to load AutoencoderKL
Loading 1 new model
Image generated with private log at: /home/smooth/Fooocus/outputs/2023-12-31/log.html
Generating and saving time: 202.58 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.35 seconds
Total time: 766.83 seconds
```

**Comment by mashb1t** [comment]
Thamk you for the report.
I do not have an AMD GPU to confirm, can somebody else please double-check?

**Comment by Amit30swgoh** [comment]
> **Read Troubleshoot**
> 
> [x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.
> 
> **Describe the problem** Very long upscaling. When i do upscale to 2x it takes 700 seconds when regular image generation takes 60 I have amd 6600xt **Full Console Log**
> 
> ```
> HSA_OVERRIDE_GFX_VERSION=10.3.0 python3 entry_with_update.py
> Already up-to-date
> Update succeeded.
> [System ARGV] ['entry_with_update.py']
> Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
> Fooocus version: 2.1.859
> Running on local URL:  http://127.0.0.1:7865
> 
> To create a public link, set `share=True` in `launch()`.
> Total VRAM 8176 MB, total RAM 15901 MB
> Set vram state to: NORMAL_VRAM
> Always offload VRAM
> Device: cuda:0 AMD Radeon RX 6600 XT : native
> VAE dtype: torch.float32
> Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --attention-split
> Refiner unloaded.
> model_type EPS
> UNet ADM Dimension 2816
> Using split attention in VAE
> Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
> Using split attention in VAE
> extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
> Base model loaded: /home/smooth/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors
> Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/home/smooth/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors].
> Loaded LoRA [/home/smooth/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/home/smooth/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
> Fooocus V2 Expansion: Vocab with 642 words.
> Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
> Requested to load SDXLClipModel
> Requested to load GPT2LMHeadModel
> Loading 2 new models
> [Fooocus Model Management] Moving model(s) has taken 0.76 seconds
> App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
> [Parameters] Adaptive CFG = 7
> [Parameters] Sharpness = 2
> [Parameters] ADM Scale = 1.5 : 0.8 : 0.3
> [Parameters] CFG = 4.0
> [Parameters] Seed = 6381012367455673301
> [Fooocus] Downloading upscale models ...
> [Parameters] Sampler = dpmpp_2m_sde_gpu - karras
> [Parameters] Steps = 18 - 9
> [Fooocus] Initializing ...
> [Fooocus] Loading models ...
> Refiner unloaded.
> [Fooocus] Processing prompts ...
> [Fooocus] Encoding positive #1 ...
> [Fooocus] Encoding negative #1 ...
> [Fooocus] Image processing ...
> [Fooocus] Upscaling image from (873, 618) ...
> Upscaling image with shape (873, 618, 3) ...
> Image upscaled.
> [Fooocus] VAE encoding ...
> Requested to load AutoencoderKL
> Loading 1 new model
> [Fooocus Model Management] Moving model(s) has taken 0.36 seconds
> Final resolution is (1744, 1232).
> [Parameters] Denoising Strength = 0.382
> [Parameters] Initial Latent shape: torch.Size([1, 4, 218, 154])
> Preparation time: 562.69 seconds
> [Sampler] refiner_swap_method = joint
> [Sampler] sigma_min = 0.0291671771556139, sigma_max = 0.5689725279808044
> Requested to load SDXL
> Loading 1 new model
> [Fooocus Model Management] Moving model(s) has taken 1.01 seconds
> 100%|███████████████████████████████████████████| 18/18 [01:55<00:00,  6.42s/it]
> Requested to load AutoencoderKL
> Loading 1 new model
> Image generated with private log at: /home/smooth/Fooocus/outputs/2023-12-31/log.html
> Generating and saving time: 202.58 seconds
> Requested to load SDXLClipModel
> Requested to load GPT2LMHeadModel
> Loading 2 new models
> [Fooocus Model Management] Moving model(s) has taken 0.35 seconds
> Total time: 766.83 seconds
> ```

have you tried dreamshaper xl turbo? it can be x4 times faster

**Comment by GZGavinZhao** [comment]
Please try installing the PyTorch nightly wheels `pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.7`. Nightly PyTorch are built with newer ROCm versions, which may help fix some issues.

**Comment by Amit30swgoh** [comment]
> Please try installing the PyTorch nightly wheels `pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.7`. Nightly PyTorch are built with newer ROCm versions, which may help fix some issue

I have same problem last 2 days on INTEL
Could u please send all neccecery files so i will reinstall everything because it seems that not only upscaled takes time to be shown slow frame bty frame display
The generate image is fast but then it takes a min instead of 2 second to display the result .. again on both upscaled and normal ty

**Comment by Amit30swgoh** [comment]
![293597956-444d8615-f4b8-47c7-ab50-0bad481fc1e1](https://github.com/lllyasviel/Fooocus/assets/42430868/646566a4-6e23-466e-a093-24fa6debedf9)

**Comment by mashb1t** [comment]
Hope the nightly will soon be stable and published with the next release. As PR code reviews will only happen mid/end of January again i'm not certain if it's worth it opening a OR for this or just waiting until rocm is officially fixed in zhe meantime.

**Comment by GZGavinZhao** [comment]
@mashb1t PyTorch 2.2.0 is already on RC6 and from the CI logs I believe it's going to be built with ROCm 5.7, the same version used in nightly, so I don't think there's going to be a long wait :D

**Comment by GZGavinZhao** [comment]
@Amit30swgoh I do not have Intel hardware so I unfortunately I'm unable to help.

**Comment by hqnicolas** [comment]
I'm Runing here without no problems using this GIST:

https://gist.github.com/hqnicolas/5fbb9c37dcfc29c9a0ffe50fbcb35bdd
