### ISSUE TITLE
Cannot run Fooocus after 1.0.32 update - ModuleNotFoundError: No module named 'cuda_malloc'

### ISSUE THREAD

**Issue by kirbykirby** [lllyasviel/Fooocus#169]
Fooocus version: 1.0.32
Inference Engine exists.
Git clone failed for Inference Engine: 'NoneType' object has no attribute '_pointer'
Traceback (most recent call last):
  File "J:\Fooocus_win64_1-1-10\Fooocus\entry_with_update.py", line 45, in <module>
    from launch import *
  File "J:\Fooocus_win64_1-1-10\Fooocus\launch.py", line 84, in <module>
    cuda_malloc()
  File "J:\Fooocus_win64_1-1-10\Fooocus\launch.py", line 78, in cuda_malloc
    import cuda_malloc
ModuleNotFoundError: No module named 'cuda_malloc'

**Comment by lllyasviel** [comment]
Related https://github.com/lllyasviel/Fooocus/issues/148

**Comment by derVedro** [comment]
same on linux in a venv.
```
$ python launch.py 
Python 3.10.7 (main, May 29 2023, 13:51:48) [GCC 12.2.0]
Fooocus version: 1.0.32
Inference Engine cloned.
Inference Engine checkout finished.
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Requirement already satisfied: torch==2.0.1 in ./venv/lib/python3.10/site-packages (2.0.1)
Collecting torchvision==0.15.2
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-linux_x86_64.whl (6.1 MB)
Requirement already satisfied: typing-extensions in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (4.7.1)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (8.5.0.96)
Requirement already satisfied: sympy in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (1.12)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (11.10.3.66)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (11.7.101)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (10.2.10.91)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (11.7.91)
Requirement already satisfied: filelock in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (3.12.2)
Requirement already satisfied: networkx in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (3.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (11.7.4.91)
Requirement already satisfied: triton==2.0.0 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (2.0.0)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (11.7.99)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (10.9.0.58)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (2.14.3)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (11.4.0.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (11.7.99)
Requirement already satisfied: jinja2 in ./venv/lib/python3.10/site-packages (from torch==2.0.1) (3.1.2)
Requirement already satisfied: numpy in ./venv/lib/python3.10/site-packages (from torchvision==0.15.2) (1.23.5)
Requirement already satisfied: requests in ./venv/lib/python3.10/site-packages (from torchvision==0.15.2) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./venv/lib/python3.10/site-packages (from torchvision==0.15.2) (9.2.0)
Requirement already satisfied: wheel in ./venv/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1) (0.41.1)
Requirement already satisfied: setuptools in ./venv/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1) (59.6.0)
Requirement already satisfied: cmake in ./venv/lib/python3.10/site-packages (from triton==2.0.0->torch==2.0.1) (3.27.2)
Requirement already satisfied: lit in ./venv/lib/python3.10/site-packages (from triton==2.0.0->torch==2.0.1) (16.0.6)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.10/site-packages (from jinja2->torch==2.0.1) (2.1.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests->torchvision==0.15.2) (2.0.4)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.10/site-packages (from requests->torchvision==0.15.2) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.10/site-packages (from requests->torchvision==0.15.2) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.10/site-packages (from requests->torchvision==0.15.2) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in ./venv/lib/python3.10/site-packages (from sympy->torch==2.0.1) (1.3.0)
Installing collected packages: torchvision
Successfully installed torchvision-0.15.2+cu118
Installing xformers
Traceback (most recent call last):
  File "/home/me/Fooocus/launch.py", line 84, in <module>
    cuda_malloc()
  File "/home/me/Fooocus/launch.py", line 78, in cuda_malloc
    import cuda_malloc
  File "/home/me/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/cuda_malloc.py", line 3, in <module>
    from comfy.cli_args import args
ModuleNotFoundError: No module named 'comfy.cli_args'
```

**Comment by jw408** [comment]
(focus) jw@aircooled3:~/ai2/focus$ python launch.py
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
Fooocus version: 1.0.32
Inference Engine exists.
Inference Engine checkout finished.
Traceback (most recent call last):
  File "/home/jw/ai2/focus/launch.py", line 84, in <module>
    cuda_malloc()
  File "/home/jw/ai2/focus/launch.py", line 78, in cuda_malloc
    import cuda_malloc
  File "/home/jw/ai2/focus/repositories/ComfyUI-from-StabilityAI-Official/cuda_malloc.py", line 3, in <module>
    from comfy.cli_args import args
ModuleNotFoundError: No module named 'comfy.cli_args'
(focus) jw@aircooled3:~/ai2/focus$ git ls-remote --tags origin
9978306be4335c1d73db0cff7c22ba39f29af46f        refs/tags/1.0.35
615137bd2fa68eaedf4c71280456d654afa8f7ed        refs/tags/release
(focus) jw@aircooled3:~/ai2/focus$ git checkout 1.0.35 -b local
Switched to a new branch 'local'
(focus) jw@aircooled3:~/ai2/focus$ git status
On branch local
nothing to commit, working tree clean
(focus) jw@aircooled3:~/ai2/focus$ python launch.py
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
Fooocus version: 1.0.35
Inference Engine exists.
Inference Engine checkout finished.
Traceback (most recent call last):
  File "/home/jw/ai2/focus/launch.py", line 84, in <module>
    cuda_malloc()
  File "/home/jw/ai2/focus/launch.py", line 78, in cuda_malloc
    import cuda_malloc
  File "/home/jw/ai2/focus/repositories/ComfyUI-from-StabilityAI-Official/cuda_malloc.py", line 3, in <module>
    from comfy.cli_args import args
ModuleNotFoundError: No module named 'comfy.cli_args'

**Comment by jw408** [comment]
For those reading this thread, I found a solution: somewhere, somehow, a pip package called comfy, not the same thing as in the source tree, was imported, and removing it did the trick:

`(focus) jw@aircooled3:~/ai2/focus/repositories/ComfyUI-from-StabilityAI-Official$ pip uninstall comfy
Found existing installation: comfy 0.0.1
Uninstalling comfy-0.0.1:
  Would remove:
    /home/jw/miniconda3/envs/focus/lib/python3.10/site-packages/comfy-0.0.1.dist-info/*
    /home/jw/miniconda3/envs/focus/lib/python3.10/site-packages/comfy/*
Proceed (Y/n)? y
  Successfully uninstalled comfy-0.0.1
(focus) jw@aircooled3:~/ai2/focus/repositories/ComfyUI-from-StabilityAI-Official$ python
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> from comfy.cli_args import args
>>>
(focus) jw@aircooled3:~/ai2/focus/repositories/ComfyUI-from-StabilityAI-Official$ cd ..
(focus) jw@aircooled3:~/ai2/focus/repositories$ cd ..
(focus) jw@aircooled3:~/ai2/focus$ python launch.py
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
Fooocus version: 1.0.36
['/home/jw/ai2/focus', '/home/jw/ai2/focus/repositories/ComfyUI-from-StabilityAI-Official/comfy', '/home/jw/miniconda3/envs/focus/lib/python310.zip', '/home/jw/miniconda3/envs/focus/lib/python3.10', '/home/jw/miniconda3/envs/focus/lib/python3.10/lib-dynload', '/home/jw/miniconda3/envs/focus/lib/python3.10/site-packages', '/home/jw/ai2/focus/repositories/ComfyUI-from-StabilityAI-Official']
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total VRAM 24564 MB, total RAM 31968 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention`

**Comment by kirbykirby** [comment]
> For those reading this thread, I found a solution: somewhere, somehow, a pip package called comfy, not the same thing as in the source tree, was imported, and removing it did the trick:
> 
> `(focus) jw@aircooled3:~/ai2/focus/repositories/ComfyUI-from-StabilityAI-Official$ pip uninstall comfy Found existing installation: comfy 0.0.1 Uninstalling comfy-0.0.1: Would remove: /home/jw/miniconda3/envs/focus/lib/python3.10/site-packages/comfy-0.0.1.dist-info/* /home/jw/miniconda3/envs/focus/lib/python3.10/site-packages/comfy/* Proceed (Y/n)? y Successfully uninstalled comfy-0.0.1 (focus) jw@aircooled3:~/ai2/focus/repositories/ComfyUI-from-StabilityAI-Official$ python Python 3.10.12 (main, Jul 5 2023, 18:54:27) [GCC 11.2.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import sys
> > > > from comfy.cli_args import args
> 
> (focus) jw@aircooled3:~/ai2/focus/repositories/ComfyUI-from-StabilityAI-Official$ cd .. (focus) jw@aircooled3:~/ai2/focus/repositories$ cd .. (focus) jw@aircooled3:~/ai2/focus$ python launch.py Python 3.10.12 (main, Jul 5 2023, 18:54:27) [GCC 11.2.0] Fooocus version: 1.0.36 ['/home/jw/ai2/focus', '/home/jw/ai2/focus/repositories/ComfyUI-from-StabilityAI-Official/comfy', '/home/jw/miniconda3/envs/focus/lib/python310.zip', '/home/jw/miniconda3/envs/focus/lib/python3.10', '/home/jw/miniconda3/envs/focus/lib/python3.10/lib-dynload', '/home/jw/miniconda3/envs/focus/lib/python3.10/site-packages', '/home/jw/ai2/focus/repositories/ComfyUI-from-StabilityAI-Official'] Running on local URL: http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`. Total VRAM 24564 MB, total RAM 31968 MB xformers version: 0.0.20 Set vram state to: NORMAL_VRAM Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync Using xformers cross attention`

Can you elaborate, please?

**Comment by derVedro** [comment]
> Can you elaborate, please?
delete comfy package via pip in your venv:
```
$ pip uninstall comfy
```

**Comment by maxchiron** [comment]
> if you use anaconda, you should remove package with `conda remove`

Not working after "conda remove comfy". But I might find the reason for this problem.

---
This might be a network problem when 'git clone comfyUI repo'. I guess fellows here might need proxy tool to have a more comfortable git action.
The way I figured this is Delete the folder in "repository" folder, then python launch.py again. Or delete the folder than "proxychains python launch.py"
This is a network problem in mine.
@lllyasviel 
---

**Comment by WangZhiqiang-academia** [comment]
Thanks to @maxchiron this seems indeed a network problem. My solution:
1. Delete the content of Fooocus/repositories/ComfyUI-from-StabilityAI-Official
2. Go to https://github.com/comfyanonymous/ComfyUI and download it in the directory. The .git should be directly in /ComfyUI-from-StabilityAI-Official

**Comment by mratanusarkar** [comment]
having same issue in Ubuntu 20.04.6 LTS

here is the stack trace:
```bash
(fooocus) atanu:~/Workspace/project-diffusers/Fooocus$ python launch.py
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
Fooocus version: 1.0.41
Inference Engine exists.
Git clone failed for Inference Engine: failed to resolve address for github.com: Name or service not known
Traceback (most recent call last):
  File "/home/atanu/Workspace/project-diffusers/Fooocus/launch.py", line 84, in <module>
    cuda_malloc()
  File "/home/atanu/Workspace/project-diffusers/Fooocus/launch.py", line 78, in cuda_malloc
    import cuda_malloc
ModuleNotFoundError: No module named 'cuda_malloc'
```

**Comment by lllyasviel** [comment]
please follow official installation guidelines.
(if any problems occur, check internet connection to github)
