### ISSUE TITLE
Ability to create an image by selecting a preset in the browser

### ISSUE THREAD

**Issue by monkrus** [lllyasviel/Fooocus#1692]
**Is your feature request related to a problem? Please describe.**
Ability to select preset image generation settings.

**Describe the idea you'd like**
I hope I do not repeat the ideas already proposed in issues. 

The idea is to add a feature allowing users to select preset image generation settings by typing a keyword. That would simplify the process for those not familiar with the platform. For example, one can choose a "famous singer", or "Instagram influencer" keyword and the best settings will immediately apply during the image creation.

Additionally, it could allow the user to save their custom settings.

**Comment by mashb1t** [comment]
Hey, thank you for the input.
After https://github.com/lllyasviel/Fooocus/pull/1570 has been merged you can switch presets in the UI, which would solve your first suggestion.
Keeping this issue open as a reminder to save the settings in UI to a preset.

**Comment by gitnito** [comment]
Just create your own styles json file on the sdxl_styles folder ...
