### ISSUE TITLE
High Resolution and wide aspect ratios

### ISSUE THREAD

**Issue by gitnito** [lllyasviel/Fooocus#1695]
**Is your feature request related to a problem? Please describe.**
When I try 32:9 at 5120x1440 I get multiple torsos or limbs scattered around or elongated bodies. If I generate 32 images maybe 1 or 2 are ok. If I keep the same ratio but at half the resolution, most images come out ok. Are any of the hi-res fixes floating around able to improve this? Ideally images get generated at high res as they look amazing.

**Describe the idea you'd like**
Other frameworks have implemented hi-res fixes for this issue. Is there such a fix for Fooocus, or is it possible to create one?

**Comment by mashb1t** [comment]
A Hi-Res Fix equivalent is already included in Fooocus. Please go ahead and try the 2x upscaling (non-fast variant) in Input Image > Upscale or Variation.
More insights into why these high resolutions aren't working in SDXL: https://github.com/lllyasviel/Fooocus/pull/1617
Hope this helped!
