### ISSUE TITLE
 Button to copy parameters to clipboard in log wont tranfer correctly the settings

### ISSUE THREAD

**Issue by PeterJared** [lllyasviel/Fooocus#1698]
This is supposed to allow users to load parameters directly by pasting parameters to prompt.
But there are numerous erros where the settings are not transferred or done in a wrong way.
For example:
-Image creation number will change to 1 instead 2
-Loras will reappear even they have been removed before
-Force overriding samples will reset to -1 even the setting was 6

**Comment by mashb1t** [comment]
Thank you for raising the issue.

> This is supposed to allow users to load parameters directly by pasting parameters to prompt. But there are numerous erros where the settings are not transferred or done in a wrong way. 
For example: 
-Image creation number will change to 1 instead 2

This is intended as you're copying the config for one image and users most likely want to generate this one image again or reiterate on one image.

> -Loras will reappear even they have been removed before

This is also correct as the iamge has been created with these LoRAs. You can only regenerate an image when having all necessary LoRAs downloaded

> -Force overriding samples will reset to -1 even the setting was 6

None of the Developer Debug Mode settings are overridden when using the import parameters action, which was already noticed. I assume you're trying to generate and reimporting configs for SDXL Turbo.
Please find the according PR including import of steps override here: https://github.com/lllyasviel/Fooocus/pull/1580
Until it is merged you may adjust the code locally to the one of the PR if needed.

Feel free to reopen the issue or provide additional feedback, which is always welcome.

**Comment by mashb1t** [comment]
Oh, correction: i really thought i've added the import for force override of steps to the PR, but it isn't included yet. Will do the changes after the PR has been merged.

**Comment by PeterJared** [comment]
If Im in the same session, it will keep the Loras out if it was out already. The image will look identical
But if I re start it, the default Lora will be added. The image will look different but will look identical again if I remove manually the Lora. Noticed I used a specific model, but this happens with any model.
 I'm not sure if your post above is in order to correct the  possible bug I with the Loras.


Using these settings, what was suppose to have no Loras on, but probably will activate it when you try to use it
{
"Prompt": "(DreamWorks 3d cartoon films style:1.1). Black male. Neutral expression",
"Negative Prompt": "",
"Fooocus V2 Expansion": "",
"Styles": "[]",
"Performance": "Speed",
"Resolution": "(896, 1152)",
"Sharpness": 2,
"Guidance Scale": 4,
"ADM Guidance": "(1.5, 0.8, 0.3)",
"Base Model": "new\\dynavisionXLAllInOneStylized_release0557Bakedvae.safetensors",
"Refiner Model": "None",
"Refiner Switch": 0.5,
"Sampler": "dpmpp_2m_sde_gpu",
"Scheduler": "karras",
"Seed": 6074194465337618730,
"Version": "v2.1.859"
}
![msedge_Gbb0fe9wp7](https://github.com/lllyasviel/Fooocus/assets/49351356/b79f6298-b7fb-48e2-bee2-3c1f7b3a9bfd)
![image](https://github.com/lllyasviel/Fooocus/assets/49351356/d54b7e65-e99e-4e15-b286-a561c58b0299)
