### ISSUE TITLE
slow loading finished images (Picture previews are slow to load)

### ISSUE THREAD

**Issue by Amit30swgoh** [lllyasviel/Fooocus#1705]
take long time to show the finished images and this problem started several hours ago
takes forever to load grids and preview images
Picture previews are slow to load  
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/a19450c9-7b69-4b65-a23f-8b22ae8f57a8)

what optimal python and gradio versions? because i did made a change by mistake
and how i uninstall and reinstall the working version please?

**Comment by mashb1t** [comment]
There weren't any code changes today, so we can rule that out. Please check what else is running on your computer and maybe close a few other programs if the performance of Fooocus is not as high as usual.
You can also find code adjustments concerning the intermediate image gallery here https://github.com/lllyasviel/Fooocus/pull/1013 (known to get slow if high image amount is generated at once).
If you're using my fork you already have the checkbox and can just enable it in advanced settings, dev debug mode (look for "intermediate").
Hope this helps.

**Comment by Amit30swgoh** [comment]
> There weren't any code changes today, so we can rule that out. Please check what else is running on your computer and maybe close a few other programs if the performance of Fooocus is not as high as usual. You can also find code adjustments concerning the intermediate image gallery here #1013 (known to get slow if high image amount is generated at once). If you're using my fork you already have the checkbox and can just enable it in advanced settings, dev debug mode (look for "intermediate"). Hope this helps.

seems to happan on any image the generated image is fast no probble but when finished it takes so much time to show the finished image i think i need to reinstall everything but not sure what to uninstall... could you please send me codes so i can uninstall thank you!

**Comment by mashb1t** [comment]
this is an individual problem. Please open a terminal and navigate to Fooocus root folder (the one where the config.txt is). Then run the command `git reset --hard`, with which you reset all your changes.
If this doesn't work: The Fooocus folder is self-containing, so you can just delete it completely and download + extract the zip file again.

**Comment by Amit30swgoh** [comment]
> this is an individual problem. Please open a terminal and navigate to Fooocus root folder (the one where the config.txt is). Then run the command `git reset --hard`, with which you reset all your changes. If this doesn't work: The Fooocus folder is self-containing, so you can just delete it completely and download + extract the zip file again.

Will try thanks you again.
