### ISSUE TITLE
Feature Request - Add Style Model to end of filename

### ISSUE THREAD

**Issue by mitchellkrogza** [lllyasviel/Fooocus#171]
It would be great if the output files could have the model used added on the end

Example: 2023-08-17_12-06-24_8513_artstyle-abstract-expressionism.png

**Comment by mashb1t** [comment]
Hey, i am afraid this will cause the file name to explode in length when multiple styles are used. Maybe this is better fit for an individual solution.
You can modify the filename here: https://github.com/lllyasviel/Fooocus/blob/0c4f20a0d261d4fe045aae6e5a0fcad185ba6804/modules/util.py#L141-L148
