### ISSUE TITLE
Video, Animations

### ISSUE THREAD

**Issue by Fedebat99** [lllyasviel/Fooocus#1711]
It would be nice to be able to create mini animations or videos, facial expressions, additional effects etc...

**Comment by Krupakar-Reddy-S** [comment]
I am pretty sure the current setup of the code supports image only but there are [video generating models](https://stability.ai/stable-video) and they can be added in the future, if you want to try vide generation you can try [ComfyUI](https://github.com/comfyanonymous/ComfyUI), a node based Stable Diffusion app.

Video generation is just getting started and future models will support more length and frame output options, But it is just not there yet.

**Comment by mashb1t** [comment]
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1031, it (at least) is in the backlog :)
