### ISSUE TITLE
Mac M2 - process disconnected without sending a response

### ISSUE THREAD

**Issue by PLILI729** [lllyasviel/Fooocus#1712]
I managed to open the 127.0.0.1 link in terminal, but when I "generate" the image, here comes out the errors, attached the photo for your ref, I am using macbook air with M2, please help
![WX20240102-171629@2x](https://github.com/lllyasviel/Fooocus/assets/133625274/1b944d4e-c8ea-4722-a075-97ae1ee1b6fb)
![WX20240102-171606@2x](https://github.com/lllyasviel/Fooocus/assets/133625274/6236fa23-b22a-4941-8f5e-eae39a8cb717)

**Comment by mashb1t** [comment]
Please check https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#connection-errored-out and make sure to use sufficient Swap or have memory assigned to your GPU.

**Comment by PLILI729** [comment]
I checked the link, found my swap should be capable to run, pls see below image, and I tries the command "--disable-offload-from-vram" (macbook M2) ,still doesn't work. FYI, 
![WX20240102-221901@2x](https://github.com/lllyasviel/Fooocus/assets/133625274/5d38db42-05ed-478d-b5b0-ca3206fc1a17)
![WX20240101-110904@2x](https://github.com/lllyasviel/Fooocus/assets/133625274/d44ea755-2926-44f8-9b13-6b545e40bf80)

**Comment by mashb1t** [comment]
It shows that 0 bytes swap are used on your Mac. Please double-check with `sysctl vm.swapusage`, if it also shows 0 bytes Swap isn't set up / used.
Personally i have never set up Fooocus on a Mac, so maybe somebody else can help if you still need some after running `sysctl vm.swapusage`.

**Comment by PLILI729** [comment]
I checked apple.com, system will be default to assign the swap usage, I hope some Mac guy could help, thank you anyway for kind help.

**Comment by mashb1t** [comment]
One last thing: 8GB RAM in the Macbook Air M2 might just be too little to be able to run Fooocus at all, but maybe sb. else can confirm.

**Comment by PLILI729** [comment]
Actually I successfully installed and run Fooocus before, after I deploy another AI under fooocus by mistake, everything changed, so bad. As you said, 8GB just maybe be too little, miss fooocus and will have another try.

**Comment by mashb1t** [comment]
Closing for now, maybe we stumble upon another solution in the future.
