### ISSUE TITLE
Error in API

### ISSUE THREAD

**Issue by nazar220160** [lllyasviel/Fooocus#172]
from gradio_client import Client

client = Client("http://127.0.0.1:7860/")

result = client.predict(
    "Howdy!",  # str in 'parameter_8' Textbox component
    "Howdy!",  # str in 'Negative Prompt' Textbox component
    "None",  # str in 'parameter_22' Radio component
    "Speed",  # str in 'Performance' Radio component
    "1152×896",  # str in 'Aspect Ratios (width × height)' Radio component
    1,  # int | float (numeric value between 1 and 32) in 'Image Number' Slider component
    -1,  # int | float in 'Random Seed' Number component
    2,  # int | float (numeric value between 0.0 and 40.0) in 'Sampling Sharpness' Slider component
    "sd_xl_base_1.0_0.9vae.safetensors",
    # str (Option from: ['sd_xl_base_1.0_0.9vae.safetensors', 'sd_xl_refiner_1.0_0.9vae.safetensors']) in 'SDXL Base Model' Dropdown component
    "sd_xl_refiner_1.0_0.9vae.safetensors",
    # str (Option from: ['None', 'sd_xl_base_1.0_0.9vae.safetensors', 'sd_xl_refiner_1.0_0.9vae.safetensors']) in 'SDXL Refiner' Dropdown component
    "sd_xl_offset_example-lora_1.0.safetensors",
    # str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 1' Dropdown component
    0.5,  # int | float (numeric value between -2 and 2) in 'Weight' Slider component
    "None",
    # str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 2' Dropdown component
    0.5,  # int | float (numeric value between -2 and 2) in 'Weight' Slider component
    "None",
    # str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 3' Dropdown component
    0.5,  # int | float (numeric value between -2 and 2) in 'Weight' Slider component
    "None",
    # str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 4' Dropdown component
    0.5,  # int | float (numeric value between -2 and 2) in 'Weight' Slider component
    "None",
    # str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 5' Dropdown component
    0.5,  # int | float (numeric value between -2 and 2) in 'Weight' Slider component
    fn_index=2
)
print(result)

Error:

Traceback (most recent call last):
  File "E:\Programming\Python\XelixAI\main.py", line 11, in <module>
    result = client.predict(
  File "E:\Programming\Python\XelixAI\venv\lib\site-packages\gradio_client\client.py", line 291, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "E:\Programming\Python\XelixAI\venv\lib\site-packages\gradio_client\client.py", line 1120, in result
    return super().result(timeout=timeout)
  File "C:\Users\nazar\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Users\nazar\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\nazar\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\Programming\Python\XelixAI\venv\lib\site-packages\gradio_client\client.py", line 794, in _inner
    predictions = self.process_predictions(*predictions)
  File "E:\Programming\Python\XelixAI\venv\lib\site-packages\gradio_client\client.py", line 984, in process_predictions
    predictions = self.deserialize(*predictions)
  File "E:\Programming\Python\XelixAI\venv\lib\site-packages\gradio_client\client.py", line 970, in deserialize
    [
  File "E:\Programming\Python\XelixAI\venv\lib\site-packages\gradio_client\client.py", line 971, in <listcomp>
    s.deserialize(
  File "E:\Programming\Python\XelixAI\venv\lib\site-packages\gradio_client\serializing.py", line 200, in deserialize
    file = utils.decode_base64_to_file(x, dir=save_dir)
  File "E:\Programming\Python\XelixAI\venv\lib\site-packages\gradio_client\utils.py", line 426, in decode_base64_to_file
    data, extension = decode_base64_to_binary(encoding)
  File "E:\Programming\Python\XelixAI\venv\lib\site-packages\gradio_client\utils.py", line 391, in decode_base64_to_binary
    extension = get_extension(encoding)
  File "E:\Programming\Python\XelixAI\venv\lib\site-packages\gradio_client\utils.py", line 347, in get_extension
    encoding = encoding.replace("audio/wav", "audio/x-wav")
AttributeError: 'dict' object has no attribute 'replace'

![image](https://github.com/lllyasviel/Fooocus/assets/47225102/6787b5dc-feda-4ddf-89cf-8b4bb48458bd)

**Comment by shirubei** [comment]
same error here.

**Comment by gxy0410** [comment]
怎么解决呢

**Comment by wuaidajiejie** [comment]
I'm having the same problem, has anyone solved it yet?

**Comment by shirubei** [comment]
Hello guys, I found the solution here https://github.com/Vision-CAIR/MiniGPT-4/issues/158
the buddy said "don't serialize"
client = Client("http://127.0.0.1:7860/", serialize=False)

**Comment by wuaidajiejie** [comment]
> 

good. The right thing to do.

**Comment by wuaidajiejie** [comment]
> Hello guys, I found the solution here [Vision-CAIR/MiniGPT-4#158](https://github.com/Vision-CAIR/MiniGPT-4/issues/158) the buddy said "don't serialize" client = Client("http://127.0.0.1:7860/", serialize=False)

good. The right thing to do.

**Comment by DevepNoName** [comment]
```python
from gradio_client import Client

client = Client("http://127.0.0.1:7865/", serialize=False)
result = client.predict(
	"Howdy!",	# str in 'parameter_10' Textbox component
	"Howdy!",	# str in 'Negative Prompt' Textbox component
	["Fooocus V2"],	# List[str] in 'Selected Styles' Checkboxgroup component
	"Speed",	# str in 'Performance' Radio component
	"1152×896", # <span style='color: grey;'> | 1:2</span>",	# str in 'Aspect Ratios' Radio component
	1,	# int | float (numeric value between 1 and 32)in 'Image Number' Slider component
	"123",	# str in 'Seed' Textbox component
	0,	# int | float (numeric value between 0.0 and 30.0)in 'Image Sharpness' Slider component
	1,	# int | float (numeric value between 1.0 and 30.0)in 'Guidance Scale' Slider component
	"juggernautXL_version6Rundiffusion.safetensors",	# str (Option from: ['juggernautXL_version6Rundiffusion.safetensors', 'realisticStockPhoto_v10.safetensors', 'bluePencilXL_v050.safetensors', 'DreamShaper_8_pruned.safetensors'])in 'Base Model (SDXL only)' Dropdown component
	"None",	# str (Option from: ['None', 'juggernautXL_version6Rundiffusion.safetensors', 'realisticStockPhoto_v10.safetensors', 'bluePencilXL_v050.safetensors', 'DreamShaper_8_pruned.safetensors'])in 'Refiner (SDXL or SD 1.5)' Dropdown component
	0.1,	# int | float (numeric value between 0.1 and 1.0)in 'Refiner Switch At' Slider component
	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors', 'SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 'sdxl_lcm_lora.safetensors'])in 'LoRA 1' Dropdown component
	-2,	# int | float (numeric value between -2 and 2)in 'Weight' Slider component
	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors', 'SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 'sdxl_lcm_lora.safetensors'])in 'LoRA 2' Dropdown component
	-2,	# int | float (numeric value between -2 and 2)in 'Weight' Slider component
	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors', 'SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 'sdxl_lcm_lora.safetensors'])in 'LoRA 3' Dropdown component
	-2,	# int | float (numeric value between -2 and 2)in 'Weight' Slider component
	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors', 'SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 'sdxl_lcm_lora.safetensors'])in 'LoRA 4' Dropdown component
	-2,	# int | float (numeric value between -2 and 2)in 'Weight' Slider component
	"None",	# str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors', 'SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 'sdxl_lcm_lora.safetensors'])in 'LoRA 5' Dropdown component
	-2,	# int | float (numeric value between -2 and 2)in 'Weight' Slider component
	True,	# bool in 'Input Image' Checkbox component
	"Howdy!",	# str in 'parameter_73' Textbox component
	"Disabled",	# str in 'Upscale or Variation:' Radio component
	"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==",	# str (filepath or URL to image)in 'Drag above image to here' Image component
	["Left"],	# List[str] in 'Outpaint Direction' Checkboxgroup component
	"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==",	# str (filepath or URL to image)in 'Drag above image to here' Image component
	"Howdy!",	# str in 'Inpaint Additional Prompt' Textbox component
	"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==",	# str (filepath or URL to image)in 'Image' Image component
	0,	# int | float (numeric value between 0.0 and 1.0)in 'Stop At' Slider component
	0,	# int | float (numeric value between 0.0 and 2.0)in 'Weight' Slider component
	"ImagePrompt",	# str in 'Type' Radio component
	"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==",	# str (filepath or URL to image)in 'Image' Image component
	0,	# int | float (numeric value between 0.0 and 1.0)in 'Stop At' Slider component
	0,	# int | float (numeric value between 0.0 and 2.0)in 'Weight' Slider component
	"ImagePrompt",	# str in 'Type' Radio component
	"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==",	# str (filepath or URL to image)in 'Image' Image component
	0,	# int | float (numeric value between 0.0 and 1.0)in 'Stop At' Slider component
	0,	# int | float (numeric value between 0.0 and 2.0)in 'Weight' Slider component
	"ImagePrompt",	# str in 'Type' Radio component
	"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==",	# str (filepath or URL to image)in 'Image' Image component																			  
	0,	# int | float (numeric value between 0.0 and 1.0)in 'Stop At' Slider component																  
	0,	# int | float (numeric value between 0.0 and 2.0)in 'Weight' Slider component
	"ImagePrompt",	# str in 'Type' Radio component
	fn_index=29
)
print(result)
``` 

its working for me

**Comment by 8benjamin8** [comment]
same problem, did you fix it
