### ISSUE TITLE
(Not Issue) Works on 1660ti mobile

### ISSUE THREAD

**Issue by nivibilla** [lllyasviel/Fooocus#1732]
Hi,

Thank you for the amazing project. Glad to report that it works without any issues on my 6gb 1660ti mobile gpu. Albeit takes 5 mins per image.

Thanks

**Comment by nivibilla** [comment]
SDXL Turbo Versions also work

**Comment by mashb1t** [comment]
@nivibilla Perfect, good to know. Thanks for the report!
