### ISSUE TITLE
Inpaint + Face Swap

### ISSUE THREAD

**Issue by nivibilla** [lllyasviel/Fooocus#1737]
**Describe the idea you'd like**
Capability to select parts of an image(inpaint), and also provide reference face to generate with.

**Comment by mashb1t** [comment]
Luckily this option already exists, please find it in the checkbox in the advanced tab, called "Mixing Image Prompt and Inpaint".
See https://github.com/lllyasviel/Fooocus/blob/main/webui.py#L393C90-L393C90
Happy inpainting and mixing!

**Comment by nivibilla** [comment]
Thanks

**Comment by orangpelupa** [comment]
> Luckily this option already exists, please find it in the checkbox in the advanced tab, called "Mixing Image Prompt and Inpaint". See https://github.com/lllyasviel/Fooocus/blob/main/webui.py#L393C90-L393C90 Happy inpainting and mixing!

those that cant find this feature, its inside the ADCVANCED, DEV DEBUG, CONTROL.
