### ISSUE TITLE
Request for feature : Preview of style on mouse over (hover)

### ISSUE THREAD

**Issue by simartem** [lllyasviel/Fooocus#1743]
It would be so nice if we had a feature to preview the style with a sample image of that style, while we move the mouse over that style.

As an example : 

![image](https://github.com/lllyasviel/Fooocus/assets/148996864/db3ff042-1b75-4204-8db8-b17e87a4004e)

Do you think its possible..

**Comment by Nears-115** [comment]
I think it would be a useful feature to have, but I'm curious as to how they plan to implement it.
I think it's unique if you come up with a complete idea.

I think the substance of each style is a combination of a style name, text like a prompt, and text like a negative prompt.
Personally, I like that users can create their own original styles with just a text editor and minimal knowledge.
Can you change the 3 text combinations to 4 and add image file names or URL links?
If we were to compromise the ability for users to create their own original styles, it would probably be easier to have a feature that displays prepared images according to each predefined style.
Personally, I would like to avoid such an implementation.

I don't think it would be a good idea to just add the horizontal spear and then leave it, so I'll also write a personal request related to style.

Is it possible to have a feature like image prompts that allow you to style specific images?
It's like processing the original image file and inserting prompts, negative prompts, and style names in a specific format in the metadata part.
It would be even better if the illustrations of the original images could complement the sensory parts that cannot be explained in text, similar to image prompts.
Wouldn't it be nice if they were lined up together with the styles? Then, strangely, one style and one illustration would be connected.
Instead, there is the drawback that one processed image file is required for each style, but I think it would be nice if it could be used in conjunction with the conventional one.

**Comment by mashb1t** [comment]
The easiest way would be to add a link to https://github.com/lllyasviel/Fooocus/discussions/143

**Comment by docppp** [comment]
Maybe not hover images, but i think static page would be sufficient:
https://github.com/lllyasviel/Fooocus/pull/1749

**Comment by simartem** [comment]
I respect all other ideas but we all know it is not the easiest way to find a style while exploring a webpage out of the gui. I understand that it is not the easiest way to put sample images over all the styles, but if it is something a developer can manage to do, I believe it is the most useful. Thank you for all the developer efforts and I respect.

**Comment by mashb1t** [comment]
@simartem Gradio currently doesn't support tooltips for python, so one would have to write a custom component for Gradio 3.41.2. There is one available for javascript though: https://www.gradio.app/main/docs/js/tooltip / https://www.npmjs.com/package/@gradio/tooltip?activeTab=code
TBH i don't know if i'm able to pull it off and if it's worth the hassle of also maintaining the component when upgrading to Gradio 4.12.0 (partially done, see https://github.com/lllyasviel/Fooocus/pull/961 for 4.3.0, but outdated).
The component might be available soon anyways in Gradio (python), see https://github.com/gradio-app/gradio/issues/4278 and https://github.com/gradio-app/gradio/issues/3050), so i guess the most rational decision would be to wait with this feature, at least in the extend you had in mind.

**Comment by hswlab** [comment]
Can you temporaly add a "History Log Link" to [style samples](https://github.com/lllyasviel/Fooocus/discussions/143), like in the Settings tab at the very bottom?
![image](https://github.com/lllyasviel/Fooocus/assets/12501993/85542be9-3535-4348-a392-848fcb49d58b)

**Comment by mashb1t** [comment]
@hswlab i don't see the benefit of adding something temporarily, especially if, like in this case, the link is already there but in another tab.
Feel free to copy the code over for an individual solution.

**Comment by crohrer** [comment]
@simartem please see my PR #1762

**Comment by hswlab** [comment]
@mashb1t  I thought the solution with tooltips would take a little longer, hence the suggestion with a link to a static view where the styles are explained. But there already seems to be an implemented solution with tooltips, which is of course more convenient. :)
