### ISSUE TITLE
I see error after clicking on generate button.

### ISSUE THREAD

**Issue by Absleepy** [lllyasviel/Fooocus#1744]
**Describe the problem**
I installed the python and other packages of the repo. I ran the application and it runs perfectly but when i type something in the prompt and click generate. After a few seconds I see this error.
Here is a screenshot of the error.
 
![Screenshot from 2024-01-04 15-43-21](https://github.com/lllyasviel/Fooocus/assets/59653077/d24ab989-a596-42f2-8668-271b36186494)

**Full Console Log**
index.js:488 WebSocket connection to 'ws://localhost:7865/queue/join' failed:

**Comment by harrypango** [comment]
I ran into the same error yesterday and I think it has to do with storage. Someone suggested that could be the problem and it was, so I freed up as much space as I could on my SSD. That worked and I'm not getting these errors anymore.

**Comment by mashb1t** [comment]
Please follow the troubleshooting guide https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md and find all issues relating this error here: https://github.com/lllyasviel/Fooocus/issues?q=is%3Aissue+errored+out+is%3Aclosed.
