### ISSUE TITLE
Your start amd realistic/anime codes are wrong they start like this

### ISSUE THREAD

**Issue by KintCark** [lllyasviel/Fooocus#1747]
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml --preset anime
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml --preset realistic

**Comment by mashb1t** [comment]
> For AMD, use python entry_with_update.py --directml --preset anime or python entry_with_update.py --directml --preset realistic for Fooocus Anime/Realistic Edition.

See readme, https://github.com/lllyasviel/Fooocus
