### ISSUE TITLE
Colab: Crashing every 8 to 15 minutes

### ISSUE THREAD

**Issue by Sharpbeep** [lllyasviel/Fooocus#1756]
**Describe the problem**
So in the between 8 to 15 minutes usually, the fooocus on colab crashes, it is ^C or it just crashes withou any explanation.

**Full Console Log**
I don´t have the log because I´m consistently resetting the whole code when it keeps crashing to keep using it, I would really appreciate any help with this consistent issue I´m having because it interrupts my work and makes it really harder and longer then it should be.

**Comment by mashb1t** [comment]
Please provide more information about
- what you're doing exactly on Colab or if idle for that time
- if you're using image prompt
- RAM + VRAM statistics
- further ciecumstances

so we're able to help you better

**Comment by Sharpbeep** [comment]
I´m doing on colab: face swapping, upscaling (2x), Inpainting bad things. Basically I´m doing fully AI influencer mode which means that I use almost every tool on the Colab UAI. 
My ram is 8GB and VRAM is 3GB (I know shit but I somehow seem to still be able to use the Colab)
That´s pretty much everything I do, just trying to get some high quality pictures for my AI model that I will train later in the future

**Comment by mashb1t** [comment]
I was referring to the statistics of RAM and VRAM on Colab while generating.

Please find this laragraph in our readme:
> Note that this Colab will disable refiner by default because Colab free's resources are relatively limited (and some "big" features like image prompt may cause free-tier Colab to disconnect). We make sure that basic text-to-image is always working on free-tier Colab.

You can apply the optimisations from https://github.com/lllyasviel/Fooocus/pull/1710 or upgrade to Colab Pro.

Most likely your RAM is exhausted, which is why your process is cancelled. Please check and upgrade it or your plan.

See #1330, #1574, #1558 (comment), #1619
