### ISSUE TITLE
not enough memory: you tried to allocate 9437184 bytes

### ISSUE THREAD

**Issue by PublicClassHorny** [lllyasviel/Fooocus#177]
![изображение_2023-08-17_183921003](https://github.com/lllyasviel/Fooocus/assets/114310288/bf993c7d-4938-4f01-9795-d5bea6f48dfe)

I have this error on Nvidia gtx 1660 6gb/ AMD Ryzen 5/ 16Gb Ram
My pagefile.sys was about 16Gb and i tried to expand into unlimited but no luck with this error.
Any ideas? :/

**Comment by lllyasviel** [comment]
In readme there is a "Click here to the see the image instruction." see if that works

**Comment by PublicClassHorny** [comment]
> In readme there is a "Click here to the see the image instruction." see if that works

Did it exatctly like on a picture, restarted my pc but still have this error after a few minutes of rendering

**Comment by lllyasviel** [comment]
How many free space do you have on your hard disk?

**Comment by PublicClassHorny** [comment]
> How many free space do you have on your hard disk?

23Gb on E drive (when Fooocus installed) and 5Gb on C drive.
How much i need btw?

**Comment by PublicClassHorny** [comment]
> Not sure but you can try to get 50GB free space on each drive and then it should work much likely - free space is the more the better

Thanks, it worked out well! Rendering consumes about 30Gb on C drive. But i have 2 questions:

1. Is that normal that it took more than 1 hour to generate 1 pic on my hardware? 
2.Where can I find files left after generation to delete them? I mean those temporary files (about 30Gb) with which the program littered my disk.

**Comment by lllyasviel** [comment]
1. one hour is relatively slow, but if you are using old hardware, that may happen. You may try other software to run SDXL and see if their speed has differences.
2. There are no temp files to remove. This is Microsoft Windows's virtual swap technique to use hard disk as system memory. Your free space in your hard disk is still there, but they are temporarily used by your Windows to help system memory issue.
