### ISSUE TITLE
Input Image not working

### ISSUE THREAD

**Issue by AkashSCIENTIST** [lllyasviel/Fooocus#1771]
When Colab notebook as well as drive folder is shared between users. Input Image feature is working only for owner user. Others users getting unfinished rendering and missing feature issues

**Comment by mashb1t** [comment]
Can you please provide the terminal output or a screenshot of the errors for the other users? This would make further debugging much easier. Thank you!

**Comment by mashb1t** [comment]
@AkashSCIENTIST bump

**Comment by freshlesh3** [comment]
Having the same issue on a local install.  Anyone have a resolution to this?
