### ISSUE TITLE
Foocus brush alternatives for inpaint, outpaint

### ISSUE THREAD

**Issue by hclivess** [lllyasviel/Fooocus#1774]
Hello. Can we please have something like PNG transparency recognition instead of having to use the Foocus brush when using the paint feature? I would like to prepare the image in advance in Photoshop instead of having to paint over it every time with this less precise tool that lags a lot when zoomed in. If it's possible now, please tell me how. Thanks.

**Comment by simartem** [comment]
![image](https://github.com/lllyasviel/Fooocus/assets/148996864/04fe575d-8cca-42c2-9c73-3e1e5bd8067e)

And then..

![image](https://github.com/lllyasviel/Fooocus/assets/148996864/1d19b973-55c9-4379-9649-debb5e468f23)

**Comment by hclivess** [comment]
Oh this is genius, thank you!

**Comment by hclivess** [comment]
Maybe I was a little hasty here. It appears a bit limited, I wanted to use the masked part of the image as context for the whole picture (head) while this only allows for black color. I would welcome if black was anything (with context) and white was to be replaced.

**Comment by hclivess** [comment]
Nevermind, FaceSwap fills my request
