### ISSUE TITLE
Запуск на intel

### ISSUE THREAD

**Issue by den47999** [lllyasviel/Fooocus#1776]
подскажите как можно запустить  на видеокарте intel? при запросе выходит ошибка.

**Comment by mashb1t** [comment]
Sorry to say, but Fooocus doesn't currently offer support for Intel GPUs of any kind.
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1107, also see https://github.com/lllyasviel/Fooocus/issues/1470
