### ISSUE TITLE
Add option to disable web browser auto launch

### ISSUE THREAD

**Issue by MqtUA** [lllyasviel/Fooocus#1778]
Please add an option to disable web browser auto launch on Fooocus start.

I use a separate browser for Image Generators, and it's kinda annoying that each time I start Fooocus my main browser launches and have to close it.

**Comment by sakibulalam** [comment]
This is already an option for that. Run Foocus with `--disable-in-browser` flag.

```shell
python3 entry_with_update.py --disable-in-browser
```

**Comment by MqtUA** [comment]
Well, it doesn't work.

**Comment by mashb1t** [comment]
Fix is already implemented and waiting for review, see https://github.com/lllyasviel/Fooocus/pull/1718

**Comment by MqtUA** [comment]
> Fix has already been implemented and awaiting review, see #1718 Feel free to copy the code of the PR to your installation.

Yep, that worked. Thank you.
