### ISSUE TITLE
Additional LoRA types support: LoHA/LyCORIS

### ISSUE THREAD

**Issue by aolko** [lllyasviel/Fooocus#1780]
Please add support for additional LoRA types like LoHA and LyCORIS

**Comment by mashb1t** [comment]
This should already work (at least LyCORIS, please test!
See https://github.com/lllyasviel/Fooocus/issues/297

**Comment by aolko** [comment]
Some loras produce fried vivid orange/pink outputs

**Comment by mashb1t** [comment]
Can you please provide links to those LoRAs (if they are LoRAs) and your terminal output? Thanks!

**Comment by aolko** [comment]
> Can you please provide links to those LoRAs (if they are LoRAs) and your terminal output? Thanks! Please make sure to only use adaptions trained for SDXL, not 1.5 or 2.1.

Log: https://paste.ee/p/yIvxU
Lora: [Get](https://sprend.com/download?C=0cd4472b0fce473eb5d7c3520a084329) [[Mirror]](https://send.cm/d/riPa)

**Comment by aolko** [comment]
> I can't find any information about TGXL on the internet, did you train this LyCORIS yourself? Please provide a link to Civitai / HuggingFace or similar if it's been downloaded to get more information about it.

No i did not, it's a [niche LoRA](https://privnote.com/CaTybOcd#ZV5Fvn3g5)

**Comment by aolko** [comment]
> I was able to successfully generate images with the LyCORIS you've provided, so this is not an issue of Fooocus (also combined with other LoRAs + also the linked LyCORIS can be used without issues). Please check if this also works for you when reducing the amount of LoRAs used (single LoRA test, not 5 LoRAs at once) or adjusting their weight.

i noticed that it fries image on `.8`+, seems fine on `.6`-

**Comment by RodTDai** [comment]
i tried lycoris, it is not working for me, can you take a test?
i tried this one:
https://civitai.com/models/90175/elizabeth-mitchell

additionally, anyone know how to use "embbedings" from civitai?
thanks

**Comment by mashb1t** [comment]
Please make sure you're using SDXL LoRAs/LyCORIS as you can only use 1.5 with 1.5 refiner.

Embeddings can be used by adding them to a preset, see anime as reference.
