### ISSUE TITLE
A very strange question: sits on "Waiting for task to start"

### ISSUE THREAD

**Issue by coollofty** [lllyasviel/Fooocus#1786]
I coded in VisualStudio C++, use system or CreateProcess, or ShellExecute functions to execute "run.bat" in Fooocus directory to make fooocos started. At this time, after I submit any prompt, "Waiting for task to start" will hold on forever, no errors, no exceptions, no warnings ...

However, if I enter 'run. bat' in the windows command line, then after starting the focus, everything will be fine ...

What the difference? All are the same user and have the same permissions.

**Comment by mashb1t** [comment]
Are you by chance using any dev container or virtual environment to run VS C++ in? Please provide your terminal output for both cases, using VS C++ and native execution. Thanks!

**Comment by coollofty** [comment]
no, no docker, is native in windows 11, This computer only has one nvidia GPU (RTX 3070), from 'run.bat' and clicked 'generate' button, the console output:

`[System ARGV] ['Fooocus\\launch.py', '--unet-in-fp16', '--clip-in-fp16', '--disable-server-log', '--disable-image-log', '--port', '8860', '--output-path', 'D:\\Fooocus\\\\Fooocus\\outputs\\0']
Running on local URL:  http://127.0.0.1:8860

To create a public link, set `share=True` in `launch()`.
Total VRAM 16383 MB, total RAM 32654 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: D:\sd-webui-aki-v4.2\models\Stable-diffusion\sdxl-juggernaut-v7.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [D:\sd-webui-aki-v4.2\models\Stable-diffusion\sdxl-juggernaut-v7.safetensors].
Loaded LoRA [D:\Fooocus\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [D:\sd-webui-aki-v4.2\models\Stable-diffusion\sdxl-juggernaut-v7.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.62 seconds`

In browser DevTools->Network tab, I can see one with 4 requests, the 'fn_index' from 29 to 32. It seems that the first three requests have been completed, as you can see:

`{"msg":"process_completed","output":{"data":[],"is_generating":false,"duration":0.0005483627319335938,"average_duration":0.0005483627319335938},"success":true}`

but fn_index=32 blocked, the last incoming message is:

`{"msg":"process_generating","output":{"data":[{"visible":true,"value":"\n<div class=\"loader-container\">\n  <div class=\"loader\"></div>\n  <div class=\"progress-container\">\n    <progress value=\"1\" max=\"100\"></progress>\n  </div>\n  <span>Waiting for task to start ...</span>\n</div>\n","__type__":"update"},{"visible":true,"value":null,"__type__":"update"},{"visible":false,"value":[],"__type__":"update"},{"visible":false,"__type__":"update"}],"is_generating":true,"duration":0.0010046958923339844,"average_duration":0.0010046958923339844},"success":true}`

Then, there was no changes... And below is the log I directly entered after running. bat in the command line window:

`[System ARGV] ['Fooocus\\launch.py', '--unet-in-fp16', '--clip-in-fp16', '--disable-server-log', '--disable-image-log', '--port', '8860', '--output-path', 'D:\\Fooocus\\\\Fooocus\\outputs\\0']
Running on local URL:  http://127.0.0.1:8860

To create a public link, set `share=True` in `launch()`.
Total VRAM 16383 MB, total RAM 32654 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: D:\sd-webui-aki-v4.2\models\Stable-diffusion\sdxl-juggernaut-v7.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [D:\sd-webui-aki-v4.2\models\Stable-diffusion\sdxl-juggernaut-v7.safetensors].
Loaded LoRA [D:\Fooocus\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [D:\sd-webui-aki-v4.2\models\Stable-diffusion\sdxl-juggernaut-v7.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.47 seconds
HTTPConnectionPool(host='127.0.0.1', port=17676): Max retries exceeded with url: /query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002512A7C8820>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 1458699028748523029
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] cat, highly detailed, professional composition, dramatic striking, cinematic, full detail, beautiful, emotional, shiny, colorful, color, sharp focus, intricate, majestic, epic, atmosphere, new, dynamic, ambient, futuristic, magic, vivid, designed, rich deep background, open flowing, symmetry, unique, great, fine light, artistic, surreal, perfect, balanced
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] cat, elegant, highly detailed, dramatic light, sharp focus, perfect composition, aesthetic, very inspirational, colorful, deep rich colors, creative, cinematic, fine detail, crisp color, intricate, beautiful, epic, stunning, striking, iconic, vibrant, complex, enhanced, ambient background, professional, thought, imposing, incredible, wonderful, full, amazing, awesome, scenic
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 2.93 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.39 seconds
 17%|█████████████▊                                                                     | 5/30 [00:04<00:20,  1.21it/s]`

**Comment by mashb1t** [comment]
I'm not familiar with your environment, but maybe you've found a fix in the meantime which you'd like to share with the community. If no fix was found i'd like to redirect you to a forum for VS C++ support as Fooocus is running fine when being used the official way. Thanks for your reply.

**Comment by coollofty** [comment]
Yes, I have looked for various solutions but none have been able to solve this problem, so this may have been caused by myself. I will double check and thank you^_^
