### ISSUE TITLE
Jpeg 100% quality save

### ISSUE THREAD

**Issue by RodTDai** [lllyasviel/Fooocus#1789]
Hey guys!
Should be nice to have an option to save image in JPEG 100% quality instead of png. 
Thanks.

**Comment by mashb1t** [comment]
Saving could be achieved relatively easy by changing the two lines https://github.com/lllyasviel/Fooocus/blob/176faf6f347b90866afe676fc9fb2c2d74587d7b/modules/private_logger.py#L16 and https://github.com/lllyasviel/Fooocus/blob/176faf6f347b90866afe676fc9fb2c2d74587d7b/modules/private_logger.py#L25 accordingly.
Temp images in the browser are png base64 encoded images directly from pytorch_to_numpy as far as i could see and there is no conversion happening.
If you need the jpg/jpeg results only in your outputs folder, feel free to change private_logger.py accordingly.

Enhancement: make this configurable.

**Comment by RodTDai** [comment]
nice. Yes configurability is important here, because when system update files, we loose that custom modifications.
Thanks

**Comment by eddyizm** [comment]
A config something like this ?
![image](https://github.com/lllyasviel/Fooocus/assets/12236892/2ade2380-fbd4-4c28-9f5f-184262c523d2)

I got the front end mostly working but need to figure out how to update the configuration using gradio if this works.

**Comment by eddyizm** [comment]
tested my pr locally but did not see any unit tests. If this needs to save to the file to maintain state, I can update my PR.

**Comment by drdancm** [comment]
This would be a wonderful enhancement.

**Comment by RodTDai** [comment]
actually a change for gradio is a good thing, as it can become super slow when running machine at home and accessing via mobile. Jpeg will help that too.

**Comment by Irmagon** [comment]
Maybe add an additional parameter _image_quality_ specifying the JPG compression ratio?
And setting this in UI input box or config.txt.
For example: `Image.fromarray(img).save(local_temp_filename, quality=image_quality)`
In PIL.Images _quality_ only affects the lossy compression format and not be used for PNG.

**Comment by mashb1t** [comment]
@Irmagon already noticed when implementing https://github.com/lllyasviel/Fooocus/pull/1940, fixed in https://github.com/lllyasviel/Fooocus/pull/1863/commits/f1261028b8b4d0d57e5205cdea9755abdb404e95
