### ISSUE TITLE
How can I get fooocus to listen on my ip address instead of localhost?

### ISSUE THREAD

**Issue by Tigwin** [lllyasviel/Fooocus#18]
It works on 127.0.0.1, but I want it to run off of my network ip of 192.168.68.100 instead. That way I can access it from other computers in the home instead of just being on console. 

There is a share=True setting mentioned at startup, but no mention of which file to put that into. It doesn't work on the start.bat file, and I'm not sure if this setting does what I'd like. It doesn't seem like I should be editing the source files when the launcher does a git pull at startup either....

any idea?

thanks

**Comment by alfhj** [comment]
You can change webui.py. Change the bottom line to be:
`block.launch(inbrowser=True, server_name="0.0.0.0")`

**Comment by Tigwin** [comment]
thanks, that worked

**Comment by Tigwin** [comment]
actually, every time I launch fooocus, it overwrites the webui.py file, so this is still an issue. Can we get a config file that lets us set parameters without losing settings during an upgrade?

**Comment by filsanet** [comment]
Looks like this is being added.

See https://github.com/lllyasviel/Fooocus/discussions/6 for how to change your run.bat file to support the new options.
