### ISSUE TITLE
Use of Leco loRA's

### ISSUE THREAD

**Issue by mannidm** [lllyasviel/Fooocus#1802]
**Describe the idea you'd like**
Since Leco loRA's are more of a tool with a slider any chance we will get this added to fooocus? These would allow for greater control of the images and I am not sure if any forks even have this feature yet.

They do not seem to do anything in the current lora system and I am hoping this can get added in as This is a great feature. they dont error out I just cant get anything to happen.

example leco I was trying to use:
https://civitai.com/models/138760/colortone-slider

I dont even know if they can be added just hoping.

**Comment by mashb1t** [comment]
Fooocus currently doesn't include any LoRAs except the official SDXL offset by StabilityAI by default, as not everybody needs them.

The LoRA you've mentioned has been trained on SD 1.5, but Fooocus as a SDXL exclusive tool is not able to handle this without tricks. Please check out a related issue including a potential fix here: https://github.com/lllyasviel/Fooocus/issues/1568

Feel free to experiment locally and you may even consider creating a preset to set all the necessary thjngs for it on startup. All the best!

**Comment by mashb1t** [comment]
May also be related to https://github.com/lllyasviel/Fooocus/issues/1394

**Comment by mannidm** [comment]
This is definitely related to https://github.com/lllyasviel/Fooocus/issues/1394

I am surpised this is not planned, as fooocus was always easier, better ai generation and so is this. Thanks for the info though

**Comment by mashb1t** [comment]
Fooocus core development is currently on halt and resumed in mid/end January, see https://github.com/lllyasviel/Fooocus/blob/main/update_log.md first line. Thank you for your understanding.
