### ISSUE TITLE
Config.txt within "anime" preset

### ISSUE THREAD

**Issue by Geo2D3D** [lllyasviel/Fooocus#1808]
Hi! Thanks for your cool Fooocus; 
I don't know whether it's either a bug or not, but I mention that fact here; so, please, forgive me if it's not a bug:
I noticed that the configuration set in the config.txt file works fine, is assumed, in the basic version of Fooocus, however not within the "anime" preset.

**Comment by mashb1t** [comment]
Please keep in mind that the preset config overrides the default config file, so all changes you did to config.txt for fields also present in the preset wil also have to be adjusted in the preset.

See https://github.com/lllyasviel/Fooocus/blob/main/modules/config.py#L89
Suggested keys for presets are mentioned here: https://github.com/lllyasviel/Fooocus/blob/main/modules/config.py#L323

Does this answer your question? If not, please provide the full content of your config file, preset file and the terminal log output and point out what does or does not work as expected. Thanks!

**Comment by Geo2D3D** [comment]
Hi! Thank you! I found the anime preset's config file. Please, close the ticket.

**Comment by NajiusMaximus** [comment]
> Hi! Thank you! I found the anime preset's config file. Please, close the ticket.

Where did you find it? Cant find it myself. :o

**Comment by mashb1t** [comment]
https://github.com/lllyasviel/Fooocus/blob/main/presets/anime.json

**Comment by Geo2D3D** [comment]
C:\Users\YOU\Documents\github\stable-diffusion-FOOOCUS\Fooocus\presets
Anyways, its being overwritten, therefore not a permanent preset :)

**Comment by NajiusMaximus** [comment]
@mashb1t @Geo2D3D Thank you so much!
