### ISSUE TITLE
Required: More aspect ratio plz

### ISSUE THREAD

**Issue by seeronline** [lllyasviel/Fooocus#181]
1920x1024
1920x768
1680x768
1344x768

768x1680
768x1920
1024x1980

**Comment by barepixels** [comment]
Having ratio value next to the numbers is handy
For example
1:1 2:3 4:5 16:19

**Comment by MoonRide303** [comment]
From what I know it's best (in terms of generated image quality) to stick to resolutions on which SDXL models were initially trained - they're listed in Appendix I of [SDXL paper](https://arxiv.org/abs/2307.01952). Other resolutions, on which SDXL models were not trained (like for example 512x512) might not look well.

**Comment by mashb1t** [comment]
Also see https://github.com/lllyasviel/Fooocus/pull/1617
