### ISSUE TITLE
Italian Translation ("it.json" attached)

### ISSUE THREAD

**Issue by GuidoBartoli** [lllyasviel/Fooocus#1812]
I translated main strings and style names into Italian and tried to create a pull request, but I received the following error:
```Can't create a new pull request: Push failed: remote: Permission to lllyasviel/Fooocus.git denied to GuidoBartoli. unable to access 'https://github.com/lllyasviel/Fooocus.git/': The requested URL returned error: 403```

However, I attach here the corresponding [it.json](https://github.com/lllyasviel/Fooocus/files/13863510/it.json) file, so the maintainers and reviewers can take a look at it here and decide if it can be included in the main branch.

**Comment by mashb1t** [comment]
You can not directly push to this repository as you do not have permissions to do so. Please create a fork, commit your translation and create a pull request from your fork to Fooocus main.
fyi translations are currently being collected in PRs with tag[ i18n](https://github.com/lllyasviel/Fooocus/pulls?q=is%3Apr+is%3Aopen+it+label%3Ai18n), so please follow the instructions above. Thanks!

**Comment by mashb1t** [comment]
Forking main is the default and the one you need 👍

**Comment by mashb1t** [comment]
perfect, thanks!
