### ISSUE TITLE
ImagePrompt/Faceswap usage skipping some prompts

### ISSUE THREAD

**Issue by bsormagec** [lllyasviel/Fooocus#1813]
When attempting to generate a full body image using a face image and the caption "Walking on the street," I am not always able to achieve the desired result using the FaceSwap method.
Input Image
![face](https://github.com/lllyasviel/Fooocus/assets/965219/ea021758-8e30-4d92-93d1-7f16ebc1984f)

Outputs
![test2](https://github.com/lllyasviel/Fooocus/assets/965219/e02cf9a1-8865-4412-bff5-e3bc2b4be41c)
![test1](https://github.com/lllyasviel/Fooocus/assets/965219/fdc1fd8b-a9af-4a62-80f5-044fd16b12f7)

**Comment by mashb1t** [comment]
You might be able to achieve better results using a different aspect ratio, e.g. for this case one with portrait aspect ratio (vertical) such as 7:9 or even lower width

**Comment by bsormagec** [comment]
Thanks @mashb1t i used your method its better.
