### ISSUE TITLE
Minor UI issue with image preview in Style when mouse hover at the bottom

### ISSUE THREAD

**Issue by GoldMath** [lllyasviel/Fooocus#1816]
**Describe the problem**
Hi, thanks for the image preview with **2.1.861**, the mouse over is a smart implantation to save space, I just noticed that at the bottom of the window the thumbnails don't dynamically move higher so it's not cutoff, see image:

Working well:
![2024-01-08 21_14_46](https://github.com/lllyasviel/Fooocus/assets/7282547/144e9e6a-2724-43f5-bb24-083338faa97d)
Cutoff:
![2024-01-08 21_10_30](https://github.com/lllyasviel/Fooocus/assets/7282547/e5682628-7312-4125-8080-a69e856d77bf)

Regards,

**Comment by poor7** [comment]
Not all images are available. for example, the Caricature style does not.

**Comment by mashb1t** [comment]
> Not all images are available. for example, the Caricature style does not.

This is fixed in PR https://github.com/lllyasviel/Fooocus/pull/1809 (still open)
