### ISSUE TITLE
Image prompt in inpainting

### ISSUE THREAD

**Issue by Pentracchiano** [lllyasviel/Fooocus#1818]
I'm loving Fooocus so much, I tried many UIs and engines for Stable Diffusion models and this is just great! It's not just simple and easy to use, but the extra functionality that it offers made it a must-have for me now. Thank you!

**Describe the idea you'd like**
I'd love if, apart from the possibility of providing a text input, we could also provide an image input as a reference for inpainting. A picture can save a thousand words, and sometimes it's just impossible to describe something precisely without a picture. I believe that something like this already exists in literature like the IP-Adapter, but I am not sure whether there are workflows compatible with the current implementation and model choices of Fooocus. Is this in your roadmap? It would be great!

**Comment by lllyasviel** [comment]
advanced -> dev tool -> control -> mix image prompt and inpainting

**Comment by Pentracchiano** [comment]
This is great. Didn't think the debug tools could unlock features. Thanks!
