### ISSUE TITLE
VRAM mode: normal and high

### ISSUE THREAD

**Issue by xsfunc** [lllyasviel/Fooocus#182]
Fooocus starts in normal mode with 3080 12GB vram and only 8gb used.
Ho to run in high vram mode?

**Comment by Phrixus2023** [comment]
edit Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_management.py file，in line 111

**Comment by xsfunc** [comment]
but when I change it and then start focus, It restore this file

**Comment by lllyasviel** [comment]
each model is about 7GB so even if high vram is enabled, you wont be able to load more models to GPU unless you have > 14GB vram

**Comment by xsfunc** [comment]
yes, check it know, normalvram works faster. thank you

**Comment by abomonov** [comment]
Hi, how did you change this parameter? I change it and it It restore this file. 
 if lowvram_available and total_vram <= 4096:
        print("Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram")
        set_vram_to = VRAMState.LOW_VRAM
