### ISSUE TITLE
Semantic Versioning Please

### ISSUE THREAD

**Issue by aiwillcoming** [lllyasviel/Fooocus#1828]
**Is your feature request related to a problem? Please describe.**

see 
https://semver.org/
https://semver.org/lang/zh-CN/

**Describe the idea you'd like**

**Comment by mashb1t** [comment]
+1, see https://github.com/lllyasviel/Fooocus/pull/1418#discussion_r1445404490

**Comment by mashb1t** [comment]
i do now have merge permissions, will make sure to work within SemVer boundaries. Can't speak for the other people though, hopefully we'll be able to align.

**Comment by mashb1t** [comment]
Closing as done, feel fre to use the SemVer releases from now on.

https://github.com/lllyasviel/Fooocus/releases
