### ISSUE TITLE
Not using GPU 

### ISSUE THREAD

**Issue by MasterRed0** [lllyasviel/Fooocus#1839]
Hi,
I work with GTX 1660 super 6gb RAM, 16gb regular (non GPU) RAM, and everything used to be fine until today. Whenever I want to launch Fooocus, the regular RAM works itself up like crazy, practically freezing my computer, even without generating anything
![Untitled](https://github.com/lllyasviel/Fooocus/assets/155583984/77c116d1-affa-4d1b-ab01-e43942798552)
(this is with Fooocus just being open)
All the while GPU usage is almost 0%
When launching the app, I noticed this log:
![Untitled1](https://github.com/lllyasviel/Fooocus/assets/155583984/5a1e61fc-d6e6-4942-8d82-8323d1e88aa7)
I thought it might have something to do with this issue, so I tried to edit the config log in such a way:
![image](https://github.com/lllyasviel/Fooocus/assets/155583984/c5cf16ee-77a1-4784-a3c1-be295a919366)
I know this is probably wrong, and if so, please tell me how I can enter --always-low-vram properly into the config text file.
(Yes I have read the manual but there is no mention of how to enter such a modification in there)
This issue started only after I've generated 2 inpaint results today, never happened before.
I have also read the system swap fix tutorial, and can safely report that there are no problems in that department.
Would you know of a fix to this issue? Is the "always offload vram" even the issue here? PLEASE help,
Thanks

**Comment by NaschBear** [comment]
Hi 
im apologize for my bad English

How can i Speed up Fooocus?

Fooocus is a fun Program and i like it to make things in it but i have this feeling Fooocus is on my Computer quit slow.
If i see how fast other can make it and that makes me a little bit Jealous and i ask "oh do you use the web version?" 
all say to me "no" so what make i wrong?

I use Low renders, more Anime/Comic Base Models and im still slow. for 4 pictures i need most 45 minutes 

what must i do?

How can i boost my GPU?

thanks for the answer ^^


my computer info: 

Processor: AMD Athlon(tm) X4 870K Quad Core Processor        3.90 GHz

RAM: 16 GB

NVIDIA GeForce GTX 1050 Ti

**Comment by MasterRed0** [comment]
Hi, just 1 more question:
How do I offload Fooocus?
Thanks again (Im new)

**Comment by mashb1t** [comment]
@NaschBear Your PC is on the brink of being able to run Fooocus, and as you're using a GTX 1050 (1XXX series "only marginally faster than CPU") and your CPU is also quite old (8+ years), there's not really mich you can do.

You have 2 options:
- upgrade your PC (Graphics card, but might be held back by DDR3 RAM, so i personally suggest getting a completely new PC)
- use a cloud provider such as Colab (free), see https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#colab. Basically a 2 click solution, just click the link, hit play and wait for it to be up & running in 2-3 minutes

@MasterRed0 Offloading is enabled by default if you haven't manually disable it

**Comment by NaschBear** [comment]
oh thank you for the fast answer ^^  

ok  in the time i buy a new computer i make  more stuff in Fooocus with Blender hihiihiii ^^

**Comment by MasterRed0** [comment]
Hey, 
sorry to drag you like this, 
After multiple PC restarts and trying everything you've said before, the issue still persists
As soon as I launch Fooocus, my system RAM usage skyrockets to 99% in the first few seconds, making my system barely responsive. The commands appearing at that time:
![image](https://github.com/lllyasviel/Fooocus/assets/155583984/fe3d10e8-e91f-4f7f-94f2-dc5337687c35)
Even when I tried to bear through it and generate a simple "kitten" prompt regardless, It gets stuck on this:
![image](https://github.com/lllyasviel/Fooocus/assets/155583984/1ebc01bb-0009-4c1d-b93e-bf0cd87fd137)
Not generating anything for 15 minutes, constantly lagging my PC,
This was not the case before and I don't know what went wrong,
Big Thanks in advance

**Comment by mashb1t** [comment]
> This was not the case before and I don't know what went wrong

@MasterRed0 Do you know which version worked "before" and when before was?
Please make sure you're only running one Fooocus instance at a time and keep in mind to close other programs using GPU.

**Comment by mashb1t** [comment]
> Inpainting uses more VRAM (in your case RAM or disk for offloading) as normal image inference, which is why this behaviour is normal and you couldn't use Fooocus at all without offloading. If you would have more VRAM, your GPU could keep the models loaded all the time and your image generation would be (much) faster.

As mentioned, inpainting uses more resources than normal image generation. There sadly is not really much you can do, you especially should not wait 40 minutes for one image 😐. 
Please check out Colab, where a T4 GPU instance can be used for free and is averaging 2-3 iterations per second, maybe less for inpainting, but still under a minute for quality performance.

**Comment by MasterRed0** [comment]
It's very weird because like I said, everything worked just fine previously, both normal generating and inpaiting taking only a couple minutes. It probably generated those 2 images in a short amount of time but just stopped for some reason. Now I can't generate even a single image. 
I will have to try Colab, but I would at least like to have the option to generate on my PC.
Nevertheless, a huge thank you for your time.

**Comment by rythmn1111** [comment]
Hey guys so i have installed fooocus and its working but i dont think it is using my 4gb 1650 nvidia card but it is only using CPU.. does anyone has solution for this?

**Comment by p1agnut** [comment]
@rythmn1111 Hi, maybe a little bit too late but you can with the `--gpu-device-id DEVICE_ID` argument. You can set arguments in your run.bat after `entry_with_update.py` and find your device ID via the 'nVidia Control Panel' under 'Help -> System Information' then scroll down the 'Details' list.
