### ISSUE TITLE
VAE problem?

### ISSUE THREAD

**Issue by E2GO** [lllyasviel/Fooocus#1840]
Is there a way to check VAE usage while inpainting in Fooocus? Or may be it's not even VAE but upscaler\inpaint issue. Strange question may be, but I see that images after inpainting or upscaling became more unsaturated and kind of bleached. 
Some additional info: all settings used the same as on generation while upscaling, 1 custom LORA used. Don't have such problem with A1111.
Heavy images below!
Original: 
![image](https://github.com/lllyasviel/Fooocus/assets/1776669/ae09af30-48af-4814-aabf-067445f7a1f2)
Upscaled with 2x: 
![image](https://github.com/lllyasviel/Fooocus/assets/1776669/2ee6d4b5-84bd-46fc-bcce-30e70a09ff44)
![image](https://github.com/lllyasviel/Fooocus/assets/1776669/370ef887-8050-42e7-bc18-c78e5cc73cdd)
Problem not only for this generations - here is just an example.
UPD: fast 2x upscale work ok.

**Comment by E2GO** [comment]
Also checkout inpainting bleach. Here I turned custom LORA to 0 just to check out if it's affecting results or not.
Masked content:
![image](https://github.com/lllyasviel/Fooocus/assets/1776669/6bb6551c-10ea-468b-8739-f4275aa7940a)
Result - it's visible that masked zone is desaturated and bleached:
![image](https://github.com/lllyasviel/Fooocus/assets/1776669/d1b3c0bb-01f5-4129-99bc-e53aefac8a9e)

**Comment by mashb1t** [comment]
Are you by chance using the "Extreme Speed" preset? Might have to do with that, it is prone to grey /wash out content..
If not, please make sure the issue still exists when opening a new tab of Fooocus (browser session debugging) and provide a link to the the LoRA you're using + your preset/config.

**Comment by E2GO** [comment]
It's surely not Extreme Speed - double checked it.
1. Completely restarted UI - loaded settings from log, upscale 2x - gives again bleached results.
2. Did another one experiment with default Juggernaut model, made new generations, no LORA's used - all works fine. Before I've used MOHAWK_v20 model and custom made own LORA.

Can I somehow choose vae for not default one Jug model? May be mohawk checkpoint don't have embedded one and it tries to use VAE somehow not suitable for it?... Just a thoughts - don't know how much it clever, sry))) Because usually I got such behavior (on sd1.5 especially) when VAE is not "right" one..

**Comment by E2GO** [comment]
Prompt is rather simple: 
{
"Prompt": "highly detailed mutant head and face\npostapocalyptic giant mutant, solo, mighty eerie look, army style, wuart style character creature concept",
"Negative Prompt": "deviantart, (hands:1.3), jpeg, child painting",
"Fooocus V2 Expansion": "highly detailed mutant head and face, glowing, sharp focus, highly intricate, cinematic light, clear, crisp, very coherent, symmetry, artistic, innocent, beautiful, novel, romantic, stunning, enhanced, color, epic, best, fine, fair, perfect, colorful, vivid, inspired, creative, complex, professional, amazing, gorgeous, attractive, full, awesome",
"Styles": "['Fooocus V2']",
"Performance": "Quality",
"Resolution": "(1024, 1024)",
"Sharpness": 2,
"Guidance Scale": 4,
"ADM Guidance": "(1.5, 0.8, 0.3)",
"Base Model": "MOHAWK_v20.safetensors",
"Refiner Model": "None",
"Refiner Switch": 0.5,
"Sampler": "dpmpp_2m_sde_gpu",
"Scheduler": "karras",
"Seed": 8200128622392930234,
"LoRA 1": "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
"LoRA 2": "Weapon_Wu_Conceptart_EGGOXL_v3.safetensors : 0.0",
"Version": "v2.1.862"
}

**Comment by lllyasviel** [comment]
hi some XL model author like those grey feeling and they use grey color vae baked in their models

so it is intentional by those XL model authors. and this is not related to us

Fooocus does not do anything to make it look grey. Also we make sure that all default settings/models do not have this problem.

**Comment by mashb1t** [comment]
> some XL model author like those grey feeling and they use grey color vae baked in their models

Thank you @lllyasviel for your insights. I only knew abut the noise offset for more black images (https://civitai.com/models/10391?modelVersionId=12354), but a grey offset might be used in this case.

@E2GO you can check if `MOHAWK_v20.safetensors` includes this or if your LoRA is based on another LoRA with this offset. If your LoRA was trained on the SDXL base model you can basically use it with every other SDXL model, so feel free to mix and match.

Closing this issue for now, feel free to let us know your findings!

**Comment by E2GO** [comment]
@lllyasviel @mashb1t Thanks for info! Will check mohawk model for sure about it. May be will try experiment with removing and adding other one vae))
FYI: My LORA extracted from finetuned model based on sd_xl_base_1.0_0.9vae checkpoint.

**Comment by E2GO** [comment]
Well, it's definitely VAE problem. I've baked sdxl vae into model and get those results:
![image](https://github.com/lllyasviel/Fooocus/assets/1776669/c148ea6a-b3bc-44c1-a558-954fe3942d16)

@mashb1t @lllyasviel Sorry for interrupting you, but I don't think it's the only one such model, so can I have a suggestion on implement some kind of selection of VAE used for model? Such as A1111 have function to choose which VAE to use - it can be automatic (used baked one or if it's not bakes - default) or forces (just choosing which one to use). 
From A1111: ![image](https://github.com/lllyasviel/Fooocus/assets/1776669/e6672d7a-3919-4b61-ab7c-f5927bc454bf)

**Comment by mashb1t** [comment]
VAE select has been implemented, please check out https://github.com/lllyasviel/Fooocus/pull/2867

**Comment by mashb1t** [comment]
merged to develop
