### ISSUE TITLE
Why can't this image be recognized when I upload it using the API?

### ISSUE THREAD

**Issue by a88852asdw** [lllyasviel/Fooocus#1851]
**After I converted a picture of a puppy to base64 format and uploaded it to the API, I wanted to change the picture. However, the uploaded picture was not detected, and the function of generating text from pictures was executed.**

`from gradio_client import Client
import base64

path = "D:/Test/Dog.png"
with open(path, "rb") as image_file:
    encoded_image = base64.b64encode(image_file.read()).decode("utf-8")

client = Client("http://localhost:0000/", serialize=False)
result = client.predict(
    "",  # str in 'parameter_10' Textbox component
    "",  # str in 'Negative Prompt' Textbox component
    ["Fooocus V2", "Fooocus Sharp", "Fooocus Enhance"],  # List[str] in 'Selected Styles' Checkboxgroup component
    "Speed",  # str in 'Performance' Radio component
    "1152×896",  # str in 'Aspect Ratios' Radio component
    1,  # int | float (numeric value between 1 and 32)in 'Image Number' Slider component
    "123",  # str in 'Seed' Textbox component
    2,  # int | float (numeric value between 0.0 and 30.0)in 'Image Sharpness' Slider component
    7,  # int | float (numeric value between 1.0 and 30.0)in 'Guidance Scale' Slider component
    "juggernautXL_version6Rundiffusion.safetensors",
    # str (Option from: ['juggernautXL_version6Rundiffusion.safetensors', 'sd_xl_base_1.0_0.9vae.safetensors', 'sd_xl_refiner_1.0_0.9vae.safetensors'])in 'Base Model (SDXL only)' Dropdown component
    "None",
    # str (Option from: ['None', 'juggernautXL_version6Rundiffusion.safetensors', 'sd_xl_base_1.0_0.9vae.safetensors', 'sd_xl_refiner_1.0_0.9vae.safetensors'])in 'Refiner (SDXL or SD 1.5)' Dropdown component
    0.1,  # int | float (numeric value between 0.1 and 1.0)in 'Refiner Switch At' Slider component
    "None",
    # str (Option from: ['None', 'sdxl_lcm_lora.safetensors', 'sd_xl_offset_example-lora_1.0.safetensors'])in 'LoRA 1' Dropdown component
    -2,  # int | float (numeric value between -2 and 2)in 'Weight' Slider component
    "None",
    # str (Option from: ['None', 'sdxl_lcm_lora.safetensors', 'sd_xl_offset_example-lora_1.0.safetensors'])in 'LoRA 2' Dropdown component
    -2,  # int | float (numeric value between -2 and 2)in 'Weight' Slider component
    "None",
    # str (Option from: ['None', 'sdxl_lcm_lora.safetensors', 'sd_xl_offset_example-lora_1.0.safetensors'])in 'LoRA 3' Dropdown component
    -2,  # int | float (numeric value between -2 and 2)in 'Weight' Slider component
    "None",
    # str (Option from: ['None', 'sdxl_lcm_lora.safetensors', 'sd_xl_offset_example-lora_1.0.safetensors'])in 'LoRA 4' Dropdown component
    -2,  # int | float (numeric value between -2 and 2)in 'Weight' Slider component
    "None",
    # str (Option from: ['None', 'sdxl_lcm_lora.safetensors', 'sd_xl_offset_example-lora_1.0.safetensors'])in 'LoRA 5' Dropdown component
    -2,  # int | float (numeric value between -2 and 2)in 'Weight' Slider component
    True,  # bool in 'Input Image' Checkbox component
    "",  # str in 'parameter_85' Textbox component
    "Upscale (2x)",  # str in 'Upscale or Variation:' Radio component
    "data:image/png;base64," + encoded_image,
    # str (filepath or URL to image)in 'Drag above image to here' Image component
    ["Left"],  # List[str] in 'Outpaint Direction' Checkboxgroup component
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==",
    # str (filepath or URL to image)in 'Drag inpaint or outpaint image to here' Image component
    "chosen_style_description",  # str in 'Inpaint Additional Prompt' Textbox component
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==",
    # str (filepath or URL to image)in 'Mask Upload' Image component
    # ---------图像控制---------
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==",
    # str (filepath or URL to image)in 'Image' Image component
    0,  # int | float (numeric value between 0.0 and 1.0)in 'Stop At' Slider component
    0,  # int | float (numeric value between 0.0 and 2.0)in 'Weight' Slider component
    "ImagePrompt",  # str in 'Type' Radio component
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==",
    # str (filepath or URL to image)in 'Image' Image component
    0,  # int | float (numeric value between 0.0 and 1.0)in 'Stop At' Slider component
    0,  # int | float (numeric value between 0.0 and 2.0)in 'Weight' Slider component
    "ImagePrompt",  # str in 'Type' Radio component
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==",
    # str (filepath or URL to image)in 'Image' Image component
    0,  # int | float (numeric value between 0.0 and 1.0)in 'Stop At' Slider component
    0,  # int | float (numeric value between 0.0 and 2.0)in 'Weight' Slider component
    "ImagePrompt",  # str in 'Type' Radio component
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==",
    # str (filepath or URL to image)in 'Image' Image component
    0,  # int | float (numeric value between 0.0 and 1.0)in 'Stop At' Slider component
    0,  # int | float (numeric value between 0.0 and 2.0)in 'Weight' Slider component
    "ImagePrompt",  # str in 'Type' Radio component
    fn_index=33
)
print(result)
`

**This code is to upload the image {"data:image/png;base64," + encoded_image,}. Is there any error? Thank you very much.**

**Comment by mashb1t** [comment]
Closing as stale. Feel free to start a discussion if needed.
