### ISSUE TITLE
Web UI starts lagging behind on larger image counts

### ISSUE THREAD

**Issue by manabreak** [lllyasviel/Fooocus#1854]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
When doing larger batches via the web UI (e.g. 64 and up), the preview and generated images view starts lagging behind. After a while, it stops showing the step-by-step generation of the image, and after a while, the preview image starts lagging behind, showing an image that has already been generated multiple images ago. To lesser extent, the preview starts lagging around the 30th image or so. With a batch of 300 images, the preview was showing about the 100th image while the output folder already had the 150th image or so.

This isn't a big deal, other than after the generation is complete and all images are done, the UI still keeps processing the previews of the images, pretty much doubling the time it takes to gain control of the UI and start with the next generation. Usually it's faster to kill the process and restart, but this means losing all configurations that were done on the UI.

The generation works correctly, churning out images as usual, it's just the web UI that lags behind.

As per specs, I'm running RTX 3080 (10 GB VRAM), 32 GB RAM, 48 GB swap. 

**Full Console Log**
Nothing relevant in the console.

**Comment by mashb1t** [comment]
@manabreak this is already covered in a PR, which still has to be reviewed.
@lllyasviel please consider evaluating https://github.com/lllyasviel/Fooocus/pull/1013 when you have time, there are more and more duplicate issues popping up lately.

**Comment by poor7** [comment]
Perhaps disabling preview will somehow help temporarily solve this problem.
Advanced -> Developer Debug Mode -> Disable Preview

**Comment by mashb1t** [comment]
@poor7 sadly this is not going to help as only the temp  step preview is then hidden, but not the result gallery, which causes the issues.
