### ISSUE TITLE
Filtering SDXL models

### ISSUE THREAD

**Issue by ekinertac** [lllyasviel/Fooocus#1866]
**Is your feature request related to a problem? Please describe.**
We sohuld be able to filtering SDXL models than Sd models. Most of us keep their models in the single file to use them in multiple clients.

**Describe the idea you'd like**
 If we read `.safetensors` meta data we can filter them in the UI.

i've added a pretty low effort filtering to the `modules/config.py` file the code but there must be a better way to do it.

```diff
def get_model_filenames(folder_path, name_filter=None):
-    return get_files_from_folder(folder_path, ['.pth', '.ckpt', '.bin', '.safetensors', '.fooocus.patch'], name_filter)
+    model_files = get_files_from_folder(folder_path, ['.pth', '.ckpt', '.bin', '.safetensors', '.fooocus.patch'], name_filter)
+    sdxl_models = []
+
+    for file in model_files:
+        if "xl" in file or "XL" in file:
+            sdxl_models.append(file)
+
+    return sdxl_models
```

**Comment by eddyizm** [comment]
Seems very reasonable. I might add that we log what is filtered out so people can see which ones are not sdxl incase they are new to the tool and can't figure out why it's not loading all their models.

**Comment by mashb1t** [comment]
Already had the same idea a while ago (https://github.com/mashb1t/Fooocus/pull/2), but please check https://github.com/lllyasviel/Fooocus/issues/460 (https://github.com/lllyasviel/Fooocus/issues/460#issuecomment-1873918219) for further information.
Name filtering isn't the way to go as not all models do use xl / XL in their name, e.g. the [realistic preset](https://github.com/lllyasviel/Fooocus/blob/main/presets/realistic.json) model  is called realisticStockPhoto_v10.safetensors.

**Comment by JulienZLQ** [comment]
@mashb1t It seems that the WEBUI of SD can tell whether LORA is 1.5 or xl according to the selected cktp. Does cktp have a similar identification method?

**Comment by mashb1t** [comment]
I'm currently not aware of how A1111 currently implements the model checking

**Comment by ekinertac** [comment]
checked their code, they are using metdata of Lora files to understand which Lora can bue used on Sd or SDXL.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/cf2772fab0af5573da775e7437e6acdca424f26e/extensions-builtin/Lora/network.py#L58-L66

i've tried to run the same code with little edits, most of the model files I have doesn't have metadata. including juggernaut. so our only option is name filtering but as @mashb1t said some models doesn't include `xl` or `sdxl` in their name. 

it's currently a dead end

**Comment by JulienZLQ** [comment]
This is a pity. It seems that this can only be used as a semi-automatic function. The files must be sorted and renamed to be effective. It is a very private state.

**Comment by ekinertac** [comment]
couldn't find a way to add grouping like `optgroup` to the gradio dropdown, we can show the files has `xl` keyword first then the rest

**Comment by barepixels** [comment]
Just make Fooocus able to read subfolders

This is how it looks in my A111 and Comfyui

SDXL/blahblah.safetensors
SDXL/blahblah.safetensors
SDXL/blahblah.safetensors
SDXL/blahblah.safetensors
SD15/blahblah.safetensors
SD15/blahblah.safetensors
SD15/blahblah.safetensors
SD15/blahblah.safetensors

Do the same for Loras

**Comment by mashb1t** [comment]
Fooocus can already read subfolders, feel free to adjust the folder structure of your models/loras accordingly!

**Comment by mashb1t** [comment]
Closing as not planned
