### ISSUE TITLE
Stopped working after latest update

### ISSUE THREAD

**Issue by sdeepak88** [lllyasviel/Fooocus#1871]
![console](https://github.com/lllyasviel/Fooocus/assets/32766228/e028ff14-2da5-430e-9835-b837f83cf307)
![webUI](https://github.com/lllyasviel/Fooocus/assets/32766228/c46dcccf-8d98-4983-b5e5-85350092eb28)
The software was running perfectly until yesterday (10/1/24) but somehow when I load it up today morning (11/1/24), it is all messed up. It might have got an update and something happened. 
One screenshot shows console, which now not opening the webUI on its own. So, I opened the link generated after software run.
Second screenshot shows what happened I click on generate after giving a prompt. It just keeps running something and loading in the background nothing works for hours. Not sure what happened but please check.

**Comment by lllyasviel** [comment]
no update these days.
your case looks like you do not have enough free disk space since that "yesterday"
clean the disk and make sure that each drive has at least 40gb free space
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

**Comment by sdeepak88** [comment]
> no update these days. your case looks like you do not have enough free disk space since that "yesterday" clean the disk and make sure that each drive has at least 40gb free space https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

But I have not added anything in one day. Earlier C drive had about 15 GB space and still the same. Also tried removing few things from my C drive but still same issue.

**Comment by mashb1t** [comment]
Please make sure to clean up your drive and monitor the free space when running Fooocus. Please be advised to do a cleanup for 30-40GB free space on your drive to ensure image generation with less/no issues.
