### ISSUE TITLE
How many models that fooocus could install

### ISSUE THREAD

**Issue by ykhasia** [lllyasviel/Fooocus#1873]
Does the fooocus could also install various models from civitai? justl similar like stable diffusion ？

**Comment by mashb1t** [comment]
Fooocus is backed by Stable Diffusion, so feel free to use all the SDXL models from Civitai or HuggingFace. You just have to make sure that they are SDXL for inference and can only be 1.5 for refiner.

**Comment by ykhasia** [comment]
ok. thanks very much.

**Comment by yaranbarzi** [comment]
> Does the fooocus could also install various models from civitai? justl similar like stable diffusion ？

Yes, you can add various models from Civitai to Fooocus.
