### ISSUE TITLE
Win11 installation fails on latest build with pygit2 (no module found)

### ISSUE THREAD

**Issue by Kameelv** [lllyasviel/Fooocus#1875]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
Windows 11 installation on the latest build fails with an error mentioning no pygit2.

**Full Console Log**

D:\ComfyUI>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Update failed.
No module named 'pygit2.ffi'
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Traceback (most recent call last):
  File "D:\ComfyUI\python_embeded\lib\site-packages\numpy\__init__.py", line 124, in <module>
    from numpy.__config__ import show as show_config
ModuleNotFoundError: No module named 'numpy.__config__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ComfyUI\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "D:\ComfyUI\Fooocus\launch.py", line 24, in <module>
    from modules.config import path_checkpoints, path_loras, path_vae_approx, path_fooocus_expansion, \
  File "D:\ComfyUI\Fooocus\modules\config.py", line 7, in <module>
    import modules.sdxl_styles
  File "D:\ComfyUI\Fooocus\modules\sdxl_styles.py", line 5, in <module>
    from modules.util import get_files_from_folder
  File "D:\ComfyUI\Fooocus\modules\util.py", line 1, in <module>
    import numpy as np
  File "D:\ComfyUI\python_embeded\lib\site-packages\numpy\__init__.py", line 129, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
**

**Comment by Kameelv** [comment]
Yes that's right.

**Comment by mashb1t** [comment]
Will check this tomorrow

**Comment by mashb1t** [comment]
@Kameelv no issues for me. Please make sure to use the official installation instructions and/or provide further information about what you did before Python began giving you the errors.

Fresh install from latest 7z file- no errors:
![image](https://github.com/lllyasviel/Fooocus/assets/9307310/bc6c4a15-2f16-43d6-84ff-021169572435)

**Comment by mashb1t** [comment]
Haven't heard back from you. Is this still relevant?

**Comment by Kameelv** [comment]
Hi, this works without any problems now.

It seems to be a timing issue, if you execute run.bat too quickly after
win11 has booted, it fails. Perhaps a needed windows service isn't up? Or
another application is preventing it from working properly?? Either way, if
you wait a minute before running it, there's no problem.

Thanks for following up.
