### ISSUE TITLE
Set VRAM , Foocus , 'object not found - no match for id

### ISSUE THREAD

**Issue by alihaidersheikh** [lllyasviel/Fooocus#1876]
![123](https://github.com/lllyasviel/Fooocus/assets/124422122/398573e2-8e99-481c-ae77-e13c7575e14d)

Please Help Me to fix this issue

**Comment by bruno-c** [comment]
There are troubleshooting instructions here https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md that may help.

**Comment by mashb1t** [comment]
Most likely a swap misconfiguration or too little VRAM to fully load and contain the model + maybe also too little RAM to also keep it there. Please check the troubleshooting guide.
