### ISSUE TITLE
Nvidia driver error on macbook m1

### ISSUE THREAD

**Issue by ricinthesky** [lllyasviel/Fooocus#1877]
hi folks, everything was fine till today with colab then suddenly i am getting this nvidia drivers missing.
My system is a macbook air m1 with sonoma 14.2.1.
Any ideas about how to fix this? Dis anything change from foooocus end?
Cheers

**Comment by mashb1t** [comment]
Just making sure: did you use Colab (cloud) until now or your Macbook?
If Colab: please make sure you're using a T4 instance or similar instance equipped with a GPU, not TPU and also not compute only!
If Macbook: did you follow the setup guide https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#mac ?

**Comment by ricinthesky** [comment]
I was usisng colab. After some hours from my previous post, started to work again without doing anything from my side so i guess there were some updates going on from server end. Wasn't working always smoothly, some hang ups but was mostly delivering.

**Comment by mashb1t** [comment]
It is possible that your task or environment got paused / canceled due to inactivity. In this case, you can just click the play button on your colab notebook again.
