### ISSUE TITLE
Is there any way could self-define the image size ?

### ISSUE THREAD

**Issue by ykhasia** [lllyasviel/Fooocus#1878]
Is there any way could self-define the image size ?
such as 1024 X 768 or 800 X 600 or 720 X 1280 etc...
thanks in advance.

**Comment by bruno-c** [comment]
You could do for a "one time" thing this way

- Enable the advanced settings
- Go to advanced tab
- Under the debug tools tab, there is a set of sliders to override the resolution

![image](https://github.com/lllyasviel/Fooocus/assets/50042/da699073-f844-4af9-9f68-42ca5f954e98)

Or you can add the resolutions you need to your custom configuration file (`config.txt), under `available_aspect_ratios` but keep in mind the resolutions listed are the optimal ones for SDXL, you might be better off using them and then editing the image to fit the resolution you need.

**Comment by mashb1t** [comment]
see also https://github.com/lllyasviel/Fooocus/pull/1617 for SDXL resolutions

**Comment by ykhasia** [comment]
> see also #1617 for SDXL resolutions

got it. thank you🤙🤙🤙

**Comment by rafstahelin** [comment]
can i change it in one of the python scirpts for permanent? 

I tried adding it to the config.txt file and nothing happend after restarting:
"available_aspect_ratios : "1024x1280",

is this wrong?

**Comment by mashb1t** [comment]
solved via https://github.com/lllyasviel/Fooocus/issues/2076#issuecomment-1934705215
