### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by techmastercloud** [lllyasviel/Fooocus#1880]
How to uninstall Foocus from Windows?

**Comment by bruno-c** [comment]
Just delete the folder?

**Comment by techmastercloud** [comment]
folders the installation? There are other folders?

**Comment by bruno-c** [comment]
No, unless you've changed the folder configuration there are no other folders, everything is in that folder.

**Comment by CosmosVoy** [comment]
There is also copy of the generated image in here: `\AppData\Local\Temp\gradio\`
by its name, i guess that other StableDiffusion project has their images copied there too.

**Comment by techmastercloud** [comment]
thanks
