### ISSUE TITLE
Could the dependency on opencv be limited to the headless variant?

### ISSUE THREAD

**Issue by rsl8** [lllyasviel/Fooocus#1882]
It seems to work fine in SageMaker Studio Lab, where the full version requires extra dependencies: https://stackoverflow.com/questions/70553701/couldnt-import-cv2-in-sagemaker-studio-lab

Unfortunately, Fooocus reinstalls what it finds in `requirements_versions.txt` everytime it starts.

**Comment by mashb1t** [comment]
Haven't checked yet but can this be solved by using opencv-python-headless without causing any issues?

**Comment by mashb1t** [comment]
Just checked, feel free to use `opencv-contrib-python-headless==4.8.0.74` as a replacement on your local installation.
I'm not into opencv, but if you are you can also create a PR after testing this version.
