### ISSUE TITLE
Inpaint with image prompt

### ISSUE THREAD

**Issue by hclivess** [lllyasviel/Fooocus#1885]
Would it be difficult to extend functionality of the inpaint feature, which is great at fixing details, with image prompts? It is currently very hard to get details in for which the model was not trained for and this could give it good guidance on what is wanted/needed. Sort of like a prompt within an already existing image.

**Comment by docppp** [comment]
![obraz](https://github.com/lllyasviel/Fooocus/assets/29142757/fd5a2eed-f2b5-445d-8e52-81aa7150e2a8)
How about Mixing Image Prompt and Inpaint in Developer Debug Mode?

**Comment by mashb1t** [comment]
Mixing should serve you well here. Feel free to close this issue if this answers your question.

**Comment by hclivess** [comment]
Exactly what I was looking for, thanks.
