### ISSUE TITLE
Erase/Remove Objects - The Right Way

### ISSUE THREAD

**Issue by ikmalsaid** [lllyasviel/Fooocus#1887]
Hi, here's what I got when trying to erase something using the modify objects function.

![Fooocus-2-1-862](https://github.com/lllyasviel/Fooocus/assets/35127268/b4bc5a50-6039-4766-b8bd-60038753489a)

As you can see, I'm trying to figure out the right way to remove objects. Any help is appreciated. Thank you!

**Comment by mashb1t** [comment]
please do not use natural language in the inpaint additional prompt, just write what you want to have ("plain white background" or similar)

**Comment by ikmalsaid** [comment]
> please do not use natural language in the inpaint additional prompt, just write what you want to have ("plain white background" or similar)

Thanks! It's definitely working!

![Fooocus-2-1-862 (1)](https://github.com/lllyasviel/Fooocus/assets/35127268/6a57a9e3-42fc-4ca3-a47f-5b3835393f7a)
