### ISSUE TITLE
 uninstall fooocus on a Mac 

### ISSUE THREAD

**Issue by djfamoso** [lllyasviel/Fooocus#1890]
what's the proper way to uninstall fooocus on a Mac  I installed but can't get it to work so just want to uninstall everything it installed the proper way

**Comment by mashb1t** [comment]
There are currently no official uninstallation instructions, but you can simply follow the installation steps in reverse order (see https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#mac)
=> remove conda env, then delete the folder, but olease check for yourself

**Comment by djfamoso** [comment]
thank you for your response but do you think you can tell me the entire
command
