### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.expansion'

### ISSUE THREAD

**Issue by DecadentCode** [lllyasviel/Fooocus#1891]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
It's not generating anything, I assume due to the ModuleNotFound error I'm encountering.

**Full Console Log**
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--directml']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.831
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Using directml with device:
Total VRAM 1024 MB, total RAM 32648 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: privateuseone
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --attention-split
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\Andrew\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "C:\Users\Andrew\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 12, in <module>
    from modules.expansion import FooocusExpansion
ModuleNotFoundError: No module named 'modules.expansion'

**Comment by mashb1t** [comment]
please make sure you followed the official installation instructions for Windows (AMD) https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windowsamd-gpus and you're using the embedded python version, not the one on your system.

**Comment by DecadentCode** [comment]
I didn't initially notice the AMD instructions until after running it once. Now even when I run the AMD adjusted .bat, it gives that modules error. How do I use the embedded python version?

**Comment by mashb1t** [comment]
I assume you're already using the embedded Python, but please double check your run.bat includes ``.\python_embeded\python.exe -s Fooocus\entry_with_update.py``. THis is not the issue.

You're using an old Fooocus version (yours is 2.1.831 vs current 2.1.862), please update + check if line 10 is like this 
```
from extras.expansion import FooocusExpansion
```
The important thing to notice is that FooocusExpansion has to be imported from extras, not modules. You might have merge conmflicts / code changes, which is why the auto update doesn't work correctly. You can also update the code by executing `git pull` to pull the repository inside your Fooocus folder.

Please provide an update about the situation after updating the code.

**Comment by mashb1t** [comment]
@DecadentCode  were you able to run Fooocus on your machine after updating or do you require further assistance?

**Comment by DecadentCode** [comment]
I just went to redownload and the download link is still to 2.1.861

**Comment by mashb1t** [comment]
The zip file downloads version `Fooocus_win64_2-1-831.7z`, but should self-updatea to the latest version on start. If this is not the case, please open a terminal in the Fooocus subdir and execute the command `git pull` + start Fooocus afterwards.

**Comment by DecadentCode** [comment]
You're correct, it did update itself, and it is working correctly now. Thank you very much!
