### ISSUE TITLE
Issue with Indian woman images

### ISSUE THREAD

**Issue by sdeepak88** [lllyasviel/Fooocus#1893]
Dear team,
Your tool is awesome. However, whenever I try to generate an image of an Indian woman, the output image has tons of jewellery and head mark on the woman. Even if I put jewellery and head mark in negative prompt, they still show up on output images. Kindly look into it so the software can generate more variety and more realistic images of modern Indian woman.

**Comment by xhoxye** [comment]
This is my attempt.
![QQ截图20240112170245](https://github.com/lllyasviel/Fooocus/assets/129571231/ee8b3bad-bafe-4506-89c0-63d608cadd29)

`{
"Prompt": "\u0939\u093f\u0928\u094d\u0926\u0940 \u0939\u093f\u0902\u0926\u0940, woman, OOTD, modern Everyday casual clothing, city street",
"Negative Prompt": "(traditional clothing, jewellery , earrings, head mark:1.5)",
"Fooocus V2 Expansion": "\u0939\u093f\u0928\u094d\u0926\u0940 \u0939\u093f\u0902\u0926\u0940, woman, OOTD, modern Everyday casual clothing, city street, elegant, highly detailed, professional composition, magical atmosphere, sharp focus, quality, very coherent, magic, beautiful, epic, stunning, gorgeous, intricate detail, clear, amazing, cinematic",
"Styles": "['Fooocus V2', 'Fooocus Enhance', 'Fooocus Sharp']",
"Performance": "Speed",
"Resolution": "(896, 1152)",
"Sharpness": 2,
"Guidance Scale": 4,
"ADM Guidance": "(1.5, 0.8, 0.3)",
"Base Model": "juggernautXL_version6Rundiffusion.safetensors",
"Refiner Model": "None",
"Refiner Switch": 0.5,
"Sampler": "dpmpp_2m_sde_gpu",
"Scheduler": "karras",
"Seed": 8407922742211695823,
"LoRA 1": "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
"Version": "v2.1.861"
}`

**Comment by sdeepak88** [comment]
> This is my attempt. ![QQ截图20240112170245](https://private-user-images.githubusercontent.com/129571231/296184510-ee8b3bad-bafe-4506-89c0-63d608cadd29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTA5MDMsIm5iZiI6MTcwNTA1MDYwMywicGF0aCI6Ii8xMjk1NzEyMzEvMjk2MTg0NTEwLWVlOGIzYmFkLWJhZmUtNDUwNi04OWMwLTYzZDYwOGNhZGQyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwOTEwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmFlZGQwNzg4ZTIwZWYyNzE2NzUyM2RiZTkwZWYwZWE3OTU5OWRiMWQyM2E1ZGMyYzVlN2MzMDI1MWZlOGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.od-F5NYW-WsgYxlmebv_f1HM0KwqyQCHXR5lUu0wEys)
> 
> `{ "Prompt": "\u0939\u093f\u0928\u094d\u0926\u0940 \u0939\u093f\u0902\u0926\u0940, woman, OOTD, modern Everyday casual clothing, city street", "Negative Prompt": "(traditional clothing, jewellery , earrings, head mark:1.5)", "Fooocus V2 Expansion": "\u0939\u093f\u0928\u094d\u0926\u0940 \u0939\u093f\u0902\u0926\u0940, woman, OOTD, modern Everyday casual clothing, city street, elegant, highly detailed, professional composition, magical atmosphere, sharp focus, quality, very coherent, magic, beautiful, epic, stunning, gorgeous, intricate detail, clear, amazing, cinematic", "Styles": "['Fooocus V2', 'Fooocus Enhance', 'Fooocus Sharp']", "Performance": "Speed", "Resolution": "(896, 1152)", "Sharpness": 2, "Guidance Scale": 4, "ADM Guidance": "(1.5, 0.8, 0.3)", "Base Model": "juggernautXL_version6Rundiffusion.safetensors", "Refiner Model": "None", "Refiner Switch": 0.5, "Sampler": "dpmpp_2m_sde_gpu", "Scheduler": "karras", "Seed": 8407922742211695823, "LoRA 1": "sd_xl_offset_example-lora_1.0.safetensors : 0.1", "Version": "v2.1.861" }`

So, what's that Hindi, hindi in the prompt? How do you get it? Those negative prompts helped me.

**Comment by xhoxye** [comment]
The use of "from Indian" should be the same.

**Comment by poor7** [comment]
Fooocus understands only English words.

**Comment by sdeepak88** [comment]
Worked a couple of times but as soon as I tried changing something it went back to the same thing. I don't know why it has to put heavy jewellery all the time. I gave a simple prompt "An young Indian woman enjoying a beautiful evening" and gave all the negative prompts but not much change. result attached here
![Uploading Firefox_Screenshot_2024-01-12T10-55-07.646Z.png…]()

**Comment by sdeepak88** [comment]
Worked a couple of times but as soon as I tried changing something it went back to the same thing. I don't know why it has to put heavy jewellery all the time. I gave a simple prompt "An young Indian woman enjoying a beautiful evening" and gave all the negative prompts but not much change. results attached here
![Firefox_Screenshot_2024-01-12T10-55-07 646Z](https://github.com/lllyasviel/Fooocus/assets/32766228/ece75395-eed8-4664-a59b-6e66376dd41b)
![Firefox_Screenshot_2024-01-12T10-57-24 480Z](https://github.com/lllyasviel/Fooocus/assets/32766228/f838e4f4-33cc-4230-ab06-f51574810a94)

**Comment by poor7** [comment]
You removed the brackets () and thereby reduced the weight.  

Correctly like this: (traditional clothing, jewellery , earrings, head mark:1.5)

**Comment by xhoxye** [comment]
> Fooocus understands only English words.


In fact, there is no need for focus to recognize non-English semantics. The use of non-English words is to tell focus that this person is from here.

**Comment by sdeepak88** [comment]
> You removed the brackets () and thereby reduced the weight.
> 
> Correctly like this: (traditional clothing, jewellery , earrings, head mark:1.5)

With or without brackets, it's the same thing

**Comment by sdeepak88** [comment]
Fooocus just loves putting earrings and head marks

**Comment by mashb1t** [comment]
> Fooocus doesn't care. He doesn't understand non-English words.

This is not correct.
Prompts written in other languages might also work because the training data apparently had samples with other languages as description. You can read more about the training dataset here: https://clarifai.com/stability-ai/stable-diffusion-2/models/stable-diffusion-xl

Excerpt:
> The dataset consists of 1.8 million images from the ImageNet dataset and 1.2 million images from the OpenImages dataset.

https://www.image-net.org/about.php
https://storage.googleapis.com/openimages/web/index.html

**Comment by mashb1t** [comment]
@sdeepak88 closing this issue as this is not an issue of Fooocus but a potential bias in the SDXL training dataset and this can be mitigated by using a negative prompt with prompt weights.
Feel free to continue the discussion if needed though.

**Comment by sdeepak88** [comment]
> @sdeepak88 closing this issue as this is not an issue of Fooocus but a potential bias in the SDXL training dataset and this can be mitigated by using a negative prompt with prompt weights. Feel free to continue the discussion if needed though.

The issue is not resolved. Negative prompts don't help much either. I shared this so the inherent bias could be removed in future releases. However, the whole discussion went into whether fooocus understands foreign words or not. Fooocus at least puts a head mark and earrings even if you are prompting for a bikini model on a beach. Once we remove Indian and put any other country name then it works fine. Negative prompts work once in a hundred generations.

**Comment by mashb1t** [comment]
@sdeepak88 There's not really much Fooocus can do to influence the bias of the training data of SDXL in its core code, but individual users can. Fooocus is the wrapper around SDXL/SD in general and you can configure it to use specific models fine-tuned for specific purposes.
You will experience the same behavior / bias in every other WebUI using SDXL as well.
Possibilities to modify weights and prevent potential biases are:
- using a LoRA (please check if some for indian woman exist in civitai.com)
- using an embedding (lowest impact, but may be helpful)
- using another base model specific for this purpose (highest impact, potentially also found on civitai.com)
- using negative prompts with high prompt weight

Examples you can try can be found e.g. here:
- https://civitai.com/search/models?sortBy=models_v5&query=indian
- https://civitai.com/search/models?sortBy=models_v5&query=indian%20woman

I hope this helps you to understand that this is not an issue of Fooocus and in resolving the inconveniences you're experiencing!

**Comment by poor7** [comment]
```
{
"Prompt": "young Indian woman enjoying a beautiful evening",
"Negative Prompt": "(bindi, jewelry:1.5)",
"Fooocus V2 Expansion": "",
"Styles": "[]",
"Performance": "Speed",
"Resolution": "(1152, 896)",
"Sharpness": 2,
"Guidance Scale": 4,
"ADM Guidance": "(1.5, 0.8, 0.3)",
"Base Model": "juggernautXL_version6Rundiffusion.safetensors",
"Refiner Model": "None",
"Refiner Switch": 0.5,
"Sampler": "dpmpp_2m_sde_gpu",
"Scheduler": "karras",
"Seed": 1234,
"LoRA 1": "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
"Version": "v2.1.862"
}
```
Seed:1234
![2024-01-13_08-33-38_5182](https://github.com/lllyasviel/Fooocus/assets/154618384/146d216e-621e-4ba0-abf0-e7333f8bcf06)
Seed:5722215484075938716
![2024-01-13_08-34-23_2858](https://github.com/lllyasviel/Fooocus/assets/154618384/2d33255a-d289-4f03-b966-702e3777490a)
Seed:4565953615806594921
![2024-01-13_08-35-03_7528](https://github.com/lllyasviel/Fooocus/assets/154618384/a90991f0-9827-4bd1-a43a-a84ebe9ebc96)
Seed:2997314892326416773
![2024-01-13_08-36-56_2826](https://github.com/lllyasviel/Fooocus/assets/154618384/dce6aea2-95f2-4db8-9512-c700ca3d8c4e)

There is a small problem with the styles enabled by default: 'Fooocus V2', 'Fooocus Enhance', 'Fooocus Sharp', but if you disable them there are no problems.

**Comment by sdeepak88** [comment]
> ```
> {
> "Prompt": "young Indian woman enjoying a beautiful evening",
> "Negative Prompt": "(bindi, jewelry:1.5)",
> "Fooocus V2 Expansion": "",
> "Styles": "[]",
> "Performance": "Speed",
> "Resolution": "(1152, 896)",
> "Sharpness": 2,
> "Guidance Scale": 4,
> "ADM Guidance": "(1.5, 0.8, 0.3)",
> "Base Model": "juggernautXL_version6Rundiffusion.safetensors",
> "Refiner Model": "None",
> "Refiner Switch": 0.5,
> "Sampler": "dpmpp_2m_sde_gpu",
> "Scheduler": "karras",
> "Seed": 1234,
> "LoRA 1": "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
> "Version": "v2.1.862"
> }
> ```
> 
> Seed:1234 ![2024-01-13_08-33-38_5182](https://private-user-images.githubusercontent.com/154618384/296439907-146d216e-621e-4ba0-abf0-e7333f8bcf06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTc4MTgsIm5iZiI6MTcwNTI5NzUxOCwicGF0aCI6Ii8xNTQ2MTgzODQvMjk2NDM5OTA3LTE0NmQyMTZlLTYyMWUtNGJhMC1hYmYwLWU3MzMzZjhiY2YwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwNTQ1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzMxMjE1Y2M3OGM2OWNmZDM5NWUyNTFhZDNmMjBiYTRmMzFlM2RlZTAxZmQ1ZDkyMWM5MmU0YjgxMzFjODUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WjkPka9t1me2Ix_u78QG8hqG-9S84lSBX1xIqTxLoKY) Seed:5722215484075938716 ![2024-01-13_08-34-23_2858](https://private-user-images.githubusercontent.com/154618384/296439918-2d33255a-d289-4f03-b966-702e3777490a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTc4MTgsIm5iZiI6MTcwNTI5NzUxOCwicGF0aCI6Ii8xNTQ2MTgzODQvMjk2NDM5OTE4LTJkMzMyNTVhLWQyODktNGYwMy1iOTY2LTcwMmUzNzc3NDkwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwNTQ1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Zjc2MDc4YjRkOGIwY2MyZTUyZDhmMjZlMmM1ODZmNDY1MzYzYTM5ZTVhZTMwMDE5NzZkYWJhYWE0Yzk5ZDkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xwzN2zMXtStnCObHRq4MjtPWgPfwhT9QCppkuPuDthI) Seed:4565953615806594921 ![2024-01-13_08-35-03_7528](https://private-user-images.githubusercontent.com/154618384/296439932-a90991f0-9827-4bd1-a43a-a84ebe9ebc96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTc4MTgsIm5iZiI6MTcwNTI5NzUxOCwicGF0aCI6Ii8xNTQ2MTgzODQvMjk2NDM5OTMyLWE5MDk5MWYwLTk4MjctNGJkMS1hNDNhLWE4NGViZTllYmM5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwNTQ1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjBlY2YwMDdkZmQ5MmMxNzYxOGY4NzRmZjllZDBlZGRhZGEwMjk0YzY4MTU4MGFmOWQ4OTUyYzA3NDkyODg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._fcTkkO-umn-NcS0x38VRzijmignVL8nemkwr7t0JfI) Seed:2997314892326416773 ![2024-01-13_08-36-56_2826](https://private-user-images.githubusercontent.com/154618384/296439949-dce6aea2-95f2-4db8-9512-c700ca3d8c4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTc4MTgsIm5iZiI6MTcwNTI5NzUxOCwicGF0aCI6Ii8xNTQ2MTgzODQvMjk2NDM5OTQ5LWRjZTZhZWEyLTk1ZjItNGRiOC05NTEyLWM3MDBjYTNkOGM0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwNTQ1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmE0MzQ2OTRhNzQwNGVmM2MyYjJiOWI0ZWJkMWI5NGY3YzA5YThjMGZkODA2NTI4ZjJlNTAyY2YwZWEyZDZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D9OYIoMb1N_kNuZwjAUhF-jlSVUOJXja7xt3tn0LlFE)
> 
> There is a small problem with the styles enabled by default: 'Fooocus V2', 'Fooocus Enhance', 'Fooocus Sharp', but if you disable them there are no problems.

Thanks, this works most of the time. Once in a while bindi or earrings show up but manageable for now until the base model improves with time. Thanks again all for helping and being patient with me.
