### ISSUE TITLE
pictures cut

### ISSUE THREAD

**Issue by ricinthesky** [lllyasviel/Fooocus#1897]
hi.
when i use a picture that i want to swap the face i use my face model and select "swap face" and in the second image promt field i use the picture that i want to swap: now i am always getting as result a picture cut on top and my model always lose the top of the head. Hope i've explained it properly, what am i doing wrong? maybe using too big picture as swap model?
cheers

**Comment by mashb1t** [comment]
I'm sorry, can you please explain your situation again?
What i got:
- You're using 2 pictures, one of you (FaceSwap enabled) and one as image prompt
- the output is cut off at the top

Please make sure you have toe correct aspect ratio selected in Advanced > Aspect Ratios and check if this is benificial to your generated result.

**Comment by ricinthesky** [comment]
Manuel thanx for reaching out again. I was playing with aspect ratio as you said in advanced and i am getting better results, i thought that the system would automatically scale to the right resolution but nope.
Cheers

**Comment by mashb1t** [comment]
Glad you could find a solution!
