### ISSUE TITLE
Please support controlnet for sdxl

### ISSUE THREAD

**Issue by wodsoe** [lllyasviel/Fooocus#190]
Please support controlnet for sdxl:
https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0-mid

**Comment by mashb1t** [comment]
Support for some ControlNet adaters has been added since you've created the issue, such as
- ImagePrompt
- PyraCanny
- CPDS
- FaceSwap

There also is a fork, which supports more ControlNet adapters. You can find it here: https://github.com/fenneishi/Fooocus-ControlNet-SDXL
