### ISSUE TITLE
Is this website related to you guys?

### ISSUE THREAD

**Issue by IamTirion** [lllyasviel/Fooocus#1908]
https://fooocus.pro/

I was googling Fooocus and came across this website.

**Comment by lllyasviel** [comment]
no. this site is fake.

**Comment by mashb1t** [comment]
As of the requests, this website uses Pixabay as backend, not generative AI.

![image](https://github.com/lllyasviel/Fooocus/assets/9307310/4e54fd04-b438-4e42-a646-1a1a454f2875)
![image](https://github.com/lllyasviel/Fooocus/assets/9307310/3f706985-16bc-4385-9f05-d27c30530cb6)

**Comment by IamTirion** [comment]
Sometimes I wonder what these scams are trying to achieve.

**Comment by simartem** [comment]
> Sometimes I wonder what these scams are trying to achieve.

traffic for ads

**Comment by mashb1t** [comment]
@lllyasviel any reason to keep this issue open, for reference and potential note-keeping?

**Comment by mashb1t** [comment]
cross reference: https://github.com/lllyasviel/Fooocus/discussions/2146

**Comment by H1beer** [comment]
What the real website

**Comment by mashb1t** [comment]
@H1beer this repository is the only valid and official website there is for Fooocus.

**Comment by mashb1t** [comment]
another one: https://github.com/lllyasviel/Fooocus/discussions/2835
