### ISSUE TITLE
Error Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by PLFENG** [lllyasviel/Fooocus#1910]
E:\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.862
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 6144 MB, total RAM 16317 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 6GB : native
VAE dtype: torch.float32
Using pytorch cross attention

**Comment by PLFENG** [comment]
我解决了

**Comment by mashb1t** [comment]
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1889, https://github.com/lllyasviel/Fooocus/issues/92 and [a few more](https://github.com/lllyasviel/Fooocus/issues?q=is%3Aissue+line+1+column+1+is%3Aclosed). Please check https://github.com/lllyasviel/Fooocus/issues/92#issuecomment-1706827413

**Comment by mlic00** [comment]
> 我解决了

How did you solve this problem?
/// Expecting value: line 1 column 1 (char 0)
