### ISSUE TITLE
sdxl_styles bug

### ISSUE THREAD

**Issue by outsami-9527** [lllyasviel/Fooocus#1911]
When I check the style inside fooocus, I don't see the negative cue word in the generated log.
But it's there in the style, is this a bug?

**Comment by poor7** [comment]
There are no positive ones either.

**Comment by docppp** [comment]
this is how it is right now, but with https://github.com/lllyasviel/Fooocus/pull/1920 you can see prompt style expansion

**Comment by mashb1t** [comment]
@outsami-9527 as mentioned, the styles do include positive and negative prompt, but the specific keywords are not resolved and shown in zhe prompt log file as the user didn't specifically enter these.
