### ISSUE TITLE
ARC A770 16BG driver

### ISSUE THREAD

**Issue by crerigan** [lllyasviel/Fooocus#1914]
Is it possible to run it on an ARC A770 16gb? 
it work like a charme with STD and other generators. There is something alreasy? or can be added in the future?

**Comment by mashb1t** [comment]
Sorry to say, but Intel ARC GPUs are currently not supported, see https://github.com/lllyasviel/Fooocus/issues/141.
Closing this issue as the enhancement is already in the backlog.
