### ISSUE TITLE
How can we enable refiner in Fooocus on payed Colab?

### ISSUE THREAD

**Issue by vanetreg** [lllyasviel/Fooocus#1922]
I'd like to enable refiner, but after reading README.md and searching issues for "refiner" I haven't found the answer.
Thanks

**Comment by mashb1t** [comment]
You can enable the refiner in the Advanced > Model tab by selecting any model as refiner next to the model itself. Suggestions for the switch can be found in the slider below.

For the original refiner of SDXL make sure to start Fooocus once with the `sai` preset as this downloads the SDXL refiner for you, but you can use any other model too.
