### ISSUE TITLE
[Errno 10048] error while attempting to bind on address ('127.0.0.1', 7865):

### ISSUE THREAD

**Issue by MrMyth** [lllyasviel/Fooocus#1926]
When i start Fooocus i got [Errno 10048] error while attempting to bind on address ('127.0.0.1', 7865). How to fix it?

**Comment by eddyizm** [comment]
It means that another application (possibly another instance of Fooocus) is already running on that port. If it is not Fooocus, then you need to figure out what else is running on your system and shut it down. 
run in your cli to give you a list and review. 
`netstat -abn`

If you already have fooocus running try a reboot. if another tool you need is running on that port then I believe there is a way to change to port but I have to go dig into the code ->
```
  server_port: will start gradio app on this port (if available). Can be set by environment variable GRADIO_SERVER_PORT. If None, will search for an available port starting at 7860.
````

**Comment by mashb1t** [comment]
Basically what @eddyizm said, there is another program running on this port or you've opened Fooocus twice.
You can change the port used by Fooocus by using the arg `--port 1234`.

**Comment by mashb1t** [comment]
@MrMyth is this still relevant?

**Comment by MrMyth** [comment]
Cant find free port for prgram

**Comment by mashb1t** [comment]
Either your System is using all 65535 ports (unrealistic) or there are no ports ehich you can use, in which case we can't help.

You can check port occupancy lime this:
- Linux: https://www.cyberciti.biz/faq/unix-linux-check-if-port-is-in-use-command/
- Windows: https://stackoverflow.com/questions/48198/how-do-i-find-out-which-process-is-listening-on-a-tcp-or-udp-port-on-windows

As this is a very individual issue of yours and can be solved by searching for free ports + adjusting the args i'll close this issue now. All the best for your search!
