### ISSUE TITLE
Google colab Gradio webui does not work 

### ISSUE THREAD

**Issue by 0xKayra** [lllyasviel/Fooocus#1927]
After the last update, while working on Google Colab, gradio webui keeps giving errors, but Fooocus continues to run in the background. 
Pictures are being created, but there is a problem with webui

**Comment by eddyizm** [comment]
It is working form, can you show the full log output in the terminal and what version of Fooocus you are using?

**Comment by 0xKayra** [comment]
> It is working for me, can you show the full log output in the terminal and what version of Fooocus you are using?

I used the version where the last change was made 5 days ago and I encountered this problem in the interface. 
There is no problem with the terminal, it continues to run in the background, only gradio webui gives an error. 
I didn't encounter this problem when I used the previous version, the last update (5 days ago) is troublesome for Google colab, at least for me...

**Comment by mashb1t** [comment]
Please make sure your network isn't bugging out and be aware of that you can't (reliably) use Image Prompt and refiners in Colab as RAM gets exhausted. See https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#colab (potential improvement in https://github.com/lllyasviel/Fooocus/pull/1710).

> Note that this Colab will disable refiner by default because Colab free's resources are relatively limited (and some "big" features like image prompt may cause free-tier Colab to disconnect). We make sure that basic text-to-image is always working on free-tier Colab.

Feel free to reopen this issue if you still experience issues using the base features of Fooocus in Colab and provide the terminal output to determine next steps.
