### ISSUE TITLE
Stuck on 'Preparing Fooocus text #1'

### ISSUE THREAD

**Issue by Hobstarr** [lllyasviel/Fooocus#1928]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
No progress after 'Preparing Fooocus text #1'
Originally had the segmentation fault (core dumped), but updated torch nightly, and used the following command which fixed that issue. Now there is just no progress after the above terminal output.

**Full Console Log**
(fooocus_env) [fedora Fooocus]$ HSA_OVERRIDE_GFX_VERSION=10.3.0 python entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.10.13 [(Red Hat 13.2.1-6)]
Fooocus version: 2.1.862
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 8176 MB, total RAM 32013 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 AMD Radeon RX 5500 XT : native
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --attention-split
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.91 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 3671671505151708204
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...

**Comment by mashb1t** [comment]
@Hobstarr make sure you've followed all steps in https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#linux-amd-gpus. 
In general, your RX 5500 XT has 8GB VRAM, which should be sufficient since one of the last updates of Fooocus.
Also make sure you have swap configured and sufficient space available, see https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

**Comment by Hobstarr** [comment]
I'll try this later - I'm using Fedora, and I think I have the option for zram or zwap. I don't really know much about it so if you have advice on which one to use then I can try follow the advice for those. - Thanks for the quick response.

**Comment by f0n51** [comment]
@Hobstarr Since your machine has 32GB of RAM, I'd recommend using a mininum of 40GB swap partition (not zram) for Fooocus.

**Comment by mashb1t** [comment]
@Hobstarr were you able to run Fooocus on your machine or do you require further assistance?

**Comment by mashb1t** [comment]
@Hobstarr Closing as stale, feel free to provide feedback if further assistance is needed.
