### ISSUE TITLE
CUDA out of memory with the same specification as mentioned in README file

### ISSUE THREAD

**Issue by hamjam** [lllyasviel/Fooocus#193]
Hi,
I have a laptop with exactly the same specification as mentioned in README file:
Nvidia RTX 3060 laptop with 6GiB VRAM
16GiB RAM
but when I execute run.bat file on windows, I get this:
![image](https://github.com/lllyasviel/Fooocus/assets/12621752/159d084c-b7c2-4feb-95e3-76cc30974b2b)
Am I doing something wrong?

**Comment by ludashi6789** [comment]
it worked success！ If the directory you installed is on the C drive, then set the cache to the C drive. If the directory you installed is on the D drive, install the cache on the D drive.
![微信截图_20230820085627](https://github.com/lllyasviel/Fooocus/assets/127379764/812e1834-7911-4daa-baae-dbbf22f1bcda)

**Comment by mashb1t** [comment]
> it worked success！ If the directory you installed is on the C drive, then set the cache to the C drive. If the directory you installed is on the D drive, install the cache on the D drive

^ basically this!

Closing this issue, can be solved by following the troubleshooting guide https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md (expecially swap section) after looking up the minimum requirements in https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement
