### ISSUE TITLE
Installation Focus MAC - cannot import name 'IOComponent' from 'gradio.components.base'

### ISSUE THREAD

**Issue by jfl272** [lllyasviel/Fooocus#1930]
Hello,

I cannot launch Focus in my MAC. When I try I get this error:

Installed Python-3.10.6 to /Users/javierfernandezlorente/.pyenv/versions/3.10.6
(base) javierfernandezlorente@MacBook-Air Fooocus % conda activate fooocus
(fooocus) javierfernandezlorente@MacBook-Air Fooocus % python entry_with_update.py --disable-offload-from-vram 
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--disable-offload-from-vram']
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
Fooocus version: 2.1.862
Installing requirements
Couldn't install requirements.
Command: "/Users/javierfernandezlorente/miniconda3/envs/fooocus/bin/python" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stdout: Collecting torchsde==0.2.5
  Using cached torchsde-0.2.5-py3-none-any.whl (59 kB)
Collecting einops==0.4.1
  Using cached einops-0.4.1-py3-none-any.whl (28 kB)
Collecting transformers==4.30.2
  Using cached transformers-4.30.2-py3-none-any.whl (7.2 MB)
Collecting safetensors==0.3.1
  Using cached safetensors-0.3.1.tar.gz (34 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting accelerate==0.21.0
  Using cached accelerate-0.21.0-py3-none-any.whl (244 kB)
Collecting pyyaml==6.0
  Using cached PyYAML-6.0-cp310-cp310-macosx_11_0_arm64.whl (173 kB)
Collecting Pillow==9.2.0
  Using cached Pillow-9.2.0-cp310-cp310-macosx_11_0_arm64.whl (2.8 MB)
Collecting scipy==1.9.3
  Using cached scipy-1.9.3.tar.gz (42.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

stderr:   error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      + meson setup /private/var/folders/jq/zz3lk2nj1fv91whp7f6v1br40000gn/T/pip-install-2tlilx9w/scipy_b69b47c0d108437a862d94855c21c452 /private/var/folders/jq/zz3lk2nj1fv91whp7f6v1br40000gn/T/pip-install-2tlilx9w/scipy_b69b47c0d108437a862d94855c21c452/.mesonpy-t1yb1s85 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/private/var/folders/jq/zz3lk2nj1fv91whp7f6v1br40000gn/T/pip-install-2tlilx9w/scipy_b69b47c0d108437a862d94855c21c452/.mesonpy-t1yb1s85/meson-python-native-file.ini
      The Meson build system
      Version: 1.3.1
      Source dir: /private/var/folders/jq/zz3lk2nj1fv91whp7f6v1br40000gn/T/pip-install-2tlilx9w/scipy_b69b47c0d108437a862d94855c21c452
      Build dir: /private/var/folders/jq/zz3lk2nj1fv91whp7f6v1br40000gn/T/pip-install-2tlilx9w/scipy_b69b47c0d108437a862d94855c21c452/.mesonpy-t1yb1s85
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      C compiler for the host machine: cc (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
      C linker for the host machine: cc ld64 650.9
      C++ compiler for the host machine: c++ (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
      C++ linker for the host machine: c++ ld64 650.9
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO (cached)
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      
      ../meson.build:57:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
      A full log can be found at /private/var/folders/jq/zz3lk2nj1fv91whp7f6v1br40000gn/T/pip-install-2tlilx9w/scipy_b69b47c0d108437a862d94855c21c452/.mesonpy-t1yb1s85/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

CMD Failed requirements: install -r "requirements_versions.txt"
Traceback (most recent call last):
  File "/Users/javierfernandezlorente/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/Users/javierfernandezlorente/Fooocus/launch.py", line 109, in <module>
    from webui import *
  File "/Users/javierfernandezlorente/Fooocus/webui.py", line 13, in <module>
    import modules.gradio_hijack as grh
  File "/Users/javierfernandezlorente/Fooocus/modules/gradio_hijack.py", line 21, in <module>
    from gradio.components.base import IOComponent, _Keywords, Block
ImportError: cannot import name 'IOComponent' from 'gradio.components.base' (/Users/javierfernandezlorente/miniconda3/envs/fooocus/lib/python3.10/site-packages/gradio/components/base.py)

Thank you in advance for your help!

Javier

**Comment by eddyizm** [comment]
what mac hardware do you have? 
I was able to install on an m1. however, i never use conda and just use plain python. I always find that install much more straightforward. Hopefully someone with conda experience can help you out.  My assumption is there is an issue with conda versions.

**Comment by jfl272** [comment]
I also have the M1. Do you know where I can find a guide to install it without conda?
Thank you!
BR from Barcelona

**Comment by mashb1t** [comment]
@jfl272 You seem to run a custom setup using meson. I can confirm that in general MacOS (on a M1 Macbook) can run Fooocus without issues, just tested from a fresh install following the unofficial installation guide at https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#mac. Resetting your installation (delete & setup again) might help.
You might also be able to use https://github.com/LykosAI/StabilityMatrix and their one-click-installer for MacOS.

Please provide your feedback if one of the provided starting points helped.

**Comment by jfl272** [comment]
After resetting the installation it did work, thank you!!
I have a MacBook Air with the M1 and it's soooooo slow though

**Comment by jfl272** [comment]
After resetting the installation it did work, thank you!!
I have a MacBook Air with the M1 and it's soooooo slow though

**Comment by mashb1t** [comment]
it is how it is, luckily you managed to make it work in the first place 👍

**Comment by gokhanbaydar** [comment]
Your gradio version is probably 4 something , I had the same issue, downgraded to gradio==3.41.2 like it is mentioned in requirements and it worked with no problems after: 

pip install gradio==3.41.2
