### ISSUE TITLE
No way to stop process when prompt has bad syntax unreadable for Fooocus

### ISSUE THREAD

**Issue by zilvergrafix** [lllyasviel/Fooocus#194]
try this prompt:

**_a woman in a blue and yellow dress posing for a picture, sexy push up bras, 中 元 节, pastel blue, detailed face of a asian girl, big breasts!, scaled robes, beautiful well rounded face, in front of the temple, .ai, plushy, wearing in shirt, ice blue, huge!!!, 1 0 0 0 mm_**

Generate
some issue on the cmd window, hangs forever, last resort is kill the process and restart from zero.

image unfinished

![image](https://github.com/lllyasviel/Fooocus/assets/126435153/47afbdd9-8700-4a9b-a1e5-438ef153a46b)

**Comment by zilvergrafix** [comment]
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\AI\Fooocus\Fooocus\modules\async_worker.py", line 104, in worker
    handler(task)
  File "C:\AI\Fooocus\Fooocus\modules\async_worker.py", line 92, in handler
    log(x, d)
  File "C:\AI\Fooocus\Fooocus\modules\private_logger.py", line 26, in log
    f.write(f"<p>{k}: <b>{v}</b> </p>\n")
  File "encodings\cp1252.py", line 19, in encode
**UnicodeEncodeError: 'charmap' codec can't encode character '\u4e2d' in position 117: character maps to <undefined>**

**Comment by zilvergrafix** [comment]
![Screenshot 2023-08-18 091741](https://github.com/lllyasviel/Fooocus/assets/126435153/1f0a5b75-302e-4d0f-afd0-f33d98343145)

**Comment by MoonRide303** [comment]
@lllyasviel Fix for crashing when writing log file entries for prompts containing non-ASCII characters available in pull request #197 (merged on [my fork](https://github.com/MoonRide303/Fooocus)).
