### ISSUE TITLE
Questions about switching history (date folder not changed after 00:00)

### ISSUE THREAD

**Issue by JulienZLQ** [lllyasviel/Fooocus#1951]
Does the history record need to be restarted every day before it can be updated to the current day, or what trigger state is required. During use, I found that the time is not synchronized and switches to the log folder link of the new day.

**Comment by mashb1t** [comment]
Hey @JulienZLQ , as of https://github.com/lllyasviel/Fooocus/blob/main/modules/util.py#L153 the folder name is generated for every image and updates itself.
Can you please check it the datetime in filenames of the outputs folder is correct?

**Comment by JulienZLQ** [comment]
@mashb1t The generation time is normal.
I mean, let's say I launch fooocus on January 17th, and I click on the history on the web, and what I see is that it was generated on January 17th.
However, I kept it started, and on January 18th, I continued to generate, and the pictures were successfully entered into the folder on January 18th. However, no matter how I refreshed the web and clicked on the history, the logs from January 17th were still opened. html.
But at this time, I closed the background program and restarted fooocus, and the log on January 18th could be linked to the log on the web normally.

**Comment by mashb1t** [comment]
I got what you mean, will check in the evening (8 PM CET / UTC+1)

**Comment by mashb1t** [comment]
@JulienZLQ i tripple checked, it works fine for me every time when manually adjusting the windows clock to a specific date and time, also for 23:59, 00:00 and 00:01. Which OS are you using and can you reproduce the behavior when manually setting the time on your OS?

**Comment by JulienZLQ** [comment]
@mashb1t windows, Manual adjustment is still ineffective, and refreshing and opening still stays at the previous day.

**Comment by JulienZLQ** [comment]
@mashb1t I even re-downloaded fooocus just now without using any additional tweaks. But no matter how I set the time, at 00:00, the historical log  is still the previous day, even though the picture I generated at 00:00 can correctly enter the folder of the right day.

**Comment by mashb1t** [comment]
@JulienZLQ i must admit, i misunderstood the question and did only check for the image, not for the history log. Will have a look again, sorry!

**Comment by JulienZLQ** [comment]
@mashb1t thx, just the link of history log on web.

**Comment by mashb1t** [comment]
See linked PR. Small issue, prio low, but still an issue.

**Comment by mashb1t** [comment]
I'm not a fan of this idea as sessions then have to be tracked + identified for each tab and looped through the whole application, which will also lead to chaos in your outputs folder. I'd just leave it at date as this also makes assets way easier to find.
