### ISSUE TITLE
how to shorten time?

### ISSUE THREAD

**Issue by cleexiang** [lllyasviel/Fooocus#1953]
The actual processing time of the picture is twice as long as the log shows, about 15s, but the log shows 7s.
Server:1 x RTX 4090,16 vCPU 62 GB RAM
Ratio: 704x1408

Logs:::
Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 3.0
[Parameters] Seed = 6994768219998219688
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] Full body photo,1girl,cat girl, 20 years old, long black hair, big green eyes, sexy, big breasts, tattered clothes, revealing cleavage, revealing thighs, life and death, handle,seeing again, realisation, way to die, mentioned earlier, significance, thoughts, share, comfortable, thought original, accepted, attractive, extremely detailed
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1408, 704)
Preparation time: 0.44 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.23 seconds
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.81it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.22 seconds
Image generated with private log at: /data/Fooocus/outputs/2024-01-17/log.html
Generating and saving time: 6.42 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.38 seconds
Total time: 7.71 seconds

**Comment by mashb1t** [comment]
Just to make sure, are the 15s the time from click to result?
If this is the case, Gradio takes some time to queue your request, start frontend handling, handle network communication and a few more things, which are all things the processing can't measure.
Please provide more information about your measuring procedure, much appreciated!

**Comment by cleexiang** [comment]
Yes, it's from click to result.
What does "Moving model(s)" mean in the log, and why does" Moving model(s)" happen every time an image is generated?

**Comment by mashb1t** [comment]
Models are offloaded to RAM and loaded to VRAM for every generation to guarantee a smooth OS experience.
You might want to optimize this by using the arg `--disable-offload-from-vram` and/or `--always-high-vram`, depending on your GPU. A RTX 4090 should also easily be able to keep everytrhing (also text encoders) in VRAM, so feel free to use `--always-gpu` instead of the above parameters instead for maximum performance and blazung fast inference with next to no loading speeds for models as they are not offloaded from GPU then.

**Comment by cleexiang** [comment]
> Models are offloaded to RAM and loaded to VRAM for every generation to guarantee a smooth OS experience. You might want to optimize this by using the arg `--disable-offload-from-vram` and/or `--always-high-vram`, depending on your GPU. A RTX 4090 should also easily be able to keep everything (also text encoders) in VRAM, so feel free to use `--always-gpu` instead of the above parameters for maximum performance and blazing fast inference with next to no loading speeds for models as they are then not offloaded from GPU. Please let me know your results, i strongly assume that you'll be amazed and we can close this issue ;)

The log indicates a duration of approximately 5-6 seconds, whereas the total time for each generation on the webpage remains consistently around 15 seconds.

**Comment by mashb1t** [comment]
As mentioned in https://github.com/lllyasviel/Fooocus/issues/1953#issuecomment-1896785735 there are multiple delays in Gradio as well as bootstrapping going on in Fooocus every time you do a request, which might not directly be tracked (webui.py elements + functions).

> Gradio takes some time to queue your request, start frontend handling, handle network communication and a few more things, which are all things the processing can't measure.

Can this issue be closed?
