### ISSUE TITLE
Diffusers support?

### ISSUE THREAD

**Issue by machineminded** [lllyasviel/Fooocus#1959]
I'm interested in integrating PhotoMaker into a Fooocus fork of mine, but it's in diffusers format.  Huggingface provides some methods to convert diffusers and I was wondering if that would work for the pipelines that are utilized in Fooocus?  Otherwise is it possible to use diffusers with Fooocus out of the box?  Thanks in advance.

**Comment by mashb1t** [comment]
The pipelines in Fooocus have been customized and as Fooocus doesn't use diffusers at all, it's not compatible by default without isntalling the diffusers python package.
Feel free to do so, i also intalled diffusers for https://github.com/lllyasviel/Fooocus/pull/958 (btw thank you for letting me double-check, forgot to add it and only committed the package in my fork ^^)

**Comment by machineminded** [comment]
Thanks for the response @mashb1t .  I will look into using diffusers for this otherwise converting the model on huggingface.  Not sure if either are feasible.
