### ISSUE TITLE
Colab

### ISSUE THREAD

**Issue by MasterRed0** [lllyasviel/Fooocus#1961]
Hi, 
I purchased the 12$ version of Colab so Fooocus runs better, but the quality is poor fe. with face swap, is it because the is no refiner? how can I make it work? 
Also, is there anything else I should do to make it run like it's supposed to with the premium version of Colab? (except for switching to the high ram environment every time) 
I couldn't find any tutorial.
Another issue I have is with checkpoints, how can I create my own, or do I have to download a pre-existing one from CivitAI?
Thanks in advance

**Comment by mashb1t** [comment]
Hey @MasterRed0, i'm trying to answer you on all points:

1. using no refiner is fine. The generated result depends on the prompt and the styles you chose, as well as what feels a million other factors. Please make sure you're using a prompt specifying major characteristice of your subject.
2. you can find optimisations in https://github.com/lllyasviel/Fooocus/pull/1710, which work well for many people and also boost inference speed.
3. You can create your own Checkpoints (not in Fooocus, but e.g. by using https://github.com/bmaltais/kohya_ss), but this would take a few days/weeks if you want to make the call. I'd suggest downloading models (checkpoints) from https://civitai.com and check out existing ones. Once you're into the topic of AI you can have a look at LoRA training, also described well in the kohya_ss repo, but be aware of that this might be overwhelming at first as there are so many options.

I hope i could answer all of your points. Feel free to also check out the beginners guide at https://stable-diffusion-art.com/beginners-guide/ + https://stable-diffusion-art.com/models/ to get to know Stable Diffusion (XL) and for some further tips on models. Keep in mind that Fooocus only supports SDXL models and SD (non-XL and XL) refiners.

Happy to have you in the community and happy prompting!

**Comment by eddyizm** [comment]
Damn @mashb1t you are always getting to the answer before I can even type out my reply. lol

**Comment by mashb1t** [comment]
@eddyizm i appreciate the effort ;)
