### ISSUE TITLE
Question: Why this particular set of resolutions?

### ISSUE THREAD

**Issue by kyeno** [lllyasviel/Fooocus#1962]
Hey, this may be a bit nooby one, but still remains a mystery to me at this point.
So - as the title says: why this particular set of available resolutions?
Most of them seem very weird and rather uncommon.

Why not anything of more standard range, like 1280x720, 1280x1024, 1920x1080, 2560x1440, 2560x1600, 3840x2160?
Is there any reasoning/logic behind that?
@mashb1t ? :)

![zapierajace_dech_w_piersiach_ROZDZIELCZOSCI_EKRANU](https://github.com/lllyasviel/Fooocus/assets/1790957/29c74e9e-1501-4d07-987e-1fb3ab16faeb)

**Comment by mashb1t** [comment]
You can find all the information necessary to understand why this is not possible / well supported in https://github.com/lllyasviel/Fooocus/pull/1617#issuecomment-1870469961 and below + https://github.com/lllyasviel/Fooocus/discussions/117#discussioncomment-7364981.
As Fooocus strives for highest quality, none of these resolutions is included.
Hope this helps!

**Comment by kyeno** [comment]
Thank you very much @mashb1t, that indeed explains a lot.
And sorry for my lack of background in generative AI in general - still trying to catch up. :)

**Comment by mashb1t** [comment]
No worries, you're welcome. For higher resolutions you can always use and it's recommended to use upscaling, which also works really well in Fooocus.
