### ISSUE TITLE
Photographic models are not colourful enough and feel greyish

### ISSUE THREAD

**Issue by jwcun** [lllyasviel/Fooocus#1968]
![12](https://github.com/lllyasviel/Fooocus/assets/155848431/8eb31462-602f-4ce6-aaff-97d1c86b6b6b)
None of them are bright enough, is there a good solution for this please and thank you!

**Comment by jwcun** [comment]
Thank you for your reply.

**Comment by jwcun** [comment]
> This looks like a good photograph and realistic, what is your prompt and settings?

I couldn't agree with you more and agree that it's a good photo, sadly it looks more like a film stills, whereas I would have preferred it to look like a postcard or wallpaper.
I can't find the specific settings and prompts anymore, but I can show you similar ones:
prompt：Spring, flowers      styles:Fooocus Enhance，Light Cheery Atmosphere，Macro Photography
![1](https://github.com/lllyasviel/Fooocus/assets/155848431/ab6e6a6f-5964-4976-8b7a-df1fba07481b)
prompt：Spring, flowers      styles:Photo Tilt Shift
![4](https://github.com/lllyasviel/Fooocus/assets/155848431/5bc06f42-38b0-4c51-9823-13283889a6c0)
I think these are very nice to look at, but they're too much like a scene that would appear in a certain frame of a film, which doesn't really suit me, I want them to look like this：
![OIP](https://github.com/lllyasviel/Fooocus/assets/155848431/58b0b237-2646-422e-913d-de9301abf056)
It's much brighter and suitable for some postcards or wallpapers.
I've tried almost all the styles about photography but they don't meet my requirements, do you have any good suggestions to help me improve this situation, thank you for your answer!

**Comment by BuBaLoM-JMP** [comment]
![image (1)](https://github.com/lllyasviel/Fooocus/assets/133919957/df7aaee7-0886-48f9-a85d-bff84abf7477)
![image](https://github.com/lllyasviel/Fooocus/assets/133919957/ec8c125e-5294-472a-bb0d-2affca3b9b04)
Promt:
a bunch  flowers,
