### ISSUE TITLE
Is it possible to generate images in batches?

### ISSUE THREAD

**Issue by YellowTigerr** [lllyasviel/Fooocus#1969]
Only the prompt words are modified，other parameters remain unchanged,Is it possible to enter multiple prompts to mass produce images?

**Comment by Phrixus2023** [comment]
wildcards，https://www.youtube.com/watch?v=ZyxRUBKw6gs

**Comment by mashb1t** [comment]
@YellowTigerr you can either use wildcards or [arrays](https://github.com/lllyasviel/Fooocus/pull/1503)
