### ISSUE TITLE
LoRA settings are not considered while generating images

### ISSUE THREAD

**Issue by leonandroid** [lllyasviel/Fooocus#1975]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
Models (from LORA) seems not to be taken in consideration while generating the result.

Taking this example:
https://civitai.com/models/6888/luisap-humanoid-robots-1mb
![image](https://github.com/lllyasviel/Fooocus/assets/1564651/c7db2c1e-5849-46fe-8e65-b3ee889a4581)
Trigger words "ROBOT"

I'm using the following model as example:
![image](https://github.com/lllyasviel/Fooocus/assets/1564651/6e6a8e63-37cd-4668-b95c-0acd0d38b7ab)

**Style: Fooocus v2, Fooocus Photograph, Fooocus Negative**

This is the result with **default settings**: MODEL:
prompt: cyborg girl posing, futuristic robot, robotic girl
seed: 8144510124993697307
RealisticStockPhoto_v10
Lora1: SDXL_FILM_PHOTOGRAPHY_STYLE_Betav0.4 = weight 0.25

I get this result, fair enough
![image](https://github.com/lllyasviel/Fooocus/assets/1564651/95e3de7f-3104-480a-a62b-5f663507f263)

Now i'm trying a specific LORA to do this, the one mentioned above
prompt: cyborg girl posing, futuristic robot, robotic girl
seed: 8144510124993697307 (same)
RealisticStockPhoto_v10
Lora1: Cyborgbot = weight 2 (trying lower values also)
![image](https://github.com/lllyasviel/Fooocus/assets/1564651/4a366b4d-f07c-4880-92ef-4a5d270b3dea)

no difference... so this clearly means is not taking in consideration the LORA.

Let's try something drastically different, i'm gonna pick a LORA that makes it ANIME, 
https://civitai.com/models/104976/future-diffusion-robot-youtuber
this would be the example expected:
![image](https://github.com/lllyasviel/Fooocus/assets/1564651/7fb7a1b3-c1b4-49d7-94c4-37294ad78605)

it has the same trigger word "ROBOT" and "CYBORG", so it should work without affecting the prompt.

prompt: cyborg girl posing, futuristic robot, robotic girl (same)
seed: 8144510124993697307 (same)
RealisticStockPhoto_v10
Lora1: futuredifussion-08 = weight 2 (trying lower values also) with -2 is exactly the same, with 0.5 is the same as well

it's again the same result, is doing nothing with the LORA clearly
![image](https://github.com/lllyasviel/Fooocus/assets/1564651/f879271b-e718-45a7-9290-54a037de72a9)

I'm gonna try removing the base model, instead of Realistic Stock photo, i'm gonna use the juggernautXL_version6 and again the last LORA model.

Result: Different, but not as per the LORA.
![image](https://github.com/lllyasviel/Fooocus/assets/1564651/d6d54724-ef3e-4c3e-8f52-05540b8615f8)

I'm gonna try now removing the STYLE, that I think it might be affecting:
So now, no STYLE applied, all empty

Not sure why It changed to this, but still not similar to the LORA:
![image](https://github.com/lllyasviel/Fooocus/assets/1564651/973022cb-6dee-42a7-ab45-676c1fb6992a)

Testing now removing the SEED; let it be random:
Result: even worst:
![image](https://github.com/lllyasviel/Fooocus/assets/1564651/75877d5f-5d1d-4ce6-bca7-2c628bf5d4f2)

Let's say the image prompt i'm using, its affecting the result, so let's not use image prompt anymore and let it be just with the text prompt:

I get this; which is not what is expected by the LORA:
![image](https://github.com/lllyasviel/Fooocus/assets/1564651/057f3e9c-3664-49fa-be5a-bb159a875dd3)

**So, i'm not sure, what am I doing wrong here? why the loras are not taken in consideration?**

**Full Console Log**

{
"Prompt": "cyborg girl posing, futuristic robot, robotic girl",
"Negative Prompt": "unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label",
"Fooocus V2 Expansion": "",
"Styles": "[]",
"Performance": "Extreme Speed",
"Resolution": "(896, 1152)",
"Sharpness": 0.0,
"Guidance Scale": 1.0,
"ADM Guidance": "(1.0, 1.0, 0.0)",
"Base Model": "juggernautXL_version6Rundiffusion.safetensors",
"Refiner Model": "None",
"Refiner Switch": 1.0,
"Sampler": "lcm",
"Scheduler": "lcm",
"Seed": 265211598705829415,
"LoRA 1": "futurediffusion-08.safetensors : 2.0",
"LoRA 6": "sdxl_lcm_lora.safetensors : 1.0",
"Version": "v2.1.862"
}

**Comment by mashb1t** [comment]
Please make sure you're using SDXL LoRAs when only using a base model or SD 1.5 LoRAs with a refiner.

https://civitai.com/models/6888/luisap-humanoid-robots-1mb has been trained on SD 1.5
![image](https://github.com/lllyasviel/Fooocus/assets/9307310/dfb402c7-0312-4572-9b6d-918f24007ce3)

https://civitai.com/models/104976/future-diffusion-robot-youtuber
![image](https://github.com/lllyasviel/Fooocus/assets/9307310/5fbdced5-7612-4410-9d7f-473ea9d3a5bf)
