### ISSUE TITLE
Where to upload CHECKPOINT MERGE?

### ISSUE THREAD

**Issue by Nicolayka** [lllyasviel/Fooocus#1977]
I download the model and upload it to models\checkpoints, but when I try to create something, a bunch of errors pop up.

For example:
https://civitai.com/models/241415/picxreal

Please tell me where to upload the "CHECKPOINT MERGE" type models. Thanks

**Comment by ekinertac** [comment]
it's a SD 1.5 model, you need SDXL models for Fooocus

**Comment by mashb1t** [comment]
@Nicolayka as mentioned by @ekinertac you're trying to load an SD model while Fooocus only supports SDXL base models. What you can do is to use SD 1.5 models as refiner and the Juggernaut base model.

![image](https://github.com/lllyasviel/Fooocus/assets/9307310/cfd70fb2-0acb-4c25-9ca6-d8701d26f196)

**Comment by Nicolayka** [comment]
Thanks guys! Thanks a lot for the clarification!
