### ISSUE TITLE
Create a space to share the best practices.

### ISSUE THREAD

**Issue by monkrus** [lllyasviel/Fooocus#1978]
**Is your feature request related to a problem? Please describe.**
Creating an educational cycle for those involved in image generation.

**Describe the idea you'd like**
Establish a space to consistently post the best settings/practices for image generation. Include the exact settings used along with the corresponding results.

**Comment by mashb1t** [comment]
This more or less already exists in the Show & Tell section of our discussions, see https://github.com/lllyasviel/Fooocus/discussions/categories/show-and-tell

What would be your proposal, including considerations not to open a Discord server (see https://github.com/lllyasviel/Fooocus/issues/112)?

**Comment by monkrus** [comment]
Something similar to this. Not the greatest image, but this test set has distance/position rows. Visual reference, so to speak.

<img width="430" alt="Screenshot 2024-01-18 171023" src="https://github.com/lllyasviel/Fooocus/assets/12500447/6a575005-d490-4884-81ff-5ddecf3eb680">

**Comment by mashb1t** [comment]
Yeah, that's perfect for Show & Tell, feel free to post it there!
