### ISSUE TITLE
Manipulate only a region of an (uploaded) image?!

### ISSUE THREAD

**Issue by Hadryan** [lllyasviel/Fooocus#198]
This requires two steps:
1.) The ability to upload a user's image.
2.) Manipulate a region of the uploaded image, either by drawing a box around the region or just by the help of the prompt.

![Selection tool](https://github.com/lllyasviel/Fooocus/assets/5006555/b7563da3-d276-446a-9398-ef4f008d391b)

![With prompt](https://github.com/lllyasviel/Fooocus/assets/5006555/23f2a11a-3547-4358-b283-c5656f1ef906)

That would be great if you can suggest a workaround about that.

**Comment by mashb1t** [comment]
Please check out the new (more or less, since 2 months) inpainting tools in the latest version of Fooocus.
Let me know if this is sufficient for you and feel free to reopen the PR.
Thanks, your feedback is welcome!
