### ISSUE TITLE
How to add Cloud path to Checkpoints? 

### ISSUE THREAD

**Issue by artemsvit** [lllyasviel/Fooocus#1983]
Hello. I have a problem. 
I download models to my Cloud and try to connect it in config file. But it's not working.
My Cloud Path is:  "\\MYCLOUD-JS90EG\artsvit\AI\Sources\checkpoints"
I add this in config:  "path_checkpoints": "\\MYCLOUD-JS90EG\\artsvit\\AI\\Sources\\checkpoints",
Maybe for this format need something else?

**Comment by mashb1t** [comment]
@artemsvit do you require further assistance?

**Comment by mashb1t** [comment]
closing as stale
