### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by ksorah1** [lllyasviel/Fooocus#1988]
Hello. I'm supposed to have the last version, but my dad just installed it and his Fooocus look newer.

My .bat :
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset realistic
pause

My update log :
**(2023 Oct 26) Hi all, the feature updating of Fooocus will (really, really, this time) be paused for about two or three weeks because we really have some other workloads. Thanks for the passion of you all (and we in fact have kept updating even after last pausing announcement a week ago, because of many great feedbacks)  - see you soon and we will come back in mid November. However, you may still see updates if other collaborators are fixing bugs or solving problems.**

# 2.1.750

* New UI: now you can get each image during generating.

# 2.1.743

* Improved GPT2 by removing some tokens that may corrupt styles.

My UI :
![2024-01-19 19_31_29](https://github.com/lllyasviel/Fooocus/assets/112913359/e8215cd3-eeff-4823-9239-046670e74dea)

**Comment by eddyizm** [comment]
What do you see in your terminal output, the log output when you start it up? 
It should update automatically and if not I would expect to see some error.

**Comment by mashb1t** [comment]
Update has been tested and is working as expected. Please manually re-download or execute `git pull` in a terminal in the Fooocus folder.

**Comment by ksorah1** [comment]
I updated it with pinokio I use now.
I totaly dislike 2 changes :
- first the log is so laggy when it try to load images that now my PC freeze 20 sec for each images.
- 2nd I hate that now we have to import the image for each tab in img to img.

sad.

**Comment by mashb1t** [comment]
fyi i'm actively working on the metadata integration, see https://github.com/lllyasviel/Fooocus/pull/1940.
Metadata saving is already possible in both Fooocus and A1111 format, import is still WIP.

**Comment by ksorah1** [comment]
cool thank you !

I don't know why I can't open the logs without an intense lag since the update... maybe some pictures are too big
