### ISSUE TITLE
Image Doesn't Appear When In/Outpainting

### ISSUE THREAD

**Issue by SubjectGinger** [lllyasviel/Fooocus#1991]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
I am trying to outpaint a photo. I drag and drop the photo into the in/outpaint window, and the text saying "Drop Image or Upload" disappears and the brush tool appears. However, the photo is not visible. Dragging other photos works fine and appear as normal. The photo I am trying to outpaint is a standard png file. 

Adding to this, dragging photos that have been outpainted from the preview window (just above where you drag photos to be outpainted) does not work. The area where you are to drag the photo to be in/outpainted gets the orange dashed lines but nothing actually happens when you let go of the mouse button.

EDIT: I see an error in the command prompt that says "TypeError: 'nonetype' object is not subscriptable"

**Full Console Log**
Would gladly share a log but I see no instruction on how to create one, and browsing the Fooocus file folders I don't see any log files.

**Comment by eddyizm** [comment]
the `Full Console Log` is all the output from the command prompt window - also referred to as the terminal. It will help give us more context on the error you are seeing.

**Comment by mashb1t** [comment]
Closing as stale
