### ISSUE TITLE
Please add feature for style expansion

### ISSUE THREAD

**Issue by AkashSCIENTIST** [lllyasviel/Fooocus#1995]
When we use predefines style, the Fooocus V2 expander expands only given positive prompts. It doesn't add original positive and negative prompts of chosen style in log

**Comment by mashb1t** [comment]
Please check if changing https://github.com/lllyasviel/Fooocus/blob/main/modules/async_worker.py#L425C61-L425C72 to `positive` is able to achieve better results than using prompt expansion based on `task_prompt` only.

**Comment by mashb1t** [comment]
Implemented in https://github.com/lllyasviel/Fooocus/pull/1920

**Comment by mashb1t** [comment]
https://github.com/lllyasviel/Fooocus/pull/1920 has just been merged to develop, will be included in [2.4.0](https://github.com/lllyasviel/Fooocus/milestone/5)
