### ISSUE TITLE
Please add additional feature for saving image

### ISSUE THREAD

**Issue by AkashSCIENTIST** [lllyasviel/Fooocus#1996]
If we download image from civitai we could see generation data in comment section of image's metadata. This feature is missing in image generation of Fooocus UI.

**Comment by eddyizm** [comment]
Do you mean you want the image generation data in the image metadata? The generation details are on the log file if you have that enabled.

**Comment by eddyizm** [comment]
I am not clear on what you mean by what "added to the image" because looking at some of the images on citvitia , I don't see any data embedded in the file which is what I think of as adding data to an image. If you could provide side by side examples on what you expect to see and what is missing that would be really helpful.

**Comment by techalexx** [comment]
For example:
![01](https://github.com/lllyasviel/Fooocus/assets/14972280/c66b5529-8122-4e6b-af31-916510c748ec)

Viewer - XnView Classic 2.51.2

**Comment by mashb1t** [comment]
Please find more information / the implementation in https://github.com/lllyasviel/Fooocus/pull/1940 + https://github.com/lllyasviel/Fooocus/discussions/160

**Comment by AkashSCIENTIST** [comment]
> I am not clear on what you mean by what "added to the image" because looking at some of the images on citvitia , I don't see any data embedded in the file which is what I think of as adding data to an image. If you could provide side by side examples on what you expect to see and what is missing that would be really helpful.

![Screenshot 2024-01-21 090253](https://github.com/lllyasviel/Fooocus/assets/25793714/8bef091e-d77d-4bab-b759-c2bfc5d41dfc)
Above image is generated using Civitai. You could see that generation data is present as comment
![Screenshot 2024-01-21 090342](https://github.com/lllyasviel/Fooocus/assets/25793714/ed14831b-bc78-41ad-953a-83c5e3ed728e)
Above image is generated using Fooocus UI. You could see that generation data is missing

**Comment by xhoxye** [comment]
This isn't information loss, this is deliberate non-preservation, information exists only in log.html.

**Comment by lgwjames** [comment]
any way to download all files, say i make 6 images, to download all 6 and its makes its own name files?

**Comment by mashb1t** [comment]
> The option “write hidden meta data” does not even exist in Fooocus, so that you do not need to constantly check if you have forget to turn it on/off, or constantly using some tools to check it.

@xhoxye https://github.com/lllyasviel/Fooocus/pull/1940 is 95% finished

@lgwjames there currently is no zipping feature as files are handled separately and solely by Gradio. Feel free to provide a separate issue with extensive description as enhancement or directly provide a PR.
