### ISSUE TITLE
ImagePrompt Stuck at Downloading Control Models

### ISSUE THREAD

**Issue by rudraxh** [lllyasviel/Fooocus#1999]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describing the problem**
So, When I tried to run ImagePrompt, with Faceswap or PyraCanny the process Gets to Downloading control models and terminates, When I try to generate again the process ends by reaching Downloading Control models.
I Turned on SysteSwap.
I Turned Off my Firewalls and Defender. But still Issue remains

Here is the processing screenshot of my UI, Now see here it reaches there by microsecond. Then the Generate button appears again nothing happens.
![image](https://github.com/lllyasviel/Fooocus/assets/150448119/d1d0a222-039b-49e8-ab82-a9c1edea662f)

**Full Console Log**

```
A:\AI bitch>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.862
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 6140 MB, total RAM 16104 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 4050 Laptop GPU : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: A:\AI bitch\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [A:\AI bitch\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [A:\AI bitch\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [A:\AI bitch\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.91 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 1482835032781904514
[Fooocus] Downloading control models ...
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/clip_vision_vit_h.safetensors" to A:\AI bitch\Fooocus\models\clip_vision\clip_vision_vit_h.safetensors

Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1454, in connect
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "A:\AI bitch\Fooocus\modules\async_worker.py", line 823, in worker
    handler(task)
  File "A:\AI bitch\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "A:\AI bitch\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "A:\AI bitch\Fooocus\modules\async_worker.py", line 329, in handler
    clip_vision_path, ip_negative_path, ip_adapter_face_path = modules.config.downloading_ip_adapters(
  File "A:\AI bitch\Fooocus\modules\config.py", line 468, in downloading_ip_adapters
    load_file_from_url(
  File "A:\AI bitch\Fooocus\modules\model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "A:\AI bitch\python_embeded\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
Total time: 0.26 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 3384243269532495860
[Fooocus] Downloading control models ...
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/clip_vision_vit_h.safetensors" to A:\AI bitch\Fooocus\models\clip_vision\clip_vision_vit_h.safetensors

Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1454, in connect
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "A:\AI bitch\Fooocus\modules\async_worker.py", line 823, in worker
    handler(task)
  File "A:\AI bitch\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "A:\AI bitch\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "A:\AI bitch\Fooocus\modules\async_worker.py", line 329, in handler
    clip_vision_path, ip_negative_path, ip_adapter_face_path = modules.config.downloading_ip_adapters(
  File "A:\AI bitch\Fooocus\modules\config.py", line 468, in downloading_ip_adapters
    load_file_from_url(
  File "A:\AI bitch\Fooocus\modules\model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "A:\AI bitch\python_embeded\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
Total time: 0.26 seconds
```

**Comment by eddyizm** [comment]
It looks like it could be your internet connection or the huggingface server is having issues. I have seen this before. I would suggest try it again later.

**Comment by rudraxh** [comment]
> It looks like it could be your internet connection or the huggingface server is having issues. I have seen this before. I would suggest try it again later.

It's my first time running this on my PC, So I will continue Running and checking it for a week

**Comment by mashb1t** [comment]
Please try again, most likely HuggingFace had some issues and forced clients to disconnect.

**Comment by rudraxh** [comment]
Okay friend I will try again

**Comment by eddyizm** [comment]
It's hard to say, you could save off your checkpoint model and then do a complete wipe, download a fresh copy and give it another try. 

I would also try to download the file that is failing first,

Eg 
https://huggingface.co/lllyasviel/misc/resolve/main/clip_vision_vit_h.safetensors

Since that is the part that is failing. 
Once downloaded successfully do the same for other file and put them in the correct folder.

**Comment by rudraxh** [comment]
> It's hard to say, you could save off your checkpoint model and then do a complete wipe, download a fresh copy and give it another try. 
> 
> I would also try to download the file that is failing first,
> 
> Eg 
> https://huggingface.co/lllyasviel/misc/resolve/main/clip_vision_vit_h.safetensors
> 
> Since that is the part that is failing. 
> Once downloaded successfully do the same for other file and put them in the correct folder. 

Idk which part is failing, If i download the link mentioned above, Where should I place it? Currently my running model is Juggernaut XL and nothing else, BTW thanks for help man !

**Comment by Knitser** [comment]
Have the same issue with Juggernaut XL, I'll try another model now

**Comment by mashb1t** [comment]
> Where should I place it?
@rudraxh clip vision has to be put to the path_clip_vision you've configured in the config.txt, please check and move it there.

**Comment by rudraxh** [comment]
> > Where should I place it?
> 
> @rudraxh clip vision has to be put to the path_clip_vision you've configured in the config.txt, please check and move it there.

I Have put the file In the given folder path. But The ImagePrompt Advanced features are still not working (Pyracanny etc.), I am using this AI To explain Image generative AI Scenario to my peers at College, So Please Help me With this Problem, I will Provide my contact details if you wanna call, thx

**Comment by mashb1t** [comment]
Are you still not able to download the models or is the process still stuck in the download steps anyways despite you having downloaded the models already? Trying to understand the current issue, thank you for the update.

**Comment by mashb1t** [comment]
Closing as stale, feel free to provide additional information.

**Comment by sohamaa** [comment]
![Screenshot 2024-02-08 212509](https://github.com/lllyasviel/Fooocus/assets/119129683/c9ae53b3-9a07-4e3e-81dd-fb613cabc80c)
I had the same problem.
Make sure you scroll down to the bottom to see if your downloading is still on. If you have a pure connection, try to find the model/models download them individually, and put them in the path that it shows.

**Comment by mumbles13** [comment]
I'm curious as to whether folks have resolved their issues on this. I've been having a similar issue. To my knowledge, it had all been working fine, and I began having issues after changing a drive letter (from E: to D:). In my troubleshooting, I noticed it was no longer loading the config file, and I changed over all the addresses to D:\\ and was no longer getting that error. In any case, my issue seems to only occur when trying to use image prompts. It states:
[Fooocus] Downloading control models ...
[Fooocus] Loading control models ...

D:\AI>Pause

**Comment by mumbles13** [comment]
Just an update for anyone finding similar issues in the future, I resolved my issue by moving all of the checkpoints/loras/etc that I wanted to keep and deleting my Fooocus folder. I then re-extracted the original zip and started fresh letting it download the models it needed. I had tried this before, but I'm traveling and stuck with hotel wifi which disconnects frequently. I believe that caused it to end up in a state where it thought it had the models it needed, but would error out and pause when it tried to load them.

**Comment by rudraxh** [comment]
> Just an update for anyone finding similar issues in the future, I resolved my issue by moving all of the checkpoints/loras/etc that I wanted to keep and deleting my Fooocus folder. I then re-extracted the original zip and started fresh letting it download the models it needed. I had tried this before, but I'm traveling and stuck with hotel wifi which disconnects frequently. I believe that caused it to end up in a state where it thought it had the models it needed, but would error out and pause when it tried to load them.

Okay about to try

**Comment by hosseinrashidi75** [comment]
The two files must be downloaded and placed in the folders I mentioned, otherwise, after installing and pressing the generate button, it will give you the message Downloading Control models and it wants to download itself, which takes a long time; Therefore, download the files from the links below and place them in the folders mentioned:

 File (clip_vision_vit_h.safetensors)

 From the link: https://huggingface.co/llyasviel/misc/resolve/main/clip_vision_vit_h.safetensors
be downloaded

and be placed in the folder: Fooocus\models\clip_vision./

 The second file (ip-adapter-plus_sdxl_vit-h.bin)

 From the link: https://huggingface.co/lllyasviel/misc/resolve/main/ip-adapter-plus_sdxl_vit-h.bin
 be downloaded

and put it in Fooocus\models\controlnet folder.
