### ISSUE TITLE
No access to files and folder anymore. Fooocus blocks them

### ISSUE THREAD

**Issue by alexamore** [lllyasviel/Fooocus#2000]
Hello everybody!

I have an Nvidia 2060 with 6GB with Win10 32GB RAM but when I start Fooocus on my run.bat file and I start working on it using the browser then after few minutes it starts working on the first generation it comes out the error and it goes on "pause" then and I'm not able to access to my folders on the pc anymore.
Some file are not visible at all in the folder and on other folders I don't get access anymore so I have to restart Win10 again and it's always same story.
It's quite wierd and I don't understand where is the problem, I'm getting crazy with my M.2 drives, on [C:] is located the Windows and on [T:] I have all Users files. It's not important where I install FOOOCUS, it's same story and I've also tried to manage the Swap by myself with manual settings.... but nothing! 
Any suggestions? Thank you in advance

**Comment by eddyizm** [comment]
Can you post a screenshot? and a step by step on how you are using it. What you are describing is wild and not related to fooocus at all.
Also the output of your foocus window when you start it up , eg the log output will give us some clues as well.

**Comment by alexamore** [comment]
Here we are! On this work for istance it stops when it works on upscaling. I have 32GB RAM and under stress the machine is using around 65% memory.

The point is that something weird is going on with Swap configuration.

```
T:\temp\FOOOCUS>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset realistic
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'realistic']
Loaded preset: T:\temp\FOOOCUS\Fooocus\presets\realistic.json
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.862
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 6144 MB, total RAM 32677 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: T:\temp\FOOOCUS\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors
Request to load LoRAs [['SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 0.25], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [T:\temp\FOOOCUS\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors].
Loaded LoRA [T:\temp\FOOOCUS\Fooocus\models\loras\SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for UNet [T:\temp\FOOOCUS\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors] with 788 keys at weight 0.25.
Loaded LoRA [T:\temp\FOOOCUS\Fooocus\models\loras\SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for CLIP [T:\temp\FOOOCUS\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors] with 264 keys at weight 0.25.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.86 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 3.0
[Parameters] Seed = 5672392155551910955
[Fooocus] Downloading upscale models ...
[Fooocus] Downloading inpainter ...
[Inpaint] Current inpaint model is T:\temp\FOOOCUS\Fooocus\models\inpaint\inpaint_v26.fooocus.patch
[Fooocus] Downloading control models ...
[Fooocus] Loading control models ...
extra clip vision: ['vision_model.embeddings.position_ids']
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Synthetic Refiner Activated
Synthetic Refiner Activated
Request to load LoRAs [['SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 0.25], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0], ('T:\\temp\\FOOOCUS\\Fooocus\\models\\inpaint\\inpaint_v26.fooocus.patch', 1.0)] for model [T:\temp\FOOOCUS\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors].
Loaded LoRA [T:\temp\FOOOCUS\Fooocus\models\loras\SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for UNet [T:\temp\FOOOCUS\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors] with 788 keys at weight 0.25.
Loaded LoRA [T:\temp\FOOOCUS\Fooocus\models\loras\SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for CLIP [T:\temp\FOOOCUS\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors] with 264 keys at weight 0.25.
Loaded LoRA [T:\temp\FOOOCUS\Fooocus\models\inpaint\inpaint_v26.fooocus.patch] for UNet [T:\temp\FOOOCUS\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors] with 960 keys at weight 1.0.
Request to load LoRAs [['SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 0.25], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [T:\temp\FOOOCUS\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors].
Loaded LoRA [T:\temp\FOOOCUS\Fooocus\models\loras\SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for UNet [T:\temp\FOOOCUS\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors] with 788 keys at weight 0.25.
Requested to load SDXLClipModel
Loading 1 new model
unload clone 1
[Fooocus Model Management] Moving model(s) has taken 0.70 seconds
[Fooocus] Processing prompts ...
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding positive #3 ...
[Fooocus] Encoding positive #4 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Fooocus] Encoding negative #3 ...
[Fooocus] Encoding negative #4 ...
[Fooocus] Image processing ...
Upscaling image with shape (711, 713, 3) ...

T:\temp\FOOOCUS>pause
Premere un tasto per continuare . . .
```
![screen](https://github.com/lllyasviel/Fooocus/assets/30070297/dfa80fee-25a9-4d43-910f-a7bd688a8814)

**Comment by alexamore** [comment]
I use this opportunity also to ask where Fooocus put its temporary files because, between a test and another I've just lost more than 20GB.
After the screenshot I've sent you I've tried setting the swap memory to 60GB (considering I had 80,6GB on C: drive). After that PC is "crashed" during the generation (still at upscaling fase) and when I recovered the system the main drive (C:) is 60GB 👎  
![Image1](https://github.com/lllyasviel/Fooocus/assets/30070297/4f75602e-fdaf-4577-ab69-ac2c2ff85156)

**Comment by mashb1t** [comment]
Your Fooocus installation is located in T:\temp\FOOOCUS, the issue you're describing occurs in T:\Alex\Downloads, which is completely unrelated and not used by Fooocus as it is self-contained (also for python). Please check if other processes have modified the permissions on the Downloads folder.
Closing this ticket as unrelated.

**Comment by alexamore** [comment]
No my friend, previously I've installed on C: and the problem was the same, then I've installed inside my temporary folder in drive T:
As written previously Windows is installed on C: but all personal file are on T: so Documents Images Video Download folder too... it was just an example. There are many other folders I'm not able to open after Fooocus starts working. 
All folders that become unavailable... For the system they don't exist anymore... I have to restart the system to go inside those folders again.

**Comment by alexamore** [comment]
It's definitely related to Fooocus! That's the weird thing.

> Your Fooocus installation is located in T:\temp\FOOOCUS, the issue you're describing occurs in T:\Alex\Downloads, which is completely unrelated and not used by Fooocus as it is self-contained (also for python). Please check if other processes have modified the permissions on the Downloads folder. Closing this ticket as unrelated.

**Comment by mashb1t** [comment]
Please check file permissions on the folders before and after the issue occurs + your Firewall/Antivirus config and reporting log. As this issue is not reproducible, has never occurred on any system before and not been reported before i am 99% certain that this is not Fooocus fault, but maybe your Firewall/Antivirus going crazy or similar.

**Comment by alexamore** [comment]
I will check it but it doesn't happens in any other situations, 24hrs, only after few minutes I've activated Fooocus. So I'm reporting it because I'm getting crazy to find a solution to get images with Fooocus, I can do only online when it doesn't crash with error message. 
Anyway, the first time I've installed Fooocus was on C: and Download folder was accessible but with just few files inside it (indeed I was worried they were cancelled but they don't matter the restart of Windows).
So, I will switch off my firewall/antivirus and I will come back but I hope I don't have to underline once again I don't have this problem normally but only starting Fooocus. Thank you

**Comment by alexamore** [comment]
Hi @mashb1t, I would like to share with forum that the problem on the files/folders is still active even with the brand new Windows 10 installed. I have one of the NVMe SSD 2TB which is not accessible in various files and folders. Just to let you know. I will survive because the important thing is that Fooocus keeps generating pictures.
