### ISSUE TITLE
Just nVidia GPU

### ISSUE THREAD

**Issue by joepram** [lllyasviel/Fooocus#2007]
**Read Troubleshoot**

[x]

**Describe the problem**
ERROR,

**Full Console Log**
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Its just for nVidia GPU?**
Not work with other GPU.  My laptop used Intel(R) Irish(R) Xe Graphics

**Comment by mashb1t** [comment]
Intel Iris GPUs are not supported, but Nvidia + AMD + all DirectML GPUs are. You can run Fooocus by using the argument `--always-cpu` after making sure you have enough system swap set up, see arguments in the readme file and troubleshooting guide.
Please find the minimal requirements here:
https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement
