### ISSUE TITLE
[Feature Request] Low Vram and No Vram options as in ComfyUI

### ISSUE THREAD

**Issue by eduard-sukharev** [lllyasviel/Fooocus#201]
ComfyUI has support for `--novram`,  `--low-vram` and other options for setting VRam for those unlucky stuck with built-in low-end or mid-range shared vram or 4Gb vram.

Add an easy way to run Fooocus with those options

**Comment by czettnersandor** [comment]
Second this. There's an option to launch with --lowvram and --novram, but there's also a condition that checks GPU memory size and if it's <=4086, it will automatically set --lowvram and there's no way to set --novram. See here: https://github.com/lllyasviel/Fooocus/blob/cca0ca704a713ab153938e78de6787609c723cad/backend/headless/fcbh/model_management.py#L117

Also, if I comment this out, it's still not using novram mode for me.

**Comment by mashb1t** [comment]
This is now possible, `--novram` basically translates to `--always-cpu`.
Please find all available arguments here: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#all-cmd-flags

**Comment by Ulf3000** [comment]
> This is now possible, `--novram` basically translates to `--always-cpu`. Please find all available arguments here: [lllyasviel/Fooocus?tab=readme-ov-file#all-cmd-flags](https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#all-cmd-flags)

thats wrong, --novram still uses gpu ...

**Comment by mashb1t** [comment]
@Ulf3000 you're right, i was mistaken when writing the comment.

For clarification:
- `--no-vram` still uses GPU for processing, but RAM/swap instead of VRAM.
- `--always-cpu` does not use the GPU at all, neither VRAM nor processing.
