### ISSUE TITLE
Cuda error : OutOfMemoryError

### ISSUE THREAD

**Issue by fedyfausto** [lllyasviel/Fooocus#2010]
_Originally posted by @fedyfausto in https://github.com/lllyasviel/Fooocus/issues/1984

In the original issue (closed and I do not know why because the issue has not been solved) I posted an issue with the Cuda Out of VRAM. The stranger thing is that Fooocus works well in Google Collab with only 12 of RAM (VRAM and RAM I think), but in our server with:

Ubuntu 22.04
NVIDIA Tesla K80 x2
12 GB of VRAM (each Tesla)
64 GB of RAM
50 GB of Swap Memory
8- core

application crashes with CudaOutOfMemory. A little fix I discovered was the launch of the application with the --attention-split param but if I use the Image Input the application crashes. Do we need to do something in Linux to FORCE fooocus/pytorch to use RAM and Swap? Because it seems that the only RAM used is the VRAM to load everything.

**Comment by mashb1t** [comment]
Oh ok, then there must have been a misunderstanding, as you wrote that it worked with split attention (see https://github.com/lllyasviel/Fooocus/issues/1984#issuecomment-1901033815 and the comment before).

As of experience, for other users his had most likely to do with swap not being configured correctly. You can force RAM usage by adding the arg `--always-no-vram`, but this is probably not what you want long-term but only for debugging.
You might also have to specify a GPU as you have two in your system, but i'm not certain if this is necessary.

Please check the arg and use one fixed GPU to debug further. Looking forward to the results!

**Comment by mashb1t** [comment]
@fedyfausto is this still an issue or had the issue been solved on your side?

**Comment by mashb1t** [comment]
Closing as stale
