### ISSUE TITLE
Inpaint/Outpaint IP

### ISSUE THREAD

**Issue by xale76** [lllyasviel/Fooocus#2018]
In inpaint/outpaint and in particular when a prompt is requested why it is not possible to use IP adapter combined with text?

**Comment by mashb1t** [comment]
![Screenshot 2024-01-22 at 16 37 38](https://github.com/lllyasviel/Fooocus/assets/9307310/00dbb0f7-2407-4b0d-82dd-8c887fcfb97a)

Please find the option "Mixing Image Prompt and Inpaint" in Advanced > Advanced > Developer Debug Mode > Control.
