### ISSUE TITLE
[Feature Request] Animatediff extension

### ISSUE THREAD

**Issue by brentjohnston** [lllyasviel/Fooocus#202]
I am able to run animatediff on automatic1111 at 512x512 with 1.4 motion model and it works but it takes over 5 minutes to generate on two second video. On my old 4080 desktop it would only take like 20 seconds. I feel if it was integrated into this somehow it would work great. It really is a cool extension when you can get it working if you have enough vram!

https://github.com/continue-revolution/sd-webui-animatediff

**Comment by tiwentichat** [comment]
+1

Feature Request: Animatediff Extension,

**Comment by mashb1t** [comment]
Superseded by https://github.com/lllyasviel/Fooocus/issues/937
