### ISSUE TITLE
Won't Run

### ISSUE THREAD

**Issue by GunnyNinja** [lllyasviel/Fooocus#2022]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

Steps I have taken:
Downloaded.
Extracted
Run.bat
Nothing happens.

**Comment by mashb1t** [comment]
> Describe the problem
> A clear and concise description of what the bug is.
> 
> Full Console Log
> Paste full console log here. You will make our job easier if you give a full log.

Please fill out the issue template and provide necessary information in order to be able to analyse it further and to receive proper feedback. Thanks!

**Comment by GunnyNinja** [comment]
> > Describe the problem
> > A clear and concise description of what the bug is.
> > Full Console Log
> > Paste full console log here. You will make our job easier if you give a full log.
> 
> Please fill out the issue template and provide necessary information in order to be able to analyse it further and to receive proper feedback. Just to make sure: have you read the linked [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)? Thanks!

Yes. Nothing in the guide about it doing nothing.

**Comment by mashb1t** [comment]
Please provide the full console log and some screenshots about your hardware utinization, as analysis can't happen without it.

**Comment by mashb1t** [comment]
@GunnyNinja is this still relevant?

**Comment by mashb1t** [comment]
Closing as stale

**Comment by GunnyNinja** [comment]
> Please provide the full console log and some screenshots about your hardware utilization, as analysis can't happen without it.

Sorry, been away. There is no log, because the console never opens.

**Comment by mashb1t** [comment]
@GunnyNinja run.bat doesn't open a terminal? Sorry, i didn't mean console as jn browser console, but terminal output.

**Comment by GunnyNinja** [comment]
> @GunnyNinja run.bat doesn't open a terminal? Sorry, i didn't mean console as jn browser console, but terminal output.

Corect. Nothing happens.
