### ISSUE TITLE
How to configure anime/ realistc bat. I can only find the config for the run.bat. Is there a way

### ISSUE THREAD

**Issue by NajiusMaximus** [lllyasviel/Fooocus#2024]
I can only find the config for the run.bat. Is there a way to configure the anime and realistic one?

**Comment by eddyizm** [comment]
What are you trying to change? 
The config is for the whole system, you other two you can edit via the presets. 
![image](https://github.com/lllyasviel/Fooocus/assets/12236892/5771d182-9364-40fe-a607-08158c8f9268)
