### ISSUE TITLE
How to control the generation position

### ISSUE THREAD

**Issue by freek99** [lllyasviel/Fooocus#2027]
Hi, such as text to image, how to control the object in the generated image to be at a certain position in the image, such as near the right, near the bottom？Can I achieve this effect with prompt words?

**Comment by poor7** [comment]
Sometimes this can be done using promts. The positioning accuracy is very low.

**Comment by mashb1t** [comment]
you can use prompts to create an initial image and then reiterate on the image using inpainting, which allows more granular control for object positioning.
You can also check out https://github.com/fenneishi/Fooocus-ControlNet-SDXL, but it's not maintained anymore.
