### ISSUE TITLE
Is my PC good for Fooocus?

### ISSUE THREAD

**Issue by StepHaze** [lllyasviel/Fooocus#2033]
Hello,
I'm very interested in image generation.
So I would like to ask experts, is my PC good for Fooocus?

I have Ubuntu 18.04 here,
Processor: Intel Cor i5-9300H CPU @ 2.40GHz × 8
Graphics: NVIDIA GeForce GTX 1650
SSD: 500 GB

Thanks in advance!

**Comment by eddyizm** [comment]
Your nvidia is going to be really slow, 4GB vram. Worth a try, I know a 4GB nvidia can work just not fast.

**Comment by mashb1t** [comment]
> Your nvidia is going to be really slow, 4GB vram. Worth a try, I know a 4GB nvidia can work just not fast.

^ Exactly this, don't expect any magic from it and prepare a coffee or drink of choice while generating, but in general it should work.

**Comment by dude-with-the-long-username** [comment]
@StepHaze Did it work?

**Comment by maryf-t-s** [comment]
hello everyone, I'm joining the thread, what is the cheapest computer that can meet fooocus requirements, so that I can download fooocus to a local disk and the images are generated quickly, many thanks for any possible suggestions, link to the product...
