### ISSUE TITLE
Can intel GPU use fooocus?

### ISSUE THREAD

**Issue by chenhaokui** [lllyasviel/Fooocus#2034]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

**Comment by mashb1t** [comment]
Sorry, Intel ARC / IRIS GPUs are not (yet) supported, see https://github.com/lllyasviel/Fooocus/issues/141. Fooocus currently supports GPUs manufactured by Nvidia, AMD and Apple (MacOS in general).
Closing as duplicate.

**Comment by chenhaokui** [comment]
> Sorry, Intel ARC / IRIS GPUs are not (yet) supported, see #141. Fooocus currently supports GPUs manufactured by Nvidia, AMD and Apple (MacOS in general). Closing as duplicate.

Sorry to hear that, but thanks for your reply.

**Comment by mashb1t** [comment]
There now is a PR for support of Intel ARC GPUs, feel free toc check it out: https://github.com/lllyasviel/Fooocus/pull/2120
