### ISSUE TITLE
ubuntu error 

### ISSUE THREAD

**Issue by alizmod** [lllyasviel/Fooocus#2035]
![D5E652B0-7A4E-47AD-98DD-C8AA05D6CECF](https://github.com/lllyasviel/Fooocus/assets/119986364/da016bbd-c801-4f83-a1ca-3994af411ac4)

Please help

**Comment by eddyizm** [comment]
From the error message it looks like you are missing a GL library, 
`apt-get update && apt-get install ffmpeg libsm6 libxext6  -y`
Found this [here](https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo#63377623)
I'd give that a try although it looks like you are running this on a mobile device?

**Comment by alizmod** [comment]
Termius ssh connection device

**Comment by mashb1t** [comment]
@alizmod please make sure to follow all steps in https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#linux-using-python-venv and install the missing package(s) as described in above comment.
