### ISSUE TITLE
Style Thumbnail Rendered Incorrectly

### ISSUE THREAD

**Issue by thiner** [lllyasviel/Fooocus#2040]
**Read Troubleshoot**

[x]  I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
The style thumbnails became incorrect after several rounds of search, check and uncheck operations. 
![image](https://github.com/lllyasviel/Fooocus/assets/1897227/7215d12b-3a57-47e6-822c-6b0b05acbdd9)

**Full Console Log**
Not a backend error, no console logs.

**Comment by mashb1t** [comment]
Hey @thiner, thank you for reporting the issue. I am not able to reproduce the issue, even after 10 min constantly checking/unchecking styles and searching. Is this reproducible on your side and can you make a step-by-step guide to reproduce the behaviour on another device?

**Comment by thiner** [comment]
1. try different styles combination for several shots. You should see the order styles is different to default.
2. Type something in the search input, the styles will be reordered again. Now you should see some of the thumbnails are wrong.
![image](https://github.com/lllyasviel/Fooocus/assets/1897227/b29ef576-b903-42e0-8afa-d2a91cb164e1)

In the above screenshot, my mouse pointer is moved on "Futuristic Vaporwave", but the thumbnail is wrong obviously.

**Comment by mashb1t** [comment]
Still not able to reproduce... can somebody else confirm this is an actual bug?

**Comment by thiner** [comment]
I tried several rounds, I am sure it's reproducible. Steps as below:

1. Pick up a style from the middle of the list, say "Craft Clay". Generate a image with the selected style. You should see the style orders changed now, similar as below:
![image](https://github.com/lllyasviel/Fooocus/assets/1897227/62515993-e807-45fb-baec-085ee0c1cfc7)

2. Search something from the input field, e.g. "`mini`". You should see `Misc Minialist`, `Minimalism` come to the head of the list. Now, move mouse pointer to the style names, you should see the mismatch of thumbnail  of some styles(not all of them).
![image](https://github.com/lllyasviel/Fooocus/assets/1897227/7932b823-b981-4244-9d6b-4e840810eaa0)

**Comment by crohrer** [comment]
The bug is caused by this line in Gradio (the problem is `(i)`): https://github.com/gradio-app/gradio/blob/84249043b476836a87d1cd5bef202c9aaaa58296/js/radio/Index.svelte#L68 
They use the index of the array as the key. When the search is used, it removes items from the array and suddenly the keys don't match the content. For our use case here, it would work if they use `display_value` as the key.

**Comment by mashb1t** [comment]
@crohrer can you maybe check if there is already a PR / Issue for Gradio and if not create one? Much appreciated, thanks!

**Comment by mashb1t** [comment]
Closing as stale + not a bug of Fooocus, but rather Gradio.
