### ISSUE TITLE
concurrent operations

### ISSUE THREAD

**Issue by mrzjl** [lllyasviel/Fooocus#2049]
when multiple users are using it, the image generation becomes chaotic. User A’s image displayed in User B’s location.

**Comment by mashb1t** [comment]
This has already been fixed in https://github.com/lllyasviel/Fooocus/pull/981, but not yet merged. Feel free to apply the changes of the feature (they are plenty) or use my fork, which also includes many more improvements (see readme): https://github.com/mashb1t/Fooocus

**Comment by mashb1t** [comment]
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/713
