### ISSUE TITLE
How to train my self inpaint model?

### ISSUE THREAD

**Issue by zhangzhengyi12** [lllyasviel/Fooocus#2051]
I have some custom requirements and want to train a inpaint model, similar to fooocus inpaint, but I don't know how to go about it and where to find the relevant training scripts

**Comment by eddyizm** [comment]
There are a lot of youtube videos on it. This is not really related to Fooocus.

**Comment by mashb1t** [comment]
@zhangzhengyi12 feel free to check out https://github.com/bmaltais/kohya_ss. You can find tutorials on YouTube!

**Comment by haoqiangyu** [comment]
The processing idea of Fooocus's inpainting function is relatively new, and the process used is also different from other common inpainting models.

**Comment by haoqiangyu** [comment]
The processing idea of Fooocus's inpainting function is relatively new, and the process used is also different from other common inpainting models.
@eddyizm @mashb1t Can you provide a Youtube video of related training?
@lllyasviel Could you please share any information about the training details of the inpainting model?
