### ISSUE TITLE
image has watermark

### ISSUE THREAD

**Issue by mrzjl** [lllyasviel/Fooocus#2052]
I generated an image with a watermark with default settings. The watermark is a random case. Is it possible that the model has been trained using images with watermarks?
[image with watermark](https://github.com/lllyasviel/Fooocus/assets/15856132/c49e65e0-01fd-4ad8-a4c8-5409664b0858)

**Comment by thiner** [comment]
I think that's the model behavior, not Fooocus. You may either regenerate or change the model you are using.

**Comment by f0n51** [comment]
Yes, thats definately a model / checkpoint / style thingy. Which settings did you use? 

You can either try to generate a new image or try to remove the watermark with the inpaint feature.

**Comment by mashb1t** [comment]
@mrzjl This is definitely not an issue of Fooocus, as no watermark is introduced, but the training data of the model you used.
You can mitigate watermark / signatures from appearing in generated inages by using the negative prompt or using inpainting, as mentioned before.
