### ISSUE TITLE
OSX

### ISSUE THREAD

**Issue by peterspeeder** [lllyasviel/Fooocus#2057]
I am wondering if this works for mac amd gpus

**Comment by mashb1t** [comment]
Works for MacOS in general (unofficial guideline in https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#mac). There is no official support for any separate GPU on MacOS, but you might be able to follow the MacOS tutorial and experiment with directml or rocm. No guarantee though as this hasn't been tested.
