### ISSUE TITLE
Argument output-path is not working

### ISSUE THREAD

**Issue by mqtt-fan** [lllyasviel/Fooocus#2065]
Hi all,

I mounted my google drive in colab and tried:
`!python entry_with_update.py --output-path /content/drive/MyDrive/fooocus --share `

But the output folder (checked in config.txt and generating images) is still:
`/content/Fooocus/outputs`

It works only if I stop the runtime and change the config.txt file manually to  "path_outputs": "/content/drive/MyDrive/fooocus"

Am I missing something? Is there a trick?

**Comment by mashb1t** [comment]
Confirmed, --output-path is not used for saving assets. I assume this is one of the args from ComfyUI, which has been ported but actually never implemented.

**Comment by eddyizm** [comment]
@mashb1t Is this one in the works anywhere? I may be able to fix this as I also was looking to use that feature in colab.

**Comment by mashb1t** [comment]
AFAIK not, feel free to create a PR. Much appreciated!

**Comment by eddyizm** [comment]
testing with another path in colab is working after a few stumbles on my part. 
`!python entry_with_update.py --output-path /content/sample_data`
![image](https://github.com/lllyasviel/Fooocus/assets/12236892/addd45cd-1d8d-4914-bf16-4bd06e124ec3)

will clean up

**Comment by eddyizm** [comment]
https://github.com/lllyasviel/Fooocus/pull/2074
