### ISSUE TITLE
save image

### ISSUE THREAD

**Issue by Renan7696** [lllyasviel/Fooocus#2073]
Is there any way to change where the images are saved? I want to install it on the SSD, but i don't want the images to be saved on the SSD because of the storage. Thank you.

**Comment by speedytechdev** [comment]
You could right-click them and select save as. Unless I'm misunderstanding you?

**Comment by mashb1t** [comment]
Feel free to change the config file to your liking. You can find a tutorial config file alongside of it and when https://github.com/lllyasviel/Fooocus/pull/2074 is merged you can also use the arg again.
