### ISSUE TITLE
Change to custom Aspect Ratio 

### ISSUE THREAD

**Issue by rafstahelin** [lllyasviel/Fooocus#2076]
I’ve trained my Lora’s in 1024x1280 aspect ratio. 

Can i use this aspect somehow in fooocus?

How do i set it? I dont see a custom option for aspect ratio’s

**Comment by mashb1t** [comment]
You can change the config for permanent usage or the advanced settings for temporary width and height asjustments, see https://github.com/lllyasviel/Fooocus/issues/1878#issuecomment-1887267562

**Comment by rafstahelin** [comment]
I tried using "available_aspect_ratios : "1024x1280","
but it doesnt appear in the Aspect Ratios tab

**Comment by rafstahelin** [comment]
> please make sure to provide them in the format "available_aspect_ratios": "1024x1280",
> 
> and check terminal output. You'll be informed in terminal if there is an issue with a value or your config in general in the output.

It's working had to check the syntax thank you
