### ISSUE TITLE
The new model for anime preset

### ISSUE THREAD

**Issue by vanguard-bit** [lllyasviel/Fooocus#2078]
I just used the new model for anime and its wonderful...a big upgrade from blue pencil...
And i noticed it is similar to animagine v3 are they the same?

**Comment by poor7** [comment]
"The anime model is animaPencilXL_v100. Note that:

animaPencilXL_v100 = [animagine-xl-3.0](https://huggingface.co/cagliostrolab/animagine-xl-3.0) + blue_pencil-XL

blue_pencil-XL = [a merge of about 150 sdxl models](https://huggingface.co/bluepen5805/blue_pencil-XL) (including [Kohaku-XL beta](https://civitai.com/models/162577/))

In the final round of test, the model animaPencilXL_v100 and [AAMXL(another animagine v3 mix)](https://civitai.com/models/269232?modelVersionId=303526) are both slightly more flexiable to use than animagine-xl-3.0, especially when the prompt is short or casually written. (the original animagine-xl would require formatted prompts, and shorter prompts or casual prompts sometimes will cause artifacts or saturation problems. Using a merge from animagine-xl, like animaPencilXL_v100 or AAMXL, can fix this problem.)"
https://github.com/lllyasviel/Fooocus/discussions/2067
