### ISSUE TITLE
Can't disable Phantom LoRA 6 

### ISSUE THREAD

**Issue by Scartafist** [lllyasviel/Fooocus#2085]
When looking at my logs it shows that there is a LoRA 6 being enabled but when using Fooocus this option simply doesn't exist. Problem started on the 10th of January. Any and all help is appreciated. 

Update 1: Just uploaded full output log

![LoRA6 Logs](https://github.com/lllyasviel/Fooocus/assets/73492958/d3cc8898-ddfb-4ef5-9f01-0a2b49aed05c)
![Github LoRA6](https://github.com/lllyasviel/Fooocus/assets/73492958/bba33ceb-7304-45d6-8f0c-144d6cf74d00)
[LoRA6 Log 2.txt](https://github.com/lllyasviel/Fooocus/files/14078127/LoRA6.Log.2.txt)

**Comment by eddyizm** [comment]
Please post the full output of the terminal.

**Comment by Scartafist** [comment]
> `Performance: Extreme Speed` This requires the lcm lora

thank you :)
