### ISSUE TITLE
super slow download speed of files..

### ISSUE THREAD

**Issue by BORICUAPR** [lllyasviel/Fooocus#2086]
![Screenshot 2024-01-28 181137](https://github.com/lllyasviel/Fooocus/assets/25351626/b2026210-7c15-45fd-9348-7dbc2bd2d6ce)

im trying to download files faster, i got 1gb download speed at home and im using ethernet.
and i only get max 3mb download speed of the ai files

**Comment by eddyizm** [comment]
I was getting similar speeds. I don't think this is related to fooocus.

If you download the model directly via your browser/huggingface or a curl/wget command you can verify the speed is different.

**Comment by mashb1t** [comment]
This isn't an issue of Fooocus but either your internet connection or Huggingface limiting speeds. It might be possible that they now also started throttling unauthenticated connections, but i haven't experienced such behavior byself.
