### ISSUE TITLE
Better Hands

### ISSUE THREAD

**Issue by m00nsp3ll** [lllyasviel/Fooocus#2087]
everything is perfect but hands are mostly problematic, any solution? any negative prompt solves the issue? thanks

**Comment by E2GO** [comment]
Some recent news as with _hands_ in negative prompt and even with some weighting added could make hands a little bit better. Just _hands_ - nothing more like bad hands and etc...

**Comment by m00nsp3ll** [comment]
in my opinion a light adetailer could be added to the code just for hands and minor improvoments for faces

**Comment by f0n51** [comment]
The new Juggernaut 8 checkpoint comes with improved hand / fingers generation and there is already a pull request to use the Juggernaut 8 checkpoint as the new standard checkpoint in Fooocus. 
You can use the inpaint feature too for improving hands or fingers.

**Comment by mashb1t** [comment]
@m00nsp3ll please check out the solution mentioend above ("hands" in negative prompt) and try JuggernautXL V8. If this doesn't provide sufficient control feel free to use inpainting on the hands.

Also https://github.com/lllyasviel/Fooocus/issues/1831 already exists, closing this issue in favor for it.
