### ISSUE TITLE
Why Fooocus often generates chess board incorrectly?

### ISSUE THREAD

**Issue by StepHaze** [lllyasviel/Fooocus#2091]
Either the board dimensions do not correspond to 8 by 8, or the black and white squares do not follow each other.

**Comment by poor7** [comment]
He generally has difficulty with any precise things. He can't even draw 3 fish! Draws first 2, then 4, etc. And you want him to draw something exactly for you. He is an artist, not an engineer, that’s how he sees it!

**Comment by eddyizm** [comment]
My chess board images were interesting to say the least.

**Comment by StepHaze** [comment]
> He generally has difficulty with any precise things. He can't even draw 3 fish! Draws first 2, then 4, etc. And you want him to draw something accurate for you. He is an artist, not an engineer, that’s how he sees it!

Maybe there's a magic prompt for a correct chessboard ?

**Comment by poor7** [comment]
I do not know this.

**Comment by mashb1t** [comment]
I don't know if there is "magic prompt" to make chessboards look correctly, but this is not an issue of Fooocus in general, but rather with thes Stable Diffusion XL model, which was trained on specific images.
I couldn't find chessboard LoRAs on civitai.com, but maybe this is sufficient for you: https://creator.nightcafe.studio/model/1cSWBdvyITTzBG2D2SDl
Closing as not related to Fooocus.
