### ISSUE TITLE
High RAM Usage and little VRam being used.

### ISSUE THREAD

**Issue by Hetster1969** [lllyasviel/Fooocus#2093]
While Fooocus is running the RAM Usage steadily increases. If i generate the ram goes to 100% usage, I have 24gb Installed, yet it starts at 8gb and steadily goes to 19gb (Python cmd window), with windows and Firefox using the rest of the spare GB it freezes my system for several minutes. Its unusable for me at this point.. Been trying a few days. I have other AI tools installed that all use python from GitHub and none have the memory leak issue.
![image](https://github.com/lllyasviel/Fooocus/assets/157532588/65985adf-f7ac-4697-9a0e-3aef166851ea)

**Comment by LiteSoul** [comment]
Same for me, it clogs my RAM until 100% and it freezes for a minute. Then moves the model to GPU and RAM decreases a bit.

**Comment by Hetster1969** [comment]
8 mins for me.. total freeze, Seen quite a few with same issue but not sure if its been brought up in official GitHub page

**Comment by mashb1t** [comment]
Please provide the full console log so this can be analysed. Are you by chance using an AMD graphics card?

**Comment by Hetster1969** [comment]
yes I am.. and full log as in? from opening to when i can no longer do anything or just when i open Foooocus. ?
And i assume you mean the cmd window

**Comment by mashb1t** [comment]
yes, terminal output (cmd or powershell)

**Comment by GodFazer** [comment]
> While Fooocus is running the RAM Usage steadily increases. If i generate the ram goes to 100% usage, I have 24gb Installed, yet it starts at 8gb and steadily goes to 19gb (Python cmd window), with windows and Firefox using the rest of the spare GB it freezes my system for several minutes. Its unusable for me at this point.. Been trying a few days. I have other AI tools installed that all use python from GitHub and none have the memory leak issue. ![image](https://private-user-images.githubusercontent.com/157532588/300547665-65985adf-f7ac-4697-9a0e-3aef166851ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTQ5OTEsIm5iZiI6MTcwNjYxNDY5MSwicGF0aCI6Ii8xNTc1MzI1ODgvMzAwNTQ3NjY1LTY1OTg1YWRmLWY3YWMtNDY5Ny05YTBlLTNhZWYxNjY4NTFlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxMTM4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGQ1Mzc5MDZhMjBhODcyZDM1MjQ3NWQzMWRkYTY2YjI0MTZjYzkxMjU1MmRiMGU3OGI2MWM5YWM4YTM0MzZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HUuOX-aTRfFD3jAQkb2t7fVdgi9dL4MTu8wpz7pj1v4)

run it with high productivity VRAM parametr

**Comment by mashb1t** [comment]
@Hetster1969 contrary to your previous comment you're not using an AMD GPU but a NVIDIA GeForce GTX 1050 Ti with 4GB VRAM. High RAM usage is to be expected when running on low end GPUs with insufficient VRAM. 15GB RAM usage are possible, but uncommon.
Please check if using the argument `--always-cpu` works better for you.

**Comment by mashb1t** [comment]
If you'd reallyrun a high VRAM GPU i'd recommend running `--attention-split --disable-offload-from-vram --always-high-vram` or even `--always-gpu` for maximum performance. Closing this issue, as you're using a 1050 TI and this is expected.
