### ISSUE TITLE
Anime Preset Issue 

### ISSUE THREAD

**Issue by Galactica80** [lllyasviel/Fooocus#2096]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
Hi you recently changed the Anime preset like a couple of days ago and it's totally messed up my upscale generations it's completely changed the look of the upscales (A real downgrade) faces etc, could you post the original settings for the Anime preset or create an additional "Anime Original" preset with the original settings for older users of the application please?

**Comment by mashb1t** [comment]
@Galactica80 +1 what @eddyizm said, the easiest way to create a new template is by copying an existing one and adjusting the values/models.
You should just be able to c&p the template from an old version, rename it and use it as --preset arg, the changes  only introduced one new key `previous_default_models`.

**Comment by Galactica80** [comment]
Thanks, guys I really appreciate the help!
