### ISSUE TITLE
An error occurs when running the run.bat file.

### ISSUE THREAD

**Issue by donkw** [lllyasviel/Fooocus#2101]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.
Yes

**Describe the problem**
When I run the *.bat file, I encounter an 'update failed' error, yet the program still runs normally. How can I ensure that I'm using the latest version?

**Full Console Log**
![image](https://github.com/lllyasviel/Fooocus/assets/32894787/c7cabaee-4b06-4fcd-bea3-1bfc69897e46)

**Comment by eddyizm** [comment]
Can you post you full console log and what os version you are using?

**Comment by donkw** [comment]
> Can you post you full console log and what os version you are using?
The picture above displays all the information shown in the command prompt window, and I am using Windows 11.
![image](https://github.com/lllyasviel/Fooocus/assets/32894787/8165fd87-57ff-4cee-a18f-9b460d3b647d)

**Comment by mashb1t** [comment]
Please ensure you can execute `git pull` in your Fooocus folder (the one in E:\Fooocus_win642-1-831\Fooocus) and you have no changes in your source code, see `git status`.

**Comment by donkw** [comment]
> Please ensure you can execute `git pull` in your Fooocus folder (the one in E:\Fooocus_win642-1-831\Fooocus) and you have no changes in your source code, see `git status`.

This is a screenshot of the messages from executing git pull and git status, but there's still an update failed error prompt when running the *.bat file.
![image](https://github.com/lllyasviel/Fooocus/assets/32894787/0bb81e2c-30f9-463b-889d-4f1cbf2276fa)
![image](https://github.com/lllyasviel/Fooocus/assets/32894787/0d723a77-2df8-4313-a24c-3c30393e2104)

**Comment by donkw** [comment]
Even if this error occurs, we can still update to the latest version using git pull, right?

**Comment by eddyizm** [comment]
you can also do a `git log` and see that you have all the latest commit but yes, to answer your question, you should have the latest. 
when you run it again, you should see the focus version displayed.
