### ISSUE TITLE
REQUEST: Multi-GPU Support

### ISSUE THREAD

**Issue by SurvivaLlama** [lllyasviel/Fooocus#211]
Great program. I have it running on unRaid, through a docker, on my home server. I can access it anywhere using tailscale.
I have 1 request. Is there any way to add multi-GPU support? I have 2x 1070s and multi-gpu support would greatly increase my build time.

**Comment by doutorinfamous** [comment]
Hi @SurvivaLlama, how did you run that in unraid since that is no docker in community apps?

**Comment by mashb1t** [comment]
Duplicate of https://github.com/lllyasviel/Fooocus/issues/292
