### ISSUE TITLE
Cover of book

### ISSUE THREAD

**Issue by StepHaze** [lllyasviel/Fooocus#2111]
Hello dear Fooocus users and developers!
Which text prompt and which style should I use to generate cover of book?

**Comment by poor7** [comment]
You won't get a full-fledged cover, as there will be errors in the text, but you can generate a picture for the cover.

**Comment by mashb1t** [comment]
Please find prompts for book covers in https://civitai.com/search/models?sortBy=models_v5&query=book%20cover.
