### ISSUE TITLE
Same faces all the time

### ISSUE THREAD

**Issue by m00nsp3ll** [lllyasviel/Fooocus#2115]
I am trying to generate lets say a business man walking on the street and want to create 10 images, but all the time faces are the same i dont know what i am doing wrong? i want to have different faces

**Comment by lgwjames** [comment]
have you anything in imported image? add something like a a business man walking on the street, 40 years old, in a blakc suit etc

**Comment by m00nsp3ll** [comment]
no i just wrote a prompt, oh if i import and image + prompt than it will create multiple images faces poses based on referance image ?

**Comment by m00nsp3ll** [comment]
Well basically my main goal is to create variations, different faces different poses i could not manage to do it, i am sorry i f i am writing my issues in the wrong place, i really like to use fooocus and trying to master it

**Comment by mashb1t** [comment]
you can start describing the business mans facial feature in the prompt, such as "with a beard", "glasses", "wearing a fedora" etc.

> no i just wrote a prompt, oh if i import and image + prompt than it will create multiple images faces poses based on referance image ?

Yes, you can use both vary subtle and vary strong plus up to four images as reference in image prompt if you want to. Feel free to adjust the image amount when doing variations.

**Comment by m00nsp3ll** [comment]
Well i get used to work with Automatic1111 and if i describe "with a beard", "glasses", "wearing a fedora" it gives me variations, but in foocus it kind of tries to generate me same businessman all the time, i am trying to figure out the prompt structure of foocus to enter positive and negative prompt and it generates me variety of business mans with different faces poses etc.

Thanks a lot for the answers and i am sorry for my silly questions

**Comment by poor7** [comment]
I get them all different and in different poses. The settings are all default.
![snap1](https://github.com/lllyasviel/Fooocus/assets/154618384/1afd10d4-5890-493f-a865-67f7f91cdf83)

**Comment by m00nsp3ll** [comment]
Thank you for reply, is there a trick or prompt like it will generate different shirt colors, or different suit colors for each image?

**Comment by mashb1t** [comment]
@m00nsp3ll you can use a prompt with wildcard for color, e.g. "__color__ suit", which will then pull a random line from the corresponding wildcard file.

**Comment by m00nsp3ll** [comment]
@mashb1t thanks a lot for your answers, i did not know that the default Fooocus interface supports wildcards, or do i neeed to modified version of fooocus to use it ?

P.s: is it possible to use Foocus with automatic1111 or comfyui?

thanks a lot

**Comment by mashb1t** [comment]
@m00nsp3ll wildcards have been inplemented in the main branch of Fooocus quite a while ago.

Fooocus is a separate application and not only a frontend which you can switch the backend for. It also includes various optimisations for image generation, which will lead to better results.

You're welcome :)

**Comment by m00nsp3ll** [comment]
danke vielmals,
I am testing it on my macbook air m2 16gb ram but its quite slow so testing it on collab for now,

Looking imto tutorials to use wildcards, The project i am working on is a creating different images in each creation like if i write a business man walking on the street should give me results with different faces, beard, hat, glasses, different skin colors, different accesories etc.

Nochmal danke vielmals für ihre antworte
