### ISSUE TITLE
running very slowly, and stucked on last sample

### ISSUE THREAD

**Issue by igninjaz** [lllyasviel/Fooocus#2122]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

**Comment by igninjaz** [comment]
from yesterday, the program suddently started loading very slowly, loading samples very slowly, stuck on last and have to refresh to start again. using google colab paid version v100 high ram, thanks

**Comment by mashb1t** [comment]
Please provide the full terminal output / colab command output, thanks!

**Comment by igninjaz** [comment]
Timestamp,Level,Message
"Feb 1, 2024, 9:16:53 AM",INFO,Kernel interrupted: f154f8d1-d2fd-44f5-afb9-7b3f2add77b8
"Feb 1, 2024, 8:46:55 AM",INFO,"Kernel started: f154f8d1-d2fd-44f5-afb9-7b3f2add77b8, name: python3"
"Feb 1, 2024, 8:37:20 AM",INFO,Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
"Feb 1, 2024, 8:37:20 AM",INFO,Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
"Feb 1, 2024, 8:37:20 AM",INFO,http://172.28.0.2:9000/
"Feb 1, 2024, 8:37:20 AM",INFO,Jupyter Notebook 6.5.5 is running at:
"Feb 1, 2024, 8:37:20 AM",INFO,http://172.28.0.12:9000/
"Feb 1, 2024, 8:37:20 AM",INFO,Jupyter Notebook 6.5.5 is running at:
"Feb 1, 2024, 8:37:20 AM",INFO,Serving notebooks from local directory: /
"Feb 1, 2024, 8:37:20 AM",INFO,Serving notebooks from local directory: /
"Feb 1, 2024, 8:37:18 AM",INFO,google.colab serverextension initialized.
"Feb 1, 2024, 8:37:18 AM",INFO,google.colab serverextension initialized.
"Feb 1, 2024, 8:37:18 AM",INFO,"Authentication of /metrics is OFF, since other authentication is disabled."
"Feb 1, 2024, 8:37:18 AM",INFO,"Authentication of /metrics is OFF, since other authentication is disabled."
"Feb 1, 2024, 8:37:18 AM",INFO,Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
"Feb 1, 2024, 8:37:18 AM",INFO,Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
"Feb 1, 2024, 8:37:18 AM",WARNING,    	/root/.jupyter/jupyter_notebook_config.json
"Feb 1, 2024, 8:37:18 AM",WARNING,    	/root/.jupyter/jupyter_notebook_config.json
"Feb 1, 2024, 8:37:18 AM",WARNING,    	/root/.local/etc/jupyter/jupyter_notebook_config.json
"Feb 1, 2024, 8:37:18 AM",WARNING,    	/root/.local/etc/jupyter/jupyter_notebook_config.json
"Feb 1, 2024, 8:37:18 AM",WARNING,    	/usr/etc/jupyter/jupyter_notebook_config.json
"Feb 1, 2024, 8:37:18 AM",WARNING,    	/usr/etc/jupyter/jupyter_notebook_config.json
"Feb 1, 2024, 8:37:18 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.json
"Feb 1, 2024, 8:37:18 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.json
"Feb 1, 2024, 8:37:18 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json
"Feb 1, 2024, 8:37:18 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json
"Feb 1, 2024, 8:37:18 AM",WARNING,    	/etc/jupyter/jupyter_notebook_config.json
"Feb 1, 2024, 8:37:18 AM",WARNING,    	/etc/jupyter/jupyter_notebook_config.json
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.485 NotebookApp] Loaded config file: /root/.jupyter/jupyter_notebook_config.py
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.485 NotebookApp] Loaded config file: /root/.jupyter/jupyter_notebook_config.py
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.482 NotebookApp] Looking for jupyter_notebook_config in /root/.jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.482 NotebookApp] Looking for jupyter_notebook_config in /root/.local/etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.482 NotebookApp] Looking for jupyter_notebook_config in /root/.jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.482 NotebookApp] Looking for jupyter_notebook_config in /root/.local/etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.482 NotebookApp] Looking for jupyter_notebook_config in /usr/etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.482 NotebookApp] Looking for jupyter_notebook_config in /usr/etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.482 NotebookApp] Loaded config file: /usr/local/etc/jupyter/jupyter_notebook_config.json
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.482 NotebookApp] Loaded config file: /usr/local/etc/jupyter/jupyter_notebook_config.json
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.478 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.478 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.478 NotebookApp] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.478 NotebookApp] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.474 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.474 NotebookApp] Looking for jupyter_config in /root/.jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.473 NotebookApp] Looking for jupyter_config in /root/.local/etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.473 NotebookApp] Looking for jupyter_config in /usr/etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.472 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.472 NotebookApp] Looking for jupyter_config in /etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,"[D 07:37:18.471 NotebookApp] Searching ['/root/.jupyter', '/root/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files"
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.474 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.474 NotebookApp] Looking for jupyter_config in /root/.jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.473 NotebookApp] Looking for jupyter_config in /root/.local/etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.473 NotebookApp] Looking for jupyter_config in /usr/etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.469 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,[D 07:37:18.468 NotebookApp] Looking for jupyter_config in /etc/jupyter
"Feb 1, 2024, 8:37:18 AM",WARNING,"[D 07:37:18.467 NotebookApp] Searching ['/root/.jupyter', '/root/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files"

**Comment by igninjaz** [comment]
https://colab.research.google.com/github/lllyasviel/Fooocus/blob/main/fooocus_colab.ipynb#scrollTo=VjYy0F2gZIPR&line=1&uniqifier=1

**Comment by E2GO** [comment]
I recently got a problem with generation of 30 pics in a row that it's not synced with preview window and ready pics in output folder. I've got already done pics in output but there's some time needs for UI to show it up yet.

**Comment by mashb1t** [comment]
@E2GO this is solved in https://github.com/lllyasviel/Fooocus/pull/1013, if only lllyasviel had time to review the now 90 PRs...

**Comment by E2GO** [comment]
@mashb1t ty for info! I got it) No rush here - it's already great to know that such bug solved)

**Comment by mashb1t** [comment]
@igninjaz i can confirm that it's working fine on a T4 GPU on Colab (free). Your last terminal output didn't include any sampling steps or anything specific to be able to analyze the issue. Please check again.

**Comment by mashb1t** [comment]
Closing as stale, will reopen when further information is provided.
