### ISSUE TITLE
Unable to run the app (no idea what happened)

### ISSUE THREAD

**Issue by Haneesh000** [lllyasviel/Fooocus#2128]
I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
I cloned the repo into D:\AI\Fooocus and created a anaconda environment with latest python version (3.11.5). Then, I ran `python entry_with_update.py` which downloaded the AI model and others. Then, after launching it when I tried to generate image it showed ERROR so when I checked the console log I found errors.

**Full Console Log**
Log is in this file: https://github.com/Haneesh000/AI-Issues/blob/main/my-error-log.txt

**Comment by mashb1t** [comment]
As you've confirmed and read in the troubleshooting guide, this is the exact same error:
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#torch-not-compiled-with-cuda-enabled

Please use the official installation instructions on https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windows by downloading the zip fil, or, if having an AMD GPU, follow the steps at https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windowsamd-gpus

**Comment by Haneesh000** [comment]
Thx
