### ISSUE TITLE
Torch not compiled with CUDA enabled comfyui

### ISSUE THREAD

**Issue by alexkog10** [lllyasviel/Fooocus#2129]
Hi, after installing a few new nodes comfyui stopped working for me, giving the error "Torch not compiled with CUDA enabled"
Any ideas what might fix that?
![Screenshot_253](https://github.com/lllyasviel/Fooocus/assets/123573522/6c11c5b2-f760-471b-9405-a528c7ef1315)

**Comment by mashb1t** [comment]
Duplicate of https://github.com/lllyasviel/Fooocus/issues/2128, see https://github.com/lllyasviel/Fooocus/issues/2128#issuecomment-1921747084
