### ISSUE TITLE
BUG: Foocus crash when no refiner use

### ISSUE THREAD

**Issue by barepixels** [lllyasviel/Fooocus#213]
If you choose not to use SDXL refiner, Fooocus will crash

**Comment by sampadsams** [comment]
The base model that Fooocus comes with needs its refiner , that's a system Stable Diffusion XL is based on; not generating much of an image but getting to an acceptable result by refining it.

**Comment by barepixels** [comment]
You can use base sdxl without refiner in other GUI.  No crash there

**Comment by Ambratolm** [comment]
It works fine without refiner. Was this an old problem ? Is it fixed for you now?

**Comment by mashb1t** [comment]
Closing as stale.
