### ISSUE TITLE
The bug in the FaceSwap feature.

### ISSUE THREAD

**Issue by diaolulu1** [lllyasviel/Fooocus#2131]
The FaceSwap function switches models at the 15th step, after which the subsequent refinement makes the faces, which were originally quite similar, look completely dissimilar.

**Comment by mashb1t** [comment]
It would be great if you could investigate if this is a 50% or 15th step issue (changing to quality and checking again) and if you could pin point the code line stating the switch. Thank you!

**Comment by diaolulu1** [comment]
I think it should be caused by the Refiner feature; the default Refiner Switch is set to activate at 50%. As long as I don't enable the Refiner, there's no problem.
![01](https://github.com/lllyasviel/Fooocus/assets/55993721/fbeb292a-0c90-4ab6-b02c-df5ed402e3a7)
![02](https://github.com/lllyasviel/Fooocus/assets/55993721/7d064b5a-0a42-4e6a-b1c0-468c2c2e549f)
![03](https://github.com/lllyasviel/Fooocus/assets/55993721/b66851f0-b9fd-41ca-90e8-a50e7e17697e)
![04](https://github.com/lllyasviel/Fooocus/assets/55993721/2f81a37e-3ddd-4b79-ab93-eb85a48f79d8)

**Comment by xhoxye** [comment]
https://github.com/lllyasviel/Fooocus/blob/1bcbd6501bb3e5db5674a18a8a8074034cda318b/modules/async_worker.py#L307
It is indeed 0.5 of the lock, which will cause all guidance to lose control.

**Comment by dav30383** [comment]
I still have the same problem, and I've never used ReFiner! For a certain point it seems to follow the right face, and then it changes it! But wouldn't it be possible to implement ReActor??? Much more effective when it comes to face swapping!

**Comment by mashb1t** [comment]
This will be reevaluated, for now we have https://github.com/lllyasviel/Fooocus/pull/2165

**Comment by dav30383** [comment]
Sorry, but why don't you fix it now instead? It's a serious problem! I've already given you the solution, just implement the ReActor code or add it as a feature, right?

**Comment by mashb1t** [comment]
@dav30383 please calm down. See https://github.com/lllyasviel/Fooocus/discussions/2154#discussioncomment-8389770, i'll focus on bugfixes first before adding new geazures, especially sich which need external packages / libraries like insightface or similar.

**Comment by LIQUIDMIND111** [comment]
> The FaceSwap function switches models at the 15th step, after which the subsequent refinement makes the faces, which were originally quite similar, look completely dissimilar.

CONFIRMED, this happens after 50% either at 15 or 30 steps depending on if its in SPEED or QUALITY

**Comment by dhonta** [comment]
Same problem here. Faceswap doesn't work at this moment.

**Comment by mashb1t** [comment]
Please understand that we should really not change the code without knowing the reasons behind why it's been implemented this way in the first place, see https://github.com/lllyasviel/Fooocus/pull/2165#issuecomment-1937764894.

**Comment by Amit30swgoh** [comment]
What about useing dreamshaper xl turbo 8 steps? how can i know optimal refiner number for best faceswap. also i didnt see where to increase from 0.5 to 0.8 because in all the branches i see 0.5 refiner switch no?

**Comment by mashb1t** [comment]
@Amit30swgoh turbo models shouldn't use a refiner, as they have a too little step count that it makes an impact.
I'd recommend using 30 steps Speed performance for face swap and applying the changes of this PR manually.

**Comment by Amit30swgoh** [comment]
Ok so i need to use a different model not turbo right?
And pr manually could u please tell me what exactley to change in the pr preset ty so much

**Comment by Amit30swgoh** [comment]
Im useing my personal branch and i just tried and its changing the faceswap in the middle even after puting 0.8 instaed of 0.5![20240306_200020.jpg](https://github.com/lllyasviel/Fooocus/assets/42430868/142f33c7-c96e-495f-b947-57b3f425bc04)

**Comment by Amit30swgoh** [comment]
![20240306_200020.jpg](https://github.com/lllyasviel/Fooocus/assets/42430868/d8bdb7e2-267d-4924-a996-9a3d5756cc1b)

My personal branch i changed..
Can it work without inpaint?

**Comment by mashb1t** [comment]
This issue is about mixing inpaint with faceswap. If you need support for anyhing else please open another discussion in Q&A.
