### ISSUE TITLE
Faster colab notebook

### ISSUE THREAD

**Issue by m00nsp3ll** [lllyasviel/Fooocus#2134]
Hello,
is it possible to have an updated version of collab file which connects with google drive and just update the repo and do not re-install large model files if they are already installed and give user an option to upload new models via link if required ?

everytime i run the official colab file it downloads the juggernautXL_v8Rundiffusion.safetensors 6x gb all the time

<img width="1624" alt="image" src="https://github.com/lllyasviel/Fooocus/assets/2984726/0fa68111-d13f-4cb8-b4ea-00a52f3d22d3">

thanks a lot

**Comment by m00nsp3ll** [comment]
well as a developer i am using upgraded version :) and i really love fooocus and enjoy working with it

**Comment by eddyizm** [comment]
Upgraded colab and extra storage for google drive? 
You can change the path of your checkpoints in your `config.txt` file here
`"path_checkpoints"` 
And map it your mounted google drive. That way you don't have to re-download everytime.

**Comment by mashb1t** [comment]
@m00nsp3ll please check out https://github.com/lllyasviel/Fooocus/issues/423, https://github.com/lllyasviel/Fooocus/issues/423#issuecomment-1727767095.
Closing as duplicate, should work with zhe referenced commands.
