### ISSUE TITLE
EMBEDDING / Trigger Words Problem

### ISSUE THREAD

**Issue by aliwithgrain** [lllyasviel/Fooocus#2135]
I want similar results in [Fooocus](https://github.com/lllyasviel/Fooocus), I would appreciate any help. 
Thank you

[The Book of Fixed Stars](https://civitai.com/models/190295?modelVersionId=213704)

**Comment by eddyizm** [comment]
You can only use SDXL models with focus, so unfortunately that one will not work. However, someone smarter than me could correct me but you may be able to use it as a refiner, but not sure.

**Comment by mashb1t** [comment]
You can use the juggernaut base model, set this referenced model as refiner, change refiner switch to 0.1 and try to achieve your goals like this. Be aware that this will not produce as good images as e.g. A1111/ComfyUI as Fooocus is a SDXL based UI.

**Comment by aliwithgrain** [comment]
May I ask what I should use?

**Comment by mashb1t** [comment]
That totally depends on the style you want to achieve.
For more anime likeness i'd propose to use https://civitai.com/models/4384/dreamshaper, realism https://civitai.com/models/4201?modelVersionId=130072 or one of my oersonal favorites for a mix and more anime+3D-likeness https://civitai.com/models/7371?modelVersionId=46846
