### ISSUE TITLE
run on the android

### ISSUE THREAD

**Issue by alen978** [lllyasviel/Fooocus#2138]
hi has installed it on the win10, but how to run it on the android? thanks

**Comment by AsaTyr2018** [comment]
Since its aGradio App. It need to be started with the "--listen" Argument. It changes the Listen IP from localhost to 0.0.0.0 (Listen to all IP Interfaces) Then you can run it on Android / other Devices in the network via the Computer IP + port.

But i didn´t found any points to add this args. The WebUI was modified =/

Maby someone can help here?

**Comment by AsaTyr2018** [comment]
> hi has installed it on the win10, but how to run it on the android? thanks

I found what you need. Just edit the run.bat (or run_anime.bar/Run_realistic) and add --listen to the start command. 
Example:
`.\python_embeded\python.exe -s Fooocus\entry_with_update.py --listen`

That way the Gradio will listen to all IP´s and not just to 127.0.0.1.

Example. your Computer IP is 192.168.1.35 (run cmd -> ipconfig to find your IP) 
Then you can reach it via http://192.168.1.35:7865/ from your android device.

Be aware that the access is not restricted to you only. Everyone in your Local Network will be able to access it. (not Internet. Unless you open the ports)
Still be carefull with this.

Hope this helps you =)

**Comment by mashb1t** [comment]
@alen978 Please add `--listen` to your entrypoint.
If you wish to have authentication enabled you can apply the changes of PR https://github.com/lllyasviel/Fooocus/pull/2127.

**Comment by AYuvraj7** [comment]
Why closed

**Comment by IPv6** [comment]
> Why closed

You need to run Fooocus on normal system with GPU with share/listen parameter.
Then you can open Fooocus web page in android browser. Gradio should be fine on it, imho

It`s the only option for "run on android" currently, afaik

**Comment by IPv6** [comment]
> Why closed

You need to run Fooocus on normal system with GPU with share/listen parameter.
Then you can open Fooocus web page in android browser. Gradio should be fine on it, imho

It`s the only option for "run on android" currently, afaik
