### ISSUE TITLE
Very long generation

### ISSUE THREAD

**Issue by Wells83** [lllyasviel/Fooocus#2140]
Bonjour, j'ai un soucis en terme de performance. L’outil en lui même semble fonctionner correctement. J'arrive à avoir des résultats très intéressants. Néanmoins, je met prêt de 1 à 2 minutes pour générer UNE image !

Est ce que cela vient du fait que je suis sur un proc AMD et CG AMD ?

Ma config :

Proc : AMD 7800X3D
Graphic Card : Sapphire Pulse AMD Radeon RX 7900 XTX 24GB GDDR6
RAM: 32 Gb DDR5 6000C30
HD: Lexar NM790 4 to SSD, M.2 2280 PCIe Gen4

----------------------------------------------------------------------------------------------------------------------------------------

Hello, I have a performance problem. The tool itself seems to work correctly. I'm getting very interesting results. However, it takes me nearly 1 to 2 minutes to generate ONE image!

Is this due to the fact that I'm using an AMD proc and AMD CG?

My config :

Proc : AMD 7800X3D
Graphic Card : Sapphire Pulse AMD Radeon RX 7900 XTX 24GB GDDR6
RAM: 32 Gb DDR5 6000C30
HD: Lexar NM790 4 to SSD, M.2 2280 PCIe Gen4

**Comment by eddyizm** [comment]
AMD gpu's have some known [issues](https://github.com/lllyasviel/Fooocus/issues?q=is%3Aissue+is%3Aopen+amd) with fooocus.

**Comment by mashb1t** [comment]
Closing as there are already a lot of AMD issues with more specific description for the same case.
