### ISSUE TITLE
seed is not fixed

### ISSUE THREAD

**Issue by Alireza2317** [lllyasviel/Fooocus#2141]
Hello there. i have a problem with fixed seeds.
I have created multiple images on random seed, then i liked the output with a certain seed like `5207638156172183669`.

then i unchecked the random seed and entered the seed in the box, and created more outputs. but when i looked at the log html, the seeds were nor fixed nor completely random, they were increments of my main seed. i mean i created 4 outputs, the first one's seed was in fact `5207638156172183669`, but the next one's was `5207638156172183670` (one more than the last), and the next was `5207638156172183671` and so on.

Of course the outputs were completely different due to the different seeds.

i tried other base models ( i tested on juggernutV6 and juggernutV8) and i tried unchecking all the styles but it happened again.

I don't exactly know if this is by design or not, but i just wanted to be sure what is going on.

Im using fooocus version 2.1.862 on Linux.

**Comment by poor7** [comment]
Так было всегда, и, вероятно, так было задумано.

**Comment by mashb1t** [comment]
The first image per generation is generated with the given seed, all subsequent images are uncrements on this seed. Increasing image amount with always fixed seed would cause all images to be the same, which is not what you'd expect.
Please decrease the image amount to 1 to always get zhe image with the exact seed you've set.

**Comment by Alireza2317** [comment]
> The first image per generation is generated with the given seed, all subsequent images are increments on this seed. Increasing image amount with always fixed seed would cause all images to be the same, which is not what you'd expect. Please decrease the image amount to 1 to always get the image with the exact seed you've set.

ok it makes sense. but what if I wanted to use wildcards?

**Comment by mashb1t** [comment]
I don't know if i got what you mean but wildcards are random in every case.
Please check if https://github.com/lllyasviel/Fooocus/pull/1761 or https://github.com/lllyasviel/Fooocus/pull/1503 suit your needs.

**Comment by poor7** [comment]
> ok it makes sense. but what if I wanted to use wildcards?

I think it's possible to use the "infinite generation" mode. Enabled and disabled by right-clicking on the Generate button.

**Comment by Alireza2317** [comment]
> I don't know if i got what you mean but wildcards are random in every case. Please check if #1761 or #1503 suit your needs.

I meant i wanna generate for example 10 images, using a `__color__` wildcard, for the same seed. so every little detail is the same, except the color of something in the picture. but if that's not possible then i guess i should do this manually.

**Comment by mashb1t** [comment]
> > ok it makes sense. but what if I wanted to use wildcards?
> 
> I think it's possible to use the "infinite generation" mode. Enabled and disabled by right-clicking on the Generate button.

@Alireza2317 this is then also the solution i'd propose, just right click the generate button and use genrate forever

**Comment by flanneryhbh** [comment]
> > I don't know if i got what you mean but wildcards are random in every case. Please check if #1761 or #1503 suit your needs.
> 
> I meant i wanna generate for example 10 images, using a `__color__` wildcard, for the same seed. so every little detail is the same, except the color of something in the picture. but if that's not possible then i guess i should do this manually.

Sounds like https://github.com/lllyasviel/Fooocus/pull/1503 is exactly what you want.  The only thing is you'd just type out the different colors in the array.

**Comment by Alireza2317** [comment]
> > > I don't know if i got what you mean but wildcards are random in every case. Please check if #1761 or #1503 suit your needs.
> > 
> > 
> > I meant i wanna generate for example 10 images, using a `__color__` wildcard, for the same seed. so every little detail is the same, except the color of something in the picture. but if that's not possible then i guess i should do this manually.
> 
> Sounds like #1503 is exactly what you want. The only thing is you'd just type out the different colors in the array.

oh thank you so much, i did not know about arrays in the prpmpt.
