### ISSUE TITLE
Cartoon image and caricature

### ISSUE THREAD

**Issue by StepHaze** [lllyasviel/Fooocus#2142]
Hello,
I'm a newbie to Fooocus.
Please give me step-by-step instructions how to turn my photo to a cartoon image and to a caricature.
Thank you.

**Comment by eddyizm** [comment]
run the anime preset > image prompt > generate will get you most of the way there, not sure about the caricature.

**Comment by mashb1t** [comment]
You can simply upload an image to image prompt or upscale/vary with specific styles and prompts. To keep the exact shape you can use image prompt advanced PyraCanny or CPDS.
