### ISSUE TITLE
Bulk/Queue Work

### ISSUE THREAD

**Issue by AsaTyr2018** [lllyasviel/Fooocus#2143]
Is it possible to add in a Queue List with different Prompts that get worked throu? 

I create a lot of Images with different Prompts but i need to set in every one manual.

**Comment by poor7** [comment]
Probably only through wildcards for now, but they will be in random order.

**Comment by AsaTyr2018** [comment]
> Probably only through wildcards for now, but they will be in random order.

wildcard would be fine too. i use multi character Loras. Most Prompts jsut look like this:

[Var.Char.Name], [Static Prompt] 

Can you tell me about?

**Comment by poor7** [comment]
https://github.com/lllyasviel/Fooocus/discussions/1667

**Comment by AsaTyr2018** [comment]
> #1667

Works perfectly!! Thank you =D
