### ISSUE TITLE
PyYAML error during installation

### ISSUE THREAD

**Issue by RealMW96** [lllyasviel/Fooocus#2144]
Hey, 

i was running into errors while installing Fooocus in Ubuntu 22.04. When I execute the command "pip install -r "requirements_versions.txt", I get the following log:  

Requirement already satisfied: torchsde==0.2.5 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 1)) (0.2.5)
Requirement already satisfied: einops==0.4.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 2)) (0.4.1)
Requirement already satisfied: transformers==4.30.2 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 3)) (4.30.2)
Requirement already satisfied: safetensors==0.3.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 4)) (0.3.1)
Requirement already satisfied: accelerate==0.21.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 5)) (0.21.0)
Collecting pyyaml==6.0 (from -r requirements_versions.txt (line 6))
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Collecting Pillow==9.2.0 (from -r requirements_versions.txt (line 7))
  Using cached Pillow-9.2.0-cp38-cp38-manylinux_2_28_x86_64.whl (3.2 MB)
Requirement already satisfied: scipy==1.9.3 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 8)) (1.9.3)
Requirement already satisfied: tqdm==4.64.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 9)) (4.64.1)
Collecting psutil==5.9.5 (from -r requirements_versions.txt (line 10))
  Using cached psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
Requirement already satisfied: pytorch_lightning==1.9.4 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 11)) (1.9.4)
Requirement already satisfied: omegaconf==2.2.3 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 12)) (2.2.3)
Requirement already satisfied: gradio==3.41.2 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 13)) (3.41.2)
Requirement already satisfied: pygit2==1.12.2 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 14)) (1.12.2)
Requirement already satisfied: opencv-contrib-python==4.8.0.74 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 15)) (4.8.0.74)
Requirement already satisfied: httpx==0.24.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 16)) (0.24.1)
Requirement already satisfied: onnxruntime==1.16.3 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 17)) (1.16.3)
Requirement already satisfied: timm==0.9.2 in /home/marcel/anaconda3/lib/python3.8/site-packages (from -r requirements_versions.txt (line 18)) (0.9.2)
Requirement already satisfied: boltons>=20.2.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torchsde==0.2.5->-r requirements_versions.txt (line 1)) (23.1.1)
Requirement already satisfied: torch>=1.6.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torchsde==0.2.5->-r requirements_versions.txt (line 1)) (2.1.2)
Requirement already satisfied: trampoline>=0.1.2 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torchsde==0.2.5->-r requirements_versions.txt (line 1)) (0.1.2)
Requirement already satisfied: numpy>=1.19.* in /home/marcel/anaconda3/lib/python3.8/site-packages (from torchsde==0.2.5->-r requirements_versions.txt (line 1)) (1.22.3)
Requirement already satisfied: filelock in /home/marcel/anaconda3/lib/python3.8/site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (3.0.12)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (0.20.2)
Requirement already satisfied: packaging>=20.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (21.3)
Requirement already satisfied: regex!=2019.12.17 in /home/marcel/anaconda3/lib/python3.8/site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (2020.10.15)
Requirement already satisfied: requests in /home/marcel/anaconda3/lib/python3.8/site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (2.28.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (0.13.3)
Requirement already satisfied: fsspec>2021.06.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from fsspec[http]>2021.06.0->pytorch_lightning==1.9.4->-r requirements_versions.txt (line 11)) (2023.12.2)
Requirement already satisfied: torchmetrics>=0.7.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from pytorch_lightning==1.9.4->-r requirements_versions.txt (line 11)) (1.3.0.post0)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from pytorch_lightning==1.9.4->-r requirements_versions.txt (line 11)) (4.9.0)
Requirement already satisfied: lightning-utilities>=0.6.0.post0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from pytorch_lightning==1.9.4->-r requirements_versions.txt (line 11)) (0.10.1)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /home/marcel/anaconda3/lib/python3.8/site-packages (from omegaconf==2.2.3->-r requirements_versions.txt (line 12)) (4.9.3)
Requirement already satisfied: aiofiles<24.0,>=22.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (23.2.1)
Requirement already satisfied: altair<6.0,>=4.2.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (4.2.0)
Requirement already satisfied: fastapi in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (0.109.0)
Requirement already satisfied: ffmpy in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (0.3.1)
Requirement already satisfied: gradio-client==0.5.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (0.5.0)
Requirement already satisfied: importlib-resources<7.0,>=1.3 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (6.1.1)
Requirement already satisfied: jinja2<4.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (2.11.2)
Requirement already satisfied: markupsafe~=2.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (2.0.1)
Requirement already satisfied: matplotlib~=3.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (3.3.2)
Requirement already satisfied: orjson~=3.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (3.9.12)
Requirement already satisfied: pandas<3.0,>=1.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (1.1.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (2.5.3)
Requirement already satisfied: pydub in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (0.25.1)
Requirement already satisfied: python-multipart in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (0.0.6)
Requirement already satisfied: semantic-version~=2.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (2.10.0)
Requirement already satisfied: uvicorn>=0.14.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (0.26.0)
Requirement already satisfied: websockets<12.0,>=10.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from gradio==3.41.2->-r requirements_versions.txt (line 13)) (11.0.3)
Requirement already satisfied: cffi>=1.9.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from pygit2==1.12.2->-r requirements_versions.txt (line 14)) (1.14.3)
Requirement already satisfied: certifi in /home/marcel/anaconda3/lib/python3.8/site-packages (from httpx==0.24.1->-r requirements_versions.txt (line 16)) (2023.11.17)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from httpx==0.24.1->-r requirements_versions.txt (line 16)) (0.17.3)
Requirement already satisfied: idna in /home/marcel/anaconda3/lib/python3.8/site-packages (from httpx==0.24.1->-r requirements_versions.txt (line 16)) (2.10)
Requirement already satisfied: sniffio in /home/marcel/anaconda3/lib/python3.8/site-packages (from httpx==0.24.1->-r requirements_versions.txt (line 16)) (1.3.0)
Requirement already satisfied: coloredlogs in /home/marcel/anaconda3/lib/python3.8/site-packages (from onnxruntime==1.16.3->-r requirements_versions.txt (line 17)) (15.0.1)
Requirement already satisfied: flatbuffers in /home/marcel/anaconda3/lib/python3.8/site-packages (from onnxruntime==1.16.3->-r requirements_versions.txt (line 17)) (2.0)
Requirement already satisfied: protobuf in /home/marcel/anaconda3/lib/python3.8/site-packages (from onnxruntime==1.16.3->-r requirements_versions.txt (line 17)) (3.20.1)
Requirement already satisfied: sympy in /home/marcel/anaconda3/lib/python3.8/site-packages (from onnxruntime==1.16.3->-r requirements_versions.txt (line 17)) (1.10.1)
Requirement already satisfied: torchvision in /home/marcel/anaconda3/lib/python3.8/site-packages (from timm==0.9.2->-r requirements_versions.txt (line 18)) (0.16.2)
Requirement already satisfied: entrypoints in /home/marcel/anaconda3/lib/python3.8/site-packages (from altair<6.0,>=4.2.0->gradio==3.41.2->-r requirements_versions.txt (line 13)) (0.3)
Requirement already satisfied: jsonschema>=3.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from altair<6.0,>=4.2.0->gradio==3.41.2->-r requirements_versions.txt (line 13)) (3.2.0)
Requirement already satisfied: toolz in /home/marcel/anaconda3/lib/python3.8/site-packages (from altair<6.0,>=4.2.0->gradio==3.41.2->-r requirements_versions.txt (line 13)) (0.11.1)
Requirement already satisfied: pycparser in /home/marcel/anaconda3/lib/python3.8/site-packages (from cffi>=1.9.1->pygit2==1.12.2->-r requirements_versions.txt (line 14)) (2.20)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from fsspec[http]>2021.06.0->pytorch_lightning==1.9.4->-r requirements_versions.txt (line 11)) (3.9.1)
Requirement already satisfied: h11<0.15,>=0.13 in /home/marcel/anaconda3/lib/python3.8/site-packages (from httpcore<0.18.0,>=0.15.0->httpx==0.24.1->-r requirements_versions.txt (line 16)) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from httpcore<0.18.0,>=0.15.0->httpx==0.24.1->-r requirements_versions.txt (line 16)) (4.2.0)
Requirement already satisfied: zipp>=3.1.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from importlib-resources<7.0,>=1.3->gradio==3.41.2->-r requirements_versions.txt (line 13)) (3.17.0)
Requirement already satisfied: setuptools in /home/marcel/anaconda3/lib/python3.8/site-packages (from lightning-utilities>=0.6.0.post0->pytorch_lightning==1.9.4->-r requirements_versions.txt (line 11)) (50.3.1.post20201107)
Requirement already satisfied: cycler>=0.10 in /home/marcel/anaconda3/lib/python3.8/site-packages (from matplotlib~=3.0->gradio==3.41.2->-r requirements_versions.txt (line 13)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from matplotlib~=3.0->gradio==3.41.2->-r requirements_versions.txt (line 13)) (1.3.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/marcel/anaconda3/lib/python3.8/site-packages (from matplotlib~=3.0->gradio==3.41.2->-r requirements_versions.txt (line 13)) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from matplotlib~=3.0->gradio==3.41.2->-r requirements_versions.txt (line 13)) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /home/marcel/anaconda3/lib/python3.8/site-packages (from pandas<3.0,>=1.0->gradio==3.41.2->-r requirements_versions.txt (line 13)) (2020.1)
Requirement already satisfied: annotated-types>=0.4.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4->gradio==3.41.2->-r requirements_versions.txt (line 13)) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in /home/marcel/anaconda3/lib/python3.8/site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4->gradio==3.41.2->-r requirements_versions.txt (line 13)) (2.14.6)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/marcel/anaconda3/lib/python3.8/site-packages (from requests->transformers==4.30.2->-r requirements_versions.txt (line 3)) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from requests->transformers==4.30.2->-r requirements_versions.txt (line 3)) (1.25.11)
Requirement already satisfied: networkx in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (2.5)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.18.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (2.18.1)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (12.1.105)
Requirement already satisfied: triton==2.1.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (2.1.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/marcel/anaconda3/lib/python3.8/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (12.3.101)
Requirement already satisfied: click>=7.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from uvicorn>=0.14.0->gradio==3.41.2->-r requirements_versions.txt (line 13)) (7.1.2)
Requirement already satisfied: humanfriendly>=9.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from coloredlogs->onnxruntime==1.16.3->-r requirements_versions.txt (line 17)) (10.0)
Requirement already satisfied: starlette<0.36.0,>=0.35.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from fastapi->gradio==3.41.2->-r requirements_versions.txt (line 13)) (0.35.1)
Requirement already satisfied: mpmath>=0.19 in /home/marcel/anaconda3/lib/python3.8/site-packages (from sympy->onnxruntime==1.16.3->-r requirements_versions.txt (line 17)) (1.1.0)
Requirement already satisfied: attrs>=17.3.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==1.9.4->-r requirements_versions.txt (line 11)) (20.3.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/marcel/anaconda3/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==1.9.4->-r requirements_versions.txt (line 11)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==1.9.4->-r requirements_versions.txt (line 11)) (1.9.4)
Requirement already satisfied: frozenlist>=1.1.1 in /home/marcel/anaconda3/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==1.9.4->-r requirements_versions.txt (line 11)) (1.4.1)
Requirement already satisfied: aiosignal>=1.1.2 in /home/marcel/anaconda3/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==1.9.4->-r requirements_versions.txt (line 11)) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==1.9.4->-r requirements_versions.txt (line 11)) (4.0.3)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/marcel/anaconda3/lib/python3.8/site-packages (from anyio<5.0,>=3.0->httpcore<0.18.0,>=0.15.0->httpx==0.24.1->-r requirements_versions.txt (line 16)) (1.1.3)
Requirement already satisfied: six in /home/marcel/anaconda3/lib/python3.8/site-packages (from cycler>=0.10->matplotlib~=3.0->gradio==3.41.2->-r requirements_versions.txt (line 13)) (1.15.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio==3.41.2->-r requirements_versions.txt (line 13)) (0.17.3)
Requirement already satisfied: decorator>=4.3.0 in /home/marcel/anaconda3/lib/python3.8/site-packages (from networkx->torch>=1.6.0->torchsde==0.2.5->-r requirements_versions.txt (line 1)) (4.4.2)
DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: pyyaml, psutil, Pillow
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 5.3.1
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

My PyYAML version does not seem to be compatible with the one used in Fooocus. Any advice on how to solve this issue?

**Comment by eddyizm** [comment]
Have you tried to create and install in a venv?

**Comment by mashb1t** [comment]
Make sure to use Python 3.10 to install Fooocus and check out the official installation instructions https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#linux-using-anaconda, https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#linux-using-python-venv and https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#linux-using-python-venv (this one also explicitely mentions Python 3.10 btw)

**Comment by mashb1t** [comment]
edited, wrong link: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#linux-using-native-system-python
