### ISSUE TITLE
About independent maintenance of multiple users in the LAN

### ISSUE THREAD

**Issue by JulienZLQ** [lllyasviel/Fooocus#2148]
Due to work needs, multiple peoples in the LAN use it, but we don't want everyone to be able to use it.
1. Multiple users cannot be set up through auth, and they can only share the same user and password. Is it possible to set up multiple users, so that the authorization switch for each person can be realized in disguise?
2. On the basis of 1, is it possible to identify users as information and independently create a folder with the user name to store historical records, so that it can be better maintained separately for local multiple users?
Looking forward to this, thank you so much

**Comment by mashb1t** [comment]
@JulienZLQ You'd have to change/add an authentication system (currently one user only in  gradio basic auth and not then readable from Python AFAIK) or add a text input for the users to be distinguishable from another. Then you'll have to use this username as / in the private loggers foldername to separate outputs, if that is what you want.

Be advised that multiple users are not fully supported until https://github.com/lllyasviel/Fooocus/pull/981 is merged.

**Comment by mashb1t** [comment]
Can this issue/question be closed?

**Comment by JulienZLQ** [comment]
@mashb1t Okay, close it. I can read and understand the logic and procedures you mentioned, but I do not have the corresponding professional capabilities because I'm not a develope. I will study and research separately. Thanks :).
