### ISSUE TITLE
Updating the model led to a deterioration of the result

### ISSUE THREAD

**Issue by leoken937** [lllyasviel/Fooocus#2150]
Can you add the ability to select the version of models in colab?
 
The new version of realisticStockPhoto_v2.0.safetensors draws the same ugly face every time (in my opinion), the past version could draw different beautiful faces. 

Sometimes new versions of models are worse than old ones.

**Comment by eddyizm** [comment]
You should still have the old model in your folder if you had it before.

**Comment by mashb1t** [comment]
You can make a fork of this repository and revert the changes, then use the Jupyter Notebook of your fork in Colab.

Models are carefully evaluated before changing them to another version and in general they met the criterias and generated better results on average than the old ones.
