### ISSUE TITLE
Can't get config.txt to work

### ISSUE THREAD

**Issue by VGF64** [lllyasviel/Fooocus#2152]
I have the paths set for each of them to load a1111 material into Fooocus, but I keep getting an error that mentions something about expecting a delimiter in config.txt and it refuses to work. The console log looks like this:

C:\Users\jrnsa\OneDrive\Documents\Fooocus UI>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
**Failed to load config file "C:\Users\jrnsa\OneDrive\Documents\Fooocus UI\Fooocus\config.txt" . The reason is: Expecting ':' delimiter: line 2 column 205 (char 206)**
Please make sure that:
1. The file "C:\Users\jrnsa\OneDrive\Documents\Fooocus UI\Fooocus\config.txt" is a valid text file, and you have access to read it.
2. Use "\\" instead of "\" when describing paths.
3. There is no "," before the last "}".
4. All key/value formats are correct.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.864
Running on local URL:  

To create a public link, set `share=True` in `launch()`.
Total VRAM 8192 MB, total RAM 16005 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: C:\Users\jrnsa\OneDrive\Documents\Fooocus UI\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [C:\Users\jrnsa\OneDrive\Documents\Fooocus UI\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [C:\Users\jrnsa\OneDrive\Documents\Fooocus UI\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\Users\jrnsa\OneDrive\Documents\Fooocus UI\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.65 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865

And config.txt looks like this:

{
    "path_checkpoints": "C:\\Users\\jrnsa\\OneDrive\\Documents\\Fooocus UI\\Fooocus\\models\\checkpoints", "C:\\Users\\jrnsa\\OneDrive\\Documents\\GitHub\\stable-diffusion-webui\\models\\Stable-diffusion", "G:\\models\\stable-diffusion",
    "path_loras": "C:\\Users\\jrnsa\\OneDrive\\Documents\\Fooocus UI\\Fooocus\\models\\loras", "G:\\models\\Lora",
    "path_embeddings": "C:\\Users\\jrnsa\\OneDrive\\Documents\\Fooocus UI\\Fooocus\\models\\embeddings", "C:\\Users\\jrnsa\\OneDrive\\Documents\\GitHub\\stable-diffusion-webui\\embeddings",
    "path_vae_approx": "C:\\Users\\jrnsa\\OneDrive\\Documents\\Fooocus UI\\Fooocus\\models\\vae_approx", 
    "path_upscale_models": "C:\\Users\\jrnsa\\OneDrive\\Documents\\Fooocus UI\\Fooocus\\models\\upscale_models", "C:\\Users\\jrnsa\\OneDrive\\Documents\\GitHub\\stable-diffusion-webui\\models\\ESRGAN",
    "path_inpaint": "C:\\Users\\jrnsa\\OneDrive\\Documents\\Fooocus UI\\Fooocus\\models\\inpaint",
    "path_controlnet": "C:\\Users\\jrnsa\\OneDrive\\Documents\\Fooocus UI\\Fooocus\\models\\controlnet",
    "path_clip_vision": "C:\\Users\\jrnsa\\OneDrive\\Documents\\Fooocus UI\\Fooocus\\models\\clip_vision",
    "path_fooocus_expansion": "C:\\Users\\jrnsa\\OneDrive\\Documents\\Fooocus UI\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
    "path_outputs": "C:\\Users\\jrnsa\\OneDrive\\Documents\\Fooocus UI\\Fooocus\\outputs"
}

I am not sure what I am doing wrong? What would I need to do to fix this error?

**Comment by eddyizm** [comment]
You need to update your paths with a double backslash like below: 

"path_checkpoints": "K:\\BarracudaDrive.Mu
sic.Photos.Apps\\Apps\\Fooocus_win64_2-1-831\\
Fooocus\\models\\checkpoints",

**Comment by mashb1t** [comment]
> "path_checkpoints": "C:\Users\jrnsa\OneDrive\Documents\Fooocus UI\Fooocus\models\checkpoints", "C:\Users\jrnsa\OneDrive\Documents\GitHub\stable-diffusion-webui\models\Stable-diffusion", "G:\models\stable-diffusion",

@VGF64 please only use key: value in line 2, you have key: value, value, value

**Comment by VGF64** [comment]
I got it working, thanks guys.
