### ISSUE TITLE
Transparent PNG -> transparency is mask for inpaint

### ISSUE THREAD

**Issue by bjaan** [lllyasviel/Fooocus#2153]
When I am trying to fill the background of a transparent PNG-file with Fooocus, I need to manually highlight the entire background area of my subject with brush to have it apply the inpaint. This is tedious and not as precise.

What would be cool is a simple way or an option to automatically select the transparent areas of the PNG image in the inpaint image, and set it as the mask that inpaint will use.

As an extension to this, the ability to select the background if it is a solid color, like using magic wand (Fuzzy Select Tool in GIMP) to select areas.

**Comment by mashb1t** [comment]
Please check out https://github.com/lllyasviel/Fooocus/pull/2032 where automated masking and even mask prompting has been included.
