### ISSUE TITLE
Image Prompt checkbox doesn't open options for image prompting

### ISSUE THREAD

**Issue by Mcpoowl** [lllyasviel/Fooocus#2158]
**Describe the problem**
When running Fooocus through run.bat everything opens up fine, and I'm able to generate images correctly, however, the checkbox 'Image Prompt doesn't seem to do anything.

**Full Console Log**
![image](https://github.com/lllyasviel/Fooocus/assets/2244753/735b99a1-b9c3-4745-92d3-2eec68b65c67)

![image](https://github.com/lllyasviel/Fooocus/assets/2244753/dce971c3-3f03-45fd-9f42-7ac25e29355d)

**Comment by Irmagon** [comment]
Hi
1. Try open UI in another browser. Or check AdBlock extension in current browser. Or check u antivirus log (mb blocked local scripts)
2. Try add --listen parameter to run.bat (I have many net interfaces on my computers and UI dnt work without this parameters)

**Comment by Mcpoowl** [comment]
> Hi
> 
> 1. Try open UI in another browser. Or check AdBlock extension in current browser. Or check u antivirus log (mb blocked local scripts)
> 2. Try add --listen parameter to run.bat (I have many net interfaces on my computers and UI dnt work without this parameters)

Thanks for your reply. I've tested different browser (even clean without any addon, with no luck. The listen (and port) parameter didn't change anything either.

For the record: the rest of the UI works perfectly. It just that checking the 'image prompt' checkbox doesn't seem to do anything / give extra options as shown in all the screenshots

**Comment by mashb1t** [comment]
@Mcpoowl / @datboi6942 This strongly looks like a JS issue as also the styles on the aspect ratios is messed up. Please check the console log + network tab in your browser for more insights and disable adblockers if necessary (as already mentioned by @Irmagon).

**Comment by Mcpoowl** [comment]
> @Mcpoowl / @datboi6942 This strongly looks like a JS issue as also the styles on the aspect ratios is messed up. Please check the console log + network tab in your browser for more insights and disable adblockers if necessary (as already mentioned by @Irmagon).


You're (and @Irmagon ) are quite right. I checked the console, and its littered with 403 forbidden errors. It can't seem to access some of the files. Any idea what might cause this?

I've, again, checked multiple browsers, clean without any addons running. Even private modes don't change anything.

![image](https://github.com/lllyasviel/Fooocus/assets/2244753/3d92c2b2-ca11-4860-942e-d860be08d8df)
