### ISSUE TITLE
My pc isnt enough powerfull ? 

### ISSUE THREAD

**Issue by Gabi201265** [lllyasviel/Fooocus#2160]
Here is my issue : 

D:\Projet AI\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.864
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 2048 MB, total RAM 8082 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --always-normal-vram
Set vram state to: LOW_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce GTX 960M : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.

--------------------------

I dont understand why. Indeed I have 8GB RAM on my PC and Geforce GTX 960M.  So with this configuration, it should be ok as its written in ur repo in the section minimal requirement.

Can u help me please  ? 

Regards, 
Gabriel

**Comment by widiot1** [comment]
According to your log you have 2gb VRAM and 8gb ram. Fooocus requires a minimum of 4gb VRAM and even then will run slowly.

**Comment by mashb1t** [comment]
> According to your log you have 2gb VRAM and 8gb ram. Fooocus requires a minimum of 4gb VRAM and even then will run slowly.

^ this. GeForce GTX 960M is not supported, please check if you're able to use Fooocus with `--always-cpu` by modifying your run.bat.
`.\python_embeded\python.exe -s Fooocus\entry_with_update.py --always-cpu`
