### ISSUE TITLE
multiple face swap 

### ISSUE THREAD

**Issue by shangtsung056** [lllyasviel/Fooocus#2162]
let's say that I'm gonna create a little story with 2 characters i want to generate 3 images for this story and when I do a face swap I want to characters to swap the faces if I can a text input under the face swap to precise with character to swap the face with and put the name in that input and in the next generation prompt but the names so the ai can relate (sorry for my bad english)

**Comment by mashb1t** [comment]
You can use an iterative approach with inpainting one face at a time and using face swap this way.
There is currently no easier option available in Fooocus, but A1111 has a face swapper called ReActor, see https://github.com/Gourieff/sd-webui-reactor?tab=readme-ov-file#there-are-multiple-faces-in-result.

Does this help you to achieve your goal? Please let me know.

**Comment by mashb1t** [comment]
Closing as stale, feel free to provide your feedback to reopen.
