### ISSUE TITLE
Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW

### ISSUE THREAD

**Issue by nftizate** [lllyasviel/Fooocus#2169]
When I start Fooocus I get "_Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW"

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

I have a debian 11.8. My praphic card info:

```
~/Fooocus/Fooocus$ lspci | grep -i nvidia
01:00.0 VGA compatible controller: NVIDIA Corporation GP104BM [GeForce GTX 1070 Mobile] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)


~/Fooocus/Fooocus$ nvidia-smi
Mon Feb  5 11:24:10 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1070        Off | 00000000:01:00.0  On |                  N/A |
| N/A   49C    P3              24W /  65W |    296MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1897      G   /usr/lib/xorg/Xorg                           99MiB |
|    0   N/A  N/A      2021      G   /usr/bin/gnome-shell                         70MiB |
|    0   N/A  N/A      3930      G   /usr/lib/firefox-esr/firefox-esr            123MiB |
+---------------------------------------------------------------------------------------+
```

I also tried two ways for installing Fooocus: Using Anaconda and usin Python Venv. Both installations give me the same error.

Any clue?

**Comment by nftizate** [comment]
The complete Traceback is:

Traceback (most recent call last):
  File "/home/xavi/Fooocus/Fooocus/fooocus_env/lib/python3.9/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/xavi/Fooocus/Fooocus/fooocus_env/lib/python3.9/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/xavi/Fooocus/Fooocus/fooocus_env/lib/python3.9/site-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/xavi/Fooocus/Fooocus/fooocus_env/lib/python3.9/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/home/xavi/Fooocus/Fooocus/fooocus_env/lib/python3.9/site-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/xavi/Fooocus/Fooocus/fooocus_env/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/xavi/Fooocus/Fooocus/fooocus_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/home/xavi/Fooocus/Fooocus/fooocus_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/xavi/Fooocus/Fooocus/fooocus_env/lib/python3.9/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/home/xavi/Fooocus/Fooocus/fooocus_env/lib/python3.9/site-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/xavi/Fooocus/Fooocus/webui.py", line 27, in generate_clicked
    import ldm_patched.modules.model_management as model_management
  File "/home/xavi/Fooocus/Fooocus/ldm_patched/modules/model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/home/xavi/Fooocus/Fooocus/ldm_patched/modules/model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/home/xavi/Fooocus/Fooocus/fooocus_env/lib/python3.9/site-packages/torch/cuda/__init__.py", line 787, in current_device
    _lazy_init()
  File "/home/xavi/Fooocus/Fooocus/fooocus_env/lib/python3.9/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW

**Comment by mashb1t** [comment]
https://github.com/pytorch/pytorch/issues/40671#issuecomment-650712854

Rebooting or reinstalling the graphics driver could fix the problem, please check again.
If this doesn't worm your hardware may not be supported. Happy to hear your feedback!

**Comment by nftizate** [comment]
Hi, thanks for your quick response

I rebooted the system and check drivers and it seems to me the system is okay. I tested the CUDA driver with torch:

```
import torch
use_cuda = torch.cuda.is_available()

if not use_cuda:
	exit()

print(torch.cuda.get_device_name(0))
print('__CUDNN VERSION:', torch.backends.cudnn.version())
print('__Number CUDA Devices:', torch.cuda.device_count())
print('__CUDA Device Name:',torch.cuda.get_device_name(0))
print('__CUDA Device Total Memory [GB]:',torch.cuda.get_device_properties(0).total_memory/1e9)
print('Memory Usage:')
print('Allocated:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')
print('Cached:   ', round(torch.cuda.memory_reserved(0)/1024**3,1), 'GB')
```

the resultt:

```
NVIDIA GeForce GTX 1070
__CUDNN VERSION: 8902
__Number CUDA Devices: 1
__CUDA Device Name: NVIDIA GeForce GTX 1070
__CUDA Device Total Memory [GB]: 8.506048512
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB
[Finished in 1.3s]
```

**Comment by dpublic** [comment]
Apparently, there is some breaking change in the cuda version.
I only run from a docker container not directly as you show.
To fix for me, go to dockerhub and look for compatible nvidia/cuda tag.
Edit the first line of Dockerfile to build with it.
For my setup, it would be:

FROM nvidia/cuda:12.2.2-base-ubuntu22.04
