### ISSUE TITLE
If Fooocus can modify my photos in my prefer style?

### ISSUE THREAD

**Issue by chenhaokui** [lllyasviel/Fooocus#2172]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

**Comment by mashb1t** [comment]
Sure can, feel free to use them in upscale or vary and vary them (subtle or strong) as well as use PyraCanny / CPDS.
Examples (PyraCanny): https://gallery.mashb1t.de/gallery/vEQgUO12nqZuivc_Dir3U0eY

**Comment by chenhaokui** [comment]
> Sure can, feel free to use them in upscale or vary and vary them (subtle or strong) as well as use PyraCanny / CPDS in Image Prompt > Advanced. Examples (PyraCanny): https://gallery.mashb1t.de/gallery/vEQgUO12nqZuivc_Dir3U0eY

![Snipaste_2024-02-05_23-44-19](https://github.com/lllyasviel/Fooocus/assets/92264358/c3beff34-3ef9-41f0-9374-1c556fd73085)
I think the effect is not very well?

**Comment by mashb1t** [comment]
Please start a discussion for individual questions and do not use issues :) Ferel free to start one in "Q&A" at https://github.com/lllyasviel/Fooocus/discussions/categories/q-a
