### ISSUE TITLE
Is something wrong in my operation or prompt?

### ISSUE THREAD

**Issue by chenhaokui** [lllyasviel/Fooocus#2173]
![Snipaste_2024-02-05_23-44-19](https://github.com/lllyasviel/Fooocus/assets/92264358/9bf96767-baae-44d0-99a0-15a1b3e1501c)
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

**Comment by mashb1t** [comment]
I assume you're coming from DALL-E, which allows such operations.
This is not how Stable Diffusion works, it does not use a natural language prompt preprocessor. Please write the prompt with things you actually want in the target image, not `change <this> to <that>`.

Tutorials:
- https://stable-diffusion-art.com/prompt-guide/
- https://stable-diffusion-art.com/beginners-guide/

Advanced tip: you can create a mask based on a prompt and automate the inpaint process after https://github.com/lllyasviel/Fooocus/pull/2032 is merged, when applying the changes locally or when using [my fork](https://github.com/mashb1t/Fooocus) (instructions for switching in https://github.com/mashb1t/Fooocus?tab=readme-ov-file#switching-from-fooocus-to-this-fork)

**Comment by chenhaokui** [comment]
> I assume you're coming from DALL-E, which allows such operations. This is not how Stable Diffusion works, it does not use a natural language prompt preprocessor. Please use inpainting and write the prompt with things you actually want in the target image, not `change <this> to <that>`.
> 
> Tutorials:
> 
> * [[Fooocus 2.1.822] Fooocus Inpaint or Outpaint (Midjourney Left/Right/Top/Bottom) #414](https://github.com/lllyasviel/Fooocus/discussions/414)
> * https://stable-diffusion-art.com/prompt-guide/
> * https://stable-diffusion-art.com/beginners-guide/
> 
> Advanced tip: you can create a mask based on a prompt and automate the inpaint process after #2032 is merged, when applying the changes locally or when using [my fork](https://github.com/mashb1t/Fooocus) (instructions for switching in https://github.com/mashb1t/Fooocus?tab=readme-ov-file#switching-from-fooocus-to-this-fork)

OK,i"ll try it, thanks bro!
