### ISSUE TITLE
Invalid HTML in private log output

### ISSUE THREAD

**Issue by V1sionVerse** [lllyasviel/Fooocus#2178]
Please fix the following mistakes in the HTML code produced by `private_logger.py` by using the correct HTML5 self-closing tag syntax:

original:
`<img src='{only_name}' onerror=\"this.closest('.image-container').style.display='none';\" loading='lazy'></img>`
correction:
`<img src='{only_name}' onerror=\"this.closest('.image-container').style.display='none';\" loading='lazy'/>`

and replace all occurrences of `</br>` with `<br/>`

Please also add `<!DOCTYPE html>` right before the opening `<html>` tag for the sake of completeness.

**Comment by mashb1t** [comment]
Feel free to provide a PR for these changes by modifying the private_logger.py file.
This is currently not highest prio.

**Comment by V1sionVerse** [comment]
Done: https://github.com/lllyasviel/Fooocus/pull/2187
