### ISSUE TITLE
Fooocus Not Working for Google Colab Users

### ISSUE THREAD

**Issue by jatinpreeet** [lllyasviel/Fooocus#2186]
When we run the command that is available for Google Colab Users it generates a link ( same as before ) but when I open the link , on the new tab it keeps on running forever and nothing is displayed and eventually 504 ERROR is displayed
<img width="1306" alt="Screenshot 2024-02-06 at 5 54 06 PM" src="https://github.com/lllyasviel/Fooocus/assets/137918595/5efbc93c-96eb-46be-9265-8fb8dbb14172">
<img width="1391" alt="Screenshot 2024-02-06 at 5 54 39 PM" src="https://github.com/lllyasviel/Fooocus/assets/137918595/548a10e2-0623-4af9-8fac-bc500ea5182e">
<img width="1490" alt="Screenshot 2024-02-06 at 5 54 54 PM" src="https://github.com/lllyasviel/Fooocus/assets/137918595/cd3f1ca0-8670-4db9-839e-16a9bd61217f">

**Comment by jatinpreeet** [comment]
> Hello, I have the same problem, is there any way out?

Actually I got to know that this problem is not from Fooocus but from Gradio on which this app is hosted live on , well let's see how fast hugging face will resolve this issue , considering their work and employees I think this should be resolved in 3-4 hours.

**Comment by NemesisPrasa** [comment]
Yeah, got the same issue. Fooocus just worked fine few hours ago and then just stopped working as you described on this.

**Comment by trivikramak** [comment]
Is there any resolution yet?

**Comment by machomooch** [comment]
Hello, I have the same problem . Its show "504 Gateway Time-out"

**Comment by jatinpreeet** [comment]
> Is there any resolution yet?

Well , some officials from Hugging Face said on their official discord channel  "we are aware of this and and working on it",
I mean come on now , it's been over 6 hours since this thing is down.
![IMG_6855](https://github.com/lllyasviel/Fooocus/assets/137918595/3e328ea4-fa74-477a-8334-9e251a7d44cb)

**Comment by mashb1t** [comment]
Closing this issue, works again!

**Comment by SkelegonDK** [comment]
This is issue is back


`
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share', '--always-high-vram']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.3.1
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Total VRAM 40514 MB, total RAM 85481 MB
Set vram state to: HIGH_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA A100-SXM4-40GB : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
2024-04-27 20:38:02.200526: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-27 20:38:02.200575: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-27 20:38:02.202684: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-27 20:38:03.459513: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7865
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
loaded straight to GPU
Requested to load SDXL
Loading 1 new model
Base model loaded: /content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [/content/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.59 seconds
Started worker with PID 14780
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865 or None

`
