### ISSUE TITLE
Fooocus NOT WORKING on Google Colab's Gradio Link

### ISSUE THREAD

**Issue by talha9445** [lllyasviel/Fooocus#2189]
I admit that I have read the troubleshoot thoroughly.

The issue is being faced by all of the Google Colab's users. Before 3 hours ago, Fooocus was working fine on Google Colab. But since the last 3 hours, the gradio link which is generated is not working. All other AI models are working pretty fine on the Google Colab. Only Foocus's gradio link is unable to open.

I have run the code in the colab multiple times as you can see. My requirements are already satifisfied:-
<img width="928" alt="1" src="https://github.com/lllyasviel/Fooocus/assets/136476133/ca9414b7-0f71-464b-94cc-a4cf2e5c17dc">
<img width="897" alt="2" src="https://github.com/lllyasviel/Fooocus/assets/136476133/9a872656-7928-4682-a743-583040983f3d">
When the gradio's link is generated, we click the link but it keeps on loading like this:-
<img width="819" alt="3" src="https://github.com/lllyasviel/Fooocus/assets/136476133/0621605a-cfe2-4c59-9236-22e91aee0be5">
After about 15-20 seconds , the opened tab crashes itself:-
<img width="737" alt="4" src="https://github.com/lllyasviel/Fooocus/assets/136476133/c5c339de-652d-435d-b506-5e2ff3b74741">
And there is no change in the terminal also:-
![image](https://github.com/lllyasviel/Fooocus/assets/136476133/c82caca0-6fcf-46a6-861b-98a91760b5f7)

KINDLY STATE THE SOURCE OF THE BUG AND TELL HOW MUCH TIME WILL IT TAKE TO SOLVE THIS BUG? KINDLY PROVIDE YOUR RESPONSE IN DETAIL SO EVERYONE READING CAN UNDERSTAND...

**Comment by auino** [comment]
This is a clone of issue #2186.

**Comment by machomooch** [comment]
Hello. I also have this error too. "504 Gateway Time-out"  

Yesterday it was working well but today  ""504 Gateway Time-out"  "

**Comment by igninjaz** [comment]
I have the same issue at the moment. Please help

**Comment by StepHaze** [comment]
I'm facing this issue as well.

**Comment by zhanziyang** [comment]
Same

**Comment by talha9445** [comment]
UPDATE: It's fixed now. You can use it again normally :)

**Comment by talha9445** [comment]
UPDATE: It's fixed now. You can use it again normally :)

**Comment by auino** [comment]
Seems not to work again.

**Comment by shafali03** [comment]
Hi it seems like the colab not working how long will it take to fix the issue many thanks

**Comment by thakurtech** [comment]
Facing the same issue for the first time on 27th May 2024 "404 Gateway Time-out"

**Comment by lonley79** [comment]
I Am Facing The Same Issue On 06-Oct-2024. ''504Gateway Time-out"
