### ISSUE TITLE
No HIP GPUs are available

### ISSUE THREAD

**Issue by vishnuravva** [lllyasviel/Fooocus#2190]
When i try to load a model it shows such error.
I am using Linux Ubuntu 22.04 and having [AMD/ATI] Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X]
How it can be resolved

**Comment by eddyizm** [comment]
Hi @vishnuravva, 
Unfortunately, AMD gpu's have some known [issues](https://github.com/lllyasviel/Fooocus/issues?q=is%3Aissue+is%3Aopen+amd) with fooocus. Take a look and search to see if this issue is already opened elsewhere as we are consolidating them so they get resolved together.

**Comment by mashb1t** [comment]
^ what @eddyizm said!
Closing as duplicate of e.g. https://github.com/lllyasviel/Fooocus/issues/1079
