### ISSUE TITLE
Add cuda model loading config

### ISSUE THREAD

**Issue by MindOfMatter** [lllyasviel/Fooocus#2199]
https://github.com/MindOfMatter/Fooocus-MindOfMatter-Edition/pull/17

**Comment by MindOfMatter** [comment]
Hi

I just created a fork fooocus project version just synced with the original project in main branch
https://github.com/MindOfMatter/Fooocus-MindOfMatter-Edition

I created a pr in my fork project to show what we need to change to enable the feature

https://github.com/MindOfMatter/Fooocus-MindOfMatter-Edition/pull/17

If you want to test it, you need to replace your fooocus local folder with mine
(according to selected feature branch)

Also my dev branch contains all merged tested pr features in my fork project
https://github.com/MindOfMatter/Fooocus-MindOfMatter-Edition/tree/dev

I hope that it could help you :)

Have a nice day

**Comment by mashb1t** [comment]
Basically the same as in https://github.com/lllyasviel/Fooocus/issues/2198#issuecomment-1933133239, the args `--always-high-vram` and `always-gpu` prevent models from offloading if sufficient resources are available. This solution doesn't have any failsafe mechanisms and may introduce more loading/offliading shifts from GPU.
Your feedback is welcome!

**Comment by MindOfMatter** [comment]
You're right, I didn't know it. 

You can delete this issue then.

I have not tested with these arguments thank you for sharing it with me :)
