### ISSUE TITLE
The face always broken

### ISSUE THREAD

**Issue by ykhasia** [lllyasviel/Fooocus#2200]
When I generate a person the face always broken, seems fooocus can't use adetailer plugin.
Any solution could resolve this defect?

**Comment by mashb1t** [comment]
There is no adetailer support in Fooocus, also no plugin support. The official solution is to use a sufficient prompt and if the result is not of expected quality, use inpaint with improve details to re-render faces, hands, etc. in higher quality.
Closing as won't do, adetailer or face plugin support already is an enhancement in the backlog.
