### ISSUE TITLE
Problem with eye color in prompt

### ISSUE THREAD

**Issue by FanteHub** [lllyasviel/Fooocus#2205]
Hi,
thank you for your great work!
I've a strange problem or a mistake in the prompt, but I'm not able to fix.

for example this prompt

young 28 years old man,  beautifully detailed eyes, (best quality), extremely detailed handsome gentleman, vest face, high quality, fine fabric, full body, 8k, cinematic lighting,  dark blue tight suit,  elegant black shoes, different poses

produces this result

![Screenshot 2024-02-08 at 11 28 42](https://github.com/lllyasviel/Fooocus/assets/20957864/d5a38e61-360e-45d7-b3d5-465e48ead150)

adding the eyes color

young 28 years old man,  beautifully detailed eyes, (best quality), extremely detailed handsome gentleman, vest face, high quality, fine fabric, full body, 8k, cinematic lighting,  dark blue tight suit,  elegant black shoes, different poses, green eyes

I have this result:
![Screenshot 2024-02-08 at 11 29 39](https://github.com/lllyasviel/Fooocus/assets/20957864/585fdbad-4d81-49da-a9ad-8894ef9f923f)

I've tried to change the order but the clothes become green

Could you help me?
Thankyou

**Comment by sab76** [comment]
This is a problem with stable diffusion: it's not good at changing the color of precise objects. Adding a color to your prompt has a high chance of that color affecting other parts of the image. If you want him to have green eyes, it's easier to inpaint specifically the eyes or use photo editing software.

**Comment by mashb1t** [comment]
> This is a problem with stable diffusion: it's not good at changing the color of precise objects. Adding a color to your prompt has a high chance of that color affecting other parts of the image. If you want him to have green eyes, it's easier to inpaint specifically the eyes or use photo editing software.

^  this!

**Comment by alhar-sd** [comment]
I don't know if you already understand the process of adding color to the eyes without affecting the color of clothes and other things.
Follow this hierarchy in your Prompt example:

(Sexy secretary Women's Sparkly Sequin red Skirt Mid Waist Glitter Party Club Velvet red Skirts), (((sexy model girl 19yo, light green eyes))),

The colors of the clothes before the color of the eyes, this works well for me.
I hope it helps.
