### ISSUE TITLE
0.8 aspect ratio 1024x1280 seems to work fine. any thoughts?

### ISSUE THREAD

**Issue by rafstahelin** [lllyasviel/Fooocus#2207]
Hi. Ive been having this doubt in my head. I have trained dozens of human dreambooth lora models of people, with some fullbodies (usually datasets of mostly closeups and midshots, some fullbodies. I used 1024px width by 1280px height, which is 0.8 ratio compared to the 896x1152 sdxl ratio of 0.777. I cannot see any distortions in the gen's. Would you say there may be improvements of some sort, alghtough i dont see any issues?

**Comment by mashb1t** [comment]
Closing as answered in https://github.com/lllyasviel/Fooocus/pull/1617#issuecomment-1934392963
