### ISSUE TITLE
Install and run Fooocus without a default model loaded

### ISSUE THREAD

**Issue by rajtilakjee** [lllyasviel/Fooocus#2208]
**Is your feature request related to a problem? Please describe.**
I usually use Fooocus on AWS SageMaker Studio Lab. However, it has limited space. I can delete delete Juggernaut and load a different checkpoint but every time I restart Fooocus, it starts downloading Juggernaut once again however, it doesn't finish because there's no space left. I use [this script](https://github.com/rajtilakjee/fooocus-sagemaker-studio) to use Fooocus on SageMaker Studio Lab.

**Describe the idea you'd like**
If there is an option to install and run Fooocus without installing any default checkpoint, it would be really helpful.

**Comment by mashb1t** [comment]
This possibility already exists. Feel free to use a custom preset and change the default model of the preset.
