### ISSUE TITLE
Issue with History Log. Have custom output folder. How to fix?

### ISSUE THREAD

**Issue by rafstahelin** [lllyasviel/Fooocus#2209]
I have the following custom output:
"path_outputs": "E:\\studio Dropbox\\studio\\ai\\output\\pc_fooocus" set in the config.txt file. Images are being saved there, i can see them. Its all good so far. 

But when i select history log, i get this:

{"detail":"File not allowed: E:/studio Dropbox/studio/ai/output/pc_fooocus/2024-02-08/log.html."}

This appears in my chrome browser. 

I am running the latest fooocus install

**Comment by eddyizm** [comment]
I want to say this may not be working as expected. There is a PR for a CLI overide fix. See [#2074 ](https://github.com/lllyasviel/Fooocus/pull/2074)

**Comment by mashb1t** [comment]
@rafstahelin also see https://github.com/lllyasviel/Fooocus/issues/1485.
If you need a fix for this feel free to apply https://github.com/peterng1618/Fooocus/commit/78142a097dce201bb64d3854f2986857449ea1c8 after line https://github.com/lllyasviel/Fooocus/blob/main/webui.py#L622 locally.
You can work with symlinks though, see https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mklink
