### ISSUE TITLE
Changing the inference/sampling steps

### ISSUE THREAD

**Issue by fx1234** [lllyasviel/Fooocus#2223]
Hi,

thanks for the interesting project.

As far as I can see, the inference/sampling steps for "Quality" are set to 60. Is there a way to change this number?

**Comment by poor7** [comment]
Advanced - Developer Debug Mode - Debug Tools - Forced Overwrite of Sampling Step

**Comment by melteemcaglar** [comment]
after the update, when I change the sampling step, it generates until the last moment and then it is canceled. how can I solve this?

**Comment by Nanoche** [comment]
You need to read what the console (command line) writes. Perhaps some file (LoRA, embedding...) is missing or something else.

**Comment by Nanoche** [comment]
> after the update, when I change the sampling step, it generates until the last moment and then it is canceled. how can I solve this?

You need to read what the console (command line) writes. Perhaps some file (LoRA, embedding...) is missing or something else.
