### ISSUE TITLE
Computer crashes halfway through generating image

### ISSUE THREAD

**Issue by samrluxford** [lllyasviel/Fooocus#2224]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

The Problem I am having is that while trying to generate an image my computer keeps crashing and I am unable to figure out why.
I am using a 
AMD Ryzen 7 5800X CPU
AMD Radeon RX 6800 XT GPU ( 16gb VRAM )
4x G.Skill F4-3200C16-32GTZN DDR4 ( 32gb each )
Samsung SSD 980 PRO 1TB ( I know doesn't seem relevant but I saw someone say this might be the problem somewhere perhaps someone could clarify if it is and why? )
EVGA 850 G5 power supply ( I don't think it's a lack of power I've tested it and it seems well within it's capacity)

I suspect it has to do with the graphics card because when I use
`--always-gpu`
it crahsse as soon as I start typing.
I have also tried
`--always-cpu`
and this also crahes mid generation so I'm not sure?
I have also tried
`--disable-xformers` which I saw someone else say helped.
I would also like to confirm that I do have it right for AMD
`.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
.\python_embeded\python.exe -m pip install torch-directml
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml --preset realistic
pause`

I am also sure it isn't a colling issue because I've used tools while It's run to monitor that and I have also monitored the usage the usage for the CPU and GPU do not use more then 70- 80 %.

Does anyone have any idea what the issue may be I suspect it might be the AMD GPU for the reason I stated above but am not sure.

I am unfortunately not able to provide a console log of when the issue occurs due to the computer crashing and have to restart I am unable to retrieve it and can only provide up till before it starts generating the image.

**Comment by lgwjames** [comment]
crash or just a black screen? you should have a log from the cmd

**Comment by samrluxford** [comment]
Yes it crashes here are the last 2 logs from the cmd.

Event[52]:
  Log Name: System
  Source: User32
  Date: 2024-02-08T05:56:43.3590000Z
  Event ID: 1074
  Task: N/A
  Level: Information
  Opcode: N/A
  Keyword: Classic
  User: S-1-5-18
  User Name: NT AUTHORITY\SYSTEM
  Computer: WIN-H76L6OMK9PO
  Description:
The process C:\Windows\system32\winlogon.exe (MINWINPC) has initiated the restart of computer WIN-H76L6OMK9PO on behalf of user NT AUTHORITY\SYSTEM for the following reason: Operating System: Upgrade (Planned)
 Reason Code: 0x80020003
 Shutdown Type: restart
 Comment:

Event[53]:
  Log Name: System
  Source: EventLog
  Date: 2024-02-08T05:56:05.4050000Z
  Event ID: 6005
  Task: N/A
  Level: Information
  Opcode: N/A
  Keyword: Classic
  User: N/A
  User Name: N/A
  Computer: WIN-H76L6OMK9PO
  Description:
The Event log service was started.

**Comment by samrluxford** [comment]
Good news I was able to fix it not sure why but once I downloaded AMD software Adrenaline edition and had it running in the background I was able to generate images without it crashing I was originally doing this to see if I could find what the problem was I can now safely assume it was the GPU but as I said for some reason running this in the background stops it/
Unsure why but it does :)
