### ISSUE TITLE
Fooocus crashing of first boot in COLAB

### ISSUE THREAD

**Issue by floxdaw** [lllyasviel/Fooocus#2230]
[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
Fooocus has been working finde for many months. Today when I start up a new session in COLAB, it cannot import a module and is crashing.

Below is the console log from my second attempt at running the session:

```
Requirement already satisfied: pygit2==1.12.2 in /usr/local/lib/python3.10/dist-packages (1.12.2)
Requirement already satisfied: cffi>=1.9.1 in /usr/local/lib/python3.10/dist-packages (from pygit2==1.12.2) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.9.1->pygit2==1.12.2) (2.21)
/content
fatal: destination path 'Fooocus' already exists and is not an empty directory.
/content/Fooocus
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.1.864
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /content/Fooocus/models/vae_approx/xlvaeapp.pth

Traceback (most recent call last):
  File "/content/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/content/Fooocus/launch.py", line 124, in <module>
    download_models()
  File "/content/Fooocus/launch.py", line 90, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae_approx, file_name=file_name)
  File "/content/Fooocus/modules/model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

```

**Comment by eddyizm** [comment]
Looks like an http error, I know today huggingface was returning a `503` for several hours as they were doing some kind of maintenance. My suspicion is that you were experiencing some of that as well. 
I would suggest if you get http errors when trying to download models/files from huggingface that you either go to the actual website in your browser and verify you can download the file or to be more fancy, I have a preset that grabs models from civitia, with some of the smaller files you may be able to mount them to your google drive so you don't have to download everything again in colab.

**Comment by eddyizm** [comment]
just gave it a try and my colab is also failing, 
when i try to go directly to the repo I get a 504 
https://huggingface.co/lllyasviel
![image](https://github.com/lllyasviel/Fooocus/assets/12236892/35f8b552-c4dd-4b1e-9eff-8868c765a21b)

looking at what I can do to work around this.

**Comment by CreatedbyRamy** [comment]
Hi Eddy, I sent you an email regarding this, not sure if the contact option on your blog still works?

**Comment by eddyizm** [comment]
> Hi Eddy, I sent you an email regarding this, not sure if the contact option on your blog still works?

something seems to be amiss with the mailgun account and im getting messages. you can hit me on discord or my mastodon link. 

I pointed the main checkpoint to civitia and skipped a file check, but the app requires too many files from huggingface. Suggest to wait or run it locally as all my files are already loaded.

**Comment by eddyizm** [comment]
> Hi Eddy, I sent you an email regarding this, not sure if the contact option on your blog still works?

ok fixed the account there, tested and working again.

**Comment by mashb1t** [comment]
I've been able to spin up a Colab instance using the playbook without any issues. Please check again if the issue still exists on your end.

**Comment by floxdaw** [comment]
Just tried running an instance. No issues.

So just a temporary issue it seems

**Comment by CreatedbyRamy** [comment]
Hi David,
Thanks for the reply, yes it's working now again but wouldn't it be better
if we could save a version locally just in case huggingface? I am not sure
how to do it

**Comment by mashb1t** [comment]
@CreatedbyRamy if you're using Fooocus on your local machine and have already successfully started it once, the file has already been downloaded and will never have to be downloaded again (see https://github.com/lllyasviel/Fooocus/blob/fdc4dc1d8793e71a43c89e75e73f3e050d3dd308/launch.py#L63)
The whole point of Colab is to provide ephemeral instance access by always setting it up from scratch.
If you want to prevent this from happening you can mount the models folder from your Google Drive, but you'll need 8+GB of storage for this.
