### ISSUE TITLE
What I can't obtain (inelaborate images)

### ISSUE THREAD

**Issue by StepHaze** [lllyasviel/Fooocus#2241]
Thank you for this awesome project!
It allows me to create fantastic images full of objects with luxuriant background.

But what I want is to create simple (colored, but plain and inelaborate) images: stand-alone object (for example, cat or chess figure) with no backgound.
How can I achieve this?

**Comment by mashb1t** [comment]
@StepHaze This is nothing Fooocus can fix, you'll have to experiment with the (negative) prompt. Try to disable all styles and check again, as each style adds its own keywords to prompts, and feel free to provide your feedback despite closing this issue.
