### ISSUE TITLE
Zip file won't expand

### ISSUE THREAD

**Issue by Psokratease** [lllyasviel/Fooocus#2244]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**

I have downloaded "Fooocus_win64_2-1-831.7z" Using 7-zip I attempted to extract. 4 hours later it is at 29%...
Machine is win 11, 3090 gpu, 64 gb ram, 1 tb hd remaining.
Tried it twice on 2 different solid-state drives. Same result.

**Comment by mashb1t** [comment]
I've unzipped and installed the 7z file multiple times already and there has neber been any issue.
Decompressing is a CPU heavy task, so please ensure to close background processes using up your CPU resources or when using a virtual machine / docker, assign more vCPU cores and/or extract directly from the host to the mounted volume.

**Comment by Psokratease** [comment]
Ryzen 9 5900x must be too slow with no other process running. I will await a different release that my PC can handle then., Thank you for the response.

**Comment by mashb1t** [comment]
Very strange, i have a similar setup (5900x, 3080, 32GB RAM) and no issues with the zip file, also not on a Macbookand so has nobody else... I'm not sayung it's your system but there are some signs supporting this hypothesis.

**Comment by mashb1t** [comment]
I mean, if this zip file doesn't work and to confirm if it's maybe an issue with 7z on your machine, you may give the one in my fork a shot (attached to https://github.com/mashb1t/Fooocus/releases/tag/2.1.864).

**Comment by Psokratease** [comment]
It is a mystery, I have rebooted to try again.  29% at present in the python site packages. I did download the code directly, but no Bat files (Which leaves this rookie out of luck on how to get it running). My extract speed is at 4300 kb/s. I'm not sure what else to do.

**Comment by mashb1t** [comment]
One last thing you might check is the disk usage percentage in task manager (i assume you're using Windows due to writing about .bat files).
If your drive is at 100% it's the bottleneck and slowing down everything else.
Also check if your CPU is in energy saving mode or similar in your mainboard utility software settings.
All the best!

**Comment by Psokratease** [comment]
Thank you!

**Comment by fershopls** [comment]
I'm also having this issue with windows 11, Ryzen. I tried with WinRAR, 7z and default windows zip manager. It's so slow. >50min waiting and it doesn't finishes the uncompression.

**Comment by Psokratease** [comment]
I finally found a cure for this: WinZip.
Worked flawlessly and fast.

I don't know why the other compression software failed.

**Comment by yogiyushi** [comment]
stuck because i can't unzip file either with 7zip or winrar and winzip says trial expired so i am out of luck

**Comment by Psokratease** [comment]
I don't know if it's allowed or possible, but I wonder if someone that does have access to it can expand it and recompress with 7-zip or something.
This should be a non-issue.
Dev can fix if so inclined...

**Comment by mashb1t** [comment]
The zip file has already been created with 7zip.

**Comment by Psokratease** [comment]
> The zip file has already been created with 7zip.

I don't understand the problem the we experienced then. Only WinZip would work on our particular machines. Any freeware compression software did not work for us.
🤷...
