### ISSUE TITLE
not an issue, but request a Queue system

### ISSUE THREAD

**Issue by faridskyman** [lllyasviel/Fooocus#225]
possible to have a queue system, so if i want it to generate for all the styles, i can add that request to queue and it will run, while i go for lunch. i think we can, im not sure if i can help with this, but do you do guys think?

**Comment by Semonxue** [comment]
The CamfyUi's Queue system is good. Can reused this?

**Comment by PrestonLeeC** [comment]
Yes, please! I can't seem to figure out any other Stable Diffusion workflow, but Fooocus is working so awesome right now. I just want to leave my computer running and generate 100s of images while I'm at work! :)

**Comment by MNeMoNiCuZ** [comment]
Yes please. A simple queue system. Instead of pressing Generate, you add to queue. And a simple way to remove a queued item. And then to run the queue.

**Comment by sclausen** [comment]
That would be awesome! DiffusionBee has a great workflow with it's queuing system. Unfortunately it's abandoned, setting it up for development is undocumented and I didn't got it to work. And it currently doesn't support SD XL.

**Comment by xx88xx** [comment]
has there been any progress on this queue system? It would be super useful!

**Comment by zeonglow** [comment]
I would love to have a go at implementing this,  but from a quick read through the source code,  I'm guessing it would be a fair amount of work trying to understand what is going on!     I will also need to play with Gradio a bit to understand how it works. 
Off the top of my head,  *replacing* the generate button with a queue feature,  would be neater.   

Also,  I imagine there would be some pushback to introducing Redis, Celery, or some other 3rd party service to Fooocus,  which makes implementation tricker.

**Comment by mashb1t** [comment]
A queue would be awesome and some people are already working on this (e.g. https://github.com/lllyasviel/Fooocus/issues/1664, which still needs a bit of work before it can be a PR).
Closing this issue in favor for it.
