### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by SoftologyPro** [lllyasviel/Fooocus#2251]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
Which zip is the latest to use?

There is
`https://github.com/lllyasviel/Fooocus/releases/download/release/Fooocus_win64_2-1-831.7z`
linked from
`https://github.com/lllyasviel/Fooocus?tab=readme-ov-file`
under the `>>> Click here to download <<<` link.

Then there is
`https://github.com/lllyasviel/Fooocus/archive/refs/tags/2.1.865.zip`
under the latest release.

The problem with the latest 2.1.865 release is that there is no run.bat once extracted.  Is there a new way to launch Fooocus once downloaded and unzipped?  Or is that a missing file bug?

**Full Console Log**
N/A

**Comment by mashb1t** [comment]
Please download the one linked in the readme, it will automatically update to the latest version 2.1.865.
