### ISSUE TITLE
Slider LoRA #3 doesn't move well with the mouse.

### ISSUE THREAD

**Issue by poor7** [lllyasviel/Fooocus#2253]
Slider LoRA №3 doesn't move well with the mouse. But after entering a digital value, it starts moving normally.

**Comment by mashb1t** [comment]
No issues for me. Are you by chance using a fork or pure Fooocus and do you have any config for LoRA 3 set by default?
Do you also have the issue when reloading the browser or on Colab without any modifications to the config?

**Comment by poor7** [comment]
Pure focus. The problem is rare, it is not reproduced often, I will try to clarify the details for reproduction.

**Comment by barepixels** [comment]
brower is prob running out of memory.  refresh or quit and relaunch web browser

**Comment by mashb1t** [comment]
Closing for now, might reopen when reproducible
