### ISSUE TITLE
Kaggle --share webui doesn't work

### ISSUE THREAD

**Issue by Sitolam** [lllyasviel/Fooocus#2257]
**Describe the problem**
If I try to start the program on kaggle with the `--share` feature it just gives this error and fooocus crashes:
![image](https://github.com/lllyasviel/Fooocus/assets/79202140/10958472-eee0-4ae4-80b1-1e388c89ab5c)

**Full Console Log**
```bash
Running on public URL: https://35e24552b7ee093a1a.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Creating index file ./outputs/2024-02-13/imageme.html
Processing ./outputs/2024-02-12
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
```

**Comment by mashb1t** [comment]
Fooocus does not offer support for other runtimes than the ones pointed out in the readme. Feel free to check https://github.com/lllyasviel/Fooocus/issues/2155 for support and check if this is the same issue.
