### ISSUE TITLE
Negative prompts doesnt works

### ISSUE THREAD

**Issue by JD-Alx** [lllyasviel/Fooocus#2263]
I've tried several times to generate Ayanami Rei in different styles, but she still has an Asian appearance. I also tried generating "Film Production" (yes, I realize it's an unspecific promt, but why this result??) and got a bunch of women, then tried adding a negative promt and it didn't work again. The women only disappeared when I disabled the Fooocus Masterpiece and Fooocus V2 styles.... _And how to return default settings of Deloper Debug Mode? I changed Sampler, Sheduler and TSNR there, on the forum it was written that it can help not to ignore negative promt, but it didn't help. I changed the values back (TSNR value I don't remember)._ Is this a bug or am I doing something wrong? 

I apologize in advance for the stupid question :D
**_Screenshoots:_**
<details>

![2024-02-14_224219](https://github.com/lllyasviel/Fooocus/assets/159651224/54d81454-402e-4d3c-8945-4bd1361e840e)
![2024-02-14_224212](https://github.com/lllyasviel/Fooocus/assets/159651224/a8abe263-b67d-4530-a12f-760d2bb8ef99)
![2024-02-14_222715](https://github.com/lllyasviel/Fooocus/assets/159651224/669cbb61-30de-40ba-b120-5ccd41681d8b)
![2024-02-14_222910](https://github.com/lllyasviel/Fooocus/assets/159651224/82ec3474-4a3a-4ba9-9d88-83bc5e742917)
![2024-02-14_222942](https://github.com/lllyasviel/Fooocus/assets/159651224/8fee3419-612c-4a25-91c7-317eec81a428)

</details>

**Comment by ILikeToasters** [comment]
As for returning to the default values in debug mode, if you refresh the browser or restart Fooocus it will have the default settings.

**Comment by mashb1t** [comment]
You can increase the prompt strength by putting keywords in parenthesis to in/decrease the likelihood of the resulting image resembling the word, e.g. "(asian:1.2)" in negative prompt.
As @ILikeToasters already mentioned reloading the website resets all settings to their defaults.

**Comment by JD-Alx** [comment]
> e.g. "(asian:1.2)" in negative prompt.
Thanks, but it didn't work again :( How does the number after the colon affect the effectiveness of the negative prompt?

**Comment by mashb1t** [comment]
@JD-Alx see https://stable-diffusion-art.com/prompt-guide/, headline "Keyword Weight"

**Comment by JD-Alx** [comment]
@mashb1t Ok, tnx. Also, I've now tried it on simpler examples and still see the negative prompt being ignored - no matter how hard I try, it generates cats with white fur... It didn't work out with the Asian woman either.
<details>
![2024-02-15_202823](https://github.com/lllyasviel/Fooocus/assets/159651224/87f5f6c1-76e8-4664-94f9-9e3fe3008898)
![2024-02-15_202135](https://github.com/lllyasviel/Fooocus/assets/159651224/24f17572-703a-4fa1-8622-4fa7874b7ad8)
![2024-02-15_191357](https://github.com/lllyasviel/Fooocus/assets/159651224/5ad170a1-8887-49f8-b9bf-fae4c37022a1)
</details>
_Styles: Fooocus v2, fooocus enhance, fooocus sharp_

**Comment by APCOTech** [comment]
Same here, whatever I add to negative prompt are ignored completely.

**Comment by mashb1t** [comment]
Try to use less styles or increase cfg scale.

**Comment by aldozorzi** [comment]
Custom negative prompts are simply put after all negative prompts created by "Style". Don't understand why, my negative prompt is surely always more important than automatic ones, I suggest to append "style" prompts to ours.

**Comment by mashb1t** [comment]
@aldozorzi this shouldn't matter: https://arxiv.org/abs/2406.02965v1
