### ISSUE TITLE
api-ms-win-core-path-l1-1-0.dll issue

### ISSUE THREAD

**Issue by HedgeCoinCrypto** [lllyasviel/Fooocus#2269]
Hi, i'm running win7 x64, when running "run.bat" I get "The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem" so i put api-ms-win-core-path-l1-1-0.dll in system32 (also tried fooocus folder) now when i run "run.bat" i get "The application was unable to start correctly (0xc000007b). Click OK to close the application", how can I fix this? thanks

**Comment by mashb1t** [comment]
Please provide the full terminal output, thanks!

**Comment by HedgeCoinCrypto** [comment]
> Please provide the full terminal output, thanks!

Hi, thanks, it's the windows version, no terminal output to show, only this

![image](https://github.com/lllyasviel/Fooocus/assets/156864030/16798286-1c9f-41bb-8048-7a1506c6fd0b)

**Comment by mashb1t** [comment]
Frankly speaking, i'm not certain if Windows 7 is officially supported, but as you've already notices this is most likely not a Fooocus issue but an issue with your OS. Normally dll files should be kocated in the system32 folder of Windows itself.
