### ISSUE TITLE
Python RAM usage so high but gpu usage is too low

### ISSUE THREAD

**Issue by ngaia1** [lllyasviel/Fooocus#2270]
Edit: i tried on other webui, it looks like because of juggernautXL_v8Rundiffusion , Can i run fooocus without this model (if i deleted this model, fooocus will automatically download again)

I am runing on i5 10gen, 16gb ram, RTX 3060 (12gb ram)

when i generate image my ram usage will go up around 90% and gpu stays at around 20-30%, it's like my doing all the works
![runing](https://github.com/lllyasviel/Fooocus/assets/64317761/af0e8ad6-8fb9-40f7-be63-f542312d4ae4)

even after job done, ram usage will stay at around 80% untill i closed cmd. 
![after](https://github.com/lllyasviel/Fooocus/assets/64317761/7f44217e-2eb1-422c-9a01-699a51b7cccd)

is this normal? please help me

**Comment by mashb1t** [comment]
This is normal, please check your performance tab in task manager for more information about GPU usage.

**Comment by mashb1t** [comment]
Vlosing as not an Issue of Fooocus, please nevertheless send a screenshot of your performance tab output after selecting GPU during rendering!
