### ISSUE TITLE
Three default styles

### ISSUE THREAD

**Issue by StepHaze** [lllyasviel/Fooocus#2286]
By default, three styles are on: Fooocus V2, Fooocus Enhance and Fooocus Sharp.
Why is it so? What do they mean?

I've heard that Fooocus V2 works as GPT (in other words, it is for better "understanding" text prompts), is it correct?
Thank you.

**Comment by lgwjames** [comment]
why is this posted in issues? this should be in Q&A :)

**Comment by mashb1t** [comment]
@StepHaze this is how it works best. If you want to change it you can override the default styles in your config.txt file.

@lgwjames i'll do an update to the issues/feature request reporting templates today
