### ISSUE TITLE
No module named 'torch_directml' issue (AMD)

### ISSUE THREAD

**Issue by EugeneRuckusHucksley** [lllyasviel/Fooocus#2294]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
running the run.bat file with the AMD GPU commands:
`.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
.\python_embeded\python.exe -m pip install torch-directml
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml
pause`
I have 64 GB ram, 7900 xtx, driver version 24.1.1

**Full Console Log**

`C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)>.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
Found existing installation: torch 2.0.0
Uninstalling torch-2.0.0:
  Successfully uninstalled torch-2.0.0
Found existing installation: torchvision 0.15.1
Uninstalling torchvision-0.15.1:
  Successfully uninstalled torchvision-0.15.1
WARNING: Skipping torchaudio as it is not installed.
WARNING: Skipping torchtext as it is not installed.
WARNING: Skipping functorch as it is not installed.
WARNING: Skipping xformers as it is not installed.

C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)>.\python_embeded\python.exe -m pip install torch-directml
Requirement already satisfied: torch-directml in c:\users\creti\appdata\roaming\python\python310\site-packages (0.2.0.dev230426)
Collecting torch==2.0.0 (from torch-directml)
  Obtaining dependency information for torch==2.0.0 from https://files.pythonhosted.org/packages/87/e2/62dbdfc85d3b8f771bc4b1a979ee6a157dbaa8928981dabbf45afc6d13dc/torch-2.0.0-cp310-cp310-win_amd64.whl.metadata
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl.metadata (23 kB)
Collecting torchvision==0.15.1 (from torch-directml)
  Obtaining dependency information for torchvision==0.15.1 from https://files.pythonhosted.org/packages/03/06/6ba7532c66397defffb79f64cac46f812a29b2f87a4ad65a3e95bc164d62/torchvision-0.15.1-cp310-cp310-win_amd64.whl.metadata
  Using cached torchvision-0.15.1-cp310-cp310-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: filelock in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.12.2)
Requirement already satisfied: typing-extensions in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (4.7.1)
Requirement already satisfied: sympy in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (1.12)
Requirement already satisfied: networkx in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.1)
Requirement already satisfied: jinja2 in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.1.2)
Requirement already satisfied: numpy in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (1.23.5)
Requirement already satisfied: requests in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (9.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from jinja2->torch==2.0.0->torch-directml) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (2023.5.7)
Requirement already satisfied: mpmath>=0.19 in c:\users\creti\test\fooocus\fooocus_win64_2-1-831(1)\python_embeded\lib\site-packages (from sympy->torch==2.0.0->torch-directml) (1.3.0)
Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Using cached torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: torch, torchvision
  WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed torch-2.0.0 torchvision-0.15.1

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)\python_embeded\python.exe -m pip install --upgrade pip

C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--directml']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.865
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)\Fooocus\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)\Fooocus\modules\patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)\Fooocus\ldm_patched\modules\model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)\Fooocus\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)\Fooocus\ldm_patched\ldm\modules\attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)\Fooocus\ldm_patched\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "C:\Users\creti\test\fooocus\Fooocus_win64_2-1-831(1)\Fooocus\ldm_patched\modules\model_management.py", line 37, in <module>
    import torch_directml
ModuleNotFoundError: No module named 'torch_directml'`

**Comment by eddyizm** [comment]
There is a lot of suggestions here  #624 that may help.

**Comment by EugeneRuckusHucksley** [comment]
@mashb1t I'm confident that it was installed. The fix was going through conda, but only if i `conda activate fooocus` will running the AI work. No idea why

**Comment by mashb1t** [comment]
@EugeneRuckusHucksley with `conda activate fooocus' you enable the project venv, in which the packages are installed, and do not use the system or embedded python, which is presumably how you've set it up.
Geeat you found a solution, closing this issue now 🎉
