### ISSUE TITLE
Cannot find empty port in range: 7860-7860

### ISSUE THREAD

**Issue by ashish-aesthisia** [lllyasviel/Fooocus#2296]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
We have started to get this issue since few recent updates. When fooocus is launched for the first time, it crashes right away saying: 

```
File "/home/ubuntu/.local/lib/python3.10/site-packages/gradio/networking-py", line 169, in start_server raise OSError(
OSerror: Cannot find empty port in range: 7860-7860. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the 'server_port parameter to
'launch ()'.
```

After i restart fooocus, it works fine. I have checked firewall, ports etc. No other process is running on the same port. 

CMD Args: --port 7860
If there was any other issue, it should not even work after a restart(foocus). 

I have checked all the github issues, but nothing was helpful. 

OS: Ubuntu
GPU: Nvidia

**Full Console Log**
![image](https://github.com/lllyasviel/Fooocus/assets/108272701/6aba899d-a645-4c50-a1b2-300bbcdb8672)

**Comment by mashb1t** [comment]
The error message points out that the poet is unavailable / not empty. Please check with `ps aux | grep 7860` which other program is running in the background occupying it. Make sure that there isn't any stale process and fooocus correctly exits (it spawns worker processes, wait for generation to finish to also stop them correctly).

**Comment by eddyizm** [comment]
Definitely sounds like it is crashing and holding that port open. A reboot will also clear it but as @mashb1t suggested, see which processes has it open and kill that process. On a slow computer, even shutting down takes time to the point where I have to manually kill processes because the cli becomes unresponsive.

**Comment by mashb1t** [comment]
@ashish-aesthisia do you still need support? If not this issue can be closed.

**Comment by ashish-aesthisia** [comment]
Yes sorry for late reply, When i am creating a new machine on cloud provider, immidiate foocus launch is breaking. So i need to restart, then it works fine. 

If it's not a new machine & suppose i am restarting the machine then initiating the foocus launch. It works fine. This is quite strange issue.
