### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by LennartW24** [lllyasviel/Fooocus#2301]
Hey friends, I have an issue when trying to install Fooocus. After I unpacked all the files from the download file and tried to run the .exe file, I ran into an issue where it would spit out some error  code (see below) and stop the download. It asks me to hit a random key and then exits out the command prompt without anything happening. The error at random percentages, once happened already at 1% and once I got to 86%. Same thing happens when I try to run the run_anime or the run_realistic. Does anyone know what I can do to fix this?

Full error code:

Traceback (most recent call last):
  File "E:\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "E:\Fooocus\launch.py", line 125, in <module>
    download_models()
  File "E:\Fooocus\launch.py", line 116, in download_models
    load_file_from_url(url=url, model_dir=config.path_checkpoints, file_name=file_name)
  File "E:\Fooocus\modules\model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "E:\python_embeded\lib\site-packages\torch\hub.py", line 651, in download_url_to_file
    buffer = u.read(8192)
  File "http\client.py", line 465, in read
  File "socket.py", line 705, in readinto
  File "ssl.py", line 1274, in recv_into
  File "ssl.py", line 1130, in read
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2548)

E:\>pause

**Comment by mashb1t** [comment]
Hey @LennartW24, as you've read the troubleshooting guide you must have also read https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#ssl-certificate_verify_failed.
Make sure you're not using any VPN and are permitted to access the checkpoint url.
You can always try to download the model(s) manually by having a look at the URLs in the default preset file and putting them in their corresponding directories. 
You can find the needed models here: 
- https://github.com/lllyasviel/Fooocus/blob/main/presets/default.json#L40-L46
- https://github.com/lllyasviel/Fooocus/blob/main/modules/config.py#L418-L527 (depending on features you're planning to use)

Hope this helps. Closing this issue as this is an individual problem of yours. Feel free to provide your feedback nevertheless.
