### ISSUE TITLE
Would you consider adding seed info to png metadata when random option is selected?

### ISSUE THREAD

**Issue by randomoneh** [lllyasviel/Fooocus#231]
It would be really useful. Alternatively, if it's already visible somewhere and I'm missing it - please point me in the right direction.

Thank you!

**Comment by barepixels** [comment]
use this version for metadata embed in PNG https://github.com/MoonRide303/Fooocus-MRE

**Comment by randomoneh** [comment]
> use this version for metadata embed in PNG https://github.com/MoonRide303/Fooocus-MRE

Unfortunatelly I'm using Colab with Lyumin's version.

**Comment by MoonRide303** [comment]
@randomoneh I've just updated colab file for MRE, you can see if it works for you: https://github.com/MoonRide303/Fooocus-MRE/blob/moonride-main/colab.ipynb

**Comment by mashb1t** [comment]
see https://github.com/lllyasviel/Fooocus/issues/241 (https://github.com/lllyasviel/Fooocus/issues/241#issuecomment-1873434362)
