### ISSUE TITLE
Tells me to download a new driver when I already have it downloaded

### ISSUE THREAD

**Issue by ILTIRCONTATO** [lllyasviel/Fooocus#2312]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
When I try running the program on the "colab" link posted, it tells me that it couldn't find a NVIDIA driver. I have updated the driver through the link provided in the log and through the "GE-Force experience" app, but the program still tells me it can't find an NVIDIA driver. I've tried restarting my laptop but it still didn't work. What can I do?

**Full Console Log**
Requirement already satisfied: pygit2==1.12.2 in /usr/local/lib/python3.10/dist-packages (1.12.2)
Requirement already satisfied: cffi>=1.9.1 in /usr/local/lib/python3.10/dist-packages (from pygit2==1.12.2) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.9.1->pygit2==1.12.2) (2.21)
/content
fatal: destination path 'Fooocus' already exists and is not an empty directory.
/content/Fooocus
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--preset', 'anime', '--share']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.1.865
Loaded preset: /content/Fooocus/presets/anime.json
Running on local URL:  (I removed this)
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/Fooocus/modules/async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "/content/Fooocus/modules/default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "/content/Fooocus/modules/core.py", line 1, in <module>
    from modules.patch import patch_all
  File "/content/Fooocus/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/content/Fooocus/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/content/Fooocus/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/content/Fooocus/ldm_patched/ldm/modules/attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/content/Fooocus/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/content/Fooocus/ldm_patched/modules/model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/content/Fooocus/ldm_patched/modules/model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 769, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Running on public URL: https://4741a6b346ce8d3737.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)

**Comment by mashb1t** [comment]
@ILTIRCONTATO are you using Google Colab (cloud infrastructure) or your Laptop (local infrastructure)?
If you're on the cloud, you don't have to install something on your Laptop, but the cloud.
Make sure you're not using Colab with TPU, but rather GPU (T4 instances or better).

**Comment by ILTIRCONTATO** [comment]
@mashb1t 
I’m using the Google colab, but it still says I have to download a driver.

**Comment by mashb1t** [comment]
@ILTIRCONTATO which instance do you use on Colab? (upper right corner, next to statistics)

**Comment by ILTIRCONTATO** [comment]
@mashb1t I can't find anything labeled "statistics" or "instances" on colab.

This is what I have on-screen:
![image](https://github.com/lllyasviel/Fooocus/assets/95072666/42185d8a-8cce-4aea-bf9c-e2a4e708ae92)

**Comment by mashb1t** [comment]
Please check the statistics (ram/disk) on thr upper right as well as the arrow down next to it.
There should be the output of the instance. In my case, this is a T4 instance. If you've selected a TPU instance, please switch to GPU.

![Screenshot_20240220-235700](https://github.com/lllyasviel/Fooocus/assets/9307310/ff454ecd-ed9f-4a2a-95c9-72dc4790ef41)

**Comment by ILTIRCONTATO** [comment]
![image](https://github.com/lllyasviel/Fooocus/assets/95072666/6bc2f6fc-a1b3-4955-8f9d-dac76830f409)


If this is what you're referring to, I've already tried chaging the type runtime type, and it didn't work.

**Comment by mashb1t** [comment]
@ILTIRCONTATO Please ensure you're 100% connected to T4 and not a TPU/CPU instance. If you want to, you can also attach a screen recording, but i'm not certain how i can support further, as using T4 works for me like a charm...

**Comment by ILTIRCONTATO** [comment]
https://github.com/lllyasviel/Fooocus/assets/95072666/d1ef4da0-f653-434e-8e40-8514d6de61ee

**Comment by mashb1t** [comment]
I'm not sure how I can further support, currently lost for ideas (works just file for me, no idea how you could be helped). Maybe you terminate your Colab session and start a new one again, ensuring T4 usage from the beginning?

**Comment by ILTIRCONTATO** [comment]
@mashb1t 

Thanks anyways.
