### ISSUE TITLE
Bug of "<span" in Settings tab and no style preview shown in Style tab

### ISSUE THREAD

**Issue by omarhrpe** [lllyasviel/Fooocus#2314]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
Hi. It turns out that I changed the fooocus folder to a new folder and then with use suddenly two things started happening to me:
1. I get a <span style and I don't know what else in the Settings tab that neither updating nor installing again fixes.
2. In the Style tab, when I put the mouse pointer over each style, the preview is not shown. I guess these are rare bugs since I have not found a solution.
3. When I activate the Input Image option, the blue box is activated, but nothing happens.
I hope you can help me or in any case help me to uninstall completely, since even deleting all the folder, cache and so on has not worked. Thank you.

Features: Windows, Nvidia, good RAM, good storage last version.

![span](https://github.com/lllyasviel/Fooocus/assets/140922882/42b10ae6-c0be-490d-a9d7-ee90d006c9bd)

**Full Console Log**
Paste the **full** console log here. You will make our job easier if you give a **full** log.

**Comment by mashb1t** [comment]
@omarhrpe this is a JavaScript error. Please check thr console tab of your browser to find more information there.

**Comment by omarhrpe** [comment]
@mashb1t hi, thanks for the answer. The installation seems to be incomplete, because apart from the <span you can't see the previews of the styles and the Input Image option doesn't work either. I removed it and installed from scratch, tried with different browsers in base modes without extensions or anything and it still doesn't work. I would like to know if there is any way to uninstall it completely on my PC to install it again or how I can fix those three little problems I have, obviously without formatting my PC. Thanks.

**Comment by mashb1t** [comment]
@omarhrpe were you able to identify the source of your JS issue and can this issue be closed?
