### ISSUE TITLE
 How to clear the cache of fooocus in the browser

### ISSUE THREAD

**Issue by jinnaluo0** [lllyasviel/Fooocus#2324]
**Is your feature request related to a problem? Please describe.**

**Describe the idea you'd like**

**Comment by eddyizm** [comment]
This is browser dependent. [link](https://www.lifewire.com/how-to-clear-cache-2617980)

**Comment by mashb1t** [comment]
1. Which cache do you mean? Filling out the form would have helped a lot. Browser cache
> This is browser dependent. [link](https://www.lifewire.com/how-to-clear-cache-2617980)

2. Fooocus doesn't have a cache, but Gradio has. You can't clear the temp picture cache in the browser, but have to manually delete it in your temp file dir of your OS. See https://github.com/lllyasviel/Fooocus/pull/1992 for more information.
