### ISSUE TITLE
help! ''Expecting value: line 1 column 1 (char 0)''

### ISSUE THREAD

**Issue by Huanxin0722** [lllyasviel/Fooocus#233]
Hi,guys,I want to ask why my webpage always prompts for errors？
''error
Expecting value: line 1 column 1 (char 0)''
I tried to turn off'' clash''.
But after closing, I was prompted that I could not connect.
I've been working on it all night and it's still unsolved. This problem drives me crazy!
[
![图片](https://github.com/lllyasviel/Fooocus/assets/142834042/2100053e-60a8-4545-9958-185ad8ae4713)
](url)

**Comment by jiatusuo123** [comment]
你好，请问解决了嘛，我也是这个问题

**Comment by Xtttt** [comment]
Me too. I'm not sure if this is the reason, is your graphics card AMD?

**Comment by sve211314** [comment]
I have the same problem. Has anyone solved it?

**Comment by sunrising101** [comment]
me too

**Comment by mori173** [comment]
可能是挂了代理产生的问题。在webui里，需要在webui-user.bat启动命令里加入--no-gradio-queue.但是fooocus我找不到在哪里加。所以请问作者 @lllyasviel

**Comment by skywolf123** [comment]
很明确用clash启用了系统代理，此时打开fooocus点击生成就会报错
这时即使关闭系统代理，再点击生成还是会报错
只有关闭系统代理并且关闭fooocus重新打开才会不报错
尝试在run.bat加入--no-gradio-queue，提示不支持这个参数
所以目前没有解决方案，只能关闭clash，至少是关闭系统代理，再打开fooocus才能使用

**Comment by Macroeye** [comment]
> 很明确用clash启用了系统代理，此时打开fooocus点击生成就会报错 这时即使关闭系统代理，再点击生成还是会报错 只有关闭系统代理并且关闭fooocus重新打开才会不报错 尝试在run.bat加入--no-gradio-queue，提示不支持这个参数 所以目前没有解决方案，只能关闭clash，至少是关闭系统代理，再打开fooocus才能使用


I also have this problem, it only works if I manage the crash agent and restart the UI。Adding “--no-gradio-queue” to “webui-user.bat” cannot solve this problem。@lllyasviel
