### ISSUE TITLE
Will SD Cascade be supported in the future？

### ISSUE THREAD

**Issue by Zxilly** [lllyasviel/Fooocus#2333]
**Is your feature request related to a problem? Please describe.**
Just days before stable diffusion release their new model cascade. https://github.com/Stability-AI/StableCascade

**Describe the idea you'd like**
I'm wondering if possible for this project to support it.

**Comment by mashb1t** [comment]
see https://github.com/lllyasviel/Fooocus/discussions/2249#discussioncomment-8467819, closing this issue in favor for the discussion / idea.
Answer is a definitive "maybe" 😬 (needs time to implement, which i personally don't have)
