### ISSUE TITLE
Moving model to GPU

### ISSUE THREAD

**Issue by turkiet** [lllyasviel/Fooocus#2335]
I installed Fooocus for AMD via Anaconda without any problems and completely. When I try to produce a photo, it gets stuck on "Moving model to GPU".

In the cmd screen
"Requested to load SDXL
Loading 1 new model"

I have an RX 6600 graphic card and 16GB of ram. Fooocus installed on a 1TB SSD.

**Comment by mashb1t** [comment]
Please make sure your swap is set up correctly (check the troubleshooting guide) and is using the SSD instead of any other drive on your PC.
RX 6600 has 8GB VRAM, which is on the edge, but should be able to run Fooocus.

**Comment by mashb1t** [comment]
@turkiet were you able to check the swap location?

**Comment by mashb1t** [comment]
Closing as stale
