### ISSUE TITLE
Possibility of producing an image while retaining the identity of a person (InstanID)

### ISSUE THREAD

**Issue by droseraph** [lllyasviel/Fooocus#2339]
Hello, I love using InstantID locally on my PC. But we are quickly limited by the basic functionalities.

InstantID allows with a single photo + a position photo (optional) to produce an image of a person while retaining their identity.

It's amazing and gives better results than with a LORA.

It would be good to include it in Fooocus, we would have the choice of styles and the ease of changing SDXL models easily.

I had the opportunity to modify the InstantID style file to have predefined prompts and it worked.

https://github.com/InstantID/InstantID

**Comment by barepixels** [comment]
see https://github.com/machineminded/Fooocus-inswapper/issues/15

**Comment by mashb1t** [comment]
@droseraph thank you for your interest, this is already a feature in the backlog. Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/2025
