### ISSUE TITLE
I have some problems ，I need some help please. Error Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by luv1145** [lllyasviel/Fooocus#234]
When I use [Fooocus](https://github.com/lllyasviel/Fooocus), It tells me:Error
Expecting value: line 1 column 1 (char 0),
so what can I do ,How can I solve these problems.
[erro.txt](https://github.com/lllyasviel/Fooocus/files/12404507/erro.txt)
![屏幕截图 2023-08-22 115014](https://github.com/lllyasviel/Fooocus/assets/137468065/4ce07312-551e-4a9c-97f8-5d8ff42f863f)

**Comment by zenlinuxs** [comment]
me to ,how help me

**Comment by luv1145** [comment]
this problem doesn't come up often，Now I can use Fooocus, It's nice and useful

**Comment by luv1145** [comment]
> 我要，如何帮助我

this problem doesn't come up often，Now I can use Fooocus, It's nice and useful

**Comment by im6chen** [comment]
same problem

**Comment by im6chen** [comment]
After shutting down the VPN, it returns to normal

**Comment by hylarucoder** [comment]
turn off your vpn global mode
