### ISSUE TITLE
Same seed, different results on different GPUS

### ISSUE THREAD

**Issue by jetjodh** [lllyasviel/Fooocus#2345]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
I ran a generation on foocus on two different GPUs with same seeds and exact same parameters, and got different results. Is there any way to get fooocus to give same results with same seeds across multiple platforms?

**Comment by poor7** [comment]
I think the results will be the same only if the GPUs are the same. Otherwise, they will be at least slightly different, because... The initial noise may be generated differently on different GPUs.

**Comment by mashb1t** [comment]
I see that results are resembling another but still different. What boggles me is that noise is generated from CPU, see https://github.com/lllyasviel/Fooocus/blob/main/ldm_patched/modules/sample.py#L9-L26...

**Comment by mashb1t** [comment]
@jetjodh sorry, took me 10 minutes to figure this one out. Make sure you're using a non "...-gpu" sampler as well as not use prompt expansion (not select style Fooocus V2).

**Comment by jetjodh** [comment]
Thanks for the information, I'll be sure to do that!

**Comment by jetjodh** [comment]
@mashb1t I tried using euler_ancestral sampler and still got different results on different GPUs. I have no style selections, or loras, just the base sdxl model(sd_xl_base_1.0.safetensors).
Prompt in MJ style for easier readability:
 a red apple --seed:15 --sampler:euler_ancestral --size:1024x1024 --cfg-scale:6 --steps:25
 
![a red apple_backend_focus_ (1)](https://github.com/lllyasviel/Fooocus/assets/20591775/f0090243-d810-4676-9d73-832883faaaf1)
![a red apple_backend_focus_](https://github.com/lllyasviel/Fooocus/assets/20591775/30cf5c90-58de-43f6-a172-8396eed8aa97)
