### ISSUE TITLE
cannot use the Mixing Image Prompt and Inpaint feature

### ISSUE THREAD

**Issue by KaYiu** [lllyasviel/Fooocus#2353]
![image](https://github.com/lllyasviel/Fooocus/assets/2405269/441f521c-520e-4b5c-b7e8-63dc64181960)
no extra input even if checked [Mixing Image Prompt and Inpaint]

**Comment by mashb1t** [comment]
There is no extra input element. You have to use the image prompt tab to upload image prompt reference images and it will apply both inpainting and image prompt tabs when generating images.
