### ISSUE TITLE
Load parameters from the clipboard does not reset unused LoRAs

### ISSUE THREAD

**Issue by GrAndAG** [lllyasviel/Fooocus#2354]
How to reproduce:

1. Generate an image using single LoRA.
2. Add a second (or more) LoRA.
3. Open History Log, find the image which was created with single LoRA. Click [Copy To Clipboard] for that image.
4. Paste the copied settings to the Prompt field and click [Load Parameters] button.
5. Discover that the LoRA 2 (and other if were set) are not reset to None, while parameters from the clipboard do not have it/them.

I expected the LoRAs list to match the parameters I imported.

**Comment by mashb1t** [comment]
solved in https://github.com/lllyasviel/Fooocus/pull/1940, stay tuned
