### ISSUE TITLE
Persistent download - automatic restart of partial downloads

### ISSUE THREAD

**Issue by Tenfilip** [lllyasviel/Fooocus#2356]
**Is your feature request related to a problem? Please describe.**
Downloads from huggingface typically finish not completed (e.g. stops at 7%, resulting in corrupted files). I have to download them through chrome, manually "restarting" them once or two so it completes, and put it manually to the right folder. I understand this is an issue with external provider, but...

**Describe the idea you'd like**
... I would like the downloader in Fooocus to be more persistent and restart "failed" download like I do in Chrome, until I get the whole model that is missing.

**Comment by eddyizm** [comment]
You really only have to download them once, then you are good. This feature feels like it is out of scope. I'd be more curious if your connection is unstable. Perhaps use another tool?

**Comment by mashb1t** [comment]
https://github.com/lllyasviel/Fooocus/blob/1c999be8c8134fe01a75723ea933858435856950/modules/model_loader.py#L25 
The library Fooocus uses to download files doesn't allow to resume downloads.

See https://pytorch.org/docs/stable/_modules/torch/hub.html#download_url_to_file

To allow this, it would require a substantial switch to a new library, which also doesn't guarantee that the server side supports the Range bytes HTTP header (see e.g. https://github.com/conda/conda/pull/13231/files#diff-cb41738bd5c97fa7459db5a5aca65808aed9a2b254a6564366feacabdc8f0d4fR94).

Closing this issue as won't fix.

**Comment by Tenfilip** [comment]
> You really only have to download them once, then you are good. This feature feels like it is out of scope. I'd be more curious if your connection is unstable. Perhaps use another tool?

Hey, got a symmetric 1 gbps on fiber, only hugging face is such a pain. Just downloaded 9GB from speedtest with no issues, also I just dont recall having issues with my provider.

Not sure what you mean by use another tool? Not fooocus? Or other for download? I just thought it would be worth to have this working for people who wont be able to read the "dos" box output. If this is just me, than I guess that's not worth for the project to care about this. 

Personally, I'm not impacted by the downloading (got a plugin in chrome to autoresume, also it's not long), but it get's me out of the flow. I also sometimes do fresh installs etc. so I assume this will happen again... OR I diagnose the connectivity issues I have with this specific site:)

Thank both for commenting:)

**Comment by eddyizm** [comment]
@Tenfilip Yes, sorry, I meant another tool for downloading. To your point though, sites like huggingface and civitia are probably struggling to serve so much data. Once I download a large file, I put it on my network and share it across devices if need be, as there have been days when they are down altogether. 

Definitely room for improvement but probably low on the scale of other cool things to do with Fooocus.
