### ISSUE TITLE
hi~ Small issue of style

### ISSUE THREAD

**Issue by madsteed** [lllyasviel/Fooocus#2357]
Incorrect "Blueprint Schematic Drawing" thumbnail in style

**Comment by madsteed** [comment]
<img width="895" alt="截屏2024-02-29 20 12 25" src="https://github.com/lllyasviel/Fooocus/assets/12323248/0f7688a5-21a8-4daf-ac64-2a8baacab97a">

Thumbnails look black and white

**Comment by madsteed** [comment]
When is SDXL lighting supported? Where to set 2-8 step sampling？

**Comment by mashb1t** [comment]
Please find the discussion here: https://github.com/lllyasviel/Fooocus/discussions/2318

**Comment by madsteed** [comment]
I read it. It is inconvenient to adjust, so it is recommended to switch to the front end. thx!
