### ISSUE TITLE
Resumable Downloads

### ISSUE THREAD

**Issue by moritz-t-w** [lllyasviel/Fooocus#2358]
**Is your feature request related to a problem? Please describe.**
I ran `entry_with_update.py` and it started downloading stuff. It got to 50%, on the default safetensors model then my pc crashed for unrelated reasons and after rebooting the download had to start over.

**Describe the idea you'd like**
Make the downloads resumable

**Comment by mashb1t** [comment]
See https://github.com/lllyasviel/Fooocus/issues/2356
