### ISSUE TITLE
RuntimeError: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

### ISSUE THREAD

**Issue by Haneesh000** [lllyasviel/Fooocus#2360]
**Read Troubleshoot**

[✅] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
I am using Windows OS with AMD GPU, I have 8GB Memory. I followed the [official installation guide](https://github.com/lllyasviel/Fooocus/tree/main?tab=readme-ov-file#windows-amd-gpus). However, there is an issue when I am trying to generate images. Since I have no experience in this I am unable to figure out what the issue is. Therefore, I followed the error message `RuntimeError: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.` and searched up in troubleshoot but didn't find anything there :(

**Full Console Log**
File was too lengthy 😅😅 so pasted it in [here](https://github.com/Haneesh000/AI-Errors/blob/master/Fooocus%20Error.txt).

**Comment by Haneesh000** [comment]
![image](https://github.com/lllyasviel/Fooocus/assets/92240889/43387c69-4171-4fef-b521-590c6e238134)
I don't have TdrDelay key in the first place @mashb1t

**Comment by Haneesh000** [comment]
like this?
Let me try once.
![image](https://github.com/lllyasviel/Fooocus/assets/92240889/50f59c71-896c-464f-a548-f9f86bfe504b)

**Comment by Haneesh000** [comment]
Hmm. It works. However, a new error that says `RuntimeError: Not enough memory resources are available to complete this operation.` What does it mean?? My PC has the minimal requirements mentioned. Full Log [here](https://github.com/Haneesh000/AI-Errors/blob/master/Fooocus%20Error%202)

**Comment by mashb1t** [comment]
@Haneesh000 glad it fixes the initial issue. Please check task manager if RAM or VRAM is now not sufficient, i assume in your specific combination one is lacking capacity. Also ensure that you've set up swap according to the troubleshooting guide.

**Comment by Haneesh000** [comment]
How much is the VRAM requirement? I have 0.5 GB VRAM as I can see here
![image](https://github.com/lllyasviel/Fooocus/assets/92240889/bf1d6490-bc88-401d-a1c0-ceb138884aa7)

**Comment by Haneesh000** [comment]
Hey my GPU has 4 GB only. Does it mean I can't use Fooocus 😭😭??

**Comment by Haneesh000** [comment]
@mashb1t Can't I use Fooocus? In any way possible?

**Comment by mashb1t** [comment]
> Hey my GPU has 4 GB only. Does it mean I can't use Fooocus 😭😭??

Sadly not as you're not meeting minimal system requirements (8GB VRAM for AMD GPUs)

**Comment by Haneesh000** [comment]
So, there's literally no chance unless I upgrade my GPU??

**Comment by Haneesh000** [comment]
How do I use this mode?
![image](https://github.com/lllyasviel/Fooocus/assets/92240889/a1f1112f-9614-41fb-ad5c-bc954d1fc475)

**Comment by mashb1t** [comment]
Again, there is not, you're not meeting minimal system requirements.
Closing this issue.

**Comment by Haneesh000** [comment]
@mashb1t Can you suggest some alternatives since I can't run Fooocus? I won't disturb you again. But, please.....

**Comment by mashb1t** [comment]
There are none, at least not SDXL based ones. Please check out A1111 / ComfyUI for the usage with SD1.5 models.
