### ISSUE TITLE
Same seed, different results on different GPUS, part 2

### ISSUE THREAD

**Issue by jetjodh** [lllyasviel/Fooocus#2361]
_@jetjodh sorry, took me 10 minutes to figure this one out. Make sure you're using a non "...-gpu" sampler as well as not use prompt expansion (not select style Fooocus V2)._

_Originally posted by @mashb1t in https://github.com/lllyasviel/Fooocus/issues/2345#issuecomment-1962304127_

@mashb1t
I tried the solution posted in the previous issue but it did not work.

**Comment by jetjodh** [comment]
@mashb1t I tried using euler_ancestral sampler and still got different results on different GPUs. I have no style selections, or loras, just the base sdxl model(sd_xl_base_1.0.safetensors).
Prompt in MJ style for easier readability:
 a red apple --seed:15 --sampler:euler_ancestral --size:1024x1024 --cfg-scale:6 --steps:25
 
![a red apple_backend_focus_ (1)](https://github.com/lllyasviel/Fooocus/assets/20591775/f0090243-d810-4676-9d73-832883faaaf1)
![a red apple_backend_focus_](https://github.com/lllyasviel/Fooocus/assets/20591775/30cf5c90-58de-43f6-a172-8396eed8aa97)

**Comment by mashb1t** [comment]
After debugging again, this time without time pressure, I am still able to reproduce the exact same images on different systems with very minor and not noticable changes in composition.
The issue you're experiencing might have to do with the attention selection, which pytorch 2.x does automatically do for you depending on your systems capabilities.
Please check if setting `--attention-split`,  `--attention-quad` or  `--attention-pytorch` helps with reproducibility.

**Comment by mashb1t** [comment]
comparison (please find the prompts in the image metadata, readable/applicable using the latest 2.2.0-rc1 version, image prompt => metadata):

<details><summary>Apples</summary>
<p>

RTX 3080
![3080-apple](https://github.com/lllyasviel/Fooocus/assets/9307310/365779b3-ac4d-40f3-909d-c017e1538204)

RTX 4090
![4090-apple](https://github.com/lllyasviel/Fooocus/assets/9307310/1c887c79-2343-4961-88a0-a0e5520690e8)

Macbook M1
![macos-apple](https://github.com/lllyasviel/Fooocus/assets/9307310/be6209ad-5423-412e-8456-75bf8c8cd96c)

</p>
</details> 

<details><summary>man in a bar</summary>
<p>

RTX 3080
![3080-man](https://github.com/lllyasviel/Fooocus/assets/9307310/ffbf0292-8c1b-4534-bade-e1f4bdbbb238)

RTX 4090
![4090-man](https://github.com/lllyasviel/Fooocus/assets/9307310/efef4ba4-33a9-48f2-bcf3-418901aa0460)

Macbook M1
![macos-man](https://github.com/lllyasviel/Fooocus/assets/9307310/23a6ef8c-9825-465a-9262-10ca3a1fba62)

</p>
</details>

**Comment by jetjodh** [comment]
I'll check with these settings.

**Comment by jetjodh** [comment]
Dockerfile runtime:
`nvidia/cuda:12.1.0-runtime-ubuntu22.04`
My old torch and xformers versions:
```
torch==2.1.2 --index-url https://download.pytorch.org/whl/cu121
torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu121
xformers==0.0.23.post1 --index-url https://download.pytorch.org/whl/cu121
```
My new torch and xformers versions:
```
torch==2.2.0 --index-url https://download.pytorch.org/whl/cu121
torchvision==0.17.0 --index-url https://download.pytorch.org/whl/cu121
xformers==0.0.24 --index-url https://download.pytorch.org/whl/cu121

```
Startup args:
```
-sync-repo skip --skip-pip --preload-pipeline --all-in-fp16 --always-high-vram  --disable-server-log --queue-size 100 --always-offload-from-vram --attention-pytorch
```
![diff](https://github.com/lllyasviel/Fooocus/assets/20591775/7668721e-11e2-4fda-8795-12c677627835)
with attention-pytorch i was able to get get diff to about 5% from 88.75%

**Comment by mashb1t** [comment]
@jetjodh of course results will be different when using different package versions. Please keep them in sync when comparing systems.
Can this issue be closed?

**Comment by jetjodh** [comment]
@mashb1t My bad.
I tried with comparing the images in my old and new setups separately, still got the issue.
I am using L4 and A30 gpus for comparing these.
Exact prompt:
```
{
      "prompt": "a red apple",
      "performance_selection": "Speed",
      "sharpness": 0,
      "refiner_model_name": "None",
      "advanced_params": {
        "scheduler_name": "karras",
        "overwrite_width": 1024,
        "overwrite_height": 1024,
        "overwrite_step": 25,
        "sampler_name": "euler_ancestral"
      },
      "style_selections": [],
      "image_seed": 15,
      "image_number": 1,
      "guidance_scale": 6,
      "base_model_name": "sd_xl_base_1.0.safetensors",
      "refiner_switch": 1,
      "negative_prompt": ""
  }
```
