### ISSUE TITLE
DefaultCPUAllocator: not enough memory: you tried to allocate 26214400 bytes.

### ISSUE THREAD

**Issue by iwantobreathe** [lllyasviel/Fooocus#237]
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 26214400 bytes. form the run.bat

Can somebody help me how to fix . My laptop is RTX3060 + AMD cpu

**Comment by ProgramSalamander** [comment]
I solved this by adding more virtual memory on Windows 10. Just following instructions on Google.

**Comment by iwantobreathe** [comment]
> I solved this by adding more virtual memory on Windows 10. Just following instructions on Google.

thanks.
