### ISSUE TITLE
model / LoRA dropdown bug on initial start

### ISSUE THREAD

**Issue by mashb1t** [lllyasviel/Fooocus#2372]
I maybe found a bug with the LoRA dropdowns:

I'm running in a Google Colab machine with the following code:
```!pip install pygit2==1.12.2
!rm -rf /content/Fooocus
%cd /content
!git clone -b develop https://github.com/lllyasviel/Fooocus.git
%cd /content/Fooocus
!python entry_with_update.py --share --always-high-vram --all-in-fp16
```

Then click Advanced - Model and open the LoRA 1 dropdown with the sd_xl_offset_example-lora_1:
![image](https://github.com/lllyasviel/Fooocus/assets/155714366/536efde8-de60-44b0-af55-5cdd833f2a18)

The dropdown itself only contains a 'None' value and after choosing 'None' and opening the dropdown again, the sd_xl_offset_example-lora_1 is gone forever:
![image](https://github.com/lllyasviel/Fooocus/assets/155714366/3b10d9bc-9573-4891-91e1-b5e3848dcd0b)

It works again after clicking 'Refresh all files'.

_Originally posted by @f0n51 in https://github.com/lllyasviel/Fooocus/discussions/2362#discussioncomment-8602289_

**Comment by mashb1t** [comment]
> This is i think a general issue already present in the main branch. Please double-check it there
We might have to add an initial reload after lora/model download and first "cold boot"

https://github.com/lllyasviel/Fooocus/discussions/2362#discussioncomment-8604253

**Comment by f0n51** [comment]
I can confirm now, that this is a bug in the main branch too :-)

**Comment by mashb1t** [comment]
resolved, took a while to get to the topic again but it works now
