### ISSUE TITLE
Adding custom settings preset

### ISSUE THREAD

**Issue by IamTirion** [lllyasviel/Fooocus#2373]
**Is your feature request related to a problem? Please describe.**
There are currently 3 preset settings available in Fooocus: Speed, Extreme Speed, Quality. These settings are not preferable to be used with Turbo or Lightning, because even the Extreme Speed setting uses too many steps or CFG than what the Turbo or Lightning models recommend. We can overwrite these settings in the Advanced options, but it's repetitive to do it every time you open Fooocus.

**Describe the idea you'd like**
Can we have the ability to add custom settings preset, specifically on the number of steps used, CFG, and the sampler?

**Comment by midareashi** [comment]
All those options are available to set in your preset. Check out config_modification_tutorial.txt for the complete list.

"default_cfg_scale": 3.0,
"default_sampler": "dpmpp_2m_sde_gpu",
"default_overwrite_step": 1,

**Comment by IamTirion** [comment]
> All those options are available to set in your preset. Check out config_modification_tutorial.txt for the complete list.
> 
> ```
> "default_cfg_scale": 3.0,
> "default_sampler": "dpmpp_2m_sde_gpu",
> "default_overwrite_step": 1,
> ```
There are times when I want to switch between different presets, such as when I am using a different checkpoint, or inpainting. If I change the default settings in config.txt, I can't go back to the custom preset after switching to another preset.

**Comment by midareashi** [comment]
You don't want to update config.txt, you want to create new presets for your different workflows. Create a new preset for turbo, set `"default_overwrite_step": 1` and whatever other options you want by default. Then create a new turbo.bat file and load the turbo preset

```
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset turbo
pause
```

You can make a preset for Turbo, Inpaint, or whatever you want. You can have more than one instance of fooocus running with different presets, they use different ports on localhost.

**Comment by IamTirion** [comment]
> You don't want to update config.txt, you want to create new presets for your different workflows. Create a new preset for turbo, set `"default_overwrite_step": 1` and whatever other options you want by default. Then create a new turbo.bat file and load the turbo preset
> 
> ```
> .\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset turbo
> pause
> ```
> 
> You can make a preset for Turbo, Inpaint, or whatever you want. You can have more than one instance of fooocus running with different presets, they use different ports on localhost.

Sorry I am really bad at technical stuff. Can you give me more detailed instructions? How do I make a new preset? And how do I make a new .bat file? And assuming I have done everything correctly, I will end up with something like the run_anime or run_realistic batch files, right?

**Comment by midareashi** [comment]
There is a presets folder inside fooocus that contains all the settings that load when you launch fooocus. The different .bat files just apply those preset configurations on launch (and if you reload your browser window). You can create a new preset config (use one of the existing ones as an example) and add any settings you find in config_modification_tutorial.txt.

You can create a new .bat file using notepad

```
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset turbo
pause
```

Save that as run_turbo.bat and you should be good to go.

**Comment by IamTirion** [comment]
> There is a presets folder inside fooocus that contains all the settings that load when you launch fooocus. The different .bat files just apply those preset configurations on launch (and if you reload your browser window). You can create a new preset config (use one of the existing ones as an example) and add any settings you find in config_modification_tutorial.txt.
> 
> You can create a new .bat file using notepad
> 
> ```
> .\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset turbo
> pause
> ```
> 
> Save that as run_turbo.bat and you should be good to go.

Alright I'll give it a try. Thank you.

**Comment by mashb1t** [comment]
Closing as answered, thanks @midareashi
