### ISSUE TITLE
URGENT

### ISSUE THREAD

**Issue by Khaos1221** [lllyasviel/Fooocus#2374]
I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

Guys my browser said COnnnection timed out and I refreshed  I know the CLI is still working , Now I have lost the webpage of the prompt, Can Someone please share How to bring it back?? I dont want to build a complete image as My pc is not able to handle the requests pretty well

OR is there any way of looking for current Iteration?

Edit 
My prompt is still on work but the prompt page has been lost , I cant afford to COmplete the whole picture SO can I look at the iterations?
Also is it possible to download the current generated image without the webui from Cache or something?

**Comment by cparello** [comment]
you prob just need to restart it
