### ISSUE TITLE
The Image Preview window is much slower than image generation

### ISSUE THREAD

**Issue by midareashi** [lllyasviel/Fooocus#2377]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
When doing large batches of images the batch will finish way ahead of the preview window. For example a 32 image batch will be done and the preview window could still be showing image 20. Skip and Stop don't work because there are no items in the task to skip. You are locked out of doing new generations until you either wait for the preview to catch up, or you open a new browser tab to run localhost. Refreshing the current page doesn't work.

**Comment by mashb1t** [comment]
Already fixed in https://github.com/lllyasviel/Fooocus/pull/1013, please check out the current develop branch and release 2.2.0-rc1.
