### ISSUE TITLE
Windows installer throwing up python error

### ISSUE THREAD

**Issue by Sierbahnn** [lllyasviel/Fooocus#2389]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
I have downloaded and extracted the package to install Foocus on windows 10.
The first time I run run.bat it claims that there is no such file, but when I run it as an admin I can get a bit further, but not a lot, as it immediately throws up an error

![image](https://github.com/lllyasviel/Fooocus/assets/68108749/ecc419f6-df3b-494f-930a-1d898911536b)

I don't have the files in the system32 folder, so I am not sure why it is looking there.
How can I resolve this?

**Comment by Sierbahnn** [comment]
I also tried editing the run-bat to reflect the file where the python-embeded is located, but that just tells me that the folder is not recognized as an internal or external command, operable program or batch file, which is fair, but the file is IN there.

**Comment by Sierbahnn** [comment]
Trying to run python through the CMD can get it to run, but then throws this error
![image](https://github.com/lllyasviel/Fooocus/assets/68108749/de64b713-eac9-4af8-824e-f4ac6d9606db)

**Comment by Sierbahnn** [comment]
I installed Python from the microsoft app store to try to run the entry_with_update.py but all it does it flicker open and then closes. It does not appear to execute it at all.
This is deeply frustrating, and I feel there is something simple I am missing.

**Comment by Sierbahnn** [comment]
Well, a little at a time I guess
I ran python from the cmd and got this error instead

![image](https://github.com/lllyasviel/Fooocus/assets/68108749/e13ff708-9a39-4b76-a9b1-651e16e362df)

Seems the installer, even when I get it to run the command it is supposed to, which it does not out of the box, cannot execute the command.

**Comment by Sierbahnn** [comment]
1. Then how do I execute the command? If I just run the run-bat I get an error
![image](https://github.com/lllyasviel/Fooocus/assets/68108749/de1f6fa7-ddcc-4884-8bd5-c93bd4e0c957)

2. Sure, but that only results in the error above.
3. I think you mean "assure", and obviously there is an error somewhere, as the module is not found.
4. And when I do I get the error above.

Let's start with one of these then - the run.bat - if it gives the error I posted above, so how do I get passed that? I am guessing running it as admin is not a great idea, since that just throws up the initial error.

**Comment by mashb1t** [comment]
Please make sure that the file is still named `run.bat` and not `run-bat`, then execute it.
As far as i could see you've actually never executed the embedded python / run.bat with the correct command in non-elevated admin mode.

- https://github.com/lllyasviel/Fooocus/issues/2389#issue-2161152517 => run.bat executed as admin, directory changed
- https://github.com/lllyasviel/Fooocus/issues/2389#issuecomment-1971047976 `run-bat` => maybe you've accidentally renamed it?
- https://github.com/lllyasviel/Fooocus/issues/2389#issuecomment-1971076153 running python.exe and then adding flags is not possible AFAIK
- https://github.com/lllyasviel/Fooocus/issues/2389#issuecomment-1971089509 python.exe of your system was used, not the embedded python.exe, which is also why there are no packages installed. You'll be able to run Fooocus this way though when installing the package on a system wide level, but this might not be what you're intending to do.

The solution is to run Fooocus with the embedded python.exe by either executing the run.bat after ensuring that the file has not accidentally been renamed or the command `.\python_embeded\python.exe -s Fooocus\entry_with_update.py` from a CMD terminal in `D:\Program Files (x86)\Foocus`, which will find the already installed packages in the embedded.

Hope this analysis helps in putting the previous steps of yours in context as well as in finding the correct entrypoint!

**Comment by Sierbahnn** [comment]
The error 
![image](https://github.com/lllyasviel/Fooocus/assets/68108749/8f561b15-7e1a-4f78-ae5d-2728864f091e)
appears when I run the 
![image](https://github.com/lllyasviel/Fooocus/assets/68108749/61ef9e28-e308-4b74-9cd7-49c1b180e037)

I had no idea what elevated CMD vs non-elevated CMD even was four hours ago, so I am happy I was told that one of them could cause an issue. :) I think I managed to run a non-elevated CMD and after some tinkering (seems the zip didn't unpack everything the first go, so I had to go in and do it again for some folders) the prompt is now running and it seems to be downloading the juggernautXL.

It would have been nice if the run.bat had done this from the jump. Any idea why it didn't?
Does it expect to be in the appdata or somewhere else in particular, and has issues "finding itself" when it is not?

**Comment by mashb1t** [comment]
@Sierbahnn sorry for the initial confusion, the zip hasn't been changed in 2 months and normally works fine, some users only had problems when extracting it but the structure is proven to be working. The run.bat also correctly works when everything has been extracted as it just calls a command... Maybe this is because of spaces in the name or something else on your system, can't tell.
Glad you figured out the solution, closing this issue now!
