### ISSUE TITLE
An error occurred when running fooocus in the proxy server

### ISSUE THREAD

**Issue by aris1211** [lllyasviel/Fooocus#2394]
**Describe the problem**
An error occurred when running fooocus in the proxy server, I real sure that is Gradio problem. but SD Webui can be solved through the --no-gradio-queue parameter. Can Fooocus modify and add this parameter?

At present, the proxy server must be temporarily turned off and the proxy server cannot be used until the system is turned on.

**Full Console Log**
.
.
.
File "D:\Desktop\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\gradio\blocks.py", line 1913, in launch
raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
Please press any key to continue. . . .

**Comment by mashb1t** [comment]
There is no such option in Fooocus to disable the queue with an argument.
You can turn off the queue by modifying the code and removing `.queue()` in https://github.com/lllyasviel/Fooocus/blob/main/webui.py#L88, but i've personally never tested Fooocus without a queue.
If you want to use WebSocket connections for real-time progress trakcking, make sure to enable connection upgrading in the proxy.
Nginx example: https://nginx.org/en/docs/http/websocket.html

Please keep in mind that issues in this repository are for Fooocus only and the team does not offer proxy support other than hinting to possible solutions. Nevertheless you can open a discussion in the [Q&A category](https://github.com/lllyasviel/Fooocus/discussions/new?category=q-a) to discuss with the community.
