### ISSUE TITLE
[Feature Request] Batch Upscale Images

### ISSUE THREAD

**Issue by deadpipe** [lllyasviel/Fooocus#2396]
**Is your feature request related to a problem? Please describe.**
When there are lots of images to upscale, it is inconvenient to do one by one. 

**Describe the idea you'd like**
It would be better if there is an option to select a folder/multiple images at once and then upscale all of them in a batch process. 

Thank You

**Comment by mashb1t** [comment]
@deadpipe thank you for raising the issue, but the same idea already exists in https://github.com/lllyasviel/Fooocus/issues/1236.
Closing as duplicate.
