### ISSUE TITLE
Style gallery

### ISSUE THREAD

**Issue by Sierbahnn** [lllyasviel/Fooocus#2402]
**Is your feature request related to a problem? Please describe.**
No, everything is fine.

**Describe the idea you'd like**
I love the versatility of styles offered by Fooocus, but I would love for there to be more, or possibly a centralized LoRa repository where I could get others. I am looking for several specific ones which don't appear to exist in the current set.

**Comment by eddyizm** [comment]
I don't believe Styles are LoRAs, they are just prompt enhancements. Something that is more familiar with correct, probably @mashb1t :-)

You can get any SDXL lora from civitia.com though, I use plenty of them to great effect.

**Comment by Sierbahnn** [comment]
To me, a layman, it does not really matter what styles and LoRas are, just how they enhance the image. 
If it would be possible to poll civitai.com for more styles, LoRas, models, whatever, that might be good.
I think that is what I was trying to say. :)

**Comment by mashb1t** [comment]
You can think about the different types like this:
- a model is like a vehicle, which can be fundamentally different, e.g. a car/plane/ship.
- a LoRA is the pilot or driver, steering the model into a specific direction, but can't change the nature of the vehicle.
- a style has the least impact, defining the color of the vehicle. Styles are keywords added to the prompt and can be modified in the sdxl_styles folder.

Plus there are hypernetworks and embeddings, but they're not really inportant in this scenario at all.

Models and LoRAs can be downloaded from e.g. https://civitai.com or https://huggingface.co + you have to put them into their corresponding folder in models > checkpoints or loras. They have to be based on SDXL 1.0 to use them in Fooocus as SD1.5 models are supported only for usage as refiner. Keep in mind to either restart Fooocus afterwards or press the "reload all models" button in advanced > models.

Hope this helps in understanding the difference.
