### ISSUE TITLE
png without info

### ISSUE THREAD

**Issue by jasoncow007** [lllyasviel/Fooocus#241]
if I want to recreate a image base on a generated one, cannot find back the seed or other info anymore

**Comment by jasoncow007** [comment]
got it! fooocus is 小而美，I'm wondering if controlnet will be added, it would be 小而精

**Comment by nzkritik** [comment]
Will embedding the metadata (prompt, seed etc) into the png files be added at some stage? or is there a setting or flag I have missed that enables this? 
Great project, awesome UI and ease of setup and use.
thank you

**Comment by VictorZakharov** [comment]
UI or server side config override (or cmd line arg) should have an option to include metadata. I understand privacy and all, but right now I cannot share my gens on civit, because it cannot link to the model I'm using to generate. And it cannot extract tags, which is why publish button is disabled.

**Comment by mashb1t** [comment]
> Fooocus is committed to protect user privacy and will never write any hidden data in your generated images.

https://github.com/lllyasviel/Fooocus/discussions/160
This is our commitment. Feel free to use the history log for image generation parameter reference or https://github.com/MoonRide303/Fooocus-MRE (it is not maintained anymore AFAIK)

**Comment by VictorZakharov** [comment]
@mashb1t You don't have to break your commitment to implement this feature. Just add a right click option, special button that appears on hover etc, that would let user literally "copy with embedded metadata" (reading from log.html). So they will have to explicitly click it and it would only save for that image.

The unfortunate downside - it won't work with images that were previously generated. But the UI could have a place/tab/button to perform this action on any image from previous gens.

**Comment by mashb1t** [comment]
Gradio reading from log.html would lead to a break in user isolation when used by multiple users in parallel. Some people also have `--disable-image-log` set, which would not allow reading from the file. In general, reading from an html file just doesn't feel right and is finicky at best.

There are actually already 2 gallery projects, which may fulfill your needs:
- https://github.com/sngazm/fooocus-viewer 
- https://github.com/toutjavascript/Fooocus-Log-Viewer

> use this version for metadata embed in PNG https://github.com/MoonRide303/Fooocus-MRE

@barepixels already pointed out that Fooocus-MRE supports png meta data handling, so feel free to use MRE instead.

**Comment by VictorZakharov** [comment]
@mashb1t I don't have multiple users, only me. The easiest impl is to just drag and drop log and images, and download all images with metadata as zip in return. No permission issues.

MRE is not updated anymore, last update was 4 months ago. I don't want to use a stale version of the software, for the sake of having 1 simple feature.

The 2 gallery projects you mentioned cannot embed the metadata, to enable publishing on civit, which does not accept it otherwise (it does, but it ends up in limbo where no-one will see it, so you get 0 reactions, as if you never posted it).

**Comment by angelopouloschristos** [comment]
> @mashb1t I don't have multiple users, only me. The easiest impl is to just drag and drop log and images, and download all images with metadata as zip in return. No permission issues.
> 
> MRE is not updated anymore, last update was 4 months ago. I don't want to use a stale version of the software, for the sake of having 1 simple feature.
> 
> The 2 gallery projects you mentioned cannot embed the metadata, to enable publishing on civit, which does not accept it otherwise (it does, but it ends up in limbo where no-one will see it, so you get 0 reactions, as if you never posted it).
> 
> I'm not sure when devs will hear this point, that the problem is not metadata by itself, it's publishing fooocus gens to civit, which is currently blocked. There is no way for non-python-gurus to do it by themselves. So you end up not sharing work, motivation is reduced and you quit using fooocus or any Stable Diffusion. Which is what happened in my case.

10000000000000000000000000% AGREE.
I CAN'T UNDERSTAND why there is no button to allow users to have meta data INSIDE their images. Ofc everyone is leaving to other plateforms, sure it's harder but omg, it's full freedom.
What the hell are you trying to create ? A easy tool without freedom ? Make it atleast an option available for dev's in the advance tab ...
I'm sad that some GOOD products are destroyed by people who think it's better to reduce freedom. 
Read the heuristics of Jacob Nielson about UI/UX from 1980 !!!!!

**Comment by mashb1t** [comment]
@VictorZakharov @angelopouloschristos thank you for your opinions, much appreciated.
@angelopouloschristos i can understand that you're emotional, but please keep it to a level where your feedback stays constructive.

> #160 This is our commitment.

The Fooocus core dev team will return in mid/end of January and evaluate next steps (see https://github.com/lllyasviel/Fooocus/blob/main/update_log.md). Please stay tuned.

**Comment by angelopouloschristos** [comment]
> @VictorZakharov @angelopouloschristos thank you for your opinions, much appreciated. @angelopouloschristos i can understand that you're emotional, but please keep it to a level where your feedback stays constructive.
> 
> > #160 This is our commitment.
> 
> The Fooocus core dev team will return in mid/end of January and evaluate next steps (see https://github.com/lllyasviel/Fooocus/blob/main/update_log.md). Please stay tuned.

Sorry if my feedback was aggressive, this was not the goal of the message. I'm just disappointed to see such easy tools for beginners that restrict advanced users so much.

To be more constructive, the workflow of development in this project should add beginner-friendly options for beginners without restricting the freedom of advanced users. This is the way technology evolves much faster. We are talking about basic options such as having the choice to get the metadata in the PNG or the choice of steps, etc.

**Comment by mashb1t** [comment]
Fooocus already offers the overriding of steps in the advanced > developer debug mode tab, and while i respect your opinion and also think more freedom for the user is great to have, the guidelines are (for now) in place and might be reconsidered in the future. Again, thank you for the insights. A diverse set of opinions can be beneficial for a community and an open source project, at least to a point where a common consensus can be established.

**Comment by mashb1t** [comment]
Hey folks, i've implemented meta data handling in https://github.com/lllyasviel/Fooocus/pull/1940. This PR will most likely not be merged, so feel free to either apply the changes locally or switch to my fork https://github.com/mashb1t/Fooocus
