### ISSUE TITLE
[Bug]: Destroy picture with upscale 2x

### ISSUE THREAD

**Issue by Cil20KLV** [lllyasviel/Fooocus#2441]
### Checklist

- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Why upscale 2x destroy picture ?

look at his ear

![2024-03-04_14-09-50_7863](https://github.com/lllyasviel/Fooocus/assets/155557968/27997d5e-54e2-4bc2-825c-41eb5317e125)

after upscale 2x
![2024-03-04_14-11-40_6996](https://github.com/lllyasviel/Fooocus/assets/155557968/7fe1a940-31e3-425a-9a36-dde9167c3f2c)

### Steps to reproduce the problem

upscale 2x

### What should have happened?

perfect picture

### What browsers do you use to access Fooocus?

Microsoft Edge

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
-
```

**Comment by mashb1t** [comment]
The nature of upscaling is to improve details. Fooocus upscaling is comparable to hires fix / img2img with double the size of the original canvas.

1. latent upscale
2. regenerate the image using SDXL (currently selected model)

If you want no/minimal changes in your image you can also just use Upscale Fast 2x.

Long story short: This is intended. Hive it a second or even a third shot and you may get better results.
