### ISSUE TITLE
[Bug]: the .bat file does not execute

### ISSUE THREAD

**Issue by kinower** [lllyasviel/Fooocus#2442]
### Checklist

- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

the .bat file does not execute, I press but the command console does not open.

### Steps to reproduce the problem

I click on run.bat, run_anime.bat and run_realistic.bat and none of them open.

### What should have happened?

I don't have the solution

### Where are you running Fooocus?

None

### Console logs

```Shell
I have no records because the console does not open
```

**Comment by mashb1t** [comment]
Seems like either your security policy or employer doesn't allow execution of bat files or a firewall blocks you from doing so.


If you can't run any bat files (create one by renaming a text file), then i can assure you this is not an issue of Fooocus, but your local system. Please follow the article https://learn.microsoft.com/en-us/answers/questions/1290862/bat-file-is-not-working-from-a-pc to ensure you can run bat files.

Happy to hear your feedback afterwards.

**Comment by kinower** [comment]
I have stable-diffusion-webui installed and it works perfectly running webui-user.bat

**Comment by mashb1t** [comment]
Please check your folder/file permissions to find that something which prevents you from opening the file.
You can also copy its contents and run the command directly on CMD/Powershell in the same folder it currently is located in.

**Comment by kinower** [comment]
the option to open the command console seems to have worked fine.
