### ISSUE TITLE
[Bug]: Error when reproducing image metadata with non-standard resolution (1920x1080).

### ISSUE THREAD

**Issue by poor7** [lllyasviel/Fooocus#2446]
### Checklist

- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When trying to generate an image with imported metadata from a 1920x1080 image, an error appears in the console.

### Steps to reproduce the problem

1. Input Image - Metadata - Drag image 1920x1080
2. Apply Metadata
3. Generate image

### What should have happened?

Generate image

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### Console logs

```Shell
Traceback (most recent call last):
  File "/content/Fooocus/modules/async_worker.py", line 900, in worker
    handler(task)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/async_worker.py", line 389, in handler
    if overwrite_width > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
Total time: 0.02 seconds
```

### Additional information

If you manually move the Forced Overwrite of Generating Width and Forced Overwrite of Generating Height sliders, the error disappears.

**Comment by mashb1t** [comment]
@poor7 thank you for reporting, fixed in main!
