### ISSUE TITLE
Replace  extreme  speed with lightening and speed with turbo

### ISSUE THREAD

**Issue by saberzaid** [lllyasviel/Fooocus#2448]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Hello . Please replace the extream speed with lightening preset

And speed with turbo 

In short : change the names and update the preset 

So it will be : Quality  Turbo   Lightening 

### Proposed workflow

Preset names and setting updates

**Comment by mashb1t** [comment]
No, this will not be done. Turbo is not commercially usable without a subscription as discussed multiple times, and backwards compatibility isn't possible when removing Extreme Speed (LCM), so this is will be closed.
Lightning on the other hand is in evaluation, see PR https://github.com/lllyasviel/Fooocus/pull/2415
