### ISSUE TITLE
PNG with Transparency Alpha is not being saved. Only with checkerboard background

### ISSUE THREAD

**Issue by protector131090** [lllyasviel/Fooocus#2449]
### Checklist

- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

PNG with Transparency Alpha is not being saved. Only with checkerboard background. If i generate 1 image it wil save transparent PNG in TEMP folder but if a batch it dosnt... What do i do to make it save Transparency PNGS?

### Steps to reproduce the problem

PNG with Transparency Alpha is not being saved. Only with checkerboard background. If i generate 1 image it wil save transparent PNG in TEMP folder but if a batch it dosnt... What do i do to make it save Transparency PNGS?

### What should have happened?

PNG with Transparency Alpha is not being saved. Only with checkerboard background. If i generate 1 image it wil save transparent PNG in TEMP folder but if a batch it dosnt... What do i do to make it save Transparency PNGS?

### Where are you running Fooocus?

None

### Console logs

```Shell
[Memory Management] Current Free GPU Memory (MB) =  15766.0712890625
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  14742.0712890625
Moving model(s) has taken 0.00 seconds
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 10.83it/s]
[Layer Diffusion] LayerMethod.FG_ONLY_CONV
To load target model SDXL
Begin to load 1 model
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  19237.01318359375
[Memory Management] Model Memory (MB) =  3451.8823318481445
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  14761.130851745605
Moving model(s) has taken 0.90 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.97it/s]
To load target model AutoencoderKL███████████████████▊                             | 1590/3000 [05:38<03:23,  6.92it/s]
Begin to load 1 model
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  15765.81298828125
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  14741.81298828125
Moving model(s) has taken 0.01 seconds
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 10.76it/s]
[Layer Diffusion] LayerMethod.FG_ONLY_CONV
To load target model SDXL
Begin to load 1 model
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  19236.7548828125
[Memory Management] Model Memory (MB) =  3451.8823318481445
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  14760.872550964355
Moving model(s) has taken 0.93 seconds
 73%|████████████████████████████████████████████████████████████▏                     | 22/30 [00:03<00:01,  6.97it/s]
Total progress:  54%|█████████████████████████████████▎                            | 1612/3000 [05:44<03:21,  6.90it/s]
```

**Comment by mashb1t** [comment]
Image generation / modification with transparency isn't currently possible, Fooocus doesn't support alpha channel.
Please check https://github.com/lllyasviel/Fooocus/issues/2403 for image generation from scratch with transparency.
