### ISSUE TITLE
its always Processing text encoding ...

### ISSUE THREAD

**Issue by Twilightooo** [lllyasviel/Fooocus#245]
cmd tell me: RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from. 
But  my gpu is amd. 
when i click generate button ,there is always loading without any logs.
how to fix it

**Comment by dhs964057117** [comment]
> cmd tell me: RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from. But my gpu is amd. when i click generate button ,there is always loading without any logs. how to fix it

The author has explained that AMD type graphics are currently not supported

**Comment by Twilightooo** [comment]
thanks ,I ingore this messages

**Comment by dhs964057117** [comment]
and this issues，https://github.com/lllyasviel/Fooocus/issues/244#issue-1862451637，you has open the same issues twice

**Comment by dhs964057117** [comment]
and this issues，https://github.com/lllyasviel/Fooocus/issues/244#issue-1862451637, you has open the same issues twice
