### ISSUE TITLE
[Feature Request]: 16:9 Ratio 

### ISSUE THREAD

**Issue by PierrunoYT** [lllyasviel/Fooocus#2459]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

I would love to make 16:9 widescreen images

### Proposed workflow

Just like where the other ratios are

**Comment by widiot1** [comment]
Have a look at how to edit config.txt and add your own custom resolution in there

**Comment by mashb1t** [comment]
You can add this yourself in the aspect rations in config, but this is not officially supported. See https://github.com/lllyasviel/Fooocus/pull/1617 for more information.
