### ISSUE TITLE
 RuntimeError: CPUAllocator: not enough memory: you tried to allocate 6553600 bytes.

### ISSUE THREAD

**Issue by JohnTesla** [lllyasviel/Fooocus#247]
8GB VRAM GTX1070
Why I get this error?
Automatic can run and gen up to 2k image on my pc

**Comment by JohnTesla** [comment]
When I run SD it works with 8g Vram, if Fooocus caanot run on this configuration - this is application optimization bug

**Comment by MoonRide303** [comment]
@JohnTesla Did you read and applied instructions from @lllyasviel, available in Fooocus readme?
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/853db7c1-e181-47b2-a1c1-c86fc6e4feb6)
I would start with making sure you have it configured this way - it should help.

If it won't, you can check out my fork ([Fooocus-MRE](https://github.com/MoonRide303/Fooocus-MRE)) - I tested it on my kids PCs (16 GB RAM, 8 GB VRAM (3050)), and it worked just fine. It's pretty similar to original Fooocus in terms of memory requirements, but has a bit more recent comfy version, and updated Python env (made with current Anaconda) - maybe some of those changes would help a bit.

**Comment by JohnTesla** [comment]
Yes I've done, thanks for nice try -)
![done1](https://github.com/lllyasviel/Fooocus/assets/31341615/391847e9-52b5-4591-a831-64c26ba8741a)
![done2](https://github.com/lllyasviel/Fooocus/assets/31341615/4140494d-a66a-424d-a010-4b4424253368)

**Comment by JohnTesla** [comment]
When I start "Generate"
![done3](https://github.com/lllyasviel/Fooocus/assets/31341615/62330dd3-e19a-44cd-8360-31befb25ea79)
hangs like this for 1 minute
then the computer starts to freeze and the mouse freezes

**Comment by MoonRide303** [comment]
@JohnTesla You can try disabling Refiner - if you set it to "None" it won't be loaded into memory when you press Generate.

**Comment by JohnTesla** [comment]
I think this is bad idea. I tried SDXL in my Automatic1111 but caanot run because of memory. Size of model tensors is more than VRAM availible (thanks for stupped XL developers).
I hope that FOCUS can solve this probplem and rus SD using smaty optimization  - but this is lie!
Focus is same bug and cannot optimize memory for RUN SDXL

**Comment by MoonRide303** [comment]
@JohnTesla After disabling refiner I am able to run Fooocus-MRE relatively comfortably on lower-end machines (8 GB VRAM, 16 GB RAM - I tested on PCs of my kids) - it just takes a bit to generate image, but aside of that it works just fine. With refiner enabled it has to read more data and use swap memory more - quality gain vs performance drop is not worth it, then (IMO).

**Comment by JohnTesla** [comment]
ok thanks, disable refiner start generate
![image](https://github.com/lllyasviel/Fooocus/assets/31341615/6288a5ca-0090-491c-902b-3f20818c2bf5)
but slowly...about 10 min/pic
windows also stucks somebit gg)
Worked but I expected more
My case better to use online service for gen XL picture  -  5 seconds or less

**Comment by MoonRide303** [comment]
@JohnTesla You can try [Fooocus-MRE](https://github.com/MoonRide303/Fooocus-MRE) (release file: [Fooocus-MRE-v1.0.40.7z](https://github.com/MoonRide303/Fooocus-MRE/releases/download/v1.0.40/Fooocus-MRE-v1.0.40.7z)) - it's doesn't load refiner by default when starting, so it should launch and work faster on your PC (when you don't use refiner). You can also make it disabled by default, if you set it to "None" in settings.json file, like that:
```
{
    "refiner_model": "None"
}
```

@lllyasviel Please consider disabling loading refiner on startup in vanilla, too - not all people will need it, and it eats some RAM (I did it on me form in commit [f20465c](https://github.com/MoonRide303/Fooocus-MRE/commit/f20465cb44a8c12566864dfea05dbba0198a994d) - with some extra code related to loading only model files defined in settings.json).
