### ISSUE TITLE
[Bug]: Sd 1.5 Checkpoint and Lora with Foocus on Google Colab

### ISSUE THREAD

**Issue by eriktavares** [lllyasviel/Fooocus#2470]
### Checklist

- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

I'm trying do generate a image using SD 1.5 model and Lora in Foocus, there was an erro message on display
![Erro](https://github.com/lllyasviel/Fooocus/assets/6141088/2a637305-82fb-4547-89fd-26528e7a8c0b)

### Steps to reproduce the problem

Run Foocus on Google Colab
Select Model Refiner epicrealism_naturalSinRC1VAE.safetensors
Select Lora 1 epiCRealLife.safetensors
Write a prompt and Negative prompt and click on generate

### What should have happened?

It should have generate the image with the prompt

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

None

### Console logs

```Shell
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.20 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 62.93 seconds
[Sampler] refiner_swap_method = vae
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 3.19 seconds
100% 12/12 [00:11<00:00,  1.05it/s]
Fooocus VAE-based swap.
Requested to load Interposer
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 115.14 seconds
Requested to load BaseModel
Loading 1 new model
```

**Comment by mashb1t** [comment]
> Note that this Colab will disable refiner by default because Colab free's resources are relatively limited (and some "big" features like image prompt may cause free-tier Colab to disconnect). We make sure that basic text-to-image is always working on free-tier Colab.

Please find this paragraph in the colab section of the readme. There is no official support for Colab with refiner, no matter if Free or Pro. You might get lucky when applying https://github.com/lllyasviel/Fooocus/pull/1710 though.
