### ISSUE TITLE
[Bug]: RuntimeError: Found no NVIDIA driver on your system.

### ISSUE THREAD

**Issue by yuxistar001** [lllyasviel/Fooocus#2472]
### Checklist

- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GU and installed a driver from http: //www.nvidia.com/Download/index.aspx

on MAC pro M1

### Steps to reproduce the problem

<img width="1621" alt="2" src="https://github.com/lllyasviel/Fooocus/assets/127599617/0e65a635-ebff-4dc4-8b00-27163f77f5be">

### What should have happened?

Can't find driver program from that link for MAC

### What browsers do you use to access Fooocus?

Brave

### Where are you running Fooocus?

Locally

### What operating system are you using?

MAC os

### Console logs

```Shell
https://colab.research.google.com/github/lllyasviel/Fooocus/blob/main/fooocus_colab.ipynb#scrollTo=VjYy0F2gZIPR
```

**Comment by mashb1t** [comment]
You have to select a GLU instance, e.g. T4 or V100 in order to run Fooocus on Colab without further modifications.
Running Fooocus on CPU only (not TPU) is also supported, but by a magnitude of 40-50x slower. To do so add `--always-cpu` after entrypoint_with_update.py.

I assume you just need to switch to T4 instance.

**Comment by yuxistar001** [comment]
swtiched to T4GPU, it appears"
Cannot connect to GPU backend
You cannot currently connect to a GPU due to usage limits in Colab."

**Comment by mashb1t** [comment]
@losyalla please ensure you didn't run out of minutes for Colab and you've selected T4 or better as an instance with a GPU.
