### ISSUE TITLE
[Feature Request]: Add support for layer diffusion：https://github.com/layerdiffusion/LayerDiffuse

### ISSUE THREAD

**Issue by p971607** [lllyasviel/Fooocus#2484]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Add support for layer diffusion：https://github.com/layerdiffusion/LayerDiffuse

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by mashb1t** [comment]
Duplicate of https://github.com/lllyasviel/Fooocus/issues/2403
