### ISSUE TITLE
[Feature Request]: Support Playground 2.5

### ISSUE THREAD

**Issue by PierrunoYT** [lllyasviel/Fooocus#2487]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Support Playground 2.5 Model 

### Proposed workflow

Choose the Playground 2.5 Model like the other models in Fooocus

**Comment by mashb1t** [comment]
see https://github.com/lllyasviel/Fooocus/discussions/2395

**Comment by mashb1t** [comment]
@RandomGitUser321 thanks for the hint, but Fooocus doesn't use the diffuses package.

**Comment by mashb1t** [comment]
Implemented in https://github.com/lllyasviel/Fooocus/pull/3073, please test CFG so we can find the best one for the preset (tested with 2 and 3, both with pro/contra9.
