### ISSUE TITLE
[Feature Request]: image for outpainting

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/Fooocus#2496]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

ok i want outpaint an image ... now only a prompt is available.
maybe its possible also take an image and change the weight between prompt and image to generate the outpaint part

### Proposed workflow

1. Go to .... inpaint-outpaint
2. upload the image you want outpaint
3. upload the image with the main idea for the outpaint area
4. optional write a prompt
5. set weight
6. Press .... the area to outpaint (left, right ...)
7. generate

**Comment by mashb1t** [comment]
@kalle07 this is already possible. Please use "Mixing Image Prompt and Inpaint" in Developer Debug Mode and upload up to four image prompt references.

![Screenshot 2024-03-11 at 00 13 29](https://github.com/lllyasviel/Fooocus/assets/9307310/4046f583-0605-4624-a280-69b7fe46e0a2)

**Comment by kalle07** [comment]
really,

thy i will try   ;)
