### ISSUE TITLE
[Bug]: proxy ? UI not working anymore. 

### ISSUE THREAD

**Issue by ksorah1** [lllyasviel/Fooocus#2499]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

[Start proxy] Local Sharing {{input.event[0]}}
Proxy Started {"target":"{{input.event[0]}}","proxy":"http://170.20.144.1:8001"}

### Steps to reproduce the problem

I updated pinokio then fooocus, and now it purpose me an adress with a proxy (instead of http://127.0.0.1...etc) , but it's not working

### What should have happened?

just working

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

w11

### Console logs

```Shell
Microsoft Windows [version 10.0.22631.3235]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\x\pinokio\api\fooocus.git\app>C:\Users\x\pinokio\api\fooocus.git\app\env\Scripts\activate C:\Users\x\pinokio\api\fooocus.git\app\env && python entry_with_update.py --preset realistic --disable-in-browser
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--preset', 'realistic', '--disable-in-browser']
Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
Fooocus version: 2.2.1
Loaded preset: C:\Users\x\pinokio\api\fooocus.git\app\presets\realistic.json
Total VRAM 8192 MB, total RAM 32492 MB
xformers version: 0.0.23.post1+cu118
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Refiner unloaded.

(env) C:\Users\x\pinokio\api\fooocus.git\app>
[Start proxy] Local Sharing {{input.event[0]}}
Proxy Started {"target":"{{input.event[0]}}","proxy":"http://170.20.144.1:8001"}
```

**Comment by mashb1t** [comment]
I am not familiar with Pinokio but i can assure you that sharing is working. Getting support [in the pinokio issue](https://github.com/pinokiocomputer/pinokio/issues/143) is the next step as this is not an issue of Fooocus.

Note that Pinokio appears to be no longer maintained.

You can use multiple options for sharing Fooocus. Please find more information here: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#ui-access-and-authentication

**Comment by mashb1t** [comment]
@ksorah1 the last commit to main wad on August 21, 2023. Are you sure it's actively maintained?
https://github.com/pinokiocomputer/pinokio/commits/main/

**Comment by ksorah1** [comment]
tanks for ze new update, very cool ! (kb is broken sry)
![2024-03-11 09_42_09](https://github.com/lllyasviel/Fooocus/assets/112913359/b2109112-8261-4f34-ad88-15247500853b)
![2024-03-11 09_41_15](https://github.com/lllyasviel/Fooocus/assets/112913359/8f084fbd-5dd3-46d5-8631-ff5565bb218f)


my pb fixed

**Comment by Gillzango** [comment]
Comment as tu fait j'ai le même problème, que dois je faire , je dois modifier mon fichier start.json ou pas?

**Comment by ksorah1** [comment]
restart ton pc

**Comment by Gillzango** [comment]
J'ai redémarré mon pc mais sa ne marche toujours pas.

C'est le même problème proxy started input event (0)
Que dois je faire
