### ISSUE TITLE
[Feature Request]: Switch LoRA Off or On in Preset or Config.txt

### ISSUE THREAD

**Issue by mashb1t** [lllyasviel/Fooocus#2503]
### Discussed in https://github.com/lllyasviel/Fooocus/discussions/2479

<div type='discussions-op-text'>

<sup>Originally posted by **DavidDragonsage** March  8, 2024</sup>
I really appreciate the Fooocus platform, and am happy with the new features in version 2.2. Thank you to the team for all your dedication and hard work!

I would like to control whether a LoRA starts off being enabled or disabled (checked or unchecked).</div>

**Comment by DavidDragonsage** [comment]
Thank you for all the hard work!
