### ISSUE TITLE
why i don't make it run,i don't know what's wrong

### ISSUE THREAD

**Issue by EXPECTTomarrow** [lllyasviel/Fooocus#251]
Total VRAM 4096 MB, total RAM 15741 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
xformers version: 0.0.20
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1650 : cudaMallocAsync
Using xformers cross attention

**Comment by DobleAncho** [comment]
I had the same issue. 
I extracted the main archieve into one folder and after it try to move it into other folder (I had a problem with 4Gb limit on FAT32) and start run.bat file from the new folder.
It had no sucess because the paths led to previous folder.
Reopening the archive have helped.

**Comment by mashb1t** [comment]
You need min. 8GB (6GB not tested) of VRAM with a 1XXX series card. Please find the official minimal requirements here: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement
