### ISSUE TITLE
[Bug]: Can't deploy to hugging face spaces. 

### ISSUE THREAD

**Issue by AndrewMTA5** [lllyasviel/Fooocus#2511]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

Trying to deploy fooocus to a hugging face space but when I use gradio deploy it won't let me set share=True. I'd like to use it in a webapp and have read over the gradio documentation but can't find a solution.

### Steps to reproduce the problem

gradio deploy

### What should have happened?

Should deploy and be available permanently on huggingface spaces

### Where are you running Fooocus?

None

### Console logs

```Shell
-
```

**Comment by mashb1t** [comment]
Also see https://github.com/lllyasviel/Fooocus/discussions/2512
