### ISSUE TITLE
[Bug]: Can't load/ use XFormers

### ISSUE THREAD

**Issue by nikolatesla20** [lllyasviel/Fooocus#2513]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I want to run Fooocus with Xformers since it greatly speeds up image generation on my RTX 3090. If I run a similar configuration in Automatic1111, my 3090 will perform a SDXL 1024x1024 image at 2.5it/s *without* xformers, and 3.6it/s *with* xformers. Fooocus always runs at 2.5it/s, so the cross attention that is is using seems slower.

if I edit "Launch.py" and set TRY_LOAD_XFORMERS to "True" it will download and install Xformers but I get this error during startup of run.bat:

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.0+cu121)
    Python  3.10.11 (you have 3.10.9)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention

So it switches back to using pytorch cross attention, which I can definitely see isn't as fast (Fooocus will run 2.5it/s whereas Automatic1111 with xformers will run 3.6it/s)

Is there a way to get Xformers working? It looks like it does not like a couple of the dependencies that Fooocus is currently using - OR perhaps I can get a specific Xformers version.

### Steps to reproduce the problem

1. open Launch.py
2. Set TRY_INSTALL_XFORMERS to "True"
3. execute Run.bat
4. note that xformers cross attention will not be used, it will give a warning about dependency issues.

### What should have happened?

Hopefully I should be able to use Xformers. I can run a similar setup in Automatic1111 and it speeds up my RTX3090 quite a bit.

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 10

### Console logs

```Shell
C:\Users\niko20\Desktop\fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --listen
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--listen']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.2.1
Total VRAM 24575 MB, total RAM 32672 MB
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.0+cu121)
    Python  3.10.11 (you have 3.10.9)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
Running on local URL:  http://0.0.0.0:7865
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: C:\Users\niko20\Desktop\fooocus\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [C:\Users\niko20\Desktop\fooocus\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [C:\Users\niko20\Desktop\fooocus\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\Users\niko20\Desktop\fooocus\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.

To create a public link, set `share=True` in `launch()`.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.66 seconds
Started worker with PID 37048
App started successful. Use the app with http://localhost:7865/ or 0.0.0.0:7865
```

### Additional information

RTX 3090 with NVidia drivers 551.76

**Comment by mashb1t** [comment]
@nikolatesla20 thank you for reporting, PR to update to 0.0.23 is created. Feel free to manually adjust the one line mentioned in the PR to check if this is working for you locally.
There seems to be some issue with your setup / fooocus though, i have an RTX 3080 and am able to get similar numbers to yours. It seems a bit odd that you get lower performance with your RTX 3090.

In general, Fooocus (2.2.1) should outperform A1111 (1.8.0) pretty easily in both performance and VRAM usage.

Fooocus:

![image](https://github.com/lllyasviel/Fooocus/assets/9307310/c5ce51e8-5c1c-4f82-b48d-2c9994f75a48)

![image](https://github.com/lllyasviel/Fooocus/assets/9307310/1cd04e95-9e1d-4465-a5cc-c9dfb14c4325)

- without xformers (pytorch cross attention): 2,81 it/s 
- with xformers 0.0.23: 2,79 it/s

A1111


![image](https://github.com/lllyasviel/Fooocus/assets/9307310/5f9d0efe-ddff-4602-aa73-88f470f51a8b)

with `--xformers`
![image](https://github.com/lllyasviel/Fooocus/assets/9307310/c176bdb5-51f1-4f68-a85a-86c033d7021c)

without `--xformers`
![image](https://github.com/lllyasviel/Fooocus/assets/9307310/55e78461-323d-48cc-be76-bf456a782a65)


I don't really know what's happening on your machine, but please check again. Something seems off.

**Comment by mashb1t** [comment]
@nikolatesla20 Feel free to post your feedback anyways, issue is closed as the issue doesn't exist anymore (PR merged to main).

**Comment by nikolatesla20** [comment]
Thank you @mashb1t for helping fix up main. I definitely was using 1024x1024. I'm not sure what other setting may be affecting me at the moment. I had previously found threads that mention the 3it/s, interestingly I get almost 3.4 - 3.5it/s in automatic1111 once I enabled xformers, (JuggernautXL or SDXL 1.0 with 1024x1024) the speed actually goes up as the image is rendering. 

In Fooocus I get a consistent 2.4 - 2.6 it/s even when it says it's using xformers cross attention. Haven't yet found the difference of why yet.
