### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shiloh92** [lllyasviel/Fooocus#2521]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

![abvx](https://github.com/lllyasviel/Fooocus/assets/84908222/64b4c76a-b600-4ae7-abb7-af792e8b40ae)
Perfectly loaded in cmd window, no errors whatsoever. Wont let me render anything. Worked perfect yesterday. 

### Steps to reproduce the problem

Start, try to render.

### What should have happened?

Render.

### What browsers do you use to access Fooocus?

Mozilla Firefox, Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

11

### Console logs

```Shell
To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: C:\Users\Administrator\Downloads\FFFFFFFFFF\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [C:\Users\Administrator\Downloads\FFFFFFFFFF\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [C:\Users\Administrator\Downloads\FFFFFFFFFF\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\Users\Administrator\Downloads\FFFFFFFFFF\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cpu, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Started worker with PID 20852
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
```

**Comment by steppres** [comment]
I also have the same issue from the no update yesterday that isn't impacting anyone 🤌 Mama mia!

**Comment by mashb1t** [comment]
Please also check if your Fooocus installation path has any spaces in its name, which could prevent Chrome from functioning correctly.
Checked with the latest version of Chrome in both Windows and MacOS, no issues on multiple devices, neither locally nor in Colab.

**Comment by zhincic** [comment]
Same issue, over and over again. Also checked the drive allocation sizes and it's on 'Automatic' for me, just as in the troubleshoot manual.
