### ISSUE TITLE
[Feature Request]: Change the Model Folder Source

### ISSUE THREAD

**Issue by lost-in-emotions** [lllyasviel/Fooocus#2529]
### What would your feature do?

hello there, it would be great if we can change the path of the Fooocus needed model folder to another existing folder (in my case from sd a1111), so that i dont have multiple safetensors of a huge file f.e. juggernautXL, dreamshaperXL, etc...

### Proposed workflow

1. Go to "Model Tab"
2. Press Button "Change Directory Folder"
3. Activate

**Comment by mashb1t** [comment]
You can already do so in the config, the checkpoints folders can also be an array. Example: 

```json
"path_checkpoints": [
    "/Volumes/data/ai/fooocus/models/checkpoints",
    "/Volumes/data/ai/a1111/models/Stable-diffusion"
],
```

Please find all config keys in config_modification_tutorial.txt and set them if necessary in config.txt.
