### ISSUE TITLE
[Bug]: Rounding long seeds in metadata.

### ISSUE THREAD

**Issue by poor7** [lllyasviel/Fooocus#2535]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When I try to view the metadata, it shows the wrong seed that is in the image.

### Steps to reproduce the problem

1. Create any image with metadata saved.
2. Save the image.
3. View the metadata of the saved image.

### What should have happened?

The seed should match, but it doesn't.
![snap](https://github.com/lllyasviel/Fooocus/assets/154618384/78d8d0c7-3787-46ac-9ead-0b2e2bd475f7)

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### Console logs

```Shell
no
```

### Additional information

When you try to load metadata, it loads the correct one, and not the one that is shown (rounded).

**Comment by mashb1t** [comment]
Yeah, that's one of the issues in the Gradio version Fooocus currently uses ([3.41.2](https://github.com/lllyasviel/Fooocus/blob/main/requirements_versions.txt#L13C9-L13C15)).
Parsing as string for metadata works as it's parsed to int anyways in https://github.com/lllyasviel/Fooocus/blob/main/modules/meta_parser.py#L132.

**Comment by mashb1t** [comment]
@poor7 thanks for reporting, much appreciated!
