### ISSUE TITLE
[Feature Request]: Please add proper mobile view

### ISSUE THREAD

**Issue by dasnolojy** [lllyasviel/Fooocus#2544]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

It would be great to use Fooocus on mobile device through VPN or so. It is available on mobile in the same network with --listen key but layout seems broken.

### Proposed workflow

1. Go to Fooocus publication from mobile device in the same network
2. Layout is broken

**Comment by mashb1t** [comment]
Can you please provide examples (screenshots) of which layout is broken for you?

**Comment by dasnolojy** [comment]
It seems i have a problem with "Generate" button.

![790457e5-a52d-461c-8c50-17d86f1d39a8](https://github.com/lllyasviel/Fooocus/assets/10321658/e7224cb8-f934-4bcb-98a2-ac91da3f8704)
![60b81b8d-7a84-4e5a-8c4c-9012295baf01](https://github.com/lllyasviel/Fooocus/assets/10321658/63caa737-d8e4-4f47-92bf-02525ea4a7b3)

**Comment by poor7** [comment]
Try zooming out on the page or rotating your phone.

**Comment by mashb1t** [comment]
Fooocus has a proper mobile view and offers in general a good experience on all tested modern handheld devices.
Can you please provide more informaton about the device/viewport/resolution you are using?

**Comment by dasnolojy** [comment]
Info about device on the first screenshot, viewport and resolution (591*1280) are the same as screenshots have.

**Comment by mashb1t** [comment]
> Info about device on the first screenshot (RMX1921=Realme XT), viewport and resolution (591*1280) are the same as screenshots have.

This resolution is not supported, sorry. Minimum is 600px afaik
