### ISSUE TITLE
[Feature Request]: SUPIR for upscale

### ISSUE THREAD

**Issue by MacroHongZ** [lllyasviel/Fooocus#2548]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

I've seen the latest SDXL-based image restoration algorithm, SUPIR, perform well in generating detail.
https://github.com/Fanghua-Yu/SUPIR

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by mashb1t** [comment]
> ⚠ Due to the large RAM (60G) and VRAM (30G x2) costs of SUPIR, we are working on the online demo releasing.

Resource requirements are too high at the moment to include this. Fooocus is currently able to run on Nvidia GPUs with 4GB VRAM.
