### ISSUE TITLE
[Feature Request]: Prompt embedded LoRAs

### ISSUE THREAD

**Issue by Cruxial0** [lllyasviel/Fooocus#2561]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Similar to how A1111 handles LoRAs by default, I believe there should be an option to embed LoRAs in the prompt by using the following structure:
```csharp
<LORA_NAME:WEIGHT>
```

The current workflow works well, but has a few limitations, namely being able to use wildcards and LoRAs together for more dynamic prompts. Additionally, this feature already exists for embeddings, so I reckon adding it for LoRAs should be trivial.

### Proposed workflow

1. Enter LoRAs in the prompt using the `<LORA_NAME:WEIGHT>` structure
2. Generate images, and LoRAs are loaded for each iteration

**Comment by mashb1t** [comment]
https://github.com/lllyasviel/Fooocus/pull/2323/ has been merged into develop
