### ISSUE TITLE
[Bug]: Custom styles fail to replicate pure-prompt generation

### ISSUE THREAD

**Issue by xunkar** [lllyasviel/Fooocus#2574]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I have created a JSON for customized styles. Generating a picture with a custom style, and manually inputting the style expansion into the prompt result in two different results.

### Steps to reproduce the problem

For testing purposes, I have a style file contains the following style: 

`{"name": "~Quality", "prompt": "{prompt}, best quality"}`

Using a fixed seed, generate any picture using the `~Quality` style only.
Using the same seed and the same prompt, uncheck the `~Quality` style and add `, best quality` to the prompt manually.

The generated pictures are different. Note that negative prompts in custom styles work correctly, it only impacts positive prompt expansions.

### What should have happened?

Using styles or manual prompt should be equivalent.

### What browsers do you use to access Fooocus?

Mozilla Firefox

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 10

### Console logs

```Shell
N/A
```

**Comment by mashb1t** [comment]
@xunkar sadly i can't reproduce the exact issue. Can you please provide the config from either history log or the resulting image with metadata turned on so this can be reproduced (or further analyzed)?
You can also test it yourself by importing these images using the metadata tab in input image:

only ~quality
![2024-03-19_23-23-20_5867](https://github.com/lllyasviel/Fooocus/assets/9307310/20564720-58cd-4e26-b70e-12592a577881)

~quality and Fooocus V2
![image - 2024-03-19T232557 705](https://github.com/lllyasviel/Fooocus/assets/9307310/5a75ed2f-4784-4519-a7e5-8d9958f61603)

**Comment by xunkar** [comment]
I ran more tests with your input and could not reproduce it either. I must have messed something up in my initial test… terribly sorry.
