### ISSUE TITLE
It takes up long time to install on colab

### ISSUE THREAD

**Issue by thekingbalXD** [lllyasviel/Fooocus#2586]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [x] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

It shows "Install requirements" for minutes.

### Steps to reproduce the problem

Just run it on colab

### What should have happened?

Fooocus should install fast

### Where are you running Fooocus?

Cloud (Google Colab)

### Console logs

```Shell
Collecting pygit2==1.12.2
  Downloading pygit2-1.12.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 15.5 MB/s eta 0:00:00
Requirement already satisfied: cffi>=1.9.1 in /usr/local/lib/python3.10/dist-packages (from pygit2==1.12.2) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.9.1->pygit2==1.12.2) (2.21)
Installing collected packages: pygit2
Successfully installed pygit2-1.12.2
/content
Cloning into 'Fooocus'...
remote: Enumerating objects: 5802, done.
remote: Counting objects: 100% (202/202), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 5802 (delta 118), reused 115 (delta 61), pack-reused 5600
Receiving objects: 100% (5802/5802), 32.69 MiB | 24.24 MiB/s, done.
Resolving deltas: 100% (3317/3317), done.
/content/Fooocus
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share', '--always-high-vram']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.3.0
Error checking version for torchsde: No package metadata was found for torchsde
Installing requirements
```

**Comment by poor7** [comment]
This is the norm.

**Comment by Abh3201** [comment]
Try Adding this at 1st line 
!pip install torchsde==0.2.5
OR 
!pip install torchsde

**Comment by mashb1t** [comment]
It can take up to 2 minutes to install all the packages on Colab, which is normal.

**Comment by andresdlp** [comment]
Yeah but this is not taking 2-5 minutes. I've been stuck on "!python entry_with_update.py --share --always-high-vram" for half an hour and every time I run it it gets stuck there again. Something's not working, might be on Colab's side.
