### ISSUE TITLE
[Bug]: Automatically determined expansion size of the outpainting seems wrong

### ISSUE THREAD

**Issue by justin-prnd** [lllyasviel/Fooocus#2599]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Following the instruction, Fooocus outpainting tries to expand 30% of each side if a side is included at `outpaint_selections`.
However, according to the code snippet which makes the paddings, 'left' and 'right' side padding seems wrong since `height * 0.3` is used rather than `width * 0.3`.

https://github.com/lllyasviel/Fooocus/blob/978267f461e204c6c4359a79ed818ee2e3e1af39/modules/async_worker.py#L603-L623

I think it should be modified like below.
```python3
        if 'inpaint' in goals:
            if len(outpaint_selections) > 0:
                H, W, C = inpaint_image.shape
                print(f"[DEBUG] Inpaint image shape: {str((H, W, C))}")
                if 'top' in outpaint_selections:
                    inpaint_image = np.pad(inpaint_image, [[int(H * 0.3), 0], [0, 0], [0, 0]], mode='edge')
                    inpaint_mask = np.pad(inpaint_mask, [[int(H * 0.3), 0], [0, 0]], mode='constant',
                                          constant_values=255)
                if 'bottom' in outpaint_selections:
                    inpaint_image = np.pad(inpaint_image, [[0, int(H * 0.3)], [0, 0], [0, 0]], mode='edge')
                    inpaint_mask = np.pad(inpaint_mask, [[0, int(H * 0.3)], [0, 0]], mode='constant',
                                          constant_values=255)

                H, W, C = inpaint_image.shape
                if 'left' in outpaint_selections:
                    inpaint_image = np.pad(inpaint_image, [[0, 0], [int(W * 0.3), 0], [0, 0]], mode='edge')
                    inpaint_mask = np.pad(inpaint_mask, [[0, 0], [int(W * 0.3), 0]], mode='constant',
                                          constant_values=255)
                if 'right' in outpaint_selections:
                    inpaint_image = np.pad(inpaint_image, [[0, 0], [0, int(W * 0.3)], [0, 0]], mode='edge')
                    inpaint_mask = np.pad(inpaint_mask, [[0, 0], [0, int(W * 0.3)]], mode='constant',
                                          constant_values=255)
```

### Steps to reproduce the problem

Let's assume that I have an image whose size is (H,W) = (1500, 2000).
If I outpaint for all four directions, Fooocus gives me (2400, 3440) size image.

Following the code snippet,
1. top, bottom padding for (1500, 2000) image -> (1500 + 1500 * 0.3 + 1500 * 0.3, 2000) = (2400, 2000)
2. left, right padding for (2400, 2000) image -> _(2400, 2000 + 2400 * 0.3 + 2400 * 0.3) = (2400, 3440)_
> this is the weird part

### What should have happened?

2. left, right padding for (2400, 2000) image -> **(2400, 2000 + 2000 * 0.3 + 2000 * 0.3) = (2400, 3200)**

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

Ubuntu 20.04

### Console logs

```Shell
.
```

**Comment by mashb1t** [comment]
@justin-prnd you're absolutely right, fixed
