### ISSUE TITLE
It's really great，Thank you ，Nvidia GTX 3050 4GB VRAM & 16GB RAM success run (  真的是太棒了，感谢大佬，rtx3050 4G显存+16G内存也能跑)

### ISSUE THREAD

**Issue by myopenresources** [lllyasviel/Fooocus#260]
It's working in my case
I have 16GB RAM and Nvidia GTX 3050 with 4GB VRAM

This is my computer configuration
![mmexport1692882196356](https://github.com/lllyasviel/Fooocus/assets/12525342/7e432208-f231-4a26-979e-fa30c37ff384)

example:
![mmexport1692882194744](https://github.com/lllyasviel/Fooocus/assets/12525342/22dcdf7a-6fc7-4463-a99e-281c2b415d10)

final generated image: 
![mmexport1692882201950](https://github.com/lllyasviel/Fooocus/assets/12525342/06a236a9-3058-4199-b1d8-a2ac2add31b0)

----------------------------------------------------------------------------------------------------------------------------------------

这是我的电脑配置
![mmexport1692882196356](https://github.com/lllyasviel/Fooocus/assets/12525342/7e432208-f231-4a26-979e-fa30c37ff384)
这个生成过程
![mmexport1692882194744](https://github.com/lllyasviel/Fooocus/assets/12525342/22dcdf7a-6fc7-4463-a99e-281c2b415d10)
这是最终生成的图片
![mmexport1692882201950](https://github.com/lllyasviel/Fooocus/assets/12525342/06a236a9-3058-4199-b1d8-a2ac2add31b0)

这是我见过硬件要求最低的了

**Comment by RealPhper** [comment]
590请求出战，等我消息

**Comment by RealPhper** [comment]
不支持A卡

**Comment by OpaoGuoNai** [comment]
共计花费了多长时间，我1070用了起码半小时

**Comment by mybhxl** [comment]
2060行吗？

**Comment by myopenresources** [comment]
> 590请求出战，等我消息

A卡当然不行了，我用公司电脑试过，RX550也不行，所以用自己的电脑玩了

**Comment by myopenresources** [comment]
> 共计花费了多长时间，我1070用了起码半小时

我的3050还行，原来5-6分钟出2图，昨晚加了32G内存，直接2-3分钟了

**Comment by myopenresources** [comment]
> 2060行吗？

没试过，按理2060的显示6G及以上是没问题的，但是内存不能太小了，16G以上吧

**Comment by myopenresources** [comment]
> 共计花费了多长时间，我1070用了起码半小时

可能是运行内存不够

**Comment by wonder-hy** [comment]
两个模型文件都下不下来,,同学可以分享一下么,十分感谢

**Comment by mashb1t** [comment]
Closing this issue as stale.
