### ISSUE TITLE
[Bug]: Lora hash values different between stable-diffusion-webui (Forge) and Fooocus.

### ISSUE THREAD

**Issue by mashb1t** [lllyasviel/Fooocus#2600]
When adding metadata, Lora hash values seem to be different between stable-diffusion-webui (Forge) and Fooocus. (Checkpoint hash values were the same.) Is this intended behavior?

---

### Model and Lora

- [juggernautXL_v9Rundiffusionphoto2](https://civitai.com/models/133005?modelVersionId=348913)
- [sd_xl_offset_example-lora_1.0](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/sd_xl_offset_example-lora_1.0.safetensors)

### Fooocus (v2.3.0)

![2024-03-22_13-00-43_9170](https://github.com/lllyasviel/Fooocus/assets/129341151/8c3751d8-2b1e-45c0-a1fb-7e0984b2c4e4)

#### hashes

```
juggernautXL_v9Rundiffusionphoto2: c9e3e68f89
sd_xl_offset_example-lora_1.0: 4852686128
```

#### metadata (a1111)

```
{
parameters:  "middle aged man, full body Steps: 30, Sampler: DPM++ 2M SDE Karras, Seed: 0, Size: 832x1216, CFG scale: 6, Sharpness: 2, ADM Guidance: "(1.5, 0.8, 0.3)", Model: juggernautXL_v9Rundiffusionphoto2, Model hash: c9e3e68f89, Performance: Speed, Scheduler: karras, Raw prompt: "middle aged man, full body", Raw negative prompt: , Lora hashes: "sd_xl_offset_example-lora_1.0: 4852686128: 0.1", Version: Fooocus v2.3.0",
metadata_scheme:  "a1111"
}
```

### stable-diffusion-webui-forge (f0.0.17v1.8.0rc-latest-276-g29be1da7)

![00008-0](https://github.com/lllyasviel/Fooocus/assets/129341151/60685750-224e-4fc9-ad4f-2997ffc59184)

#### hashes

```
juggernautXL_v9Rundiffusionphoto2: c9e3e68f89
sd_xl_offset_example-lora_1.0: 8e3e833226b3
```

#### metadata

```
{
parameters:  "middle aged man, full body, <lora:sd_xl_offset_example-lora_1.0:0.1> Steps: 30, Sampler: DPM++ 2M SDE Karras, CFG scale: 6, Seed: 0, Size: 832x1216, Model hash: c9e3e68f89, Model: juggernautXL_v9Rundiffusionphoto2, Lora hashes: "sd_xl_offset_example-lora_1.0: 8e3e833226b3", Version: f0.0.17v1.8.0rc-latest-276-g29be1da7",
metadata_scheme:  "a1111"
}
```

#### Fooocus
![meta_fooocus_civit](https://github.com/lllyasviel/Fooocus/assets/129341151/21054beb-4827-4639-a059-e2e6b9d3d698)

#### stable-diffusion-webui-forge
![meta_forge_civit](https://github.com/lllyasviel/Fooocus/assets/129341151/6b1f7bdc-06db-4747-9797-4499ccc66c03)

_Originally posted by @d4c2b0 in https://github.com/lllyasviel/Fooocus/discussions/2598_

**Comment by jvel07** [comment]
how do you generate a full-body person like this? When I try to generate someone like "playing tennis" for example, it always shows half the body (upper part), never a complete body.
Are there any specific configs for this?

**Comment by d4c2b0** [comment]
@jvel07 I think you can simply add "full body" to the prompt.

**Comment by jvel07** [comment]
@d4c2b0 not working, almost never generates a full body. Either half or 3/4

**Comment by d4c2b0** [comment]
Other than that, you can increase the word strength like `(full body:1.1)` or make the ratio of the generated image vertical.

---

![2024-04-23_20-41-50_3493](https://github.com/lllyasviel/Fooocus/assets/129341151/fbee5488-5b2b-447f-9c94-e66f1159820f)
playing tennis, (full body:1.1)

```json
{
"prompt": "playing tennis, (full body:1.1)",
"negative_prompt": "",
"prompt_expansion": "playing tennis, (full body:1.1), sharp focus, detailed, intricate, elegant, highly enhanced, loving, caring, generous, scenic background, warm light, clear, color, romantic, beautiful, symmetry, stunning, aesthetic, perfect composition, creative, positive radiant, attractive, thought, fancy, best detail, dramatic, pleasant, lovely, illuminated, joyful",
"styles": "['Fooocus V2', 'Fooocus Negative']",
"performance": "Speed",
"resolution": "(1344, 704)",
"guidance_scale": 7,
"sharpness": 2,
"adm_guidance": "(1.5, 0.8, 0.3)",
"base_model": "xl\\juggernautXL_juggernautX.safetensors",
"refiner_model": "None",
"refiner_switch": 0.5,
"sampler": "dpmpp_2m",
"scheduler": "karras",
"seed": "5134009732579248459",
"lora_combined_1": "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
"metadata_scheme": "a1111",
"version": "Fooocus v2.3.1"
}
```

---

![2024-04-23_20-42-45_2325](https://github.com/lllyasviel/Fooocus/assets/129341151/8eaa7bca-af17-41ab-99ea-5ce50597c63d)
playing tennis, full body

```json
{
"prompt": "playing tennis, full body",
"negative_prompt": "",
"prompt_expansion": "playing tennis, full body, enchanted, magic, light atmosphere, background, colorful, stunning, intricate, highly detailed, professional, complex, polished, beautiful, elegant, color, cool, epic, great composition, cinematic, sharp focus, winning, fine detail, creative, positive, attractive, artistic, thoughtful, cheerful, engaging, calm, cute, pretty, passionate",
"styles": "['Fooocus V2', 'Fooocus Negative']",
"performance": "Speed",
"resolution": "(896, 1152)",
"guidance_scale": 7,
"sharpness": 2,
"adm_guidance": "(1.5, 0.8, 0.3)",
"base_model": "xl\\juggernautXL_juggernautX.safetensors",
"refiner_model": "None",
"refiner_switch": 0.5,
"sampler": "dpmpp_2m",
"scheduler": "karras",
"seed": "1407158880935718667",
"lora_combined_1": "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
"metadata_scheme": "a1111",
"version": "Fooocus v2.3.1"
}
```

---

If this does not solve the problem, it may be due to the model (or Lora) you are using. The attached image uses [RunDiffusion/Juggernaut-X-v10](https://huggingface.co/RunDiffusion/Juggernaut-X-v10).

**Comment by mashb1t** [comment]
> hi @mashb1t! how do you generate a full-body person like this? When I try to generate someone like "playing tennis, full body" for example, it always shows half the body (upper part), never a complete body. Are there any specific configs for this?

@jvel07 the aspect ratio plays a big part here as well as the mention of "full body". You can continue with doing outpainting after you got your character right. This is at least what worked for me the best.
