### ISSUE TITLE
ARC GPU ,use XPU loading models to GPU , without any progress

### ISSUE THREAD

**Issue by 823863429** [lllyasviel/Fooocus#2604]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Configure the environment according to this method, #2120 
The runtime keeps getting stuck on loading models to GPU. Please help me

System Info
Name: torch
Version: 2.1.0a0+cxx11.abi
CPU：Intel(R) Core(TM) Ultra 5 125H
GPU 0：
Intel(R) Arc(TM) Graphics

Driver version: 31.0.101.5008
Driver date: 2023/11/23
DirectX version: 12 (FL 12.1)
Physical location: PCI bus 0, device 2, function 0

Utilization rate 4%
Dedicated GPU memory
Shared GPU memory 5.8/15.8 GB
GPU memory 5.8/15.8 GB

### Steps to reproduce the problem

Configure the environment according to this method, #2120 
.\python_embeded\python -u main\entry_with_update.py --disable-analytics --unet-in-bf16 --vae-in-bf16 --clip-in-fp16

### What should have happened?

work success

### What browsers do you use to access Fooocus?

Microsoft Edge

### Where are you running Fooocus?

Locally

### Console logs

```Shell
Loading models to GPU is always displayed
Waited for half an hour, no response
```

**Comment by mashb1t** [comment]
Intel ARC GPUs are not officially supported, please discuss in https://github.com/lllyasviel/Fooocus/pull/2120.
