### ISSUE TITLE
Fooocus is much slower than official replicate sdxl model. Any way to speed up？

### ISSUE THREAD

**Issue by lanyusan** [lllyasviel/Fooocus#264]
I took the liberty to bundle it as a private replicate model just for testing, and had a run on an a40 large instance, which is the same to the machine to run official sdxl replicate model at  https://replicate.com/stability-ai/sdxl.

With same prompt of `An astronaut riding a rainbow unicorn, cinematic, dramatic`, at `speed` mode,  it took  Fooocus 17s but it only took official sdxl model around 8s to run, at 30 steps, with expert ensemblance refiner.

Is it possible to make Fooocus as fast as official sdxl replicate model?

Edit: Official replicate logs:

official replicate SDXL model log:
```
Using seed: 23774
Prompt: An astronaut riding a rainbow unicorn, cinematic, dramatic
txt2img mode
  0%|          | 0/19 [00:00<?, ?it/s]
  5%|▌         | 1/19 [00:00<00:03,  5.00it/s]
 11%|█         | 2/19 [00:00<00:03,  4.98it/s]
 16%|█▌        | 3/19 [00:00<00:03,  4.97it/s]
 21%|██        | 4/19 [00:00<00:03,  4.98it/s]
 26%|██▋       | 5/19 [00:01<00:02,  4.98it/s]
 32%|███▏      | 6/19 [00:01<00:02,  4.98it/s]
 37%|███▋      | 7/19 [00:01<00:02,  4.98it/s]
 42%|████▏     | 8/19 [00:01<00:02,  4.98it/s]
 47%|████▋     | 9/19 [00:01<00:02,  4.97it/s]
 53%|█████▎    | 10/19 [00:02<00:01,  4.97it/s]
 58%|█████▊    | 11/19 [00:02<00:01,  4.97it/s]
 63%|██████▎   | 12/19 [00:02<00:01,  4.97it/s]
 68%|██████▊   | 13/19 [00:02<00:01,  4.97it/s]
 74%|███████▎  | 14/19 [00:02<00:01,  4.96it/s]
 79%|███████▉  | 15/19 [00:03<00:00,  4.96it/s]
 84%|████████▍ | 16/19 [00:03<00:00,  4.96it/s]
 89%|████████▉ | 17/19 [00:03<00:00,  4.97it/s]
 95%|█████████▍| 18/19 [00:03<00:00,  4.97it/s]
100%|██████████| 19/19 [00:03<00:00,  4.97it/s]
100%|██████████| 19/19 [00:03<00:00,  4.97it/s]
  0%|          | 0/7 [00:00<?, ?it/s]
 14%|█▍        | 1/7 [00:00<00:01,  4.37it/s]
 29%|██▊       | 2/7 [00:00<00:01,  4.35it/s]
 43%|████▎     | 3/7 [00:00<00:00,  4.34it/s]
 57%|█████▋    | 4/7 [00:00<00:00,  4.34it/s]
 71%|███████▏  | 5/7 [00:01<00:00,  4.34it/s]
 86%|████████▌ | 6/7 [00:01<00:00,  4.33it/s]
100%|██████████| 7/7 [00:01<00:00,  4.33it/s]
100%|██████████| 7/7 [00:01<00:00,  4.34it/s]

```
Fooocus model log:

```
/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
return self.fget.__get__(instance, owner)()
  0%|          | 0/30 [00:00<?, ?it/s]/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/torchsde/_brownian/brownian_interval.py:594: UserWarning: Should have tb<=t1 but got tb=14.614643096923828 and t1=14.614643.
warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
  3%|▎         | 1/30 [00:00<00:10,  2.80it/s]
  7%|▋         | 2/30 [00:00<00:07,  3.72it/s]
 10%|█         | 3/30 [00:00<00:06,  4.14it/s]
 13%|█▎        | 4/30 [00:00<00:06,  4.30it/s]
 17%|█▋        | 5/30 [00:01<00:05,  4.46it/s]
 20%|██        | 6/30 [00:01<00:05,  4.57it/s]
 23%|██▎       | 7/30 [00:01<00:05,  4.56it/s]
 27%|██▋       | 8/30 [00:01<00:04,  4.63it/s]
 30%|███       | 9/30 [00:02<00:04,  4.68it/s]
 33%|███▎      | 10/30 [00:02<00:04,  4.64it/s]
 37%|███▋      | 11/30 [00:02<00:04,  4.69it/s]
 40%|████      | 12/30 [00:02<00:03,  4.72it/s]
 43%|████▎     | 13/30 [00:02<00:03,  4.67it/s]
 47%|████▋     | 14/30 [00:03<00:03,  4.71it/s]
 50%|█████     | 15/30 [00:03<00:03,  4.73it/s]
 53%|█████▎    | 16/30 [00:03<00:02,  4.68it/s]
 57%|█████▋    | 17/30 [00:03<00:02,  4.71it/s]
 60%|██████    | 18/30 [00:03<00:02,  4.73it/s]
 63%|██████▎   | 19/30 [00:04<00:02,  4.67it/s]
Refiner swapped.
 67%|██████▋   | 20/30 [00:04<00:02,  4.70it/s]
 70%|███████   | 21/30 [00:05<00:04,  2.00it/s]
 73%|███████▎  | 22/30 [00:05<00:03,  2.35it/s]
 77%|███████▋  | 23/30 [00:06<00:02,  2.71it/s]
 80%|████████  | 24/30 [00:06<00:01,  3.04it/s]
 83%|████████▎ | 25/30 [00:06<00:01,  3.29it/s]
 87%|████████▋ | 26/30 [00:06<00:01,  3.53it/s]
 90%|█████████ | 27/30 [00:06<00:00,  3.72it/s]
 93%|█████████▎| 28/30 [00:07<00:00,  3.83it/s]/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/torchsde/_brownian/brownian_interval.py:585: UserWarning: Should have ta>=t0 but got ta=0.02916753850877285 and t0=0.029168.
warnings.warn(f"Should have ta>=t0 but got ta={ta} and t0={self._start}.")
 97%|█████████▋| 29/30 [00:07<00:00,  3.97it/s]
100%|██████████| 30/30 [00:07<00:00,  4.07it/s]
100%|██████████| 30/30 [00:07<00:00,  3.89it/s]
```

**Comment by MoonRide303** [comment]
@lanyusan Did you make sure both generators have exactly the same setup, first? Selected scheduler and sampler, numbers of steps - those things affect generation speed. When you will have those aligned, then total generation speed should be very similar.

Try for example Karras Scheduler and Euler sampler ("K_EULER" in Replica), disable Refiner and LoRAs, set 60 steps - and repeat your test, then. You should get pretty similar results.

**Comment by lanyusan** [comment]
I tested the two with similar settings. 

I have looked at the example code published by stablility ai. They use diffusers.

Does comfyui use diffusers too?

**Comment by MoonRide303** [comment]
@lanyusan Nope. [ComfyUI](https://github.com/comfyanonymous/ComfyUI) has loaders for diffusers models, but it's not built on top of diffusers. So as long as Fooocus isn't noticeably slower than Comfy (with exactly same workflow and generation parameters, running on the same hardware, OS and drivers), then it's not bug in Fooocus. I am using current master version of Comfy in [Fooocus-MRE](https://github.com/MoonRide303/Fooocus-MRE) (trying to not get behind more than couple of days), and I see no difference between generation speed in ComfyUI and in MRE.

And if you you think there's a bug in Comfy code making it slower than it should be - please report it directly to Comfy.

**Comment by konieshadow** [comment]
Newer version of Fooocus is much faster.
In my test, the Fooocus default pipeline only need 6~8 senconds to generate a 1024x1024 picture.

Log of https://replicate.com/konieshadow/fooocus-api:

[Predictor Predict] Params: {'prompt': 'An astronaut riding a rainbow unicorn, cinematic, dramatic', 'negative_prompt': '', 'style_selections': [], 'performance_selection': 'Speed', 'aspect_ratios_selection': '1024×1024', 'image_number': 1, 'image_seed': 23774, 'sharpness': 2.0, 'guidance_scale': 7.0, 'base_model_name': 'sd_xl_base_1.0_0.9vae.safetensors', 'refiner_model_name': 'sd_xl_refiner_1.0_0.9vae.safetensors', 'loras': [('sd_xl_offset_example-lora_1.0.safetensors', 0.5)], 'uov_input_image': None, 'uov_method': 'Disabled', 'outpaint_selections': [], 'inpaint_input_image': None, 'image_prompts': []}
[Task Queue] Task queue is free, start task, seq=32
[Parameters] Adaptive CFG = 7.0
[Parameters] Sharpness = 2.0
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 7.0
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 20
[Fooocus] Initializing ...
[Fooocus] Loading models ...
[Fooocus] Processing prompts ...
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
Preparation time: 0.08 seconds
Moving model to GPU: 0.00 seconds
  0%|          | 0/30 [00:00<?, ?it/s]
  3%|▎         | 1/30 [00:00<00:05,  4.98it/s]
  7%|▋         | 2/30 [00:00<00:05,  4.93it/s]
 10%|█         | 3/30 [00:00<00:05,  4.91it/s]
 13%|█▎        | 4/30 [00:00<00:05,  4.92it/s]
 17%|█▋        | 5/30 [00:01<00:05,  4.92it/s]
 20%|██        | 6/30 [00:01<00:04,  4.92it/s]
 23%|██▎       | 7/30 [00:01<00:04,  4.92it/s]
 27%|██▋       | 8/30 [00:01<00:04,  4.92it/s]
 30%|███       | 9/30 [00:01<00:04,  4.91it/s]
 33%|███▎      | 10/30 [00:02<00:04,  4.91it/s]
 37%|███▋      | 11/30 [00:02<00:03,  4.88it/s]
 40%|████      | 12/30 [00:02<00:03,  4.88it/s]
 43%|████▎     | 13/30 [00:02<00:03,  4.88it/s]
 47%|████▋     | 14/30 [00:02<00:03,  4.89it/s]
 50%|█████     | 15/30 [00:03<00:03,  4.90it/s]
 53%|█████▎    | 16/30 [00:03<00:02,  4.90it/s]
 57%|█████▋    | 17/30 [00:03<00:02,  4.90it/s]
 60%|██████    | 18/30 [00:03<00:02,  4.90it/s]
 63%|██████▎   | 19/30 [00:03<00:02,  4.91it/s]
Refiner Swapped
 67%|██████▋   | 20/30 [00:04<00:02,  4.91it/s]
 70%|███████   | 21/30 [00:04<00:01,  4.90it/s]
 73%|███████▎  | 22/30 [00:04<00:01,  4.75it/s]
 77%|███████▋  | 23/30 [00:04<00:01,  4.65it/s]
 80%|████████  | 24/30 [00:04<00:01,  4.59it/s]
 83%|████████▎ | 25/30 [00:05<00:01,  4.55it/s]
 87%|████████▋ | 26/30 [00:05<00:00,  4.52it/s]
 90%|█████████ | 27/30 [00:05<00:00,  4.50it/s]
 93%|█████████▎| 28/30 [00:05<00:00,  4.49it/s]
 97%|█████████▋| 29/30 [00:06<00:00,  4.50it/s]
100%|██████████| 30/30 [00:06<00:00,  4.51it/s]
100%|██████████| 30/30 [00:06<00:00,  4.76it/s]
Generating and saving time: 6.63 seconds
[Task Queue] Finish task, seq=32
[Predictor Predict] Finished with 1 images

**Comment by karklav** [comment]
i tried to generate teh same picture as you but it took me more than 6 minutes

[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] New suffix: intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski
[Fooocus] Encoding base positive #1 ...
[Fooocus] Encoding base negative #1 ...
[ADM] Negative ADM = True
  0%|          | 0/30 [00:00<?, ?it/s]C:\Users\User\AppData\Roaming\StabilityMatrix\Packages\Fooocus\venv\lib\site-packages\torchsde\_brownian\brownian_interval.py:594: UserWarning: Should have tb<=t1 but got tb=14.614643096923828 and t1=14.614643.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
 93%|#########3| 28/30 [04:13<00:16,  8.45s/it]C:\Users\User\AppData\Roaming\StabilityMatrix\Packages\Fooocus\venv\lib\site-packages\torchsde\_brownian\brownian_interval.py:585: UserWarning: Should have ta>=t0 but got ta=0.02916753850877285 and t0=0.029168.
  warnings.warn(f"Should have ta>=t0 but got ta={ta} and t0={self._start}.")
100%|##########| 30/30 [04:29<00:00,  8.99s/it]
Diffusion time: 376.16 seconds
Image generated with private log at: C:\Users\User\AppData\Roaming\StabilityMatrix\Packages\Fooocus\outputs\2023-10-11\log.html
Total time: 381.18 seconds

**Comment by mashb1t** [comment]
The speed has recently been bumped again, also LCM and Turbo are now supported.
Many more things have changed since you reported the issue, feel free to check out the latest vesion of Fooocus.
Your feedback is always welcome!
