### ISSUE TITLE
[Bug]: error loading nvfuser_codegen.dll or one of its dependencies

### ISSUE THREAD

**Issue by iamsuper123** [lllyasviel/Fooocus#2649]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

the run.bat didn't start

### Steps to reproduce the problem

1. click on the run.bat

### What should have happened?

it should've opened the webui

### Where are you running Fooocus?

None

### Console logs

```Shell
C:\Users\alienware\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset anime
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'anime']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.3.1
Loaded preset: C:\Users\alienware\Fooocus_win64_2-1-831\Fooocus\presets\anime.json
[Cleanup] Attempting to delete content of temp dir C:\Users\alienware\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/animaPencilXL_v100.safetensors" to C:\Users\alienware\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\animaPencilXL_v100.safetensors

Traceback (most recent call last):
  File "C:\Users\alienware\Fooocus_win64_2-1-831\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Users\alienware\Fooocus_win64_2-1-831\Fooocus\launch.py", line 132, in <module>
    config.default_base_model_name, config.checkpoint_downloads = download_models(
  File "C:\Users\alienware\Fooocus_win64_2-1-831\Fooocus\launch.py", line 123, in download_models
    load_file_from_url(url=url, model_dir=config.paths_checkpoints[0], file_name=file_name)
  File "C:\Users\alienware\Fooocus_win64_2-1-831\Fooocus\modules\model_loader.py", line 24, in load_file_from_url
    from torch.hub import download_url_to_file
  File "C:\Users\alienware\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 193] %1 is not a valid Win32 application. Error loading "C:\Users\alienware\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.

C:\Users\alienware\Fooocus_win64_2-1-831>pause
Press any key to continue . . .
```

### Additional information

I've ran sd-forge webui and stable diffusion webui perfectly before. I have python added to path. I'm also using symlink directory junctions for my models folder to go to my stable diffusion folder to save disk space

I've also read the troubleshoot guide and the closest thing i found to my error was "abort" or "no error but console disappears immediately, could not find error" in which case it tells me to set up more system swap. I did the steps correctly in the image in memory paging of my pc and I don't think that's the problem, as I've ran stable diffusion before

**Comment by mashb1t** [comment]
Are yiu using a 32 or 64 Bit installation of Windows?

**Comment by mashb1t** [comment]
@iamsuper123 bump
