### ISSUE TITLE
[Bug]: strange default_model behaviour

### ISSUE THREAD

**Issue by shadowblade227** [lllyasviel/Fooocus#2653]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

If you specify an existing checkpoint file in the config.txt under the default_model key, it will be ignored and juggernaut v8 will still be downloaded when launch using run.bat. 

If you specify the name of a non-existent file, then juggernaut v8 will not be loaded, but the existing juggernaut v7 in the checkpoints directory will be used.

If you don't specify default_model, then juggernaut v7 will just be used.

My config.txt:
{
    "path_checkpoints": "C:\\diffusion\\stable-diffusion-webui\\models\\Stable-diffusion\\xl",
    "path_loras": "C:\\diffusion\\stable-diffusion-webui\\models\\Lora\\xl",
    "path_embeddings": "C:\\diffusion\\fooocus\\Fooocus\\models\\embeddings",
    "path_vae_approx": "C:\\diffusion\\fooocus\\Fooocus\\models\\vae_approx",
    "path_upscale_models": "C:\\diffusion\\fooocus\\Fooocus\\models\\upscale_models",
    "path_inpaint": "C:\\diffusion\\fooocus\\Fooocus\\models\\inpaint",
    "path_controlnet": "C:\\diffusion\\fooocus\\Fooocus\\models\\controlnet",
    "path_clip_vision": "C:\\diffusion\\fooocus\\Fooocus\\models\\clip_vision",
    "path_fooocus_expansion": "C:\\diffusion\\fooocus\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
    "path_outputs": "C:\\Dropbox\\fooocus",
	"default_model": "zavychromaxl_v21.safetensors",
	"default_refiner": "",
	"default_loras": [],
	"default_styles": []
}

I've also tried change default.json in presets, still the save behaviour.

### Steps to reproduce the problem

1. add "default_model": "modelname.safetensors" to config.txt
2. launch run.bat
3. program will try to download juggernaut v8
4. change "default_model" to "abcd123.safetensors"
5. program will use juggernaut v7 which exist in checkpoints directory
6. delete "default_model" key
7. program will use juggernaut v7

### What should have happened?

specified model should be used if it exists!

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 10

### Console logs

```Shell
C:\diffusion\fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --listen
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--listen']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.3.1
[Cleanup] Attempting to delete content of temp dir C:\Users\l41N\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_v8Rundiffusion.safetensors" to C:\diffusion\stable-diffusion-webui\models\Stable-diffusion\xl\juggernautXL_v8Rundiffusion.safetensors

  0%|▎
```

### Additional information

I would also like to know how to correctly specify default_loras placed in subdirectories. I've tried name it like "style/lora.safetensors", "style//lora.safetensors", "style\lora.safetensors", r"style/lora.safetensors" - it all ignored.

**Comment by mashb1t** [comment]
You alao have to change/remove the model downloads in the default presrt or override these keys in your config in order for Fooocus not to download the default models.

**Comment by jjiikkkk** [comment]
i tried to find out the default config in linux folders
