### ISSUE TITLE
[Bug]: New Wildcard Files not working

### ISSUE THREAD

**Issue by metzo007** [lllyasviel/Fooocus#2663]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Hi,

new wildcard files are nor reconised anymore. Old files I had in my wildcards folder work fine. 

### Steps to reproduce the problem

I downloaded colors.txt from here https://github.com/lllyasviel/Fooocus/blob/main/wildcards/color.txt
Works fine 
I remamed the file to colors.txt and __colors__ in prompt, I only get the name colors in the prompt. 

### What should have happened?

Fooocus should show the colours from the text file 

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

None

### Console logs

```Shell
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: E:\FOoOcus\Fooocus\outputs\2024-03-29\log.html
Generating and saving time: 16.55 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Total time: 17.04 seconds
[Fooocus Model Management] Moving model(s) has taken 0.61 seconds
```

**Comment by mashb1t** [comment]
You have to click the "reload files" button or restart Fooocus to detect new wildcard files.

**Comment by metzo007** [comment]
"reload files" button or restart Fooocus does not help. New wildcards fils will not show
