### ISSUE TITLE
docker of Fooocus

### ISSUE THREAD

**Issue by cgwyx** [lllyasviel/Fooocus#267]
docker pull cgwyx/fooocus:gpu118

docker run -it --name fooocus --gpus all --net=host \\
-p 7860:7860 \\
-v /mnt/p1/diffusion/Fooocusdocker:/Fooocus \\
cgwyx/fooocus:gpu118 bash

conda activate fooocus

python launch.py

**Comment by mabushey** [comment]
What are the extra commands after the docker run? You have to exec into the container and run those?

**Comment by cgwyx** [comment]
> What are the extra commands after the docker run? You have to exec into the container and run those?

docker pull cgwyx/fooocus:gpu118

docker run -it --name fooocus --gpus all --net=host \\
-p 7860:7860 \\
-v /mnt/p1/diffusion/Fooocusdocker:/Fooocus \\
cgwyx/fooocus:gpu118 bash

$ conda activate fooocus

$ python launch.py

**Comment by cgwyx** [comment]
> vast.ai

https://vast.ai/docs/overview/quickstart

> What are the extra commands after the docker run? You have to exec into the container and run those?



> how do i use that on vast.ai? Sorry.. kinda of a newbie on docker...

https://vast.ai/docs/overview/quickstart

https://github.com/SU1199/fastBooth

**Comment by cgwyx** [comment]
> how do i use that on vast.ai? Sorry.. kinda of a newbie on docker...

https://vast.ai/docs/overview/quickstart

https://github.com/SU1199/fastBooth

**Comment by mashb1t** [comment]
Please also check https://github.com/lllyasviel/Fooocus/pull/1418 for further docker setup code.

**Comment by cgwyx** [comment]
FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04
# FROM nvidia/cuda:11.6.2-runtime-ubuntu20.04
# FROM nvidia/cuda:11.3.1-runtime-ubuntu20.04


LABEL MAINTAINER="chenggong"


ENV PATH="/root/miniconda3/bin:${PATH}"


RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &amp;&amp; echo "Asia/Shanghai" &gt; /etc/timezone


RUN apt-get update &amp;&amp; \
&nbsp; &nbsp; apt-get install -y wget git ffmpeg libsm6 libxext6 &amp;&amp; \
&nbsp; &nbsp; rm -rf /var/lib/apt/lists/* &amp;&amp; \
&nbsp; &nbsp; wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh &amp;&amp; \
&nbsp; &nbsp; mkdir /root/.conda &amp;&amp; \
&nbsp; &nbsp; bash Miniconda3-latest-Linux-x86_64.sh -b &amp;&amp; \
&nbsp; &nbsp; rm -f Miniconda3-latest-Linux-x86_64.sh&nbsp;


RUN git clone https://github.com/lllyasviel/Fooocus.git


WORKDIR /Fooocus


RUN conda env create -f /Fooocus/environment.yaml
RUN conda init bash
SHELL ["conda", "run", "-n", "fooocus", "/bin/bash", "-c"]


RUN pip install -r requirements_versions.txt


CMD ["python3","-u", "launch.py"]





尾生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lllyasviel/Fooocus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月2日(星期二) 凌晨2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lllyasviel/Fooocus] docker of Fooocus (Issue #267)





 
Please also check #1418 for further docker setup code.
