### ISSUE TITLE
[Bug]: parameter "default_cfg_tsnr" does not change when changing preset

### ISSUE THREAD

**Issue by attyru** [lllyasviel/Fooocus#2684]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I have several presets created, each of them has different parameter values. When changing a preset in the interface, all parameters are loaded correctly except for "default_cfg_tsnr", it still has the previous value.

### Steps to reproduce the problem

1. Create new preset (or copy existing), open in notepad.
2. Add `"default_cfg_tsnr": 3.0`, save.
3. Restart or run Fooocus in web interface open "Advanced" tab and change "CFG Mimicking from TSNR" on 1,0.
4. Go to the "Settings" tab and change preset on created in 1.)
5. Open "Advanced" tab again - "CFG Mimicking from TSNR" not changed.

### What should have happened?

corectly load "default_cfg_tsnr" parameter from preset json

### What browsers do you use to access Fooocus?

Microsoft Edge

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
none
```

**Comment by mashb1t** [comment]
It's not necessarily a bug, but a feature as it is not in the array https://github.com/lllyasviel/Fooocus/blob/e2f9bcb11d06216d6800676c48d8d74d6fd77a4b/modules/config.py#L474-L497 and could be added.
It may already work when also setting `adaptive_cfg` in a preset in addition with default_cfg_tsnr with the same value. Please check.

**Comment by attyru** [comment]
made it this way:
![image](https://github.com/lllyasviel/Fooocus/assets/76990611/5942467d-5c73-4ff9-b036-d9f32225a361)

the value still doesn't change

**Comment by mashb1t** [comment]
implemented in https://github.com/lllyasviel/Fooocus/pull/2990
