### ISSUE TITLE
[Feature Request]: 'output file browser' for use when Fooocus is shared

### ISSUE THREAD

**Issue by fbauer-kunbus** [lllyasviel/Fooocus#2686]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

To my opinion, the 'sharing' option to expose the local Fooocus instance to public via gradio doesn't make much sense if I don't have a convenient way to access all the images in the 'output' folder. When I am remote and create images on my AI machine at home, I don't want to immediately download each and every image that I just created! 
This use-case is so obvious, it seems strange, that the developers of Fooocus didn't realize it. Especially the typical users of Fooocus cannot be expected to set up an own web- or ftp-server on their local AI machines to serve the 'output' directory for public access.

### Proposed workflow

Implement some sort of 'output file browser', directly integrated into Fooocus GUI

**Comment by mashb1t** [comment]
This is already implemented, please use the History Log.
See https://github.com/lllyasviel/Fooocus/discussions/160
