### ISSUE TITLE
[Bug]: New Wildcard Files not working

### ISSUE THREAD

**Issue by metzo007** [lllyasviel/Fooocus#2687]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

Hi,

new wildcard files are nor reconised anymore. Old files I had in my wildcards folder work fine.
reload files" button or restart Fooocus does not help. New wildcards fils will not show up

Will provide pictures below

### Steps to reproduce the problem

created file setup.txt in folder Fooocus\wildcards with the entrys "black" and "white"
re started fooocus again

prompt for the setup file with __setup__ ( picture two )

instead of using "black" or "white", Fooocus used the name "setup" in the prompt ( picture 3 )

### What should have happened?

![image](https://github.com/lllyasviel/Fooocus/assets/49093328/4eaee5aa-95af-4cfb-bc21-96d25b2bb6d3)

![image](https://github.com/lllyasviel/Fooocus/assets/49093328/2206aa80-676a-479a-ba3b-62af57127553)
![image](https://github.com/lllyasviel/Fooocus/assets/49093328/1aa0b280-1d4a-455a-b369-0d4dafe69863)

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

None

### Console logs

```Shell
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.98 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:13<00:00,  2.23it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: E:\FOoOcus\Fooocus\outputs\2024-04-01\log.html
Generating and saving time: 16.60 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Total time: 17.33 seconds
[Fooocus Model Management] Moving model(s) has taken 0.61 seconds
```

**Comment by ILikeToasters** [comment]
Your setup.txt filename has two .. in it. If you look you will see it is `setup..txt`

**Comment by metzo007** [comment]
> Your setup.txt filename has two .. in it. If you look you will see it is `setup..txt`

Sorry for wasting you time. tanks :-)
