### ISSUE TITLE
[Feature Request]: stable video diffusion

### ISSUE THREAD

**Issue by bamtheboozle** [lllyasviel/Fooocus#2706]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

is it possible to integrate stable video diffusion into fooocus?

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by mashb1t** [comment]
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1031, also see https://github.com/lllyasviel/Fooocus/discussions/390#discussioncomment-9011639
