### ISSUE TITLE
[Bug]:  Starting the app on MAC, request torch==2.1.0 but not found

### ISSUE THREAD

**Issue by urostrickovic** [lllyasviel/Fooocus#2719]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When installing Fooocus on Mac  Silicon and trying to start it, conda request instalation of torch 2.1.0 but it says there isn't that version available, only 2.2.0 and + versions.
When changing code it needs torchvision==0.16.0 but that is also not available, the next recomended is 0.17.0 but when you edit that code, it shows another error and so on. 

### Steps to reproduce the problem

Install Fooocus on mac silicon.
Try to open it and there is an error.

### What should have happened?

It should open normally and work.

### What browsers do you use to access Fooocus?

Other

### Where are you running Fooocus?

Locally

### What operating system are you using?

Mac OS

### Console logs

```Shell
Don't have it. It was on another pc.
```

**Comment by mashb1t** [comment]
Please provide the console logs fur further debugging.
Also keep in mind that Apple Silicon is not extensively tested, see https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#mac.

**Comment by Cochonfou** [comment]
If you follow the guides:
https://github.com/lllyasviel/Fooocus?tab=readme-ov-file
https://developer.apple.com/metal/pytorch/
This will install pytorch 2.3.0 and torchvision 1.8.0 with conda prior to installing fooocus.
It works fine with the current version of fooocus.
