### ISSUE TITLE
怎么使用api去下载图片

### ISSUE THREAD

**Issue by StartHua** [lllyasviel/Fooocus#272]
生成图片后使用api去获取图片怎么做？

**Comment by myopenresources** [comment]
> 生成图片后使用api去获取图片怎么做？
改源代码

**Comment by shirubei** [comment]
http://127.0.0.1:7860/  网页左下角use via API

**Comment by mashb1t** [comment]
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/287
