### ISSUE TITLE
Any change to support SD 1.5?

### ISSUE THREAD

**Issue by maxchiron** [lllyasviel/Fooocus#273]
### Thanks again~

**Comment by tamal777** [comment]
so dose it support SD 1.5?

**Comment by roseyyy2022ai** [comment]
Yeah I'm also hoping they'll add support for 1.5 models as base, and also support for ControlNet and AfterDetailer

**Comment by mashb1t** [comment]
There are currently no plans to support SD 1.5 base models. You can still use this workaround:

1. use SDXL model as base model
2. use SD 1.5 model as refiner
3. switch at 0.1 (as early as possible)

This allows you to use all SD 1.5 models in Fooocus!
Hope this helped!

**Comment by Mobian2388329** [comment]
Unfortunately using SD 1.5 as a refiner doesn't work for me. SD 1.5 and 2.0 support is critical for my work. I will have to give up fooocus because of the lack of SD 1.5 support. With fooocus I cannot get the output image I need.

**Comment by mashb1t** [comment]
Sad to hear it's not a fit for you.
I can highly recomment https://github.com/comfyanonymous/ComfyUI and https://github.com/AUTOMATIC1111/stable-diffusion-webui, both excellent tools for SD 1.5, while not being as easy to use as Fooocus.

**Comment by Mobian2388329** [comment]
I like fooocus, but the lack of SD 1.5 support deprives me of all the advantages your interface offers.

**Comment by Mobian2388329** [comment]
The models I'm using don't make SDXL versions.

**Comment by Mobian2388329** [comment]
Is there anything that can be done about this? For example add the ability to cross and transfer weights like in automatic1111 or add a new mode for rafiner to be able to use the SD 1.5 rafiner control point like Lora?
