### ISSUE TITLE
[Feature Request]:  feature to include controlnet in fooocus

### ISSUE THREAD

**Issue by ratnashakya** [lllyasviel/Fooocus#2745]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

apply controlnet to image for using controlnet models in fooocus

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by mashb1t** [comment]
Four ControlNet models are already implemented. Please find them in Image Input > Advanced.

**Comment by kienerj** [comment]
Are there any plans to integrate [Fooocus-ControlNet-SDXL](https://github.com/fenneishi/Fooocus-ControlNet-SDXL)? Because that gives so many more possibilities but since it's just a fork it is not really maintained anymore,

**Comment by mashb1t** [comment]
@kienerj this fork is, as you've already mentioned, not maintained anymore since 6 months. I'd steongly assume that it would need quite a bit of refactoring to make the changes compatible again.
=> currently this is not planned
