### ISSUE TITLE
[Feature Request]: Automatically create folders

### ISSUE THREAD

**Issue by fevolq** [lllyasviel/Fooocus#2746]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

![image](https://github.com/lllyasviel/Fooocus/assets/49370176/e7ce18f8-3e63-4ffd-963b-e154fd0395b9)
If the path configured in config.txt does not exist, automatically create the corresponding folder instead of using the default path, e.g., ../models/embeddings/. 
Otherwise,
1. It may give the illusion that the configuration in config.txt is ineffective.
2. When starting based on Docker and if mounting is required, all folders need to be pre-created on the host machine.

### Proposed workflow

By default, automatic creation can be enabled.
Alternatively, use an environment variable to control whether automatic creation is enabled or not.

**Comment by xynydev** [comment]
I ran into the issue where it seemed like I had to manually create the folders with Docker. Using instead of a bind mount a volume, as is suggested by the documentation, the issue disappeared.

**Comment by fevolq** [comment]
If you only created the `models` folder on the host and mounted it (e.g.  `-v ${PATH}/models:/app/data/models`), then only the `checkpoints` and `loras` folders will exist within the `models` folder. Other folders under `/app/data/models` (such as `embeddings`) will not be present in `${PATH}/models`.
