### ISSUE TITLE
Specify GPU

### ISSUE THREAD

**Issue by sfingali** [lllyasviel/Fooocus#275]
I have a 2 GPU setup. Would be great to be able to select GPU in the gui so I can run separate instances.

**Comment by cgwyx** [comment]
use my fooocus docker --gpus \"device=1\"

docker run -it --name fooocus --gpus \"device=1\" --network host /\
-p 7860:7860 /\
-v /mnt/p1/diffusion/Fooocusdocker:/Fooocus /\
cgwyx/fooocus:cuda118-xformers \
bash

**Comment by KneeHaw** [comment]
if launching from terminal and is controlled by CUDA, 
CUDA_VISIBLE_DEVICES=n (where n belongs to [0, 1] for 2 GPU setup) can used as a command preceding the fooocus launch.
This limits code therafter to see only the desired device.

I often use this on a 4 GPU machine, and it works like a charm for various python applications :)
