### ISSUE TITLE
[Feature Request]:  request to add feature to load model form other folders as in comfyui

### ISSUE THREAD

**Issue by Robot12r** [lllyasviel/Fooocus#2755]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

the feature is actually provided in comfyui, like it has file named extra_model_paths.yaml that loads checkpoints of other ui 
the below is the inside of the file :
#Rename this to extra_model_paths.yaml and ComfyUI will load it

fooocus:
    base_path: C:\Users\s\Compressed\Fooocus_win64_2-1-831_1\Fooocus\

    checkpoints: models/checkpoints
    configs: models/configs
    vae: models/vae
    loras: |
         models/loras/
         models/LyCORIS
    upscale_models: |
                  models/ESRGAN
                  models/RealESRGAN
                  models/SwinIR
    embeddings: embeddings
    hypernetworks: models/hypernetworks
    controlnet: models/controlnet
    clip_vision: models/clip_vision
    prompt_expansion: models/prompt_expansion
#config for comfyui
#your base path should be either an existing comfy install or a central folder where you store all of your models, loras, etc.

#comfyui:
#     base_path: C:\Users\s\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\comfyui
#     checkpoints: models/checkpoints/
#     clip: models/clip/
#     clip_vision: models/clip_vision/
#     configs: models/configs/
#     controlnet: models/controlnet/
#     embeddings: models/embeddings/
#     loras: models/loras/
#     upscale_models: models/upscale_models/
#     vae: models/vae/

#other_ui:
#    base_path: path/to/ui
#    checkpoints: models/checkpoints
#    gligen: models/gligen
#    custom_nodes: path/custom_nodes
#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
#a111:

### Proposed workflow

1. Go to ....  
2. Press ....
3. ...
 I dont have workflow:

**Comment by mashb1t** [comment]
You can already provide an array of paths for LoRAs and checkpoints to load them from multiple folders, which could also be extended for all other file path settings in the config. Feel free to adjust the code and provide a PR!
