### ISSUE TITLE
[Feature Request]: Eliminate Redundant "Drag inpaint" Label

### ISSUE THREAD

**Issue by mashb1t** [lllyasviel/Fooocus#2763]
### Discussed in https://github.com/lllyasviel/Fooocus/discussions/2757

<div type='discussions-op-text'>

<sup>Originally posted by **DavidDragonsage** April 14, 2024</sup>
My wife has poor near vision and typically operates Firefox at about 150% enlargement, using a Display Resolution of 1920x1080 pixels. As shown in the first image, the label in the top left of the Inpainting canvas takes up a very small but sometimes very significant part of the image, and for no particular reason.

The Inpainting label says, "Drag inpaint or outpaint image to here", and there is currently no way to hide the label. As seen in the second image, this label is in any case completely redundant, because the Inpainting canvas displays a large message, "Drop Image Here - or - Click to Upload". In fact, the Image Prompt canvases currently only display that message, without the use of an additional label.

In the case of this example, the moon was Inpainted into the sky (I setup this demo on my computer, not my wife's). This did not require high precision Inpainting, but nonetheless it was very easy to miss a spot at the edge of the screen. In fact, a spot that was not hidden by the label was initially missed by the Inpainting brush, but of course it was easy to see that this was the case.

There are times when Inpainting does require fine control, and that may occur anywhere on the canvas. It is possible that the tools in the top right corner of the canvas could hide some things, but because each tool occupies such a small area - with visible canvas space around it - they have not proven to be a problem.

The third image shows the label reduced to a very small size with a small change to the webui.py file. The fourth image shows no label at all. With either option, the label no longer interferes with the canvas in any way. I would like to create a PR for this change.

![Inpainting with Full Label](https://github.com/lllyasviel/Fooocus/assets/162500231/3cd86404-d0ca-4478-b09c-54003c7c4bda)
![Inpaint Drop Image Here](https://github.com/lllyasviel/Fooocus/assets/162500231/bdac0ab9-bb37-43a0-97b1-097b222c4468)
![Inpainting with Reduced Label](https://github.com/lllyasviel/Fooocus/assets/162500231/b86f233a-854d-4b55-940e-a6bdd56ff282)
![Inpainting with No Label](https://github.com/lllyasviel/Fooocus/assets/162500231/35218d17-6d4e-4531-a43a-2c2e33366814)
</div>

**Comment by mashb1t** [comment]
@DavidDragonsage this is going to be re-evaluated soon, thanks for the input.

**Comment by DavidDragonsage** [comment]
Well that sounds intriguing! I look forward to future developments. 🙂

**Comment by xhoxye** [comment]
A temporary change can be made by modifying this file, https://github.com/lllyasviel/Fooocus/blob/main/language/en123.json
`    "Drag inpaint or outpaint image to here": "123",
.\python_embeded\python.exe -s Fooocus\launch.py --language en123 %*`
![QQ截图20240521083143](https://github.com/lllyasviel/Fooocus/assets/129571231/e33c6fd6-9cb5-4bb2-b7fd-d9a47806fc2e)

**Comment by DavidDragonsage** [comment]
I would rather have no label at all, as shown in my fourth image. It just requires a small change to the webui.py file, which I am prepared to do with a PR. However, I suspect that mashb1t may have some bigger plans for the Inpainting interface.

**Comment by DavidDragonsage** [comment]
Thank you, my wife and I will really appreciate this change! 🙂🙂👍
