### ISSUE TITLE
Issue with Style Misalignment

### ISSUE THREAD

**Issue by kingyoolee** [lllyasviel/Fooocus#277]
I tested all the styles and found that the styles towards the end are all off by one position. I started noticing something was amiss around the horror style, and by the monochrome style, it's very apparent that there's a one-position error. I hope this issue can be corrected in the upgraded version. Thank you for your efforts, which have given us such a useful software!

**Comment by mashb1t** [comment]
Thank you for reporting the issue. This luckily has been fixed quite a while ago. 
A few (many) more things changed since you reported the issue, feel free to check out the latest vesion of Fooocus.
Your feedback is always welcome!
