### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by ShivaeAI** [lllyasviel/Fooocus#2774]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

SD3 api access to facilitate the use of that better model

### Proposed workflow

SD3 api access to facilitate the use of that better model

### Additional information

SD3 api access to facilitate the use of that better model

**Comment by mashb1t** [comment]
Fooocus is a free open-source tool running on local environments with privacy in mind.
The SD3 API is paid and not open-source, data privacy can't be guaranteed and almost all functions of Fooocus' pipeline are incompatible with external API calls.
Closing as won't do. Please stay tuned for the official model weight release of SD3.
