### ISSUE TITLE
[Bug]: Selected styles reset after describing an image

### ISSUE THREAD

**Issue by ustas-eth** [lllyasviel/Fooocus#2780]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When I describe an image to get a prompt, my selected styles are reset and I have to set them again, which is often inconvenient.

### Steps to reproduce the problem

1. Run Fooocus with any settings
2. Select random styles
3. Describe an image

### What should have happened?

The selected styles will reset to the default ones.

### What browsers do you use to access Fooocus?

Mozilla Firefox

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 10

### Console logs

```Shell
Will be provided if needed
```

**Comment by mashb1t** [comment]
This is intended and depending on which mode you've used when describing the image, see https://github.com/lllyasviel/Fooocus/blob/main/webui.py#L696 and below.

**Comment by mashb1t** [comment]
Checked the implementation again and it seems reasonable to have a checkbox. Implemented in https://github.com/lllyasviel/Fooocus/pull/3430
