### ISSUE TITLE
Feature Request: Image-to-image

### ISSUE THREAD

**Issue by etha302** [lllyasviel/Fooocus#279]
Hello,

I would like to request image-to-image feature to be added, i really like fooocus. But it would be amazing if just basic image to image support would be added

**Comment by li-qishan** [comment]
Support!

**Comment by barepixels** [comment]
this fork have img2img https://github.com/MoonRide303/Fooocus-MRE

**Comment by etha302** [comment]
> this fork have img2img https://github.com/MoonRide303/Fooocus-MRE

thanks allot, downloading right now. will report back

**Comment by hzeasy** [comment]
> 这个叉子有img2img https://github.com/MoonRide303/Fooocus-MRE
This is a nice change, already in use, thanks for sharing. But some of these functions are not well understood. For example, the principle of (Scheduler) selection is not very clear to me. Hope to have a help document.

**Comment by MoonRide303** [comment]
@hzeasy Sampler and scheduler selection determine how diffusion model will use to turn noise into final image. You can read a bit more about in [Stable Diffusion Samplers: A Comprehensive Guide](https://stable-diffusion-art.com/samplers/) article. There is no single combination that always gives best result for given combination of prompts, seed, and steps (and 2 different people may have different definitions of "best result", too), so sometimes I just play with sampling parameters, and compare the outputs. If you want to take a look at imags generated using different samplers and schedulers available in MRE, you can check out [Samplers](https://github.com/MoonRide303/Fooocus-MRE/wiki/Samplers) and [Schedulers](https://github.com/MoonRide303/Fooocus-MRE/wiki/Schedulers) pages in MRE wiki.

@lllyasviel picked solid sampler and scheduler as the defaults in vanilla Fooous, and I kept those in MRE, as well - so if you don't feel like experimenting, you can just stick to those defaults.

**Comment by mashb1t** [comment]
This luckily has been implemented quite a while ago.
A few (many) more things changed since you reported the issue, feel free to check out the latest vesion of Fooocus.
Your feedback is always welcome!
