### ISSUE TITLE
[Feature Request]: Random Style Button

### ISSUE THREAD

**Issue by epicalxyz** [lllyasviel/Fooocus#2795]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Press a button and have it select a random style or styles to be applied to the prompt. 

### Proposed workflow

1. Go to Styles tab
2. Press Random button at the top
3. Images get generated with random styles

**Comment by mashb1t** [comment]
@epicalxyz implemented in https://github.com/lllyasviel/Fooocus/pull/2855, happy to hear your feedback!

**Comment by mashb1t** [comment]
merged to develop
