### ISSUE TITLE
[Bug]: Fooocus not working

### ISSUE THREAD

**Issue by igninjaz** [lllyasviel/Fooocus#2798]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

![ss](https://github.com/lllyasviel/Fooocus/assets/157118183/1e0aa779-8a2b-4c77-bc49-2838dcc56239)

please help.

### Steps to reproduce the problem

not working

### What should have happened?

not working

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

None

### Console logs

```Shell
/
```

**Comment by AnimeDalit97** [comment]
seems like a network issue, did you try to config the proxy or download it directly from https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth and put it at the `/content/....` path showed in your log?

**Comment by mashb1t** [comment]
@igninjaz HF might just have been down at the time, which happens sometime. Please check and try again.
