### ISSUE TITLE
[Feature Request]: ip-adapter update,style and composition are referenced separately

### ISSUE THREAD

**Issue by xhoxye** [lllyasviel/Fooocus#2800]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Solve the leakage of style and composition in the image prompt, separate them, and choose to refer to only one or both at the same time

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

### Additional information

https://github.com/lllyasviel/Fooocus/discussions/2709
https://github.com/InstantStyle/InstantStyle
https://github.com/cubiq/ComfyUI_IPAdapter_plus
https://github.com/Mikubill/sd-webui-controlnet/discussions/2770
https://github.com/Mikubill/sd-webui-controlnet/discussions/2781

**Comment by mashb1t** [comment]
@xhoxye thanks for reporting, but @ismailhabib was faster in https://github.com/lllyasviel/Fooocus/issues/2648.
I'll check out how to implement it when there's time, but currently I'm pretty busy, sorry 😐
