### ISSUE TITLE
[Feature Request]: Save the settings you have used locally？

### ISSUE THREAD

**Issue by istingbiao** [lllyasviel/Fooocus#2808]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Sometimes the computer crashes and you need to recall the last settings

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by mashb1t** [comment]
You can recover from the crash my doing either of the following things:
- create a customized preset
- activate metadata, load everything from the last generated image again (except image prompts)
- wait for https://github.com/lllyasviel/Fooocus/issues/1622 to be implenented (no ETA/release planned)
