### ISSUE TITLE
[Bug]: Inpainting always moves models despite using --always-gpu and --disable-offload-from-vram

### ISSUE THREAD

**Issue by user425846** [lllyasviel/Fooocus#2811]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Whenever i run an inpainting task, it always has to load and move models which takes more than 30 seconds in total, for a single inpainting task. Despite using the mentioned parameters, it does not keep the models loaded.

### Steps to reproduce the problem

1. Follow the install instructions on github
2. Run inpainting

### What should have happened?

With using the mentioned parameters i expected Fooocus to keep the models loaded to not take 15 seconds every single time to load and move models.

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (other)

### What operating system are you using?

Ubuntu

### Console logs

```Shell
python entry_with_update.py --disable-offload-from-vram --always-gpu --share
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--disable-offload-from-vram', '--always-gpu', '--share']
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Fooocus version: 2.3.1
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Total VRAM 48647 MB, total RAM 1547821 MB
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA RTX 6000 Ada Generation : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7865
model_type EPS
UNet ADM Dimension 2816
Running on public URL: https://11841329bc7fad2627.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
loaded straight to GPU
Requested to load SDXL
Loading 1 new model
Base model loaded: /workspace/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/workspace/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [/workspace/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/workspace/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 2.23 seconds
Started worker with PID 1175
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865 or https://11841329bc7fad2627.gradio.live
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 6703923305498849412
[Fooocus] Downloading upscale models ...
[Fooocus] Downloading inpainter ...
[Inpaint] Current inpaint model is /workspace/Fooocus/models/inpaint/inpaint_v26.fooocus.patch
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 24
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Synthetic Refiner Activated
Synthetic Refiner Activated
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0], ('/workspace/Fooocus/models/inpaint/inpaint_v26.fooocus.patch', 1.0)] for model [/workspace/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [/workspace/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/workspace/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Loaded LoRA [/workspace/Fooocus/models/inpaint/inpaint_v26.fooocus.patch] for UNet [/workspace/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors] with 960 keys at weight 1.0.
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/workspace/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [/workspace/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/workspace/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Requested to load SDXLClipModel
Loading 1 new model
unload clone 1
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] a cat, intricate, elegant, highly detailed, wonderful quality, perfect light, glowing, sharp focus, beautiful, coherent, cute, artistic, expressive, color spread, clear, nice, lovely, creative, delicate, friendly, pretty, background, ambient, focused, charming, professional, best, fair, true colors, shining, loving, symmetry, illuminated, attractive
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] a cat, deep focus, beautiful, highly detailed, very intricate, dramatic light, illuminated background, ambient cinematic, rich colors, perfect, sharp, romantic, cute, artistic, expressive, symmetry, striking, iconic, fine, innocent, enhanced, colorful, best, creative, positive, unique, attractive, elegant,, pure, color, inspired, vibrant, loving
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Fooocus] Image processing ...
Upscaling image with shape (313, 313, 3) ...
[Fooocus] VAE Inpaint encoding ...
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.11 seconds
[Fooocus] VAE encoding ...
Final resolution is (1365, 768), latent is (1024, 1024).
[Parameters] Denoising Strength = 1
[Parameters] Initial Latent shape: Image Space (1024, 1024)
Preparation time: 7.94 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
unload clone 3
[Fooocus Model Management] Moving model(s) has taken 13.08 seconds
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 24/30 [00:03<00:00,  6.02it/s]Requested to load SDXL
Loading 1 new model
unload clone 0
[Fooocus Model Management] Moving model(s) has taken 0.21 seconds
Refiner Swapped
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.91it/s]
Image generated with private log at: /workspace/Fooocus/outputs/2024-04-25/log.html
Generating and saving time: 18.78 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
unload clone 1
[Fooocus Model Management] Moving model(s) has taken 17.13 seconds
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 24/30 [00:03<00:00,  7.15it/s]Requested to load SDXL
Loading 1 new model
unload clone 0
[Fooocus Model Management] Moving model(s) has taken 0.24 seconds
Refiner Swapped
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.06it/s]
Image generated with private log at: /workspace/Fooocus/outputs/2024-04-25/log.html
Generating and saving time: 22.69 seconds
Total time: 49.49 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 6343848598120094344
[Fooocus] Downloading upscale models ...
[Fooocus] Downloading inpainter ...
[Inpaint] Current inpaint model is /workspace/Fooocus/models/inpaint/inpaint_v26.fooocus.patch
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 24
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Synthetic Refiner Activated
Synthetic Refiner Activated
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/workspace/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [/workspace/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/workspace/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] a cat, intricate, elegant, highly detailed, wonderful colors, glowing, sharp focus, beautiful light, expressive, cute, symmetry, illuminated deep background, thought, cinematic, complex, color, clear, crisp, complimentary, vibrant, original, fine detail, enhanced, colorful, shiny, attractive, epic, best, artistic, hopeful, unique, charming, creative, positive
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Image processing ...
Upscaling image with shape (313, 313, 3) ...
[Fooocus] VAE Inpaint encoding ...
[Fooocus] VAE encoding ...
Final resolution is (1365, 768), latent is (1024, 1024).
[Parameters] Denoising Strength = 1
[Parameters] Initial Latent shape: Image Space (1024, 1024)
Preparation time: 5.98 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
unload clone 3
[Fooocus Model Management] Moving model(s) has taken 15.66 seconds
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 24/30 [00:03<00:00,  6.30it/s]Requested to load SDXL
Loading 1 new model
unload clone 0
[Fooocus Model Management] Moving model(s) has taken 0.21 seconds
Refiner Swapped
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.81it/s]
Image generated with private log at: /workspace/Fooocus/outputs/2024-04-25/log.html
Generating and saving time: 21.33 seconds
Total time: 27.36 seconds
```

**Comment by user425846** [comment]
I did some more testing.

Changing the code i mentioned above to this quick workaround:

>     for index, item in enumerate(current_loaded_models):
>         if item.model ==  loaded_model.model:
>             print("DEBUG: Found Model at index " + str(index)+": " + item.model.__class__.__name__)
>             break;
>     else:
>         index = -1
>     if index != -1:
>         current_loaded_models.insert(0, current_loaded_models.pop(index))
>         models_already_loaded.append(loaded_model)
>     else:
>         if hasattr(x, "model"):
>             print(f"Requested to load {x.model.__class__.__name__}")
>             models_to_load.append(loaded_model)

works, it finds the model. HOWEVER: The model is still a clone, so it is being unloaded. I can prevent the unloading of clones by just commenting out the unloading in the unload_model_clones method, then it actually works, it doesnt reload the model.

BUT: then i get some artifacting in the image. I have attached an image without this modification and with the modification. It almost seems like somehow the refiner is not run for the last few steps but im not 100% sure.
![IMG_9195](https://github.com/lllyasviel/Fooocus/assets/100499696/48921fb1-a183-455e-a6e5-bb4484740ab3)
![IMG_9196](https://github.com/lllyasviel/Fooocus/assets/100499696/b006f823-c922-4c19-add9-a7793c4e95ce)

**Comment by user425846** [comment]
Anyone has any idea how to make progress on this? Im willing to help of course, i just need direction on what causes this as im not too familiar with python

**Comment by user425846** [comment]
@lllyasviel would you be able to check out this issue? It would help me a lot, thank you

**Comment by 862345563456234654** [comment]
Willing to pay 300$ btc for anyone to fix this

**Comment by mashb1t** [comment]
@user425846 @862345563456234654 
This is not (necessarily) a bug, but a feature!

reason 1: see LoRA offloading "issue" (flexibility > having to merge LoRA with unet in pretraining) https://github.com/lllyasviel/Fooocus/issues/2311 (most likely not the case here, same for CLIP)
tested by not using any LoRA

reason 2: input_block_patch for each inpaint task, see 
https://github.com/lllyasviel/Fooocus/blob/80068a0cd729d6148ac533bf844e1247a0baa9b4/modules/inpaint_worker.py#L215-L216 (also not the issue here, as patch is necessary for each task)
tested with 
```
        # m = model.clone()
        model.set_model_input_block_patch(input_block_patch)
```

reason 3 (the real reason): synthetic refiner
https://github.com/lllyasviel/Fooocus/blob/57a01865b99e3334fc83da25adc48ab989d853ab/modules/default_pipeline.py#L231
https://github.com/lllyasviel/Fooocus/blob/0db3c10c604930001a07208b612a589e0b7c958f/modules/async_worker.py#L362
Set `use_synthetic_refiner = False` to prevent creation of clones / offloading.

This will limit you if you have the need to use refiners as well as when using face swap / other IP adapters, but if you don't need this you're good to go!

@862345563456234654 if you really want to donate something, feel free to use the PayPal link in my profile, but you're not required to.

**Comment by user425846** [comment]
Hi Manuel, danke, dass du hier mal reinschaust!

This is what i tried:

1. Setting `use_synthetic_refiner = False` at line 362 -> Did not stop the `Synthetic Refiner Activated` from showing up in the logs.

2. Even setting it directly in the call at line 429 did not stop it from showing up

3. Commenting out this code:

> #if use_synthetic_refiner and refiner_model_name == 'None':
>     #    print('Synthetic Refiner Activated')
>     #    refresh_base_model(base_model_name)
>     #    synthesize_refiner_model()
>     #else:
>     refresh_refiner_model(refiner_model_name)
>     refresh_base_model(base_model_name) 

did stop the synthetic refiner from showing up in the logs, it now says `Refiner unloaded.` in the log, but it still reloads the model every time. Full log below

> [2024-05-03 07:17:19] INFO     [Task Queue] Waiting for task finished, job_id=62be56fe-e233-454c-a7bf-568d4461e21b
> [2024-05-03 07:17:19] INFO     [Task Queue] Task queue start task, job_id=62be56fe-e233-454c-a7bf-568d4461e21b
> [2024-05-03 07:17:19] INFO     [Parameters] Adaptive CFG = 7.0
> [2024-05-03 07:17:19] INFO     [Parameters] Sharpness = 2.0
> [2024-05-03 07:17:19] INFO     [Parameters] ControlNet Softness = 0.25
> [2024-05-03 07:17:19] INFO     [Parameters] ADM Scale = 1.5 : 0.8 : 0.3
> [2024-05-03 07:17:19] INFO     [Parameters] CFG = 4.0
> [2024-05-03 07:17:19] INFO     [Parameters] Seed = 595246328180572295
> [2024-05-03 07:17:19] INFO     [Fooocus] Downloading upscale models ...
> [2024-05-03 07:17:19] INFO     [Fooocus] Downloading inpainter ...
> [2024-05-03 07:17:19] INFO     [Inpaint] Current inpaint model is /workspace/Fooocus-API/repositories/Fooocus/models/inpaint/inpaint_v26.fooocus.patch
> [2024-05-03 07:17:19] INFO     [Fooocus] Downloading control models ...
> [2024-05-03 07:17:19] INFO     [Fooocus] Loading control models ...
> [2024-05-03 07:17:19] INFO     [Parameters] Sampler = dpmpp_2m_sde_gpu - karras
> [2024-05-03 07:17:19] INFO     [Parameters] Steps = 30 - 24
> [2024-05-03 07:17:19] INFO     [Fooocus] Initializing ...
> [2024-05-03 07:17:19] INFO     [Fooocus] Loading models ...
> Refiner unloaded.
> [2024-05-03 07:17:19] INFO     [Fooocus] Processing prompts ...
> [2024-05-03 07:17:19] INFO     [Fooocus] Encoding positive #1 ...
> [2024-05-03 07:17:20] INFO     [Fooocus] Encoding negative #1 ...
> [2024-05-03 07:17:20] INFO     [Fooocus] Image processing ...
> Upscaling image with shape (469, 456, 3) ...
> [2024-05-03 07:17:22] INFO     [Fooocus] VAE Inpaint encoding ...
> [2024-05-03 07:17:22] INFO     [Fooocus] VAE encoding ...
> [2024-05-03 07:17:22] INFO     [Inpaint] Final resolution is (1024, 1024), latent is (1024, 1024).
> [2024-05-03 07:17:22] INFO     [Parameters] Denoising Strength = 1.0
> [2024-05-03 07:17:22] INFO     [Parameters] Initial Latent shape: Image Space (1024, 1024)
> [2024-05-03 07:17:22] INFO     [Fooocus] Preparation time: 2.65 seconds
> [Sampler] refiner_swap_method = joint
> [Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
> Requested to load SDXL
> Loading 1 new model
> unload clone 3
> [Fooocus Model Management] Moving model(s) has taken 6.35 seconds
>  37%|█████████████████████████████████████████████▊                                                                               | 11/30 [00:01<00:03,  6.18it/s][2024-05-03 07:17:30] INFO     [Task Queue] Already waiting for 10.8 seconds, job_id=62be56fe-e233-454c-a7bf-568d4461e21b
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.36it/s]
> [2024-05-03 07:17:33] INFO     [Fooocus] Generating and saving time: 11.29 seconds
> [2024-05-03 07:17:35] INFO     [Task Queue] Finish task, job_id=62be56fe-e233-454c-a7bf-568d4461e21b

**Comment by user425846** [comment]
I literally was about to comment here another time, asking if i can try anything else, you beat me by a minute :D I will do a full clean install from main branch and try again in a few hours. Thanks a lot!

**Comment by user425846** [comment]
Thank you very much, this can be closed. With a clean install, it works perfectly. The issue is with https://github.com/mrhan1993/Fooocus-API
