### ISSUE TITLE
[Bug]: The system cannot find the path specified.

### ISSUE THREAD

**Issue by Fruelund** [lllyasviel/Fooocus#2828]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Trying to install, getting this:

C:\Windows\System32>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
The system cannot find the path specified.

C:\Windows\System32>pause
Press any key to continue . . .

### Steps to reproduce the problem

Uh, download the zip, extract, run.bat

### What should have happened?

It should install according to the installation guide. 

### Where are you running Fooocus?

None

### What operating system are you using?

Win 11

### Console logs

```Shell
C:\Windows\System32>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
The system cannot find the path specified.

C:\Windows\System32>pause
Press any key to continue . . .
```

**Comment by okiewardoyo** [comment]
don't execute run.batch as Administrator, just doubleclick it.
