### ISSUE TITLE
Great Project! and appeal to sharing models with other UI

### ISSUE THREAD

**Issue by xy185** [lllyasviel/Fooocus#283]
Hi, @lllyasviel 
This project is so Great. I love it very much for it's simplicity and elegance.

Would you like to add the feature that sharing models with other UI?
I've tried to change the path file in the ComfyUI repo folder, well, it does not work  - -!

Fooocus, Comfy and WebUI all have special features, but  the storage of computer is not unlimited  T T

Wish for this feather to share models T T

Anyway, thank you so much for Fooocus!
I, and my friends, love it very much!

**Comment by MoonRide303** [comment]
@xy185 If you need some more options and customizations (like custom paths to model files) you can check out my fork for a bit more advanced users, [Fooocus-MRE](https://github.com/MoonRide303/Fooocus-MRE) - it allows you to set your owns paths via paths.json file (use paths-example.json as a template). It also has few other features, like img2img mode, and additional controls for sampling process.
