### ISSUE TITLE
[Feature Request]: Full prompt shown

### ISSUE THREAD

**Issue by troyau** [lllyasviel/Fooocus#2831]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

After hitting generate it would be nice to show the full prompt (showing wildcards used and added prompts from fooocus style) somewhere on the screen like in A1111.  Would make it much easier than having to go back to find the prompt on the cmd window to copy and paste it to reuse.

### Proposed workflow

1. Hit Generate
2. Show full prompt used
3. ...

**Comment by mashb1t** [comment]
Users who only use the UI casually might not need the information.
You can see the prompt in the console output as well as in the private log and metadata of images (if enabled).
