### ISSUE TITLE
[Bug]: Upscale/Vary doesn't take set Aspect Ratio into account

### ISSUE THREAD

**Issue by Mcpoowl** [lllyasviel/Fooocus#2837]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When using an existing image, and using Fooocus to create a variation of it, by selecting 'Vary (Subtle) from the options under Input Image, I noticed that the generated image has the same resolution as the input image, so the actual selected aspect ratio in Fooocus is ignored.

Example.
Input image is of resolution 816 x 1456
Selected Aspect ratio in Fooocus is 768x1024 (3:4)

Varied / Generated image comes out at resolution 816x1456

![image](https://github.com/lllyasviel/Fooocus/assets/2244753/496af154-2ca5-4a6d-94da-25a9f92b9553)
![image](https://github.com/lllyasviel/Fooocus/assets/2244753/f1795708-be91-410c-a516-206466c6ad8c)
![image](https://github.com/lllyasviel/Fooocus/assets/2244753/5589cac6-689f-44d8-8087-777d3be8bb76)

### Steps to reproduce the problem

1. Get an image from the web with a specific resolution
2. Upload it to Fooocus in the Upscale or Variation Tab
3. Select Vary (Subtle) as option
4. Select a different Aspect Ratio in the Fooocus options
5. Press Generate

Notice that the generated image has the same resolution as the downloaded image, as opposed to the set aspect ratio in the Fooocus options

### What should have happened?

Fooocus should have generated a variation of the image in the set aspect resolution

### What browsers do you use to access Fooocus?

Google Chrome, Brave

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
[Fooocus] Processing prompts ...
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.33 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Fooocus] Image processing ...
[Fooocus] VAE encoding ...
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 2.19 seconds
Final resolution is (1456, 816).
[Parameters] Denoising Strength = 0.5
[Parameters] Initial Latent shape: torch.Size([1, 4, 182, 102])
Preparation time: 3.95 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 1.2431749105453491
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 2.02 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 60/60 [00:45<00:00,  1.32it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.21 seconds
Image generated with private log at: D:\Fooocus\Fooocus\outputs\2024-04-30\log.html
Generating and saving time: 49.99 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 1.2431749105453491
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.51 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 60/60 [00:47<00:00,  1.26it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.19 seconds
Image generated with private log at: D:\Fooocus\Fooocus\outputs\2024-04-30\log.html
Generating and saving time: 51.42 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Total time: 105.44 seconds
[Fooocus Model Management] Moving model(s) has taken 0.72 seconds
```

**Comment by IPv6** [comment]
The whole point of this Vary/Upscale is just change the image provided. Especially do not change dimensions at all in unpredictable way. The same with inpaint

**Comment by mashb1t** [comment]
Hey @Mcpoowl,
this is indeed the intended behaviour, same also for inpainting, as the source material is used as basis for dimensions.
This prevents unintended deformation and cropping by uneducated users and streamlines the workflow.
I hope it's understandable why it's implemented that way and won't be changed.

**Comment by Mcpoowl** [comment]
Thanks @IPv6 and @mashb1t for the explanation. Makes perfect sense!
