### ISSUE TITLE
[Bug]: Unable to generate url link again

### ISSUE THREAD

**Issue by igninjaz** [lllyasviel/Fooocus#2839]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

again having the same issue.

### Steps to reproduce the problem

unable to generate gradio link

### What should have happened?

.

### Where are you running Fooocus?

None

### Console logs

```Shell
.
```

**Comment by gh-aam** [comment]
I'm also having this same problem in Colab.

**Comment by KirtiKousik** [comment]
gradio share api was down. https://status.gradio.app/793595965

**Comment by KirtiKousik** [comment]
you can try this code.

!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

put this before your main colab code

**Comment by gh-aam** [comment]
> you can try this code.
> 
> !wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb !dpkg -i cloudflared-linux-amd64.deb
> 
> put this before your main colab code

Hi, thanks for the suggestion!

I'm not sure if it's working or not as Gradio Share API is running again. I tried without (at first attempt, official code) and with (at second attempt, your suggested code) your method, both working though. Maybe you are right, cause someday I've noticed something (I can't remember exactly) like, "Can't download. Maybe your firewall has blocked it..... ."

My question is, "Will this method work while Gradio Share API is down?"

**Comment by mashb1t** [comment]
@gh-aam if you're referring to https://github.com/lllyasviel/Fooocus/issues/2815#issuecomment-2080369259, this can be mitigated by switching to cloudflared  or at least doesn't have critical impact.

**Comment by KirtiKousik** [comment]
> > you can try this code.
> > !wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb !dpkg -i cloudflared-linux-amd64.deb
> > put this before your main colab code
> 
> Hi, thanks for the suggestion!
> 
> I'm not sure if it's working or not as Gradio Share API is running again. I tried without (at first attempt, official code) and with (at second attempt, your suggested code) your method, both working though. Maybe you are right, cause someday I've noticed something (I can't remember exactly) like, "Can't download. Maybe your firewall has blocked it..... ."
> 
> My question is, "Will this method work while Gradio Share API is down?"

Sometimes you won't get the Gradio share link even if the share API is running, This code can help in those cases. But if the share API is down, it probably won't work.

**Comment by Arjun91221** [comment]
@KirtiKousik I tried your code. Still, Gradio link is not generating. 
The share API is NOT down. The time is 15:40 PM IST 02 May 2024

**Comment by Arjun91221** [comment]
@mashb1t Suggest the solution plz...NOT working

**Comment by gh-aam** [comment]
@Arjun91221 , here is a [Ngrok](https://ngrok.com) based working solution. Hope it will work even if the Gradio Share API is down (not sure though, I've to test it while Gradio Share API is down).

```
!pip install pygit2==1.12.2 pyngrok

%cd /content
!git clone https://github.com/lllyasviel/Fooocus.git

from pyngrok import ngrok, conf
ngrok_token = "ENTER_NGROK_AUTHTOKEN"
print(ngrok.connect(7865, pyngrok_config=conf.PyngrokConfig(auth_token=ngrok_token), bind_tls=True).public_url)

%cd /content/Fooocus
!python entry_with_update.py --always-high-vram
```

Replace "ENTER_NGROK_AUTHTOKEN" with your own Ngrok token. Get one from https://ngrok.com . It will generate and print a public URL before executing the last two lines. When you see "App started successful. ........", open the public URL.

If your Ngrok authtoken isn't working, delete the Ngrok account and register a new Ngrok account with the same Email.

**Comment by gh-aam** [comment]
Here is another solution based on @mashb1t 's comment (sometimes you will find this solution approach in Colab's output). Not sure about this, I've to test it while Gradio Share API is down.

```
%cd /usr/local/lib/python3.10/dist-packages/gradio
!wget -O frpc_linux_amd64_v0.2 https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
```

Insert this code cell after Fooocus's official Colab's code cell. Execute the official Fooocus cell first. Only run this new cell if you see "App started successful. ........" line without any Gradio URL. You have to stop executing official Fooocus cell before executing this new cell.

**Comment by Arjun91221** [comment]
@gh-aam Thanks a lot! You solved a problem for everyone who suffer. It's working using ngrok. Could you share your email here ?

**Comment by gh-aam** [comment]
> @gh-aam Thanks a lot! You solved a problem for everyone who suffer. It's working using ngrok. Could you share your email here ?

Most welcome! Sure, here is my email "rglr2.aam@gmail.com" . Sometimes I forget to check email 😁😁.

**Comment by gh-aam** [comment]
> Here is another solution based on @mashb1t 's comment (sometimes you will find this solution approach in Colab's output). Not sure about this, I've to test it while Gradio Share API is down.
> 
> ```
> %cd /usr/local/lib/python3.10/dist-packages/gradio
> !wget -O frpc_linux_amd64_v0.2 https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
> ```
> 
> Insert this code cell after Fooocus's official Colab's code cell. Execute the official Fooocus cell first. Only run this new cell if you see "App started successful. ........" line without any Gradio URL. You have to stop executing official Fooocus cell before executing this new cell. After that run the official Fooocus cell again, maybe you will get the Gradio URL.

I've test this solution right now, it doesn't work for me.
