### ISSUE TITLE
Apple M2 Pro 

### ISSUE THREAD

**Issue by Pal-player** [lllyasviel/Fooocus#284]
Apple M2 Pro  Always fail without error
![image](https://github.com/lllyasviel/Fooocus/assets/12964316/3c2f66aa-778a-49c5-8be3-6a1528cc9fbb)

**Comment by aponsin** [comment]
I can't even get it to generate anything...

"Waiting for task to start..."
with an error in the logs:

`To create a public link, set `share=True` in `launch()`.
Total VRAM 131072 MB, total RAM 131072 MB
Set vram state to: SHARED
Disabling smart memory management
Device: mps
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()`

**Comment by mashb1t** [comment]
Please make sure follow the official installation instructions https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#mac and the troubleshooting guide https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md.
You might also be better off using `--always-cpu`.

**Comment by mashb1t** [comment]
closing as stale, feel free to reopen when providing new information
