### ISSUE TITLE
[Bug]: Gradio link not generating in google colab

### ISSUE THREAD

**Issue by juneedpk** [lllyasviel/Fooocus#2844]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

gradio link is not generating when script run in google colab

### Steps to reproduce the problem

run script in google colab

### What should have happened?

gradio link not generating it showing just local host address only

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### Console logs

```Shell
/usr/local/lib/python3.10/dist-packages/gradio/analytics.py:104: UserWarning: unable to parse version details from package URL.
  warnings.warn("unable to parse version details from package URL.")
```

**Comment by produktion9** [comment]
Exact same error

**Comment by IXIXIXIXIXIXIX** [comment]
Yes Gradio was down several times today :  https://status.gradio.app/793595965

**Comment by dedounet** [comment]
what does this have to do with the state of gradio since it's offline?

**Comment by GodFazer** [comment]
working now. check it

**Comment by mashb1t** [comment]
see https://github.com/lllyasviel/Fooocus/issues/2852#issuecomment-2091534293
