### ISSUE TITLE
Hope to add Zluda support code

### ISSUE THREAD

**Issue by Dog-brother0113** [lllyasviel/Fooocus#2853]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

The Zluda project seems to have been quite popular in the field of AI recently, including Comfyui and SD NEXT has provided support for zluda, and I have found a way for Fooocus to utilize zluda from other experts, but it is cumbersome. Therefore, I hope that as creators, will you in the future use a relatively simple way to enable Fooocus to use zluda for AI creation on AMD graphics cards

### Proposed workflow

Add an identifier after the startup program to enable Zuda

**Comment by mashb1t** [comment]
There are no plans to add support for Zluda as DirectML is faster (afaik) and more stable as well as the official implenentation.
If you need it you can find the necessary code vhanges in https://github.com/lllyasviel/Fooocus/discussions/2842

**Comment by f1am3d** [comment]
> There are no plans to add support for Zluda as DirectML is faster (afaik) and more stable as well as the official implenentation. If you need it you can find the necessary code changes in #2842

DirectML is much, much slower than ZLuda on Windows OS.

**Comment by f1am3d** [comment]
> There are no plans to add support for Zluda as DirectML is faster (afaik) and more stable as well as the official implenentation. If you need it you can find the necessary code changes in #2842

No, DirectML is very slow in comparison with Zluda. 

10.2 s/it | 4.3 s/it for speed | lightning presets with DirectML.
5 s/it | 1.2 s/it for same presets with Zluda.

GPU: RX 7900 XTX
