### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by heare01** [lllyasviel/Fooocus#2859]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I tried to start Fooocus on a newly installation and it failed with an segmentation fault

### Steps to reproduce the problem

- installed according to Linux (Using Python Venv)
- Executed: pip uninstall torch torchvision torchaudio torchtext functorch xformers 
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.6
- tried to execute it with: sudo python3 entry_with_update.py --preset realistic --listen (also tried without the preset, then I can open the webgui but as soon as I try to press 'Generate' it fails)
- I have checked the troubleshooting guide and checked my swapfile according to it
(fooocus_env) ubu@ubu-MS-7A32:/media/ubu/Data/Fooocus/Fooocus$ swapon --show
NAME      TYPE SIZE USED PRIO
/swapfile file  50G   0B   -2
- Hope haven't done anything silly

### What should have happened?

I should be able to get the Webgui to generate Images

### Where are you running Fooocus?

Locally

### What operating system are you using?

22.04.1-Ubuntu

### Console logs

```Shell
(fooocus_env) ubu@ubu-MS-7A32:/media/ubu/Data/Fooocus/Fooocus$ sudo python3 entry_with_update.py --preset realistic --listen
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--preset', 'realistic', '--listen']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.3.1
Loaded preset: /media/ubu/Data/Fooocus/Fooocus/presets/realistic.json
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Total VRAM 8192 MB, total RAM 64237 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 AMD Radeon RX 580 Series : native
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --attention-split
Refiner unloaded.
Running on local URL:  http://0.0.0.0:7865

To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: /media/ubu/Data/Fooocus/Fooocus/models/checkpoints/realisticStockPhoto_v20.safetensors
Request to load LoRAs [['SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 0.25], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/media/ubu/Data/Fooocus/Fooocus/models/checkpoints/realisticStockPhoto_v20.safetensors].
Loaded LoRA [/media/ubu/Data/Fooocus/Fooocus/models/loras/SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for UNet [/media/ubu/Data/Fooocus/Fooocus/models/checkpoints/realisticStockPhoto_v20.safetensors] with 788 keys at weight 0.25.
Loaded LoRA [/media/ubu/Data/Fooocus/Fooocus/models/loras/SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for CLIP [/media/ubu/Data/Fooocus/Fooocus/models/checkpoints/realisticStockPhoto_v20.safetensors] with 264 keys at weight 0.25.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Segmentation fault
```

### Additional information

It's a not too long installed OS

**Comment by mashb1t** [comment]
Please check out https://github.com/lllyasviel/Fooocus/issues/1288.
Which CPU are you using?

**Comment by heare01** [comment]
Firstly sorry. I didn't find the duplicate yesterday, maybe wrong filter or I don't know. Tried the solution from there:
(fooocus_env) ubu@ubu-MS-7A32:/media/ubu/Data/Fooocus/Fooocus$ sudo HSA_OVERRIDE_GFX_VERSION=11.0.0 python3 entry_with_update.py 
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.3.1
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Segmentation fault
Still the same error. Here is my CPU and GPU.

ubu@ubu-MS-7A32:~$ cat /proc/cpuinfo  | grep 'name'| uniq
model name      : AMD Ryzen 5 1600X Six-Core Processor


GPU is AMD Radeon  580 X

**Comment by mashb1t** [comment]
I do not have AMD hardware, so I'd assume it would be best to add a comment to https://github.com/lllyasviel/Fooocus/issues/1288 and ask for community support there. Sorry!
