### ISSUE TITLE
Mac M1 generated empty images..

### ISSUE THREAD

**Issue by godlockin** [lllyasviel/Fooocus#286]
I was wondering if I did some mistakes on setup/variable setting? I always got empty images whether the parameters I set

env setup:
![image](https://github.com/lllyasviel/Fooocus/assets/31117750/b86db500-942d-4a39-bdf4-e5268a38aa4d)
![image](https://github.com/lllyasviel/Fooocus/assets/31117750/3b6410e4-6db4-490d-9afc-e7c170c62ac6)
image generate
![image](https://github.com/lllyasviel/Fooocus/assets/31117750/79dca5d0-f722-4312-8f07-47c8bbcadbb3)

results:
![2023-08-29_10-31-21_2039](https://github.com/lllyasviel/Fooocus/assets/31117750/b9aa54a9-ff88-46ff-90ec-37ba950dbedf)
![2023-08-29_10-27-37_9957](https://github.com/lllyasviel/Fooocus/assets/31117750/31b7a197-aec5-43db-aabf-748d7e63dfc8)

parameters:
<img width="1265" alt="image" src="https://github.com/lllyasviel/Fooocus/assets/31117750/a0c6f964-cead-4a67-b36e-c6fc9afbcb9c">

**Comment by yaroslav-ads** [comment]
You just need to restart your computer!
