### ISSUE TITLE
[Bug]: Fooocus can't be started with error message  "OSError: Cannot find empty port in range: 7865-7964"

### ISSUE THREAD

**Issue by fuckemooncoin** [lllyasviel/Fooocus#2866]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When I click run.bat under d:\Fooocus_win64_2-1-831 where fooocus is installed, it returned error

D:\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.3.1
[Cleanup] Attempting to delete content of temp dir C:\Users\blold\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Total VRAM 6144 MB, total RAM 23805 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
Traceback (most recent call last):
  File "D:\Fooocus_win64_2-1-831\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "D:\Fooocus_win64_2-1-831\Fooocus\launch.py", line 136, in <module>
    from webui import *
  File "D:\Fooocus_win64_2-1-831\Fooocus\webui.py", line 716, in <module>
    shared.gradio_root.launch(
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\blocks.py", line 1896, in launch
    ) = networking.start_server(
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\networking.py", line 169, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 7865-7964. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.

then it halts with this message

D:\Fooocus_win64_2-1-831>pause
계속하려면 아무 키나 누르십시오 (Press any key to proceed). . .
Then it is gone.

I checked with CMD and Windows PowerShell command  to search any process or app using the port mentioned in the error message but  found nothing. What is wrong? 
 
![image](https://github.com/lllyasviel/Fooocus/assets/84866643/b8ade0fd-602c-4ae9-b9d2-9fe88a99713b)

The Windows PowerShell command I used to detect any process for the port at the error message is 
PS C:\WINDOWS\system32> Get-NetTCPConnection -State Listen | Where-Object {$_.LocalPort -ge 7800 -and $_.LocalPort -le 7999} | ForEach-Object {Get-Process -Id $_.OwningPid}
PS C:\WINDOWS\system32>

It returned nothing. It worked before but now it doesn't. Can you clear out this issue? 

My system Windows 11pro 23H2 build 22631.3447
CPU AMD Ryzen 7 6800H with Radeon Graphics            3.20 GHz
GPU RTX 3060 6G VRAM 

### Steps to reproduce the problem

1. go to Fooocus root directory 
2. click run,bat 
3. error message comes out. 

### What should have happened?

New version updated couple weeks ago seems to have issues. 

### What browsers do you use to access Fooocus?

Brave

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11  pro  build 22631.3447 

### Console logs

```Shell
D:\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.3.1
[Cleanup] Attempting to delete content of temp dir C:\Users\blold\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Total VRAM 6144 MB, total RAM 23805 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
Traceback (most recent call last):
  File "D:\Fooocus_win64_2-1-831\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "D:\Fooocus_win64_2-1-831\Fooocus\launch.py", line 136, in <module>
    from webui import *
  File "D:\Fooocus_win64_2-1-831\Fooocus\webui.py", line 716, in <module>
    shared.gradio_root.launch(
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\blocks.py", line 1896, in launch
    ) = networking.start_server(
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\networking.py", line 169, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 7865-7964. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.

D:\Fooocus_win64_2-1-831>pause
계속하려면 아무 키나 누르십시오 . . .
```

**Comment by mashb1t** [comment]
Hey @fuckemooncoin,
the port can be set via the env var GRADIO_SERVER_PORT or by using the parameter `--port XXXX` (default error message from Gradio doesn't correctly state this). Please modify the content of the run.bat like this and test again:
`entry_with_update.py --port 7860` (or whichever port you want to choose)

Please ensure that the specified port is not occupied yet. See also https://github.com/lllyasviel/Fooocus/issues/2296
