### ISSUE TITLE
Suggestion to Add Image Saving Option and Optimize gradio API Return Type

### ISSUE THREAD

**Issue by pieceof** [lllyasviel/Fooocus#287]
My English is awful; the following is translated by GPT, so please try to understand the general meaning.

Could we add an option that allows users to choose whether or not to save images locally? Additionally, for the gradio API, could we consider not just returning the file path of the image, but directly returning the binary data or Base64 encoding of the image? This would provide users with more flexibility in handling the returned image data. Furthermore, the current implementation is confusing, as I can't even find where the image is saved.

Alternatively, do we already have a method for returning images in Base64 or binary format? If not, are there any other ways to remotely retrieve images via the API? This issue is very urgent for me, thank you for your assistance!

**Comment by KubeLouis** [comment]
the same

**Comment by mashb1t** [comment]
Sorry for the late response, was added as collaborator only recently and doing cleanup now.

> Could we add an option that allows users to choose whether or not to save images locally

This is now possible using `--disable-image-log`.

> Additionally, for the gradio API, could we consider not just returning the file path of the image, but directly returning the binary data or Base64 encoding of the image? This would provide users with more flexibility in handling the returned image data. Furthermore, the current implementation is confusing, as I can't even find where the image is saved.
> Alternatively, do we already have a method for returning images in Base64 or binary format? If not, are there any other ways to remotely retrieve images via the API? This issue is very urgent for me, thank you for your assistance!

I personally do not use the API of Fooocus, but quite a few things changed since you reported the issue. Please check again with the latest vesion of Fooocus and feel free to reopen the issue if this is still not possible.
Thank you very much, your feedback is appreciated.
