### ISSUE TITLE
[Feature Request]:  is there a possibility for Fooocus to join IC-Light?

### ISSUE THREAD

**Issue by HelloLaohe** [lllyasviel/Fooocus#2902]
### Is there an existing issue for this?

- [ ] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

As fans of Fooocus, we really hope the author won't stop maintaining and upgrading Fooocus. The development, updates, iterations, and changes in AI art are particularly fast-paced. For example, is there a possibility for Fooocus to join IC-Light?

### Proposed workflow

[ IC-Ligh ](https://github.com/lllyasviel/IC-Light)

### Additional information

As fans of Fooocus, we really hope the author won't stop maintaining and upgrading Fooocus. The development, updates, iterations, and changes in AI art are particularly fast-paced. For example, is there a possibility for Fooocus to join IC-Light?

**Comment by IPv6** [comment]
IC-Light is for SD15. So no use for Fooocus at all

May be in several month when the same approach will be repeated for SDXL models

**Comment by mashb1t** [comment]
> IC-Light is for SD15. So no use for Fooocus at all
> 
> May be in several month when the same approach will be repeated for SDXL models

^ what @IPv6 said.
Closing for now and this issue is going to be re-evaluated when support for SDXL has been implemented.
