### ISSUE TITLE
[Bug]: fooocus doesnt respect the path_outputs variable in presets

### ISSUE THREAD

**Issue by Alireza2317** [lllyasviel/Fooocus#2903]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

in fooocus version 2.3.1 on Linux, which i just updated, i have an issue. in the previous version, i could run fooocus with a preset, and the settings inside the preset json were applied specially the `path_outputs` which is really important to me. now that the preset selector has been added, all the outputs, no matter if i choose other presets in the ui, go to the preset which i initially called fooocus with. So when i change the preset in the ui, every setting will be applied, but the outputs will not go in the apropriate specified directory.

### Steps to reproduce the problem

1. create a preset which has the path_outputs variable in the json,
2. run fooocus with no preset specified
3. change the preset to the created preset in the ui
4. generate some images, the images wont go where you specified

### What should have happened?

the images should be saved in the exact directory specified in each preset that has been selected in the ui.

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

debian 12

### Console logs

```Shell
Update succeeded.
[System ARGV] ['entry_with_update.py', '--theme', 'dark', '--always-low-vram']
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
Fooocus version: 2.3.1
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Total VRAM 3902 MB, total RAM 15714 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --always-normal-vram
Set vram state to: LOW_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7866

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 3.41.2, however version 4.29.0 is available, please upgrade.
--------
model_type EPS
UNet ADM Dimension 2816
Opening in existing browser session.
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: /home/**********/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.2], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/home/**********/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [/home/**********/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/home/**********/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.2.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cpu, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Started worker with PID 86488
App started successful. Use the app with http://127.0.0.1:7866/ or 127.0.0.1:7866
```

**Comment by mashb1t** [comment]
Hey @Alireza2317,
this is intended as currently no paths ae applied from presets when switching from initial config to preset as these settings are not globally used, but set separately for each browser session.
This is different to booting with preset arg, where the initial config is overridden by preset keys and values in a global context.

If you need to use different output paths for each preset, feel free to add one line to read and update the output path globally in https://github.com/lllyasviel/Fooocus/blob/main/modules/config.py#L119
or directly always globally update by adding the line `config_dict.update(json_content)`.

This is most likely a won't do as Fooocus can be used by multiple people at a time and changing paths in general may not be intended by the hosting entity.

Happy to hear feedback of your and the community though on this matter.

**Comment by Alireza2317** [comment]
well i guess that makes sense, but because i am the only one who uses this machine and therefore fooocus, that functionality is a must for me. i'll try the code you presented and see if it works.
but i think if there was a checkbox in the presets section asking wether to save the images in the `path_outputs` defined in the preset or just save it in the default location, that would be very nice.
thank you for your response.

**Comment by mashb1t** [comment]
@Alireza2317 you'll also have to set the `path_outputs` var for config in webui.py, sth. liike this (not tested):

```
preset_content = modules.config.try_get_preset_content(preset) if preset != 'initial' else {}
modules.config.path_outputs = modules.config.get_path_output() # <-- add this line
preset_prepared = modules.meta_parser.parse_meta_from_preset(preset_content)
```

**Comment by Alireza2317** [comment]
great it worked like a charm! thank you so much.
