### ISSUE TITLE
【much needed】 facial restoration integrated into Fooocus

### ISSUE THREAD

**Issue by hzeasy** [lllyasviel/Fooocus#293]
First of all, thanks for providing Fooocus, which is a very good tool, but due to the limitation of resolution, when the proportion of people in the picture is low, the probability of bad faces and bad hands is high. I tested the official model and others. This is real. I hope the author can pay attention, and thank you for your efforts.

**Comment by Anandarani** [comment]
Thumbs up! Fooocus is absolutely great. The only thing which is badly missing is face restoration like Codeformer/Gfpgan and an upscaler like Esrgan. An Integration into Fooocus would be great. Thanks a lot!

**Comment by GuidoBartoli** [comment]
I think this could be a really good place where to insert Face/Hand restoration using CodeFormer or YOLO... 😉 
![codeformer](https://github.com/lllyasviel/Fooocus/assets/16103676/2b14ca46-e9de-4312-b060-305a389c335c)

**Comment by mashb1t** [comment]
You can now use inpainting with method "Improve Detail (face, hand, eyes, etc.)", which, for me, works way better than Codeformer/Gfpgan. Please make sure you update Fooocus to the latest version before testing.
![image](https://github.com/lllyasviel/Fooocus/assets/9307310/62d35abd-50d3-4944-a6b1-f0dcdf233cc5)

**Comment by GuidoBartoli** [comment]
Thanks @mashb1t, much appreciated!
