### ISSUE TITLE
Error in API seed

### ISSUE THREAD

**Issue by LittleTerry** [lllyasviel/Fooocus#294]
I tried to use the following code, but 
1) fisrt, it says: [AttributeError("'dict' object has no attribute 'replace'")]
![image](https://github.com/lllyasviel/Fooocus/assets/19617725/a27487be-4544-404e-a2af-944bff481400)

2) second, according to the file "log.html",  the seed is always 1
![image](https://github.com/lllyasviel/Fooocus/assets/19617725/4448fef2-8f8b-404e-8255-7ede5443f217)

![image](https://github.com/lllyasviel/Fooocus/assets/19617725/220a8a1c-10ab-4262-84c3-82c9fdfee3d4)

**Comment by pieceof** [comment]
https://github.com/lllyasviel/Fooocus/issues/172
