### ISSUE TITLE
LyCORIS support

### ISSUE THREAD

**Issue by kubilaykilinc** [lllyasviel/Fooocus#297]
Can support LyCORIS?

**Comment by huwhitememes** [comment]
I'd love to know if i can use LyCORIS in Fooocus. It's a great question. I hope we get an answer

**Comment by mashb1t** [comment]
As far as i could see LyCORIS are supported. Tested with https://civitai.com/models/214442/envy-action-shot-xl-01.
Please feel free to test oyurself and provide your feedback. Thanks!

**Comment by mashb1t** [comment]
models > loras works jsut fine for me. Please make sure your files do have one of the supported extensions, see https://github.com/lllyasviel/Fooocus/blob/dc5b5238c83c63b4d7814ba210da074ddc341213/modules/config.py#L388
