### ISSUE TITLE
[Feature Request]: Image Sequence / Image Batch / Video features

### ISSUE THREAD

**Issue by xx88xx** [lllyasviel/Fooocus#2988]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Would it be possible to have the ablity to import/export image sequences or batches of images, which would help creating video with fooocus. Automatic1111 has this feature with img2img, but I find fooocus a lot nicer with it's outputs. 

Is something like this possible?

### Proposed workflow

Some ideas:

- img2img - image sequence workflow
- Animate lora sliders (eg. 0.1 to 1) over a series of image outputs
- AnimDiff workflow https://github.com/guoyww/AnimateDiff

**Comment by xx88xx** [comment]
@mashb1t would it be possible to use the fooocus engine with comfyUI?

**Comment by mashb1t** [comment]
@xx88xx Which engine do you mean, inpainting / mixing / rendering?
There are various custom nodes trying to migrate functionality, e.g. https://github.com/Acly/comfyui-inpaint-nodes?tab=readme-ov-file#fooocus-inpaint

Please keep in mind that the basis of Comfy and Fooocus is similar, but has heavily been optimized in Fooocus, which may by nature of Comfys modular approach never be achieved there.
