### ISSUE TITLE
Preview image on every step

### ISSUE THREAD

**Issue by ArjixWasTaken** [lllyasviel/Fooocus#30]
Would be awesome if we could have a preview of the image as it is getting generated.

Maybe also have a blur over the image?

**Comment by Semonxue** [comment]
It looks done in latest version.

**Comment by WaGi-Coding** [comment]
any way to have it as a file, not only as blob in the webui?

**Comment by Semonxue** [comment]
> any way to have it as a file, not only as blob in the webui?

You can find images in outputs filder

**Comment by WaGi-Coding** [comment]
> > any way to have it as a file, not only as blob in the webui?
> 
> You can find images in outputs folder

i know, i am using the api and wanted to have the ongoing progress image being saved on the system and overwritten with each new step or every 3rd.

I made it manually now, which was not to easy for me ^^

**Comment by shirubei** [comment]
> > > any way to have it as a file, not only as blob in the webui?
> > 
> > 
> > You can find images in outputs folder
> 
> i know, i am using the api and wanted to have the ongoing progress image being saved on the system and overwritten with each new step or every 3rd.
> 
> I made it manually now, which was not to easy for me ^^

You can easily save that blob(which is base64 coded data) as png file.
Btw, would you please show me the api souce you are using ？ I ran into an error (#172)  . Thank you.

**Comment by WaGi-Coding** [comment]
> 



> > > > any way to have it as a file, not only as blob in the webui?
> > > 
> > > 
> > > You can find images in outputs folder
> > 
> > 
> > i know, i am using the api and wanted to have the ongoing progress image being saved on the system and overwritten with each new step or every 3rd.
> > I made it manually now, which was not to easy for me ^^
> 
> You can easily save that blob(which is base64 coded data) as png file. Btw, would you please show me the api souce you are using ？ I ran into an error (#172) . Thank you.

Actually i get the same error. Maybe we need an older version of the gradio client package, not sure. I just ignore that warning as i just want to trigger promps for now, which works anyway

**Comment by shirubei** [comment]
> Actually i get the same error. Maybe we need an older version of the gradio client package, not sure. I just ignore that warning as i just want to trigger promps for now, which works anyway

Thank you. I'll have a try on old gradio version.

**Comment by shirubei** [comment]
> > 
> 
> > > > > any way to have it as a file, not only as blob in the webui?
> > > > 
> > > > 
> > > > You can find images in outputs folder
> > > 
> > > 
> > > i know, i am using the api and wanted to have the ongoing progress image being saved on the system and overwritten with each new step or every 3rd.
> > > I made it manually now, which was not to easy for me ^^
> > 
> > 
> > You can easily save that blob(which is base64 coded data) as png file. Btw, would you please show me the api souce you are using ？ I ran into an error (#172) . Thank you.
> 
> Actually i get the same error. Maybe we need an older version of the gradio client package, not sure. I just ignore that warning as i just want to trigger promps for now, which works anyway

The error ('dict' object has no 'replace' attribute ) solved. Please check #172

**Comment by LUCANOR007** [comment]
> > > any way to have it as a file, not only as blob in the webui?
> > 
> > 
> > You can find images in outputs folder
> 
> i know, i am using the api and wanted to have the ongoing progress image being saved on the system and overwritten with each new step or every 3rd.
> 
> I made it manually now, which was not to easy for me ^^

Hi, how did you made it?
