### ISSUE TITLE
Request - Image browser with history of prompts

### ISSUE THREAD

**Issue by zono50** [lllyasviel/Fooocus#300]
I'm loving this program so far, but I think an image browser with history of the previously used prompts would be super useful.  At the very least, atleast a history of the prompts we used before. Thanks and keep up the great work

**Comment by Spirit-Catt** [comment]
I think log file in outputs does that work well.

![Example](https://github.com/lllyasviel/Fooocus/assets/143511971/7bdd5d24-7f41-438c-9784-8f17530df8d7)
