### ISSUE TITLE
[Feature Request]: Will there be a NSFW preset added?

### ISSUE THREAD

**Issue by Koaxz** [lllyasviel/Fooocus#3005]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Generate penises)))

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

### Additional information

The built-in presets can generate a vagina, but not a penis.

**Comment by mashb1t** [comment]
There will not be an official one, but feel free to create one yourself. You can find plenty of LoRAs for NSFW generation on the internet (e.g. civitai.com).
