### ISSUE TITLE
[Feature Request]: Transfer random style to the interface, remove it in styles

### ISSUE THREAD

**Issue by SunGreen777** [lllyasviel/Fooocus#3015]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Transfer random style to the interface, remove it in styles

### Proposed workflow

Transfer random style to the interface, remove it in styles

### Additional information

Transfer random style to the interface, remove it in styles

**Comment by mashb1t** [comment]
@SunGreen777 what is the reason behind this request? Please elaborate.

**Comment by JulienZLQ** [comment]
I think what he meant is to separate the random style from the checklist as an independent option. When the random style is selected, the checklist can be invalidated and the random style can be generated without repeatedly selecting and canceling the checklist.

**Comment by mashb1t** [comment]
I've originally intended to do this with a checkbox and another input for the amount of random styles, similar to the seed select, but them decided against it as more styles normally mean worse artistic direction into what the random style says.
As random style you can still check other styles (if needed) and add a random one in addition to this as well as have everything style-related in one input element, the checkbox list.
Hope it's more understandable now why this is currently a won't do for me if no other additional reasoning is provided.
