### ISSUE TITLE
Fooocus NOT WORKING on Google Colab's Gradio Link

### ISSUE THREAD

**Issue by thakurtech** [lllyasviel/Fooocus#3021]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

Fooocus NOT WORKING on Google Colab's Gradio Link it's showing 404 Time-out 

### Steps to reproduce the problem

When you run it on Collab , instead of running it shows 404 Timeout error , it's a Gradio Link issue

### What should have happened?

Instead of the error the page should be loaded

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### Console logs

```Shell
404 Timeout
```

**Comment by Er3mit4** [comment]
I have the same problem running locally on windows 10.

**Comment by mashb1t** [comment]
see https://github.com/lllyasviel/Fooocus/discussions/3020#discussioncomment-9572152

**Comment by Ytwork0** [comment]
I got same Problem, How much time its take to resolve? #admin

**Comment by mashb1t** [comment]
@Ytwork0 #admin here, please be advised that waiting for a fix is the best option for now. You can find the Gradio status dashboard here: https://status.gradio.app/.
HuggingFace is normally really good in maintaining servers and keeping them updated, but it seems like that as of lately their share API has some recurring outages. I'll keep an eye on this.

**Comment by Ytwork0** [comment]
OK, i got it

**Comment by mashb1t** [comment]
Works again, they've fixed it => Closing this issue.

**Comment by Vsatyam013** [comment]
Fooocus NOT WORKING on Google Colab's Gradio Link it's showing 404 Time-out

**Comment by mashb1t** [comment]
@Vsatyam013 yes, they currently seem to have an issue with their share API: https://status.gradio.app/history
