### ISSUE TITLE
[Bug]: Fix aspect ratio calculation

### ISSUE THREAD

**Issue by aolko** [lllyasviel/Fooocus#3033]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Aspect ratio calculation for some resolution feels very off

![](https://i.imgur.com/uRZ5oKt.png)

### Steps to reproduce the problem

1. Add custom resolutions
2. Observe incorrect aspect ratios

### What should have happened?

Correct aspect ratio calculation

### What browsers do you use to access Fooocus?

Mozilla Firefox, Google Chrome, Microsoft Edge

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11 22H2 22621.3593

### Console logs

```Shell
[System ARGV] ['D:\\Programs\\StabilityMatrix\\Data\\Packages\\Fooocus\\launch.py', '--preset', 'realistic', '--share', '--always-normal-vram', '--unet-in-fp8-e5m2', '--clip-in-fp8-e5m2']
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Fooocus version: 2.4.1
Loaded preset: D:\Programs\StabilityMatrix\Data\Packages\Fooocus\presets\realistic.json
[Cleanup] Attempting to delete content of temp dir C:\Users\[redacted]\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Downloading: "https://huggingface.co/mashb1t/misc/resolve/main/xl-to-v1_interposer-v4.0.safetensors" to D:\Programs\StabilityMatrix\Data\Packages\Fooocus\models\vae_approx\xl-to-v1_interposer-v4.0.safetensors

100%|██████████| 5.40M/5.40M [00:00<00:00, 26.4MB/s]
Total VRAM 6144 MB, total RAM 32718 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 6GB : native
VAE dtype: torch.float32
Using pytorch cross attention
[System ARGV] ['D:\\Programs\\StabilityMatrix\\Data\\Packages\\Fooocus\\launch.py', '--preset', 'realistic', '--share', '--always-normal-vram', '--unet-in-fp8-e5m2', '--clip-in-fp8-e5m2']
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Fooocus version: 2.4.1
[Cleanup] Attempting to delete content of temp dir C:\Users\[redacted]\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Refiner unloaded.
IMPORTANT: You are using gradio version 3.41.2, however version 4.29.0 is available, please upgrade.
--------
Running on local URL:  http://127.0.0.1:7865
Running on public URL: https://[redacted].gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: G:\sd-models-ext\SDXL\realisticStockPhoto_v20.safetensors
VAE loaded: None
Request to load LoRAs [('SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 0.25)] for model [G:\sd-models-ext\SDXL\realisticStockPhoto_v20.safetensors].
Loaded LoRA [D:\Programs\StabilityMatrix\Data\Models\Lora\SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for UNet [G:\sd-models-ext\SDXL\realisticStockPhoto_v20.safetensors] with 788 keys at weight 0.25.
Loaded LoRA [D:\Programs\StabilityMatrix\Data\Models\Lora\SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for CLIP [G:\sd-models-ext\SDXL\realisticStockPhoto_v20.safetensors] with 264 keys at weight 0.25.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 4.50 seconds
Started worker with PID 339408
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865 or https://[redacted].gradio.live
```

**Comment by mashb1t** [comment]
@aolko i don't see the bug, all aspect ratio calculations are correct.

Did you by chance intend to use 1536 instead of 1434?
The aspect ratio for 1536x1024 would be 3:2 then instead of 717 : 512.

Which aspect ratios did you expect for these custom resolutions?

**Comment by aolko** [comment]
> @aolko i don't see the bug, all aspect ratio calculations are correct.
> 
> Did you by chance intend to use 1536 instead of 1434? The aspect ratio for 1536x1024 would be 3:2 then instead of 717 : 512.
> 
> Which aspect ratios did you expect for these custom resolutions?

I basically went ahead and did 1024 and 512 by longest side, i expected more common ones that don't break SDXL's size limitations :)

And please do the checkboxes as dropdown list, like in Fooocus-MRE

**Comment by mashb1t** [comment]
Please find all SDXL base aspect ratios in https://github.com/lllyasviel/Fooocus/pull/1617 to not get weird artifacts / repeating subjects.
Aspect ratio select list of radio buttons will not be changed to dropdown list, feel free to do this in your own fork. It's only a small change but you can find the reasoning in https://github.com/lllyasviel/Fooocus/pull/2590

**Comment by aolko** [comment]
wait, can you redo it as a slider like this?
![](https://i.imgur.com/h3kGvrK.png)

**Comment by mashb1t** [comment]
@aolko i'm not a frontend developer and sadly don't have time to do this. Feel free to contribute this functionality.
