### ISSUE TITLE
[Bug]: Typo in VAE name variable in list

### ISSUE THREAD

**Issue by Ilya87** [lllyasviel/Fooocus#3035]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Images stop generating

### Steps to reproduce the problem

1 - Enable Developer Debug Mode
2 - set VAE to None

### What should have happened?

Simply option of no vae should be used (that means use checkpoint VAE).

### What browsers do you use to access Fooocus?

Other

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ilya\\Downloads\\forge\\Fooocus_win64_2-1-831\\Fooocus\\models\\vae\\None'

```

Fooocus literaly searches for VAE named "None".

**Comment by mashb1t** [comment]
Maybe i don't get it, but you can simply use the value `Default (model)` (see https://github.com/lllyasviel/Fooocus/blob/main/modules/flags.py#L59) as `None` would indicate no actual VAE, which isn't correct. `Default (model)` also is already the default value for default_vae in the config_modification_tutorial.txt file, so just use that one in presets, your config or similar.

IMO this is not a bug. Can this be closed?
