### ISSUE TITLE
[Feature Request] : Cancel Button

### ISSUE THREAD

**Issue by joanorsky** [lllyasviel/Fooocus#304]
A cancel button (for the current generation) with a Cue explorer (with the possibility to cancel next-on-the-line-to-be-generated images) would be a nice feature that i think is not too hard to implement.

The usability would greatly be improved by just these two "little" tweaks...

**Comment by Jisevind** [comment]
I second this! 

I have so many times changed my prompt, clicked Generate and realised that I forgot to change 5-10 image batch back to 1 image for testing of the new prompt 🙈 and now I have to wait ~30 sec/pic to finish😂

**Comment by barepixels** [comment]
[MoonRide303](https://github.com/MoonRide303)
/
[Fooocus-MRE](https://github.com/MoonRide303/Fooocus-MRE) just add this feature to his fork today

**Comment by MoonRide303** [comment]
@lllyasviel Let me know if you want backport of it, I can provide clean pull request adjusted to vanilla code base (it's pretty clean from UI / UX perspective - Generate button is being replaced with Stop button when generation starts).

**Comment by mashb1t** [comment]
This has been implemented already, feel free to test again with the latest version of Fooocus!
