### ISSUE TITLE
[Bug]: Drag & Drop not working on Firefox browser.

### ISSUE THREAD

**Issue by Xicatto** [lllyasviel/Fooocus#3047]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [x] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

After generating an image on the **Firefox** browser, when dragging & dropping the generated image onto any of the *Input Image* options from the preview screen directly, the image doesn't load. I've tested the exact same scenario on **Google Chrome** and it works. I have the latest updates on both browsers.

# Firefox
![Screenshot 2024-05-29 192332](https://github.com/lllyasviel/Fooocus/assets/39447415/8d3d21d5-58c9-4221-b034-a5d1591e0862)

### Steps to reproduce the problem

1. Open fooocus.
2. Generate the image on **Firefox**.
3. Drag & Drop the generated image onto any of the *Input Image* options.

### What should have happened?

Fooocus should have loaded the dragged image.

# Chrome
![Screenshot 2024-05-29 192513](https://github.com/lllyasviel/Fooocus/assets/39447415/82718f63-08dd-4481-8226-cd2f460c5e61)

### What browsers do you use to access Fooocus?

Mozilla Firefox, Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
https://pastebin.com/4PbXZP4B
```

**Comment by mashb1t** [comment]
Hey @Xicatto, this is a known issue and we can't do anything about it as Firefox doesn't offer this functionality. This is also one of the reasons why the labels were removed to drag down images to inputs in https://github.com/lllyasviel/Fooocus/pull/2998.

See https://github.com/lllyasviel/Fooocus/issues/1425

**Comment by BassAzayda** [comment]
I created this bookmarklet that should help

javascript:(function(){let draggedImageData=null;let currentDropZone=null;function handleDragStart(event){const img=event.target;draggedImageData=img.src;}function handleDragOver(event){event.preventDefault();currentDropZone=event.currentTarget;}function handleDrop(event){event.preventDefault();if(!draggedImageData||!currentDropZone){return;}const dropZone=currentDropZone.closest('.image-container > div:first-child');if(!dropZone){return;}fetch(draggedImageData).then(res=> res.blob()).then(blob=>{const file=new File([blob],"dragged-image.png",{type:blob.type});const dummyFileList={0:file,length:1,item:index=> dummyFileList[index]};let dropEvent=new Event('drop',{bubbles:true});Object.defineProperty(dropEvent,'dataTransfer',{value:{files:dummyFileList}});dropZone.dispatchEvent(dropEvent);console.log('Drop event triggered successfully for drop zone');}).catch(error=> console.error('Error creating File from image:',error));draggedImageData=null;currentDropZone=null;}function addEventListeners(){document.querySelectorAll('.thumbnail-item img').forEach(img=>{img.addEventListener('dragstart',handleDragStart);img.addEventListener('dragend',handleDrop);});document.querySelectorAll('.image-container > div:first-child').forEach(dropZone=>{dropZone.addEventListener('dragover',handleDragOver);dropZone.addEventListener('drop',handleDrop);});}addEventListeners();const observer=new MutationObserver(mutationsList=>{for(let mutation of mutationsList){if(mutation.type==='childList'){mutation.addedNodes.forEach(node=>{if(node.matches&&node.matches('.thumbnail-item img')){addEventListeners();}});}}});observer.observe(document.body,{childList:true,subtree:true});console.log('Automatic image drop trigger is now active');})();
