### ISSUE TITLE
I found that the Moving model (s) takes a long time to generate. Is there any solution to this problem?

### ISSUE THREAD

**Issue by ycmomo** [lllyasviel/Fooocus#3053]
### Is there an existing issue for this?

- [ ] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

[Fooocus Model Management] Moving model(s) has taken 21.13 seconds

### Proposed workflow

I found that the Moving model (s) takes a long time to generate. Is there any solution to this problem?

**Comment by mashb1t** [comment]
Hey @ycmomo, yes there are a few things you can do:
* make sure you have sufficient vram and swap isn't used
* if you don't have sufficient vram, ensure you have sufficient ram available
* if you don't, ensure swap is on the same drive as Fooocus is
* if you have sufficient vram you can disable offloading from it or use the arguments always high vram or always gpu to never move it

**Comment by ycmomo** [comment]
Thank you very much for your answer

**Comment by ycmomo** [comment]
> 嘿@ycmomo是的，您可以做以下几件事：
> 
> * 确保你有足够的 vram 并且没有使用交换空间
> * 如果你没有足够的显存，请确保你有足够的可用内存
> * 如果不是，请确保交换与 Fooocus 位于同一驱动器上
> * 如果你有足够的 vram，你可以禁用它的卸载，或者使用参数 always high vram 或 always gpu 来永不移动它

Thank you very much for your answer
