### ISSUE TITLE
Randomize seed on batch generation

### ISSUE THREAD

**Issue by Jisevind** [lllyasviel/Fooocus#306]
The seed does not randomize between images when batch generating images, it increments by 1. 

Is this by design or a bug, now it only randomizes if I generate 1 image at a time?

I can see the value with incrementing but it would be very nice to have the option to randomize between images too.

**Comment by MoonRide303** [comment]
@Jisevind As long as first number is random, it's completely fine - seed don't need to be far away to result in completely different image.

**Comment by Jisevind** [comment]
Thank you, then I misunderstood seeds 👍
