### ISSUE TITLE
[Bug]: inpaint choose Method and refiner

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/Fooocus#3088]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

1. inpaint text prompt is deleted
2. all is standart, inpaint with a mask, i generate an image and only the model starts (30 steps) BUT ...

btw, how is handled the prompt above and the inpaint prompt ?

### Steps to reproduce the problem

1
(input image) tab (inpaint or outpaint)
i choose "Improve Detail (face, hand, eyes, etc."
if i write somewhat in "Additional Prompt"
than i choose methode "Inpaint or Outpaint (default)"
than i go back choose "Improve Detail (face, hand, eyes, etc.)"
my textprompt is gone ...

2
(input image) tab (inpaint or outpaint)
i choose "Improve Detail (face, hand, eyes, etc."
write somewhat in "Additional Prompt"
"generate"
all ok (30steps)
in (Developer Debug Mode)
i check  / aybe i choose v2.6 or none too
(x) Disable initial latent in inpaint
generate again
now 24 steps with 6 refiner steps
i uncheck
( ) Disable initial latent in inpaint
refiner still work

### What should have happened?

1. dont delete   ;) the prompt

2. refiner should not be activated at all ^^

### What browsers do you use to access Fooocus?

Mozilla Firefox

### Where are you running Fooocus?

Locally

### What operating system are you using?

win10

### Console logs

```Shell
-
```

**Comment by mashb1t** [comment]
Fooo us uses a synthetic refiner if none is chosen in inpainting, so this isn't a bug but intended. The input behavior has to be evaluated.

**Comment by kalle07** [comment]
i mean that

usual:

![01a](https://github.com/lllyasviel/Fooocus/assets/118767589/9a2b6486-2aaa-40be-9d01-deeda0ecab2d)

and sorry i cant reproduce (some reason (i changed a lot but all in "inpaint" with a mask

![01b](https://github.com/lllyasviel/Fooocus/assets/118767589/848557bb-9c33-4a32-9c8b-6f40d3099026)


why and when this synthetic refiner does his job ?

**Comment by mashb1t** [comment]
The synthetic refiner is activated in https://github.com/lllyasviel/Fooocus/blob/main/modules/async_worker.py#L397 and used to boost variety in the output.

**Comment by kalle07** [comment]
isee, i was confused, somtime yes sometime not ^^

**Comment by xhoxye** [comment]
mix image prompt enable refiners at 0.8

**Comment by kalle07** [comment]
okay,

maybei you can explane how is handle the normal prompt
and the additional "inpaint" prompt, if i write the same alternately the image is identical,
but how you handle it if the prompt differ (weights?) (inpaint prompt first?) ?

**Comment by mashb1t** [comment]
Inpaint prompt is always loaded first if not empty (see screenshot above). If you write the same thing in both prompts, the prompt will just be double.
The first line of the prompt is always used as reference, all other lines are only used as positive_basic_workloads (without wildcards/array support and no prompt expansion with Fooocus V2, only for CLIP encode).
If you want one subject to be prioritized, use it in the first line. The other lines will also have impact, but less features are applied.
