### ISSUE TITLE
Forced Download of Specific Model

### ISSUE THREAD

**Issue by WinstonWoof** [lllyasviel/Fooocus#31]
Why is the run.bat insistent on grabbing  a specific model when I already have a directory full of models

![image](https://github.com/lllyasviel/Fooocus/assets/128506111/64e1dfd6-b4bb-4246-b6ff-896c42cd8b47)

**Comment by WinstonWoof** [comment]
NB I am aware I dont specifically have the ones that are being downloaded but that's not the point. I have a directory full of Models incldung SDXL models ready to use.

I dont need a forced download of a specific model thank you very much.

**Comment by marhensa** [comment]
some of the reason I think we could not choose the specific models, for now.

It uses SDXL, and this WebUI specificaly use 1.0 wih 0.9 VAE

it's for simplicity I guess?

**Comment by WinstonWoof** [comment]
> 



> some of the reason, I think we could not choose the specific models, for now. it's for simplicity I guess?
> 
> It uses SDXL, and this WebUI specificaly use 1.0 wih 0.9 VAE

so are you saying what I think you're saying that this UI is locked down to the specific model decided by the author and that no other SDXL based models can be used with it ?

If when I get up in the morning that is the case I will be a more annoyed Hector than I already am at being forced to download specifci models in the first place!!

**Comment by WinstonWoof** [comment]
BTW I do owe @lllyasviel one small apology. Had I  read the main page more precisley I would have relaised it was fgoing to look for these specific models.

I presumed it was just, as I've seen others do, being helpful and downloading some files in case a user didnt have any

**Comment by aimarxjg** [comment]
他们是把0.9的VAE再次烘焙到XL本体BASE模型中了吗？ 模型大小并没有发生变化

**Comment by s-marcelle** [comment]
It downloads what it needs.

What would have been nice would be to have the ability to adjust a config file so that we could point to a specific directory of models.  (eg my current comfyui models folder).

**Comment by mohamedghry** [comment]
If you don't want and don't have that default model, you can just add the following 3 lines at the end of your `config.txt` file


```
    "checkpoint_downloads": {},
    "lora_downloads": {},
    "embeddings_downloads": {}
```

**Comment by albozes** [comment]
@mohamedghry I've added those lines in my config.txt but it continues downloading a model at launch.
