### ISSUE TITLE
[Feature Request]: Is it possible to "teach" Fooocus new words?

### ISSUE THREAD

**Issue by Tectract** [lllyasviel/Fooocus#3105]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

I would like to make an image featuring "Tigger" from the Winnie the Pooh series. Fooocus seems to know what "Winnie the Pooh" is but not know about any of the other characters like Eeyore, Roo, Owl, or Tigger. Is there a way to "teach" Fooocus to recognize Tigger in particular?

### Proposed workflow

1. input some Tigger images
2. have Foocus remember what Tigger is somehow (???)
3. works in temporary or permament memory so it can remember Tigger over instantiations (?)

**Comment by mashb1t** [comment]
To do this it's i assume easiest to train your own LoRA. Please check out https://github.com/bmaltais/kohya_ss
