### ISSUE TITLE
[Feature Request] Full page preview

### ISSUE THREAD

**Issue by zono50** [lllyasviel/Fooocus#311]
Hello all, I would like to put in a request so when you click on the picture, it will load the image fullscreen in sort of a lightbox style. I always end up having to save the images, and then open them up to see the smaller details. Other than that, loving the program so far and the hard work.

**Comment by barepixels** [comment]
I was thinking the same.  What would be cool is while viewing full screen, one can press a reject button and delete the file and advance to the next image

**Comment by mashb1t** [comment]
This has been implemented already, feel free to test again with the latest version of Fooocus!
