### ISSUE TITLE
[Bug]: Constantly removes my custom checkpoints folder

### ISSUE THREAD

**Issue by jnpatrick99** [lllyasviel/Fooocus#3111]
### Checklist

- [x] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [x] The issue exists on a clean installation of Fooocus
- [x] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I have a `checkpoints` folder that is a symlink to a place somewhere else on my hard drive - it takes around 300GB so I share it between different image generators. Every time I run the Fooocus it deletes this folder replacing it with an empty one and then starts downloading models that I already have. It happens every time I run it.

### Steps to reproduce the problem

1. Go to `Fooocus\models`
2. You can use the following powershell command to create a symlink folder `New-Item -ItemType SymbolicLink -Path "checkpoints" -Target "C:\.[your folder with shared models].\models\Stable-diffusion\XL"`
3. Run Fooocus
4. It will remove that folder, replace with an empty one and will start downloading the juggernaut model

### What should have happened?

The folder should be left as it is

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 10

### Console logs

```Shell
Nothing about removing folder in the console
```

**Comment by mashb1t** [comment]
@jnpatrick99 will have to check but as an alternative you can always set `path_checkpoints` in your config.txt to the other folder or even use an array for checkpoints and LoRAs in the config for multiple locations.

**Comment by gerroon** [comment]
I have the exact issue on Windows, Fooocus sometimes updates itself and during this update it removes the symlinks/junctions on Windows and resets the folder to its default

**Comment by mashb1t** [comment]
Please use the config to define an array of paths if you need checkpoints not to be in the default directory and do not use symlinks, as they might be overridden.
