### ISSUE TITLE
[Feature Request]: mask generation mode 

### ISSUE THREAD

**Issue by RanjithGadde447** [lllyasviel/Fooocus#3112]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

as we know ,  have mashbit released mask generation in his repo please add that in to this repository 

### Proposed workflow

1. Go to .... advanced 
2. Press ....inpaint outpaint
3. ...mask upload checkbox inside inpaint tab 
4. mask generation feature under mask upload tab

**Comment by mashb1t** [comment]
Part of milestone https://github.com/lllyasviel/Fooocus/milestone/4, see https://github.com/lllyasviel/Fooocus/discussions/1987

**Comment by mashb1t** [comment]
=> now part of [v2.5.0-rc1](https://github.com/lllyasviel/Fooocus/releases/tag/v2.5.0-rc1), discussion in https://github.com/lllyasviel/Fooocus/discussions/3282
