### ISSUE TITLE
[Feature Request]: Automatic upscale after every generation. 

### ISSUE THREAD

**Issue by thekingbalXD** [lllyasviel/Fooocus#3113]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

It automatically upscale the generated picture after its generation

### Proposed workflow

1. Go to Advanced 
2. Debug menu
3. There will be a toggle option to automatic upscale and the user will choose to what they want (e.g. Upscale 2x)

**Comment by mashb1t** [comment]
[v2.5.0](https://github.com/mashb1t/Fooocus/releases/tag/v2.5.0) has been released in my fork including this feature

**Comment by mashb1t** [comment]
=> now part of [v2.5.0-rc1](https://github.com/lllyasviel/Fooocus/releases/tag/v2.5.0-rc1), discussion in https://github.com/lllyasviel/Fooocus/discussions/3282, docs in https://github.com/lllyasviel/Fooocus/discussions/3281 (mirrored from https://github.com/mashb1t/Fooocus/discussions/42)
