### ISSUE TITLE
[Feature Request]: Slow Fooocus Colab Installation Process Fix

### ISSUE THREAD

**Issue by Gonjiired** [lllyasviel/Fooocus#3132]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

## Originally I get this and I assume many others too, it takes around 5 minutes idk but to long.

<b>Collecting pygit2==1.12.2
  Downloading pygit2-1.12.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 13.9 MB/s eta 0:00:00
Requirement already satisfied: cffi>=1.9.1 in /usr/local/lib/python3.10/dist-packages (from pygit2==1.12.2) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.9.1->pygit2==1.12.2) (2.22)
Installing collected packages: pygit2
Successfully installed pygit2-1.12.2
/content
Cloning into 'Fooocus'...
remote: Enumerating objects: 6354, done.
remote: Counting objects: 100% (403/403), done.
remote: Compressing objects: 100% (288/288), done.
remote: Total 6354 (delta 184), reused 249 (delta 98), pack-reused 5951
Receiving objects: 100% (6354/6354), 33.21 MiB | 26.67 MiB/s, done.
Resolving deltas: 100% (3553/3553), done.
/content/Fooocus
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share', '--always-high-vram']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.4.3
<b>*Error checking version for torchsde: No package metadata was found for torchsde*</b>
Installing requirements</b>

## My fix is instead of these commands

<b>*~~!pip install pygit2==1.12.2~~
%cd /content
!git clone https://github.com/lllyasviel/Fooocus.git
%cd /content/Fooocus
!python entry_with_update.py --share --always-high-vram*</b>

## I use these

```
!pip install --no-cache-dir einops==0.4.1 pygit2==1.12.2 torchsde==0.2.5
%cd /content
!git clone https://github.com/lllyasviel/Fooocus.git
%cd /content/Fooocus
!python entry_with_update.py --share --always-high-vram
```

## Why it works according to my knowledge

<b>When checking for the dependencies that are missing for some reason it just takes forever, instead its an easy fix and I found the versions needed and have them installed like they already should. </b>

### Proposed workflow

To be replaced with the fooocus colab link thats as of right no good.

**Comment by mashb1t** [comment]
@Gonjiired are already in the [requirements_versions.txt](https://github.com/lllyasviel/Fooocus/blob/main/requirements_versions.txt#L1-L2) file and will be installed when starting Fooocus for the first time anyways, where all missing dependencies are installed, which is why it also takes a bit longer on first boot. There shouldn't be a difference between installing them manually or automatically.
I don't see a way to improve performance here.
