### ISSUE TITLE
[Feature Request]: Specifying a VAE in presets

### ISSUE THREAD

**Issue by aquawaves** [lllyasviel/Fooocus#3144]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

For some of the models, built-in VAE leads to unsatisfying results, such as: blurry/messy image, lack of colors, image is too noisy et cetera.
It would be much more comfortable if I could specify a VAE in a preset so whenever I choose it, I already know that I would get high-quality images without any issues right out of the box, without opening "Developer Debug Mode" and manually selecting a VAE after preset loading.

### Proposed workflow

1. Go to root folder of Fooocus, open /presets
2. Create a new .json preset or open existing one in any text editor.
3. Set the value of "default_vae" to any desired, e.g. "default_vae": "sharpspectrumvaexl_v1.safetensors".
4. Save the .json file.

**Comment by mashb1t** [comment]
Missed that one somehow, thanks for the hint!
Merged to main, you can start using it after restarting Fooocus or after updating to the edge docker image.
