### ISSUE TITLE
[Feature Request]: 如何将从huggingface下载模型改为镜像？

### ISSUE THREAD

**Issue by SKRY1412** [lllyasviel/Fooocus#3149]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

选择国内镜像版本下载模型

### Proposed workflow

如何对参数进行修改？

**Comment by newxhy** [comment]
1、找到你的fooocus的 youFooocus\python_embeded\Lib\site-packages\huggingface_hub\constants.py
2、将里面的https://huggingface.co 修改为 https://hf-mirror.com 然后保存
3、重启fooocus。

**Comment by mashb1t** [comment]
You can simply set the env var `HF_MIRROR` or the attribute `--hf-mirror` in your .bat script or the entrypoint.
