### ISSUE TITLE
Add feature request

### ISSUE THREAD

**Issue by Phrixus2023** [lllyasviel/Fooocus#315]
The variety of styles is increasing. It is possible to consider adding a search feature for styles or a feature that prioritizes commonly used styles to reduce the time spent searching for styles.

**Comment by MoonRide303** [comment]
@Phrixus2023 I've changed style selection to [Dropdown](https://www.gradio.app/docs/dropdown) in [Fooocus-MRE](https://github.com/MoonRide303/Fooocus-MRE) - it's more compact and allows filtering by name, like that:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/e9a24910-ae6d-4ee6-8296-77f142f6717f)

@lllyasviel Might be worth changing in vanilla, too (dropdown looks cleaner to me - YMMV, though).

**Comment by mashb1t** [comment]
This feature has already been added, the sorting now changes depending on your most recent use of the style.
