### ISSUE TITLE
[Bug]: Load preset [J:\FOOOCUS\Fooocus_win64\Fooocus\presets\realistic.json] failed

### ISSUE THREAD

**Issue by RanjithGadde447** [lllyasviel/Fooocus#3157]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

J:\FOOOCUS\Fooocus_win64>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset realistic
Update failed.
Repository not found at J:\FOOOCUS\Fooocus_win64\Fooocus
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'realistic']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.4.3
Load preset [J:\FOOOCUS\Fooocus_win64\Fooocus\presets\realistic.json] failed
Expecting property name enclosed in double quotes: line 38 column 89 (char 872)
[Cleanup] Attempting to delete content of temp dir C:\Users\Ranjith\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful

loading default model  instead of realistic model since new update 2.4.3   yesterday  14/06/24

### Steps to reproduce the problem

run realistic.bat 

### What should have happened?

fooocus should load realistic preset .. but its not loading 

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

windows 11 

### Console logs

```Shell
J:\FOOOCUS\Fooocus_win64>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset realistic
Update failed.
Repository not found at J:\FOOOCUS\Fooocus_win64\Fooocus
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'realistic']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.4.3
Load preset [J:\FOOOCUS\Fooocus_win64\Fooocus\presets\realistic.json] failed
Expecting property name enclosed in double quotes: line 38 column 89 (char 872)
[Cleanup] Attempting to delete content of temp dir C:\Users\Ranjith\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Total VRAM 8192 MB, total RAM 32610 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 SUPER : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
```

**Comment by HelloLaohe** [comment]
.\python_embeded\python.exe -s Fooocus\launch.py --preset hyper-sd12
It seems that this style is normal for me, without using quotes and commas.

**Comment by mashb1t** [comment]
@RanjithGadde447 please fix the preset at those lines and ensure to use double-quotes when modifying it.
You can always reset to the official realistic preset, which you can find in this repository.

> Expecting property name enclosed in double quotes: line 38 column 89 (char 872)
