### ISSUE TITLE
Multiple prompts??

### ISSUE THREAD

**Issue by tralala87** [lllyasviel/Fooocus#316]
Is there a way to use multiple prompts instead of just one?

**Comment by MoonRide303** [comment]
@tralala87 If you enable Advanced mode you can then use negative prompt, and pick style (which modifies both positive and negative prompts) - if that's what you mean. And if were asking about separate conditioning for both text encoders in base model - it's not supported.

**Comment by aimarxjg** [comment]
> @tralala87 If you enable Advanced mode you can then use negative prompt, and pick style (which modifies both positive and negative prompts) - if that's what you mean. And if were asking about separate conditioning for both text encoders in base model - it's not supported.

Hello, what is the special significance of using multiple prompt word modules in COMFY? Isn't this traditional writing method applicable to SD1.5? I have observed that many workflows also have two sets of prompt word dialog boxes, L and R, in order to better identify prompt words? Is there any specific basis for official explanation?

**Comment by MoonRide303** [comment]
@aimarxjg SDXL base model uses two separate text encoders for text-based conditioning, namely OpenCLIP ViT-bigG and CLIP ViT-L. You can read more internals of it in research papers available at arxiv: [SDXL](https://arxiv.org/abs/2307.01952), [OpenCLIP](https://arxiv.org/abs/2212.07143), [CLIP](https://arxiv.org/abs/2103.00020). Key difference is that CLIP was trained on OpenAI private dataset, and OpenCLIP on LAION open dataset - and cause of that they can work a bit differently. For typical use cases we can just use the same text prompts as inputs for both text encoders, and not worry too much about those differences.

If you want to play with those separate prompts you can take a look at my basic SDXL workflows for ComfyUI, available on CivitAI: [MoonRide workflows for SDXL 1.0 in ComfyUI](https://civitai.com/models/118865/moonride-workflows-for-sdxl-10-in-comfyui). If you're low on VRAM (8 GB or less) use v1.2, without Hires Fix block.

**Comment by aimarxjg** [comment]
@MoonRide303  thx~~
