### ISSUE TITLE
[Feature Request]: Is it possible to find here explained doc for presets variables?

### ISSUE THREAD

**Issue by TorAllex** [lllyasviel/Fooocus#3160]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

It make possibility for quick apply various saved settings.

### Proposed workflow

1. For example, I want to save preset with "Forced Overwrite of Sampling Step" = 7, but cant find how to write it in my_preset.json
2. Of course, I'll be happy to see new button in UI "Save all as preset", if possible.

**Comment by mashb1t** [comment]
Please find the exact keys in the config modification example file. Not all settings are applicable for presets, so double-check in https://github.com/lllyasviel/Fooocus/blob/main/modules/config.py#L525

**Comment by mashb1t** [comment]
closing in general as duplicate of https://github.com/lllyasviel/Fooocus/issues/1622 (saving preset from UI)
