### ISSUE TITLE
[Feature Request]: hash generation

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/Fooocus#3161]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Is there an intention to "pimp" hash generation with multiprocessing/filesplitting?
or an option generate hash from all files

### Proposed workflow

...

**Comment by mashb1t** [comment]
Hashes are generated only once per model and only once for each start of the application.
Currently there is no need, at least no issues are known. Do you encounter any difficulties?

**Comment by kalle07** [comment]
no difficulties but need time ,so maybe it give some moves ;)

i mean only an option generate hash from all files at once (so i can go trink a cup of coffee)

**Comment by mashb1t** [comment]
That's a relatively easy task in python, so if you are familiar feel free to add a lazy loading for a new method call for each of the models and LoRAs, calculate the hash and write it to a file. If it already exists, then load hashes from that file. This way we can prevent recalculating the hashes each time after Fooocus restart, so it could benefit everyone.
I'd estimate about 2 hours for the implementation.
Do you want to take over the implenentation of this feature?

**Comment by kalle07** [comment]
oh no sry iam not a programmer   : D

but this option (if i have 20 models in the folder no one with hash) calc hash from all models, i saw somewhere, ithnk that can be easy implemented....

**Comment by mashb1t** [comment]
@kalle07 done, check out https://github.com/lllyasviel/Fooocus/pull/3221.

**Comment by mashb1t** [comment]
part of https://github.com/lllyasviel/Fooocus/commit/f2a21900c64c0bd4ed925420ea84e643f85d292b
