### ISSUE TITLE
Possible to access fooocus on local server similar to using command line argument --listen in A1111?

### ISSUE THREAD

**Issue by akatsukiaashish** [lllyasviel/Fooocus#317]
What the title says. 

Basically, I'd like to run fooocus on my PC but access on my tablet for easy painovers.

**Comment by onlinedear** [comment]
Intranet penetration, bind a domain name, both intranet and internet can access this project.
This sentence describes the concept of "intranet penetration" or "reverse proxy", which allows access to a project or service hosted on an internal network from both the intranet and the internet. By binding a domain name to the internal IP address of the project, users can access it using the domain name regardless of whether they are within the internal network or outside of it. This enables seamless access to the project from both internal and external networks.

**Comment by akatsukiaashish** [comment]
I believe gradio supports this functionality internally. 
Looking at webui.py ( in fooocus project ), I found the following. 

Probably we can pass these through run.bat. I'll check and report back. 

parser.add_argument("--share", action='store_true', help="Set whether to share on Gradio.")
parser.add_argument("--listen", type=str, default=None, metavar="IP", nargs="?", const="0.0.0.0", help="Set the listen interface.")

**Comment by akatsukiaashish** [comment]
`.\python_embeded\python.exe -s Fooocus\entry_with_update.py --listen`

Adding --listen argument in run.bat did the job. :)

**Comment by ptits** [comment]
I use entry_with_update.py --share

**Comment by adrianalter** [comment]
@akatsukiaashish i logged in to github just to say you are a god that saved me a lot of research, bless you man.
This issue should be made into general documentation in the readme, I feel it's very important to give the option to expose Fooocus as a server on networks.

**Comment by janElsik** [comment]
@akatsukiaashish I too want to say that you are a god sir, this was huge headache for me!
