### ISSUE TITLE
[Feature Request]: prompt QUick list suggestion at positive and negative prompt fields  

### ISSUE THREAD

**Issue by RanjithGadde447** [lllyasviel/Fooocus#3173]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

this feature help users to add desired positive and negative prompts to enhance images
prompt sugesstions  like  
postive  : high quality , 4k , high detailed face,  Increase Sharpness, Enhance Colors, Improve Brightness and Contrast, Reduce Noise, HDR Effect, Skin Smoothing, Add Depth of Field, Enhance Texture, Vintage Effect, Correct Exposure

negative : Blurry, Dull Colors, Poor Lighting, Noisy, Low Dynamic Range, Harsh Skin Texture, Flat Depth, Lack of Texture, Modern Filter, Incorrect Exposure

option to chose at suggestion level at above or below prompt fields 

 example_inpaint_prompts = gr.Dataset(samples=modules.config.example_inpaint_prompts, label='Additional Prompt Quick List', components=[inpaint_additional_prompt], visible=False)

### Proposed workflow

add mostly used enhancers (high quality, UHD, 4k, high detailed, 16k UHD, HDR, intricately detailed, rich shadows, highest resolution, highest quality,  of, (entoptic phenomena) (Mystical (high resolution) photoshopped  ) into one quick suggestion like enhancer, 

like this 3 suggestion quick list at the positive prompt field   

 add mostly used negative list params ( Bad composition, Poor composition, Unbalanced, signature, inscription, text, watermark, username, ugly, gritty, Disney, (cartoon:1.1), painting, (anime:1.1), 3d, drawn, )    like negative enhancers quick list of suggestion 
 
 
like this 3 suggestion quick list at the positive prompt field

**Comment by xhoxye** [comment]
If it is a fixed set of prompt words, it is recommended to add them to the custom style

**Comment by mashb1t** [comment]
@RanjithGadde447 Your intention is clear, but this is a Won't Do. The prompt and negative prompt are simply too individual to have suggestions for and styles do already exist, so i'd encourage you to add custom styles to either an existing style file or add your own style file. Most users do well with using the default styles and Fooocus Enhance already uses a lot of common negative prompt keywords, so that's basically covered.
