### ISSUE TITLE
REQUEST - add 'favorite' for styles and display at the top for easier usage

### ISSUE THREAD

**Issue by DARMSAN** [lllyasviel/Fooocus#318]
Fooocus is minimalist tool, I know, simple and easy as much as possible.
But 'styles' are getting bigger and I found they are too many for day to day use.
Of course, in the beginning, large selection is appreciated but found less than 10 styles I use daily.
Please add 'favorite' selection for user to keep them on top of the row,
Thanks

Darmsan / Leo

**Comment by barepixels** [comment]
Hi Leo

@MoonRise303 has added this feature in his fork  https://github.com/MoonRide303/Fooocus-MRE/issues/58

**Comment by DARMSAN** [comment]
Hi,
I read through the comment and found my request is added to a new function.
Thank you very much.

2023년 9월 6일 (수) 오후 10:05, barepixels ***@***.***>님이 작성:
