### ISSUE TITLE
stop downloading juggernaut or any model at all especially if its not 1st run , run without model loaded, so i can select on my own

### ISSUE THREAD

**Issue by 3blackbar** [lllyasviel/Fooocus#3186]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

thanks

### Proposed workflow

.

### Additional information

.

**Comment by mashb1t** [comment]
see
- https://github.com/lllyasviel/Fooocus/discussions/2681
- https://github.com/lllyasviel/Fooocus/discussions/2741
- https://github.com/lllyasviel/Fooocus/discussions/2392
- https://github.com/lllyasviel/Fooocus/discussions/1474
