### ISSUE TITLE
[Feature Request]: Can it support Intel Core Ultra processor

### ISSUE THREAD

**Issue by can-3308** [lllyasviel/Fooocus#3195]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Can it support Intel Core Ultra processor

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by can-3308** [comment]
CPU display&nbsp;Intel Arc graphics



发自我的iPhone


------------------ Original ------------------
From: Manuel Schmid ***@***.***&gt;
Date: Thu,Jun 27,2024 1:47 AM
To: lllyasviel/Fooocus ***@***.***&gt;
Cc: can-3308 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [lllyasviel/Fooocus] [Feature Request]: Can it support Intel CoreUltra processor (Issue #3195)





 
You can use any modern CPU when providing the argument --always-cpu.

**Comment by mashb1t** [comment]
Please find and follow instructions (non-official as they have not been confirmed, so handle with care!) in https://github.com/lllyasviel/Fooocus/pull/2120

**Comment by can-3308** [comment]
Okay, thank you. Does the official plan support integrated graphics cards for Ultra CPUs


Because I don't understand English and code



发自我的iPhone


------------------ Original ------------------
From: Manuel Schmid ***@***.***&gt;
Date: Thu,Jun 27,2024 2:33 AM
To: lllyasviel/Fooocus ***@***.***&gt;
Cc: can-3308 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [lllyasviel/Fooocus] [Feature Request]: Can it support Intel CoreUltra processor (Issue #3195)





 
Please find and follow instructions (non-official as they have not been confirmed, so handle with care!) in #2120

**Comment by mashb1t** [comment]
With `--always-cpu` it's already supported, but if you want to use graphics acceleration you have to follow these instructions. The instructions haven't received a sufficient amount of feedback by the community and i don't personally have an Intel ARC device, so more approval / testing is needed.
