### ISSUE TITLE
Runtime flags? Is there a way to disable cuda_malloc or xformers?

### ISSUE THREAD

**Issue by MichaelMartinez** [lllyasviel/Fooocus#32]
I have tried to run this project, but it takes 15 minutes to load into the UI each time.

Not sure what is causing it to be so slow, I do see that my GPU is never loaded. 

I have an older Dell Precision with 32GB of RAM and a Quadro P6000 with 24GB of vRAM.

I see messages in the terminal like this:` setting up memoryefficientcrossattention. query dim is 640, context_dim is 2048 and using 10 heads.` hundreds of them... followed by `adm` 

I think it has to do with some settings in comfyUI or possibly xformers, but I can't be sure until I am able to set some runtime flags.

**Comment by adriangalilea** [comment]
I'm having similar issues.

I'm using an A10 remotely and I get

```
Setting up MemoryEfficientCrossAttention. Query dim is 768, context_dim is 1280 and using 12 heads.
model_type EPS
adm 2560
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
```
Part of the output


Performance:
`2.87it/s`

**Comment by mashb1t** [comment]
We haven't experienced this kind of error in a while now. Please try again with the latest version of Fooocus and feel free to reopen if still relevant.
