### ISSUE TITLE
FOOOCUS online stopped working on Advanced Account

### ISSUE THREAD

**Issue by graziano1986** [lllyasviel/Fooocus#3200]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Fooocus was running normally, actually better and faster than most days, when suddenly a sort of "error connection" started to pop out during image generation. Then the UI disappeared and was replaced with an "error 404 not found" followed by a FAQ link with Japanese characters (?). I tried to refresh the page but it doesn't work. Signing out and in doesn't do anything too.
![Cattura](https://github.com/lllyasviel/Fooocus/assets/174063616/968a4765-2ea6-4d3f-80cc-4b7b8b494d2a)

I can't provide a Log since i don't have access to the program anymore.
The hilarious thing is: the free version and the Beta version seem to work fine as usually.

### Steps to reproduce the problem

Simply press the Fooocus online App
https://fooocus.one/apps

### What should have happened?

Fooocus should run normally as always

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (other)

### What operating system are you using?

Windows 7

### Console logs

```Shell
Cannot provide it, i cannot use the App anymore.
```

**Comment by mashb1t** [comment]
https://fooocus.one/apps is not an official Fooocus service, as a matter of fact there are no official Fooocus services, only 3rd party providers. Fooocus does not have a website and this repository is the single source of truth!
Please be aware that there are a lot of scam websites around and double-check the legitimacy of 3rd party vendors and cloud providers.

**Comment by mashb1t** [comment]
Feel free to use our Fooocus playbook in Google Colab though, as Google offers this for free. Instructions: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#colab

**Comment by graziano1986** [comment]
> Collaborator

Wait, so am i being scammed??

**Comment by graziano1986** [comment]
There's also a link in the home page to run Fooocus on Google Collab. If it is a scam, it's very well done i must admit.

**Comment by mashb1t** [comment]
https://fooocus.one/apps is not official, the only official thing Fooo us itself offers is a Colab playbook, which is guaranteed legit.

**Comment by graziano1986** [comment]
> https://fooocus.one/apps is not official, the only official thing Fooocus itself offers is a Colab playbook, which is guaranteed legit.

Thanks. But you know who runs the platform? should it be reported?
![Cattura](https://github.com/lllyasviel/Fooocus/assets/174063616/147702e6-6a13-4103-a50d-d722555747e8)

Also, in the billing section it is referred as "Anyone Ai"

**Comment by mashb1t** [comment]
No idea. Legit providers do have an address in their imprint and do offer some kind of contact information.

**Comment by graziano1986** [comment]
> No idea. Legit providers do have an address in their imprint and do offer some kind of contact information.

The Contact form is just not working automatically. I smell scam in here. I've been ingenuous i guess. Weel  maybe this will be usefull to others to not fall into this scam !

**Comment by mashb1t** [comment]
https://github.com/lllyasviel/Fooocus/discussions/2113
https://github.com/lllyasviel/Fooocus/discussions/2146
just leaving this here...

**Comment by DavidDragonsage** [comment]
Wow! Their demo is not even Fooocus, its AUTOMATIC1111.

**Comment by mashb1t** [comment]
=> https://github.com/lllyasviel/Fooocus/discussions/2146
