### ISSUE TITLE
[Feature Request]: Container image should include models instead of downloading them at startup

### ISSUE THREAD

**Issue by steren** [lllyasviel/Fooocus#3207]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

When using the official container image, it downloads models from Huggingface at startup.

This leads to a slow startup time and a slow first request even when using the default settings

it is also not very compatible with autoscaled cloud environments (notably if they scale to zero)

### Proposed workflow

The official container image should already bundle the models so that at startup, all that's needed to happen to use the default settings is load them in the GPU, instead of first precious spending time downloading them from the internet. 

### Additional information

This will lead to a larger container image, but the final size on disk will be equivalent

**Comment by mrhan1993** [comment]
Mount is a better solution

**Comment by mashb1t** [comment]
No, mounting is way more flexible as not every user needs the same model.
