### ISSUE TITLE
[Bug]: Error image prompt "Error Unexpected token '<', " <!DOCTYPE "... is not valid JSON"

### ISSUE THREAD

**Issue by yodi33** [lllyasviel/Fooocus#3209]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I would like to use the section Image prompt and nothing happen
Everytime a message appear "Error
Unexpected token '<', " <!DOCTYPE "... is not valid JSON"
Can you help me ?
I have a macboook
<img width="1406" alt="Capture d’écran 2024-06-29 à 21 34 17" src="https://github.com/lllyasviel/Fooocus/assets/174222336/3bbd57cb-3173-4f82-a2b9-b759457b1193">

### Steps to reproduce the problem

Select image prompt 
Choose one image and select face swap and choose an second image and select pyracanny and generate your model

### What should have happened?

In normal time my face ( 1st image) should be on body of the 2nd image

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### What operating system are you using?

MacOS Somona version 14.5

### Console logs

```Shell
?
```

**Comment by mashb1t** [comment]
Please provide the console / terminal logs (you can find the error messages there) and your system specifications. Also ensure you've followed the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) and your system fulfills the [minimum system specifications](https://github.com/lllyasviel/Fooocus), as it most likely is caused by too little RAM on the MPS backend.

**Comment by yodi33** [comment]
<img width="810" alt="Capture d’écran 2024-07-02 à 09 58 05" src="https://github.com/lllyasviel/Fooocus/assets/174222336/c045964a-26c6-4e8f-916e-288a1a2ecb33">
<img width="791" alt="Capture d’écran 2024-07-02 à 09 58 46" src="https://github.com/lllyasviel/Fooocus/assets/174222336/eb363852-c5f1-4634-8e0d-89e9cf5a555d">
<img width="304" alt="Capture d’écran 2024-07-02 à 10 00 38" src="https://github.com/lllyasviel/Fooocus/assets/174222336/c0e5c3c6-1049-4400-995e-85b3e4173adc">
I send you my console / Terminal logs
If you can help me with this information

**Comment by mashb1t** [comment]
You probably have too little RAM to run Fooocus as this is also shared as VRAM. The terminal logs might reflect that, so please check them out. If there is nothing logged, your Macbook might just not have the perfoemance to properly run Fooocus.

**Comment by yodi33** [comment]
How I can have a better RAM
maybe clean some app in my computer ?
