### ISSUE TITLE
log.html and gradio. lifehuck and suggestion

### ISSUE THREAD

**Issue by ptits** [lllyasviel/Fooocus#322]
May be I am stupid but I found no way to see log.html when using gradio. (--share)

Lifehuck: I see that Automatic1111 can open links like:
https://47c763360a19fc9500.gradio.live/file=/data/ptits/a1111/stable-diffusion-webui/outputs/txt2img-images/2023-09-07/

So, I set output path for FocusMRE то stable-diffusion-webui/outputs/txt2img-images/ and then I can open
https://47c763360a19fc9500.gradio.live/file=/data/ptits/a1111/stable-diffusion-webui/outputs/txt2img-images/2023-09-07/log.html with no problem

But I need to have Automatic working on sever.

I found no directory than gradio of FocusMRE can access, is there one? (like in Automatic). (searching for gr.Interface had now results)

Can you make default "outputs" directory be accessible from gradio?
Something like:
https://47c763360a19fc9500.gradio.live/file=/data/ptits/FocusMRE/outputs/2023-09-07/log.html

**Comment by MoonRide303** [comment]
@ptits This is issue list for vanilla Fooocus for problems related to vanilla - and it seems you're referring to Fooocus-MRE (which has separate issues list, available [here](https://github.com/MoonRide303/Fooocus-MRE/issues)).

I am not sure if I understood problem you're describing, but in MRE you have links to current and previous private log file available in the Misc tab:

![image](https://github.com/lllyasviel/Fooocus/assets/130458190/b7512e67-b4da-4498-a294-cc26277db279)

They're in format like that:
https://[your_random_string].gradio.live/file=./outputs/[YYYY-MM-DD]/log.html

It works fine in both --share mode, as well as on Colab.
