### ISSUE TITLE
[Feature Request]: upscaler model info metadata

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/Fooocus#3224]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

there is no log in CMD or in the image(meta-tag) which upscaler(modelname) is loaded or used ...
also would be nice steps and denoise info

### Proposed workflow

-

**Comment by mashb1t** [comment]
There is only one upscaler (fooocus_upscaler_s409985e5.bin with ESRGAN):

https://github.com/lllyasviel/Fooocus/blob/e8d88d3e250e541c6daf99d6ef734e8dc3cfdc7f/modules/upscaler.py#L15-L28

=> I don't see the need to add the upscaler model to the metadata.

Steps are already in metadata (also in history log if overridden).
Denoise strength would only be for inpaint, and metadata does not include parameters for img2img.

=> Won't do.

**Comment by kalle07** [comment]
i mean like this:

tEXtparameters woman portrait
Negative prompt: sketch , drawing, cartoon
Steps: 40, Sampler: DPM++ 2M Karras, CFG scale: 4.5, Seed: 3458746777, Size: 1024x1024, Model hash: 7873076e72, Model: SDXL_myown_Sevenof9_VAE, Denoising strength: 0.6, Clip skip: 1, **Hires upscale: 2, Hires steps: 20, Hires upscaler: R-ESRGAN 4x+, Extra noise: 0.1**, Version: f0.0.17v1.8.0rc-latest-278-gbfee03d8

but if you dont wont  okay   ^^
