### ISSUE TITLE
[Bug]: clip-skip 1 noisy

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/Fooocus#3230]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

some models usual with PONY stuff merged are NOISY on CLIP 1
in A1111 it is working fine ... where ist the differences how handle it there?
Clip2 is all ok

### Steps to reproduce the problem

Developer Debug Mode
set clip to 1
noisy pics with all 10 models (from different top pony-creators on civitai ... btw jugger run on clip1)

clip2 is okay for all

(clip 1 works with a1111)

### What should have happened?

-

### What browsers do you use to access Fooocus?

Mozilla Firefox

### Where are you running Fooocus?

Locally

### What operating system are you using?

win10

### Console logs

```Shell
-
```

**Comment by mashb1t** [comment]
Just trying to get your point: You're having issues using CLIP skip -1 with any model, including the default juggernaut v8 model?

**Comment by kalle07** [comment]
no, juggernaut and dreamshaper dont include pony stuff -> they run with clip 1
(the "pony" is my conclusion, there may be other reasons)

**Comment by mashb1t** [comment]
@kalle07 in their model description they write:

> Important information
Make sure you load this model with clip skip 2 (or -2 in some software), otherwise you will be getting low quality blobs.

**Comment by mashb1t** [comment]
A1111 handles clip skip somewhat different afaik, Fooocus aligns more with Comfy's handling.
