### ISSUE TITLE
[Bug]: docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]] - on Macbook Pro with M3 Max

### ISSUE THREAD

**Issue by rgaufman** [lllyasviel/Fooocus#3236]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I am trying to install foocus using the Docker method on a MacBook M3 Max, but I'm getting stuck here:

```
Romans-MacBook-Pro.local ➜  Fooocus git:(main) docker run -p 7865:7865 -v fooocus-data:/content/data -it \
--gpus all \
-e CMDARGS=--listen \
-e DATADIR=/content/data \
-e config_path=/content/data/config.txt \
-e config_example_path=/content/data/config_modification_tutorial.txt \
-e path_checkpoints=/content/data/models/checkpoints/ \
-e path_loras=/content/data/models/loras/ \
-e path_embeddings=/content/data/models/embeddings/ \
-e path_vae_approx=/content/data/models/vae_approx/ \
-e path_upscale_models=/content/data/models/upscale_models/ \
-e path_inpaint=/content/data/models/inpaint/ \
-e path_controlnet=/content/data/models/controlnet/ \
-e path_clip_vision=/content/data/models/clip_vision/ \
-e path_fooocus_expansion=/content/data/models/prompt_expansion/fooocus_expansion/ \
-e path_outputs=/content/app/outputs/ \
ghcr.io/lllyasviel/fooocus
Unable to find image 'ghcr.io/lllyasviel/fooocus:latest' locally
latest: Pulling from lllyasviel/fooocus
7021d1b70935: Pull complete
0d6448aff889: Pull complete
0a7674e3e8fe: Pull complete
b71b637b97c5: Pull complete
56dc85502937: Pull complete
2f5cd5b6e5c9: Pull complete
b3d479427715: Pull complete
43b25310092f: Pull complete
878e9865f694: Pull complete
cba07a8b8739: Pull complete
7b364e87a312: Pull complete
1f46eefcf978: Pull complete
f87d76f8a00c: Pull complete
4f4fb700ef54: Pull complete
679fc51d59cb: Pull complete
071908bbc3c2: Pull complete
Digest: sha256:42a88594d0f2a562e124c3708ea9962ad42b8e5241a8bc91c46de047f16cfa74
Status: Downloaded newer image for ghcr.io/lllyasviel/fooocus:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

### Steps to reproduce the problem

1. Run the docker run command in the instructions
2. Observe the error above

### What should have happened?

It should've started foocus in docker.

### Where are you running Fooocus?

Locally with virtualization (e.g. Docker)

### What operating system are you using?

MacOS 15.0

### Console logs

```Shell
As above.
```

**Comment by mashb1t** [comment]
Docker doesn't offer an API for using Metal as GPU or Apple restricts it. Please use the native installation method with the MPS backend (with GPU acceleration) OR use CPU only with `--always-cpu` (no acceleration).

Also see:
- https://github.com/ollama/ollama/issues/3517#issuecomment-2052680938
- https://github.com/pytorch/pytorch/issues/81224#issuecomment-1499741152
