### ISSUE TITLE
Perfect Seed Number [Bug]: 

### ISSUE THREAD

**Issue by riazuddinshaik** [lllyasviel/Fooocus#3242]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

@lllyasviel Thanks for awesome work. What is the best seed number for image generation (inpaint feature)? I tried many seed numbers and also allowed to generate random seed number but the image generation is not good. 

Could you suggest a best fixed seed number plz?

### Steps to reproduce the problem

Normal query

### What should have happened?

Normal query

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### What operating system are you using?

windows 10

### Console logs

```Shell
Normal query
```

### Additional information

Thanks for awesome work. What is the best seed number for image generation (inpaint feature)? I tried many seed numbers and also allowed to generate random seed number but the image generation is not good. 

Could you suggest a best fixed seed number plz?

**Comment by riazuddinshaik** [comment]
@mashb1t Thanks for awesome work. What is the best seed number for image generation (inpaint feature)? I tried many seed numbers and also allowed to generate random seed number but the image generation is not good.

Could you suggest a best fixed seed number plz?

**Comment by mashb1t** [comment]
There is no such thing as a "best seed", as the seed is only the starting point for random noisegeneration before denoising with samplers/schedulers based on the model and LoRAs. I'd strongly suggest you to experiment with these instead.

> [...] image generation is not good.

Please describe what's "not good" for you. Ensure you write a very detailed prompt and use the negative prompt + at best 1-2 styles as well as change the guidance scale if your prompt isn't followed.

This is not a bug but most likely lack of knowledge. A good starting point is https://stable-diffusion-art.com/beginners-guide/.
