### ISSUE TITLE
[Feature Request]: Can you add support for Kolors?

### ISSUE THREAD

**Issue by fyepi** [lllyasviel/Fooocus#3248]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

To support t2i etc. for Kolors, which has very good prompt understanding. 

https://github.com/Kwai-Kolors/Kolors

### Proposed workflow

n/a

**Comment by mashb1t** [comment]
No, as the model is not based on SDXL and Fooocus strictly supportd only SDXL and models based on it.
