### ISSUE TITLE
[Feature Request]: FreeU parameters

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/Fooocus#3250]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

only a hint maybe you know... 
(there are some parameter for tune a bit more

https://github.com/ljleb/sd-webui-freeu?tab=readme-ov-file

![grafik](https://github.com/lllyasviel/Fooocus/assets/118767589/ebccc7f7-bdfc-48c9-ad71-f4a6bc60edea)

### Proposed workflow

Developer Debug Mode
FreeU

**Comment by mashb1t** [comment]
https://github.com/lllyasviel/Fooocus/blob/5a71495822a11bbabf7c889eed6d9b38b261bb96/ldm_patched/contrib/external_freelunch.py#L27

Fooocus code (ldm backend) doesn't allow these parameters.
