### ISSUE TITLE
Image Prompt and Inpaint

### ISSUE THREAD

**Issue by riazuddinshaik** [lllyasviel/Fooocus#3273]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

 Hi. I tried to generate the printing name and logo by uploading image in image prompt with stp at 0.86 and weght 0.96 using "mix image prompt and inpaint" feature. I later masked the another tshirt image under inpaint section. The text and logo generated as weird. Its UNREADABLE. How to generate atleast 70-80%% of graphics? Thankyou.

### Steps to reproduce the problem

NA

### What should have happened?

N A

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### What operating system are you using?

windows 10

### Console logs

```Shell
NA
```

**Comment by mashb1t** [comment]
=> https://github.com/lllyasviel/Fooocus/discussions/3274
