### ISSUE TITLE
[Bug]: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by 8642xyz** [lllyasviel/Fooocus#3275]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Hello, does anyone had this issue before, after picture is generated I got a message in code at the end: 
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
Total time: 184.33 seconds

Does anyone have idea how to solve these?

### Steps to reproduce the problem

.

### What should have happened?

.

### Where are you running Fooocus?

None

### Console logs

```Shell
.
```

### Additional information

.

**Comment by mashb1t** [comment]
As you did not enter any details nobody is able to help you. Please provide these information and check if this reference helps you: https://github.com/lllyasviel/Fooocus/discussions/2593
