### ISSUE TITLE
[Feature Request]: Allow image generation without saving output (previews only mode)

### ISSUE THREAD

**Issue by steppres** [lllyasviel/Fooocus#3276]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

A fairly simple feature: A checkbox under [Debug Tools] that allows the user to generate images without saving them to an output folder or the log.html.

My reasoning for this feature is that image generation is a trial and error process (tweaking settings and seeing results). Sometimes a user session might be mostly experimentational.

Obviously the drawback is to having this feature available is the chance a user will unwittingly lose a generation they may have wanted saved.

### Proposed workflow

1. Go to [Debug Tools]
2. Select checkbox [Do not save output]
4. Generate image
5. Images are generated as previews only

### Additional information

[Disable Preview] and [Do not save output] would need to be mutually exclusive; selecting both would be pointless.

**Comment by mashb1t** [comment]
You can already achieve this using the startup argument `--disable-image-log`, which you can set separately for each session (Fooocus startup) and i'd recommend you to use 2 run.bat files for this, one without and one with image log. As this is a global setting, Fooocus has to be restarted when changing this.

For me there is no need to set this in the browser. Which arguments do you think are benificial for a change in the UI?

**Comment by steppres** [comment]
> You can already achieve this using the startup argument `--disable-image-log`, which you can set separately for each session (Fooocus startup) and i'd recommend you to use 2 run.bat files for this, one without and one with image log. As this is a global setting, Fooocus has to be restarted when changing this.
> 
> For me there is no need to set this in the browser. Which arguments do you think are benificial for a change in the UI?

I apologize, I wasn't aware of that startup argument, which is a much better solution (less risky) that an option in the UI. 

Thank you for following up. I'll make sure I'm more thorough next time 👍🏻
