### ISSUE TITLE
[Feature Request]: hiresfix/Upscale instantly

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/Fooocus#3279]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

if i generate an image it should be instantly upscaled without save the image and after that put an image in the image-prompt.
(for me drag and drop dont work inside the webui, is it a bug? (browser: firefox))

and if i load an fooocus generated png with desciption inside, is it possible to load the textprompt from that image?

### Proposed workflow

check input-image
Upscale or Variation
eg: Upscale (2x)

### Additional information

fooocus 2.4.3

**Comment by mashb1t** [comment]
=> now part of [v2.5.0-rc1](https://github.com/lllyasviel/Fooocus/releases/tag/v2.5.0-rc1), discussion in https://github.com/lllyasviel/Fooocus/discussions/3282, docs in https://github.com/lllyasviel/Fooocus/discussions/3281 (mirrored from https://github.com/mashb1t/Fooocus/discussions/42)

**Comment by mashb1t** [comment]
btw duplicate of https://github.com/lllyasviel/Fooocus/issues/3113
