### ISSUE TITLE
[Feature Request]: calc hash - again and again

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/Fooocus#3280]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

every time i start Fooocus it calculates hashes the first time i generate an image !?!
i checked it 3 times (close/kill/start fooocus) 
choose a model (docht change the name or any kind)
with 3 different models

after generating one image with eg 3 models (and has is generated) and than switch between models hash is not generated again, only if i kill foocus and try this again

### Proposed workflow

...

### Additional information

[Fooocus Model Management] Moving model(s) has taken 1.58 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 60/60 [00:22<00:00,  2.69it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.16 seconds
[Fooocus] Saving image 1/1 to system ...
Calculating sha256 for E:\FooocusControl\Fooocus\models\checkpoints\SDXL_myown_Sevenof9_VAE.safetensors: 7873076e727e64c17b22c7bcdb8c00b20051d9fb2c31866aea79fdcb13a6e370
Image generated with private log at: e:\FooocusControl\Fooocus\outputs\2024-07-14\log.html
Generating and saving time: 39.48 seconds

**Comment by mashb1t** [comment]
also part of [v2.5.0-rc1](https://github.com/lllyasviel/Fooocus/releases/tag/v2.5.0-rc1), implemented in + synched from https://github.com/mashb1t/Fooocus/discussions/47
