### ISSUE TITLE
[Bug]: "Press any key to continue" in the cmd.exe and then nothing happens

### ISSUE THREAD

**Issue by geol13** [lllyasviel/Fooocus#3300]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I download the zip file, now I have also the 2.5.0 Then I go and open it, click on run_realistic, then comes the DOS window, now it says something about the 2.5.0 and installing requirements. After opening this DOS window and showing the bar loading, then comes "Press any key to continue", I pressed the key, nothing happened and the window just closed, so no Fooocus was running..

### Steps to reproduce the problem

i don't know

### What should have happened?

Fooocus should run

### Where are you running Fooocus?

None

### Console logs

```Shell
https://ibb.co/Dzb4ZqL
https://ibb.co/kQWbCzc
```

**Comment by CulbearSays** [comment]
Follow the update instructions: #3295 and #3284

**Comment by mashb1t** [comment]
@geol13 you're trying to run Fooocus without adjustments, which tries to load the models using Nvidia drivers and you do not have Nvidia drivers installed.
Ensure you've installed Fooocus correctly using the installation method of your choice (see [readme](https://github.com/lllyasviel/Fooocus)) and your system is fulfilling the [minimum system specifications](https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement).
