### ISSUE TITLE
[Feature Request]: add Eular a sampler for pony models

### ISSUE THREAD

**Issue by bluntstone** [lllyasviel/Fooocus#3322]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Feature: a way to change sampler:
Why:  pony model use Euler a 
problem: dpmpp_2m_sde_gpu images don't look good. look bumpy and over fitted. 

### Proposed workflow

1. Go to .... Advanced
2. Press .... sampler dropdown
3. Choose:  euler a

### Additional information

**This is from the ponyv6 civitai page:**
Using Euler a with 25 steps and resolution of 1024px is recommended although model generally can do most supported SDXL resolution.

**Comment by mashb1t** [comment]
Feel free to change the sampler / steps in developer debug mode to whatever you like. You may even add a custom preset to persist your customisations.
dpmpp_2m_sde_gpu is deterministic and produces good results depenting on the prompt, while Euler A is ancestral (hence the name Euler A) and produces different resulte depending on the amount of steps.
I'd encourage you to check out different samplers.

SFW examples with all kinds of samplers/schedulers: https://civitai.com/models/257749?modelVersionId=290640
NSFW comparison: https://civitai.com/posts/1354301

Read more in https://stable-diffusion-art.com/samplers/

 => staying with dpmpp_2m_sde_gpu as default.

**Comment by bluntstone** [comment]
Maybe they will fix it in pony 7 . Right now results aren't great with
dpmpp. Not for realistic images. I will stay with automatic111 for now.
Thanks

**Comment by mashb1t** [comment]
> Maybe they will fix it in pony 7.
Fix what? As mentioned, feel free to experiment wnd change settings yourself.

**Comment by bluntstone** [comment]
I am willing. Do I just edit the pony v6 json file and add eular_a?

**Comment by mashb1t** [comment]
@bluntstone yes, that's it. I'd suggest to make a copy of the pony preset file and adjust this one to prevent issues when updating Fooocus in the future.

**Comment by bluntstone** [comment]
Ok will do. Thank you
