### ISSUE TITLE
[Bug]: WinError 127 when running run.bat

### ISSUE THREAD

**Issue by janag-ui** [lllyasviel/Fooocus#3324]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After following the installation instructions for Windows, the first and subsequent runs of Fooocus yield WinError 127 while trying to download the models.

I was able to work around the issue by instead following the installation instructions for Linux and then installing the right version of pytorch for my setup.

### Steps to reproduce the problem

1. Download latest Windows version of Fooocus (https://github.com/lllyasviel/Fooocus/releases/download/v2.5.0/Fooocus_win64_2-5-0.7z)
2. Unzip
3. Run run.bat (or any of its variants)

### What should have happened?

Download models then launch Foocus.

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11 Pro

### Console logs

```Shell
S:\AMD\Programs\Fooocus_win64_2-5-0>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.5.0
[Cleanup] Attempting to delete content of temp dir C:\Users\Player\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Downloading: "https://huggingface.co/mashb1t/misc/resolve/main/xl-to-v1_interposer-v4.0.safetensors" to S:\AMD\Programs\Fooocus_win64_2-5-0\Fooocus\models\vae_approx\xl-to-v1_interposer-v4.0.safetensors

Traceback (most recent call last):
  File "S:\AMD\Programs\Fooocus_win64_2-5-0\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "S:\AMD\Programs\Fooocus_win64_2-5-0\Fooocus\launch.py", line 140, in <module>
    config.default_base_model_name, config.checkpoint_downloads = download_models(
  File "S:\AMD\Programs\Fooocus_win64_2-5-0\Fooocus\launch.py", line 104, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae_approx, file_name=file_name)
  File "S:\AMD\Programs\Fooocus_win64_2-5-0\Fooocus\modules\model_loader.py", line 26, in load_file_from_url
    from torch.hub import download_url_to_file
  File "S:\AMD\Programs\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\torch\__init__.py", line 132, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "S:\AMD\Programs\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.

S:\AMD\Programs\Fooocus_win64_2-5-0>pause
Press any key to continue . . .
```

### Additional information

The file referenced by the error, c10_cuda.dll, did exist at that path. The AMD in the path are not a reference to AMD the graphics card vendor, rather they're my initials. I'm using an nVidia GeForce RTX 4090.

nVidia driver version: 551.78
CUDA version: 12.4
RAM size: 64GB
Swap file: enabled & 256GB

**Comment by mashb1t** [comment]
> CUDA version: 12.4

Ensure you use 12.1 with Fooocus. To do so, do one of the two following things:
- modify https://github.com/lllyasviel/Fooocus/blob/main/launch.py#L25 and set it to True, then execute run.bat
- run S:\AMD\Programs\Fooocus_win64_2-5-0\python_embeded\python.exe -m pip install torch==2.1.0 torchvision==0.16.0 --extra-index-url https://download.pytorch.org/whl/cu121

Please also update your Nvidia GPU driver and try again, it's a bit outdated.

I had no issues executing the run.bat after extracting the zip file with 7zip (use this and not any other unzipping tool), so cab't reproduce.
Thanks for your update after trying the steps mentioned above.

**Comment by janag-ui** [comment]
> Ensure you use 12.1 with Fooocus. To do so, do one of the two following things:
> 
> * modify https://github.com/lllyasviel/Fooocus/blob/main/launch.py#L25 and set it to True, then execute run.bat

I tried this. It downloaded and reinstalled pytorch but the error is the same.

> * run S:\AMD\Programs\Fooocus_win64_2-5-0\python_embeded\python.exe -m pip install torch==2.1.0 torchvision==0.16.0 --extra-index-url https://download.pytorch.org/whl/cu121

I tried this. Error was the same.
 
> Please also update your Nvidia GPU driver and try again, it's a bit outdated.

I upgraded to driver version 560.70 but same error. 

> I had no issues executing the run.bat after extracting the zip file with 7zip (use this and not any other unzipping tool), so cab't reproduce. Thanks for your update after trying the steps mentioned above.

I confirm that I used the 7zip program rather than other archiving software to unzip.

This _does_ fix it though:
```
S:\AMD\Programs\Fooocus_win64_2-5-0>python --version
Python 3.10.6
S:\AMD\Programs\Fooocus_win64_2-5-0>python -m venv env
S:\AMD\Programs\Fooocus_win64_2-5-0>env\Scripts\activate
(env) S:\AMD\Programs\Fooocus_win64_2-5-0>cd Fooocus
(env) S:\AMD\Programs\Fooocus_win64_2-5-0\Fooocus>pip install -r requirements_versions.txt
... installs requirements
(env) S:\AMD\Programs\Fooocus_win64_2-5-0\Fooocus>pip install torch torchvision --index-url https://download.pytorch.org/whl/cu124
... installs pytorch
(env) S:\AMD\Programs\Fooocus_win64_2-5-0\Fooocus>pip freeze
accelerate==0.32.1
addict==2.4.0
aiofiles==23.2.1
aiohttp==3.9.5
aiosignal==1.3.1
altair==5.3.0
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.4.0
async-timeout==4.0.3
attrs==23.2.0
certifi==2024.7.4
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.2.1
cycler==0.12.1
dnspython==2.6.1
einops==0.8.0
email_validator==2.2.0
exceptiongroup==1.2.2
fastapi==0.111.1
fastapi-cli==0.0.4
ffmpy==0.3.2
filelock==3.15.4
flatbuffers==24.3.25
fonttools==4.53.1
frozenlist==1.4.1
fsspec==2024.6.1
gradio==3.41.2
gradio_client==0.5.0
groundingdino-py==0.4.0
h11==0.14.0
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.0
huggingface-hub==0.24.0
humanfriendly==10.0
idna==3.7
imageio==2.34.2
importlib_metadata==8.0.0
importlib_resources==6.4.0
intel-openmp==2021.4.0
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
lazy_loader==0.4
lightning-utilities==0.11.5
llvmlite==0.43.0
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.1
mdurl==0.1.2
mkl==2021.4.0
mpmath==1.3.0
multidict==6.0.5
networkx==3.3
numba==0.60.0
numpy==1.26.4
omegaconf==2.3.0
onnxruntime==1.18.1
opencv-contrib-python-headless==4.10.0.84
opencv-python==4.10.0.84
opencv-python-headless==4.10.0.84
orjson==3.10.6
packaging==24.1
pandas==2.2.2
pillow==10.4.0
platformdirs==4.2.2
pooch==1.8.2
protobuf==5.27.2
psutil==6.0.0
pycocotools==2.0.8
pycparser==2.22
pydantic==2.8.2
pydantic_core==2.20.1
pydub==0.25.1
pygit2==1.15.1
Pygments==2.18.0
PyMatting==1.1.12
pyparsing==3.1.2
pyreadline3==3.4.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.9
pytorch-lightning==2.3.3
pytz==2024.1
PyYAML==6.0.1
referencing==0.35.1
regex==2024.5.15
rembg==2.0.57
requests==2.32.3
rich==13.7.1
rpds-py==0.19.0
safetensors==0.4.3
scikit-image==0.24.0
scipy==1.14.0
segment-anything==1.0
semantic-version==2.10.0
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
starlette==0.37.2
supervision==0.6.0
sympy==1.13.1
tbb==2021.13.0
tifffile==2024.7.2
timm==1.0.7
tokenizers==0.19.1
tomli==2.0.1
toolz==0.12.1
torch==2.3.1+cu121
torchaudio==2.3.1+cu121
torchmetrics==1.4.0.post0
torchsde==0.2.6
torchvision==0.18.1
tqdm==4.66.4
trampoline==0.1.2
transformers==4.42.4
typer==0.12.3
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
uvicorn==0.30.3
watchfiles==0.22.0
websockets==11.0.3
yapf==0.40.2
yarl==1.9.4
zipp==3.19.2
(env) S:\AMD\Programs\Fooocus_win64_2-5-0\Fooocus>python -s entry_with_update.py --preset realistic
... runs without issue
```
I'm not sure what the difference is vs. setting REINSTALL_ALL == True but it works.
