### ISSUE TITLE
How to stop loading refiner model every time I start Foocus?

### ISSUE THREAD

**Issue by tamal777** [lllyasviel/Fooocus#333]
I just want to use the base model. how to stop loading refiner model? If I set refiner model to none in advance settings it still load and the settings reverts back to default.

**Comment by MoonRide303** [comment]
Simplest way is using settings.json. You can copy "settings-no-refiner.json" to "settings.json" to change only that.

And if you wish to change other settings, like Advanced mode, saving metadata, or output format - you can copy "settings-example.json" with all the settings listed to settings.json, and then adjust it all to whatever you like.

**Comment by mashb1t** [comment]
Please test again with the latest version of Fooocus and let us know the results. This should work now.
