### ISSUE TITLE
[Bug]: System Crash BSOD due to Memory_Management 16GB RAM

### ISSUE THREAD

**Issue by Nic-Raf** [lllyasviel/Fooocus#3347]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I previously had no issues with Fooocus been using it for months, but after updating to the latest version, I've encountered a problem. Initially, the update seemed fine, but after a few days of use, the application began to cause my PC to crash with a Blue Screen of Death (BSOD) due to a `Memory_Management` error, even during starting the run.bat program. It appears to be related to RAM usage, as Task Manager shows that Fooocus is consuming nearly 98% of my RAM before the crash occurs. 

I have tried performing a clean installation of Fooocus, but that did not resolve the issue. I also consulted the troubleshooting guide, but it did not provide a solution. 

For context, I'm using the portable version of Fooocus to avoid environment errors and ensure portability.

Do I need to upgrade my RAM?

**Specs:**
- AMD Ryzen 5 3600 6-core Processor
- 16GB RAM
- Windows 10 Pro 22H2
- Nvidia RTX 2060

### Steps to reproduce the problem

1. Just run the portable version on a 16GB RAM.
2. Or maybe it's because of my system?

### What should have happened?

Fooocus should not system crash just like before

### What browsers do you use to access Fooocus?

Brave, Other

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 10 Pro

### Console logs

```Shell
E:\AI_Softwares\ImageGenerator\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.5.0
[Cleanup] Attempting to delete content of temp dir C:\Users\Nick-PC\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Total VRAM 6144 MB, total RAM 16315 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 3.41.2, however version 4.29.0 is available, please upgrade.
--------
model_type EPS
UNet ADM Dimension 2816
```

**Comment by mashb1t** [comment]
It seems like you do not have sufficient swap to offload VRAM/RAM to, see https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#system-swap. Please ensure you have 30-40GB of disk space left in order to generate images with this setup.

Upgrading your RAM will help to prevent this issue and will prevent the system from offloading that much, but upgrading your GPU (+RAM) is even more effective, so the models can be kept loaded in VRAM.

**Comment by Nic-Raf** [comment]
> It seems like you do not have sufficient swap to offload VRAM/RAM to, see https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#system-swap. Please ensure you have 30-40GB of disk space left in order to generate images with this setup.
> 
> Upgrading your RAM will help to prevent this issue and will prevent the system from offloading that much, but upgrading your GPU (+RAM) is even more effective, so the models can be kept loaded in VRAM.

This actually works. Thank you. I'm also planning to upgrade my system in the future.
