### ISSUE TITLE
Feature request: outpainting

### ISSUE THREAD

**Issue by lanyusan** [lllyasviel/Fooocus#335]
Since Fooocus aims at matching mj's simplicity and popular functions, I am wondering if there is any plan to add outpainting in Fooocus/Foooocus-MRE.

Simple top, left, bottom, right outpainting with some default settings would be sufficient.

**Comment by mashb1t** [comment]
outpainting has actually been implemented a few months ago.
Please check it out with the latest version of Fooocus and let us know the results.
