### ISSUE TITLE
Loras

### ISSUE THREAD

**Issue by KevinHashensborow** [lllyasviel/Fooocus#336]
when i put a loras into the lora folder i get these types of lines any idea  of why/fixes ? 

ERROR diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_out.0.weight shape '[640, 640]' is invalid for input of size 1638400

**Comment by TimothyAlexisVass** [comment]
It says right there in the error message.

`shape '[640, 640]' is invalid for input of size 1638400` means that the shape of the weight tensor for the attention layer in the diffusion model is not compatible with the input size.

This error can occur for a few reasons:
1.     The LoRA you are using is not compatible with the diffusion model you are trying to use it with.
2.     The LoRA you are using is corrupted or incomplete.
3.     The diffusion model you are trying to use the LoRA with is corrupted or incomplete.

**Comment by mashb1t** [comment]
Issue solved, @TimothyAlexisVass thank you for the feedback, much appreciated.
