### ISSUE TITLE
[error] 1.0.64 启动失败

### ISSUE THREAD

**Issue by CDJenson** [lllyasviel/Fooocus#337]
是不是要更新下 python_embeded ？

![image](https://github.com/lllyasviel/Fooocus/assets/22700161/c7ebd5dd-b77f-433f-91ea-e93646fb6d3c)

**Comment by lllyasviel** [comment]
file corrupted

**Comment by CDJenson** [comment]
> file corrupted

应该是更新fooocus_expansion.bin这个文件被打断过导致的，删掉项目再重新下载就可以了。

**Comment by CDJenson** [comment]
> file corrupted

网络不稳定，在下载fooocus_expansion.bin这个文件被打断过一次，应该是这个导致的，现在删掉项目再重新下载就可以正常跑了。
