### ISSUE TITLE
[Feature Request]: Using Florence 2 in describe option

### ISSUE THREAD

**Issue by thekingbalXD** [lllyasviel/Fooocus#3409]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

It will use Microsoft's Florence 2 as image description.

### Proposed workflow

Works as usual when you use the describe option.

### Additional information

Florence 2 demo:
https://huggingface.co/spaces/gokaygokay/Florence-2

**Comment by mashb1t** [comment]
BLIP-2 does still offer the best quality to performance ratio, especially as florence isn't made specifically for tagging an image as far as i could see.
