### ISSUE TITLE
[Bug]: No errors, not starting at all

### ISSUE THREAD

**Issue by TheChilliPL** [lllyasviel/Fooocus#3410]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

The UI does not start.

![image](https://github.com/user-attachments/assets/7291d9ef-4f43-49a6-aa0e-c20147372424)

### Steps to reproduce the problem

Download it, unpack, start `run.bat` or `run_anime.bat` or `run_realistic.bat`

### What should have happened?

Fooocus should start correctly

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
F:\Downloads\2024\2024-07\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset anime
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'anime']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.5.2
Loaded preset: F:\Downloads\2024\2024-07\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\Fooocus\presets\anime.json
[Cleanup] Attempting to delete content of temp dir C:\Users\Chilli\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Downloading: "https://huggingface.co/mashb1t/fav_models/resolve/main/fav/animaPencilXL_v500.safetensors" to F:\Downloads\2024\2024-07\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\Fooocus\models\checkpoints\animaPencilXL_v500.safetensors

100%|█████████████████████████████████████████████████████████████████████████████| 6.46G/6.46G [01:45<00:00, 66.0MB/s]
Total VRAM 3072 MB, total RAM 32718 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --always-normal-vram
Set vram state to: LOW_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 3GB : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.

F:\Downloads\2024\2024-07\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0>pause
Press any key to continue . . .
```

**Comment by mashb1t** [comment]
You're not meeting minimal system requirements: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement

min. VRAM for GTX 10xx is 6GB, you have 3GB.
