### ISSUE TITLE
[Feature Request]: Suggestions for adjusting log.html

### ISSUE THREAD

**Issue by aidec** [lllyasviel/Fooocus#3417]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

I found that log.html is very slow and often gets stuck.

I found that log.html is very slow and often gets stuck.
In the test, it was found that the [loading='lazy'] item caused the problem
It is recommended that this be removed in future versions

### Proposed workflow

Update modules/private_logger.py
line:109
item += f"<td><a href=\"{only_name}\" target=\"_blank\"><img src='{only_name}' onerror=\"this.closest('.image-container' ).style.display='none';\" loading='lazy'/></a><div>{only_name}</div></td>"

item += f"<td><a href=\"{only_name}\" target=\"_blank\"><img src='{only_name}' onerror=\"this.closest('.image-container' ).style.display='none';\" /></a><div>{only_name}</div></td>"

**Comment by mashb1t** [comment]
Lazy loading is very beneficial here as not all inages have to be loaded in order to use the bpage (non-blocking operation).
Imaging being in mobile phone accessing Fooocus through the internet in your home setup  or the cloud and clicking the history log link. Without lazy loading all inages would have to be loaded instantly and only then you'd see the page => extensive use of data, especially if you e.g. only want to see the latest image.

Woth lazy loading the browser takes care of determining the optimal time to download the image based on its proximity to the visible part of the screen.

=> Lazy loading will make things faster.

Feel free to adjust the code anyways in your fork or adjust it locally, but this is a won't do. I hope the explanation helped you to understand the reasoning behind the decision.

**Comment by aidec** [comment]
I understand the benefits of lazy load, but there seems to be something wrong with lazy here
Even if log.html only has 100 pictures, the browser will freeze for more than 10 seconds every time you scroll the scroll when log.html is opened, seriously affecting browsing


<50 items can be browsed smoothly
>100 will cause obvious lag.
>500 items, basically unable to browse

My guess is that a lot of data is in the DOM


rewritten a version
Change to using js and paging for rendering
This can retain the lazy effect and improve browsing performance.
For your reference

Sorry, my English is not very good. Please forgive me if I use inappropriate words.

`import os
import args_manager
import modules.config
import json
import urllib.parse

from PIL import Image
from PIL.PngImagePlugin import PngInfo
from modules.flags import OutputFormat
from modules.meta_parser import MetadataParser, get_exif
from modules.util import generate_temp_filename

log_cache = {}

def get_current_html_path(output_format=None):
    output_format = output_format if output_format else modules.config.default_output_format
    date_string, local_temp_filename, only_name = generate_temp_filename(folder=modules.config.path_outputs,
                                                                         extension=output_format)
    html_name = os.path.join(os.path.dirname(local_temp_filename), 'log.html')
    return html_name

def log(img, metadata, metadata_parser: MetadataParser | None = None, output_format=None, task=None, persist_image=True) -> str:
    path_outputs = modules.config.temp_path if args_manager.args.disable_image_log or not persist_image else modules.config.path_outputs
    output_format = output_format if output_format else modules.config.default_output_format
    date_string, local_temp_filename, only_name = generate_temp_filename(folder=path_outputs, extension=output_format)
    os.makedirs(os.path.dirname(local_temp_filename), exist_ok=True)

    parsed_parameters = metadata_parser.to_string(metadata.copy()) if metadata_parser is not None else ''
    image = Image.fromarray(img)

    if output_format == OutputFormat.PNG.value:
        if parsed_parameters != '':
            pnginfo = PngInfo()
            pnginfo.add_text('parameters', parsed_parameters)
            pnginfo.add_text('fooocus_scheme', metadata_parser.get_scheme().value)
        else:
            pnginfo = None
        image.save(local_temp_filename, pnginfo=pnginfo)
    elif output_format == OutputFormat.JPEG.value:
        image.save(local_temp_filename, quality=95, optimize=True, progressive=True, exif=get_exif(parsed_parameters, metadata_parser.get_scheme().value) if metadata_parser else Image.Exif())
    elif output_format == OutputFormat.WEBP.value:
        image.save(local_temp_filename, quality=95, lossless=False, exif=get_exif(parsed_parameters, metadata_parser.get_scheme().value) if metadata_parser else Image.Exif())
    else:
        image.save(local_temp_filename)

    if args_manager.args.disable_image_log:
        return local_temp_filename

    html_name = os.path.join(os.path.dirname(local_temp_filename), 'log.html')

    css_styles = (
        "<style>"
        "body { background-color: #121212; color: #E0E0E0; font-family: Arial, sans-serif; } "
        "a { color: #BB86FC; } "
        ".metadata { border-collapse: collapse; width: 100%; } "
        ".metadata .label { width: 15%; } "
        ".metadata .value { width: 85%; font-weight: bold; } "
        ".metadata th, .metadata td { border: 1px solid #4d4d4d; padding: 4px; } "
        ".image-container img { height: auto; max-width: 512px; display: block; padding-right:10px; } "
        ".image-container div { text-align: center; padding: 4px; } "
        "hr { border-color: gray; } "
        "button { background-color: #BB86FC; color: #000; border: none; border-radius: 5px; padding: 10px 15px; text-align: center; display: inline-block; font-size: 16px; cursor: pointer; margin: 5px; } "
        "button:hover { background-color: #3700B3; color: #fff; }"
        "#log-container { margin-bottom: 20px; } "
        "#pagination { text-align: center; margin-top: 20px; }"
        ".page-button { background-color: #3700B3; color: #fff; border: none; border-radius: 5px; padding: 5px 10px; margin: 0 5px; cursor: pointer; }"
        ".page-button.active { background-color: #BB86FC; color: #000; }"
        "</style>"
    )

    js = (
        """<script>
        let logData = [];
        let currentPage = 1;
        const itemsPerPage = 25;

        function to_clipboard(txt) { 
            txt = decodeURIComponent(txt);
            if (navigator.clipboard && navigator.permissions) {
                navigator.clipboard.writeText(txt)
            } else {
                const textArea = document.createElement('textArea')
                textArea.value = txt
                textArea.style.width = 0
                textArea.style.position = 'fixed'
                textArea.style.left = '-999px'
                textArea.style.top = '10px'
                textArea.setAttribute('readonly', 'readonly')
                document.body.appendChild(textArea)

                textArea.select()
                document.execCommand('copy')
                document.body.removeChild(textArea)
            }
            alert('Copied to Clipboard!\\nPaste to prompt area to load parameters.\\nCurrent clipboard content is:\\n\\n' + txt);
        }

        function renderLogItem(item) {
            return `
                <div id="${item.divName}" class="image-container">
                    <hr>
                    <table>
                        <tr>
                            <td>
                                <a href="${item.imageName}" target="_blank">
                                    <img src='${item.imageName}' loading='lazy' onerror="this.closest('.image-container').style.display='none';" />
                                </a>
                                <div>${item.imageName}</div>
                            </td>
                            <td>
                                <table class='metadata'>
                                    ${item.metadata.map(([label, key, value]) => `
                                        <tr>
                                            <td class='label'>${label}</td>
                                            <td class='value'>${typeof value === 'string' ? value.replace(/\\n/g, ' </br> ') : value}</td>
                                        </tr>
                                    `).join('')}
                                    ${item.fullPromptDetails ? `
                                        <tr>
                                            <td class='label'>Full raw prompt</td>
                                            <td class='value'>${item.fullPromptDetails}</td>
                                        </tr>
                                    ` : ''}
                                </table>
                                </br>
                                <button onclick="to_clipboard('${item.clipboardData}')">Copy to Clipboard</button>
                            </td>
                        </tr>
                    </table>
                </div>
            `;
        }

        function renderPage(page) {
            const startIndex = (page - 1) * itemsPerPage;
            const endIndex = startIndex + itemsPerPage;
            const pageItems = logData.slice(startIndex, endIndex);
            
            let html = '';
            for (let item of pageItems) {
                html += renderLogItem(item);
            }
            
            document.getElementById('log-container').innerHTML = html;
        }

        function renderPagination() {
            const totalPages = Math.ceil(logData.length / itemsPerPage);
            let paginationHtml = '';
            
            for (let i = 1; i <= totalPages; i++) {
                paginationHtml += `<button class="page-button ${i === currentPage ? 'active' : ''}" onclick="changePage(${i})">${i}</button>`;
            }
            
            document.getElementById('pagination').innerHTML = paginationHtml;
            document.getElementById('pagination-top').innerHTML = paginationHtml;
        }

        function changePage(page) {
            currentPage = page;
            renderPage(currentPage);
            renderPagination();
        }

        function initPagination() {
            renderPage(currentPage);
            renderPagination();
        }

        function addLogItem(item) {
            logData.unshift(item);
            initPagination();
        }
        function scrollToTop() {
            window.scrollTo({ top: 0, behavior: 'smooth' });
        }

        window.onload = initPagination;
        </script>"""
    )

    begin_part = f"<!DOCTYPE html><html><head><title>Fooocus Log {date_string}</title>{css_styles}</head><body>{js}<h1>Fooocus Log {date_string} (private)</h1>\n<p>Metadata is embedded if enabled in the config or developer debug mode. You can find the information for each image in line Metadata Scheme.</p><div id='pagination-top'></div><div id='log-container'></div><div id='pagination'></div> <button id=\"to-top-button\" onclick=\"scrollToTop()\">To Top</button>\n\n"
    end_part = f'\n<script>initPagination();</script></body></html>'

    div_name = only_name.replace('.', '_')
    
    full_prompt_details = ""
    if task is not None and 'positive' in task and 'negative' in task:
        full_prompt_details = f"""<details><summary>Positive</summary>{', '.join(task['positive'])}</details>
        <details><summary>Negative</summary>{', '.join(task['negative'])}</details>"""

    js_txt = urllib.parse.quote(json.dumps({k: v for _, k, v, in metadata}, indent=0), safe='')
    
    new_item = {
        "divName": div_name,
        "imageName": only_name,
        "metadata": metadata,
        "fullPromptDetails": full_prompt_details,
        "clipboardData": js_txt
    }

    log_data = log_cache.get(html_name, [])
    log_data.insert(0, new_item)
    log_cache[html_name] = log_data

    with open(html_name, 'w', encoding='utf-8') as f:
        f.write(begin_part + '<script>logData = ' + json.dumps(log_data) + ';</script>' + end_part)

    print(f'Image generated with private log at: {html_name}')

    return local_temp_filename`

[private_logger.zip](https://github.com/user-attachments/files/16457054/private_logger.zip)
[c.txt](https://github.com/user-attachments/files/16457055/c.txt)
