### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by revolvedai** [lllyasviel/Fooocus#342]
Hello! Can we get a dark mode version of the app? Would make it nice without requiring the user to switch their browser theme. Thanks for the amazing app!

**Comment by Crypto-Spartan** [comment]
See #327

**Comment by NewEpoch2020** [comment]
You can modify the webui.py file like below to automatically start Dark Mode：

`import webbrowser
webbrowser.open(f"http://{args_manager.args.listen}:{args_manager.args.port}/?__theme=dark")

shared.gradio_root.launch(
    # inbrowser=args_manager.args.auto_launch,
    server_name=args_manager.args.listen,
    server_port=args_manager.args.port,
    share=args_manager.args.share,
)`
