### ISSUE TITLE
[Bug]: API do not create Images

### ISSUE THREAD

**Issue by lionelgoodboy** [lllyasviel/Fooocus#3422]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

hi everyone! I instaled gradio client and tested same API , but no success creating the images here.
There is no error, i call it using windows prompt, for example: python test.py

But, how to create the images using those apis? No images has been created in output folder. And I tryed a lot of function index of the API.

from gradio_client import Client

client = Client("http://127.0.0.1:7865/")
result = client.predict(
fn_index=0
)
print(result)

Thanks for any help! ;)

### Steps to reproduce the problem

1. Install gradio client
2. Copy some API exemplo from Fooocus "Use the API" bottom link. 
3. Save the api code in a file, lets say "test.py".
4. Open CMD on windows, e type: python test.py

it appears it is fine, but no image is created :(

### What should have happened?

I think this API call should create the images.

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
no applicable
```

**Comment by mashb1t** [comment]
This is not how it works, you have to replace images in parameters with their base64 representation. Outdated example: see https://github.com/toutjavascript/FoooXus-Fooocus-Extender/blob/main/src/api.py#L39 and examples in whole file
