### ISSUE TITLE
[Feature Request]: Add Support for Flux models

### ISSUE THREAD

**Issue by Amin-nem** [lllyasviel/Fooocus#3424]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Any plans to add support for the new Flux Models.

### Proposed workflow

1. Go to Presets
2. Select Flux

**Comment by mashb1t** [comment]
Similar to https://github.com/lllyasviel/Fooocus/issues/2984 + Flux needs a high amount of VRAM, which the majority of users doesn't have.
Fooocus currently supports SDXL only (no support for SD3 yet) and does not use diffusers + there are no ControlNets / IP adapters yet for Flux => 3/4 of the functionality if not even more will straight up not even work.


=> Won't do (for now)

**Comment by Wontfallo** [comment]
> Similar to #2984 + Flux needs a high amount of VRAM, which the majority of users doesn't have. Fooocus currently supports SDXL only (no support for SD3 yet) and does not use diffusers + there are no ControlNets / IP adapters yet for Flux => 3/4 of the functionality if not even more will straight up not even work.
> 
> => Won't do (for now)

Sounds like Foooocus needs to STEP IT UP!  Falling behind. Why the hell is ComfyUI the defacto for FLUX? I HATE ComfyUI what a dumb UX, so unnecessary.  Get SD3, FLUX and SAM2 in there, COME ON, LETS GO!!  WHAT ARE YOU WAITING FOR?

**Comment by mashb1t** [comment]
@Wontfallo see https://github.com/lllyasviel/Fooocus/discussions/3504 + readme. Fooocus is in bugfix support only and can be regarded as a complete project with no known bugs prioritized critical or high.
Feel free to switch to a fork of Fooocus, which supports  some of the models you've requested, such as SimpleSDXL or RuinedFooocus.
Feel free to add support to this repository though by contributing the implementation via Pull Request.
