### ISSUE TITLE
Same basic UI for TI/Lora training?

### ISSUE THREAD

**Issue by aolko** [lllyasviel/Fooocus#344]
Can you make the same basic UI for TI/Lora training? It would greatly benefit people and allow novices to finally effortlessly train their own TIs/Loras.

**Comment by mashb1t** [comment]
There are already great UIs out there, see https://github.com/bmaltais/kohya_ss

**Comment by aolko** [comment]
> There are already great UIs out there, see https://github.com/bmaltais/kohya_ss

it's not great, it's an equivalent of sticks bound with manure

**Comment by mashb1t** [comment]
i mean, it does the trick and training for SDXL LoRAs at least is possible + quality is great ^^
You can find tutorials [here](https://github.com/bmaltais/kohya_ss?tab=readme-ov-file#tutorials)

**Comment by aolko** [comment]
the whole configuration step is just some bonkers voodoo, for most people, dataset creation could be built in the ui, as well as labelling
