### ISSUE TITLE
Would width and height inputs be possible? [Feature Request]: 

### ISSUE THREAD

**Issue by MarkBowenPiano** [lllyasviel/Fooocus#3462]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

I was wondering if instead of having all the aspect ratios set as radio buttons _(admitted we can add our own in the setting file)_ if we could also perhaps have a width and height input box so that we could use any size that we wanted? Obviously I know we can't go too big as then with certain images AI starts to go a bit wonky but would be great to be able to test with different aspect ratios without needing to keep on adding them to the settings file?

### Proposed workflow

1) Settings page within Fooocus
2) Have a radio button to either choose from existing aspect ratios (those set in settings file) or to 'input' our own.
3) If 'Input' is chosen then height and width input fields appear allowing us to input whatever we want.

**Comment by MarkBowenPiano** [comment]
Apologies I've just come across something in the Advanced settings which might address this issue? Forced overwrite of generating width and the height one too?

I hadn't ventured that far down into the settings yet so if this is indeed what I'm after then apologies.

**Comment by Xyperion** [comment]
Hello did you find that specialization ? Like can we adjust image size bigger? Like 3840 x 2160 pixel etc.
