### ISSUE TITLE
[Feature Request]: Add a "balanced" option in the performance section to sit between quality and speed

### ISSUE THREAD

**Issue by bigfordy1983** [lllyasviel/Fooocus#3476]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

In flags.py, modify the enums as follows to provide a "balanced" performance that sits in between quality and speed. I have found this actually produces favourable results in my own testing:

class PerformanceLoRA(Enum):
    QUALITY = None
    BALANCED = None
    SPEED = None
    EXTREME_SPEED = 'sdxl_lcm_lora.safetensors'
    LIGHTNING = 'sdxl_lightning_4step_lora.safetensors'
    HYPER_SD = 'sdxl_hyper_sd_4step_lora.safetensors'

class Steps(IntEnum):
    QUALITY = 60
    BALANCED = 45
    SPEED = 30
    EXTREME_SPEED = 8
    LIGHTNING = 4
    HYPER_SD = 4

    @classmethod
    def keys(cls) -> list:
        return list(map(lambda c: c, Steps.__members__))

class StepsUOV(IntEnum):
    QUALITY = 36
    BALANCED = 24
    SPEED = 18
    EXTREME_SPEED = 8
    LIGHTNING = 4
    HYPER_SD = 4

class Performance(Enum):
    QUALITY = 'Quality'
    BALANCED = 'Balanced'
    SPEED = 'Speed'
    EXTREME_SPEED = 'Extreme Speed'
    LIGHTNING = 'Lightning'
    HYPER_SD = 'Hyper-SD'

### Proposed workflow

During advanced selection select the balanced option from performance settings before generating the image

**Comment by p1agnut** [comment]
Is this really necessary since you can freely set the sampling steps from 0 to 200 in the “Developer Debug Mode” menu?

**Comment by mashb1t** [comment]
Hey @bigfordy1983, thanks for the input but i totally agree with @p1agnut. While this is the easiest way for useers to select a specific amount of steps as new performance, there are already other ways to customize and adjust the step count to your needs:

- override the step count in developer debug mode
- use a preset and set the override steps in there to easily switch

Closing this issue aka. PR in disguise, but thanks nevertheless for your contribution.

**Comment by bigfordy1983** [comment]
All good, no problem @mashb1t @p1agnut. I agree its just a quality of life feature for those that don't have the confidence to do it for themselves via overrides and debugs, even though subjectively the setting does produce the best and most accurate images over and above the standard offerings.

Thank you for your support as always.

**Comment by XDM-Inc** [comment]
Question on this. i also made a custom flags.py file and back it up each time before updating the app. i was wondering if its possible that I can place these settings in the config.txt file for persistence? i wonder if it will take the formatting? i have added custom things to the config file before and it worked but not a class entity. the gradio engine is flexible but complicated.
