### ISSUE TITLE
[Feature Request]: LoRA notification support in prompt array

### ISSUE THREAD

**Issue by gadolinium157** [lllyasviel/Fooocus#3485]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

I will be happy if I could use array by specifying LoRAs and those weights in prompt.
For example:
`a cat, <lora:[[A, B]]>`
above prompt will be expanded 2 prompts `a cat, <lora:A>` and `a cat, <lora:B>`
`a cat, <lora:A:[[0.1,0.2,0.3]]>`
above prompt will be expanded 3 prompts `a cat, <lora:A:0.1>`, `a cat, <lora:A:0.2>` and `a cat, <lora:A:0.3>`
I have already tried them in the latest Fooocus, but those weren't expanded as I expected.
I also have tried array like `a cat, [[<lora:A>, <lora:B>]]` and `a cat, [[<lora:A:0.1>,<lora:A:0.2>,<lora:A:0.3>]]`, but these weren't the solutions. 
I'm sorry for my poor English.

### Proposed workflow

1. Go to prompt textbox and write a prompt using array like above examples.
2. Check "Advanced" checkbox below the prompt textbox.
3. Specify # of image at "Image Number" slider.
4. Press "Generate" button.
5. Prompt will be expanded as described above and Fooocus will generate multiple images.

**Comment by mashb1t** [comment]
Been there, done that, the only possible solution drastically slows everything down, as the patched unet can't be reused and has to be patched from scratch for ewch image again: https://github.com/lllyasviel/Fooocus/pull/2966#issue-2306090209

It's possible but very impractical and slow => won't do
