### ISSUE TITLE
I used the JavaScript API call but there was no response

### ISSUE THREAD

**Issue by 6666665** [lllyasviel/Fooocus#351]
This is my code：

import { client } from "@gradio/client";
const list = await client("http://127.0.0.1:7860/",{normalise_files:false});
const result = await list.predict(4, [
    "car", // string  in 'parameter_8' Textbox component		
    "", // string  in 'Negative Prompt' Textbox component		
    "None", // string  in 'parameter_23' Radio component		
    "Speed", // string  in 'Performance' Radio component		
    "704×1408", // string  in 'Aspect Ratios (width × height)' Radio component		
    1, // number (numeric value between 1 and 32) in 'Image Number' Slider component		
    5, // number  in 'Seed' Number component		
    0, // number (numeric value between 0.0 and 30.0) in 'Sampling Sharpness' Slider component		
    "sd_xl_refiner_1.0.safetensors", // string (Option from: ['sd_xl_refiner_1.0.safetensors', 'sd_xl_refiner_1.0_0.9vae.safetensors', 'sd_xl_base_1.0_0.9vae.safetensors']) in 'SDXL Base Model' Dropdown component		
    "None", // string (Option from: ['None', 'sd_xl_refiner_1.0.safetensors', 'sd_xl_refiner_1.0_0.9vae.safetensors', 'sd_xl_base_1.0_0.9vae.safetensors']) in 'SDXL Refiner' Dropdown component		
    "None", // string (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 1' Dropdown component		
    -2, // number (numeric value between -2 and 2) in 'Weight' Slider component		
    "None", // string (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 2' Dropdown component		
    -2, // number (numeric value between -2 and 2) in 'Weight' Slider component		
    "None", // string (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 3' Dropdown component		
    -2, // number (numeric value between -2 and 2) in 'Weight' Slider component		
    "None", // string (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 4' Dropdown component		
    -2, // number (numeric value between -2 and 2) in 'Weight' Slider component		
    "None", // string (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 5' Dropdown component		
    -2,   // number (numeric va
]);

console.log(result.data);

![微信图片_20230912204940](https://github.com/lllyasviel/Fooocus/assets/44966362/adb3f0b1-84bc-44f2-90ff-5037d8cc57c5)

**Comment by KubeLouis** [comment]
the same
but I got them at the folder
can the img added in res?

**Comment by mashb1t** [comment]
Please test again with the latest version of Fooocus and let us know the results. Shouzld have been implemented, but i'm not personally using the API. Feel free to reopen if necessary, looking forward to your feedback.
