### ISSUE TITLE
Extension for Automatic1111? 

### ISSUE THREAD

**Issue by Maki9009** [lllyasviel/Fooocus#354]
I know the whole point of Fooocus is to be simpler than Auto... but but Fooocus manages to creates Really nice images with such low effort, it would be nice to have an extension for it to perhaps use its magic into Auto for the users who want extended flexibility

**Comment by thundercat71** [comment]
https://github.com/thundercat71/Automatic1111-Fooocus-Styles

**Comment by Maki9009** [comment]
but this is just the styles, it isnt the same weird voodoo magic fooocus does you know

**Comment by Maki9009** [comment]
i want the same rendering ability...

**Comment by mashb1t** [comment]
Sorry to say, but this doesn't make sense. The whole backend is different from A1111 and there are almost no reusable parts. Using an iframe integration also does only lead to ressources being used up double, 6-8GB for each tool and SDXL model.
Closing this issue but appreciate the contribution of the idea.
