### ISSUE TITLE
Some LoRAs causing high VRAM usage

### ISSUE THREAD

**Issue by MoonRide303** [lllyasviel/Fooocus#356]
@lllyasviel Changes introduced in v2.0.0 caused increased VRAM usage with some LoRAs (like [Bloodstained XL](https://civitai.com/models/118889/bloodstained-xl)). It's LoRA smaller than 10 MB, but it almost doubles VRAM usage (eating about 12 GB of VRAM on 4080).

No such problems observed (with the same LoRA) in v1.0.67 - staying under 8 GB on this version.

**Comment by lllyasviel** [comment]
cannot reproduce - i can load  Bloodstained XL+"sai offset" on 8GB card and the vram use is 5.9GB

**Comment by lllyasviel** [comment]
I pushed a seemly fix see if works https://github.com/lllyasviel/Fooocus/pull/357

**Comment by MoonRide303** [comment]
Seems to be working  - VRAM usage with this test LoRA back to normal in v2.0.3.

**Comment by lllyasviel** [comment]
can you also test reverted 2.0.4 at 7700276b5013ff6a4ce9776bfe6b6919326654b0

**Comment by MoonRide303** [comment]
@lllyasviel v2.0.4 works fine, too 👍.

**Comment by MoonRide303** [comment]
@lllyasviel v2.0.4 (I just checked latest dev) seems to be fine, too.
