### ISSUE TITLE
[Bug]: Letters S,R,F and sometimes Capital Letters not working

### ISSUE THREAD

**Issue by PheonixAi420** [lllyasviel/Fooocus#3568]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

Okay so this happens a lot, and I have reported it before but its been a few months with no fix. Apparently it has something to do with the shortcut keys to the inpaint tab. I have to copy and paste letters S and R from other words to change my prompt and using the letter F unselects the prompt window completely. For instance if you want to type out "Detailed Face" you will get Detailed but as soon as you hit the F key for Face it deselects the prompt area. This is very annoying and I dont know if other people have this issue or not and I know what you are thinking but it is not my keyboard it is new and works 100% on any other website and stable diffusion. Also I think Mashbit said it was because I hovered over the inpaint window while typing and it recognizes those keys as shortcuts but that is not the problem. Can we address this soon? 

### Steps to reproduce the problem

open fooocus and type letters S,R,F sometimes it happens very quickly within the first 5 minutes of opening and some longer

### What should have happened?

The S,R,F keys should work.

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

windows 11

### Console logs

```Shell
No logs
```

### Additional information

Yes

**Comment by linus74** [comment]
If I understand correctly, and it is a problem I also have, it originates from the position of the mouse arrow remaining on the inpaint image area. By moving the position of the mouse arrow out of the image area, you will see that all the buttons on the keyboard will work. However, it is a bug that can perhaps be fixed.
If I misunderstood the problem, I apologise in advance!

**Comment by linus74** [comment]
If I understand correctly, and it is a problem I also have, it originates from the position of the mouse arrow remaining on the inpaint image area. By moving the position of the mouse arrow out of the image area, you will see that all the buttons on the keyboard will work. However, it is a bug that can perhaps be fixed.
If I misunderstood the problem, I apologise in advance!

**Comment by PheonixAi420** [comment]
That is not the case for me. It happens for me when the input image section is unchecked and the inpaint area is not visible, I even moved the mouse completely off screen and it still happens but if I open a new tab the letters work perfectly in google search and other websites. It is extremely annoying when you want to change prompts and you have to type a prompt in google search and copy and paste it to the prompt window in Fooocus. I appreciate the response but it seems I am having a worse issue than simply moving the cursor away from the inpaint area. I do hope the bug gets fixed soon, I prefer Fooocus over Stable Diffusion but it makes me want to use SD because it doesn't have issues with letters not being recognized.

**Comment by PheonixAi420** [comment]
So since mashbit left to spend time with family (not sure) I am closing this issue because there will probably not be any fix for it in the future. So I just uninstalled it and sticking with Stable Diffusion Forge because I am more interested in Flux quality now. It was fun while it lasted Fooocus.
