### ISSUE TITLE
[Feature Request]: Flux support?

### ISSUE THREAD

**Issue by KKuehlem** [lllyasviel/Fooocus#3587]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

I recently saw a discussion for A1111 to include Flux support (https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/16314). I wondered if there are any plans to add Flux support for Fooocus?

### Proposed workflow

-

**Comment by Aerthlyomi** [comment]
Apparently you missed some results in that search. A number of posts over the last weeks have been done about that: Fooocus is in IT Death aka mature product with a stable code but no evolution planned.

At the moment at least, but since no one has taken over the code, likely to remain like this.

**Comment by mashb1t** [comment]
=> use https://github.com/metercai/SimpleSDXL

**Comment by KKuehlem** [comment]
Thanks!
