### ISSUE TITLE
[Feature Request]: Support for [FLUX] (can't be the only one who wants this)

### ISSUE THREAD

**Issue by JonnyJV** [lllyasviel/Fooocus#3605]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Add support for FLUX models (unet/gguf/nf4), even if doing so means we have to live without live previews.

### Proposed workflow

1. unet checkpoint loader (model)
2. clip loader (t5/clip_l)
3. (vae loader (ae.sft)
4. next step varies, depending on whether its gguf or safetensor, etc
5. the rest is similar to SD

**Comment by freelancer2000** [comment]
@JonnyJV Fooocus won't be getting anymore updates as Illyasviel has dropped out from developing further. Vlad is now taken over but he already has Automatic so would not see why he'd work on two projects in parallel. Automatic already has support for FLUX.

**Comment by JonnyJV** [comment]
Thanks for the reply, and letting me know. I actually didn't know that. I'll give you one good reason why he shouldn't, but not necessarily why he wouldn't: because the way I see it playing out is basically: ComfyUI/Swarm Users, Fooocus (branches but 2.5 IMO has highest mass-adoption appeal due to midjourney-like similarity), and "everything else (A111)" when is the last time anyone preferred the latter over any of the former UIs?

**Comment by freelancer2000** [comment]
Again, family and private life will come first.
https://github.com/lllyasviel/Fooocus/discussions/3504

**Comment by JonnyJV** [comment]
> Again, family and private life will come first. #3504

yeah, no doubt, i would do the same thing.

**Comment by mashb1t** [comment]
I'm not Vladmandic, but Fooocus is in security maintenance only mode, so no new features.
