### ISSUE TITLE
[Feature Request]:    custom step count , sampler and scheduler  choice dropdown  in settings tab 

### ISSUE THREAD

**Issue by RanjithGadde447** [lllyasviel/Fooocus#3633]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

it allows the use of different samples not only fixed samplers but customer steps as per need 

### Proposed workflow

go to advanced tab below there should be a tab for the custom steps count input field and samplers selection drop-down and scheduler dropdown these all in one tab in the settings tab  above the image count

**Comment by mashb1t** [comment]
already exists in advanced > developer debug mode

**Comment by RanjithGadde447** [comment]
i asked it to appear in first page  not going ing into developer mode

**Comment by mashb1t** [comment]
This is not relevant for most users. feel free to move the options in your fork.
