### ISSUE TITLE
slow generation after first image

### ISSUE THREAD

**Issue by K1ngOfCurses** [lllyasviel/Fooocus#365]
when focus first came out and i was using it for a couple of updates, all 4 of my images would have the same generation time, however i updated it after a while and when i used it for some reason after the first image which is 2mins, the image after that becomes like 40min to generate. i have 3060 6gb vram, but like i said when i first used it they were all the same amount of time, dont know what changed

**Comment by lllyasviel** [comment]
degrade nvidia driver to 517

**Comment by K1ngOfCurses** [comment]
my game driver? does that mean it always needs to be 517

**Comment by lllyasviel** [comment]
are you using official Fooocus?

**Comment by K1ngOfCurses** [comment]
yeah

**Comment by lllyasviel** [comment]
In readme:

Besides, Nvidia driver above 532 is sometimes 10x slower than Nvidia driver 531. If your generation time is very long, consider download [Nvidia Driver 531 Laptop](https://www.nvidia.com/download/driverResults.aspx/199991/en-us/) or [Nvidia Driver 531 Desktop](https://www.nvidia.com/download/driverResults.aspx/199990/en-us/).

**Comment by K1ngOfCurses** [comment]
i tried the MRE fork and it works fine with all 4 images having the same time, its cool though i just use that but thanks for your work, loving how easy it is to use

**Comment by K1ngOfCurses** [comment]
coming out with awesome images thank you for your hard work :)
