### ISSUE TITLE
about NSFW

### ISSUE THREAD

**Issue by mingcun693** [lllyasviel/Fooocus#368]
Hello,

I really appreciate this software and its functionality. However, I have noticed that it seems to automatically block NSFW (Not Safe for Work) content, even when using lora or checkpoint models known for generating NSFW.

I have gone through the code but I'm unsure how to enable the generation of NSFW content. 

I would greatly appreciate it if someone could provide me with some guidance or assistance on how to configure the software to generate NSFW content.

**Comment by Yardanico** [comment]
@mingcun693 NSFW is not blocked, it's just that SDXL itself was trained on much less NSFW content so to generate that you'll have to use fine-tunes or at least loras.

**Comment by Nebhg** [comment]
> @mingcun693 NSFW is not blocked, it's just that SDXL itself was trained on much less NSFW content so to generate that you'll have to use fine-tunes or at least loras.

Do you have any advice on how do this?

**Comment by CharlyPico** [comment]
Any idea of how loras work or are prompted?

**Comment by mashb1t** [comment]
see https://github.com/lllyasviel/Fooocus/issues/950 (https://github.com/lllyasviel/Fooocus/issues/950#issuecomment-1871335733) and on the corresponding LoRA model card

**Comment by PhiGo67** [comment]
Even with specialized models and loras I can´t get fooocus to generate an anatomically correct male.
And I just wanted to create a statue of a nude greek athlete, so nothing special.

**Comment by eisenbruch** [comment]
I too am having issues with nsfw content. for example trying to generate images of "man and woman walking down a beach nude" will only show backside images no matter what else I add like "frontal view". Is there a solution for even getting minorly-nsfw content lol

**Comment by mashb1t** [comment]
@eisenbruch it may be beneficial to create one image and then inpaint the second person, or you add sfw to negative prompt + tinker a bit with keywords in positive/negative prompt or try different models.
From my own experience it works best when generating single persons in full body shots or portraits.
