### ISSUE TITLE
[Bug]: Exits upon attempting to load a model on Windows

### ISSUE THREAD

**Issue by hhkcu** [lllyasviel/Fooocus#3689]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Attempting to run Fooocus on Windows 11 (and possibly 10, haven't tested) simply exits when attempting to load the default model, no error or nothing.

### Steps to reproduce the problem

1. Install Fooocus on Windows 11 with a NVIDIA GPU
2. Attempt to run it.

### What should have happened?

It should've loaded the model successfully.

### What browsers do you use to access Fooocus?

Mozilla Firefox

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11 (23H2)

### Console logs

```Shell
(fooocus_env) D:\Misc4\Fooocus>python entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
Fooocus version: 2.5.5
[Cleanup] Attempting to delete content of temp dir C:\Users\hkcu\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Total VRAM 12281 MB, total RAM 16317 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
IMPORTANT: You are using gradio version 3.41.2, however version 4.44.1 is available, please upgrade.
--------
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.

(fooocus_env) D:\Misc4\Fooocus>
```

### Additional information

Using Fooocus on the exact same machine, with the exact same amount of swap configured (4Gb) works as normal.

**Comment by rururu243** [comment]
ive also occured this, the solution was easy, just change the name of the safetensors you want in the default.json in the presets folder in the fooocus/presets, change the checkpoint to the one you want, like ponyxl.safetensors
then you go in the config.txt and do the same:
{
    "path_checkpoints": [
        "C:\\Programs\\anaconda3\\envs\\Fooocus\\models\\checkpoints"
    ],
    "path_loras": [
        "C:\\Programs\\anaconda3\\envs\\Fooocus\\models\\loras"
    ],
	"default_model": "ponyxl.safetensors",    <-----  if the default model dosent say in the config you add it just like this,

and if that isnt enough you change the config_modification_tutorial.txt

 where it says default_model:"ponyxl.safetensors"

well this worked for me and i dont have to wait 30 minutes for the damn loading of the models,
Hope this helped.

**Comment by hhkcu** [comment]
I've actually figured out the likely cause which is my GPU running out of VRAM, since I tried to use SD WebUI Forge on Windows, and this time it actually threw a useful error which was CUDA running out of memory. Not sure what the difference is between Windows and Linux, considering I have the same amount of memory across both systems and the same amount of swap configured.

**Comment by mashb1t** [comment]
Do not use python 3.12.7 but rather 3.10/3.11 for highest compatibility.
