### ISSUE TITLE
[Feature Request]: NSFW content not possible?

### ISSUE THREAD

**Issue by etienno83** [lllyasviel/Fooocus#3704]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Hello, I have been trying to create some adult content with fooocus but it doesnt seem to let me do more than naked. Is there an option somewhere so that it can go all the way or is it pre prompting that it doesn't do it at all?

### Proposed workflow

1. Go to homepage of Fooocus
2. Press NSFW Allowed
3. Let there be p*rn

**Comment by mashb1t** [comment]
There are no limits by default. Please download and use a NSFW model (checkpoint) from e.g. CivitAI and try again.
I can confirm that even with default models NSFW generation is possible.
