### ISSUE TITLE
[Feature Request]: Does the latest version support multi-GPU usage?

### ISSUE THREAD

**Issue by libaolu312** [lllyasviel/Fooocus#3705]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Does the latest version support multi-GPU usage?

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by mashb1t** [comment]
No, please run multiple instances of Fooocus assigned to different GPUs (see console arguments in readme).
