### ISSUE TITLE
[Feature Request]: Straightforward macOS installation/usage

### ISSUE THREAD

**Issue by danispringer** [lllyasviel/Fooocus#3709]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Allow mac users to install and run app without taking way more steps than win/lin users

### Proposed workflow

n/a

**Comment by mashb1t** [comment]
Fooocus does not offer official MacOS support. Please write a script for automated install for yourself.

**Comment by mashb1t** [comment]
see https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#mac

> Mac is not intensively tested. Below is an unofficial guideline for using Mac. You can discuss problems here.
