### ISSUE TITLE
[Bug]: RunTime Error: Found no NVIDIA driver in your system. 

### ISSUE THREAD

**Issue by ToshForce** [lllyasviel/Fooocus#3737]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [x] The issue exists on a clean installation of Fooocus
- [x] The issue exists in the current version of Fooocus
- [x] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Can't launch the application as it runs into error while loading saying that it cant find NVIDIA driver. This is correct since I don't have NVIDIA GPU. But I can't imagine that the application cant be run without that? 

### Steps to reproduce the problem

1. Launch the app?

### What should have happened?

It should be compatible with my current graphics driver maybe? 

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### Console logs

```Shell
Runtime error: Found no NVIDIA driver on your system. Please check that you have an NVIDIA driver.
```

**Comment by mashb1t** [comment]
Please find installation instructions for AMD and Mac in the Readme and Intel ARC in https://github.com/lllyasviel/Fooocus/pull/2120.
