### ISSUE TITLE
[Bug]: Can't generate web link on Google Colabs.

### ISSUE THREAD

**Issue by mlf-crypto** [lllyasviel/Fooocus#3763]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

no link

### Steps to reproduce the problem

only ip adress

### What should have happened?

generate link

### Where are you running Fooocus?

None

### Console logs

```Shell
help
```

**Comment by tronexis** [comment]
Gradio Share Links is down for 2 hours. https://status.gradio.app/793595809
