### ISSUE TITLE
[Feature Request]: HARD force stop ability/button

### ISSUE THREAD

**Issue by XDM-Inc** [lllyasviel/Fooocus#3767]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

it would be nice to have a force stop button which stops it from any task it's currently doing regardless of what that task might be. even if it's image processing or vae inpainting, it would be nice to have a force stop. sometimes while you're glossing over your configurations you realize before it even started you missed something and now you might have to wait a while for it to finish its task before it stops.

### Proposed workflow

1. Click generate
2. click stop or double click stop
3. the processing stops INSTANTLY without finishing additional tasks

**Comment by mashb1t** [comment]
ctrl+c in your terminal is always an option, but this also stops Fooocus. This is currently the only possible method and another one will not be implemented.

**Comment by XDM-Inc** [comment]
I'm using fooocus via stability matrix I don't necessarily have a "terminal"  open

**Comment by mashb1t** [comment]
I'd suggest to add a feature request for "hard resetting" tools in the stability matrix repository.

**Comment by XDM-Inc** [comment]
Out of curiosity when you Ctrl c  it that would shut down the whole application and you need to restart it again right? If so then there is a restart button already I just thought there needed to be a graceful way to shut down the application.
