### ISSUE TITLE
[Bug]: not generating any images gcolab pro

### ISSUE THREAD

**Issue by mlf-crypto** [lllyasviel/Fooocus#3780]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

starting to load, and simply stops.

### Steps to reproduce the problem

not working

### What should have happened?

not working

### Where are you running Fooocus?

None

### Console logs

```Shell
google colab pro
```

**Comment by simoyassin** [comment]
Prompt:

A hyper-realistic portrait of a young human woman with long, vibrant blue hair flowing naturally. She has piercing blue eyes with a soft and captivating gaze. Her skin is smooth, pale, and radiant, with a delicate scattering across her cheeks and nose. Her expression is serene and charming, reflecting natural beauty and elegance. The lighting is soft and warm, emphasizing the fine details of her features and hair. She is dressed in a simple yet stylish outfit that complements her overall look.

**Comment by mashb1t** [comment]
Tested and it's working, closing as no further information has been provided to debug. Feel free to follow the troubleshooting guide and provide qualitative feedback for further debugging. Thanks.
