### ISSUE TITLE
[Bug]: C:\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0>pause.

### ISSUE THREAD

**Issue by Harsh3054** [lllyasviel/Fooocus#3788]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After loading control models it is getting pause autmatically and Error :Connection timed out is displayed
![erro1](https://github.com/user-attachments/assets/401ec650-fe28-434f-a749-6ee7af6a986b)

### Steps to reproduce the problem

1.Run run_realistic file
2.Select Input Image option and upload image in image prompt .Set the stop at 0.9 and weight 1.32
3.Add image prompt whatever you like.Following will be displayed in command prompt. 
![erro2](https://github.com/user-attachments/assets/8b0bbb06-d180-47c5-b896-1df198a5302c)
4.Error will be displayed.

### What should have happened?

It should generate image according to prompt

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11 version 23H2

### Console logs

```Shell
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] CLIP Skip = 2
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] Seed = 1812086270447336670
[Parameters] CFG = 3
[Fooocus] Downloading control models ...
[Fooocus] Loading control models ...

C:\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0>pause
Press any key to continue . . .
```

### Additional information

My system has processor AMD Ryzen 5 5600H with Radeon Graphics            3.30 GHz
Installed RAM :-8.00 GB (7.34 GB usable)
GPU:-NVIDIA GeForce GTX 1650

**Comment by tarekhassan2020** [comment]
I also have GTX 1050 ti 4GB
