### ISSUE TITLE
about the problem,  If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

### ISSUE THREAD

**Issue by peter2office** [lllyasviel/Fooocus#379]
File "G:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\transformers\modeling_utils.py", line 479, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'G:\Fooocus-MRE\Fooocus-MRE\models\prompt_expansion\fooocus_expansion\pytorch_model.bin' at 'G:\Fooocus-MRE\Fooocus-MRE\models\prompt_expansion\fooocus_expansion\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

What Should I do next？

**Comment by peter2office** [comment]
Do you means I should redownload the cheakpoint file? sd_xl_base and refine?

**Comment by peter2office** [comment]
I have recovered the checkpoint files again, but it's also got the same promble.  
![image](https://github.com/lllyasviel/Fooocus/assets/136039687/db9c16a1-237a-4c37-8cab-8843050a9fcf)

**Comment by lllyasviel** [comment]
Fooocus files are corrupted, not sdxl models

**Comment by CDJenson** [comment]
just redownload the whole project.

**Comment by peter2office** [comment]
Thanks a lot . I'm gonna to do that
