### ISSUE TITLE
[Feature Request]: Use 2Vram Gpu

### ISSUE THREAD

**Issue by midoalawieh** [lllyasviel/Fooocus#3790]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

I do not have a 4Vram GPY, but here are my specs

16 Ram ddr4
Ryzen 5 Pro 3500U w/ Vega X
Mobile Vega 8 Graphics
can i install foocus with my gpu?

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by mashb1t** [comment]
Please ensure you're meeting the minimum system specs, which you can find in the readme.
