### ISSUE TITLE
MacOS M1 can't run 2.0.14

### ISSUE THREAD

**Issue by edmondyip** [lllyasviel/Fooocus#380]
I using MacOS 13.4.1 in M1 Macbook Pro 32GB.
Fooocus work well in v1.
But it don't work after update to v2.
It can start the UI, but have error when generate.
Even I reinstall everything, it still have this error.

Python 3.10.6 (main, May  3 2023, 17:07:07) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Fooocus version: 2.0.14
Inference Engine exists.
Inference Engine checkout finished.
Total VRAM 32768 MB, total RAM 32768 MB
Set vram state to: SHARED
Device: mps
Fooocus Text Processing Pipelines are retargeted to mps
model_type EPS
adm 2816
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: sd_xl_base_1.0_0.9vae.safetensors
model_type EPS
adm 2560
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Refiner model loaded: sd_xl_refiner_1.0_0.9vae.safetensors
LoRAs loaded: [('sd_xl_offset_example-lora_1.0.safetensors', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5)]
Fooocus Expansion engine loaded.

`RuntimeError: MPS does not support cumsum op with int64 input`

**Comment by lllyasviel** [comment]
fooocus has not officially support mac
but you can try disable Fooocus V2 in style

**Comment by edmondyip** [comment]
I using native python to run in MacOS
It seem work with V2 if I set `PYTORCH_ENABLE_MPS_FALLBACK = 1`
But it is slower than V1

**Comment by lllyasviel** [comment]
I fixed in 2.0.17

**Comment by edmondyip** [comment]
If I removed `PYTORCH_ENABLE_MPS_FALLBACK = 1`
And run 2.0.17
I will have another error

NotImplementedError: The operator 'aten::std_mean.correction' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

**Comment by lllyasviel** [comment]
added
