### ISSUE TITLE
[Bug]: No Run.bat

### ISSUE THREAD

**Issue by SuperGamer001** [lllyasviel/Fooocus#3808]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I downloaded the current version of Fooocus, but I'm not seeing run.bat anywhere. Has it been accidentally deleted or moved?

### Steps to reproduce the problem

I just looked in the uncompressed file I got, and I didn't see any run.bat anywhere, even the other files inside the Fooocus-main folder.

### What should have happened?

There should be a bat file, but there is none.

### Where are you running Fooocus?

None

### Console logs

```Shell
Nothing. There is no run.bat file to run anything
```

**Comment by mashb1t** [comment]
See https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#download, do not download the repository as zip file.

**Comment by isupovleonid** [comment]
Sorry to bring this up again, but I had the same problem, even with the download 7z archive.
Unblock the archive file (in the file properties), cause the problem may be that Windows blocks unpacking batch files from unknown sources.

![Image](https://github.com/user-attachments/assets/700fd434-607a-499d-bd8c-a5a310673da8)
