### ISSUE TITLE
generate always get output with previous prompt

### ISSUE THREAD

**Issue by holyvslin** [lllyasviel/Fooocus#383]
**Fooocus is best project I'd prefer!**

Just met issue about output image is mismatched with current prompt, when click generate will get images quickly but it's previous prompt seems data in cache. As several links access and use from different IP, not sure some multi button click/threads impact and stuck?  

Thanks for checking. :)

**Comment by zhuojg** [comment]
I'm facing the same issue, does anyone have ideas?
My version is 1.0.45.

**Comment by zhuojg** [comment]
I found a issue of Gradio: https://github.com/gradio-app/gradio/issues/1954.

So maybe at some point there were two tasks running concurrently, which triggered a bug in Gradio, causing subsequent tasks to fail to return results correctly.

I restart Fooocus and it seems to work fine.

**Comment by abidlabs** [comment]
Ok I'll close given that we have #1954 open

**Comment by mashb1t** [comment]
Please test again with the latest version of Fooocus and let us know the results. Issue is long solved, should not occur anymore.
