### ISSUE TITLE
checkpoints in nested folders

### ISSUE THREAD

**Issue by chuckkay** [lllyasviel/Fooocus#386]
first issue
i use a symlink for my models directory. 2 problems with fooocus
in Fooocus\models\checkpoints I created a symlink to my shared models directory 
and put sd_xl_base_1.0_0.9vae.safetensors & sd_xl_refiner_1.0_0.9vae.safetensors in the root of the directory,

but on first install Run.bat deleted the Fooocus\models\checkpoints killing the symlink and it created a new empty folder and started downloading sd_xl_base_1.0_0.9vae.safetensors & sd_xl_refiner_1.0_0.9vae.safetensors.  had to wait for it to finish, had to delete Fooocus\models\checkpoints and re create symlink to my shared models directory...

second issue i use a nested subdirectory system for my models  Fooocus only seems to look for safetensor files in the root of Fooocus\models\checkpoints and will not scan for models recursivly.

**Comment by chuckkay** [comment]
also hows about a refresh button for models loras etc, for when a new safetensor is put in the models folders, so you dont have to restart to see them in the dropdown lists

**Comment by barepixels** [comment]
symlink doesn't work with Fooocus.  Use "paths.json"
1. duplicate "paths-example.json" and rename the new file as "paths.json"
2. edit  "paths.json"

Fooocus is SDXL only so here is how I point to my "checkpoints" folder

For A1111 I use this path
D:\stable-diffusion-shared\Ckpt

For Fooocus I use this path
D:\stable-diffusion-shared\Ckpt\XL

I do the same for Loras

**Comment by chuckkay** [comment]
barepixels <notifications@github.com>
Sep 16, 2023, 1:21 AM (1 day ago)
to lllyasviel/Fooocus, chuckkay, Author

symlink doesn't work with Fooocus. Use "paths.json"

duplicate "paths-example.json" and rename the new file as "paths.json"
edit "paths.json"
Fooocus is SDXL only so here is how I point to my "checkpoints" folder

For A1111 I use this path
D:\stable-diffusion-shared\Ckpt

For Fooocus I use this path
D:\stable-diffusion-shared\Ckpt\XL

I do the same for Loras


----------------------------------------------------------------
no such file "paths-example.json" exists in the entire directory

**Comment by barepixels** [comment]
my bad, I should have mentioned this is only available in these two forks

https://github.com/MoonRide303/Fooocus-MRE  <-my preferred flavor of Fooocus

and

https://github.com/runew0lf/RuinedFooocus

**Comment by jurandfantom** [comment]
Up.

So it is/would be possible for Fooocus to scan sub-folders or not really? (at least for loras themself)

**Comment by MoonRide303** [comment]
Added in v2.1.698 (https://github.com/lllyasviel/Fooocus/pull/725).
