### ISSUE TITLE
When making an API request, a picture is generated which contains many pictures, connected together.

### ISSUE THREAD

**Issue by 823863429** [lllyasviel/Fooocus#391]
A png image generated during an api request contains many sub-images and are connected top to bottom.
Here's how I do it:
from gradio_client import Client

client = Client("https://83223fb617f7a122be.gradio.live", serialize=False)
result = client.predict(
				"modern sports car",	# str in 'parameter_8' Textbox component
				"",	# str in 'Negative Prompt' Textbox component
				["Fooocus V2"],	# List[str] in 'Image Style' Checkboxgroup component
				"Speed",	# str in 'Performance' Radio component
				"704×1408",	# str in 'Aspect Ratios' Radio component
				1,	# int | float (numeric value between 1 and 32) in 'Image Number' Slider component
				5,	# int | float in 'Seed' Number component
				5,	# int | float (numeric value between 0.0 and 30.0) in 'Sampling Sharpness' Slider component
				"sd_xl_base_1.0_0.9vae.safetensors",	# str (Option from: []) in 'SDXL Base Model' Dropdown component
				"sd_xl_refiner_1.0_0.9vae.safetensors",	# str (Option from: ['None']) in 'SDXL Refiner' Dropdown component
				"sd_xl_offset_example-lora_1.0.safetensors",	# str (Option from: ['None']) in 'SDXL LoRA 1' Dropdown component
				0.5,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
				"None",	# str (Option from: ['None']) in 'SDXL LoRA 2' Dropdown component
				0.5,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
				"None",	# str (Option from: ['None']) in 'SDXL LoRA 3' Dropdown component
				0.5,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
				"None",	# str (Option from: ['None']) in 'SDXL LoRA 4' Dropdown component
				0.5,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
				"None",	# str (Option from: ['None']) in 'SDXL LoRA 5' Dropdown component
				0.5,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
				fn_index=4
)
print(result)

**Comment by mashb1t** [comment]
Please test again with the latest version of Fooocus and let us know the results. Should not occur anymore.
