### ISSUE TITLE
Is it possible to launch offline?

### ISSUE THREAD

**Issue by Henry-Suen** [lllyasviel/Fooocus#406]
It seems that it needs to update and download something every time it launches.
I guess it could be not mandatory right?

**Comment by barepixels** [comment]
You can try disabling Wi-Fi or unplug Ethernet cable and find out

**Comment by captainpd** [comment]
> It seems that it needs to update and download something every time it launches. I guess it could be not mandatory right?

You can directly run `webui.py` instead of `launch.py`.

All `launch.py` do is to prepare and download everything needed to update before launching `webui.py`.
