### ISSUE TITLE
[Minor] Add optional password authentication

### ISSUE THREAD

**Issue by Yardanico** [lllyasviel/Fooocus#408]
Since Fooocus can be hosted on servers, some people might want to expose them directly but have some kind of authentication, it's trivial to add with Gradio: https://www.gradio.app/guides/sharing-your-app#authentication (just add as a flag `--gradio-auth` or something similar, just like A1111 does it)

Just as a note, there are already some exposed Fooocus instances that can be found on Censys, so this is a real security problem, even if not a big one.

**Comment by Yardanico** [comment]
If anyone wants to add password auth manually, just add the credentials to the last line in webui.py like this:
```
shared.gradio_root.launch(inbrowser=True, server_name=args.listen, server_port=args.port, share=args.share, auth=("YOURUSER", "PASSWORD"))
```

**Comment by MoonRide303** [comment]
I've ported support for auth from MRE in v2.1.739 (https://github.com/lllyasviel/Fooocus/pull/778) - you can define your credentials in auth.json (auth-example.json is provided as an illustraion of the syntax).
