### ISSUE TITLE
Feature request :  face-replacement option

### ISSUE THREAD

**Issue by Kaneki010** [lllyasviel/Fooocus#409]
similar to the variations & upscaling feature ,  face-replacement is a feature available in midjourney and can be used in other stable diffusion UIs with roop , it would be a great feature in fooocus

**Comment by TimothyAlexisVass** [comment]
Roop has been discontinued and Facefusion, which is the continued fork of Roop requires a lot of resources and should be used standalone: https://github.com/facefusion/facefusion
