### ISSUE TITLE
Option --port doesn't seem to do anything 

### ISSUE THREAD

**Issue by mraggi** [lllyasviel/Fooocus#41]
I tried with both `python launch.py --listen --port 3123` and without `--listen`.

Both open a port in 7860.

```bash
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
Fooocus version: 1.0.22
Inference Engine exists.
Inference Engine checkout finished.
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```

Also, `--disable-auto-launch` doesn't work, still launches a (text-based) browser.

**Comment by tcmaps** [comment]
there is no code handling port yet

**Comment by mashb1t** [comment]
Just tested, it works with the latest version of Fooocus.
Please try again with the latest version of Fooocus and feel free to reopen if still relevant.
