### ISSUE TITLE
Low vram but high ram usage

### ISSUE THREAD

**Issue by royqh1979** [lllyasviel/Fooocus#420]
I'm running Fooocus 2.0 on a maching with the following hardware:
 - Intel i7 10700
 - 64G memory (20G used as ram disk)
 - Nvidia 3090Ti
 - Windows 10

After Fooocus started, the ram usage runs from 26.6GB to 42.4GB, while VRAM usage is only 0.8GB.

When generation started, the ram usage floats around 44GB, while VRAM usage never exceeds 8GB.

It's there any command line option to let fooocus use more vram and less ram?

**Comment by fervguida** [comment]
Same problem here! I installed it and still haven't been able to use it because it consumes all my RAM! It seems like it's not using my gpu and just the entire ram, I've never seen this in my life, whether in a game or a program consuming 16b of ram, it's something unheard of for me, if you find a solution please share.

**Comment by DinkoGeorgiev** [comment]
Same here. Shortly after it starts it eats the entire available memory until the laptop becomes unresponsive (Fedora 38, 16GB RAM).
```
[System ARGV] ['entry_with_update.py']
Python 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865
To create a public link, set `share=True` in `launch()`.
Total VRAM 4044 MB, total RAM 15899 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
Set vram state to: LOW_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce GTX 860M : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
^CKeyboard interruption in main thread... closing server.
terminate called without an active exception
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
Aborted (core dumped)
```

**Comment by stockarea** [comment]
I am getting the same exact issue.

**Comment by lllyasviel** [comment]
hello see also https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md for common problem fix

**Comment by Coderman460** [comment]
Same issue here i have 8 gb of vram and it is only using 1 gb while 16 gb of my ram is used up, have you found a solution yet??

**Comment by lllyasviel** [comment]
@Coderman460 
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

**Comment by Coderman460** [comment]
@lllyasviel I already looked at trouble shoot, the problem is in the cmd, it says it is only using 1GB vram but with task manager open while the process runs i can see 8GB vram is being used, I had to lower quality from speed to extreme speed and was able to produce solid images. (AMD RX 5700 XT)

**Comment by Hetster1969** [comment]
I also have same issue.. 24gb ram and it freezes PC for around 8 mins as its using 100% ram
