### ISSUE TITLE
Regarding the slow drawing problem of Fooocus2.0.62.

### ISSUE THREAD

**Issue by hzeasy** [lllyasviel/Fooocus#421]
@lllyasviel Thank you for creating this great tool Fooocus. Since it was upgraded to version 2.0.62 today, the drawing time is obviously much longer than the previous version 1.0. If this is due to function upgrade, I can understand, but I noticed that with the same parameters, only one picture is very fast, and more than 2 pictures at a time will cause the second picture to be very slow, and I noticed It turns out that the GPU memory has been exhausted during the generation of the second picture. The slow problem should be in the video memory. Can it be optimized to the previous level? Looking forward to replying, thank you!
![46635a043505a776020083571df74d3](https://github.com/lllyasviel/Fooocus/assets/136664755/7a5ada7b-a5cd-4039-8778-6b880a68422b)
![image](https://github.com/lllyasviel/Fooocus/assets/136664755/4be1d2d5-ede8-4cf8-921a-fc56746042a7)

**Comment by lllyasviel** [comment]
are you happened to open two fooocus at the same time?

**Comment by lllyasviel** [comment]
user mistake - closed

**Comment by hzeasy** [comment]
> are you happened to open two fooocus at the same time?

@lllyasviel I'm sure I only opened one fooocus. When making the first picture, it takes up about 4.5G of GPU memory. The second picture exceeds the 6G range and reaches about 2G of virtual memory, so it becomes slow and there are 2 incomprehensible warnings. Hope these issues can be resolved, thank you for your reply.
![1695107827621](https://github.com/lllyasviel/Fooocus/assets/136664755/ccc6d684-51bc-4fc2-812e-0231bf6c3dfa)
![image](https://github.com/lllyasviel/Fooocus/assets/136664755/621f070f-9faa-466a-ba8d-56f8c8f389d5)

**Comment by lllyasviel** [comment]
from the log it shows that you have modified the codes...
can you provide a gpu curve?
my development machine is also 3060 6GB with bad driver 537 and it does not have problems

**Comment by hzeasy** [comment]
> from the log it shows that you have modified the codes... can you provide a gpu curve? my development machine is also 3060 6GB with bad driver 537 and it does not have problems

@lllyasviel Hello, in order to see the GPU curve more intuitively, I recorded a video. Please go to the network disk to download and view it.
Link：https://pan.baidu.com/s/1VQ_TPdKN2J5aR4QKDrgRwg?pwd=akai 
extract code：akai 

Regarding the code, I only modified the path of the model to facilitate the use of comfy and SD at the same time, and the rest has not been changed.

Video description:
1. After fooocus2.0.62 completes the first picture, it will not reset the GPU memory and then start the second picture, so it will be very slow.Because the picture output was too slow, I stopped the video before it ended.
2. use the MRE version for comparison, this situation will not occur.
3、This problem does not seem to occur in the original Fooocus2.0.0.

**Comment by lllyasviel** [comment]
Very interesting - it seems that on 3060 with refiner, it always work very well
but if I remove refiner and run a lot, it sometime has memory leak
interesting - most of my previous tests are with refiner

**Comment by lllyasviel** [comment]
I created a post https://github.com/lllyasviel/Fooocus/issues/421
see if you can fix this by using a refiner.
We are still looking into what is the cause

**Comment by hzeasy** [comment]
> Very interesting - it seems that on 3060 with refiner, it always work very well but if I remove refiner and run a lot, it sometime has memory leak interesting - most of my previous tests are with refiner

@lllyasviel thank you for your reply. When I was about to test the refiner, RUN started to upgrade and the modified model path was gone. Haha, what method can be used to avoid upgrading during RUN?

**Comment by hzeasy** [comment]
> I created a post #421 see if you can fix this by using a refiner. We are still looking into what is the cause

I will test it later and report back the results.

**Comment by hzeasy** [comment]
> > I created a post #421 see if you can fix this by using a refiner. We are still looking into what is the cause
> 
> I will test it later and report back the results.

@lllyasviel After upgrading to 2.0.65, I enabled the refiner and ran it with the same parameters. The result is still the same as before, just like the video sent to you. The memory still cannot be released. Is there anything special about my 3060 graphics card? Ha ha.

**Comment by hzeasy** [comment]
There are two other minor issues here, and they're not the first time they've cropped up.
1. The service interruption shown in screenshot mark 1 is because I drag the CMD window with the mouse. Just like this, the service is automatically disconnected.
2. The warnings listed in screenshot marker 2 occurred recently but do not affect the drawing.
![e075e029115a55ed9e8d226562c3311](https://github.com/lllyasviel/Fooocus/assets/136664755/c6be5265-7663-4cec-87dd-0897282428ce)
![image](https://github.com/lllyasviel/Fooocus/assets/136664755/17c36d56-85a0-4010-a1ba-9356e4e7aade)

**Comment by lllyasviel** [comment]
this problem is just caused by a careless pull request that put torch in a function before backend call it, so the torch has duplicated instance https://github.com/lllyasviel/Fooocus/pull/397/files
should review other pull request more carefully

**Comment by hzeasy** [comment]
> this problem is just caused by a careless pull request that put torch in a function before backend call it, so the torch has duplicated instance https://github.com/lllyasviel/Fooocus/pull/397/files should review other pull request more carefully

@lllyasviel Updated to 2.0.68, the same parameter tests are normal, and turning off Refiner is also normal. The GPU memory curve is perfect, and the memory optimization is even better than before. it's great!Thanks..
![image](https://github.com/lllyasviel/Fooocus/assets/136664755/9d4bb6cc-9283-4f9f-8707-9636de19f9de)

**Comment by hzeasy** [comment]
> I fixed the problem in 2.0.66 please test

Test addition: Dragging the CMD window no longer causes an error break.

Request: Updates can be done selectively as the model's path settings are more practical for me and automatic updates change the settings.
Thanks

**Comment by lllyasviel** [comment]
added in 2.0.71
