### ISSUE TITLE
Option to load generated images into upscale and inpaint on phone UI

### ISSUE THREAD

**Issue by Dravoss** [lllyasviel/Fooocus#422]
I did not found a way to load a generated image, not even the last generated ones, into upscale or inpaint zone to work with it using the mobile UI

**Comment by holyvslin** [comment]
All generated images are in **outputs** path.
http://127.0.0.1:7860/file=./**outputs/2023-09-19/log.html**

**Comment by Dravoss** [comment]
Thanks, that's helpful but the real problem was firefox not opening the storage browser when touching the upscale/inpaint image areas possibly due to security settings, it works in other browsers so I'm closing this issue.
