### ISSUE TITLE
Can We Install Fooocus on Google Drive / Colab just like Auto1111 and ComfyUI

### ISSUE THREAD

**Issue by Hearcharted** [lllyasviel/Fooocus#423]
Hi, can we install Fooocus on Google Drive / Colab just like Auto1111 and ComfyUI ?

As far as I can see, Foocus is running in this "per Session" base,
so when you end the Session you lose every uploaded file...

Many thanks in advance...

@lllyasviel

**Comment by barepixels** [comment]
You are no longer allowed to use Auto1111 and ComfyUI  on Colab

**Comment by Hearcharted** [comment]
The free tier got nuked, but I'm using the paid one.

**Comment by Hearcharted** [comment]
Got ya, I'm already using it on Google Colab.
But, I need to install it on Google Drive, just like you install Comfy and Auto1111.
I need it to start "Living Inside Google Drive" Forever and Ever (O_O)
Thank you...

**Comment by barepixels** [comment]
If you didn't notice https://github.com/camenduru wrote the codes for Colab.  Contact [camenduru](https://github.com/camenduru)

**Comment by Hearcharted** [comment]
@TimothyAlexisVass
@barepixels

Thank you, I'm going to save this trick...

**Comment by KitsonBroadhurst** [comment]
Figured this out. I wrote some [code in colab](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbFpoRXpXdVNTRTM0UmNOVjZ6eWM3cy0zUjB6d3xBQ3Jtc0tubHdqbElpMDhhOEVVQlZpMkNDcF9xNEl6MElocjVaZWpnaDFkU1lZZmNaRHJiSU1FZkxhbnBwbkJQT29zMVFDNDV5LXBjaWVQcHE0Qmk1THVCMG1VS1ZRY3M4Q2hRNHVtRE5WOHlOVUtiU2VQUndJQQ&q=https%3A%2F%2Fcolab.research.google.com%2Fdrive%2F18zNcbJV9r2Rxkb4UkY0YhjzMvj1wFMy0%3Fusp%3Dsharing&v=EIWZ6u0o4dc) and did a quick [tutorial on YouTube](https://youtu.be/EIWZ6u0o4dc)

**Comment by Sjnjerak** [comment]
Thank you, Kitson! I wanted to start running Fooocus on cloud GPUs and this seems like a great way to do it.

**Comment by MXTcomunica** [comment]
Thank you @KitsonBroadhurst, I duplicated your notebook in Colab, but the following error occurs:

> Error
> Unexpected token '<', " <!DOCTYPE "... is not valid JSON

![immagine](https://github.com/lllyasviel/Fooocus/assets/5735682/7d88daf3-685e-4684-8f7d-de4ea4b71ea7)

And then the runtime crashes warning an error similar to  "Not allowed code/operation has been detected"...

What could be?

**Comment by mashb1t** [comment]
@MXTcomunica please use the officially supported playbook in https://colab.research.google.com/github/lllyasviel/Fooocus/blob/main/fooocus_colab.ipynb

**Comment by MXTcomunica** [comment]
Yeah I already used the official Fooocus playbook @mashb1t, but the one provided by @KitsonBroadhurst allows you to mount your Gdrive to have persistent data, so to not lose your generated images, to use your own custom settings/wildcards, and to use your own models/loras without the need to re-download them every time.

It would be nice if the official playbook also provided a similar wrapper.

**Comment by mashb1t** [comment]
Got it, thx. 
When you ran https://colab.research.google.com/drive/18zNcbJV9r2Rxkb4UkY0YhjzMvj1wFMy0 you might just have encountered a timeout and the console log may give you more information about the status.

**Comment by yassineofd** [comment]
is there any working way now that allows me to lunch it on google colab.

**Comment by mashb1t** [comment]
@yassineofd you can simply run https://colab.research.google.com/github/lllyasviel/Fooocus/blob/main/fooocus_colab.ipynb on a T4 instance in Colab. Be aware that if your daily quota for the T4 instance type may be exceeded you might not be able to use it without paying for Colab Pro.
