### ISSUE TITLE
image error in api

### ISSUE THREAD

**Issue by 823863429** [lllyasviel/Fooocus#427]
Using the api request, the final picture you get is like this.
![image](https://github.com/lllyasviel/Fooocus/assets/6307936/6dc7e57f-bff6-41f1-bb0a-c24bc2a224f0)

Several pictures are mixed in one picture, how should I deal with it? It's a bit urgent, please reply to me as soon as possible, thank you

**Comment by mashb1t** [comment]
Please test again with the latest version of Fooocus and let us know the results.
