### ISSUE TITLE
Problem running webui

### ISSUE THREAD

**Issue by mikmoth** [lllyasviel/Fooocus#428]
I still have no idea why this happens on only one of my computers, but the web ui will not load.

The only way I can get it load is by adding "--share" to the run.bat file:

.\python_embeded\python.exe -s Fooocus\entry_with_update.py --share

Then the web interface displays normally. Just thought I'd share this tip so you can avoid any problems.

Peace.

**Comment by mashb1t** [comment]
make sure you call the correct URL and do not use ad blockers for the page. This might also be an issue with the network setup on your machine when mapping 127.0.0.1 to a different host or similar (very uncommon but possible).
