### ISSUE TITLE
Issues with random seed values

### ISSUE THREAD

**Issue by MoonRide303** [lllyasviel/Fooocus#44]
1. Large random seed values are not workings - seems to be artificially capped at 65535 (in async_worker.py - it changes seed to random value from this tiny entropy range, when this threshold is exceeded). We should be able to generate like billions (int range) of different images for the same prompts if we wanted to, not just few thousands. People also might also have their favorite numbers they like to use as random seed, that are much bigger than mere 2**16. Both A1111 and ComfyUI allow much bigger values than 65535.
2. With current implementation we don't have information about what seed was used to generate the image, when it was random value - it would be nice to have it displayed somewhere in the UI (per image, or at least for first image from the batch).

**Comment by MoonRide303** [comment]
@lllyasviel I noticed you did initial version of fix in 1.0.35, but it could be improved a bit - instead of:
```
                def refresh_seed(r, s):
                    if r:
                        return random.randint(1, 1024*1024*1024)
                    else:
                        return s
```
in `webui.py` I'd go with
```
                def refresh_seed(r, s):
                    if r or not isinstance(s, int) or s < 0 or s > 2**63 - 1:
                        return random.randint(0, 2**63 - 1)
                    else:
                        return s
```
to refresh seed for people who enter value out of allowed range.

You could also bump max_seed in `async_worker.py` from `1024*1024*1024` to `2**63 - 1`. People use 64-bit machines these days, and you already use similar values in `core.py` - I made all of them consistent, and staying in 0 to 2**63-1 range on my fork.

**Comment by lllyasviel** [comment]
negative or large seed will still work as they willl be preprocessed inner worker

**Comment by MoonRide303** [comment]
@lllyasviel They will work, but in your version they will be silently re-generated, and not displayed to the user in the UI.

**Comment by lllyasviel** [comment]
this impl cannot get same results from same negative number as seed

**Comment by MoonRide303** [comment]
It just generates new seed when out-of-range number is entered.

**Comment by MoonRide303** [comment]
Works fine in v2.1.739 (seeds from 0 to 2 ** 63 - 1 are now supported).
