### ISSUE TITLE
[Feature request] Save current session (pos/neg prompts, advanced settings, etc.) as defaults after restart

### ISSUE THREAD

**Issue by ke1ne** [lllyasviel/Fooocus#445]
Hi, it may be useul to add some checkbox or button to save a whole UI state for next restart, as default preset. So no need to enter negative prompt and other tweaks every time.
Thanks!

**Comment by barepixels** [comment]
I first experienced this with A1111 v1.6 RC and thought it was cool

If you experienced a crash, closed the browser tab by accident, or haven't used Fooocus in days.  Upon launching it will display the most recent project with all the settings

**Comment by mashb1t** [comment]
see https://github.com/lllyasviel/Fooocus/issues/692 (https://github.com/lllyasviel/Fooocus/issues/692#issuecomment-1873365427)
