### ISSUE TITLE
NVIDIA GeForce GTX 1070 RAM utilization

### ISSUE THREAD

**Issue by Maor-Ar** [lllyasviel/Fooocus#448]
The model is running for a few minutes, and I don't see any iteration appearing. 
When I open my GPU performance tab on the task manager I don't see any activity, what could be the cause?

![image](https://github.com/lllyasviel/Fooocus/assets/73241556/f3375bea-5d08-432a-9c83-887d7cf68f32)

![image](https://github.com/lllyasviel/Fooocus/assets/73241556/e8e9160d-8582-43de-a7b4-db82184d20bf)

**Comment by patbhakta** [comment]
Check the logs or the cmd prompt, it'll tell you more than taskman

**Comment by mashb1t** [comment]
Please test again with the latest version of Fooocus and let us know the results.
