### ISSUE TITLE
user stoped

### ISSUE THREAD

**Issue by pengpengzi** [lllyasviel/Fooocus#450]
‘’‘
[Fooocus] Initializing ...
开始翻译
请求成功
开始翻译
请求成功
[Fooocus] Loading models ...
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] New suffix: intricate, elegant, highly detailed, centered, digital painting, artstation, concept art, smooth, sharp focus, illustration, artgerm, tomasz alen kopera, peter mohrbacher, donato giancola, joseph christian leyendecker, wlop, boris vallejo
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] New suffix: extremely detailed and intricate octane render trending on Artstation, 8K artistic photography, photorealistic, dramatic volumetric cinematic perfect light, chiaroscuro, award-winning photograph, masterpiece, Raphael, Caravaggio, harsh flash photography
[Fooocus] Encoding base positive #1 ...
[Fooocus] Encoding base positive #2 ...
[Fooocus] Encoding base negative #1 ...
[Fooocus] Encoding base negative #2 ...
[Fooocus] Encoding refiner positive #1 ...
[Fooocus] Encoding refiner positive #2 ...
[Fooocus] Encoding refiner negative #1 ...
[Fooocus] Encoding refiner negative #2 ...
[ADM] Negative ADM = True
  0%|                                                                                                            | 0/60 [00:00<?, ?it/s]
User stopped
‘’’
When I use local redrawing and image expansion, "user stopped" often appears, but I did not click on the termination button on the interface.

**Comment by mashb1t** [comment]
Please test again with the latest version of Fooocus and let us know the results. This should not occur anymore and has not occurred for anybody else since 3 months
