### ISSUE TITLE
Suggestion for Advanced Tab - a filter for showing only SDXL, or only SD 1.5 etc.

### ISSUE THREAD

**Issue by drdancm** [lllyasviel/Fooocus#460]
For anyone who has downloaded a lot of models it takes a lot of time to find only SDXL, or only SD 1.5, so a simple filter to show only one of these would be extremely helpful.
Thanks for a great Job.

**Comment by drdancm** [comment]
Or maybe all I have to do is type XL in the Lora input. Hm, that seems to work.

**Comment by mashb1t** [comment]
What you can do is to rename the models to include a prefix of the corresponding version

**Comment by drdancm** [comment]
Not only is that  cumbersome, but since the models are shared with other programs in Stability Matrix, it will cause problems.
I would think a simple optional filter would do a far better job. As far as I understand you cannot use SD1.5 models with FOOCUS in any case so why show them ??

**Comment by mashb1t** [comment]
I totally agree that this would be a great addition.
The issue with adding a is that AFAIK the type of a mode (SDXL / 1.5) can only be read when loading it, which would cause a too high performance impact.
I already tried but then discarded the idea of text-based filtering, see https://github.com/mashb1t/Fooocus/pull/2
The issue with this is that not every SDXL model also has "xl" of some form in its name.

This is why IMHO a prefix is the easiest option, but feel free to check if we can get the model type without loading the model.
Thank you for your feedback.
