### ISSUE TITLE
Can't launch webui

### ISSUE THREAD

**Issue by Axonical** [lllyasviel/Fooocus#461]
I just installed Fooocus, and run the "run.bat" and I received this error message ![Screenshot (233).png](https://github.com/lllyasviel/Fooocus/assets/145185861/b1812daa-f5e7-4b7b-b0e4-4e6f481e7680)

I'm not a tech person, so please explain in a way that is easy for me to understand to solve the problem

**Comment by mashb1t** [comment]
Please test again with the latest version of Fooocus and let us know the results.
