### ISSUE TITLE
Where can I add the "--no-half" argument?

### ISSUE THREAD

**Issue by artifexstudio** [lllyasviel/Fooocus#467]
When generating an image, I get a black screen as a result. I can add the --no-half argument to webui-user.bat in Automatic1111. How can I add this in Fooocus?

**Comment by TimothyAlexisVass** [comment]
The short answer is "you can't"

Foocus as of this date accepts 3 arguments when you start it.`--share`, `--port` and `--listen`

**Comment by artifexstudio** [comment]
I'm sorry because fooocus looks good otherwise.
It would be nice to see an improvement in this direction so that those whose video card does not support half precision can also use it.

**Comment by TimothyAlexisVass** [comment]
Feel free to add it🕺

**Comment by mashb1t** [comment]
this is now possible, see all arguments here: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#all-cmd-flags
The equivalent is `--all-in-fp32`, but it is not at all advised to use this by default.
