### ISSUE TITLE
RuntimeError: mat1 and mat2 must have the same type

### ISSUE THREAD

**Issue by ajarmstron** [lllyasviel/Fooocus#472]
Hi - I have downloaded Fooocus, but when I run it about 40% of the image is generated and then I get the error message: "RuntimeError: mat1 and mat2 must have the same type"

I have a Dell XPS9040 with 6GB graphics card and 12GB memory.
![error](https://github.com/lllyasviel/Fooocus/assets/85850670/f2a9331a-4257-4f0d-8804-488ad4197877)

Can you please explain what this error is?

(Sorry, I have also noted that other persons are having the same issue and a bug report has been filed.)

**Comment by Weyero** [comment]
https://github.com/lllyasviel/Fooocus/issues/411

thread for this problem

**Comment by mashb1t** [comment]
closed as https://github.com/lllyasviel/Fooocus/issues/411 has been resolved
