### ISSUE TITLE
The prompt does not match the result, it looks like someone else's result.

### ISSUE THREAD

**Issue by xplfly** [lllyasviel/Fooocus#476]
The prompt does not match the result, it looks like someone else's result.
example：prompt is 'modern living room'
img:
![image1](https://github.com/lllyasviel/Fooocus/assets/31639097/2979991c-6bff-4255-bec0-46610ff24f61)
<img width="1442" alt="image" src="https://github.com/lllyasviel/Fooocus/assets/31639097/792ab344-9498-468b-afd7-f46073647893">
<img width="884" alt="image" src="https://github.com/lllyasviel/Fooocus/assets/31639097/ceac0c96-4a66-407a-8585-21a742b195b5">

**Comment by xplfly** [comment]
Additional information：Fooocus V2
when use Fooocus 1.0.45 is normalcy

**Comment by lllyasviel** [comment]
https://huggingface.co/spaces/SpacesExamples/Fooocus/discussions/1#6502bedeb1792803da75916e

**Comment by stunlocked1** [comment]
i dont get it i thought this is a local model... why does it need 2GB of space then?

**Comment by xplfly** [comment]
> https://huggingface.co/spaces/SpacesExamples/Fooocus/discussions/1#6502bedeb1792803da75916e

I'm having a similar problem with my local deployment。 

api.py
`
  import random
  from datetime import datetime
  from asyncio import sleep
  import requests
  from gradio_client import Client
  import os
  import uvicorn
  from fastapi import Query, FastAPI
  
  app = FastAPI()
  @app.get("/generate")
  async def generate_image(
          prompt: str = Query(None),
          negative_prompt: str = Query('nsfw'),
          performance: str = Query(None),
          width: int = Query(1024),
          height: int = Query(1024),
          batch_size: int = Query(1)
  ):
      client = Client("http://localhost:7761/", serialize=False)
      client.reset_session()
      millis = int(datetime.timestamp(datetime.now()) * 1000)
      max_seed = int(1024 * 1024 * 1024)
      job = client.submit(
          prompt,  # str in 'parameter_8' Textbox component
          negative_prompt,  # str in 'Negative Prompt' Textbox component
          ["Fooocus V2"],  # str in 'parameter_23' Radio component
          performance,  # str in 'Performance' Radio component
          "{}×{}".format(width, height),  # str in 'Aspect Ratios (width × height)' Radio component
          batch_size,  # int | float (numeric value between 1 and 32) in 'Image Number' Slider component
          random.randint(1, max_seed),  # int | float in 'Seed' Number component
          2,  # int | float (numeric value between 0.0 and 40.0) in 'Sampling Sharpness' Slider component 采样清晰度
          "sd_xl_base_1.0_0.9vae.safetensors",  # str (Option from: ['sd_xl_refiner_1.0.safetensors', 'sd_xl_base_1.0.safetensors', 'sd_xl_refiner_1.0_0.9vae.safetensors', 'sd_xl_base_1.0_0.9vae.safetensors']) in 'SDXL Base Model' Dropdown component
          "sd_xl_refiner_1.0_0.9vae.safetensors",  # str (Option from: ['None', 'sd_xl_refiner_1.0.safetensors', 'sd_xl_base_1.0.safetensors', 'sd_xl_refiner_1.0_0.9vae.safetensors', 'sd_xl_base_1.0_0.9vae.safetensors']) in 'SDXL Refiner' Dropdown component
          "None",  # str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 1' Dropdown component
          -2,  # int | float (numeric value between -2 and 2) in 'Weight' Slider component
          "None",  # str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 2' Dropdown component
          -2,  # int | float (numeric value between -2 and 2) in 'Weight' Slider component
          "None",  # str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 3' Dropdown component
          -2,  # int | float (numeric value between -2 and 2) in 'Weight' Slider component
          "None",  # str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 4' Dropdown component
          -2,  # int | float (numeric value between -2 and 2) in 'Weight' Slider component
          "None",  # str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) in 'SDXL LoRA 5' Dropdown component
          -2,  # int | float (numeric value between -2 and 2) in 'Weight' Slider component
          fn_index=4,  # 固定值4，其他貌似有问题
          # result_callbacks=on_complete
      )
  
      result_flag = True
      ai_image = []
      while result_flag:
          if 'FINISHED' == job.communicator.job.latest_status.code.value:
              f_outputs = job.communicator.job.outputs
              for f_result in f_outputs:
                  if 'dynamic' == f_result[0].get('mode', 'default'):
                      ai_image_infos = f_result[3]['value']
                      for ai_image_info in ai_image_infos:
                          file_name = ai_image_info['name']
                          ai_image.append("http://localhost:7761/file={}".format(file_name))
                          print(file_name)
                      result_flag = False
          await sleep(2)
  
      return {"image": ai_image, "code": 0}
  
  
  def on_complete(result):
      print("-------")
      print(result["prediction"])
  
  
  if __name__ == "__main__":
      uvicorn.run(app, host="0.0.0.0", port=5001)
`

**Comment by stunlocked1** [comment]
> i dont get it i thought this is a local model... why does it need 2GB of space then?
