### ISSUE TITLE
When using upscale for 4k, fooocus image processing freeze

### ISSUE THREAD

**Issue by kubilaykilinc** [lllyasviel/Fooocus#480]
Hi,

When I apply upscaling 2x or fast 2x to images larger than 1024, 1200, 1500 pixels, Fooocus completes the process. But I get this message.

"When i use upscaling upper 1024, 1200 px etc. foucus finished upscaling. After freezing generation process on UI interface.
This is happening when i get this message CMD panel:
"Image is too large. Directly returned the SR image. Usually directly return SR image at 4K resolution yields better results than SDXL diffusion."

After receiving this message, the generation process freezes on the Fooocus UI panel. Stop button does not work.

My computer config:
NVIDIA 12 GB
32GB Ram
1 TB SSD
1 TB external HDD

**Comment by OffSided** [comment]
i am just trying to go up from 2048x2048 to 4096x4096 .. i am facing the same, .. minus the freeze issue.
does Fooocus support "tiled upscaling"?

Lenovo laptop, NVIDIA 6 GB

**Comment by jazzcript** [comment]
I had the same problem, fixed by raising the Windows default swap memory size from 4096 MB (4 GB) to 40960 (40 GB)

Used this guide:
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
