### ISSUE TITLE
After v 2.0.78 update after one generation the next one duplicates the prior one

### ISSUE THREAD

**Issue by drdancm** [lllyasviel/Fooocus#481]
After v 2.0.78 update after one generation the next one duplicates the prior one, before it goes on to produce the one that was requested. In other words it uses the prompts and settings of the prior request.

**Comment by yllwboy** [comment]
I have the same issue, especially when the webUI freezes and I'm forced to refresh before the last generation is finished (on the webUI that is, when I look in the outputs folder, the requested image has already been generated). After that, it stays stuck with that bug until I close and reopen fooocus.

**Comment by drdancm** [comment]
It's always good to hear that someone has the same experience suggesting it is not a peculiar install, or hardware combination that produces an unexpected and annoying behavior.  
Thanks for your input.

At this point I'm running v 2.0.93 (?) of Fooocus-MRE and I think, the issue is still there, but I've been using at least two other packages and I can't remember for certain. I will update after I check.

**Comment by lllyasviel** [comment]
a temp fix is landed in 2.1.751

**Comment by drdancm** [comment]
Yes, this has been fixed quite awhile ago. Thanks !
