### ISSUE TITLE
Add the calling method of http://url/api

### ISSUE THREAD

**Issue by baifagg** [lllyasviel/Fooocus#483]
Many people's fooocus may be deployed on cloud machines, but their requirement is to save the pictures on their local machines, which requires url/api to call and obtain the base64 encoding of the generated pictures.

**Comment by TimothyAlexisVass** [comment]
`scp login@cloud_uri:/path/to/Fooocus/outputs/* /your/local/path`

**Comment by KubeLouis** [comment]
> `scp login@cloud_uri:/path/to/Fooocus/outputs/* /your/local/path`

emmm hope base64 in res 🙏
