### ISSUE TITLE
Is there a way to run this without the UI?

### ISSUE THREAD

**Issue by MaxTran96** [lllyasviel/Fooocus#484]
Is there a way to run this without the UI? Like a python cli for example

**Comment by mirek190** [comment]
This is based on ComfyUI ... check there is a such possibility

**Comment by TimothyAlexisVass** [comment]
If this gets merged, then yes. Otherwise you can merge it yourself: #471

**Comment by capsloq** [comment]
bump

**Comment by mashb1t** [comment]
> This is based on ComfyUI ... check there is a such possibility

^ this and using Fooocus in CLI only currently isn't possible. You may use the API though.
