### ISSUE TITLE
How to change default Model locations in Fooocus (Checkpoints, Loras and others) .

### ISSUE THREAD

**Issue by harold1110** [lllyasviel/Fooocus#489]
I want to change the default models location in Fooocus.
All my downloaded models are in ComfyUI folder and I dont want to copy those models to Fooocus folder again since I dont have sufficient storage. Is there any way to change the default models location?

**Comment by DrJKL** [comment]
You might be able to use a softlink/symlink.
https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by barepixels** [comment]
edit "user_path_config.txt"  here is mine for example


```
{
    "modelfile_path": "D:\\stable-diffusion-shared\\Ckpt\\XL",
    "lorafile_path": "D:\\stable-diffusion-shared\\Lora\\SDXL",
    "vae_approx_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\vae_approx",
    "upscale_models_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\upscale_models",
    "inpaint_models_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\inpaint",
    "fooocus_expansion_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
    "temp_outputs_path": "E:\\Fooocus-lllyasviel\\Fooocus\\outputs"
}
```

**Comment by harold1110** [comment]
> edit "user_path_config.txt" here is mine for example
> 
> ```
> {
>     "modelfile_path": "D:\\stable-diffusion-shared\\Ckpt\\XL",
>     "lorafile_path": "D:\\stable-diffusion-shared\\Lora\\SDXL",
>     "vae_approx_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\vae_approx",
>     "upscale_models_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\upscale_models",
>     "inpaint_models_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\inpaint",
>     "fooocus_expansion_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
>     "temp_outputs_path": "E:\\Fooocus-lllyasviel\\Fooocus\\outputs"
> }
> ```

Hey there, I just now tried this but when im launching after doing this, its again saying downloading models from hugging face and the "user_path_config.txt automatically resets. Is there a solution to it?

**Comment by simartem** [comment]
> edit "user_path_config.txt" here is mine for example
> 
> ```
> {
>     "modelfile_path": "D:\\stable-diffusion-shared\\Ckpt\\XL",
>     "lorafile_path": "D:\\stable-diffusion-shared\\Lora\\SDXL",
>     "vae_approx_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\vae_approx",
>     "upscale_models_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\upscale_models",
>     "inpaint_models_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\inpaint",
>     "fooocus_expansion_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
>     "temp_outputs_path": "E:\\Fooocus-lllyasviel\\Fooocus\\outputs"
> }
> ```

where is this file located for editing ? "user_path_config.txt"

Or should i create myself and how to activate it ? Is it enough to put this file in some directory and which ?

**Comment by lllyasviel** [comment]
hi the instruction is here
https://github.com/lllyasviel/Fooocus#customization

**Comment by harold1110** [comment]
> > edit "user_path_config.txt" here is mine for example
> > ```
> > {
> >     "modelfile_path": "D:\\stable-diffusion-shared\\Ckpt\\XL",
> >     "lorafile_path": "D:\\stable-diffusion-shared\\Lora\\SDXL",
> >     "vae_approx_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\vae_approx",
> >     "upscale_models_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\upscale_models",
> >     "inpaint_models_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\inpaint",
> >     "fooocus_expansion_path": "E:\\Fooocus-lllyasviel\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
> >     "temp_outputs_path": "E:\\Fooocus-lllyasviel\\Fooocus\\outputs"
> > }
> > ```
> 
> where is this file located for editing ? "user_path_config.txt"
> 
> Or should i create myself and how to activate it ? Is it enough to put this file in some directory and which ?

Its located in root folder. The name has been changed to config.txt, so open that
![image](https://github.com/lllyasviel/Fooocus/assets/145927154/e53d4a80-ae14-4ba4-b89a-1caf67a40005)

**Comment by FullyAutomatix** [comment]
There is a file name "config_modification_tutorial.txt" in the base folder ("Fooocus") for easy guide. 
Hope this helps.
