### ISSUE TITLE
can't launch on linux with ROCm

### ISSUE THREAD

**Issue by markawonge** [lllyasviel/Fooocus#491]
stable-diffusion-webui and ComfyUI both run perfectly on my system (ubuntu 22.04 + ROCm 5.6).
However, when I followed the steps in the readme (Linux (Using Anaconda))to install Fooocus, it could not run.
the code is as follows:

(fooocus) kwan@cucc:~/Fooocus$ python entry_with_update.py 
Already up-to-date
Update succeeded.
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
Fooocus version: 2.0.78
Inference Engine exists.
Inference Engine checkout finished.
Traceback (most recent call last):
  File "/home/kwan/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/home/kwan/Fooocus/launch.py", line 110, in <module>
    prepare_environment()
  File "/home/kwan/Fooocus/launch.py", line 47, in prepare_environment
    run_pip(f"install -U -I --no-deps {xformers_package}", "xformers")
NameError: name 'xformers_package' is not defined

I tried to run it in my stable-diffusion-webui and ComfyUI conda environment, but the problem still remained.

THX

**Comment by Grey3016** [comment]
I got it to work - guide here > https://www.reddit.com/r/StableDiffusion/comments/1732ho1/guide_to_install_fooocus_with_an_amd_gpu_on_linux/

**Comment by MatthewForrester** [comment]
I am not familiar with the codebase, but while looking for something else I noticed [a commit](https://github.com/lllyasviel/Fooocus/commit/71e99185cb50497d7273505986d5c8aa16b96267) intended to stop xformers being used on Linux+AMD, which might be relevant.
