### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by Rosanguis** [lllyasviel/Fooocus#498]
When I updated Fooocus today, I got the following errors:

Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "D:\SD\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\transformers\modeling_utils.py", line 463, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "D:\SD\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "D:\SD\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\transformers\modeling_utils.py", line 467, in load_state_dict
    if f.read(7) == "version":
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 64: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\SD\Fooocus_win64_1-1-1035\Fooocus\modules\async_worker.py", line 17, in worker
    import modules.default_pipeline as pipeline
  File "D:\SD\Fooocus_win64_1-1-1035\Fooocus\modules\default_pipeline.py", line 201, in <module>
    expansion = FooocusExpansion()
  File "D:\SD\Fooocus_win64_1-1-1035\Fooocus\modules\expansion.py", line 33, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(fooocus_expansion_path)
  File "D:\SD\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\transformers\models\auto\auto_factory.py", line 484, in from_pretrained
    return model_class.from_pretrained(
  File "D:\SD\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\transformers\modeling_utils.py", line 2604, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\SD\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\transformers\modeling_utils.py", line 479, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'D:\SD\Fooocus_win64_1-1-1035\Fooocus\models\prompt_expansion\fooocus_expansion\pytorch_model.bin' at 'D:\SD\Fooocus_win64_1-1-1035\Fooocus\models\prompt_expansion\fooocus_expansion\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

These errors happen every time I try to run Fooocus, but I can't locate the problem. Does anyone know how to resolve it?

**Comment by Rosanguis** [comment]
One solution failed: I tried to replace pytorch_model.bin with another version of it, and this time it produces the following error:

Some weights of the model checkpoint at D:\SD\Fooocus_win64_1-1-1035\Fooocus\models\prompt_expansion\fooocus_expansion were not used when initializing GPT2LMHeadModel: ['bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.self.query.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.4.output.dense.bias', 'bert.encoder.layer.2.attention.self.query.weight', 'bert.encoder.layer.5.attention.output.dense.bias', 'classifier.bias', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.1.intermediate.dense.bias', 'bert.encoder.layer.2.output.dense.bias', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.self.value.bias', 'bert.encoder.layer.6.attention.self.key.bias', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.dense.weight', 'bert.encoder.layer.8.attention.output.dense.bias', 'bert.encoder.layer.7.attention.self.value.bias', 'bert.encoder.layer.0.attention.self.query.bias', 'bert.encoder.layer.2.intermediate.dense.bias', 'bert.encoder.layer.6.attention.output.dense.weight', 'bert.encoder.layer.9.attention.self.key.bias', 'bert.encoder.layer.1.attention.output.dense.bias', 'bert.encoder.layer.4.intermediate.dense.weight', 'bert.encoder.layer.2.attention.self.query.bias', 'bert.encoder.layer.1.output.dense.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.dense.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.self.query.bias', 'bert.encoder.layer.6.attention.self.value.bias', 'bert.encoder.layer.11.output.dense.bias', 'bert.encoder.layer.8.attention.self.value.weight', 'bert.encoder.layer.9.attention.self.query.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.self.key.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.1.intermediate.dense.weight', 'bert.encoder.layer.9.intermediate.dense.bias', 'bert.encoder.layer.3.attention.self.value.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.self.value.weight', 'bert.encoder.layer.3.attention.output.dense.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.dense.bias', 'bert.encoder.layer.11.attention.output.dense.weight', 'bert.encoder.layer.2.attention.self.key.weight', 'bert.encoder.layer.0.attention.output.dense.weight', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.intermediate.dense.weight', 'bert.encoder.layer.3.intermediate.dense.bias', 'bert.encoder.layer.10.attention.self.key.weight', 'bert.encoder.layer.5.attention.self.value.bias', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.0.output.dense.weight', 'bert.encoder.layer.10.intermediate.dense.bias', 'bert.encoder.layer.8.output.dense.weight', 'bert.encoder.layer.4.attention.self.value.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.intermediate.dense.bias', 'bert.encoder.layer.7.output.dense.weight', 'bert.encoder.layer.6.attention.self.query.weight', 'bert.encoder.layer.10.attention.self.query.weight', 'bert.encoder.layer.4.intermediate.dense.bias', 'bert.embeddings.position_embeddings.weight', 'bert.encoder.layer.6.output.dense.bias', 'bert.encoder.layer.10.output.dense.bias', 'bert.encoder.layer.11.attention.output.dense.bias', 'bert.encoder.layer.7.output.dense.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.self.key.bias', 'bert.encoder.layer.1.attention.self.key.bias', 'bert.encoder.layer.3.attention.self.key.weight', 'bert.encoder.layer.4.attention.self.key.weight', 'bert.encoder.layer.4.attention.self.key.bias', 'bert.encoder.layer.1.attention.self.key.weight', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.self.key.bias', 'bert.encoder.layer.11.output.dense.weight', 'bert.encoder.layer.0.intermediate.dense.weight', 'bert.encoder.layer.3.attention.self.query.weight', 'bert.encoder.layer.7.attention.self.query.weight', 'bert.encoder.layer.5.attention.self.key.bias', 'bert.encoder.layer.8.attention.self.query.weight', 'classifier.weight', 'bert.encoder.layer.10.attention.self.value.weight', 'bert.encoder.layer.9.output.dense.weight', 'bert.embeddings.position_ids', 'bert.encoder.layer.9.attention.self.key.weight', 'bert.encoder.layer.5.attention.output.dense.weight', 'bert.encoder.layer.9.attention.output.dense.bias', 'bert.encoder.layer.0.attention.self.key.weight', 'bert.encoder.layer.5.intermediate.dense.bias', 'bert.encoder.layer.1.attention.self.value.bias', 'bert.encoder.layer.6.attention.self.key.weight', 'bert.encoder.layer.8.intermediate.dense.weight', 'bert.encoder.layer.1.attention.self.query.weight', 'bert.encoder.layer.8.attention.self.query.bias', 'bert.encoder.layer.3.attention.self.query.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.dense.weight', 'bert.encoder.layer.3.intermediate.dense.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.0.attention.self.value.bias', 'bert.encoder.layer.0.attention.self.query.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.output.dense.weight', 'bert.encoder.layer.5.output.dense.weight', 'bert.encoder.layer.5.attention.self.query.bias', 'bert.encoder.layer.11.attention.self.query.bias', 'bert.encoder.layer.7.attention.self.value.weight', 'bert.encoder.layer.4.attention.self.value.weight', 'bert.embeddings.token_type_embeddings.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.self.key.weight', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.intermediate.dense.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.self.key.bias', 'bert.encoder.layer.2.attention.self.value.weight', 'bert.embeddings.word_embeddings.weight', 'bert.encoder.layer.0.output.dense.bias', 'bert.encoder.layer.10.attention.self.key.bias', 'bert.encoder.layer.8.output.dense.bias', 'bert.encoder.layer.10.output.dense.weight', 'bert.encoder.layer.5.output.dense.bias', 'bert.encoder.layer.9.intermediate.dense.weight', 'bert.encoder.layer.3.output.dense.bias', 'bert.encoder.layer.8.attention.output.dense.weight', 'bert.encoder.layer.1.attention.output.dense.weight', 'bert.encoder.layer.11.attention.self.key.weight', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.self.value.bias', 'bert.encoder.layer.5.attention.self.query.weight', 'bert.encoder.layer.7.attention.self.key.bias', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.pooler.dense.weight', 'bert.encoder.layer.10.attention.self.query.bias', 'bert.encoder.layer.1.attention.self.query.bias', 'bert.encoder.layer.5.attention.self.value.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.intermediate.dense.weight', 'bert.encoder.layer.9.attention.output.dense.weight', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.6.intermediate.dense.bias', 'bert.encoder.layer.0.attention.self.key.bias', 'bert.encoder.layer.4.attention.self.query.weight', 'bert.encoder.layer.2.attention.output.dense.weight', 'bert.encoder.layer.6.output.dense.weight', 'bert.encoder.layer.8.attention.self.value.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.dense.bias', 'bert.encoder.layer.11.attention.self.query.weight', 'bert.encoder.layer.2.attention.self.value.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.0.attention.self.value.weight', 'bert.encoder.layer.9.attention.self.query.weight', 'bert.encoder.layer.10.attention.output.dense.bias', 'bert.encoder.layer.0.attention.output.dense.bias', 'bert.encoder.layer.6.attention.self.value.weight', 'bert.encoder.layer.4.output.dense.weight', 'bert.encoder.layer.7.attention.self.query.bias', 'bert.encoder.layer.3.output.dense.weight', 'bert.encoder.layer.10.attention.output.dense.weight', 'bert.encoder.layer.10.intermediate.dense.weight', 'bert.embeddings.LayerNorm.weight', 'bert.encoder.layer.0.intermediate.dense.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.dense.bias', 'bert.encoder.layer.11.attention.self.value.weight', 'bert.encoder.layer.7.intermediate.dense.bias', 'bert.encoder.layer.7.attention.self.key.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.dense.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.self.value.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.dense.bias', 'bert.encoder.layer.1.output.dense.bias', 'bert.encoder.layer.11.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.7.intermediate.dense.weight', 'bert.encoder.layer.9.attention.self.value.weight', 'bert.encoder.layer.5.intermediate.dense.weight', 'bert.encoder.layer.11.attention.self.value.bias', 'bert.encoder.layer.2.intermediate.dense.weight', 'bert.pooler.dense.bias', 'bert.encoder.layer.5.attention.self.key.weight']
- This IS expected if you are initializing GPT2LMHeadModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing GPT2LMHeadModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of GPT2LMHeadModel were not initialized from the model checkpoint at D:\SD\Fooocus_win64_1-1-1035\Fooocus\models\prompt_expansion\fooocus_expansion and are newly initialized: ['h.8.mlp.c_proj.bias', 'h.8.mlp.c_fc.bias', 'h.6.attn.c_proj.bias', 'h.6.ln_2.bias', 'h.2.mlp.c_fc.bias', 'h.5.mlp.c_proj.bias', 'h.3.ln_2.weight', 'h.9.ln_1.bias', 'h.6.attn.c_attn.bias', 'h.2.mlp.c_proj.weight', 'h.1.mlp.c_fc.bias', 'h.8.mlp.c_proj.weight', 'h.4.ln_1.weight', 'h.11.mlp.c_proj.weight', 'h.6.mlp.c_proj.weight', 'h.6.mlp.c_fc.bias', 'h.9.ln_1.weight', 'h.0.ln_1.bias', 'h.11.ln_1.bias', 'h.9.attn.c_attn.weight', 'h.4.attn.c_attn.weight', 'h.4.mlp.c_fc.bias', 'wte.weight', 'h.8.ln_1.weight', 'h.2.ln_1.bias', 'h.10.attn.c_attn.weight', 'h.0.attn.c_attn.bias', 'h.6.mlp.c_fc.weight', 'h.7.ln_1.bias', 'h.9.mlp.c_fc.weight', 'h.4.mlp.c_fc.weight', 'h.6.attn.c_attn.weight', 'h.4.mlp.c_proj.bias', 'h.1.mlp.c_proj.bias', 'h.10.ln_1.bias', 'h.0.mlp.c_fc.weight', 'h.5.mlp.c_proj.weight', 'h.4.attn.c_attn.bias', 'h.2.mlp.c_proj.bias', 'h.0.mlp.c_proj.weight', 'h.5.ln_2.bias', 'h.10.attn.c_proj.weight', 'h.3.ln_2.bias', 'h.4.attn.c_proj.weight', 'h.5.attn.c_attn.bias', 'h.11.attn.c_attn.weight', 'h.4.ln_1.bias', 'ln_f.weight', 'h.7.ln_2.weight', 'h.0.mlp.c_fc.bias', 'h.9.attn.c_proj.weight', 'h.7.mlp.c_proj.bias', 'h.4.attn.c_proj.bias', 'h.11.ln_1.weight', 'wpe.weight', 'h.0.attn.c_proj.weight', 'h.2.mlp.c_fc.weight', 'h.9.ln_2.weight', 'h.2.attn.c_attn.weight', 'h.5.ln_1.bias', 'h.7.mlp.c_proj.weight', 'h.11.ln_2.weight', 'h.1.mlp.c_proj.weight', 'h.2.attn.c_proj.bias', 'h.10.mlp.c_proj.bias', 'h.3.mlp.c_fc.weight', 'h.2.attn.c_proj.weight', 'h.11.attn.c_proj.bias', 'h.11.attn.c_attn.bias', 'h.5.attn.c_attn.weight', 'h.3.mlp.c_proj.bias', 'h.8.mlp.c_fc.weight', 'h.5.ln_1.weight', 'h.10.attn.c_proj.bias', 'h.8.attn.c_proj.bias', 'h.9.attn.c_proj.bias', 'h.8.attn.c_attn.bias', 'h.4.ln_2.weight', 'h.6.ln_1.weight', 'h.0.ln_2.weight', 'h.3.ln_1.weight', 'h.1.ln_2.bias', 'h.7.attn.c_proj.weight', 'h.10.mlp.c_fc.bias', 'h.2.ln_2.bias', 'h.5.mlp.c_fc.bias', 'h.0.ln_2.bias', 'h.10.ln_2.weight', 'h.9.mlp.c_fc.bias', 'h.11.attn.c_proj.weight', 'h.1.attn.c_proj.bias', 'h.5.ln_2.weight', 'h.9.attn.c_attn.bias', 'h.0.attn.c_attn.weight', 'h.4.ln_2.bias', 'h.2.attn.c_attn.bias', 'ln_f.bias', 'h.8.attn.c_proj.weight', 'h.8.attn.c_attn.weight', 'h.3.mlp.c_fc.bias', 'h.0.attn.c_proj.bias', 'h.10.ln_2.bias', 'h.1.attn.c_attn.weight', 'h.2.ln_1.weight', 'h.7.attn.c_attn.weight', 'h.3.attn.c_attn.weight', 'h.5.attn.c_proj.weight', 'h.8.ln_2.bias', 'h.11.ln_2.bias', 'h.9.ln_2.bias', 'h.3.attn.c_proj.bias', 'h.5.mlp.c_fc.weight', 'h.7.ln_1.weight', 'h.8.ln_1.bias', 'h.1.ln_1.bias', 'h.3.attn.c_proj.weight', 'h.7.attn.c_attn.bias', 'h.9.mlp.c_proj.weight', 'h.10.mlp.c_proj.weight', 'h.7.ln_2.bias', 'h.6.ln_1.bias', 'h.5.attn.c_proj.bias', 'h.3.mlp.c_proj.weight', 'h.9.mlp.c_proj.bias', 'h.3.ln_1.bias', 'h.10.mlp.c_fc.weight', 'h.1.attn.c_proj.weight', 'h.0.ln_1.weight', 'h.1.ln_2.weight', 'h.1.ln_1.weight', 'h.8.ln_2.weight', 'h.10.ln_1.weight', 'h.4.mlp.c_proj.weight', 'h.1.mlp.c_fc.weight', 'h.3.attn.c_attn.bias', 'h.11.mlp.c_fc.bias', 'h.2.ln_2.weight', 'h.0.mlp.c_proj.bias', 'h.6.ln_2.weight', 'h.7.mlp.c_fc.bias', 'h.10.attn.c_attn.bias', 'h.7.attn.c_proj.bias', 'h.1.attn.c_attn.bias', 'h.6.mlp.c_proj.bias', 'h.7.mlp.c_fc.weight', 'h.11.mlp.c_proj.bias', 'h.6.attn.c_proj.weight', 'h.11.mlp.c_fc.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Fooocus Expansion engine loaded for cuda:0.

**Comment by mashb1t** [comment]
Please test again with the latest version of Fooocus and let us know the results.
