### ISSUE TITLE
Is Fooocus only for SDXL? Bit confused

### ISSUE THREAD

**Issue by vesper8** [lllyasviel/Fooocus#499]
So it seems like if you put other checkpoints in the right folder, they are available in the UI to change to.. but everywhere in the UI it reads SDXL this and SDXL that. Also I've been trying to use other models and something seems off.. it feels like SDXL is still being used even though I've disabled all styles and unselected all SDXL models/diffusers.

It seems like Fooocus would be great as an alternative to Comfy and Automatic for general use with all models.. but for that to happen it needs to be decoupled slightly? I feel like either the Github description should be clearer that this is heavily optimized for SDXL and its derivatives and won't work well with older custom models, or it should be more intuitive to use with older pre-sdxl models.

**Comment by barepixels** [comment]
@vesper8 read this  https://github.com/MoonRide303/Fooocus-MRE/discussions/121

**Comment by bach777** [comment]
Please make available the same functions for standar SD 1.5 models, your implementation of inpainting and outpainting is way better than automatic's

**Comment by MoonRide303** [comment]
@vesper8 Vanilla Fooocus (and Fooocus-MRE versions prior to v2.0.78.3) will revert to default SDXL model when trying to load non-SDXL model.

@bach777 Inpainting in Fooocus relies on special patch model for SDXL (something like LoRA). I think it's possible to create similar patch model for SD 1.x and 2.x (for example by making diff between base SD model and inpainting variant of it), but it's probably out of scope for vanilla (it supports SDXL, only).

**Comment by LadyFlames** [comment]
**### _the only Model and refiner that can be used with Fooocus is sd_xl_base_1.0_0.9_vae.safetensor and sd_xl_Refiner_1.0_0.9_vae.safetensor_** 

ive tried it with DreamShaperXL and many other XL Models and sd_xl_Base_1.0 and sd_xl_Refiner_1.0 wont let me use anything  else or any of them other than the first 2 at the beginning i mentioned i hope that clarifies thing  in a nutshell the only model and refiner that are usable are the first two that are in the Bold Text those 2 are the only 2 usable
