### ISSUE TITLE
img2img

### ISSUE THREAD

**Issue by webe998** [lllyasviel/Fooocus#5]
Very amazing creation, would it be possible to add a img2img to this?

**Comment by cerrec** [comment]
I desperately want img2img, as well. This single feature would exponentially increase the usefulness of Fooocus.

**Comment by MoonRide303** [comment]
@webe998 @cerrec I've just implemented initial version of simple img2img on [my fork](https://github.com/MoonRide303/Fooocus-MRE) (commit [62d801b](https://github.com/MoonRide303/Fooocus-MRE/commit/62d801b5f29316f78f65ce90d7f3dffe897dac89)) - feel free to check it out, and let me know if works for you.

**Comment by cerrec** [comment]
Thanks, but I have no idea how to use your fork. I'm on Windows and all I know is to click on webui-user.bat to start the app.

**Comment by cerrec** [comment]
Could you PLEASE give detailed instructions on how to install this. I just don't get it.

**Comment by MoonRide303** [comment]
@cerrec Simplest way would be like that:

1. Download original Fooocus package ([v1.0.35](https://github.com/lllyasviel/Fooocus/releases/download/1.0.35/Fooocus_win64_1-1-1035.7z)).
2. Unzip original Fooocus where you like.
3. Download Fooocus-MRE zip from [moonride-main branch](https://github.com/MoonRide303/Fooocus-MRE/archive/refs/heads/moonride-main.zip) (github makes and updates those zips automatically).
4. Overwrite files from original Fooocus folder with those from Fooocus-MRE archive.
5. Use the sam run.bat.

**Comment by ke1ne** [comment]
@MoonRide303 Hi, are steps 1-2 necessary?

**Comment by MoonRide303** [comment]
@ke1ne I've just prepared standalone release for Fooocus-MRE v1.0.40 - it's available [here](https://github.com/MoonRide303/Fooocus-MRE/releases/download/v1.0.40/Fooocus-MRE-v1.0.40.7z), you can check it out.

**Comment by cerrec** [comment]
I tried to download your standalone version, but I get this error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>677828148/5cf54627-d9c6-43f0-a344-37607d7a34d8</Key>
<RequestId>MQN8WMSDT6Z9JSDS</RequestId>
<HostId>
t71RMYdBoELx9qlb79upRfNzM4Q055Amv43nqaYBykmds7DAGKg+RFe2dyy09brss4evW1hzCE9gfH5bg/xR0KzRMJ/2eYpKlrmm7XoNdwQ=
</HostId>
</Error>

**Comment by cerrec** [comment]
IT WORKS!  OH, YEAH! This is great! Thank you, Thank you!!

**Comment by cerrec** [comment]
When unzipping your archive, I got this error. The program seems to run fine, so I don't know whether this is significant or not. Just thought I'd mention it.

![ERROR](https://github.com/lllyasviel/Fooocus/assets/26256158/54306010-a03c-482b-b3f7-87a37e006984)

**Comment by MoonRide303** [comment]
@cerrec No errors here (using latest 7-Zip, 23.01).
