### ISSUE TITLE
is this a local model or not

### ISSUE THREAD

**Issue by stunlocked1** [lllyasviel/Fooocus#500]
is this a local model or not

i dont get how it could show someone elses promts if its local

**Comment by captainpd** [comment]
> is this a local model or not
> 
> i dont get how it could show someone elses promts if its local

Fooocus is using SDXL base and refine model plus lora by default. You can share the prompts by checking the log page in the output folder named by the date of creation.
log File: `.\outputs\{DATE}\log.html`
![image](https://github.com/lllyasviel/Fooocus/assets/93906313/77c79d44-a9ad-445e-9bc6-efc088137104)

**Comment by stunlocked1** [comment]
> > is this a local model or not
> > i dont get how it could show someone elses promts if its local
> 
> Fooocus is using SDXL base and refine model plus lora by default. You can share the prompts by checking the log page in the output folder named by the date of creation. log File: `.\outputs\{DATE}\log.html` ![image](https://user-images.githubusercontent.com/93906313/272609679-77c79d44-a9ad-445e-9bc6-efc088137104.png)

so is it a local model or not?

**Comment by captainpd** [comment]
> > > is this a local model or not
> > > i dont get how it could show someone elses promts if its local
> > 
> > 
> > Fooocus is using SDXL base and refine model plus lora by default. You can share the prompts by checking the log page in the output folder named by the date of creation. log File: `.\outputs\{DATE}\log.html` ![image](https://user-images.githubusercontent.com/93906313/272609679-77c79d44-a9ad-445e-9bc6-efc088137104.png)
> 
> so is it a local model or not?

It is local, it will use models downloaded to `Fooocus\models\checkpoints` by default

**Comment by stunlocked1** [comment]
> > > > is this a local model or not
> > > > i dont get how it could show someone elses promts if its local
> > > 
> > > 
> > > Fooocus is using SDXL base and refine model plus lora by default. You can share the prompts by checking the log page in the output folder named by the date of creation. log File: `.\outputs\{DATE}\log.html` ![image](https://user-images.githubusercontent.com/93906313/272609679-77c79d44-a9ad-445e-9bc6-efc088137104.png)
> > 
> > 
> > so is it a local model or not?
> 
> It is local, it will use models downloaded to `Fooocus\models\checkpoints` by default
how could it show someone elses promts if its local

**Comment by mashb1t** [comment]
Just to clarify: Those are not someone elses prompts but the prompts added by the local prompt expansion Fooocus V2. This is like prompt magic in LeonardoAI, it adds tokens to your prompt matching the relevant input.
=> no worries, all local and only on your machine.
