### ISSUE TITLE
[BUG]The returned image is not currently requested

### ISSUE THREAD

**Issue by qy8502** [lllyasviel/Fooocus#501]
When I requested to draw a "a sleeping cat", I accidentally closed the page in the middle of the drawing process, meaning that I disconnected the websocket connection.
![QQ截图20230928090756](https://github.com/lllyasviel/Fooocus/assets/2696897/8a4dd3b9-03f0-4ff1-b3b9-9994a246b9e1)

Then on the page that reopens, request to draw a new piece "a flying bird". However, the result it gave me was the "a sleeping cat" requested in the previous picture.
![QQ截图20230928091036](https://github.com/lllyasviel/Fooocus/assets/2696897/f53b5af1-e488-49ed-9040-4fa528004d93)

If I ask again for a picture of "a jumping monkey", it will give me a picture of "a flying bird". I won't be able to get the correct drawing until I restart the fooocus program.
![QQ截图20230928091911](https://github.com/lllyasviel/Fooocus/assets/2696897/43d862ee-143e-49c3-bf35-793febeef0fc)

**Comment by serkanp** [comment]
Same here, is there any option to reset the process queue?

**Comment by barepixels** [comment]
When someone accidentally close the page in the middle of the drawing process, Fooocus in the CMD windows never receives the instruction to stop...

Anyway

Yesterday MoonRide303 added a new feature to Fooocus-MRE.   Load Last Prompt
If you ever crash, close, or reload the page, you can restore the last prompt.  This is very useful

**Comment by qy8502** [comment]
> When someone accidentally close the page in the middle of the drawing process, Fooocus in the CMD windows never receives the instruction to stop... The bug is user error, not software
@barepixels 

If I deploy fooocus to the server, I have to need operations personnel to handle the error when it occurs. 
The user's error will cause the software to no longer provide normal services, or the error may be an unintentional behavior such as network failure.
Please solve this problem

**Comment by barepixels** [comment]
Am thinking this is a ComfyUI issue

**Comment by MoonRide303** [comment]
@barepixels It's not ComfyUI problem - Comfy uses LiteGraph for UI part, and if you close and re-open tab it restores your workspace. Fooocus uses Gradio for UI part, and it's more like missing feature than a bug. Probably could be implemented using [Gradio State](https://www.gradio.app/docs/state).

**Comment by lllyasviel** [comment]
a temp fix is landed in 2.1.751
