### ISSUE TITLE
[feature request] : input image variation levels as a slider ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [lllyasviel/Fooocus#510]
Hello,

Would it be possible to turn the input image variation buttons (subtle/strong) into a slider to add some more flexibility ?

**Comment by MoonRide303** [comment]
@SuperUserNameMan Vanilla Fooocus aims for simplicity, Midjourney style. If you want increased amount of control over generation process (including options like img2img denoise slider) you can take a look at [Fooocus-MRE](https://github.com/MoonRide303/Fooocus-MRE) fork of mine, or use applications fully dedicated for advanced users, like [ComfyUI](https://github.com/comfyanonymous/ComfyUI), [SD web UI](https://github.com/AUTOMATIC1111/stable-diffusion-webui), or [InvokeAI](https://github.com/invoke-ai/InvokeAI).

**Comment by SuperUserNameMan** [comment]
thanks for the links, I'll give a look at Fooocus-MRE and InvokeAI.

I'm asking about a little bit more flexibility for variation levels, because sometimes, "subtle" is too subtle, and "strong" is too strong, and there is nothing available in between.

**Comment by MoonRide303** [comment]
@SuperUserNameMan I prefer fine-grained controls, too - but for casual users something like "Vary (Strong)" is probably easier to understand than "Image-2-Image Denoise 0.85" :).

**Comment by captainpd** [comment]
> @SuperUserNameMan Vanilla Fooocus aims for simplicity, Midjourney style. If you want increased amount of control over generation process (including options like img2img denoise slider) you can take a look at [Fooocus-MRE](https://github.com/MoonRide303/Fooocus-MRE) fork of mine, or use applications fully dedicated for advanced users - like [ComfyUI](https://github.com/comfyanonymous/ComfyUI), [SD web UI](https://github.com/AUTOMATIC1111/stable-diffusion-webui), or [InvokeAI](https://github.com/invoke-ai/InvokeAI).

Great job, bro. With your fork, I think it is easier for different experiments to happen, and more demands/discussion can happen.

**Comment by MoonRide303** [comment]
@captainpd I am glad you like it :). I think both versions are fine, just dedicated to different user groups - vanilla has simpler UI and is better option for people making their first steps with generative art, and MRE might be good choice for a bit more experienced prompters, who don't mind being exposed to more options and/or more advanced workflows.
