### ISSUE TITLE
通过0为固定seed值，测算出模型的最优匹配参数的算法，可以做成模型适配器。

### ISSUE THREAD

**Issue by boombbo** [lllyasviel/Fooocus#514]
您好，controlnet作者，我有一个测试模型的算法，可以得到任意模型的最优参数，但由于我自身不够强大的程序基础，我没办法将这个算法得以实现为程序，可是我通过手动调配和操作，是成功执行了的，如果您愿意花一些时间听一下，我可以跟您分享。

**Comment by boombbo** [comment]
希望可以得到您的回复，因为我知道您在优化上不断的追求新的性能，这个绝对是没有人测试出来的一种新算法

**Comment by captainpd** [comment]
你可以把实现方式写在这里呀 大家一起帮你看看 最优参数听起来有点不可思议 如果你不描述一下 很难理解呢

**Comment by aimarxjg** [comment]
怎么了，不更新你的原版老6插件了？
