### ISSUE TITLE
[Feature Request] Add by <artist name> prompt templates similar to styles selector (with a list of 1000+ artists known by SDXL)

### ISSUE THREAD

**Issue by ikarsokolov** [lllyasviel/Fooocus#516]
I consider style templates to be one of the most impressive features of Fooocus .

It would be fantastic to have the option to combine artist name templates with general styles. For instance, something like:
> colored pencil art by Wassily Kandinsky

I've stumbled upon a list of over 1000 artists known by SDXL 1.0, complete with their corresponding prompt tags, which you can find [here](https://huggingface.co/spaces/mattthew/SDXL-artists-browser/blob/main/artists_and_tags.js).

The [web app](https://huggingface.co/spaces/mattthew/SDXL-artists-browser) from which I obtained this list is truly remarkable. It allows users to compare the output of different checkpoints against the base SDXL model.

**Comment by MoonRide303** [comment]
@lllyasviel I've checked few names from this list marked as known for SDXL and using "art by [name]" in raw prompt (no V2 or style being used), and indeed it seems those names are known by SDXL (big changes in the style compared to using fake artist names like "art by John Smith").

Might be worth checking out to increase both artistic expression variety, and alignent with desired style - for example by refering to like 3 random artists with matching tags, or something like that (so the generation would be driven more by related art style rather than single artist).

**Comment by MoonRide303** [comment]
Another list that might be useful: [Image Synthesis Style Studies Database (The List)](https://docs.google.com/spreadsheets/d/14xTqtuV3BuKDNhLotB_d1aFlBGnDJOY0BRXJ8-86GpA/edit?usp=sharing) - about 3500 names, close to 2800 described as recognized by CLIP.

**Comment by MoonRide303** [comment]
@lllyasviel What do you think about adding those names (recognized by CLIP) as a wildcard (artist.txt)?

I did some quick tests with it (no styles, prompt `modern sports car, art by __artist__`, empty negative prompt) and it looks like simple way to increase artistic variety of the output.

seed 0:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/dabf5bc1-2c4e-42dd-b8ab-dc9aea521e95)

seed 1:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/fc723710-ba40-412a-af98-0e44f702c7d2)

seed 2:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/b4640fae-8e27-4260-b5db-e5cf7298816a)

seed 3:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/022ff307-b051-435f-958e-919d0f4cb0ae)

**Comment by MoonRide303** [comment]
I guess I needed to take some sleep - changing seed by itself will greatly change output, so it was really dumb test. Another run - this time using same seed, and using 4 different names manually picked from the list.

seed 0, no styles, prompt `modern sports car, art by Adriaen van Utrecht`, empty negative prompt:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/fc5541b4-2be2-4902-b600-fd5e4b00b59c)

seed 0, no styles, prompt `modern sports car, art by Agnes Lawrence Pelton`, empty negative prompt:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/c52712b4-d33b-465b-95b6-9e74e2654936)

seed 0, no styles, prompt `modern sports car, art by Albert Benois`, empty negative prompt:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/08b06a92-7938-44ae-b582-ed412f523412)

seed 0, no styles, prompt `modern sports car, art by Alberto Burri`, empty negative prompt:
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/e5d278fd-62d7-4bdf-926a-dc6cef5a7aa2)

**Comment by MoonRide303** [comment]
@ikarsokolov I added this as a wildcard (https://github.com/lllyasviel/Fooocus/pull/721) - you can try using `by __artist__` in your prompt to enhance generation style with influence of random artist.

@lllyasviel This can be still used for further improvements - for example if we used additional information from this list (like tags) to automatically pick like let's say 3 random names aligned with style desired by the user.
