### ISSUE TITLE
The repository will not checkout at correct commit after delete 'ComfyUI-from-StabilityAI-Official' folder

### ISSUE THREAD

**Issue by konieshadow** [lllyasviel/Fooocus#531]
As I test, after run 'rm -rf repositories/ComfyUI-from-StabilityAI-Official' and then launch the app, after auto git clone, the ComfyUI repository will always be at master branch with latest commit.

**Comment by lllyasviel** [comment]
should fix after 2.0.86

**Comment by lllyasviel** [comment]
feel free to reopen is not fixed
