### ISSUE TITLE
potential Hugging Face trial space?

### ISSUE THREAD

**Issue by captainpd** [lllyasviel/Fooocus#532]
I really appreciate the optimizing SDXL and give it a chance to be compared with MidJourney.

Is there any chance for fooocus to have a space on huggingface for other people without good video card (also not familiar with colab) to have a trial easily? This may encourage more people starting get involved in.

**Comment by mashb1t** [comment]
You can simply use your own Colab isntance for free, see https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#colab
