### ISSUE TITLE
Bugs?

### ISSUE THREAD

**Issue by Geo2D3D** [lllyasviel/Fooocus#535]
Hello! Again, thank you very much for your cool Fooocus!
Here's what my console says when the rendering stops; is it my machine that fails?

loading in lowvram mode 3100.736177444458
  0%|                                                                                                                                                                           | 0/30 [00:00<?, ?it/s]C:\Users\g\Documents\github\stable-diffusion-FOOOCUS\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py:594: UserWarning: Should have tb<=t1 but got tb=14.614643096923828 and t1=14.614643.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
 67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 20/30 [00:21<00:10,  1.05s/it]loading new
loading in lowvram mode 3089.806565284729
Refiner swapped.
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 28/30 [00:30<00:02,  1.05s/it]C:\Users\glitv\Documents\github\stable-diffusion-FOOOCUS\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py:585: UserWarning: Should have ta>=t0 but got ta=0.02916753850877285 and t0=0.029168.
  warnings.warn(f"Should have ta>=t0 but got ta={ta} and t0={self._start}.")

**Comment by captainpd** [comment]
It seems fine. Have you clicked the console? That will pause it. If you ever clicked the console, you can press any key to resume the process.

**Comment by Geo2D3D** [comment]
Hi! Thank you for your concern,quick reply and hint! 
Do you, please, mean that it's normal to having some tasks stopping without reaching the 100% during the rendering process?

**Comment by captainpd** [comment]
> Hi! Thank you for your concern,quick reply and hint! Do you, please, mean that it's normal to having some tasks stopping without reaching the 100% during the rendering process?

It is a feature of the cmd window that it will scroll down automatically unless you clikc on it. (which will make the whole programme pause)

It is unusual for tasks to stop automatically without any eye-catching errors. So I think there is some chance that you clicked the cmd window and the cmd just pause so there the process never ended.

**Comment by Geo2D3D** [comment]
Hi! Thank you! It does it always;.

I don't use to click in the console, just to copy specific behaviors. 
What is weird is that, even if the process stops, as the alerts I copied in my comment, show it, generated images are ok... Anyways...

Please, drop an eye on the other comment I dropped here, related to the fact that the ratios we manually enter in the sdxl_styles.py file get overwritten when there is an update of Fooocus; and where I humbly suggest to put them in a *.json file...

**Comment by barepixels** [comment]
maybe out of memories.  I see you are in lowvram mode.  What's your video card spec?

**Comment by barepixels** [comment]
Let's hope someone with a similar card can confirm if it's working for them or not.  Mean while, you can try to reboot the computer, make sure only browser running.  Basically try to free up vram as best as you can.  I am assuming:
loading in lowvram mode 3100.736177444458
means you only have 3gigs of vram available

**Comment by Geo2D3D** [comment]
Hi and thank you! Is there, please, a way to either assign my 6Go of VRam to the process, or at least more than the 3 ones you mention? Through a command in the run.bat file?

As, if I remember well, Fooocus is less "VRam-vore" than automatic1111.

**Comment by barepixels** [comment]
You have 6 GIGs There may be other programs running in the background using some of it or not releasing it for Fooocus.  That why I suggest for you to reboot.  To clear the Vram.

SDXL is 4 times larger than SD 1.5 so SDXL/Fooocus  need more vram

**Comment by Geo2D3D** [comment]
Thank you! I use SD 1.5.2. Anyways, I stop my comments here, as I don't want to be much too demanding. 

Have a nice day, or evening, according to where you live :)

**Comment by vicento** [comment]
got this error too on Mac studio M1 32 giga ram. 
Generating images are OK, but i don't know if and how i can fix this error.
```

/Users/stephane/Fooocus/fooocus_env/lib/python3.10/site-packages/torchsde/_brownian/brownian_interval.py:594: UserWarning: Should have tb<=t1 but got tb=14.614643096923828 and t1=14.614643.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
```

**Comment by Geo2D3D** [comment]
Hi Vicento! Yes, let's see if the creator of this cool app will find the way to fix that :)

**Comment by karklav** [comment]
hey i am having the same issues (6go Vram) i restart pc, start the app. but still got 5 min to generate one pic. is there a way to force using more Vram?

**Comment by barepixels** [comment]
{tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.") is normal.  It was explained as the coder of ComfyUI left it in as a note for himself.  I get it too and am using a pc not mac

**Comment by karklav** [comment]
ah ok but what about the lowvram ? thank you so much for your fast answer

**Comment by barepixels** [comment]
I will explain again

You have 6 physical GIGs There may be other programs running in the background using some of it or not releasing it for Fooocus. That why I suggest for you to reboot. To clear the Vram.

SDXL is 4 times larger than SD 1.5 so SDXL/Fooocus need more vram

**Comment by mashb1t** [comment]
> Hi! Thank you! A Nvidia RTX 3060-laptop with 6Go of VRam.

Sorry for being a bit late to the party but this should be sufficient to run Fooocus, see https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement
Please try again with the latest version of Fooocus as many optimisations have found their way into the code. Thanks!
Feel free to reopen or comment if you still have feedback, much appreciated.
