### ISSUE TITLE
this stop the run.bat to this max of No module named 'yaml'

### ISSUE THREAD

**Issue by AkoZ** [lllyasviel/Fooocus#539]
1. i tried some re-install of pyyaml but nothing
2. one thing was to upgrade torchsde .. ok well done.:
3. here is the complete process after run.bat:

C:\Fooocus_installedHere\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Error processing line 1 of C:\Fooocus_installedHere\Fooocus\python_embeded\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "site.py", line 186, in addpackage
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Fast-forward merge
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.0.87
Inference Engine exists and URL is correct.
Inference Engine checkout finished for 9bfec2bdbf0b0d778087a9b32f79e57e2d15b913.
Installing requirements
Traceback (most recent call last):
  File "C:\Fooocus_installedHere\Fooocus\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Fooocus_installedHere\Fooocus\Fooocus\launch.py", line 117, in <module>
    from webui import *
  File "C:\Fooocus_installedHere\Fooocus\Fooocus\webui.py", line 1, in <module>
    import gradio as gr
  File "C:\Fooocus_installedHere\Fooocus\python_embeded\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Fooocus_installedHere\Fooocus\python_embeded\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Fooocus_installedHere\Fooocus\python_embeded\lib\site-packages\gradio\components\annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
  File "C:\Fooocus_installedHere\Fooocus\python_embeded\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "C:\Fooocus_installedHere\Fooocus\python_embeded\lib\site-packages\gradio_client\client.py", line 24, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
  File "C:\Fooocus_installedHere\Fooocus\python_embeded\lib\site-packages\huggingface_hub\__init__.py", line 332, in __getattr__
    submod = importlib.import_module(submod_path)
  File "importlib\__init__.py", line 126, in import_module
  File "C:\Fooocus_installedHere\Fooocus\python_embeded\lib\site-packages\huggingface_hub\hf_api.py", line 51, in <module>
    from huggingface_hub.utils import (
  File "C:\Fooocus_installedHere\Fooocus\python_embeded\lib\site-packages\huggingface_hub\utils\__init__.py", line 32, in <module>
    from ._errors import (
  File "C:\Fooocus_installedHere\Fooocus\python_embeded\lib\site-packages\huggingface_hub\utils\_errors.py", line 5, in <module>
    from ._fixes import JSONDecodeError
  File "C:\Fooocus_installedHere\Fooocus\python_embeded\lib\site-packages\huggingface_hub\utils\_fixes.py", line 21, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

C:\Fooocus_installedHere\Fooocus>pause
Appuyez sur une touche pour continuer... then OUT ...

**Comment by lllyasviel** [comment]
have you modified any file ?

**Comment by AkoZ** [comment]
the config one : the file user_path_config.txt:

{
    "modelfile_path": "X:\\SDmodels",
    "lorafile_path": "X:\\SDmodels\\LORA",
    "vae_approx_path": "X:\\SDmodels\\VAE",
    "upscale_models_path": "X:\\SDmodels\\upscale_models",
    "inpaint_models_path": "X:\\SDmodels",
    "fooocus_expansion_path": "L:\\SD15b\\Fooocus\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
    "temp_outputs_path": "E:\\__DL3\\1111\\SD15\\1111_imgs\\FoOocus imgs"
}

**Comment by lllyasviel** [comment]
you mentioned that you updated torchsde - this indicates that you modified the environment. 
what is the cause of updating torchsde and using modified environment?

**Comment by AkoZ** [comment]
coz it said abot being obsolete version.. so i upgrade it

**Comment by lllyasviel** [comment]
what is the error look like if no modifications are applied to the environment?

**Comment by AkoZ** [comment]
exactly the same

**Comment by AkoZ** [comment]
HEy i got it !!! ;) 
i just " \Fooocus\python_embeded\Lib\site-packages>pip install --upgrade pyyaml "
and the new version is from 6.0 to pyyaml-6.0.1 !! oops ;) just that .. the screen opens alone
i'm on trying to generate sthing... it is to charge checkpoint . (as i put those on an external hdd, it's a bit not convenient.
tahnk you to try to solve. next to an other bug ? ;)

**Comment by lllyasviel** [comment]
running "pip install --upgrade pyyaml" in "python_embeded\Lib\site-packages" will not do any real things.
This will install a pyyaml inside your Windows system python, but Fooocus does not use Windows system python.
If this happens to work, then your windowns installation of python environment may already have severe soft linking problems to mess all python based software.
you may want to run "pip list" in "python_embeded\Lib\site-packages" and see what happens

**Comment by AkoZ** [comment]
Package                     Version         Editable project location
--------------------------- --------------- ------------------------------------------------------------------------
absl-py                     1.3.0
accelerate                  0.21.0
addict                      2.4.0
aiohttp                     3.8.3
aiosignal                   1.3.1
albumentations              1.3.0
altair                      4.2.0
antlr4-python3-runtime      4.9.3
anyio                       3.7.1
asttokens                   2.2.1
async-timeout               4.0.2
attrs                       22.1.0
backcall                    0.2.0
basicsr                     1.4.1
beautifulsoup4              4.11.2
bidict                      0.22.0
bitsandbytes                0.40.1.post1
blinker                     1.5
boltons                     21.0.0
cachetools                  5.2.0
certifi                     2022.9.24
cffi                        1.15.1
chardet                     4.0.0
charset-normalizer          2.1.1
clean-fid                   0.1.34
click                       8.1.7
clip                        1.0
clip-anytorch               2.5.2
clipseg                     0.0.1
colorama                    0.4.6
coloredlogs                 15.0.1
commonmark                  0.9.1
compel                      2.0.2
contourpy                   1.0.6
controlnet-aux              0.0.6
cycler                      0.11.0
datasets                    2.14.4
decorator                   5.1.1
dependency-injector         4.40.0
diffusers                   0.19.3
dill                        0.3.7
distlib                     0.3.6
dnspython                   2.4.2
docker-pycreds              0.4.0
dynamicprompts              0.29.0
easing-functions            1.0.4
einops                      0.6.0
entrypoints                 0.4
eventlet                    0.33.2
exceptiongroup              1.1.0
executing                   1.2.0
facexlib                    0.2.5
fastapi                     0.88.0
fastapi-events              0.8.0
fastapi-socketio            0.0.10
fastcore                    1.5.27
filelock                    3.8.2
filterpy                    1.4.5
Flask                       2.1.3
Flask-Cors                  3.0.10
Flask-SocketIO              5.3.0
flaskwebgui                 1.0.3
flatbuffers                 23.5.26
fonttools                   4.38.0
frozenlist                  1.3.3
fsspec                      2022.11.0
ftfy                        6.1.1
future                      0.18.2
gdown                       4.6.4
getpass-asterisk            1.0.1
gfpgan                      1.3.8
gitdb                       4.0.10
GitPython                   3.1.29
google-auth                 2.15.0
google-auth-oauthlib        0.4.6
greenlet                    2.0.1
grpcio                      1.51.1
h11                         0.14.0
httptools                   0.6.0
huggingface-hub             0.16.4
humanfriendly               10.0
idna                        2.10
imageio                     2.31.2
imageio-ffmpeg              0.4.7
importlib-metadata          5.1.0
iniconfig                   2.0.0
invisible-watermark         0.2.0
InvokeAI                    3.0.2.post1     c:\users\USER\appdata\local\programs\python\python310\lib\site-packages
ipython                     8.14.0
itsdangerous                2.1.2
jedi                        0.18.2
Jinja2                      3.1.2
joblib                      1.2.0
jsonmerge                   1.9.0
jsonschema                  4.17.3
k-diffusion                 0.0.1
kiwisolver                  1.4.4
kornia                      0.6.8
lazy_loader                 0.3
lightning-utilities         0.9.0
llvmlite                    0.40.1
lmdb                        1.4.0
loguru                      0.6.0
lovely-numpy                0.2.8
lovely-tensors              0.1.14
lpips                       0.1.4
Markdown                    3.4.1
markdown-it-py              3.0.0
MarkupSafe                  2.1.3
matplotlib                  3.6.2
matplotlib-inline           0.1.6
mdurl                       0.1.2
mediapipe                   0.10.3
mpmath                      1.2.1
multidict                   6.0.3
multiprocess                0.70.15
mypy-extensions             0.4.3
networkx                    2.8.8
npyscreen                   4.10.5
numba                       0.57.1
numpy                       1.24.4
oauthlib                    3.2.2
omegaconf                   2.2.3
onnx                        1.14.1
onnxruntime                 1.15.1
open-clip-torch             2.7.0
opencv-contrib-python       4.8.0.76
opencv-python               4.6.0.66
opencv-python-headless      4.6.0.66
packaging                   22.0
pandas                      1.5.2
parso                       0.8.3
pathtools                   0.1.2
picklescan                  0.0.5
pickleshare                 0.7.5
Pillow                      9.3.0
pip                         23.1.2
platformdirs                2.6.0
pluggy                      1.0.0
promise                     2.3
prompt-toolkit              3.0.39
protobuf                    3.20.3
psutil                      5.9.4
pudb                        2014.1
pure-eval                   0.2.2
pyarrow                     10.0.1
pyasn1                      0.4.8
pyasn1-modules              0.2.8
pycparser                   2.21
pydantic                    1.10.12
pydeck                      0.8.0
pyDeprecate                 0.3.2
Pygments                    2.13.0
Pympler                     1.0.1
pyparsing                   3.0.9
pypatchmatch                0.1.4
pyperclip                   1.8.2
pyre-extensions             0.0.29
pyreadline3                 3.4.1
pyrsistent                  0.19.2
PySocks                     1.7.1
pytest                      7.2.1
python-dateutil             2.8.2
python-dotenv               1.0.0
python-engineio             4.3.4
python-multipart            0.0.6
python-socketio             5.7.2
pytorch-lightning           2.0.6
pytz                        2022.6
pytz-deprecation-shim       0.1.0.post0
PyWavelets                  1.4.1
pywin32                     305
PyYAML                      6.0.1
qudida                      0.0.4
realesrgan                  0.2.5.0
regex                       2022.10.31
requests                    2.28.2
requests-oauthlib           1.3.1
resize-right                0.0.2
rich                        13.5.2
rsa                         4.9
safetensors                 0.3.1
scikit-image                0.21.0
scikit-learn                1.2.0
scipy                       1.9.3
semver                      2.13.0
Send2Trash                  1.8.0
sentencepiece               0.1.99
sentry-sdk                  1.11.1
setproctitle                1.3.2
setuptools                  67.5.1
shortuuid                   1.0.11
six                         1.16.0
smmap                       5.0.0
sniffio                     1.3.0
sounddevice                 0.4.6
soupsieve                   2.4
stack-data                  0.6.2
starlette                   0.22.0
streamlit                   1.15.2
style                       1.1.0
sympy                       1.11.1
taming-transformers-rom1504 0.0.6
tb-nightly                  2.12.0a20221208
tensorboard                 2.11.0
tensorboard-data-server     0.6.1
tensorboard-plugin-wit      1.8.1
test-tube                   0.7.5
threadpoolctl               3.1.0
tifffile                    2022.10.10
timm                        0.6.13
tokenizers                  0.12.1
tomesd                      0.1.3           c:\users\USER\appdata\local\programs\python\python310\lib\site-packages
toml                        0.10.2
tomli                       2.0.1
toolz                       0.12.0
torch                       2.0.1+cu118
torch-fidelity              0.3.0
torchaudio                  2.0.2+cu117
torchdiffeq                 0.2.3
torchmetrics                0.11.0
torchsde                    0.2.5
torchvision                 0.15.2+cu118
tornado                     6.2
tqdm                        4.64.1
traitlets                   5.9.0
trampoline                  0.1.2
transformers                4.31.0
typing_extensions           4.4.0
typing-inspect              0.8.0
tzdata                      2022.7
tzlocal                     4.2
update                      0.0.1
urllib3                     1.26.13
urwid                       2.1.2
uvicorn                     0.21.1
validators                  0.18.2
virtualenv                  20.17.1
wandb                       0.13.6
watchdog                    2.2.1
watchfiles                  0.20.0
wcwidth                     0.2.5
websockets                  11.0.3
Werkzeug                    2.3.7
wheel                       0.38.4
whichcraft                  0.6.1
win32-setctime              1.1.0
windows-curses              2.3.1
xformers                    0.0.21
xxhash                      3.3.0
yacs                        0.1.8
yapf                        0.32.0
yarl                        1.8.2
zipp                        3.11.0

in fact i use the invokeai (which doesn't start) Venv for Comfy ! .. not so many leaks ?

**Comment by lllyasviel** [comment]
given the list the environment you use is not Fooocus's official one
so this is to be closed

**Comment by AkoZ** [comment]
Yap , certainly due to start python in a global environment variables where they are multi-priorities.
OR i should have to re- indicate everytime the new path for each soft?
No matter Thank you to try and to have done this FoOocus !
