### ISSUE TITLE
Notebook: Which GPU is used?

### ISSUE THREAD

**Issue by blubbsy** [lllyasviel/Fooocus#546]
Hi,

is it  possible that i select the GPU somehow or can check if it is using the right one? Because in the Task Manager i see that the Geforce 3070 is not having a load, but the Intel XE is working heavily. The generation of an image (havent downgraded the drivers so far) takes accordingly a long time. 
With Stable Diffusion you can force the used GPU via CUDA_VISIBLE_DEVICES=1 in the command line. is there a similar option with fooocus?

BR
Sibby

**Comment by lllyasviel** [comment]
set CUDA_VISIBLE_DEVICES=X
    
    .\python_embeded\python.exe -s Fooocus\entry_with_update.py
    pause


does this work?

**Comment by blubbsy** [comment]
yes, this worked in combination to force again some specific versions of torch & co.

I don't know why it even installed non-compatible/wrong versions in it's virtual environment at all if i used the requirements.txt

**Comment by anmol500** [comment]
is there way to force it??

**Comment by kpagcha** [comment]
I tried with the setting `set CUDA_VISIBLE_DEVICES=X` but I am getting `RuntimeError: No CUDA GPUs are available`. How can I have it choose my Geforce GPU instead of the Intel one?

**Comment by Featurz** [comment]
Hi me too I have the same issue..

**Comment by Ni-Deshmane** [comment]
I am also having the same issue

**Comment by Ni-Deshmane** [comment]
This solution does not work

**Comment by Ni-Deshmane** [comment]
> ```
> set CUDA_VISIBLE_DEVICES=X
> 
> .\python_embeded\python.exe -s Fooocus\entry_with_update.py
> pause
> ```
> 
> does this work?

This does not work
