### ISSUE TITLE
how can i add more Aspect Ratios width × height ?

### ISSUE THREAD

**Issue by WalidAliAlfaid** [lllyasviel/Fooocus#556]
the last ratio i got is 1728×576 while i have seen people on youtube with 2048×512

**Comment by lllyasviel** [comment]
sdxl does not support 2048×512
it is possible to modify codes to force 2048×512 (that is probably what other people are doing)
but results are often worse than outpaint several times or upscale+crop

**Comment by MoonRide303** [comment]
@lllyasviel 2048x512 is on the list of the supported resolutions in the official [SDXL publication](https://arxiv.org/abs/2307.01952):
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/5c28d2a5-1893-47ef-9f55-8c0c13c47ab5)

But it's not consistent with the SAI code, though (https://github.com/Stability-AI/generative-models/issues/112) - so I guess it would be best to hear from SAI why those lists are different.
