### ISSUE TITLE
[Feature Request] Inpainting and Img2Img Options for better Workflow

### ISSUE THREAD

**Issue by Serasul1984** [lllyasviel/Fooocus#574]
[https://youtube.com/shorts/dhgcSBz7G4c?si=kbTyVEg3KItKNurq](url)  (old video)

Artbreeder has an collage option

you have an layer based canvas as inpainting
every layer can be an picture or an cutout from an picture

you can make every image or cutout transparent or even fill it with transparent color

you can make your own forms,color them and place them.

Rotating,trim,strech and so on is also possible.

When your collage is dont you can merge all of it and let Generate something new out of it like we do in Img2Img

Imagine we generate object first and than place them all together for the scene we want to generate !
The workflow would so much easier.
And than combine this with an inpainting brush that can change color,form,transparency and so on...

All that is needed at least would be an size changer of the Canvas only like in InvokeAI and this tool would made everyone happy.

**Comment by mashb1t** [comment]
AFAIK There are no plans to turn Fooocus into a full-fledged photo editing and composition suit.
You can already downlaod and drop in photos to transfer them to the corresponding fields.
Closing for now, but keeping the idea in mind.
