### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dipakurniyantoro** [lllyasviel/Fooocus#58]
Anyone can explain and have a solution for this..?
I have 16gb ram and 4gb vram rtx 3050ti laptop gpu
![error](https://github.com/lllyasviel/Fooocus/assets/125364211/a2d8ad45-effd-4884-8bf1-1fbdd0d5f4d0)

EDIT:
Problem solved!!!
I'm not sure what happened..

**Comment by kamalfarahani** [comment]
same error

**Comment by BertosHD** [comment]
Bump...
Same issue

**Comment by ConceptF1** [comment]
same error

**Comment by mashb1t** [comment]
Solution: update Fooocus.
