### ISSUE TITLE
ModuleNotFoundError: No module named 'comfy'

### ISSUE THREAD

**Issue by BNP1111** [lllyasviel/Fooocus#601]
D:\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Update failed.
unsupported URL protocol
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.25
Inference Engine exists but remote URL will be updated.
Git clone failed for Inference Engine: unsupported URL protocol
Traceback (most recent call last):
  File "D:\Fooocus\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "D:\Fooocus\Fooocus\launch.py", line 106, in <module>
    ini_comfy_args()
  File "D:\Fooocus\Fooocus\launch.py", line 97, in ini_comfy_args
    from comfy.cli_args import args as comfy_args
ModuleNotFoundError: No module named 'comfy'

**Comment by yyd106** [comment]
Same issue I'm encountered. I'm using Mac (M2 chip)

**Comment by lllyasviel** [comment]
follow official installation guidelines can solve this problem on Linux/Windows

Mac could be similar but I cannot reproduce this problem

**Comment by snowyu** [comment]
Found the reason the pygit can not clone the repo(auth required). the command `git` is ok.

comments this line: https://github.com/lllyasviel/Fooocus/blob/53573fa073b5ba670649c5d9066774b01b76b98a/launch.py#L31

And `git clone https://github.com/comfyanonymous/ComfyUI repositories/ComfyUI-from-StabilityAI-Official` manually.

**Comment by tkocou** [comment]
I have the same issue. I traced the problem to this comment in the console:
**Git clone failed for Inference Engine: authentication required but no callback set**
Is this a result of the mandatory 2FA for accounts?

**Comment by tkocou** [comment]
I have a Linux solution which works, though launch.py will need a slight modification.

**Comment by lllyasviel** [comment]
give full logs if you have similar problem

I tested 4 windows machine and 2 linux with official guidelines, all works without problems

**Comment by snowyu** [comment]
@lllyasviel 

First the pygit uses the `~/.gitconfig`, but not use the ssh private key config in `~/.ssh/` to auth. 

So add this into ~/.gitconfig to test.

```ini
[url "git@github.com:"]
        insteadOf = https://github.com/
```
 
Second, the pygit clone will try to empty and remove the `ComfyUI-from-StabilityAI-Official/.git` dir if `comfy_commit_hash` is not the same.

**Comment by BNP1111** [comment]
> Found the reason the pygit can not clone the repo(auth required). the command `git` is ok.
> 
> comments this line:
> 
> https://github.com/lllyasviel/Fooocus/blob/53573fa073b5ba670649c5d9066774b01b76b98a/launch.py#L31
> 
> And `git clone https://github.com/comfyanonymous/ComfyUI repositories/ComfyUI-from-StabilityAI-Official` manually.

Thanks for the explanation, your description is almost exactly what happened to me, I manually git clone https://github.com/comfyanonymous/ComfyUI repositories/ComfyUI-from-StabilityAI-Official , but once I start the run.bat, it removes the 》》ComfyUI-from-StabilityAI-Official 》》dir over and over again.

**Comment by BNP1111** [comment]
For what it's worth, about a week ago I was still able to use fooocus fine, although I would encounter problems such as "unsupported URL protocol" or "Git clone failed for Inference Engine: unsupported URL protocol", but I could still run fooocus.

**Comment by BNP1111** [comment]
> give full logs if you have similar problem
> 
> I tested 4 windows machine and 2 linux with official guidelines, all works without problems

你好，尽管我目前使用proxy（就是代理）, but I can access to github, huggingface and can git clone any repo（我可以访问github，huggingface或者git clone任何仓库没有障碍）。并且stable diffusion我也一直使用正常并且可以正常git pull。所以我一时间没有头绪如何解决。在你的fooocus一面世我就使用至今，几乎每次更新都没有错过，大概一周前我还是可以正常使用，这次似乎被comfy卡住了，我相信很多中国玩家也会遇到同类问题，可能我们的网络环境不同。如果这个问题需要花费你很多精力，那么我愿意继续等待一段时间，说不定就好了呢:-)

**Comment by lllyasviel** [comment]
I will hopefully take a look today

**Comment by snowyu** [comment]
```
[url "git@github.com:"]
        insteadOf = https://github.com/
```
> 
> It doesn't work for me.
> 

@BNP1111  It should reproduce the issue via this way which means use git-ssh instead of https. You shouldn't add this unless you need push to github.

**Comment by lllyasviel** [comment]
I pre-compiled all files. Now users can handle it in their own way if they have internet problems

feel free to reopen if necessary

**Comment by yyd106** [comment]
> > give full logs if you have similar problem
> > I tested 4 windows machine and 2 linux with official guidelines, all works without problems
> 
> 你好，尽管我目前使用proxy（就是代理）, but I can access to github, huggingface and can git clone any repo（我可以访问github，huggingface或者git clone任何仓库没有障碍）。并且stable diffusion我也一直使用正常并且可以正常git pull。所以我一时间没有头绪如何解决。在你的fooocus一面世我就使用至今，几乎每次更新都没有错过，大概一周前我还是可以正常使用，这次似乎被comfy卡住了，我相信很多中国玩家也会遇到同类问题，可能我们的网络环境不同。如果这个问题需要花费你很多精力，那么我愿意继续等待一段时间，说不定就好了呢:-)

@BNP1111 Is your question been resolved?

**Comment by lllyasviel** [comment]
reinstall and there wont be any comfy git things inside

**Comment by BNP1111** [comment]
I'll test right away，  should I re-download Fooocus_win64_2-1-25.7z?

**Comment by lllyasviel** [comment]
if you still have problems you can manually git pull to force update

**Comment by 841372** [comment]
I don’t have computer I need know what to do

**Comment by BNP1111** [comment]
> if you still have problems you can manually git pull to force update

now worked，灰常感谢，以后我只需要手动强制git pull     fooocus和comfy就行了是吧

**Comment by lllyasviel** [comment]
the clone of comfy can be deleted
