### ISSUE TITLE
about  ModuleNotFoundError  in  ubuntu

### ISSUE THREAD

**Issue by zhanghongyong123456** [lllyasviel/Fooocus#61]
import comfy.model_management
ModuleNotFoundError: No module named 'comfy'

**Comment by zhangyunming** [comment]
seem insue，Pip install comfy  not solve

**Comment by zhanghongyong123456** [comment]
> seem insue，Pip install comfy not solve

no,comfy   is     project  https://github.com/comfyanonymous/ComfyUI,not pip  package,so you  need  git  clone   this  version   
![image](https://github.com/lllyasviel/Fooocus/assets/48466610/387c4937-8b9e-46ef-96ea-03e542afcf69)

**Comment by lllyasviel** [comment]
yes you need to run launch.py to let it configuate the env

**Comment by zhanghongyong123456** [comment]
> yes you need to run launch.py to let it configuate the env

I think we need a way to manually download a specific version of this project, 
1. which version to download, 
2. what name to modify, 
3. where to put it, 
because sometimes there is a problem with automatic download, and maybe  can’t find it  ，like   [Automatic1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui) Extensions  install

**Comment by lllyasviel** [comment]
this part is copied from a1111 so they use same logic.
just run launch.py and it will process everything

**Comment by zhanghongyong123456** [comment]
> this part is copied from a1111 so they use same logic. just run launch.py and it will process everything

ok,thank you very much
