### ISSUE TITLE
Feature Request: Play a sound when done.

### ISSUE THREAD

**Issue by barepixels** [lllyasviel/Fooocus#62]
Often I set a batch of 20 then go surf the web instead of staring at the spinning wheel.  Would be nice to get a notice to go look at what got generated.

**Comment by Scn64** [comment]
Yes, I agree. Sometimes I'm trying several different styles with multiple images each. Instead of continuously checking the progress of one, it would be nice to hear a sound so I know to start the next one.

**Comment by TimothyAlexisVass** [comment]
@Scn64 Seems like what you're interested in actual headless/batch processing which has a pull request here: #471
When you're creating a script to use that, you could also set your own notification in that script.
