### ISSUE TITLE
wierd generating preview

### ISSUE THREAD

**Issue by abozahran** [lllyasviel/Fooocus#625]
When i click generate it takes some time and nothing show on preview window but in the cmd it say generating done and when i check outpot folder i can see the generated photo
when i press generate for the second time it take some time less than the first time as normal but i can see now the generated image is the first one showing in preview window not the scond image , when i check outpot folder i can see the second generated image which not showing yet in previw window unless i click generate for the third time , it keep going like that

**Comment by Phrixus2023** [comment]
I have the same problem with remote access to fooocus

**Comment by abozahran** [comment]
> I have the same problem with remote access to fooocus

I dont have this issue on my 3060 6gb laptop
but this happens to my upgraded pc

**Comment by Phrixus2023** [comment]
4090

**Comment by abozahran** [comment]
I found a solution just now
i closed kaspersky antivirus and the problem solved

**Comment by guoreex** [comment]
I have the same problem with remote

**Comment by mashb1t** [comment]
This issue has been fixed recently, another related PR is still open: https://github.com/lllyasviel/Fooocus/pull/981
