### ISSUE TITLE
colour difference when outpaint using V1 and V2, preview were good

### ISSUE THREAD

**Issue by frankyifei** [lllyasviel/Fooocus#647]
I have tried both v1 and v2.5, both give good result. Another issue I noticed is that in preview there is no colour difference but the final result has it. 
here is an example, there are clearly lines between each outpaint
![2023-10-12_01-03-31_8372](https://github.com/lllyasviel/Fooocus/assets/8104251/eda37e14-6778-4f6b-9e0f-199bf03e9f2b)
here is another example
original
![2023-10-12_12-41-54_9060](https://github.com/lllyasviel/Fooocus/assets/8104251/bcbf26a0-0aff-4420-a980-c48815d25c51)
V1
![2023-10-12_12-44-00_9691](https://github.com/lllyasviel/Fooocus/assets/8104251/cc1f7af5-7de4-4725-85ec-e9997290a2e0)
V2.5
![2023-10-12_12-45-36_2057](https://github.com/lllyasviel/Fooocus/assets/8104251/2d5481e5-a744-4883-a762-b8f7b7b7f386)
Preview 
![屏幕截图 2023-10-12 1245331](https://github.com/lllyasviel/Fooocus/assets/8104251/cb90a0c9-ff97-49d2-97ae-6ad7d225578b)
I did another test, this time I disabled all buildin styles and not using any lora. Outpaint v2.5
Original
![2023-10-12_13-06-06_7069](https://github.com/lllyasviel/Fooocus/assets/8104251/09dd977f-e43a-43bc-925c-9d7aa20693a7)
Preview
![新建 BMP 图像](https://github.com/lllyasviel/Fooocus/assets/8104251/33ba12b7-d75d-4c41-943e-064af489c1c0)
Result
![2023-10-12_13-07-45_5717](https://github.com/lllyasviel/Fooocus/assets/8104251/4df662d4-f4a4-437a-96a8-b897f4c2a882)

**Comment by barepixels** [comment]
Try the new beta v2.5  https://github.com/lllyasviel/Fooocus/discussions/615

**Comment by frankyifei** [comment]
> Try the new beta v2.5 #615
I updated the test result

**Comment by barepixels** [comment]
This one look good.  I would generate a batch of 10 or 20 and find one with a better seem at this location and photoshop it in
![good](https://github.com/lllyasviel/Fooocus/assets/92839033/35f1701b-2065-43e1-a464-04fe6ce29a52)

**Comment by frankyifei** [comment]
> This one look good. I would generate a batch of 10 or 20 and find one with a better seem at this location and photoshop it in
> 
> ![good](https://user-images.githubusercontent.com/92839033/274472224-35f1701b-2065-43e1-a464-04fe6ce29a52.png)
> 
> Question, have you compared it with other software that does outpainting? InvokeAI? Adobe FireFly?

How about the legs, there is clear a seal. And the sky background in second example. It is strange in the previews there were no colour difference in preview.
