### ISSUE TITLE
Ok, a couple of problems here, 

### ISSUE THREAD

**Issue by EKKIV0K** [lllyasviel/Fooocus#648]
First, hello :)

there is so many problems with this repo, i mean, why there is no bat to run the cloned repo ?

why i need to download the windows version and not git clone it ? 

Why the custom model path is so weird and when you add your sdlxl model folder located 
on a second hard drives Fooocus messed up and crash ? 

why when i add custom path in the files inside the fooocus folder, 
it try to download some models already existing on the custom path? 

Why this repo is so complicated and full of weird bugs like this ? 

i have python, anaconda, cuda installed, workinf fine with vladmandic and A1111.
NVIDIA driver 531.18 / GeForce RTX 4090......64Go RAM......

**Comment by tkocou** [comment]
Linux?

**Comment by barepixels** [comment]
why when i add custom path in the files inside the fooocus folder,
it try to download some models already existing on the custom path?

Because your path is wrongly written.  Fooocus can't find the required models so it auto download

**Comment by lllyasviel** [comment]
hello do you meet any problem in installation? 

It seems the issues are caused by using unrelated installation methods of unrelated software to install Fooocus.

**Comment by EKKIV0K** [comment]
@lllyasviel no i was just using your windows installation package, the original one and updated one on this repo.
i don't trust on others installation method, cause usually weird things can happens.

i does everything right during installation process :) 
i was forced to move all my sdxl models and loras into the fooocus path to get it worked.....
it was about 1To of data lol .... but now it works :) 

i have btw more questions about inpainting method who seems not working properly.
Like a i want to a man on a photo and it's not very working well, this happens to into stable diffusion with the "inpaint" 
Controlnet models, who result in a total mess, have you got some advises for this "issue" ?

Thanks for your help ! You're fantastic !

**Comment by lllyasviel** [comment]
maybe related
https://github.com/lllyasviel/Fooocus/discussions/679

**Comment by EKKIV0K** [comment]
@lllyasviel Just, Incredible. you blow my mind, you made a better job than all a team of dev of photoshop.
You're trully incredible...... My mind is blowed. 

i have one more question but this time on controlnet, inpaint, 
i cannot do what foocus do with the inpaing+lama or inpaint alone on a1111 is this normal ? 
each time i try for example to add a man or something else to an existing photo it fails.
it's like he try to do something but it cannot do new materials, he don't succeed to create it.
even with latent method it cannot do something great as generative fill or fooocus.

any ideas ?

**Comment by mashb1t** [comment]
Fooocus uses a unique inpainting engine, which is not available in other tools. Hope this helps.
