### ISSUE TITLE
After generation issues

### ISSUE THREAD

**Issue by Num83rGuy** [lllyasviel/Fooocus#650]
After generation most times the "stop" button will not change back to the "generate" button requiring a reload of the page which resets all settings. This is a huge inconvenience if you are trying to make variations of the same prompt or different prompts with the same style and settings.

Browser: Vivaldi | 6.2.3105.58 (Stable channel)
OS: Windows 11 Version 23H2 (Build 22635.2419)

**Comment by barepixels** [comment]
Fooocus-MRE has save STATE feature.  After every generation, it will save/update a single json file in the outputs folder for this occasion.  You can press load last prompt and restore.  It also save metadata in each PNG file so you can resume a project done months ago just by loading a generated image back then.

**Comment by Num83rGuy** [comment]
> Fooocus-MRE has save STATE feature. After every generation, it will save/update a single json file in the outputs folder for this occasion. You can press load last prompt and restore. It also save metadata in each PNG file so you can resume a project done months ago just by loading a generated image back then.

Thank you but, I do not use that fork.

**Comment by lllyasviel** [comment]
is there errors in console?

**Comment by Num83rGuy** [comment]
None that I have noticed. I can generate with any combination of settings and sometimes it will work one other times it will work many times then stop. Then other times I can have to reload the page a few times then it will start working correctly again.  I don't have to reset or close the terminal. No errors. It seems random. I have tried to disable all extensions in my browser as well, no change.

**Comment by Num83rGuy** [comment]
It has just happened again after working correctly for the past few hours.

![image](https://github.com/lllyasviel/Fooocus/assets/4624147/23fe5771-d311-49b0-9a32-5e4f1ca754a9)

**Comment by lllyasviel** [comment]
maybe related
https://github.com/lllyasviel/Fooocus/discussions/679

**Comment by mashb1t** [comment]
This issue hasn't occurred in recent time. Please check the latest version of Foocus and try again.
Feel free to reopen the issue if you still should have questions/feedback.
