### ISSUE TITLE
Refiner don't work on colab

### ISSUE THREAD

**Issue by thekingbalXD** [lllyasviel/Fooocus#652]

**Comment by barepixels** [comment]
The head of Google Colab, Chris Perry, took to social media to clarify that Google has not banned Stable Diffusion. Instead, he said, they are restricting the use of Gradio—a remote front-end web user interface (UI) for Stable Diffusion popularized by Automatic 1111 and other forks like SD.next—for free users.

The Gradio interface, widely utilized in generative UI models, has seen a surge in usage, straining Google's resources, Perry said.

https://decrypt.co/197428/google-colab-stable-diffusion-web-ui-ban
