### ISSUE TITLE
Image prompt does not work in Gooble Colab's (free) service

### ISSUE THREAD

**Issue by mp3pintyo** [lllyasviel/Fooocus#654]
First of all, I would like to thank you on behalf of everyone for the amazing work you have done to create Fooocus. You are the best!

Unfortunately, the new image prompt part does not work in Gooble Colab's (free) service.
It says Image processing for a while and then it says a red Error on the screen.
In the resources of Google Colab, you can see that the system memory (not the GPU) reaches the maximum. This is probably the cause of the error.

**Comment by greatwolf** [comment]
I'm running into the same issue on colab where during generation it would get a connection timeout error. The console in other tab shows `^C`. Now I don't think it's google colab shutting it down since the environment runtime doesn't show it being disconnect and deleted.

**Comment by barepixels** [comment]
Free colab limited system memory and image prompt feature requires more?  I faced similar problem when tried using free colab to make loras.  Hopefully, I will get a used 3090 by next week.

**Comment by greatwolf** [comment]
It seems like recent changes is what spikes up system memory usage. google colab has ~12-13gb of ram. Checking the resource before the crash shows system memory usage spike past 12gb for me.

As an interim workaround, I just ran Fooocus at an earlier point of commit. For example, `git reset --hard c275434c596ba81600bdd3c03e6d9de6bf060c06`, that's less likely to crash from my testing.

**Comment by lllyasviel** [comment]
This branch uses less memory
https://github.com/lllyasviel/Fooocus/tree/archived_colab

However we are still looking at methods to use it in a better way

**Comment by mashb1t** [comment]
Most likely your RAM is exhausted, which is why your process is cancelled. Please check and upgrade it or your plan.

See https://github.com/lllyasviel/Fooocus/issues/1330, https://github.com/lllyasviel/Fooocus/issues/1574, https://github.com/lllyasviel/Fooocus/issues/1558#issuecomment-1868166226
