### ISSUE TITLE
局域网内多个用户打开无法同时独立运行

### ISSUE THREAD

**Issue by xixiaobaiyang** [lllyasviel/Fooocus#655]
就是一个人生成图像时，会把局域网内其他用户创建的生成任务依次执行一遍。可否同一个端口，多台机器打开时，都独立运行，互不影响。

**Comment by yunkchen** [comment]
可以做成前后端分离的，多个前端（无需GPU），一个后端（GPU机器）

**Comment by mashb1t** [comment]
also see https://github.com/lllyasviel/Fooocus/pull/981
