### ISSUE TITLE
Fooocus failed to run

### ISSUE THREAD

**Issue by amorlee** [lllyasviel/Fooocus#666]
Opening run.bat as administrator prompts "C:\Windows\System32>. \python_embedded\python.exe -s Fooocus\entry_with_update.py
The system cannot find the specified path." 
My computer has python 3.10 installed.
Please tell me how to solve this situation?

**Comment by barepixels** [comment]
my run.bt look like this

.\python_embeded\python.exe -s Fooocus\entry_with_update.py
pause

![embed](https://github.com/lllyasviel/Fooocus/assets/92839033/683fb0d4-eacb-4de3-b4d8-258d5f414e7c)


Im guessing you used Stability Matrix to install

**Comment by lllyasviel** [comment]
do not  "run as administrator"
