### ISSUE TITLE
求助：使用高级功能【image Prompt】下的【image Prompt】功能出现错误。

### ISSUE THREAD

**Issue by lucknini** [lllyasviel/Fooocus#680]
使用高级功能【image Prompt】出现错误
错误如下：
Traceback (most recent call last):
  File "E:\Fooocus_win64\Fooocus\modules\async_worker.py", line 576, in worker
    handler(task)
  File "E:\Fooocus_win64\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Fooocus_win64\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Fooocus_win64\Fooocus\modules\async_worker.py", line 196, in handler
    ip_adapter.load_ip_adapter(clip_vision_path, ip_negative_path, ip_adapter_path)
  File "E:\Fooocus_win64\Fooocus\fooocus_extras\ip_adapter.py", line 105, in load_ip_adapter
    clip_vision = fcbh.clip_vision.load(clip_vision_path)
  File "E:\Fooocus_win64\Fooocus\backend\headless\fcbh\clip_vision.py", line 110, in load
    sd = load_torch_file(ckpt_path)
  File "E:\Fooocus_win64\Fooocus\backend\headless\fcbh\utils.py", line 13, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "E:\Fooocus_win64\python_embeded\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
Total time: 0.25 seconds
重新安装独立新版本也出现一样的错误，救助这个要怎么解决？；另外2个【PyraCanny】和【CPDS】使用正常。
我的硬件是：inter 12650H  4060  8g  40g 内存  软件环境：win11
<img width="845" alt="Snipaste_2023-10-14_10-45-53" src="https://github.com/lllyasviel/Fooocus/assets/126230010/f869a16f-894c-498a-97fe-6ce5e1400549">

**Comment by lllyasviel** [comment]
`Readme` said that MetaDataIncomplete is corrupted files. delete corrupted controlnet models and download again

**Comment by lucknini** [comment]
> `Readme`说元数据不完整是损坏的文件。删除损坏的 ControlNet 模型并重新下载

感谢大神，但是已经重新下载了ControlNet 模型，不管是自动更新还是在抱脸网上下载的，都显示同样的错误，愁！

**Comment by lucknini** [comment]
<img width="844" alt="Snipaste_2023-10-14_13-32-25" src="https://github.com/lllyasviel/Fooocus/assets/126230010/01d99b69-9da6-476a-b0f7-e54281d00797">

**Comment by hylarucoder** [comment]
可能不是ipadapter那个文件, 可能是另外一个相关的模型. 建议检查一下其他模型的大小是否异常. 

> > `Readme`说元数据不完整是损坏的文件。删除损坏的 ControlNet 模型并重新下载
> 
> 感谢大神，但是已经重新下载了ControlNet 模型，不管是自动更新还是在抱脸网上下载的，都显示同样的错误，愁！

**Comment by hylarucoder** [comment]
可能不是ipadapter那个文件, 可能是另外一个相关的模型. 建议检查一下其他模型的大小是否异常. 

> > `Readme`说元数据不完整是损坏的文件。删除损坏的 ControlNet 模型并重新下载
> 
> 感谢大神，但是已经重新下载了ControlNet 模型，不管是自动更新还是在抱脸网上下载的，都显示同样的错误，愁！

**Comment by lucknini** [comment]
> 可能不是ipadapter那个文件， 可能是另外一个相关的模型.建议检查一下其他模型的大小是否异常.
> 
这2天测试了的情况：重新装了新硬盘，在新系统下，重装环境，重装fooocus，一样的报错！
请了fooocus-MRE的ak大神帮忙解决，忙了一晚上，对比了模型的哈希值，模型没问题，ak大神压缩了一版他现在用的没问题的fooocus，我下载解压，结果还是一模一样的报错！我奔溃了。
这几天，张大神疯狂升级，应该非常忙，等有空再看吧，我就一个image Prompt用不了，其他测试都能使用。

**Comment by hylarucoder** [comment]
@lucknini em.....我的image prompt是可以的。 我建议，你修改一下加载模型的那边的代码，把变量print出来可能会容易解决一些。

**Comment by lucknini** [comment]
> 嗯.....我的图像提示是可以的。我建议，你修改一下加载模型的那边的代码，把变量print出来可能会容易解决一些。

感谢！
能具体说下怎么做吗？我不会代码。
救助大语言模型也说可能是路径上出问题了，但没给具体操作。摊手！

**Comment by hylarucoder** [comment]
找到截图259行， 增加print(filename)

**Comment by lucknini** [comment]
> 找到截图259行， 增加print(filename)

是不是这样添加？
![Snipaste_2023-10-16_00-28-53](https://github.com/lllyasviel/Fooocus/assets/126230010/92f99612-47ad-4245-8f04-72122be097dc)

**Comment by lucknini** [comment]
运行后
![Snipaste_2023-10-16_00-28-12](https://github.com/lllyasviel/Fooocus/assets/126230010/a5c031f9-6c79-42bd-9516-10f5d2682628)

**Comment by lllyasviel** [comment]
Readme said that MetaDataIncomplete is corrupted files. delete corrupted controlnet models and download again

if not working then delete all files in the models/controlnet

**Comment by lllyasviel** [comment]
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/16ccce8d-f309-477e-a2db-8bfdc6c64646)

I added a file checking system in 2.1.677
it will automatically delete correupted files so that it will be downloaded again in the next run

**Comment by lucknini** [comment]
> ![图像](https://user-images.githubusercontent.com/19834515/275365936-16ccce8d-f309-477e-a2db-8bfdc6c64646.png)
> 
> 我在 2.1.677 中添加了一个文件检查系统，它会自动删除相应的文件，以便在下次运行时再次下载

感谢感谢！
另外再次感谢敏神做的这么好的工具，我都已经忘记了web ui！
再次感谢！

**Comment by lucknini** [comment]
感谢，测试下来，已经跑成功了。
开心！
![Snipaste_2023-10-16_09-59-14](https://github.com/lllyasviel/Fooocus/assets/126230010/d11b1efc-b131-4115-ad9c-a4c900e96833)
