### ISSUE TITLE
Image upscale generated abnormal result

### ISSUE THREAD

**Issue by lanyusan** [lllyasviel/Fooocus#681]
I use 1.5x.

The original image:
![e961545ea53e98aa372e79d63300](https://github.com/lllyasviel/Fooocus/assets/56706512/258fb0e3-52ba-4a83-9cbd-315c56861f38)

Generated:
![image](https://github.com/lllyasviel/Fooocus/assets/56706512/7ccd9339-687a-40bd-be64-f2d3a76ea49e)

**Comment by mashb1t** [comment]
You may also do upscaling with 2x (fast) as the other upscalers ado once more reiterate the SD process (like hires fix).
