### ISSUE TITLE
Feature request: models in subdirectories

### ISSUE THREAD

**Issue by micral911** [lllyasviel/Fooocus#686]
Hi, please add support for including subdirectories when loading models list. Many of us have a lot of models/loras organized into subdirs and it would help looking for models in the dropdown a lot easier! Thank you for the amazing work!

**Comment by cjj1977** [comment]
+1 to this. It would be good to have the models/loras/etc. filtered for those compatible with SDXL, which might be a feature request in its own right.

**Comment by MoonRide303** [comment]
Added in v2.1.698 (https://github.com/lllyasviel/Fooocus/pull/725).
