### ISSUE TITLE
Can Inpaint and Image Prompt be combined?

### ISSUE THREAD

**Issue by hben35096** [lllyasviel/Fooocus#687]
I tried, in Image Prompt, upload a rabbit image, which can generate another rabbit. If I want to add a rabbit like the image prompt to the mask area, how do I do that?
If the two are combined, can it be achieved such as:
https://huggingface.co/spaces/Fantasy-Studio/Paint-by-Example
![image](https://github.com/lllyasviel/Fooocus/assets/139383150/d70d3660-2c82-4c99-890a-194c88870e34)

**Comment by hben35096** [comment]
![image](https://github.com/lllyasviel/Fooocus/assets/139383150/4fda6ee0-1299-400e-ab1a-d146c4944c6b)

**Comment by lllyasviel** [comment]
in developer tools -> Debug Control -> Mixing Image Prompt and Inpaint

**Comment by hben35096** [comment]
Thank you~

**Comment by koufounak** [comment]
@hben35096  Can you explain this circuit/algorithm please? How did you do that in comfyUI and in Fooocus?
