### ISSUE TITLE
Auto Launch, output directory and preset loras

### ISSUE THREAD

**Issue by thomasbidou** [lllyasviel/Fooocus#688]
Hi,

I can't make --disable-auto-launch and --output-directory work.
I add these options to the run.bat file, but the web UI still launches and the output directory is still the basic one.

Here is the run.bet file:
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --output-directory Y:\AI\Outpouts\Fooocus --disable-auto-launch
pause

Also, I would like to add multiple Loras to a preset. Is it possible?

Regards,

**Comment by mashb1t** [comment]
Please test again in the latest version of Fooocus.

> Also, I would like to add multiple Loras to a preset. Is it possible?

Yes, this is possible now.

Feel free to reopen this issue on further feedback.
