### ISSUE TITLE
mps not supported now on 2.1.66

### ISSUE THREAD

**Issue by vicento** [lllyasviel/Fooocus#690]
`Device mps:0 does not support the torch.fft functions used in the FreeU node, switching to CPU.
`
How can i get full MPS support on my silicon mac ?

**Comment by lllyasviel** [comment]
is that showing if you do not use FreeU or you always see this?

**Comment by vicento** [comment]
if i use freeU i get this :
`Device mps:0 does not support the torch.fft functions used in the FreeU node, switching to CPU.`

**Comment by vicento** [comment]
have updated some things, now i'm on 2.1.675 and the previous error doesn't show (Device mps:0 does not support the torch.fft functions used in the FreeU node, switching to CPU. )

**Comment by guoreex** [comment]
macos 14.0
macbookpro m1, 16g ram

[Fooocus Model Management] Moving model(s) has taken 61.51 seconds
[Sampler] Fooocus sampler is activated.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
  0%|                                                    | 0/30 [00:00<?, ?it/s]/Volumes/1TSSD/AI-project/fooocus/Fooocus/modules/anisotropic.py:132: UserWarning: The operator 'aten::std_mean.correction' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.)
  s, m = torch.std_mean(g, dim=(1, 2, 3), keepdim=True)
  3%|█▍                                         | 1/30 [01:40<48:41, 100.73s/it]

**Comment by Gitterman69** [comment]
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 7.0
[Parameters] Seed = 4730616638981956459
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 20
[Fooocus] Initializing ...
[Fooocus] Loading models ...
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] New suffix: intricate, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, unreal engine 5, 8 k, art by artgerm and greg rutkowski and alphonse mucha
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] New suffix: extremely detailed, artstation, 8 k, sensual lighting, incredible art, wlop, artgerm
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
Preparation time: 3.79 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.02916753850877285, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 60.01 seconds
[Sampler] Fooocus sampler is activated.
  0%|                                                    | 0/30 [00:00<?, ?it/s]/Applications/Fooocus/modules/anisotropic.py:132: UserWarning: The operator 'aten::std_mean.correction' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.)
  s, m = torch.std_mean(g, dim=(1, 2, 3), keepdim=True)
  7%|██▋                                      | 2/30 [04:50<1:07:49, 145.34s/it]
User stopped
Total time: 355.80 seconds

**Comment by Gitterman69** [comment]
> if i use freeU i get this : `Device mps:0 does not support the torch.fft functions used in the FreeU node, switching to CPU.` without freeU doesn't see mps error i am on 2.1.675 now

same here :( i want to use fooocus on my macbook m1 so bad :)

**Comment by Gitterman69** [comment]
yes - this is so sad :( @lllyasviel heeeeeeeeeelp

**Comment by Gitterman69** [comment]
bump

**Comment by tiancool** [comment]
Pay attention to the same problem

**Comment by Gitterman69** [comment]
bump

**Comment by none2serious** [comment]
same.

**Comment by waterydan** [comment]
Same here

**Comment by Tygrha** [comment]
bump

**Comment by Tygrha** [comment]
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1152, 896)
Preparation time: 20.42 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 113.59 seconds
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
  0%|                                                                                                      | 0/30 [00:00<?, ?it/s]/Users/ty/Desktop/Fooocus-main/modules/anisotropic.py:132: UserWarning: The operator 'aten::std_mean.correction' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.)
  s, m = torch.std_mean(g, dim=(1, 2, 3), keepdim=True)
  7%|██████                                                                                     | 2/30 [06:31<1:30:11, 193.25s/it]

**Comment by ambraxia** [comment]
```
The operator 'aten::std_mean.correction' is not currently supported on the MPS backend and will fall back to run on the CPU
```
The same error

```
193.25s/it
```
The same speed

Bump

**Comment by Tygrha** [comment]
If my understanding is correct, it looks like a compatibility issue with pytorch and apple silicon. 

Does anyone know if there is a way to adjust the parameters in Fooocus to avoid using the 'aten:std_mean.coorection', but rather some other calculation that would be supported?

**Comment by dch09** [comment]
Bump, I'd love to get an update on that.

**Comment by emilmammadov** [comment]
any update?

**Comment by muratdemirkiran33** [comment]
any update?

**Comment by gregplumbly** [comment]
UserWarning: The operator 'aten::std_mean.correction' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1701416305940/work/aten/src/ATen/mps/MPSFallback.mm:13.)
  s, m = torch.std_mean(g, dim=(1, 2, 3), keepdim=True)

**Comment by BoomerCorp** [comment]
Same on Intel iMac 2020 with AMD Graphics?

**Comment by winnduu** [comment]
Macbook M3 Pro suffers from the same problem - So i guess the whole lineup of Apples Silicon CPU's is affected

**Comment by amediantsev** [comment]
Same on MacBook Pro Apple M2 Pro, macOS Sonoma Version 14.1.
```
UserWarning: The operator 'aten::std_mean.correction' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.)
```

**Comment by bhardwajshash** [comment]
Same issue! Bump

**Comment by semyonf** [comment]
Same

**Comment by oscody** [comment]
same

**Comment by Dkray** [comment]
same
M2 Pro, Fooocus version: 2.1.854

**Comment by Gitterman69** [comment]
bump for visibility!

**Comment by Dkray** [comment]
The most interesting thing is that PyTorch works correctly. The test script from the Apple site produces the correct result: tensor([1.], device='mps:0')

**Comment by GuiFV** [comment]
up

**Comment by SimcoeHops** [comment]
Experiencing the same "Device mps:0 does not support the torch.fft functions used in the FreeU node, switching to CPU" even though a test script output indicates Metal is installed with GPU support (tensor([1.], device='mps:0'). I'm running ComfyUI on an M2 MBP 96gb etc.

**Comment by igm503** [comment]
Unfortunately, implementing fft on the mps backend is pretty difficult.

I don't think anyone has taken it up because of a lack of support from Apple. I could be wrong about this, but my understanding is that cuda has fft built in or available via a library, whereas the fourier transform functionality the relevant Apple libraries has for the m-family gpus is relatively limited as of now, so an implementation of this in pytorch might require implementing a full or near-full custom fft algorithm. I don't see why I couldn't be done, but it'll take a hero.

**Comment by dfl** [comment]
@igm503 I wonder if [VkFFT](https://github.com/DTolm/VkFFT) would fit the bill?

**Comment by schuster-rainer** [comment]
on the latest version of fooocus performance improved a lot. I'm running with:

`PYTORCH_ENABLE_MPS_FALLBACK=1 python webui.py --disable-offload-from-vram`

as I have a M1 with 64GB. my iterations with LCM are ~1.25 per second for a 768x11344 image. Non LCM renders take roughly double the time.

**Comment by Dkray** [comment]
> on the latest version of fooocus performance improved a lot. I'm running with:
> 
> `PYTORCH_ENABLE_MPS_FALLBACK=1 python webui.py --disable-offload-from-vram`
> 
> as I have a M1 with 64GB. my iterations with LCM are ~1.25 per second for a 768x11344 image. Non LCM renders take roughly double the time.

my result is -  UserWarning: The operator 'aten::std_mean.correction' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.)
  s, m = torch.std_mean(g, dim=(1, 2, 3), keepdim=True)
  3%|█▎                                       | 1/30 [03:40<1:46:36, 220.57s

**Comment by schuster-rainer** [comment]
> > on the latest version of fooocus performance improved a lot. I'm running with:
> > `PYTORCH_ENABLE_MPS_FALLBACK=1 python webui.py --disable-offload-from-vram`
> > as I have a M1 with 64GB. my iterations with LCM are ~1.25 per second for a 768x11344 image. Non LCM renders take roughly double the time.
> 
> my result is - UserWarning: The operator 'aten::std_mean.correction' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.) s, m = torch.std_mean(g, dim=(1, 2, 3), keepdim=True) 3%|█▎ | 1/30 [03:40<1:46:36, 220.57s

that's correct. Hence the fallback variable. I'm running a M1 Max on Sonoma (MacOS 14). If you have an older OS / slower cpu it might take longer

**Comment by Dkray** [comment]
> I'm running a M1 Max on Sonoma (MacOS 14)

M2 Pro on Sonoma )

**Comment by Tiago-Zarzavidjian** [comment]
> > on the latest version of fooocus performance improved a lot. I'm running with:
> > `PYTORCH_ENABLE_MPS_FALLBACK=1 python webui.py --disable-offload-from-vram`
> > as I have a M1 with 64GB. my iterations with LCM are ~1.25 per second for a 768x11344 image. Non LCM renders take roughly double the time.
> 
> my result is - UserWarning: The operator 'aten::std_mean.correction' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.) s, m = torch.std_mean(g, dim=(1, 2, 3), keepdim=True) 3%|█▎ | 1/30 [03:40<1:46:36, 220.57s

I'm getting this exact error on my M3 Pro on Sonoma 14.2.1

**Comment by igm503** [comment]
Would need to look into it, but adding aten::std_mean to the MPS backend doesn't seem too difficult, if it isn't already there in a nightly.

**Comment by vicento** [comment]
I'd be happy to see someone do it. _It's not difficult for those who know how_

**Comment by hike2008** [comment]
up

**Comment by legz** [comment]
Same here on Mac mini M2 / Sonoma 14.2.1

**Comment by igm503** [comment]
FYI, the warning about cpu fallback for aten::std_mean isn't an error--if that's all you're seeing, then the program is running fine, just slower than it would be if that op was implemented for the PyTorch MPS backend.

I'm going to check it out tomorrow and see if I have time to add support for it/if it's already supported in a nightly.

Also FYI, if y'all are still encountering problems with torch.fft support on the MPS device, there's a pull request in the pytorch repo right now that will add more support for fft functions on the macbooks, so the next pytorch nightly releases might be worth trying.

**Comment by igm503** [comment]
aten::std_mean is indeed in the latest nightly version of pytorch. Not sure when it'll make it into a release version.

**Comment by legz** [comment]
> FYI, the warning about cpu fallback for aten::std_mean isn't an error--if that's all you're seeing, then the program is running fine, just slower than it would be if that op was implemented for the PyTorch MPS backend.

You're absolutely right, but 30+ minutes per image on an M2/16GB is not really usable.
Thanks for the additional info about nightly version of pytorch!

**Comment by whz739723619** [comment]
same

**Comment by mashb1t** [comment]
@Gitterman69 in general the MPS backend is supported (beta), but not all functions are optimized. Please find the instructions on how to install Fooocus for MacOS / MPS backend in https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#mac and discuss problems in https://github.com/lllyasviel/Fooocus/pull/129

**Comment by medienbueroleipzig** [comment]
Der Operator with bis dato nicht von Apple unterstützt, dass ist alles. Da knann man noch so viel rumschrauben (wollen) wie man will.
--disable-offload-from-vram verkürzt nur das Laden des models, aber hat keine Auswirkungen auf die fehlende Unterstützung für den pytorch-operator aten::std_mean.correction.
 Liest du mehr hier :[http://medienbüro-leipzig.de/index.php?action=faq&cat=9&id=23&artlang=de](http://medienbüro-leipzig.de/index.php?action=faq&cat=9&id=23&artlang=de)

**Comment by medienbueroleipzig** [comment]
http://medienbüro-leipzig.de/index.php?action=faq&cat=9&id=23&artlang=de
