### ISSUE TITLE
[Feature Request] Save Option for Positive+Negative Promt,Settings,Style,Model and Advanced options.

### ISSUE THREAD

**Issue by Serasul1984** [lllyasviel/Fooocus#692]
Every time the program crash or we close it all our Fine-tuned Settings are gone.
Pls let us save everything so we can simple load the save,when we want to work at the same thing again.

**Comment by kubilaykilinc** [comment]
Fooocus achieved perfection. It will be more perfect if it has this feature. Also, sub folder support is required for models.

**Comment by Aenon1** [comment]
Look in X:\your\path\to\Fooocus\Fooocus\presets
There are 3 .json files in there that can be edited(with a text editor) to retain some custom settings. You can set the model, lora, default positive/negative prompt, sampler, styles, and more. The only problem is that everytime Fooocus contacts github, it will reset these back to the defaults. I created a folder in there where I keep my edited files and just copy/paste them back every time this happens. What I do is close Fooocus, copy the files back and restart it. It is then good for that session.

**Comment by stubkan** [comment]
This has been a request for awhile, and I think this program does badly need some kind of setting saving - I tend to lose my prompts and settings multiple times through inadvertent tab restarts.

https://github.com/lllyasviel/Fooocus/issues/445
https://github.com/lllyasviel/Fooocus/issues/334
https://github.com/lllyasviel/Fooocus/issues/150

**Comment by Aenon1** [comment]
Is there any way to stop Fooocus from reseting the presets every time it checks for an update? What is the point in being able to save your settings if Fooocus is just going to change them back to default?

**Comment by mashb1t** [comment]
It is intended that the settings are reset every time to the preset as this allows users to experiment with settings and if they misconfigured anything or are not satisfied with the result they can easily jump back to the preset values by reloading the page.

What you can do is to import the settings of the last generated image back into Fooocus using the history log. This does not include settings in Developer Debug Mode.
Hope this helps.

Other related issues/enhancements:
https://github.com/lllyasviel/Fooocus/issues/1692
https://github.com/lllyasviel/Fooocus/issues/1622
https://github.com/lllyasviel/Fooocus/issues/1456
https://github.com/lllyasviel/Fooocus/issues/676

Closing as duplicate.
