### ISSUE TITLE
The colab version not working after the updates

### ISSUE THREAD

**Issue by Bullseye110** [lllyasviel/Fooocus#695]
Hello!
I always have to use "!git checkout c275434" for Fooocus on google colab, because the newest updates just do not work (you can't even open the gradio link, because you'll get a "^C" error).
Will it be possible to fix it. so it can run like before without problems and even with refiner on?
Thanks!

**Comment by barepixels** [comment]
maybe this

The head of Google Colab, Chris Perry, took to social media to clarify that Google has not banned Stable Diffusion. Instead, he said, they are restricting the use of Gradio—a remote front-end web user interface (UI) for Stable Diffusion popularized by Automatic 1111 and other forks like SD.next—FOR FREE USERS.

The Gradio interface, widely utilized in generative UI models, has seen a surge in usage, straining Google's resources, Perry said.

.....

"Stable Diffusion webUI usage got super big—we can't support the usage growth on our team's budget." Perry noted in a tweet. This statement was echoed by the CEO of Stability AI, who [expressed support](https://x.com/EMostaque/status/1649191202950897666?s=20) for Google's decision, emphasizing the need to manage resources effectively.

Despite these restrictions, users have several alternatives at their disposal. They can subscribe to Google Colab's paid tier, opt for free Stable Diffusion interfaces like [Mage.Space](https://www.mage.space/), [Sea Art](https://www.seaart.ai/home) or [Leonardo.Ai](https://app.leonardo.ai/auth/login), rent a cloud instance with a powerful GPU on platforms like [Vast.AI](https://vast.ai/) or [Runpod](https://www.runpod.io/), or try the decentralized GPU service [Stable Hord](https://stablehorde.net/).

They can also run Stable Diffusion at home, using [local solutions](https://decrypt.co/resources/decrypts-guide-to-stable-diffusion-the-most-powerful-open-source-tool-for-ai-image-generation) if they have a GPU with a minimum of 4Gb of VRAM, or [specialized apps](https://decrypt.co/154766/apple-mac-silicon-ai-stable-diffusion-install-run-images) for Macs. These options ensure that users can continue their projects without significant disruptions.

https://decrypt.co/197428/google-colab-stable-diffusion-web-ui-ban

**Comment by Bullseye110** [comment]
> maybe this
> 
> The head of Google Colab, Chris Perry, took to social media to clarify that Google has not banned Stable Diffusion. Instead, he said, they are restricting the use of Gradio—a remote front-end web user interface (UI) for Stable Diffusion popularized by Automatic 1111 and other forks like SD.next—FOR FREE USERS.
> 
> The Gradio interface, widely utilized in generative UI models, has seen a surge in usage, straining Google's resources, Perry said.
> 
> .....
> 
> "Stable Diffusion webUI usage got super big—we can't support the usage growth on our team's budget." Perry noted in a tweet. This statement was echoed by the CEO of Stability AI, who [expressed support](https://x.com/EMostaque/status/1649191202950897666?s=20) for Google's decision, emphasizing the need to manage resources effectively.
> 
> Despite these restrictions, users have several alternatives at their disposal. They can subscribe to Google Colab's paid tier, opt for free Stable Diffusion interfaces like [Mage.Space](https://www.mage.space/), [Sea Art](https://www.seaart.ai/home) or [Leonardo.Ai](https://app.leonardo.ai/auth/login), rent a cloud instance with a powerful GPU on platforms like [Vast.AI](https://vast.ai/) or [Runpod](https://www.runpod.io/), or try the decentralized GPU service [Stable Hord](https://stablehorde.net/).
> 
> They can also run Stable Diffusion at home, using [local solutions](https://decrypt.co/resources/decrypts-guide-to-stable-diffusion-the-most-powerful-open-source-tool-for-ai-image-generation) if they have a GPU with a minimum of 4Gb of VRAM, or [specialized apps](https://decrypt.co/154766/apple-mac-silicon-ai-stable-diffusion-install-run-images) for Macs. These options ensure that users can continue their projects without significant disruptions.
> 
> https://decrypt.co/197428/google-colab-stable-diffusion-web-ui-ban

Man, I don't get disconnected or anything, but the interface can't load, because the newest updates somehow consume all the RAM available.
I can use Fooocus only with the version c275434 or above of the repo.

**Comment by lllyasviel** [comment]
i just tried colab and it worked well seemly.

**Comment by Bullseye110** [comment]
> i just tried colab and it worked well seemly.

With the latest commit of your repo? It's no way. Maybe you write additional lines in colab, but with the actual posted google colab notebook and with the latest commit it won't work.

**Comment by Bullseye110** [comment]
> i just tried colab and it worked well seemly.

Maybe it worked for you, because you didn't use a custom model.

**Comment by Bullseye110** [comment]
> i just tried colab and it worked well seemly.

I think I figured out what the problem is. The colab only works with one sdxl 1.0 model, If you swap the models (select another 1.0 model) in the webui, it will crash, because there's not enough memory for that RAM switch.
But in the commit c275434 and above, this issue is not existent.
Is there any way to make Fooocus to stop automatically download the base SDXL 1.0 model?

**Comment by greatwolf** [comment]
I was running into same memory issue on colab. After some more detailed investigation here's what I've found:

 - e44e1e5b672c0389743323a04a82dacca9f82cb9 is the last commit where this works without issue.
 - this code change is likely the cause of the issue: https://github.com/lllyasviel/Fooocus/commit/1601af43bebf2e252ea6f590c85c95f42665494b#diff-b935b7abd3fda301cecfc48e9eac342a969154afd1768ab31dce7e2f7c1c2126R473
 - a possible workaround to sidestep the memory issue is to have Fooocus not load the sdxl base and refiner models since that's what's causing the memory usage spike during model loading.

I found changing the model settings from gradio ui after the fact doesn't help here -- Fooocus will still try to load those two base and refiner models regardless. I wonder if it's a bug, if not definitely an area for improvement. For example, if you're using a different sdxl model checkpoint, Fooocus should not pointlessly wasting time loading the default base and refiner sdxl only just to unload them later.

Lastly, you can make Fooocus load different sdxl model by setting up `colab_fix.txt`/`user_path_config.txt`. For example, I wanted to use [RealVisXL-V2](https://civitai.com/models/139562/realvisxl-v20) instead of the default base/refiner.

modify `colab_fix.txt` with following:

    {
      "default_model": "realvisxlV20_v20Bakedvae.safetensors",
      "default_refiner": "",
      "default_lora":  ""
    }

Modify `default_model` field as appropriate if using different sdxl model checkpoint.

And have colab copy it over to `user_path_config.txt` before launching gradio:

    !cp colab_fix.txt user_path_config.txt

This will completely avoid loading default sdxl base and refiner models and therefore no more out of memory/timeout issues. It works with latest commit and I found it even loads faster now this way.

See my colab https://colab.research.google.com/drive/1G3KsEbeLawi5-vSro6rHztG70C_eEsWx?usp=sharing for working example.

**Comment by Bullseye110** [comment]
> I was running into same memory issue on colab. After some more detailed investigation here's what I've found:
> 
>     * [e44e1e5](https://github.com/lllyasviel/Fooocus/commit/e44e1e5b672c0389743323a04a82dacca9f82cb9) is the last commit where this works without issue.
> 
>     * this code change is likely the cause of the issue: [1601af4#diff-b935b7abd3fda301cecfc48e9eac342a969154afd1768ab31dce7e2f7c1c2126R473](https://github.com/lllyasviel/Fooocus/commit/1601af43bebf2e252ea6f590c85c95f42665494b#diff-b935b7abd3fda301cecfc48e9eac342a969154afd1768ab31dce7e2f7c1c2126R473)
> 
>     * a possible workaround to sidestep the memory issue is to have Fooocus not load the sdxl base and refiner models since that's what's causing the memory usage spike during model loading.
> 
> 
> I found changing the model settings from gradio ui after the fact doesn't help here -- Fooocus will still try to load those two base and refiner models regardless. I wonder if it's a bug, if not definitely an area for improvement. For example, if you're using a different sdxl model checkpoint, Fooocus should not pointlessly waste time trying to load the default base and refiner only just to unload them later.
> 
> Lastly, you can make Fooocus load different sdxl model by setting up `colab_fix.txt`/`user_path_config.txt`. For example, I wanted to use [RealVisXL-V2](https://civitai.com/models/139562/realvisxl-v20) instead of the default base/refiner.
> 
> Modify `colab_fix.txt` as follows:
> 
> ```
> {
>   "default_model": "realvisxlV20_v20Bakedvae.safetensors",
>   "default_refiner": "",
>   "default_lora":  ""
> }
> ```
> 
> (Edit `default_model` field as appropriate if using different sdxl model checkpoint.)
> 
> And have colab copy it over to `user_path_config.txt` before launching gradio:
> 
> ```
> !cp colab_fix.txt user_path_config.txt
> ```
> 
> This will completely avoid loading default sdxl base and refiner models and therefore no more out of memory/timeout issues. It works with latest commit and I found it even loads faster now this way.
> 
> See my colab https://colab.research.google.com/drive/1G3KsEbeLawi5-vSro6rHztG70C_eEsWx?usp=sharing for working example.

Thanks and appreciated!
They do not believe me when I tell them that you can not use other custom models.

**Comment by lllyasviel** [comment]
this is solved since weeks ago.
