### ISSUE TITLE
Accelarate image generation on MacOS

### ISSUE THREAD

**Issue by yuxx1006** [lllyasviel/Fooocus#696]
I was able to install Fooocus on a Mac Pro M2 silicon chip. However, I experienced a significantly longer image generation time compared to Google Colab as the Author described in the Mac installation instructions. Everyone has suggestions to accelerate this image generation process and if there are any packages I can try.

**Comment by barepixels** [comment]
Google Colab uses Nvidia.  Blame Apple for fighting with Nvidia.

**Comment by mashb1t** [comment]
Please check again, a few things have changed since October. Feel free to reopen the issue after you have checked and provide new information.
