### ISSUE TITLE
How to use local models ?

### ISSUE THREAD

**Issue by bulutharbeli** [lllyasviel/Fooocus#701]
Is it possible to use local SD model without copy them to fooocus ? 
We can do it very easy in Comfyui by adding custom path in to extra_model_path.yaml file. Is there any way to that in Foocus ?

Thanks.

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus#customization

**Comment by lllyasviel** [comment]
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/da5002f7-302e-4fb3-880d-b7039d4c8b42)

**Comment by bulutharbeli** [comment]
> ![image](https://user-images.githubusercontent.com/19834515/275431839-da5002f7-302e-4fb3-880d-b7039d4c8b42.png)

I already tried but still the same. Probably i am doing something wrong but what

**Comment by bulutharbeli** [comment]
Ok fixed. Thanks
