### ISSUE TITLE
I don’t understand why fooocus is not as good as sd web ui with the same parameters.

### ISSUE THREAD

**Issue by 812913329** [lllyasviel/Fooocus#706]
The parameter prompt word of fooocus is Beautiful starry sky, girl wearing white T-shirt and short skirt, seed 2371425288
The prompt words of the web are (masterpiece, best quality, ultra-detailed:1.1), illustration, disheveled hair, detailed eyes, perfect composition, moist skin, intricate details, earrings, by wlop, Beautiful starry sky, girl wearing white T-shirt and short skirt
Negative cue words: longbody, lowres, bad anatomy, bad hands, missing fingers, pubic hair, extra digit, fewer digits, cropped, worst quality, low quality
Seed 2371425288
The first picture with many pictures is fooocus, and the second picture is webui. The result of copying the preset style prompt words of fooocus into webui, the steps are 30.

![foocus](https://github.com/lllyasviel/Fooocus/assets/67380983/0b99fe69-1959-45f0-81ba-7ffd65368e61)
![webui](https://github.com/lllyasviel/Fooocus/assets/67380983/43c58d9e-446e-4b4d-88fa-3fdc6dfe0f50)

**Comment by MoonRide303** [comment]
@812913329 If you want to use prompts in similar fashion to A1111 you should clean styles selection (in Style tab) - this will result in your prompt and negative prompt being used directly, without any alterations.
