### ISSUE TITLE
Queue Errors -> Session Hijacking

### ISSUE THREAD

**Issue by 666spawn999** [lllyasviel/Fooocus#713]
Hi, 
I'm trying to setup a Fooocus intance for me and my colleagues.
Sadly, a problem with the queuing System is preventing, that we can use it together. 

**Error:**
 - Client A is generating an image and exits it's browser session during generation (sure, this isn't wanted, but it happens)
 - Client B, who is waiting in the queue, gets the preview and results from the running generation of Client A
 - while getting the results the progress bar is really fast, because the frames are already generated and just buffered...
 - all following Tasks are lagging one result because the queue mixed up the resolve of the queue/clients
 - this persists indefinitely and the service needs to be restarted to fix the queue. 

Video of Problem with 2 browsers
![Fooocus_Queue_Hijacking2](https://github.com/lllyasviel/Fooocus/assets/33587160/9ac0b7b3-d121-4c7d-b71a-209560e61117)

**Steps to Replicate:**
 1. Open 2 Browser windows (same/different Browsers or incognito, doesn't matter)
 2. start a job in each window -> Client A generates, Client B is in queue
 3. Exit or reload Client A Windows ->  Client B fills the slot and gets the results of ClientA instead of it's own task!
 4. The queue is from now on mixed up. Each Generation shows the Results of the Task before.
 5. Server Restart is needed to fix

**some more thoughts**
- I have already looked into this a little bit, and I think the Gradio queue and WebSocket is involved in this. 
- The Websocket Session_Ids are different in the browsers. But when ClientA quits, the rest of the result "stream" is send to the other connected websocket, even if the ID is different. 
- Adding a check, that only the Websocket who started the task, should get results, could be a fix?

Altogether this is a big problem that currently makes it impossible to share Fooocus Installation with others. All Forks I have tried are having the same problem. Some even more because they send Results to different clients in sync.. 

I think, this issues are related:
https://github.com/lllyasviel/Fooocus/issues/625

A fix would be highly appreciated! 
If you have some tips on this, I can also try to fix it myself, but currently I'm a little lost at this issue.

If this is a general problem with gradio and can't be fixed by the Fooocus Team maybe someone has some idead how to fix it in gradio?

(I really love Fooocus and all the features and the simplicity of it. Thanks for all your work! 
But sadly, bugs like this prevent me from using it in production or teams :( )

**Comment by adelorenzo-portainer** [comment]
yup, I am experiencing the same problem.

**Comment by 666spawn999** [comment]
This other issues seem to be the same bug
https://github.com/lllyasviel/Fooocus/issues/501
https://github.com/lllyasviel/Fooocus/issues/481

**Comment by yllwboy** [comment]
I've experienced the same issue, as well as encountering this issue with a single client if the client exits its browser session.

**Comment by lllyasviel** [comment]
a temp fix is landed in 2.1.751

**Comment by mmmz28** [comment]
Fooocus generates great images, but the process of getting images from the Gradio interface is always a problem, which has been bothering me for a long time. 
![202310-26302c91b37b74c883b78706173851e0](https://github.com/lllyasviel/Fooocus/assets/58453940/63e8f1c5-94d4-4389-98f6-ab7effe60e77)

**Comment by 666spawn999** [comment]
That fix makes it absolutely more tolerable because the queue doesn't break anymore. 
Thanks for looking into it!

The only problem that is left is:
 - when client A quits its session while processing an image, 
 - client B, that is in the queue gets his results AND after that his own results from the queue.

As said, the queue doesn't break anymore. But because of privacy reasons a fix for this possible image-leak-bug is still relevant I think. 

But so far, great work! And thanks very much, because I don't have to restart the server anymore!
:D

**Comment by mashb1t** [comment]
@666spawn999 tried my best as a python newbie, fixed in https://github.com/lllyasviel/Fooocus/pull/826
