### ISSUE TITLE
Moving model to GPU...

### ISSUE THREAD

**Issue by tiancool** [lllyasviel/Fooocus#714]
Moving model to GPU. Takes a long time before each generation. Is this bug?
macOS

**Comment by GLSSJG** [comment]
I'm also having this problem.

**Comment by tiancool** [comment]
Why do you have to do a memory management load before each generation for 30 seconds or more：
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.02916753850877285, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 31.17 seconds

**Comment by labeldot** [comment]
Having this issue as well. It seems on Mac that free_memory() in backend/headless/model_management is removing the model at the end of each generation. I temporarily "solved" this by commenting out basically everything in that free_memory function and it works fine.

**Comment by timothy-reyes** [comment]
Just adding my agreement with the comments above. I'm also on MacOS, M1 Macbook pro. It loads the model onto the GPU for a long time before each generation. This problem seems unique to Fooocus vs other sdxl UIs.

**Comment by Replikate648** [comment]
In win 11 doesn't work file swapping, i tried it with an Intel(R) Core(TM) i7-13700H,   16,0 GB RAM and rtx 4050 6GBVRAM

**Comment by labeldot** [comment]
I'm having the same issue with M1 Max, it moves the model to the GPU on every generation, even with the --disable-offload-from-vram flag. It does seem to be a Fooocus-specific issue as no other UIs have this problem.

**Comment by tomekand1** [comment]
I was playing with, 
<img width="1090" alt="Screenshot 2023-12-31 at 13 15 41" src="https://github.com/lllyasviel/Fooocus/assets/33412823/e04596d7-74a1-4f73-ab6f-b18a0607c9ee">
this seems not to load the model every single time, only tested on MacBook Pro 14"

**Comment by mashb1t** [comment]
This is not a bug, your disk is just a bit slow or you're using a GPU with insufficient VRAM, where Fooocus then offloads into RAM.
Feel free to re-test with the latest version of Fooocus, which might improve your performance.

**Comment by bokorumed** [comment]
@mashb1t - I'm facing the same issue, I have NVIDIA GeForce GTX 1650 Ti Mobile (4Gb of VRAM) could this be because of insufficient memory?

**Comment by mashb1t** [comment]
Yes, slow model loading time can also in zhis case have to do with your VRAM being below the minimum to load the complete SDXL model, which is 8GB.
Every bit over 4GB will be moved to RAM and if also insufficient then to swap, depending on your OS settings also directly to disk.

**Comment by DIYMSG** [comment]
I have a 3090 with 24gb vram and have the same issue

**Comment by gautamsolankidev** [comment]
12GB vram still the same
