### ISSUE TITLE
Use both VRAM and System Ram

### ISSUE THREAD

**Issue by deadpipe** [lllyasviel/Fooocus#717]
Is there an argument to make system use both VRAM and System RAM?

I have 6 GB of VRAM and 32GB of System RAM.

![Capture](https://github.com/lllyasviel/Fooocus/assets/142412134/0aaf48bb-b758-4dc1-8c8a-7e96eaf4a2df)

As you see, currently it does not use system ram of 32 GB
![Capture2](https://github.com/lllyasviel/Fooocus/assets/142412134/55d1a795-8a56-4626-80d4-23411d097df9)

**Comment by deadpipe** [comment]
But that works in Automatic1111, and is most useful for GPUs with less VRAM. It guarantees you that the image will generate regardless of low VRAM, even if it takes longer time. GPU has 50% shared System Ram so in my case it would be 6GB +16 GB = 21GB.

**Comment by deadpipe** [comment]
But it works in Automatic 1111, and is most useful for slower GPUs. It guarantees you that the Image will generate regardless of low VRAM, although it will take longer time. The GPU will share 50% of system ram so in my case it will be 6+16 = 21GB. 

As you see in the Image, GPU allocates System RAM to accommodate the model
![gpu memory](https://github.com/lllyasviel/Fooocus/assets/142412134/9a195fbf-0ec1-4204-9860-b51406333ef0)

**Comment by 812913329** [comment]
> 但它适用于自动 1111，并且对于速度较慢的 GPU 最有用。它保证无论 VRAM 是否低，图像都会生成，尽管这会花费更长的时间。GPU 将共享 50% 的系统 RAM，因此在我的例子中，它将是 6+16 = 22GB。
> 
> 如图所示，GPU 分配系统 RAM 来容纳模型 ![显卡内存](https://user-images.githubusercontent.com/142412134/276252250-9a195fbf-0ec1-4204-9860-b51406333ef0.jpg)

Mine will use ram, fooocus is newly installed in the recent versions. If yours is not, you can try downloading the latest source code and reinstalling it. If it still doesn't work, @author and other authors can solve it, because we can all use it, so we can eliminate the problem. It's just personal.

**Comment by lllyasviel** [comment]
hi if you find in any cases using shared vram is faster ( for example if you can get images from a1111 with similar visual quality but faster speed) we will take a look
