### ISSUE TITLE
Inpainting not working in case the mask area has big overlap with strong visual elements of original image 

### ISSUE THREAD

**Issue by lanyusan** [lllyasviel/Fooocus#720]
I am using 2.1.693, inpainting 1.0 & 2.5 both have this problem.

![image](https://github.com/lllyasviel/Fooocus/assets/56706512/1d6d3e73-b1a9-4b95-b161-4f70d6f38b0b)

**Comment by lanyusan** [comment]
original image:
![0 (11)](https://github.com/lllyasviel/Fooocus/assets/56706512/0665dea4-f1a9-4cef-8c86-3c4cf8680dfa)

**Comment by lllyasviel** [comment]
2.1.703 fixed many inpaint problems

![image](https://github.com/lllyasviel/Fooocus/assets/19834515/7694936c-0015-42fa-b2ec-ef492e9d34e4)

**Comment by lanyusan** [comment]
I have tested the new version '2.1.709'.

The result is that if the mask area is small, it misses mostly. When the mask area is larger, the inpainting works much more likely.

![Screenshot from 2023-10-20 08-10-56](https://github.com/lllyasviel/Fooocus/assets/56706512/d4c62ff2-50d9-4def-8c8b-0cba75faa501)

![Screenshot from 2023-10-20 08-11-58](https://github.com/lllyasviel/Fooocus/assets/56706512/3a11086b-e700-4000-bf4f-19f54c54e44a)

![Screenshot from 2023-10-20 08-12-54](https://github.com/lllyasviel/Fooocus/assets/56706512/1ebc110b-f876-4fb4-b9ea-8ce804e2da19)

**Comment by vikmaks1** [comment]
Can confirm that the strange inpainting behavior is still present in v2.1.772. 
If the mask is relatively small, it seems as if the prompt was ignored altogether — no new objects are generated, masked area is filled from the surroundings:
![image](https://github.com/lllyasviel/Fooocus/assets/81852652/8d6d18ec-d009-4695-bda4-ffd1d78de966)

But, when the mask size is increased, new objects appear, yet they tend to be far from what is in the prompt:
![image](https://github.com/lllyasviel/Fooocus/assets/81852652/58ccf6b6-b716-4587-9a23-9ac4b5f71beb)
Examples were generated with inpainting model v2.5. (v1 acts the same), no styles selected, the same seed.

**Comment by mashb1t** [comment]
Please test again with the latest version of Fooocus, especially with inpaint method "Modify Content (add objects, change background, etc.)", and let us know the results.

**Comment by mashb1t** [comment]
Closing as stale, feel free to reopen when providing new information.
