### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by yys45623** [lllyasviel/Fooocus#728]
Traceback (most recent call last):
  File "/root/Fooocus/modules/async_worker.py", line 584, in worker
    handler(task)
  File "/root/Fooocus/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/Fooocus/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/Fooocus/modules/async_worker.py", line 198, in handler
    if advanced_parameters.overwrite_step > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by Cool-Bo** [comment]
Hello brother, I have the same problem as you and it has been solved now. I don't know if the method works for you, you can try it:
        client = Client("http://127.0.0.1:7860/",serialize=False)
        result = client.predict(.......)
 Try setting up serialize=False

**Comment by konieshadow** [comment]
Self-promotion: https://github.com/konieshadow/Fooocus-API.

This project just transforms all Fooocus's generation methods to normal http apis. Have fun with it, and welcome to contribute.

**Comment by DougTanner** [comment]
I found a workaround:

1. Go into web client and check "Developer Debug Mode"
2. Change the value of "Forced Overwrite of Sampling Step" slider
3. Generate something
4. Set it back to -1
5. Generate something

The API is working now?

**Comment by thiner** [comment]
> I found a workaround:
> 
> 1. Go into web client and check "Developer Debug Mode"
> 2. Change the value of "Forced Overwrite of Sampling Step" slider
> 3. Generate something
> 4. Set it back to -1
> 5. Generate something
> 
> The API is working now?

This workaround saved me! Thank you!

Anyway, this is a bug need to be fixed. I checked relevant code. Seems it's made 2 months ago, but rare users encoutered this problem. Maybe it's version problem of Gradio?

**Comment by psydox** [comment]
> I found a workaround:
> 
> 1. Go into web client and check "Developer Debug Mode"
> 2. Change the value of "Forced Overwrite of Sampling Step" slider
> 3. Generate something
> 4. Set it back to -1
> 5. Generate something
> 
> The API is working now?

This fixes the same issue on my side.  Thanks!
