### ISSUE TITLE
Ratios

### ISSUE THREAD

**Issue by Geo2D3D** [lllyasviel/Fooocus#730]
Hi! Thank you for your cool Fooocus!
Could you, please, put that list of ratios in a *.json file? As if we enter the ratios we want in manually in the sdxl_styles.py file they keep on being overwritten everytime we launch the software.

If you don't find time to change that, could you, please, implement in the basic version of Fooocus the open html field that was in the mre version, in order for us to be able to enter the desired ratio?

**Comment by lllyasviel** [comment]
Advanced->Developer Debug Mode->Forced Overwrite of Generating Width->You can change resolution using int number below the warning "Results will be worse for non-standard numbers that SDXL is not trained on"

**Comment by Geo2D3D** [comment]
Hi, thank you for your concern. Please, note that this setting isn't kept, it disappears when we reload the console.

**Comment by Absinthze** [comment]
Please add custom resolution.  I have specific sizes that make existing renderings I would like to use.  Like 3000x2000 ,Thank you.

**Comment by Geo2D3D** [comment]
A warm thank you for your concern!
I'm sorry, I don't understand. 
I tried to enter either 1, or a value such as 1024 in the field: Forced Overwrite of Generating Width.
Same with Forced Overwrite of Generating height.
The values I enter ain't memorized, ain't kept when I relaunch the software within the *.dat file.

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/discussions/117#discussioncomment-7364981
