### ISSUE TITLE
Bug in abnormal image enlargement (reproducible), and repair of pop-up images

### ISSUE THREAD

**Issue by 812913329** [lllyasviel/Fooocus#738]
I like fooocus very much. I hope it will get better and better and more perfect. The current problem is with the latest version of fooocus that was just updated today.
1: First of all, zoom in. The restoration of the real person imported from the outside without fooocus can be described as terrible. Even though the picture can be seen clearly, the quality after restoration is even worse.
2: Weird things will always appear when repairing certain pictures, and the overall experience is not that good.
3: This magnification is surprisingly good for the pictures generated by fooocus, which is really strange. Is it possible to consider adding another repair option and using the best repair plug-in on the market in fooocus? The following is the log record of abnormal resolution, which may be an error in smart allocation.

[Fooocus] Upscaling image from (549, 699) ...
Image upscaled.
Resolution corrected - users are uploading their own images.
[Fooocus] VAE encoding ...
Final resolution is (2304, 1792).

![QQ截图20231020013202](https://github.com/lllyasviel/Fooocus/assets/67380983/ada5fd90-05c5-435f-8200-d874587720b6)
First of all, the above is the original picture，Next is the picture of quick fix 2x and and quick zoom 2x，Then the resolution is abnormal，The resolution is 1972*2304 and the original image is 699*549
![ksx2f](https://github.com/lllyasviel/Fooocus/assets/67380983/97be39ec-b18d-4110-9064-dd717a4bcb77)

Next let’s look at the 1.5x enlarged picture，The resolution is 1048*816, the original image is 699*549, the resolution here is normal，But it’s too collapsed when zoomed in.

![ks x1 5](https://github.com/lllyasviel/Fooocus/assets/67380983/2ea2ab1e-da6d-4716-86be-c2423ac9ca12)

![2023-10-20_01-35-11_2215](https://github.com/lllyasviel/Fooocus/assets/67380983/2f3cea3b-3484-42d3-a1a7-bd3c123b19f3)

**Comment by lllyasviel** [comment]
reworking resolution computation of user uploaded images is planned

**Comment by lllyasviel** [comment]
try 2.1.175
also `fast 2x` will not repaint

**Comment by 812913329** [comment]
> 尝试2.1.175 也`fast 2x`不会重画

Thanks for the proactive fix. OK, the resolution is normal, and the repair effect seems to be better. But the amazing thing is that quick repair 2x is better than repair 2x. The current magnification effect is sufficient, especially the speed of quick repair is really shocking, it only takes a few seconds. Hope it gets better and better

**Comment by lllyasviel** [comment]
fooocus upscale and vary are mainly for dragging generated images to that tool bar, like midjourney
processing uploaded user images is experimental
