### ISSUE TITLE
How to use base models other than SDXL?

### ISSUE THREAD

**Issue by vinjn** [lllyasviel/Fooocus#75]

**Comment by ujl123** [comment]
Advanced checkbox, then advanced tab on the right

**Comment by vinjn** [comment]
Nope it didn't work and I sawthe following error:

`Model not supported. Fooocus only support SDXL model as the base model.`

**Comment by ujl123** [comment]
> Nope it didn't work and I saw the following error:
> 
> `Model not supported. Fooocus only support SDXL model as the base model.`

 Sorry for misleading you. I had misread your title and thought you wanted other base models of SDXL that wasn't the basic one that SAI released. AFAIK only the base SDXL models work.

**Comment by Tigwin** [comment]
It would be really nice if we could use a different base for the initial render and then use sdxl refiner or base+refiner to finish it off.

**Comment by sampadsams** [comment]
Deleting or disabling these lines in refresh_base_model() function in default_pipeline.py:

`
    if not isinstance(xl_base.unet.model, SDXL):
        print('Model not supported. Fooocus only support SDXL model as the base model.')
        xl_base = None
        xl_base_hash = ''
        refresh_base_model(modules.path.default_base_model_name)
        xl_base_hash = name
        xl_base_patched = xl_base
        xl_base_patched_hash = ''
        return
`
and setting refiner to None in advanced section , solves the problem.


I thought there would be a critical error in the SDXL that made Fooocus to come up with these lines  , but I encountered none by removing them.

**Comment by sampadsams** [comment]
Also I realized some models require special field like weight controls that Fooocus does not have , you'll get errors for those. But some models does not require them and will work by the method I found , one is DreamSharper which is one of the bests.

**Comment by mashb1t** [comment]
> It would be really nice if we could use a different base for the initial render and then use sdxl refiner or base+refiner to finish it off.

Well, it's been a long time folks, but the answer is exactly this: https://github.com/lllyasviel/Fooocus/issues/1568#issuecomment-1868379903

**Comment by Riohigh6387** [comment]
> 👍 Solution to use other models on Fooocus :
> 
> Don't read this :
> 
> Models have different types that should be loaded correctly in their special place , a model generates images and another changes or refines it , that's the standard. Some models come with the whole sequence , but in separated files , because they have to be loaded in that standard. Example of that is the default XL model that Fooocus uses , it is one model but comes in two files , and it causes problems if you intend to replace only one of them. Solution, is to replace both.
> 
> Read this :
> 
> 1 . Deleting or disabling these lines in refresh_base_model() function in default_pipeline.py:
> 
> `if not isinstance(xl_base.unet.model, SDXL): print('Model not supported. Fooocus only support SDXL model as the base model.') xl_base = None xl_base_hash = '' refresh_base_model(modules.path.default_base_model_name) xl_base_hash = name xl_base_patched = xl_base xl_base_patched_hash = '' return`
> 
> 2 . Put a `CHECKPOINT TRAINED` type model like DreamSharper in checkpoints folder and set it in advanced section (refinder to None)
> 
> 3. Optional: You can put `Lora` type model in loras folder and use with your base model
> 
> I'll update this as I explore different types of models.

Any updates? i did exactly as you said and it worked fine till it didnt , wampwamp.black screen at finish.. Do you know what i can do to prevent this? anything helps, i like to tinker. Thanks in advance.
