### ISSUE TITLE
Power spikes during encoding positive and negative 

### ISSUE THREAD

**Issue by BeardlyBeard** [lllyasviel/Fooocus#753]
Windows 10 Pro 10.0.19045, Ryzen 7 5800x , Gigabyte RTX 3070  driver ver 545.84

Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.722
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total VRAM 8191 MB, total RAM 16284 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : native
VAE dtype: torch.bfloat16

_**Experiencing audible power spikes from GPU that also slightly dim house lights !!!!!!!!**_ 

During 
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...

**Comment by mashb1t** [comment]
> ... also slightly dim house lights

Is your house is still standing? 😆 (i'd propose to use a different circuit if you're drawing too mich power, but nothing critical, as the breaker handles electrical surges)
