### ISSUE TITLE
I carefully proofread the Chinese language script

### ISSUE THREAD

**Issue by diaolulu1** [lllyasviel/Fooocus#757]
[chs.json](https://github.com/lllyasviel/Fooocus/files/13061086/chs.json)

**Comment by Realysimon** [comment]
done well

**Comment by youyegit** [comment]
[zh_CN.json](https://github.com/lllyasviel/Fooocus/files/13063323/zh_CN.json)
it's based chs.json above,  just change some words, for reference only.

**Comment by diaolulu1** [comment]
Thanks a lot!

**Comment by tiwentichat** [comment]
@diaolulu1 @youyegit   

several changes on the version of youyegit's zh_CN.json

@lllyasviel Maybe Chinese simplified file could be pull now?


在youyegit版本基础上做了一些字词的调整
修改内容：

gallery 画廊     相册
 "Advanced": "高级选项    ",    高级设置
 "Image Style": "图像样式",   图像风格
"Similar to the Control Mode in A1111 (use 0.0 to disable). ": "类似于Stable Diffusion WebUI中的控制模式（使用0.0来禁用）。 ",  与SD WebUI 中的控制模式类似（设为0.0时为禁用）

[zh_CN.json](https://github.com/lllyasviel/Fooocus/files/13169182/zh_CN.json)

**Comment by diaolulu1** [comment]
> @diaolulu1 @youyegit   
> 
> several changes on the version of youyegit's zh_CN.json
> 
> @lllyasviel Maybe Chinese simplified file could be pull now?
> 
> 
> 在youyegit版本基础上做了一些字词的调整
> 修改内容：
> 
> gallery 画廊     相册
>  "Advanced": "高级选项    ",    高级设置
>  "Image Style": "图像样式",   图像风格
> "Similar to the Control Mode in A1111 (use 0.0 to disable). ": "类似于Stable Diffusion WebUI中的控制模式（使用0.0来禁用）。 ",  与SD WebUI 中的控制模式类似（设为0.0时为禁用）
> 
> [zh_CN.json](https://github.com/lllyasviel/Fooocus/files/13169182/zh_CN.json)
> 

good job！

**Comment by diaolulu1** [comment]
@tiwentichat Good job！I give you a new one。
[zh_CN.json](https://github.com/lllyasviel/Fooocus/files/13169440/zh_CN.json)

**Comment by diaolulu1** [comment]
@tiwentichat Good job！I give you a new one！
@lllyasviel 
[zh_CN.json](https://github.com/lllyasviel/Fooocus/files/13169454/zh_CN.json)

**Comment by tiwentichat** [comment]
> @tiwentichat Good job！I give you a new one！ @lllyasviel [zh_CN.json](https://github.com/lllyasviel/Fooocus/files/13169454/zh_CN.json)

Great!

Another change: 
 "Fooocus V2": "Fooocus提示词智能填充V2",
This button is a magic button, new user would be confused by the V2 

Most time, no one would read docs or readme or any guide...
We may clarify that button's meaning.

**Comment by tiwentichat** [comment]
"Style": "样式",    修改为 风格

> @tiwentichat Good job！I give you a new one！ @lllyasviel [zh_CN.json](https://github.com/lllyasviel/Fooocus/files/13169454/zh_CN.json)

我靠，看到你最新版本 输入提示词那一条翻译了，为啥啊。。。十连懵逼
    "Type prompt here.": "在这里输入提示词（支持简单中文词，请用英文逗号分隔）",


验证了，猫可以识别，但是熊猫识别不了。输入中文熊猫还是会画猫


有一个cg工具站的哥们搞了个这个版本：https://gitee.com/fooocus2023/Fooocus 可以直接识别中文。不过容易脸崩，两张图必崩一个
（伸手党：@diaolulu1 @lllyasviel 大佬们要不要把GPT2再发光发热一下，可以提供各种语言的功能。。
刚才码云的那个哥们版本迭代了，之前是 /C 然后就可以输入中文了；最新版本是不需要输入 /C 直接输入中文

从国际化考虑可以让非英语使用者用 /CN /FR  /RU /DE /JP之类的指令开启不同语言的提示词输入

一个不会写代码的厚脸皮伸手党留言  T T

**Comment by diaolulu1** [comment]
今天的新版本已经更新了gpt2，可以更好的识别中文了

**Comment by tiwentichat** [comment]
纠正：
    "Fooocus V2": "FooocusV2智能扩展提示词",
新增：
    "Fooocus Enhance": "Foocus-增强",
    "Fooocus Sharp": "Fooocus-锐化",

**Comment by tiwentichat** [comment]
> 今天的新版本已经更新了gpt2，可以更好的识别中文了

哎，那我重启一下试试

**Comment by tiwentichat** [comment]
> 今天的新版本已经更新了gpt2，可以更好的识别中文了

不行，目前能识别的就是：猫、狗，其他的都不能识别：牛、马、树、树木、森林，都不行，会直接画人；而熊猫则会被识别为猫。更多的中文词没有测试。

**Comment by zwdzwdzwd** [comment]
弱弱的问一句，win7系统能用吗？amd显卡，按照要求改好runbat文件后启动出现错误提示“无法启动此程序，因为计算机中丢失 api-ms-win-core-path-|1-1-0.dll。尝试重新安装该程序以解决此问题。”就用不了， 谢谢！

**Comment by diaolulu1** [comment]
没有amd显卡，没法测试

**Comment by mlbzsske** [comment]
切换中文翻译的方式为：  #https://github.com/fenneishi/Fooocus-ControlNet-SDXL/issues/12

**Comment by mashb1t** [comment]
Please contribute your changes to https://github.com/lllyasviel/Fooocus/pull/756.
