### ISSUE TITLE
USER_PATH_CONFIG

### ISSUE THREAD

**Issue by MokkaBoss1** [lllyasviel/Fooocus#760]
Hi,

I noticed that when I try to create default values to be chosen on startup, the frontend seems to revert back to the standard ones.

Is this a known problem or am I potentially doing something wrong?

my txt file looks like:

{
    "modelfile_path": "C:\\Fooocus_win64_2-1-14\\Fooocus\\models\\checkpoints",
    "lorafile_path": "C:\\Fooocus_win64_2-1-14\\Fooocus\\models\\loras",
    "vae_approx_path": "C:\\Fooocus_win64_2-1-14\\Fooocus\\models\\vae_approx",
    "upscale_models_path": "C:\\Fooocus_win64_2-1-14\\Fooocus\\models\\upscale_models",
    "inpaint_models_path": "C:\\Fooocus_win64_2-1-14\\Fooocus\\models\\inpaint",
    "controlnet_models_path": "C:\\Fooocus_win64_2-1-14\\Fooocus\\models\\controlnet",
    "clip_vision_models_path": "C:\\Fooocus_win64_2-1-14\\Fooocus\\models\\clip_vision",
    "fooocus_expansion_path": "C:\\Fooocus_win64_2-1-14\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
    "temp_outputs_path": "C:\\Fooocus_win64_2-1-14\\Fooocus\\outputs",
    "default_model": "juggernautXL_version5.safetensors",
    "default_refiner": "",
    "default_lora": "JuggerCineXL2.safetensors",
    "default_lora_weight": 0.5,
    "default_cfg_scale": 7.0,
    "default_sampler": "dpmpp_2m_sde_gpu",
    "default_scheduler": "karras",
    "default_styles": [
        "Fooocus V2",
        "Default (Slightly Cinematic)"
        "SAI Digital Art"
	"SAI Fantasy Art"
    ],
    "default_negative_prompt": "low quality, bad hands, bad eyes, cropped, missing fingers, extra digit",
    "default_positive_prompt": "",
    },
    "default_aspect_ratio": "768*1280",
    "embeddings_path": "C:\\Fooocus_win64_2-1-14\\Fooocus\\models\\embeddings",
    },
    "embeddings_downloads": {},
    "default_advanced_checkbox": false,
    "default_image_number": 2
}

Kind regards

Mokkaboss1

**Comment by lllyasviel** [comment]
use \\\\

**Comment by barepixels** [comment]
I notice you are missing a close bracket "default_styles": [ 

and like lllyasviel said use \\  like this:

"modelfile_path": "C:\\Fooocus_win64_2-1-14\\Fooocus\\models\\checkpoints",

**Comment by MokkaBoss1** [comment]
many thanks for pointing me in the right direction and apologies for my carelessness.

Regards

Mokkaboss1
