### ISSUE TITLE
what's the matter:missing somthing.

### ISSUE THREAD

**Issue by g558800** [lllyasviel/Fooocus#762]
![cHLyIwJd3E](https://github.com/lllyasviel/Fooocus/assets/119348639/456728ec-21be-4f23-8624-5706685d5875)

As framed in the picture

**Comment by Vincevinny** [comment]
bump same issue added clip_vision_g.safetensors manually not seen any changes

**Comment by mashb1t** [comment]
As far as i could see these are debug outputs. Please make sure to re-test with the latest version of Fooocus.
