### ISSUE TITLE
There are two "Aspect Ratios" that cannot be translated.

### ISSUE THREAD

**Issue by youyegit** [lllyasviel/Fooocus#766]
![image](https://github.com/lllyasviel/Fooocus/assets/131540443/7887b73c-9ee5-4ed9-af17-d7d270291f61)

language json :
![image](https://github.com/lllyasviel/Fooocus/assets/131540443/438d3f77-5b5d-4398-82eb-46d3296aebd8)

**Comment by xhoxye** [comment]
"896\u00d71152": "896\u00d71152（0.78）",
    "1152\u00d7896": "1152\u00d7896（1.29）",

**Comment by youyegit** [comment]
"1152\u00d7896": "1152\u00d7896（1.29）" is missing in language/en.json .

**Comment by mashb1t** [comment]
Specific resolutions are not translated.
