### ISSUE TITLE
[Feature Requests] Disney art styles

### ISSUE THREAD

**Issue by thekingbalXD** [lllyasviel/Fooocus#769]

**Comment by Vincevinny** [comment]
look in Fooocus\sdxl_styles 
copy sdxl_styles_fooocus.json 
rename sdxl_styles_fooocus - Copy.json 
to sdxl_styles_TheKingbalXD.json
open in notepad or better notepad++ (https://notepad-plus-plus.org/)
then delete the first 5 entry's LEAVE THE BRACKET AT THE START [
but you can delete the indented brackets {} of the first 5 entry's 
that should leave you with ONLY 
[
    {
        "name": "Fooocus Cinematic",
        "prompt": "cinematic still {prompt} . emotional, harmonious, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy",
        "negative_prompt": "anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured"
    }
]

now you can edit this to do exactly what you want\need NOTE it will not update if you modify while fooocus is still open so i would recommend going into normal fooocus and finding a prompt that works well for you then removing specific subject information as you can add that via prompt later

example is if you set in your style Cinderella then it will use her only so go for something more stylistic in those presets 

if your preset is Disney animated cartoon style 
and your prompt is Cinderella and belle it should apply the style with no other prompting needed

extra note if you plan to have multiple entries in this .json you must use comma (,) as a delimiter
if you have no idea what i mean here is an example

[
    {
        "name": "thekingbalXD Disney",
        "prompt": "disney style {prompt} Disney cartoon style",
        "negative_prompt": ""
    }, (do not copy this text im just pointing out that comma is a delimiter telling the code to look for another entry after the first)
 {
        "name": "thekingbalXD legend",
        "prompt": "epic king bal style {prompt} worlds coolest dude",
        "negative_prompt": "uncool beans"
    } (once again do not put the () brackets or any text here if copying but note that if you put a delimiter (, a comma) at the end of the json it will not load)
]

i assume you have enough know how to modify it yourself now i explained it but if you just want results her is the example i made for you just drop it in E:\Stable diffusion\Interfaces\Fooocus\Fooocus\sdxl_styles
[sdxl_styles_thekingbalXD.json](https://github.com/lllyasviel/Fooocus/files/13233870/sdxl_styles_thekingbalXD.json)
