### ISSUE TITLE
How can i save full settings parameters?

### ISSUE THREAD

**Issue by kubilaykilinc** [lllyasviel/Fooocus#775]
Hi,

Fooocus uses the default values in the sample preset files, which I can change as needed. However, I want to define my own custom settings, but I have to manually adjust other settings every time I turn it on.

How can I save the first, second, third, fourth, and fifth LoRa settings as the default values in the preset?
I also want to customize the Developer Debug Mode settings, such as setting FreeU to True by default. I want to be able to define and save all of my Developer Debug Mode settings in the preset.
I haven't been able to do this because I can't find a sample file.

**Comment by Vincevinny** [comment]
i made a new preset and new .bat to launch the preset 
the .bat 
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset Vince
pause
SAVE AS BAT


the new preset
 {
    "default_model": "juggernautXL_version6Rundiffusion.safetensors",
    "default_refiner": "",
    "default_lora": "",
    "default_lora_weight": 0.25,
    "default_cfg_scale": 3.0,
    "default_sampler": "dpmpp_3m_sde_gpu",
    "default_scheduler": "karras",
    "default_styles": [
		"Vin Neg"
    ],
    "default_prompt_negative": "",
    "default_prompt": "happy dog",
	"default_aspect_ratio": "896*1152",
	"default_image_number": 2,
    "checkpoint_downloads": {},
    "lora_downloads": {},
    "embeddings_downloads": {},
	"default_advanced_checkbox": true
}

SAVE AS JSON!!

then delete the user_path_config.txt and use windows junctions to move the models you want into foocous with the config.txt deleted it wont constantly delete your custom folders

you can also add your own styles like this just copy sdxl_styles_fooocus.json rename it and modify it to your needs

**Comment by mashb1t** [comment]
You can simply duplicate one of the existing presets, such as e.g. realistic https://github.com/lllyasviel/Fooocus/blob/main/presets/realistic.json, then modify it to suit yuur needs.
Presets can be used by ading `--preset <name>` to your run.bat or entrypoint script.

**Comment by ksorah1** [comment]
in all others uis, params are saved on each picture and you just have to drag and drop them into uis to change parameters.

**Comment by mashb1t** [comment]
Yeah, about that, i've integrated this feature only 2 days ago (at least the metadata writing part), see https://github.com/lllyasviel/Fooocus/pull/1940
This allows to add metadata for both Fooocus and A1111, but currently there is not yet a way to re-import this to Fooocus.
Stay tuned, will develop this when i have time!

**Comment by ksorah1** [comment]
ok, your ui brought me all that that the other uis did not do (comfy, 1111, dall-e, midjourney, invoke, etc...):
-working and fast sdxl
-excellent in/outpaint, better than dall-e (and hd, just how)
-satisfactory LORA, thanks to the subtle modify and to:
-upscale that hallucinates.

excellent ui but this feature is missing to death, I read your link.

**Comment by ksorah1** [comment]
ah and your ui is useful too to fix bad pictures (when you generate a bad face for exemple)...
