### ISSUE TITLE
--share --gradio-auth username:password

### ISSUE THREAD

**Issue by Andro-Meta** [lllyasviel/Fooocus#777]
I see that --share does work when adding the line argument in the .bat file. It would be nice to be able to secure it additionally with --gradio-auth username:password. It would be amazing if --ngrok was added.

**Comment by MoonRide303** [comment]
@Andro-Meta I've ported support for auth from MRE in v2.1.739 (https://github.com/lllyasviel/Fooocus/pull/778) - you can define your credentials in `auth.json` (`auth-example.json` is provided as an illustraion of the syntax).

**Comment by goetzc** [comment]
Having authentication without requiring `--share` would be great, as `--listen` could be benefited too.
