### ISSUE TITLE
Out of memory error on PC

### ISSUE THREAD

**Issue by jdmoser1** [lllyasviel/Fooocus#780]
Hello. I just installed Fooocus, let it download the SDXL models, and did my first test run. It failed to complete the run with the message:
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 3.55 GiB is free. Of the allocated memory 1.36 GiB is allocated by PyTorch, and 77.12 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I'm running on a Desktop with 8GB RAM and a NVIDIA GeForce RTX 2060 with 6GB VRAM. I was able to get SDXL to work before on Automatic1111, but the model was a slightly different version.

**Comment by lllyasviel** [comment]
show full log?

**Comment by lllyasviel** [comment]
hello this should be caused by system RAM too old and does not support transformer accelerator's hooks.
2060 is supported by Fooocus, and well tested, and should work if system RAM is in order.
if Automatic1111 works on this device then probably the best thing to do is to keep using Automatic1111.

**Comment by jdmoser1** [comment]
okay. I may do that. Is there no available workaround for the RAM issue?

**Comment by FlatMapIO** [comment]
In my test https://github.com/lllyasviel/Fooocus/issues/792, starting a 16GB CPU memory may be a problem.

**Comment by lllyasviel** [comment]
Hi all, fooocus can run in 12GB RAM in linux without swap. see also the colab demo (linux, 12GB RAM, no swap, T4 GPU). But this may also related to many complicated factors like CPU arch, etc
