### ISSUE TITLE
2x upscale is a bit more than 2x

### ISSUE THREAD

**Issue by realmalikov** [lllyasviel/Fooocus#790]
Upscaling an image with dimensions 704×1408 results in a resolution of 1408×2880, actually it should be 1408×2816, if I'm not mistaken.

Is this intentional, or am I doing something wrong?

**Comment by barepixels** [comment]
am guessing 1408×2816 is not the ideal dimension for SDXL  so lllyasviel codes change it to the nearest SDXL ideal dimension
maybe see this link https://github.com/lllyasviel/Fooocus/discussions/117#discussioncomment-7364981
but I could be wrong with my theory

**Comment by lllyasviel** [comment]
looks like a bug - will take a look

**Comment by lllyasviel** [comment]
try 2.1.744
