### ISSUE TITLE
[Bug] - "missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}"

### ISSUE THREAD

**Issue by 016R35H** [lllyasviel/Fooocus#791]
**Describe the problem**
I just installed it and ran it. I can't get it to work because apparently there's something internal missing and the whole app crashes.

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.
D:\Software\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.741
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total VRAM 23028 MB, total RAM 32535 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
[Fooocus] Disabling smart memory
model_type EPS
adm 2560
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Refiner model loaded: D:\Software\Fooocus\Fooocus\models\checkpoints\sd_xl_refiner_1.0_0.9vae.safetensors

D:\Software\Fooocus>pause
Press any key to continue . . .

**Comment by lllyasviel** [comment]
hello `missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}` is not an error and can be ignored.

Do you have problem entering the software?

**Comment by jerafim76** [comment]
I have the same problem. The software enters fine, but when I enter the prompt and create the image, it says "Error Connection errored out." and stops. If I run it with run_realistic.bat, it works fine. The problem is only with run.bat.

**Comment by Mydong** [comment]
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}

I need the same question.   run.bat

**Comment by lllyasviel** [comment]
Hi if you are using Windows, see also the parts about "Microsoft’s Virtual Swap" in the readme. This is likely to be caused by a system swap problem.

**Comment by 016R35H** [comment]
> Hi if you are using Windows, see also the parts about "Microsoft’s Virtual Swap" in the readme. This is likely to be caused by a system swap problem.

I had the paging file disabled; I've enabled it again and now works.
