### ISSUE TITLE
Color text

### ISSUE THREAD

**Issue by barepixels** [lllyasviel/Fooocus#797]
**Describe the idea you'd like**

@MoonRide303 can you change this line of code in webui.py (line 62)

    `print(f'\033[92mTotal time: {execution_time:.2f} seconds\033[0m')`

So Total time will look like this in CMD window

![totaltime2](https://github.com/lllyasviel/Fooocus/assets/92839033/3fd6f2bc-4b02-4f30-a342-08badc6f297f)

**Comment by barepixels** [comment]
Nevermind.  Figured it out.
![totaltime](https://github.com/lllyasviel/Fooocus/assets/92839033/24da1772-76f2-4b0c-91e9-ba9d6e05f24e)

**Comment by MoonRide303** [comment]
@barepixels I am not sure about this one:
1. Not for everyone generation time is most important information that should be highlighted like this.
2. Not all text terminals ANSI escape codes - and it might look like garbage on those who don't. For example support for it in Windows was added just few years ago.

**Comment by barepixels** [comment]
MRE and Ruined Fooocus use it.  I love the feature.  Just don't want to re-add to my fork when lllyasviel update.

**Comment by MoonRide303** [comment]
@barepixels Nope, MRE does NOT use it.

**Comment by barepixels** [comment]
I remember now.  With my copy of MRE it was added when I got the custom save file name mod for Style Iterator
