### ISSUE TITLE
[Feature request] Propose a shared model location

### ISSUE THREAD

**Issue by tcmaps** [lllyasviel/Fooocus#8]
There are so many SD-webuis now and each is saving the models inside it's own directory structure. Novice users unbeknownst of symlinking or launch parameter will divert to upgrading their drives, uneedingly wasting resources.

Someone should take the lead and define a default location in AppData/Local on Windows or the user's home directory on *nix. HF diffusers is a positive example with using a system-wide cache.

**Comment by WinstonWoof** [comment]
Noooooo, I dont want anything being written to my "normal" windows folders. I want all of the installs to be standalone.

What would be useful though is if maintainers put instructions on how to create symlinks etc as part of the install (although thats a sperate issue , so many 12 o'colck flashers dont read any of the documentation as it is!!

**Comment by ke1ne** [comment]
@lllyasviel I would propose to:
1. make downloading of models optional instead of forced;
2. add settings page so user can set paths to existing model directories.

**Comment by jlitz** [comment]
yea doesn't make sense to d/l  the models again  should be optionable or have a setting to point to stored models.

**Comment by teadrinker** [comment]
Please support configurable paths similar to ComfyUI:

https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example

**Comment by uarefans** [comment]
Notes: Just work for me, i don't know if this code break author code, just want share

1. create config.json in same folder with readme.md (change `C:\Users\new\AI_Model` with your model folder )
    ```json
    {
        "modelfile_path": "C:\\Users\\new\\AI_Model\\checkpoints",
        "lorafile_path": "C:\\Users\\new\\AI_Model\\loras",
        "temp_outputs_path": "C:\\Users\\new\\AI_Fooocus\\Fooocus\\outputs"
    }
    ```
2. edit Fooocus\modules\path.py
```pyhton
import os
import json

# Load configuration from config.json
with open(os.path.abspath(os.path.join(os.path.dirname(__file__), '../config.json')), 'r') as config_file:
    config = json.load(config_file)

# Access configuration values
modelfile_path = config["modelfile_path"]
lorafile_path = config["lorafile_path"]
temp_outputs_path = config["temp_outputs_path"]

# Delete or comment this 3 lines
#modelfile_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../models/checkpoints/'))
#lorafile_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../models/loras/'))
#temp_outputs_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../outputs/'))

# ... existing code
```

**Comment by eypacha** [comment]
> Notes: Just work for me, i don't know if this code break author code, just want share
> 
> 1. create `config.json` in same folder with `readme.md` (change `C:\Users\new\AI_Model` with your model folder )
>    ```json
>    {
>        "modelfile_path": "C:\\Users\\new\\AI_Model\\checkpoints",
>        "lorafile_path": "C:\\Users\\new\\AI_Model\\loras",
>        "temp_outputs_path": "C:\\Users\\new\\AI_Fooocus\\Fooocus\\outputs"
>    }
>    ```
> 2. edit `Fooocus\modules\path.py`
> 
> ```
> import os
> import json
> 
> # Load configuration from config.json
> with open(os.path.abspath(os.path.join(os.path.dirname(__file__), '../config.json')), 'r') as config_file:
>     config = json.load(config_file)
> 
> # Access configuration values
> modelfile_path = config["modelfile_path"]
> lorafile_path = config["lorafile_path"]
> temp_outputs_path = config["temp_outputs_path"]
> 
> # Delete or comment this 3 lines
> #modelfile_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../models/checkpoints/'))
> #lorafile_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../models/loras/'))
> #temp_outputs_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../outputs/'))
> 
> # ... existing code
> ```

This simple code is a good idea for a pull quest, I would only add some conditionals and Try Except for handle it. I am not saying that you should do it, in a few days if I have free time I will write it.

**Comment by mashb1t** [comment]
This is all now possible by using presets and the config.txt. Closing this issue.
