### ISSUE TITLE
Feature Request: UI Improvements

### ISSUE THREAD

**Issue by MonsterAzi** [lllyasviel/Fooocus#80]
The current UI is not intuitive in some sections, mainly the visual previews of the advanced settings.

- No Preview of Aspect Ratios
- No Preview of Styles
- No Preview of LoRas

**Comment by Semonxue** [comment]
I made a Fooocus style reference , you can preview all styles in this sheet.

https://docs.google.com/spreadsheets/d/1AF5bd-fALxlu0lguZQiQVn1yZwxUiBJGyh2eyJJWl74

**Comment by GoldMath** [comment]
**Aspect Ratios** should be heavily simplify to go with the app philosophy, actual implantation is very overwhelming: 
> Users can forget all those difficult technical parameters 

Basically a dropbox with 5 recommended simple ratio would be enough, other could be hidden with a toggle or xSlider:
![2023-11-08 11_56_15](https://github.com/lllyasviel/Fooocus/assets/7282547/06f048c6-8958-4b54-864f-71cc017ae1f1)

#181 #556 #740 #766 #882

**Comment by mashb1t** [comment]
Closing in favor of https://github.com/lllyasviel/Fooocus/issues/1339.
Preview of Aspect Ratios: https://github.com/lllyasviel/Fooocus/issues/1339
Preview of Styles: https://docs.google.com/spreadsheets/d/1AF5bd-fALxlu0lguZQiQVn1yZwxUiBJGyh2eyJJWl74 or https://github.com/lllyasviel/Fooocus/discussions/143
Preview of LoRas: too individual, this is specific to users and can not be handled in Fooocus. please refer to Civitai.com or similar platforms.
