### ISSUE TITLE
Can't follow a lot of text and famous people look weird

### ISSUE THREAD

**Issue by yorai1212** [lllyasviel/Fooocus#803]
I've used Fooocus for a few weeks now, and have a problem with it that keeps happening without knowing how to fix it.
Sometimes I have a really good prompt, I imagine in my head how it would look, but after the image generates it, it misses a lot of aspects and things I wrote. At times it can completely ignore 50% of the prompt, while the other half is prefect.

Another thing is with celebs and famous people. Their faces.
Their faces always just doesn't look like the actual celebrity, looks washed, tiny eyes or just altogether really not like how they actually look.
Going to Civitai, since most celebs LORAs are still not SDXL. And altogether this software is more focused on helped the use with no need to download anything extra or mess with any of the settings and such.

I might sound a bit rude, but that's just because I'm not a native speaker and I'm simply trying to write my experience with the program and maybe if someone can comment on ways they fixed the issue and such. Thank you!

**Comment by lllyasviel** [comment]
`Sometimes I have a really good prompt, I imagine in my head how it would look, but after the image generates it, it misses a lot of aspects and things I wrote`

yes this is a long-term problem. Some companies spend a lot of money to fix this. fooocus should be already the best ones in open source community. but if want a quick fix, when you write extremely long prompt, probably turn off all style and only turn on "Fooocus Negative" or "Fooocus Enhance"

**Comment by lanyusan** [comment]
@lllyasviel 

I noticed that Dalle 3 made some impressive progress in understanding and following prompts, for example the classic a horse riding a monkey problem. 

Do you think SD has any chances of catching up in near future? I think it will eventually catch up but I hope it won't take too long.

Thanks again for this great piece of software.

**Comment by mashb1t** [comment]
Yes, Fooocus is definitely ablew to catch up due to the nature of Open Source devleopment and the community working on LoRAs, which then can improve again image prompt precision for specific topics.
Closing as the original issue has been solved.
