### ISSUE TITLE
Can't create simple fighting scene image generation

### ISSUE THREAD

**Issue by putuoka** [lllyasviel/Fooocus#805]
bing/dalle-3 prompt: Kratos from God Of War fighting Anubis

result: 
![4s5xb5peaxwb1](https://github.com/lllyasviel/Fooocus/assets/20880839/fea7551a-e417-4a40-b82f-7834f966a476)

Fooocus result:

![image](https://github.com/lllyasviel/Fooocus/assets/20880839/4dba57f4-b922-4b4b-8438-3f14a2f12828)

**Comment by lllyasviel** [comment]
I can reproduce

`Kratos from God Of War fighting Anubis` is an interesting prompt and will fail all civitai models even in a1111

**Comment by putuoka** [comment]
[PixArt-Alpha](https://github.com/PixArt-alpha/PixArt-alpha) shows that fine-tuning on a dataset with highly detailed captions can lead to substantial quality improvements.

**Comment by mirek190** [comment]
@putuoka 
If you switch off Fooocusv2 ( gpt2 ) and Fooocus Enhance , Fooocus Sharp then you get quite good results 
and prompt "Kratos from God Of War fighting with Anubis"

![2023-10-29_19-51-50_1056](https://github.com/lllyasviel/Fooocus/assets/6817266/30046e42-c39f-43b0-b1d6-6235fef3fdbe)
![2023-10-29_19-55-57_2931](https://github.com/lllyasviel/Fooocus/assets/6817266/112a75af-077b-49ef-b744-c605773e6b67)

**Comment by lllyasviel** [comment]
2.1.755 fixed this recently

seed 31337
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/ea4fad7c-140f-4a17-89fc-859f41cb5b8c)
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/c545af0e-bfcc-462f-8217-c7cd4666657a)
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/5cd6a2fc-10c4-4bf5-be9d-23e24e352b74)

but it seems the "Fooocus sharp" a bit too strong
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/ac228a8a-77d3-4d2e-a53c-b2ed7a505e1e)

anyway will note this later if necessary

**Comment by putuoka** [comment]
@lllyasviel @mirek190 i tried in fooocus version 2.1.758 by turning off all style and installing wrong lora by @minimaxir (set weight to 1)

prompt: Kratos from God Of War fighting Anubis
seed: 6525586533838908778

no negative prompt

![image](https://github.com/lllyasviel/Fooocus/assets/20880839/70b690b2-10ec-418c-ba51-44bac5b3a0a9)
