### ISSUE TITLE
Upscale (2x) - Fooocus  2.1.757 ( base model - juggernautXL_version6Rundiffusion ) - loosing all details 

### ISSUE THREAD

**Issue by mirek190** [lllyasviel/Fooocus#814]
Look on the comparison pictures .... 

Upscale x2 removing all details from the picture now ...

original picture ( seed 1234 -  juggernautXL_version6Rundiffusion, "woman, street", base.bat
![2023-10-29_12-31-55_8220](https://github.com/lllyasviel/Fooocus/assets/6817266/a0a91213-9121-4a9f-b8a7-5e90fdd026f5)

Upscale x2  - looks like a wax.... all picture imperfections are removed from face , jacket, street , etc
![2023-10-29_12-34-45_8220](https://github.com/lllyasviel/Fooocus/assets/6817266/3d81c731-6e39-4a6b-b677-f00142cc0118)

**Comment by lllyasviel** [comment]
I believe the seed 1234 is this
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/85109829-84ed-46c8-9d46-e84456738383)

also, upscale with 2.1.757 using your image is this:
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/e5f237d6-401f-41e9-ba49-9c4429acf9c1)

both two images are different from your example so you may have  some installation problem, also there is no "base.bat". If that is the case, you can make another issue about inconsistent result.

besides, upscale using previous sdxl+refiner gives you this
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/3d77b0c8-2edc-4577-afcd-cb0bfedde6fe)

it depends but i dont any big difference larger than a different random seed

**Comment by mirek190** [comment]
With base sdxl and refiner looks similar after resize 2x but if I use  juggernautXL_version6Rundiffusion (new version fooocus) then upscale x2 I'm loosing details from the picture. 
Look on the street - is so smooth  or clothing or skin which is like a wax comparing to before resize. 
After resize it looks just bad now.

**Comment by mirek190** [comment]
I downloaded from beginning - still the same effect 
upscale x2 I'm loosing details from the picture.
Look on the street - is so smooth or clothing or skin which is like a wax comparing to before resize.
After resize it looks just bad now.


![ezgif-5-421f907161](https://github.com/lllyasviel/Fooocus/assets/6817266/75e13b2a-0d1a-40f1-af61-67c7d05848f1)

**Comment by lllyasviel** [comment]
`With base sdxl and refiner looks similar after resize 2x` what do you mean, any examples?

**Comment by mirek190** [comment]
> `With base sdxl and refiner looks similar after resize 2x` what do you mean, any examples?

I was wrong ... even base sdxl + refiner picture upscaled x2 also looks bad. 
Changing picture too much. 
Upscale alsor seems completely smooth skin which looks bad like wax.  


example   base sdxl + refiner , same prompt , same seed

![ezgif-5-7b16e191f2](https://github.com/lllyasviel/Fooocus/assets/6817266/c2d0ba2a-99a8-40f2-b6d9-aafb82c7950a)

**Comment by lllyasviel** [comment]
and you can still use sd1.5
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/bae7b428-593a-4290-a28f-7512ec6c46b1)
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/68356c08-cd58-464a-9731-0847f1bcc7c2)
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/7a693de2-9f22-47a4-91ff-9db0cf45592a)

**Comment by mirek190** [comment]
I setup like you suggested 

Have no idea why my picture is different than yours. 

![Screenshot 2023-10-29 193205](https://github.com/lllyasviel/Fooocus/assets/6817266/30226f69-1c5d-4e0f-acee-f33d2152f335) ![Screenshot 2023-10-29 193221](https://github.com/lllyasviel/Fooocus/assets/6817266/60fa8b83-7912-46e8-89c1-2c9d02ea8428)

But still upscale x2 looks very different also upscaled picture loosing a lot details and seems smoothed like before.

![ezgif-5-dc96b3c736](https://github.com/lllyasviel/Fooocus/assets/6817266/c30c6a0c-82f9-4e74-bfcc-ff5580b10424)

**Comment by 841372** [comment]
What to do 🤷
