### ISSUE TITLE
The progress bar cannot be completed

### ISSUE THREAD

**Issue by mmmz28** [lllyasviel/Fooocus#815]
This problem has been around ever since, and as the pictures below show, it comes up from time to time. Then I can only refresh the interface or restart the program and pray that the next generate doesn't have this problem.
![202310-c5fe7db797aaa11ebafaa6708a353833](https://github.com/lllyasviel/Fooocus/assets/58453940/bcd1508a-38ea-4bad-839c-2b50710d1511)
![202310-eacdf5a65af6ca69b01d3ef4e3e7e0a9](https://github.com/lllyasviel/Fooocus/assets/58453940/018f06ca-767d-4d75-bfbe-92e80ff8d5c5)

**Comment by lllyasviel** [comment]
In my opinion this may be related to gradio version because I also enconter similar problems recently.
I will probably try to change the gradio version recently

**Comment by lllyasviel** [comment]
well it seems that when I want to reproduce it, it never happens.
When i use it as normal, it happens sometimes. Stange

**Comment by lllyasviel** [comment]
well if someone know how to reproduce this please let me know.
I even tried chrome's simulated bad internet connection and still have no clue.
if someone has a hint that some older gradio can avoid this, I will downgrade gradio without any hesitation

**Comment by lllyasviel** [comment]
ok it seems gradio problem again
https://github.com/gradio-app/gradio/issues/3158
https://discuss.huggingface.co/t/issue-draggan-gradio-gets-stuck-in-loop-after-clicking-interactive-image-or-button/52698

**Comment by lllyasviel** [comment]
currently the solutuion is:

1. use it on local machine rather than remote server
2. if must use remote server, the internet should be good.
3. if the internet is bad, use --share

the it is almost okay, but I will keep eye on gradio

**Comment by mmmz28** [comment]
> currently the solutuion is:
> 
> 1. use it on local machine rather than remote server
> 2. if must use remote server, the internet should be good.
> 3. if the internet is bad, use --share
> 
> the it is almost okay, but I will keep eye on gradio

The second point solved my problem, because my network was really slow in the morning. After I realized the second point you mentioned, I fixed my network problem and then tested it a few times and the progress bar never stuck again! I get stuck almost every two times in the morning.
Thank you very much!
