### ISSUE TITLE
How to fix face & add adetailer in Fooocus?

### ISSUE THREAD

**Issue by putuoka** [lllyasviel/Fooocus#816]
Prompt: Utopian scene of humans working in harmony with AI
seed: 1616291126098141909
style: fooocusv2, fooocus enhanced, fooocus negative
lora: wrong lora by minimaxir, weight set to 1
model: juggernautxl v6
foocus version: 2.1.761

![image-1](https://github.com/lllyasviel/Fooocus/assets/20880839/1e6ca597-c9ef-4f73-a0b4-c7834898b1c6)

**Comment by mmmz28** [comment]
+1! As long as there is a small face will appear deformities. I think this is a problem worthy of attention.

**Comment by lllyasviel** [comment]
yes this is our next highest priority.

You can fix them in a1111 or comfyui but in my tests all current methods are extremely limited if you really try them. Local only-mask inpaint or any addetailer suffer from either global consistency loss, or style corruption from inpaint offset merge, or significant seams. and parameters are extremely difficult to find.

When Fooocus is going to solve this problem, we will give perfect solution that is better than all others, just like that the fooocus inpaint and image prompt is better than all current open-source alternatives.

**Comment by kubilaykilinc** [comment]
When I use fooocus upscaling 1.5 it still corrects the eyes. Not bad at all.

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/discussions/414#detail

**Comment by jnpatrick99** [comment]
Thanks for this one! Btw adetailer automatically detects and improves faces. I think Fooocus could benefit from such thing too. Will greatly improve rendering time (no need to additionally load/reload/inpaint/select/mask images).

**Comment by 2blackbar** [comment]
auto face detection with aligned face would be best ,its time consuming to fix the faces later and match the styles, better if its done during generation of the image in this gui
