### ISSUE TITLE
[Feature request] Style selection

### ISSUE THREAD

**Issue by PhilJbt** [lllyasviel/Fooocus#818]
As the list of _Styles_ is very long, and in order to facilitate the use of the appropriate style, even if the current version of the menu must remain to allow users to discover new styles, rethinking the menu would be very welcome.

I think an input text with autocomplete would do the trick in addition to the current selection system, with selected tags displayed at the top and unselected ones at the bottom. This way, finding a known style is facilitated, and discovering and selecting unknown styles is still possible.

![mockup_fooocus](https://github.com/lllyasviel/Fooocus/assets/22506952/7e854238-7477-47b3-855d-d1dd8fb45858)

**Comment by Ambratolm** [comment]
It would also be awesome to add thumbnail preview images for each style. something like those: [All 184 Styles in Fooocus with Images](https://github.com/lllyasviel/Fooocus/discussions/143).
![filter_thumb_styles](https://github.com/lllyasviel/Fooocus/assets/27871399/870cfda4-bb6a-44bd-9a0e-aa387c9fcc12)

**Comment by mashb1t** [comment]
Preview thumbnails have been added quite a while ago
