### ISSUE TITLE
Checkpoints.corrupted

### ISSUE THREAD

**Issue by thiner** [lllyasviel/Fooocus#821]
**Describe the problem**
The `models/checkpoints` folder is renamed to `models/checkpoints.corrupted` if I stop the process by `kill -9`. But the checkpoint files are all good in fact. Because it works by removing the suffix `corrupted` from the folder name.  I think this is a bug of model files verification.

**Comment by Novosti1** [comment]
same problem here ... any solution ?

**Comment by mashb1t** [comment]
Closing as stale, can't reproduce.
