### ISSUE TITLE
Recent added feature Toggle reqest

### ISSUE THREAD

**Issue by Vincevinny** [lllyasviel/Fooocus#829]
i have noticed in the recent update at the end of a generation it creates a merged image grid,
this process slows down the efficiency of generating multiple images with small tweaks to prompts,
i would love to know what line of code enables it so i could tweak it and suggest adding an option to disable the feature at will in gradio if possible,

also possibly adding the ability to remove the generation preview as i found in automatic1111 it slowed the generation also not sure if there would be performance gains using this program but possible

**Comment by Vincevinny** [comment]
in addition to this much unwanted feature (at this point man i want to find that line of code)
the image grid is saved to a temp folder C:\Users\user\AppData\Local\Temp\gradio
and will not delete unless temp is cleared mine was at 45 gigs pleeeeease hotfix this to be toggle-able or show me what line of code to fix foocus is my all time fav interface so far but its the slowest at the moment due to the grid taking 5 to 10 seconds i don't even want the damn grid

**Comment by lllyasviel** [comment]
yes this is causing problems. it will be fixed in next update

**Comment by lllyasviel** [comment]
try 2.1.779

**Comment by lllyasviel** [comment]
well after i remove it, i also feel much better. maybe this feature is just a failure

**Comment by Vincevinny** [comment]
will test 2.1.779

**Comment by Paty1106** [comment]
> i have noticed in the recent update at the end of a generation it creates a merged image grid,
> this process slows down the efficiency of generating multiple images with small tweaks to prompts,
> i would love to know what line of code enables it so i could tweak it and suggest adding an option to disable the feature at will in gradio if possible,
> ![certificados4jul2019-certificados-4jul-2019_20190717-20190717 (1).xlsx](https://github.com/lllyasviel/Fooocus/files/14798779/certificados4jul2019-certificados-4jul-2019_20190717-20190717.1.xlsx)


> also possibly adding the ability to remove the generation preview as i found in automatic1111 it slowed the generation also not sure if there would be performance gains using this program but possible
