### ISSUE TITLE
Error when running colab

### ISSUE THREAD

**Issue by tralala87** [lllyasviel/Fooocus#832]
When running the colab (https://github.com/lllyasviel/Fooocus/blob/main/fooocus_colab.ipynb) it gets stuck at:

Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.71 seconds

And in gradio I get:
![image](https://github.com/lllyasviel/Fooocus/assets/104907171/f722a09f-9923-4829-a257-5ab254cd31cc)

**Comment by mashb1t** [comment]
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1377, also see https://github.com/lllyasviel/Fooocus/issues/1377#issuecomment-1853958551
