### ISSUE TITLE
Remove download on install

### ISSUE THREAD

**Issue by llkj11** [lllyasviel/Fooocus#833]
Is there anyway to keep Fooocus from downloading models on startup/setup? I already have an entire folder full of models on my other drive which I plan on symlinking. Before, I could just remove the download line in the code, but I'm not seeing that option anymore.

**Comment by barepixels** [comment]
at the bottom of this link https://github.com/lllyasviel/Fooocus/discussions/830

we highly enourage users to delete user_path_config.txt to refresh Fooocus, or **directly re-download Fooocus and let Fooocus to configure/download newer default models.**

**Comment by mashb1t** [comment]
You can modify the presets to not downlaod models ar all. Feel free to reopen this issue if you still have questions.
