### ISSUE TITLE
Outpainting - blurry image & tone difference

### ISSUE THREAD

**Issue by kubilaykilinc** [lllyasviel/Fooocus#836]
When I use Outpainting (top, right, left, bottom), a blurry image with a lot of tone difference is created in the newly formed areas. I added the sample image.
I can write down all my fooocus settings if necessary.

![image](https://github.com/lllyasviel/Fooocus/assets/18080130/73b532f9-7f8b-4d9b-bcb5-afe16221b79f)

**Comment by lllyasviel** [comment]
?
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/8ee8d6d0-3e42-40b1-958f-fa56da3706ab)

**Comment by kubilaykilinc** [comment]
is this normal? How can i help? As far as I remember before the Fooocus updates, it was running more stable.
