### ISSUE TITLE
Image size cantt be set to the uploaded reference image causing cropping in the generated image in img2img

### ISSUE THREAD

**Issue by magekinnarus** [lllyasviel/Fooocus#843]
Hi, I find it very limiting when an image is uploaded to image input or used for Controlnet but the image size setting can't be set to the uploaded image which causes cropping in the generated image. Is there a way to set the image size that is aligned to a reference image in img2img?

**Comment by xhoxye** [comment]
because SDXL non-standard resolutions will produce a broken image, you can find a resolution of similar proportions to avoid too much cropping

**Comment by lllyasviel** [comment]
how you handle two images?

**Comment by mashb1t** [comment]
Closing the issue as stale. @magekinnarus feel free to reopen it again when providing more information.
