### ISSUE TITLE
HELP!!! How to fix an error - Error: Connection errored out

### ISSUE THREAD

**Issue by asd1231112** [lllyasviel/Fooocus#844]
How to fix an error - **Error: Connection errored out**? Really hoping for some help!
![USZBpBvKjIU](https://github.com/lllyasviel/Fooocus/assets/53057743/dc8398e5-2daa-4697-82d9-f30f786b371e)

**Comment by barepixels** [comment]
Look like Fooocus crashed.  Relaunch Fooocus

**Comment by asd1231112** [comment]
> Look like Fooocus crashed. Relaunch Fooocus

I have restarted and reinstalled several times, but have not identified the reason for the error

**Comment by TinyMikeG** [comment]
I have exactly the same issue and same error. Did you find a solution?

**Comment by mi-skam** [comment]
👍

**Comment by anteAutomate** [comment]
Same issue here

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
