### ISSUE TITLE
Solve the problem of Moving model before each build，BUG，Major discovery macOS

### ISSUE THREAD

**Issue by tiancool** [lllyasviel/Fooocus#849]
During the rendering process, if the user skips or stops, the next generation will not have a Moving model, which can improve efficiency. This BUG should be fixable.

[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] shot from selfie of a cute macaw, eiffeltower in the backgournd, cinematic, dramatic light, gorgeous, stunning, intricate, elegant, creative, extremely detailed, professional, innocent, inspired, charismatic, beautiful, futuristic, best, novel, epic, surreal, sharp focus, perfect composition, ambient, artistic, vivid colors, amazing, symmetry
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
Preparation time: 3.99 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.02916753850877285, sigma_max = 14.614643096923828
 70%|█████████████████████████████████████████████████▋                     | 7/10 [00:17<00:07,  2.46s/it]
User stopped
Total time: 21.36 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 3.0
[Parameters] Seed = 1940248585073695890
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 10 - 24
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] shot from selfie of a cute macaw, eiffeltower in the backgournd, epic professional, intricate, elegant, cinematic, directed, extremely detailed,,, innocent, artistic, sharp focus, inspired, stunning, pretty, inspiring, symmetry, amazing light, brilliant, perfect color, colors, shiny, glowing, rich deep complex strong detail, gorgeous
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
Preparation time: 3.98 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.02916753850877285, sigma_max = 14.614643096923828
100%|██████████████████████████████████████████████████████████████████████| 10/10 [00:22<00:00,  2.23s/it]
Image generated with private log at: /Users/XXX/Fooocus/outputs/2023-11-03/log.html
Generating and saving time: 25.16 seconds
Total time: 29.84 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 3.0
[Parameters] Seed = 2590971669623038202
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 10 - 24
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] shot from selfie of a cute macaw, eiffeltower in the backgournd, confident, bright glowing, professional directed, cinematic light, sharp focus, extremely detailed, clear, beautiful, aesthetic, innocent, fine detail, intricate, elegant, epic, joyful, scenic, artistic, thought, elite, decorated, vivid ambient background, polished, complex, wonderful
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
Preparation time: 4.67 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.02916753850877285, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 45.53 seconds
100%|██████████████████████████████████████████████████████████████████████| 10/10 [00:26<00:00,  2.66s/it]
Image generated with private log at: /Users/XXX/Fooocus/outputs/2023-11-03/log.html
Generating and saving time: 75.03 seconds
Total time: 80.37 seconds

**Comment by lllyasviel** [comment]
update to at least 2.1.775 and use `python entry_with_update.py --enable-smart-memory` to launch. See updated https://github.com/lllyasviel/Fooocus#mac

**Comment by tiancool** [comment]
After the update, add code effective, load from 30s, upgraded to 0.4s, a great contribution!
