### ISSUE TITLE
Drag-and-drop issue in Firefox

### ISSUE THREAD

**Issue by realmalikov** [lllyasviel/Fooocus#851]
Please fix drag-and-drop (and CNTRL + V) of images from a browser tab into Foocus in Firefox. Drag-and-drop from Windows into your app works perfectly.

I have some hope as it works in 1111 and that shares the Gradio interface with Fooocus.

**Comment by lllyasviel** [comment]
does a1111 drag work in firefox?

**Comment by realmalikov** [comment]
> does a1111 drag work in firefox?

Yes. 

Around the time of the Windows 22H2 update, I was really surprised that I could hardly use drag-and-drop in Firefox. In the meantime, many websites have fixed this, but some, like replicate, unfortunately not.

**Comment by artofbeinghuman** [comment]
drag and drop not working on 120.0 (64-bit), macos

**Comment by mashb1t** [comment]
Superseded, closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1425
