### ISSUE TITLE
Fooocus error with really long prompt

### ISSUE THREAD

**Issue by putuoka** [lllyasviel/Fooocus#852]
`<(best quality, extremery best quality, masterpiece:1.4), (realistic, intricate details:1.4), (photorealistic:1.4), (extremely intricate:1.4), highres, ultra highres, ultra detailed, ultra-detailed, absurdres, incredibly absurdres, extremely detailed, high quality, high resolution, hyperrealistic, ultra-realistic, hyper-detailed, top quality, best, fine detail, massive detail, Highly detailed, extreme detailed, highest detailed, high-res, absolutely resolution, reflection, (refraction:1.4), (hyperrealism:1.4)>, BREAK, (1girl:1.3), solo, looking at viewer, (young cute beautiful 18-year-old girl:1.4), 3d face, (hand of Guido Daniele:1.4), beautiful girl, Beautiful face, pretty, girlface, kpop idol,  supermodel, stunning innocent symmetry face, perfect body, medium breast, slim waist, slim legs, (high detailed skin:1.5), glowing eyes, goddess, natural skin texture, shiny skin, White skin, Beautiful detailed face, detailed face, real skin texture, cute delicate face, finely detailed face, golden ratio, golden ratio face, expressive eyes, perfect face, perfect skin, flawless face, clear face, shiny hair, pale skin, Proper body proportion, perfect anatomy, realistic skin texture, luscious lips, glossy lips, natural makeup, beautiful bright pupils, slender figure, intricate eyes, detailed pupils, detailed face and eyes, longeyelashes, blush, good hand, perfect hands, pretty face, beautiful female bodies, finely detailed skin, oily shiny skin, clean facial features, an extremely delicate and beautiful, cute & girly, beautiful detailed eyes, stars in the eyes, detailed simmetric eyes, perfect smooth skin texture, BREAK, (((((standing, (zanhua, holding flower, Pink flower on head:1.4), (smile, Pink hair, Pink eye, long hair, Pink eyelashes, Pink lips, Pink lip colour, Eyes glowing Pink, flat bangs, wearing hanfu, in Pink and white, happy expression, bird, lotus, hair ornament, water, dancing with butterfly, hanfu_tang, tang dynasty, chinese traditional architecture, in the garden, floral background, brilliant colors, wearing Tang-style clothing, flowing sleeves, floral pattern, golden bracelets, pearl earrings, long_hair, nail_polish, jewelry, ancient art, chinese style, golden embroidery, ornate hairpin, jade accessories, standing in imperial palace, red pillars, golden details, intricate carvings, decorative screens, sparkling jewels, ruqun, rich Chinese red, golden decorations, exquisite screens, golden dragon-patterned wallpaper, Pink silk curtains, delicate porcelain, Pink flower decorations, Pink carpets, mooth curved bridge, blue sky and green water:1.5), (night, Night time, moon light, sky, landscape, aurora borealis, stars, outdoors, Chinese, Pink fireworks, Sakura tree background:1.4), (lake background, mountains, full moon background, night lake shore, river, forest, chinese style countryard, lanterns, pond,  cobblestone pathway,   building pavilion, chinese buildings, moutains, misty lake, ancient chinese background, puddle, after the rain, petals falling, wet grass and trees, flower sea, in a meadow, waterfall, breeze, flying splashes, flying petals, leaves, bloom, bloom effect, surrounded by heavy floating petal flow, petal, Pink butterfly, flower, detailed beautiful grassland with petal, flowers, plants, Pink rose, many Pink roses, leaves falling from the tree, dust is drifting, ethereal, scenery, nature, mysterious background:1.4), (iridescent colors, Iridescence, blush, mysterious, fantasy background, fantasy, open mouth:1.2), (fog, wind:1.2), (Luminescent Particles:1.3), (fullbody:1.2), (eye focus, face focus, character focus, close-up face:1.2), (dutch angle, cowboy shot:1.3), colorful refraction)))), BREAK, <watercolor, available light, detailed light,  volumetric fog,  beautiful lighting,  Rembrandt lighting,  Cinematic, pixel art,  game art,  key visual,  surreal,   PBR Texturing,   Anisotropic Filtering, Maximum Clarity And Sharpness, Albedo And Specular Maps, Multi-Layered Textures, Surface Shading, Sub-Pixel Convolution,  Sub-Pixel Convolution,  Accurate Simulation Of Light-Material Interaction, blurry foreground, broad light, volumetric light effect, matte painting, perfectly defined features, volumetric lighting, Tone Mapping, Lumen Reflections, Global illumination, Ray Tracing, Screen Space Global Illumination, Accent Lighting, 32k, Natural Lighting, volumetric, cinematic masterpiece, Rule of thirds, high dynamic range, Multi-exposure HDR capture, cinematic render, game cg cinematic, atmospheric perspective, movie scene, epic dynamic frame, motion blur, ((cinematic look, Film look)), rim light, 4k textures, adobe lightroom, photolab, insane details, hyperdetailed, exposure blend, professional color grading, professional color correction, aerial perspective, particles and dust in beams of light, cinematic scene, dynamic lighting, sharp details, lomography, soft focus, light leaks, bold hues, atmospheric depth, (explosive light and shadow:1.2), aesthetics, intricate designs, ultra realistic digital art, (zentangle, mandala, tangle, entangle), (fractal art), elegant, vivid colours, floating particles, particles, dramatic, epic, (ink drawing, oil painting detailed), (dramatic lighting:1.2), RAW, huge filesize, extremery detailed CG, Photo, 8k uhd, cinematic atmosphere, trending on artstation, award-winning glamour photograph, highly detailed photo, official art, beautiful and aesthetic, unity 8k wallpaper, beautiful, highly detailed CG illustration, best illustration, intricate, Amazing, emotional, analog, painting, digital painting, concept art, Oil Painting, illustration, Classical art, Renaissance, Romanticism, Neoclassicism, Color Palette, depth and contrast, Vibrant colors, saturated, rich saturation, color harmony, vivid palette, concept-art, design style, detail character, concept render, colorful, analog photography, dreamy atmosphere, specular highlights, atmospheric lighting, (dynamic angle, dynamic pose :1.3), (shiny, clothes reflecting light, lens flare, bloom effect, light particle, lens glare:1.3), realistic lighting, cinematic light, (cinematic lighting), light in the face, soft lighting, saturated colors, detailed background, sharp focus, 8k high definition, perspective, Master Composition, roughness, post-processing, soft shadows, realistic shadows, ambient occlusion, ray-tracing, subsurface scattering, photon mapping, physically-based rendering, octane rendering, unreal engine 5, ue5 rendering, Adobe After FX, dslr, RTX, Best character details, radiosity, sharp, antialiased, RAW photo, HDR, 8k, 4k, (((Photographed by Roger Deakins, using a RED Monstro 8K VV camera and a series of high-end lenses))), ((Hasselblad photography)), (film grain:1.4), Kodak portra 400, ((Fujifilm X-T5)), professional photograph, depth of field, caustics, Broad lighting, diffuse lighting, rim lighting, two tone lighting, textile details, visible pores, high resolution scan, professionally color graded, photographic reality, automatic white balance, best lighting, detailed shadow, high contrast, strong light and shadow>`

**Comment by mashb1t** [comment]
What is the actual error?
Please provide the full terminal output so we're able to check the issue.
Also make sure you're using the latest version of Fooocus.

**Comment by mashb1t** [comment]
Closing as stale, feel free to reopen when providing new information.
