### ISSUE TITLE
Inpainting seems still unable to reliably put new objects in image

### ISSUE THREAD

**Issue by lanyusan** [lllyasviel/Fooocus#853]
I have been trying to add some kois to this product poster concept image. But it is only able to generate images with kois 1 out of 5 tries.

![image](https://github.com/lllyasviel/Fooocus/assets/56706512/41fab619-6704-4b45-914d-861638d0020e)

**Comment by lllyasviel** [comment]
which inpaint engine

**Comment by vikmaks1** [comment]
The problem persists with both 1.0 and 2.5 engines, it was pointed out before in the issue [#720 ](https://github.com/lllyasviel/Fooocus/issues/720#issuecomment-1789681159 ) and is still present with the current Fooocus version.

**Comment by lanyusan** [comment]
> which inpaint engine
The default engine.

**Comment by jryebread** [comment]
same problem here, sometimes none of the outputs have added what was defined in the prompt, 

I did notice the larger the mask the more likely it will add to the img

**Comment by raLaaaa** [comment]
Can confirm. Same issue. Especially with a really tiny mask.

**Comment by mashb1t** [comment]
Please test again with the latest version of Fooocus, especially with inpaint method "Modify Content (add objects, change background, etc.)", anbd let us know the results.

**Comment by raLaaaa** [comment]
@mashb1t - offtopic: what is the best way to update on windows? Download links still link to version 2-1-831. 
Thanks for the effort.

**Comment by mashb1t** [comment]
@raLaaaa Fooocus does a self-update every time you run entry_with_update.py (run.bat also uses this as the entrypoint), so no need to manually update if you do not actively develop based on Fooocus code.
If you're a developer using 2 remotes and merge upstream to your main branch works.

**Comment by raLaaaa** [comment]
For me "Modify Content (add objects, change background, etc.)" seems to work way better.
