### ISSUE TITLE
loading model becomes very slow suddently

### ISSUE THREAD

**Issue by bigupbaby** [lllyasviel/Fooocus#854]
Hi

I was generating image on my 24G RAM / 6G VRAM (GTX 1660Ti) and i get not bad results as ~250s (not as good as announced, i don't know why?)

And suddently models are loading very very slow and I can get an image after ~800s or ~900s, and my D: data disk (not SSD) is almost always 100% busy

To resolve this,I have tried many things and i have found one solution, that is desactivate virtual memory on my  D: data disk (not SSD) and activate virtual memory only on C: system disk (SSD), i get good result like ~250s 

But I don't understand why Fooocus suddently slow, some ideas ?

**Comment by mirek190** [comment]
Your pc is hardly capable to work with SDXL ... 250s to generate picture ... no comment .
Probably increasing vram usage by Fooous even +100 MB will data not fit fully in your Vram ... or maybe your system is using more vram or something lately ...you have to check how much vram you have occupied before run Fooous.

**Comment by lllyasviel** [comment]
hi, this is expected that fooocus will always use swap and please try to use SSD for swap area.
Also the newer config uses less ram. If you are not on the newer config, you can delete 'user_path_config.txt' and run again to get newer config (and latest default model(s)).
If you already on latest configs, then the only method is to try to use SSD for swap area.
Also please let us know if A1111 or ComfyUI can handle your device better (for sdxl).
