### ISSUE TITLE
Ctrl+上下键调节提示词权重

### ISSUE THREAD

**Issue by kenic123** [lllyasviel/Fooocus#855]
在Fooocus上能否增加调节提示词权重的便捷方式？
在WebUI或ComfyUI中使用Ctrl+上下键调节提示词权重非常好用，只需选中需要增加权重的某(几)个词，再按下Ctrl+上下箭头就可以按0.1(或其它更小的数值)的梯度增减，非常方便。

**Comment by lllyasviel** [comment]
solved in 2.1.777

**Comment by kenic123** [comment]
大佬神速！！
