### ISSUE TITLE
Feature Request: Metadata

### ISSUE THREAD

**Issue by blackpro98** [lllyasviel/Fooocus#86]
Hi, I love the simple that is generate a image but I noticed that the images generated doesn't include the metadata in the image itself.

**Comment by p21nc3** [comment]
Working on it 😊

**Comment by harrr1** [comment]
Seems like a duplicate of #38

**Comment by KrX3D** [comment]
it would also be nice after this is added to be able to load those information from an image

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/issues/125
