### ISSUE TITLE
A Bug of input_image['mask']

### ISSUE THREAD

**Issue by diaolulu1** [lllyasviel/Fooocus#870]
**Describe the problem**
When I select an image and draw a mask in Inpaint or Outpaint, check Mixing Image Prompt and Inpaint in the developer options, and select an image from Image Prompt, I return to the Inpaint or Outpaint interface, and clicking the Generate button will cause an error. I must click on the mask to restore it to work. Every time I switch to Image Prompt and switch back, I need to click on the mask to get it back to work.

**Full Console Log**
File "I:\Fooocus\Fooocus\modules\async_worker.py", line 649, in worker
    handler(task)
  File "I:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "I:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "I:\Fooocus\Fooocus\modules\async_worker.py", line 222, in handler
    inpaint_mask = inpaint_input_image['mask'][:, :, 0]
TypeError: 'NoneType' object is not subscriptable

**Comment by diaolulu1** [comment]
I have noticed that even if I do not select the option "Mixing Image Prompt and Inpaint", the mask still cannot be stored as soon as I switch tabs. Please fix this.

**Comment by lllyasviel** [comment]
try 2.1.778

**Comment by stubkan** [comment]
This is the same problem reported here in my issue report #817

**Comment by Elbingerr** [comment]
Fooocus Inpaint or outpaint option, stopped working even though the prompt entry area was selected - nothing happens

**Comment by mashb1t** [comment]
@diaolulu1 @Ramsello are you using the latest version of Fooocus? Please test again and let us know the result.

**Comment by mashb1t** [comment]
Closing as stale, feel free to reopen when providing new information. Thanks!
