### ISSUE TITLE
auto-update malfunction?

### ISSUE THREAD

**Issue by SmartestArtist** [lllyasviel/Fooocus#874]
Fooocus was running great for me. Then one day, I don't know if it tried to update itself or what, but I noticed that inside the Fooocus folder, in addition to the run file it also had a run_anime and a run_realistic file as well. Now, when I run double click on the run file as I used to or either of the others, the console window opens but the browser with the Fooocus interface does not open and nothing else happens. Maybe it was an auto-update malfunction?  How can I get this running again? 

BTW, you can see a video I made of artwork (while it was still running) here:

https://youtu.be/r6hzhWaekck?si=9w7hIrRPxsfzAnuj

**Comment by lllyasviel** [comment]
maybe it is some other software blocking your browser. Can you run.bat and try http://127.0.0.1:7860
also please paste or screenshot the content in the console

**Comment by SmartestArtist** [comment]
Thanks, I wasn't able to load http://127.0.0.1:7860/

Attached is the screenshot
![C__WINDOWS_system32_cmd exe 11_6_2023 8_11_44 PM](https://github.com/lllyasviel/Fooocus/assets/110261511/29f2bd76-7778-4af3-91b7-2f44cef41f4b)

**Comment by ycyy** [comment]
it is look 

> Thanks, I wasn't able to load http://127.0.0.1:7860/谢谢，我无法加载 http://127.0.0.1:7860/
> 
> Attached is the screenshot附上截图 ![C__WINDOWS_system32_cmd exe 11_6_2023 8_11_44 PM](https://user-images.githubusercontent.com/110261511/280899180-29f2bd76-7778-4af3-91b7-2f44cef41f4b.png)

It seems like a network issue, and you are unable to download files from Hugging Face.
