### ISSUE TITLE
Fooocus在初次运行时下载不了文件，显示“由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。”

### ISSUE THREAD

**Issue by CCC197** [lllyasviel/Fooocus#875]
![微信图片_20231106114935](https://github.com/lllyasviel/Fooocus/assets/149988515/a1e2e8a0-f27b-4ebe-9fe7-d5f4f3a295d7)

**Comment by ycyy** [comment]
over the gfw you will see success.

**Comment by CCC197** [comment]
> 在GFW上，你会看到成功。
我已经关闭了防火墙，不会还需要翻墙才能成功下载吧

**Comment by ycyy** [comment]
> > 在GFW上，你会看到成功。
> > 我已经关闭了防火墙，不会还需要翻墙才能成功下载吧

your are right

**Comment by diaolulu1** [comment]
这个是因为你没有科学网络，无法下载抱脸上的模型，可以翻墙下载，或者去我的百度网盘下载，里面有分享，B站搜索刁璐璐

**Comment by CCC197** [comment]
> 这个是因为你没有科学网络，无法下载抱脸上的模型，可以翻墙下载，或者去我的百度网盘下载，里面有分享，B站搜索刁璐璐

谢谢

**Comment by favouriter** [comment]
这些模型能不能上传[魔塔社区](https://modelscope.cn/models)，魔塔社区对中国人比较友好，可以满载下载

**Comment by Qchacha** [comment]
> 这个是因为你没有科学网络，无法下载抱脸上的模型，可以翻墙下载，或者去我的百度网盘下载，里面有分享，B站搜索刁璐璐

老师  是B站上的哪个视频
