### ISSUE TITLE
Masks from Photoshop or anything inpaint.

### ISSUE THREAD

**Issue by diaolulu1** [lllyasviel/Fooocus#879]
**Describe the idea you'd like**
I hope that inpaint can import masks from Photoshop or anything inpaint, and also hope to support the skeleton diagram of OpenPose.

**Comment by mashb1t** [comment]
Implementation in https://github.com/lllyasviel/Fooocus/pull/1126

**Comment by mashb1t** [comment]
this has been merged in https://github.com/lllyasviel/Fooocus/pull/1645
