### ISSUE TITLE
Outpainting blurry and tone difference problem

### ISSUE THREAD

**Issue by kubilaykilinc** [lllyasviel/Fooocus#880]
If I use an SD 1.5 model as a refiner; When outpainting, the newly formed areas are blurred and have obvious tone differences. I had a similar observation before. This time I detected the problem. I guess this is a bug.
If I only use the SDXL model and do not use an SD 1.5 model as a refiner, such a problem does not occur. Vesa occurs in extremely small amounts. I present 2 different images here.

1- Outpainting with (SDXL model + SD 1.5 model as refiner)

![image](https://github.com/lllyasviel/Fooocus/assets/18080130/72a8005e-370e-480b-864e-9e6ae30736a9)

2. Outpainting with only SDXL model

![image](https://github.com/lllyasviel/Fooocus/assets/18080130/c80d00b5-20fa-4d11-9cfd-5867c3c8874d)

**Comment by mashb1t** [comment]
Please confirm this still exists in the latest version of Fooocus and reopen the issue if it does. Thanks!
