### ISSUE TITLE
Add aspect ratio to resolution selection

### ISSUE THREAD

**Issue by GuidoBartoli** [lllyasviel/Fooocus#882]
**Is your feature request related to a problem? Please describe.**
It would be helpful to have the corresponding aspect ratio alongside each resolution so that you don't have to calculate it by hand.

**Describe the idea you'd like**
In the screenshot below, for example, it would be `704x1408 (1:2)`, `704x1344 (11:21)`, `768x1344 (4:7)`, `768x1280 (3:5)`, and so on...
![Screenshot from 2023-11-07 09-42-07](https://github.com/lllyasviel/Fooocus/assets/16103676/4e1c33a6-0324-4cb9-a306-26f0789387f2)

**Comment by xhoxye** [comment]
可以自行在翻译文档中修改
![QQ截图20231107202010](https://github.com/lllyasviel/Fooocus/assets/129571231/bf3dbabd-456e-4403-8617-a553c0c91cb9)
![QQ截图20231107201945](https://github.com/lllyasviel/Fooocus/assets/129571231/690831fc-ff30-40d7-b23f-1754576b899b)

**Comment by GuidoBartoli** [comment]
> You can modify it yourself in the translated document
Thanks for pointing it out, this is a workaround that can work, but I think it would be better if it will be part of the official code 😉

**Comment by xhoxye** [comment]
the Translating document requires you to use a command to start referencing

**Comment by GuidoBartoli** [comment]
> the Translating document requires you to use a command to start referencing
> 
> For practical translation, you may create your own file like Fooocus/language/jp.json 或 Fooocus/language/cn.json and then use flag --language jp 或 --language cn.
> 
> Note that if no --language is given and at the same time Fooocus/language/default.json exists, Fooocus will always load Fooocus/language/default.json for translation. By default, the file Fooocus/language/default.json does not exist.

Ok, thanks.

**Comment by GuidoBartoli** [comment]
I saw my suggestion implemented in the latest Fooocus version, many thanks! 😀
