### ISSUE TITLE
IPAdapter weight implementation doesn't seem compatible with GNU  GPLv3 License

### ISSUE THREAD

**Issue by cubiq** [lllyasviel/Fooocus#884]
I refer to: https://github.com/lllyasviel/Fooocus/blob/5e8a77fdac0a8c9438dca7ff2f771e2ce4c8c8dd/fooocus_extras/ip_adapter.py#L225

I don't think this can be distributed in a [GNU GPLv3](https://github.com/lllyasviel/Fooocus/blob/main/LICENSE) licensed software. I would like a clarification if the code could be used in another free and GPL3 software (which implies dropping the non-commercial clause).

**Comment by mashb1t** [comment]
Does not exist anymore in the latest Fooocus version, closing the issue.

**Comment by Laurent2916** [comment]
It's still there:
https://github.com/lllyasviel/Fooocus/blob/1bcbd6501bb3e5db5674a18a8a8074034cda318b/extras/ip_adapter.py#L228-L234
