### ISSUE TITLE
Total VRAM 12288 MB, total RAM 65457 MB

### ISSUE THREAD

**Issue by BomjRU** [lllyasviel/Fooocus#886]
Device: cuda:0 NVIDIA GeForce RTX 2060 12GB

It's not a mistake! How can I make the program use all the memory (VRAM)?

The program is very good! Thank you!

**Comment by mashb1t** [comment]
Please check https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md if you should still have issues with the latest version of Fooocus.

**Comment by mashb1t** [comment]
using `--always-high-vram` should help boost model loading time on consecutive runs a bit
