### ISSUE TITLE
The upscale models function is broken and performs poorly on macOS

### ISSUE THREAD

**Issue by tiancool** [lllyasviel/Fooocus#889]
This speed is unacceptable, I don't know if I did something wrong.

[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.02916753850877285, sigma_max = 0.5801899433135986
sh: PowerShell: command not found
 10%|█████▍                                                | 2/20 [01:26<12:17, 40.96s/it]

**Comment by alexsmedile** [comment]
For me it’s crashing almost every try during 2x up scalers.
Seems memory error or limit. MacMini M1 16GB

**Comment by mashb1t** [comment]
Please test again with the latest version of Fooocus, as back in the time where you checked it there was somehow PowerShell involved.
Feel free to reopen if there are still issues.
