### ISSUE TITLE
same seed, different results

### ISSUE THREAD

**Issue by RodTDai** [lllyasviel/Fooocus#890]
Hey.

I'm sending the exact same parameters with same seed (just a minute apart), and results differ! Looks like not obeying the seed..
in history i can see everything is identical, but the image.

What is happening?

thanks.

**Comment by LIQUIDMIND111** [comment]
same sh.. different day...

seems natural..... :D

**Comment by mashb1t** [comment]
The sstyle "Fooocus V2" uses a fine-tuned GPT2 model locally, which provides a different prompt extension for every image to be generated. Please deactivate it to generate recreatable results or use the meta copy feature in the history log.
