### ISSUE TITLE
LIVE IMAGE PREVIEW: Is there a way to DISABLE?

### ISSUE THREAD

**Issue by LIQUIDMIND111** [lllyasviel/Fooocus#895]
**Is your feature request related to a problem? Please describe.**

On low GPU VRAM, REAL TIME IMAGE PREVIEW makes it even slower, on automatic1111 you can disable LIVE preview and just get the RESULT at the end, saving lots of speed and VRAM.....

Is there a way to change the USER FILE or settings into disabling the live preview for people like me that have 6gpu VRAM? I had issues generating image and the fooocus changed to LOW VRAM automatically, and i believe image preview disable might help and just get the result......

**Describe the idea you'd like**

Requested to load SDXL
Loading 1 new model
**loading in lowvram mode 3098.916015625**
[Fooocus Model Management] Moving model(s) has taken 13.18 seconds

**Comment by LIQUIDMIND111** [comment]
also, where do i control the STEPS?

**Comment by LIQUIDMIND111** [comment]
@lllyasviel I MADE THIS ART FOR YOU :D 

![2023-11-09_15-08-46_4266](https://github.com/lllyasviel/Fooocus/assets/112510084/b7a03dfc-2bbc-4f1e-ac5f-22503b287afc)

**Comment by lllyasviel** [comment]
added in 2.1.819 dev tools

**Comment by LIQUIDMIND111** [comment]
> added in 2.1.819 dev tools

yes thanks.
