### ISSUE TITLE
🦒 colab

### ISSUE THREAD

**Issue by camenduru** [lllyasviel/Fooocus#9]
Thanks for the project ❤️ I made a colab. 🥳 I hope you like it. https://github.com/camenduru/Fooocus-colab

**Comment by lianghongli2** [comment]
good job，thanks
![Fooocus 1 0 22 和另外 4 个页面 - 个人 - Microsoft​ Edge 2023_8_13 18_37_53](https://github.com/lllyasviel/Fooocus/assets/6234601/81e485d6-0611-4257-98c2-ed04c09ba5f1)

**Comment by amida47** [comment]
You really did a great job, I tried doing myself before checking the issues tab, the app works but somehow when running a generation the whole 15gb of VRAM gets eaten up real fast and the colab restarts after exhausting all the available RAM, I have seen this same problem with all the models from huggingface lately (example https://discuss.huggingface.co/t/colab-ram-limit-exceeded-unable-to-run-3b-model-even-with-quantization/50022, have a look if you can please), I don't know how you get these model to run, but anyway thank you.

**Comment by lllyasviel** [comment]
thanks! added official version

**Comment by lianghongli2** [comment]
![梁鸿利 2023_8_14 10_07_16 Page-1](https://github.com/lllyasviel/Fooocus/assets/6234601/8fcb54c5-cafa-4db0-b2e2-20e78b563322)
![梁鸿利 2023_8_14 10_17_24 Page-1](https://github.com/lllyasviel/Fooocus/assets/6234601/9c6b2dad-11ea-4f53-ac2f-0421f5caece1)
![梁鸿利 2023_8_14 10_26_22 Page-1](https://github.com/lllyasviel/Fooocus/assets/6234601/3614a586-ee0a-4ce0-b74a-b08fe39df609)
![梁鸿利 2023_8_14 10_28_51 Page-1](https://github.com/lllyasviel/Fooocus/assets/6234601/adacfeed-7478-4e0c-8bf1-d7df8be8a11e)
![梁鸿利 2023_8_14 10_32_43 Page-1](https://github.com/lllyasviel/Fooocus/assets/6234601/36415de5-acef-49ed-b590-d391a061ff9e)
![梁鸿利 2023_8_14 10_42_24 Page-1](https://github.com/lllyasviel/Fooocus/assets/6234601/ee08302c-eb22-4ffb-a379-26cfe8472b19)
![梁鸿利 2023_8_14 10_45_35 Page-1](https://github.com/lllyasviel/Fooocus/assets/6234601/c59fe085-2a28-43cd-8c8a-efa1bb80faef)

**Comment by lianghongli2** [comment]
It does not run successfully every time. If the panel address in the fourth step does not appear, you need to re-run the colab file. If it fails many times, please confirm that the t4 gpu and other account permissions are enabled. Don't pull the warehouse from github, run it directly, you can make a copy of the configuration file, but don't pull it, I don't know why, but when I do this, the file will fail to run. Thanks again to the author of fooocus and the author of the colab file, thank you! !

**Comment by lllyasviel** [comment]
@lianghongli2 hi you are using the old colab - if you use the new official one on the Readme, this problem is already solved

**Comment by camenduru** [comment]
Let's close this issue and continue with the official colab 🥳
