### ISSUE TITLE
Connection errored out

### ISSUE THREAD

**Issue by Epidot3** [lllyasviel/Fooocus#900]
I get an error when I try to make an image. Doesn't matter what the input is.
It says Error, connection errorerd out

Here is the log:

C:\Users\jonas\OneDrive\Desktop>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.780
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total VRAM 4096 MB, total RAM 8060 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
Set vram state to: LOW_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce GTX 1650 : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE

C:\Users\jonas\OneDrive\Desktop>pause
Press any key to continue . . .

**Comment by Mydong** [comment]
### I got an error. I don't know what's going on. I re-downloaded it and overwrote it, but it doesn't work.

```
F:\S.sd-Fooocus\Fooocus_win64>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Fast-forward merge
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.808
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 8188 MB, total RAM 32508 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
```

**Comment by Dawson-Petersen** [comment]
I have the same issue, maybe it's because of the low vram?

**Comment by prime0x2** [comment]
I'm facing exact same issue. I'm using 4GB VRAM (1050 TI) and i5-7300HQ. 

Any solution?

**Comment by cashea** [comment]
Same issue here.  I believe it may be a Stable Diffusion issue, as the same problem is occurring within my Automatic1111 instance.

**Comment by Ragnarok700** [comment]
Another batch of us have reported that issue here #1112 and one more here #1258

**Comment by Ragnarok700** [comment]
> I’m having the same issue. I’m using a Mac Studio with M1 Ultra.

Good to know it's not only on Windows platforms.

**Comment by Dawson-Petersen** [comment]
Hi All, 

There's a solution here. See the section on system swap. I set my paging file to initial size 10gb and max size 40gb and it's working for me now (albeit, quite slow). 

 https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
