### ISSUE TITLE
Take a random element from curly braces with a separator as in comfyUI

### ISSUE THREAD

**Issue by Evgen2194** [lllyasviel/Fooocus#901]
In comfiYUAI I can specify in the prompt “woman, {white hair|black hair|yellow hair}” and click generate 10 images. Then I will get a random result with one of three hair colors. This would be convenient for people like me who don’t know exactly what they want to get. A warrior with an ax or a sword or a bow, an ax and so on.

**Comment by lllyasviel** [comment]
woman, \_\_color\_\_ hair

**Comment by LIQUIDMIND111** [comment]
> woman, __color__ hair

hello how do i activate xformers on foocus?

**Comment by LIQUIDMIND111** [comment]
> woman, __color__ hair

do i need to create a VENV folder?

**Comment by Evgen2194** [comment]
> woman, __color__ hair

Yes, thank you, it happened that way, but what other words can be used in this way? Or what file can I look at and edit to add my own color to the “color”, or add my own word with my own examples with which this word could be replaced?

**Comment by mashb1t** [comment]
The current implementatiom will take random elements from all of the lines in a given wildcards file. If you only want to use specific wildcards, please create a new file with only these elements.
You can also generate one image for each of some elements by using the code of this PR: https://github.com/lllyasviel/Fooocus/pull/1503
