### ISSUE TITLE
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}

### ISSUE THREAD

**Issue by LIQUIDMIND111** [lllyasviel/Fooocus#902]
**Describe the problem**
WHEN LOADING

missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}

**Full Console Log**
To create a public link, set `share=True` in `launch()`.
Total VRAM 6144 MB, total RAM 16302 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 2060 : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: C:\TEMP\FOCUS\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors
LoRAs loaded: [('SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 0.25), ('None', 0.25), ('None', 0.25), ('None', 0.25), ('None', 0.25)]
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 1.81 seconds
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860

**Comment by lllyasviel** [comment]
This is not error. but removed in 2.1.789
