### ISSUE TITLE
Fooocus Inpaint or outpaint option stopped working

### ISSUE THREAD

**Issue by Elbingerr** [lllyasviel/Fooocus#903]
Fooocus Inpaint or outpaint option stopped working even though the prompt entry area was selected - nothing happens.

**Comment by stubkan** [comment]
There will not be much help available if we only know 1 sentence from you.  Please include full console log and explain exactly what you were doing, then it will be easy to help.

**Comment by Elbingerr** [comment]
Thank you for the quick answer, after changing the Google account, the function started working - if the problem reoccurs, I will send the console log, etc. I work using Google Colab and it was not due to disconnection from the GPU

**Comment by stubkan** [comment]
Next time it stops working, try re-clicking the mask area before you click Generate, or making sure the image prompt you are using is jpg format.

**Comment by xythonix** [comment]
it start loading, and stuck just hangs up after 2 or 3 seconds, using jpg, png both

**Comment by xythonix** [comment]
how to use actually image inpaint or outpaint, should I uncheck advanced option. what should I do

**Comment by lllyasviel** [comment]
@xythonix you may take a look at https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
to find out which type of hang it is, then it does not fix, open an new issue

**Comment by xythonix** [comment]
> Next time it stops working, try re-clicking the mask area before you click Generate, or making sure the image prompt you are using is jpg format.

I use Colab, prompt is clear. I select image from pc, upload in inpaint, image input is clear, i use face clear in dropdown.i mask on eyes of girl photo, and clicks on generate button. It starts to load, after sometime, it stops working, and skip and stop button comes for a while and then again generate button comes, not clearing picture glitches, solve this issue!

**Comment by mashb1t** [comment]
Most likely your RAM is exhausted, which might be why your process is cancelled. Please check and consider upgrading your Colab plan if this should be the issue.

See https://github.com/lllyasviel/Fooocus/issues/1330, https://github.com/lllyasviel/Fooocus/issues/1574, https://github.com/lllyasviel/Fooocus/issues/1558#issuecomment-1868166226

Inpainting and outpainting both work with the latest release of Fooocus both on local computer and in Colab (Paid).
Closing this issue for now, feel free to reopen if you have further questions.
