### ISSUE TITLE
Scheduler "LCM" missing in v2.1.785

### ISSUE THREAD

**Issue by Remember2015** [lllyasviel/Fooocus#905]
**Describe the problem**

Hi, in Fooocus 2.1.785, I can not find scheduler "LCM" out, but in update_log.md, it says:

> "Users can use it by setting the scheduler as 'LCM' and setting the forced overwrite of step as 4 to 8 in dev tools. "

**Full Console Log**
No log, but i had screenshot:

![image](https://github.com/lllyasviel/Fooocus/assets/575884/b7dea2d6-67ab-4adc-a06e-78ee551eb296)

Thanks~

**Comment by lllyasviel** [comment]
it is typo and should be sampler
fixed in https://github.com/lllyasviel/Fooocus/commit/7632d752e0a854107d4d4ddf6241227377ab8d68
