### ISSUE TITLE
All of a sudden

### ISSUE THREAD

**Issue by Sirmadsen** [lllyasviel/Fooocus#910]
Ran Fooocus perfectly fine yesterday, today it resets Every time I start. Not reading user_path_config and constantly resetting config.txt when I make changes to it. No direct error message other than;

"
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\entry_with_update.py']
Processing deprecated config failed
Invalid \escape: line 11 column 29 (char 940)
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec 6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.789
Running on local URL: http://127.0.0.1:7860/
"

I haven't done anything different from yesterday more than literally going to bed.

**Comment by xhoxye** [comment]
user_path_config has been deprecated

**Comment by Sirmadsen** [comment]
"""and constantly resetting config.txt when I make changes to it."""

**Comment by lllyasviel** [comment]
paste the content of modified file?
maybe it is a mistake in json grammar?

**Comment by Sirmadsen** [comment]
Might have been a grammar mistake. Copied the entire backup of my user_path_config into config.txt and double checked everything, now it works. Thanks for pointing it out.
