### ISSUE TITLE
missing clip vision: ['vision_model.embeddings.position_ids']

### ISSUE THREAD

**Issue by kubilaykilinc** [lllyasviel/Fooocus#916]
I am using Fooocus v 2.1.791 update. I updated it without any problems.
However, when I used image prompts > face swap for the first time, after loading the necessary models, I saw the following message in the command panel.

Isn't it a bug or not? I don't know. I wanted to share.

-----------------------------------------------------------------------------------------

[Fooocus] Downloading control models ...
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/ip-adapter-plus-face_sdxl_vit-h.bin" to E:\SD-AI\Fooocus\Fooocus\models\controlnet\ip-adapter-plus-face_sdxl_vit-h.bin

100%|███████████████████████████████████████████████████████████████████████████████| 967M/967M [04:49<00:00, 3.50MB/s]
[Fooocus] Loading control models ...
missing clip vision: ['vision_model.embeddings.position_ids']

-----------------------------------------------------------------------------------------

It is very good that you use the ip adapter face plus sdxl for FaceSwap.
I am extremely pleased with this. It's the best tool for what I want to do. However, it does not give an ending like Reactor, which does very realistic face changing. I wanted to let you know.

But I think the IP adapter solution is more important. Thank you very much.

**Comment by lllyasviel** [comment]
this is already resolved in 792
