### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by woliuha** [lllyasviel/Fooocus#92]
Expecting value: line 1 column 1 (char 0)

**Comment by 15215517964** [comment]
same error

**Comment by 15215517964** [comment]
> Expecting value: line 1 column 1 (char 0)

Shut down the network proxy software

**Comment by woshitoutouge** [comment]
same error and the solution worked. Is there another way?

> > Expecting value: line 1 column 1 (char 0)
> 
> Shut down the network proxy software

**Comment by crytion111** [comment]
> > Expecting value: line 1 column 1 (char 0)
> 
> Shut down the network proxy software

Shut down [Clash for Windows] will resolve

**Comment by Huanxin0722** [comment]
> 
Unable to connect after closing. How to solve it?
![图片](https://github.com/lllyasviel/Fooocus/assets/142834042/c618ca24-6d04-4780-80cc-5491133df1d3)

**Comment by KarrenZhang** [comment]
> > 
> 
> Unable to connect after closing. How to solve it? ![图片](https://user-images.githubusercontent.com/142834042/262117269-c618ca24-6d04-4780-80cc-5491133df1d3.png)

I have same error

**Comment by bakerken** [comment]
I'm running on linux, I don't have any network proxying, yet am getting the same error.

**Comment by SDfangrui** [comment]
我的代理软件是V2RAY，更新软件版本，然后清除系统代理，问题就解决了

**Comment by Mlic0** [comment]
> In SD WebUI, add "set COMMANDLINE_ARGS=--no-gradio-queue" in webui.bat can solve this problem, but I can't find where to add this in Fooocus

Can you tell me exactly in which file and where to enter this code? Thank you.
