### ISSUE TITLE
Request to add a selector button for auto update or manual update. I still want to use the old version

### ISSUE THREAD

**Issue by lijie5555698** [lllyasviel/Fooocus#922]
Request to add an opportunity to automatically update or manually update options. Updated version 791 to 793 this evening. Persosellyt g nerates clearer images than the 793. Because of sd_xl_base_1.0_0.9vae.safetensors and the refinir sdj-xl_RNEFIX_version6Rundiffusion, does not have a refiner and generates poorly and is not clear. Am I not usong i  corlattly please? Or need to change to another templately please? Or need to change to another templately please? Or need to change to another template

**Comment by lijie5555698** [comment]
Another question. I have a 4060TI 16g nvidia graphics card and it takes 20 minutes and 30 images to generate quality images. If I use fast it also takes 20 minutes. It takes longer, is there any way to make the generation time faster, shorter and more time saving out of the pictures. Love you, mwahahaha!

**Comment by lllyasviel** [comment]
hi you can change model in `advanced->model`
or change default model using [the config](https://github.com/lllyasviel/Fooocus#customization)

**Comment by lllyasviel** [comment]
hi some old presets are restored in 2.1.814 https://github.com/lllyasviel/Fooocus/commit/8c49bb1cba2e60c9e3a885b7ea927fdcd291bdc7
one can modify the bat file to `--preset sdxl` to use it

**Comment by ycyy** [comment]
if you don't want update,you can edit `run.bat`  like this
```
.\python_embeded\python.exe -s Fooocus\lunanch.py
pause
```
