### ISSUE TITLE
Add LCM support for SSD-1B model

### ISSUE THREAD

**Issue by UmutHasanoglu** [lllyasviel/Fooocus#924]
Hi. When I try to execute Extreme Speed with SSD-1B model, it automatically takes the sdx_lcm lora but there is also a lora for ssd-1b model. Can you add this feature?

LCM for SSD-1B: https://huggingface.co/latent-consistency/lcm-ssd-1b

**Comment by UmutHasanoglu** [comment]
I manage to use it by changing the settings in developer debug mode, but it would be awesome to do automatically.

**Comment by raphatbho** [comment]
> I manage to use it by changing the settings in developer debug mode, but it would be awesome to do automatically.

Can you please tell us how you did that? Or maybe point to a place where this is explained. LCM with SSD-1B would be great!

**Comment by UmutHasanoglu** [comment]
Just open Developer Debug Mode -> Debug tools,
Change:
CFG scale to 1 to 2
Forced Overwrite of Sampling Step to 8
Sampler -> any sampler that works well with SSD-1B
Then:
Open model folder
Select SSD-1B Model checkpoint
Select SSD-1B LCM LoRa
Adjust the weight


> > I manage to use it by changing the settings in developer debug mode, but it would be awesome to do automatically.
> 
> Can you please tell us how you did that? Or maybe point to a place where this is explained. LCM with SSD-1B would be great!

**Comment by mashb1t** [comment]
You can translate your changes into a preset. I also did this exact same procedure for DreamShaper SDXL Turbo, see https://github.com/lllyasviel/Fooocus/pull/1580

**Comment by mashb1t** [comment]
Presets for SSD: see https://github.com/lllyasviel/Fooocus/discussions/1869 / https://github.com/lllyasviel/Fooocus/discussions/1888
