### ISSUE TITLE
Blurry output issue after v 2.1.799 update

### ISSUE THREAD

**Issue by kubilaykilinc** [lllyasviel/Fooocus#925]
After the latest update, which added LCM schedule support and Extreme speed, when i use quality mode the images I produced started to become extremely blurry. Prior to these updates, the images were very sharp and high quality in the exact same production process (I tested this up to the seed number), but now they are extremely blurry.

I also make a special setting in developer debug mode called "Forced Overwrite of Sampling Step." I can set this to 80 or 200, for example. When I use this setting, the time after 60 is counted as waste during production. The image does not actually continue sampling after 60.

I have encountered a strange bug, but this is all I can tell you at this time.

**Comment by lllyasviel** [comment]
show example

**Comment by kubilaykilinc** [comment]
There is also another problem. Maybe it could be related to this. In the past, when the Sharpness value was changed, the image would remain faithful and only the details would be enriched. Now, when the sharpness value changes, significant changes occur in the image.

**For Example :**
Positive Prompt : 1girl
Negative prompt : None (empty)
Performance : Quality
Seed: 0
Guidance scale : 7.1
CFG Mimicking from TSNR : 7
Freeu : Enabled

**Sharpness : 2**

![image](https://github.com/lllyasviel/Fooocus/assets/18080130/caa9508f-5b71-4228-9656-afbcb4545b3b)

Same settings
**Sharpness : 15**
![image](https://github.com/lllyasviel/Fooocus/assets/18080130/b8004cae-3a17-45dc-ad28-05d02ee693af)

Sometimes the images are very blurry, sometimes they are not so blurry. but before this latest update they were very sharp.

**Comment by kubilaykilinc** [comment]
![image](https://github.com/lllyasviel/Fooocus/assets/18080130/d4527a13-b8c1-4978-9f28-90de40ffaa87)

![image](https://github.com/lllyasviel/Fooocus/assets/18080130/0f74bb47-08f5-4994-8538-c80edc670349)

![image](https://github.com/lllyasviel/Fooocus/assets/18080130/e1003a7b-81b6-4d80-9326-3ae90e81268e)

**Comment by lllyasviel** [comment]
I tested 774 (b95c7378c9b2c08c6f41079a93c04308475de424)  vs 800 (ac8002d2a43080052289e4a16bd23cd50d9c367c) with quality mode
results are same
give paramters that can show differences

**Comment by kubilaykilinc** [comment]
Hmmm i will test somethings more deeply. If i can not any problems. I will delete this thread.
But what about sharpness issue? ( i wrote too about this)

**Comment by lllyasviel** [comment]
the Sharpness 2 vs 15 example looks expected
2 and 15 are large difference and changing small object like hair is possible

**Comment by kubilaykilinc** [comment]
I revisited some of my previous work using identical seeds, parameters, and models. The results remained consistent, indicating no underlying issues. I apologize for consuming your time, but I don't intend to express any dissatisfaction. I'm immensely grateful to be a part of this remarkable endeavor. It's as if I'm witnessing history unfold before me. Whenever I encounter any problems, I strive to provide my assistance. I'll now proceed to delete this thread. My apologies for any inconvenience caused.
