### ISSUE TITLE
Please consider standardizing the Foocus.zip to a constant name and path

### ISSUE THREAD

**Issue by SoftologyPro** [lllyasviel/Fooocus#929]
This will help standardize the update batch file I use.  With the zip name/path changing so often it constantly breaks the install.  Right now, any time you update and change zip names users complain "Fooocus install doesn't work again 404".  Leave the release page and doc versions as is, just use Foocus.zip for the zip name (or FooocusLatest.zip)?

**Comment by AndrewBabbitt97** [comment]
Updates are already pulled when running `run.bat`

If you really need to do updates using the latest release on GitHub you should really be querying the GitHub API: https://api.github.com/repos/lllyasviel/Fooocus/releases/latest

This will also ensure you are always using the latest release

**Comment by SoftologyPro** [comment]
OK, I know updates are checked each run.  But (for example) when you changed the zip to  Fooocus_win64_2-1-791.7z it killed the update script I use for users.

I will check out the API though, thanks for the pointer.

**Comment by AndrewBabbitt97** [comment]
You could use Powershell to work with JSON + make API calls if needed, or if you want to just use batch you could always bundle curl and jq together with the file and pipe the result of curl into jq to pull just the zip file similar to what you could do with bash.

Just some ideas 😁

**Comment by AndrewBabbitt97** [comment]
Also for the powershell route you can do this to get the download url:

```batch
powershell -command "(((Invoke-WebRequest -URI https://api.github.com/repos/lllyasviel/Fooocus/releases/latest).Content | ConvertFrom-Json).assets | where -Property name -like Fooocus_win64_*.7z).browser_download_url"
```

**Comment by SoftologyPro** [comment]
> Here's a solution using batch to fetch the URL using powershell and storing it in a batch variable for you:
> 
> ```batchfile
> @echo off
> for /f "delims=" %%a in ('powershell -command "(((Invoke-WebRequest -URI https://api.github.com/repos/lllyasviel/Fooocus/releases/latest).Content | ConvertFrom-Json).assets | Where -Property name -Like Fooocus_win64_*.7z).browser_download_url"') do Set "FOOOCUS_DOWNLOAD_URL=%%a"
> 
> echo %FOOOCUS_DOWNLOAD_URL%
> 
> pause
> ```

Excellent.  Thanks!
