### ISSUE TITLE
Presets only support one LoRA

### ISSUE THREAD

**Issue by AndrewBabbitt97** [lllyasviel/Fooocus#931]
**Is your feature request related to a problem? Please describe.**
Presets only allow setting one LoRA, when Fooocus supports 5 LoRA's. Presets also allow setting multiple LoRA downloads but not using more than one of them.

**Describe the idea you'd like**
Support the ability to set multiple LoRA's and their weights with presets.

**Comment by simmichj** [comment]
Can confirm, I have not been able to add a second LoRA to a custom preset.

**Comment by lllyasviel** [comment]
multiple loras in preset is in 2.1.815
but the presets need to change, see also the newer preset files
https://github.com/lllyasviel/Fooocus/commit/3a9c3c07d17163e793915d042c61d3b5aec64f1d
