### ISSUE TITLE
Faceswap not applying style

### ISSUE THREAD

**Issue by lanyusan** [lllyasviel/Fooocus#934]
The new faceswap is amazing. I have played with it for a while. It can even change facial expression.

But I found out styles wouldn't be applied. It can only generate photo like images. It makes it much less useful.

Please find the screenshot.

![image](https://github.com/lllyasviel/Fooocus/assets/56706512/50889b20-6dfd-4bfc-8c15-9518beac33e1)

**Comment by xiaohu2015** [comment]
for current version, you can only reduce the image weight to change style or use style base model.

**Comment by lanyusan** [comment]
> for current version, you can only reduce the image weight to change style or use style base model.

Yes I have noticed that as well.

Does the weight affect how much the new image follows the original photo's face structure or the original photo's style or both?

I have tested it a couple of times and it looks it affects styles only.

**Comment by mashb1t** [comment]
The lower your weight for input image is, the more the original image is take into account.
