### ISSUE TITLE
Each time run.bat is run, the config.txt file is overwritten

### ISSUE THREAD

**Issue by alexssamara63** [lllyasviel/Fooocus#935]
Each time run.bat is run, the config.txt file is overwritten. It is impossible to save paths to your folders

**Comment by lllyasviel** [comment]
use \\\\ , not \\

**Comment by alexssamara63** [comment]
I use \\ . This is not the problem - I run bat and the config.txt file is overwritten with the default one

**Comment by alexssamara63** [comment]
I need the paths to the models in ComfyUI to be specified so as not to copy them

**Comment by alexssamara63** [comment]
I found an error - my fault - there were extra characters in the new file. The config should contain ONLY PATHS!
