### ISSUE TITLE
LCM Extreme Speed is skipping Negative prompt, correct?

### ISSUE THREAD

**Issue by gjakuipers** [lllyasviel/Fooocus#936]
LCM Extreme Speed  is skipping Negative prompt

[Fooocus] Encoding positive
[Fooocus] Skipped negative .

**Comment by rubenmejiac** [comment]
Confirmed, negative prompts skipped when LCM selected.
...
[Fooocus] Encoding positive
[Fooocus] Skipped negative
...

**Comment by frankyifei** [comment]
while cfg is 1.0, negative prompt is skipped, so it also doubles the inferencing speed.

**Comment by rubenmejiac** [comment]
With newer updates, negative prompts in LCM (Extreme Speed) mode are still ignored, but no longer showing in the console output. 
In one of the recent revisions the console output showed 'Skipped negative',and effectively the actual negative prompt was ignored.
Negative prompts work as usual and expected in Speed and Quality modes.

**_Speed mode:_**
[Fooocus] Processing prompts ...
[Wildcards] processing: __pprompts__
[Wildcards] The Alamo
[Wildcards] processing: __pprompts__
[Wildcards] a horse reading a book
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
**[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...**
Preparation time: 2.28 seconds

**_Extreme Speed:_**
[Fooocus] Processing prompts ...
[Wildcards] processing: __pprompts__
[Wildcards] The Alamo
[Wildcards] processing: __pprompts__
[Wildcards] a horse reading a book
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
Preparation time: 0.20 seconds
Using lcm scheduler.

Speed mode:
positive prompt: a horse reading a book
negative prompt: (((bokeh)))
![2023-11-15_11-13-37_5090](https://github.com/lllyasviel/Fooocus/assets/20344715/26c5933b-37eb-4008-8d66-f2dd9f5963bf)

Extreme speed mode:
positive prompt: a horse reading a book
negative prompt: (((bokeh)))
![2023-11-15_11-12-22_8523](https://github.com/lllyasviel/Fooocus/assets/20344715/35cc4b01-e74d-4068-a006-be8255011219)
