### ISSUE TITLE
TensorRT

### ISSUE THREAD

**Issue by UmutHasanoglu** [lllyasviel/Fooocus#941]
I know it's not easy but is there a change that you add TensorRT support for Fooocus?

**Comment by kubilaykilinc** [comment]
My opinion, we do not need TensorRT anymore.
after LCM sampling and LCM scheduler

**Comment by RodTDai** [comment]
> My opinion, we do not need TensorRT anymore. after LCM sampling and LCM scheduler

yes, we need it. They are different things

**Comment by mashb1t** [comment]
Duplicate of https://github.com/lllyasviel/Fooocus/issues/897

**Comment by mashb1t** [comment]
> My opinion, we do not need TensorRT anymore. after LCM sampling and LCM scheduler

btw to spice things up there also is SDXL Turbo now (https://github.com/lllyasviel/Fooocus/pull/1580)
