### ISSUE TITLE
Inpainting: bad result on single color background, which severely impairs inpainting's power for designers

### ISSUE THREAD

**Issue by lanyusan** [lllyasviel/Fooocus#945]
I have been trying to use Fooocus inpainting to accelerate design prototyping. One use case is to use inpainting to draw images on a unfolded coffee cup for packaging designs.

The unfolded base image of coffee cup is as below, which has pure white background.
![wang-1](https://github.com/lllyasviel/Fooocus/assets/56706512/765db09b-b3f9-462c-a9e5-366ff7e09309)

Current inpainting output is very much influenced by existing pxiels under inpainting mask. In this case, the pixels are all white.

I wish Fooocus has this parameter that sets influence of existing pixels on inpainting, which would make it a great tool for product poster designers or packaging designers, who often need to inpaint on single color background.

![image](https://github.com/lllyasviel/Fooocus/assets/56706512/31238dfa-6e0c-43a6-8357-ffebd5326875)

**Comment by lanyusan** [comment]
Or maybe can add a paste mode that pastes generated images' mask area to the base image.

**Comment by xhoxye** [comment]
You can try using a png with alpha channel transparency

**Comment by mashb1t** [comment]
Would this be solved by using the inpaint mask features https://github.com/lllyasviel/Fooocus/pull/529 or https://github.com/lllyasviel/Fooocus/pull/1645?

**Comment by mashb1t** [comment]
@jonathanmiser9 @lanyusan bump

**Comment by mashb1t** [comment]
Closing as stale, feel free to reopen when providing new information.
