### ISSUE TITLE
NSFW filter

### ISSUE THREAD

**Issue by Xerxemi** [lllyasviel/Fooocus#950]
**Is your feature request related to a problem? Please describe.**

I'm currently setting up an event for a school and I'd ideally like to have some extra insurance. An NSFW filter would be useful just in case anything pops up (I don't want to get sued ;).

**Describe the idea you'd like**

NSFW filter, equivalent to that in diffusers / other webuis.

**Comment by mashb1t** [comment]
@Xerxemi please check out my up-to-date fork including an NSFW filter, whoch is activatable via config.
https://github.com/mashb1t/Fooocus

**Comment by tiancool** [comment]
> @Xerxemi please check out my up-to-date fork including an NSFW filter, whoch is activatable via config. https://github.com/mashb1t/Fooocus

How did you do it? I didn't see the NSFW filter in your configuration file

**Comment by mashb1t** [comment]
@tiancool i copied the censor code from https://github.com/AUTOMATIC1111/stable-diffusion-webui-nsfw-censor/blob/master/scripts/censor.py
and modified it, see https://github.com/mashb1t/Fooocus/blob/main/modules/censor.py

**Comment by tiancool** [comment]
I hope the author can consider making it a checkbox, in the advanced settings, to enable or disable

**Comment by mashb1t** [comment]
@Nebhg this is a checker, so feel free to negate the condition.
To get more NSFW images i'd propose to use a negative prompt with "sfw" and increase its weight to a suitable amount.

**Comment by daniellambert95** [comment]
@Nebhg I'm a bit confused, is it possible to generate NSFW images with Fooocus? Can you please explain how I can do this if it possible?

**Comment by mashb1t** [comment]
@daniellambert95 in general, you can generate everything in Fooocus and are not limited. What limits you is the capability of the model, e.g. SDXL Base doesn't have an extensive amount of nudity in its training dataset but is capable of it when fine tuning a model via Dreambooth or a LoRA/LyCORIS/Locon/Loha etc.
You can find a comparison here: 
![image](https://github.com/lllyasviel/Fooocus/assets/9307310/981e13a3-2707-4d30-93c6-e8a977f7a7e3)

**Comment by daniellambert95** [comment]
@mashb1t thanks for the information. I'm a bit of a noob to all this, could you recommend a place to start learning how to implementing/fine-tuning these models?

**Comment by Nebhg** [comment]
@mashb1t When training the fine tuned mode is the text embedding vital in the model understanding new words?

**Comment by Nebhg** [comment]
> @Nebhg I'm a bit confused, is it possible to generate NSFW images with Fooocus? Can you please explain how I can do this if it possible?

it is but as mashbit mentioned it wasn't trained on NSFW images so it doesn't produce good quality images

**Comment by mashb1t** [comment]
@daniellambert95 a potential starting point would be the tutorials section here: https://github.com/bmaltais/kohya_ss#tutorials
Please be advised that fine-tuning models is resource-intensive, so a LoRA is probably a better way for you to start.

@Nebhg for LoRAs it's mandatory to train keywords in order for the adjustments to take full effect. I've never trained a model via Dreambooth but i assume you also have to describe the content you tune, but you can also use CLIP/BLIP auto captioning via kohys_ss.

Hope this helps and all the best!

**Comment by mashb1t** [comment]
> I hope the author can consider making it a checkbox, in the advanced settings, to enable or disable

@tiancool the checkbox has also been added a few days ago in https://github.com/lllyasviel/Fooocus/pull/958, so you can set it in config and UI. It will do censoring if one of both is true.

**Comment by Amit30swgoh** [comment]
> Is there an opposite for this to ensure the model generates NSFW images?

Not sure how to do it

**Comment by mashb1t** [comment]
> @Nebhg this is a checker, so feel free to negate the condition. To get more NSFW images i'd propose to use a negative prompt with "sfw" and increase its weight to a suitable amount and/or to use a model fine-tuned for NSFW generation.

using a LoRA or a specific NSFW model would be your best option if adding "nsfw" to positive and "sfw" to negative prompt doesn't work for you.

**Comment by Amit30swgoh** [comment]
> > @Nebhg this is a checker, so feel free to negate the condition. To get more NSFW images i'd propose to use a negative prompt with "sfw" and increase its weight to a suitable amount and/or to use a model fine-tuned for NSFW generation.
> 
> using a LoRA or a specific NSFW model would be your best option if adding "nsfw" to positive and "sfw" to negative prompt doesn't work for you.

Can i upload to the colab gradio notebook turbo preset?
I dont know how to upload and when to run because if i execite the python update so all the files data change .
Also if i change do i need to close the public gradio?

**Comment by mashb1t** [comment]
https://github.com/lllyasviel/Fooocus/pull/958/ has just been merged to develop
