### ISSUE TITLE
Nvidia older driver

### ISSUE THREAD

**Issue by zz64** [lllyasviel/Fooocus#953]
Hi,
I would like to know if it is easy for someone to post us a tutorial to make the application work with the old Nvidia drivers.
```RuntimeError: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.```

NVIDIA Corporation GF108M [GeForce GT 540M] (nvidia-legacy-390xx-driver)
Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz 4 core 8 thread.
16Gb of RAM
Debian GNU/Linux bookworm (12.2)
Kernel Linux-6.1.0-13

I tried to do a search, but all I found was this:
https://github.com/pytorch/pytorch/issues/4546

Thanks.

**Comment by mirek190** [comment]
You are serious?
If you want to play with AI is time to upgrade ....

**Comment by LyazS** [comment]
this is my info, still said that old driver. u can just go to `lauch.py` and command the line where install torch, and reinstall torch manually.
![image](https://github.com/lllyasviel/Fooocus/assets/21286540/0d73782f-4cdd-4e4e-b733-8f6b67dac9f7)

**Comment by zz64** [comment]
thanks @LyazS for reply.

installed manually using:
```
pip install torch==1.13.0 torchvision==0.1.6 -f https://download.pytorch.org/whl/cu90/torch_stable.html
```
```
moi@develz ~/src/Fooocus $ ~/miniconda3/bin/conda list |egrep 'cuda|torch'
cuda90                    1.0                  h6433d27_0    pytorch
ffmpeg                    4.3                  hf484d3e_0    pytorch
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
pytorch                   2.1.1              py3.11_cpu_0    pytorch
pytorch-mutex             1.0                         cpu    pytorch
torchvision               0.16.1                py311_cpu    pytorch
```
but it still doesn't work :-(

i think latest Fooocus version (master) not work with cuda90.
any one confirm ?

Thanks.

**Comment by zz64** [comment]
launching Fooocus:
```
python launch.py --listen
[System ARGV] ['launch.py', '--listen']
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
Fooocus version: 2.1.820
Running on local URL:  http://0.0.0.0:7865

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/moi/src/Fooocus/modules/async_worker.py", line 20, in worker
    import modules.default_pipeline as pipeline
  File "/home/moi/src/Fooocus/modules/default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "/home/moi/src/Fooocus/modules/core.py", line 1, in <module>
    from modules.patch import patch_all
  File "/home/moi/src/Fooocus/modules/patch.py", line 4, in <module>
    import fcbh.model_base
  File "/home/moi/src/Fooocus/backend/headless/fcbh/model_base.py", line 2, in <module>
    from fcbh.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "/home/moi/src/Fooocus/backend/headless/fcbh/ldm/modules/diffusionmodules/openaimodel.py", line 16, in <module>
    from ..attention import SpatialTransformer
  File "/home/moi/src/Fooocus/backend/headless/fcbh/ldm/modules/attention.py", line 10, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/home/moi/src/Fooocus/backend/headless/fcbh/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from fcbh import model_management
  File "/home/moi/src/Fooocus/backend/headless/fcbh/model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/moi/src/Fooocus/backend/headless/fcbh/model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moi/.local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 552, in current_device
    _lazy_init()
  File "/home/moi/.local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
```

**Comment by hdnminh** [comment]
The same here.
**RuntimeError: The NVIDIA driver on your system is too old (found version 10010).** Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver


I’ve checked that:
nvcc --version: 11.3.1
nvidia-smi:
+ CUDA version: 10.1
+ CUDA driver: 418.87.01


With nnunet v2, they need pytorch >= 2.0
With nnunet v1 (1.7), they need torch ≥1.10. However, pytorch 1.10.1 wasn’t built with CUDA 10.1, but 10.2 as well as 11.3, [here](https://discuss.pytorch.org/t/pip-refuses-to-install-torch-with-gpu/142243/9#:~:text=1.10.1%20wasn%E2%80%99t%20built%20with%20CUDA%2010.1%2C%20but%2010.2%20as%20well%20as%2011.3.)

**Comment by zz64** [comment]
Hi @gwz7784,
Nop, I gave up )-:
I think you need to have python 3.6 up to 3.7 to be able to install the torch 1.1.0 binary.
_PyTorch only supports CUDA 9.0 up to 1.1.0._ 
And, I'm not even sure that Fooocus will be compatible with python 3.6 and torch 1.1.0.
https://varhowto.com/install-pytorch-cuda-9-0/

we didn't get an answer here, probably because the developers of Fooocus are very busy with other things more important than giving priority to people who keep their old equipment.

They did a good job, I congratulate them enormously. (-:

**Comment by mirek190** [comment]
> Hi @gwz7784, Nop, I gave up )-: I think you need to have python 3.6 up to 3.7 to be able to install the torch 1.1.0 binary. _PyTorch only supports CUDA 9.0 up to 1.1.0._ And, I'm not even sure that Fooocus will be compatible with python 3.6 and torch 1.1.0. https://varhowto.com/install-pytorch-cuda-9-0/
> 
> we didn't get an answer here, probably because the developers of Fooocus are very busy with other things more important than giving priority to people who keep their old equipment.
> 
> They did a good job, I congratulate them enormously. (-:

Yep ...
Apart from that such old graphics cards won't be faster that using CPU for it ....

**Comment by mashb1t** [comment]
Sorry to say but you need Python = 3.10, CUDA >= 11.X (11.8 known working) and torch >= 2.1.0 . Also see https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#nvidia-driver-too-old
Time to upgrade your driver or your hardware.

![PcMasterRaceGamingGIF](https://github.com/lllyasviel/Fooocus/assets/9307310/28340672-46b6-4af2-b4bc-112742db1089)
