### ISSUE TITLE
Better Style Selector

### ISSUE THREAD

**Issue by GuidoBartoli** [lllyasviel/Fooocus#954]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when selecting and enabling multiple styles, because I have to scroll a long list to find a needed style and also understand which are currently selected.

**Describe the idea you'd like**
A possible solution is to implement something similar to the Automatic1111 style selector, where styles can be directly searched with text and the selected ones are displayed all together in the text field.
![stable-diffusion-webui](https://github.com/lllyasviel/Fooocus/assets/16103676/c37b1a47-9edc-4832-b318-520e2b880908)

A big plus would also be able to have styles grouped by category (camera, color, artist, ...) or type (fooocus, diva, mre, sai, ...) in a way similar to EasyDiffusion UI.
![Easy-Diffusion_3](https://github.com/lllyasviel/Fooocus/assets/16103676/f4726d59-0752-4d65-983e-b5078a53a2b3)

**Comment by lllyasviel** [comment]
search is added recently since 2.1.81X

**Comment by GuidoBartoli** [comment]
> search is added recently since 2.1.81X

Found it now after updating, thanks!
Hoping for the other suggestions to be implemented, too... keep up the great work!
