### ISSUE TITLE
Negative prompts ignored when LCM (Extreme Speed) is selected.

### ISSUE THREAD

**Issue by rubenmejiac** [lllyasviel/Fooocus#957]
Confirmed, negative prompts skipped when LCM selected.
...
[Fooocus] Encoding positive
[Fooocus] Skipped negative
...

_Originally posted by @rubenmejiac in https://github.com/lllyasviel/Fooocus/issues/936#issuecomment-1811153510_

**Comment by rubenmejiac** [comment]
With newer updates, negative prompts in LCM (Extreme Speed) mode are still ignored, but no longer showing in the console output.
In one of the recent revisions the console output showed 'Skipped negative',and effectively the actual negative prompt was ignored.
Negative prompts work as usual and expected in Speed and Quality modes.

Speed mode:
[Fooocus] Processing prompts ...
[Wildcards] processing: pprompts
[Wildcards] The Alamo
[Wildcards] processing: pprompts
[Wildcards] a horse reading a book
[Fooocus] Encoding positive https://github.com/lllyasviel/Fooocus/discussions/1 ...
[Fooocus] Encoding positive https://github.com/lllyasviel/Fooocus/issues/2 ...
[Fooocus] Encoding negative https://github.com/lllyasviel/Fooocus/discussions/1 ...
[Fooocus] Encoding negative https://github.com/lllyasviel/Fooocus/issues/2 ...
Preparation time: 2.28 seconds

Extreme Speed:
[Fooocus] Processing prompts ...
[Wildcards] processing: pprompts
[Wildcards] The Alamo
[Wildcards] processing: pprompts
[Wildcards] a horse reading a book
[Fooocus] Encoding positive https://github.com/lllyasviel/Fooocus/discussions/1 ...
[Fooocus] Encoding positive https://github.com/lllyasviel/Fooocus/issues/2 ...
Preparation time: 0.20 seconds
Using lcm scheduler.

Speed mode:
positive prompt: a horse reading a book
negative prompt: (((bokeh)))
![2023-11-15_11-13-37_5090](https://github.com/lllyasviel/Fooocus/assets/20344715/34ae0a68-4037-440d-94d1-bcae7e5218c7)

Extreme speed mode:
positive prompt: a horse reading a book
negative prompt: (((bokeh)))
![2023-11-15_11-12-22_8523](https://github.com/lllyasviel/Fooocus/assets/20344715/1836815b-09af-42af-897f-96bcf22586ac)

**Comment by mashb1t** [comment]
LCM does not allow negative prompts. In the latest version of Fooocus the negative prompt input along other options is also disabled if LCM is selected.
