### ISSUE TITLE
Is it possible to support --disable-cuda-malloc?

### ISSUE THREAD

**Issue by shawnwu2022** [lllyasviel/Fooocus#96]
`RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
`

**Comment by rhurta** [comment]
I did it the dirty way: 
Commented the line `cuda_malloc()` from `launch.py`

**Comment by lllyasviel** [comment]
it is removed in the lastest version

**Comment by Digital-Driftwood** [comment]
Very nice, thank you!
