### ISSUE TITLE
First question: could you add a selector button for whether to let the user update or not.Clarity is still bad. It's very unclear.

### ISSUE THREAD

**Issue by lijie5555698** [lllyasviel/Fooocus#962]
First question: could you add a selector button for whether to let the user update or not.

I admire and love the speed with which you update, the vigor with which you do things, the charm with which you do things.

This update. Character faces, very clear. Much less chance of error. But the fingers. The probability of error in the hands is still high.

Second question: about clarity. Reproducing landscape paintings. Leaves of trees. Leaves of flowers. Clarity is still bad. It's very unclear.

I'll see if I can upload a picture. Or maybe you leave an e-mail address. I'll send you the image I generated. 我的电子邮件lijie5555698@gmail.com Please let me know yours. I'll get back to you as soon as I can. Thanks. Love you!!! 

![2023-11-15_20-36-46_5908](https://github.com/lllyasviel/Fooocus/assets/133008437/05e481cf-c4a4-4839-acc6-619a425be8ab)
![2023-11-15_21-25-26_8843](https://github.com/lllyasviel/Fooocus/assets/133008437/2cd6dab1-620a-405c-ad39-e21fcf1dfeac)
![2023-11-15_22-14-56_7344](https://github.com/lllyasviel/Fooocus/assets/133008437/dee832d9-0145-4968-b5ab-63972e5b5e06)
![2023-11-16_12-08-13_2242](https://github.com/lllyasviel/Fooocus/assets/133008437/0519c3f0-760b-48ce-a153-a08ff5edb9a7)
![2](https://github.com/lllyasviel/Fooocus/assets/133008437/95a50862-cfe4-40dc-8910-acc47fd28fe7)
![5](https://github.com/lllyasviel/Fooocus/assets/133008437/108b4dd5-a48e-4624-9c5f-838111df4442)
![11](https://github.com/lllyasviel/Fooocus/assets/133008437/d8a85751-6f10-43d8-a4a0-f4b79bdf4a59)

**Comment by lijie5555698** [comment]
Clarity is still bad. It's very unclear.Especially
 Especially the leaves of the trees. Foreground, previous version Foreground is still clearer[...] 
 You can see the leaves. version before 2.60.With
 With refiner. It's all clearer.[...] 
 Now it's updated.Functionality
 It's very powerful now.It's the first partIsn't it
 Is there a reason why there is no refiner?
![2023-11-16_15-38-37_1704](https://github.com/lllyasviel/Fooocus/assets/133008437/2a3626d1-0d3b-4c6a-9ac0-5c7f9861f179)
![2023-11-16_15-40-54_4596](https://github.com/lllyasviel/Fooocus/assets/133008437/e8a06829-f16b-47a1-92a6-f442a109e1d1)
![2023-11-16_15-45-00_1630](https://github.com/lllyasviel/Fooocus/assets/133008437/3961c13f-4e54-44c2-91c0-da4476c902f4)
![2023-11-16_15-46-14_6263](https://github.com/lllyasviel/Fooocus/assets/133008437/f7ed0103-7845-4864-8db2-eba116d25ca4)
![2023-11-16_16-49-40_7112](https://github.com/lllyasviel/Fooocus/assets/133008437/05584e95-2ec5-40d7-9db5-806338a83a4a)

**Comment by lijie5555698** [comment]
Character clarity is pretty good. Can the landscape clarity be updated? Thanks! Love you so much!

**Comment by mashb1t** [comment]
> First question: could you add a selector button for whether to let the user update or not.

You can adjust your entrypoint accordingly, call launch.py for no update or entry_with_update.py for update.

> This update. Character faces, very clear. Much less chance of error. But the fingers. The probability of error in the hands is still high.

This is not in the hands (hah, get it?) of Fooocus but of SDXL base and finetuned models. You might be able to find a LoRA for SDXL hand correction at civitai.com

> Second question: about clarity. Reproducing landscape paintings. Leaves of trees. Leaves of flowers. Clarity is still bad. It's very unclear.

Can you please update Fooocus to the latest version (if this doesn't work reinstall from the zip file in https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windows) and if it still doesn't work send us the meta data (history log) + the model you're using?

**Comment by mashb1t** [comment]
closing as stale, feel free to reopen when providing new information
