### ISSUE TITLE
First time installing. Failed.

### ISSUE THREAD

**Issue by xuegodot** [lllyasviel/Fooocus#964]
![QQ截图20231116191859](https://github.com/lllyasviel/Fooocus/assets/102223869/e1927a41-f8f1-4192-8e95-b5edc5e2c93e)

Somebody help me. thank you

**Comment by xhoxye** [comment]
If you have network problems connecting to the huggingface.co, please download the model file in another method

**Comment by xuegodot** [comment]
I downloaded the model another way and the problem is still there.

**Comment by xuegodot** [comment]
> If you have network problems connecting to the huggingface.co, please download the model file in another method. may be civitai.com?
I downloaded the model another way and the problem is still there.

**Comment by xhoxye** [comment]
Make sure that the name of the downloaded model file is the same as the required and stored in the specified folder.

**Comment by xuegodot** [comment]
> Make sure that the name of the downloaded model file is the same as the required and stored in the specified folder. If there is a difference, please change it to the same name.

Thanks for the heads up, works perfectly!

**Comment by GuidoBartoli** [comment]
> > Make sure that the name of the downloaded model file is the same as the required and stored in the specified folder. If there is a difference, please change it to the same name.
> 
> Thanks for the heads up, works perfectly!

You should close the issue, if it is resolved 😉
