### ISSUE TITLE
Possible to add an Upload Mask Feature ?

### ISSUE THREAD

**Issue by EKKIV0K** [lllyasviel/Fooocus#967]
Hello guys, i hope you're fine :) 
my request is pretty simple as A1111, can you add an "upload mask" feature ?
to be able to be more precise when we inpainting images ?
cause every times there is those strange blurred egdes around the inpainting object don't mach with the background.
the ability to add mask will helps to get more accurate inpainting :) 

or....is there to a trick to avoid that blurred edge with the inpainting object and the background ? 
i know it's a definition problem but maybe you can do something for that :) 
For anime it's not a real problem but when we work on photography it's a different problem :)

thanks guys :)

**Comment by kubilaykilinc** [comment]
You are right. I will be very usefull and life saver.

**Comment by hawk0123** [comment]
I really want this feature, precise control is more productive.

**Comment by mashb1t** [comment]
Support coming soon (hopefully, see PR https://github.com/lllyasviel/Fooocus/pull/529 or https://github.com/lllyasviel/Fooocus/pull/1645 to generate an image and override a face with only inpaint.
Closing as superseded by PR https://github.com/lllyasviel/Fooocus/issues/1036
