### ISSUE TITLE
Version 2.1.820 - LoRa s doesn't work

### ISSUE THREAD

**Issue by kubilaykilinc** [lllyasviel/Fooocus#968]
I am using Fooocus 2.1.820 - 

I did tests with the Loras I have used before. I also tested with sd_xl_offset_example-lora_1.0.safetensors. I use it all the time.
Any Lora no longer has any effect on the image.
I use the SDXL model and an SD 1.5 model as a refiner. There's no problem with that. However, no Lora command has any effect on the visual. I think there is a problem with this update.

**Comment by teherauto** [comment]
Fooocus 2.1.820
Yeah, same. The selected LoRa is not influence anything.
