### ISSUE TITLE
problem with bowtie mapping

### ISSUE THREAD

**Issue by Azimdine** [lllyasviel/Fooocus#97]
Dears SqueezeMeta developpers,
I've been trying to analyse my data for several days now but I always get an error on step 10. The first sample passes but when it wants to start the 2nd sample, I always get an error like: **the program has finished abnormally.** 

[34m[6 days, 16 hours, 3 minutes, 6 seconds]: STEP10 -> MAPPING READS: 10.mapsamples.pl
[0m  Reading samples from /pasteur/zeus/projets/p02/Biomics/Bioinfo/projet_Ariane/Result/data/00.Result.samples
  Metagenomes found: 32
  Mapping with Bowtie2 (Langmead and Salzberg 2012, Nat Methods 9(4), 357-9)
  Creating reference from contigs
  Working with sample 1: B1
  Getting raw reads
  Aligning to reference with bowtie
  Calculating contig coverage
  Reading contig length from /pasteur/zeus/projets/p02/Biomics/Bioinfo/projet_Ariane/Result/intermediate/01.Result.lon
  Counting with sqm_counter: Opening 36 threads
  1626281 reads counted
  3252561 reads counted
  4878841 reads counted
  6505121 reads counted
  8131401 reads counted
  9757681 reads counted
  11383961 reads counted
  13010241 reads counted
  14636521 reads counted
  16262801 reads counted
  17889081 reads counted
  19515361 reads counted
  21141641 reads counted
  22767921 reads counted
  24394201 reads counted
  26020481 reads counted
  27646761 reads counted
  29273041 reads counted
  30899321 reads counted
  32525601 reads counted
  34151881 reads counted
  35778161 reads counted
  37404441 reads counted
  39030721 reads counted
  40657001 reads counted
   reads counted
  42283281 reads counted
   reads counted
   reads counted
   reads counted
   reads counted
   reads counted
   reads counted
   reads counted
   reads counted
   reads counted
  Working with sample 2: B10
  Getting raw reads
  Aligning to reference with bowtie
[31mStopping in STEP10 -> 10.mapsamples.pl. Program finished abnormally
[0m[31m

Before I was using the previous version, it didn't work and a week ago, I updated the pipline and I'm on the latest version (1.6.2) but I still have the same problem. could you help me solve the problem? thank you for your help. 
please find attached the syslog.

[syslog.zip](https://github.com/lllyasviel/Fooocus/files/12342167/syslog.zip)

**Comment by mashb1t** [comment]
We haven't experienced this kind of error in a while now. Please try again with the latest version of Fooocusand feel free to reopen if still relevant.
