### ISSUE TITLE
Live Painting Krea.

### ISSUE THREAD

**Issue by gjakuipers** [lllyasviel/Fooocus#973]
@lllyasviel 

it is possible to make something like Krea AI LIVE PAINTING in FOOOCUS?

thx!

**Comment by qb20nh** [comment]
Sorry to tell you: No.

Stable Diffusion requires significant computational resources and time, ranging from seconds to minutes, to generate a single image. For real-time editing, the process needs to be much faster, ideally creating images in less than a second. It would require both significant architectural improvements in software and many performance breakthroughs in GPU hardware.

**Comment by gjakuipers** [comment]
understandable (for now), will ask over 1/2 year again ;-)

**Comment by qb20nh** [comment]
@gjakuipers
There is a significant improvement in stable diffusion.
https://arxiv.org/abs/2311.17042
It requires only 1-4 sampling steps to generate realistic images comparable to original SDXL model, which required 10-50 steps to generate usable image.
