### ISSUE TITLE
MPS backend out of memory

### ISSUE THREAD

**Issue by ufgo** [lllyasviel/Fooocus#980]
**Describe the problem**
Error when try to generate image on Mac OS (M1), Sonoma, 8gb RAM
**Full Console Log**
RuntimeError: MPS backend out of memory (MPS allocated: 8.93 GB, other allocations: 120.39 MB, max allowed: 9.07 GB). Tried to allocate 25.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
Total time: 67.34 seconds

**Comment by vicento** [comment]
when do you have this error ? 
on my M1 studio 32 gb i can't upscale x2 (that was possible with a previous version of Fooocus) 
If someone can fix it

**Comment by ufgo** [comment]
its work after i added this. in the launch.py: os.environ["PYTORCH_MPS_HIGH_WATERMARK_RATIO"] = "0.0"

**Comment by servettonga** [comment]
> its work after i added this in the launch.py: os.environ["PYTORCH_MPS_HIGH_WATERMARK_RATIO"] = "0.0"

Thanks, it helped
