### ISSUE TITLE
Unable to draw

### ISSUE THREAD

**Issue by llnqdx** [lllyasviel/Fooocus#986]
**Describe the problem**
Unable to draw.

**Full Console Log**
D:\Fooocus_2.1.821>.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
Found existing installation: torch 2.0.0
Uninstalling torch-2.0.0:
  Successfully uninstalled torch-2.0.0
Found existing installation: torchvision 0.15.1
Uninstalling torchvision-0.15.1:
  Successfully uninstalled torchvision-0.15.1
WARNING: Skipping torchaudio as it is not installed.
WARNING: Skipping torchtext as it is not installed.
WARNING: Skipping functorch as it is not installed.
WARNING: Skipping xformers as it is not installed.

D:\Fooocus_2.1.821>.\python_embeded\python.exe -m pip install torch-directml
Requirement already satisfied: torch-directml in d:\fooocus_2.1.821\python_embeded\lib\site-packages (0.2.0.dev230426)
Collecting torch==2.0.0 (from torch-directml)
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting torchvision==0.15.1 (from torch-directml)
  Using cached torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
Requirement already satisfied: filelock in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.12.2)
Requirement already satisfied: typing-extensions in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (4.7.1)
Requirement already satisfied: sympy in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (1.12)
Requirement already satisfied: networkx in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.1)
Requirement already satisfied: jinja2 in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.1.2)
Requirement already satisfied: numpy in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (1.23.5)
Requirement already satisfied: requests in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (9.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from jinja2->torch==2.0.0->torch-directml) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (2023.5.7)
Requirement already satisfied: mpmath>=0.19 in d:\fooocus_2.1.821\python_embeded\lib\site-packages (from sympy->torch==2.0.0->torch-directml) (1.3.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: torch, torchvision
  WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'D:\Fooocus_2.1.821\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed torch-2.0.0 torchvision-0.15.1

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: D:\Fooocus_2.1.821\python_embeded\python.exe -m pip install --upgrade pip

D:\Fooocus_2.1.821>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml
快速合并
国内在线更新成功！Fooocus中文本地化由CG工具站(tools.videosreel.com)进行技术支持.
Fooocus2.1.821更新内容：
1.界面高级里的LoRA模型的UI进行了更新，一般用户很难感知的到。
2.预设系统的改进，用户在web界面感知不到。
3.支持多用户访问fooocus进行出图，各用户之间看不见互相的出图结果，本项更新极大的方便了局域网出图用户。
4.改进了一些与模型精度相关的计算。
5.改进了配置加载系统在控制台的反馈，由于普通用户更改config文件会大概率格式出错，所以作者增加了很多控制台的错误反馈，让用户知道预设文件更改错在了哪里。
6.提示词翻译功能优化。
7.重绘画布提示按钮的位置优化。

[System ARGV] ['Fooocus\\entry_with_update.py', '--directml']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.821
Running on local URL:  http://0.0.0.0:8188
Using directml with device:
Total VRAM 1024 MB, total RAM 32500 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: privateuseone
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Refiner unloaded.
model_type EPS
adm 2816

To create a public link, set `share=True` in `launch()`.
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
extra keys {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: D:\Fooocus_2.1.821\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [D:\Fooocus_2.1.821\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [D:\Fooocus_2.1.821\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for model [D:\Fooocus_2.1.821\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cpu, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
程序成功启动. 使用程序通过 http://localhost:8188/ 或 0.0.0.0:8188
输入的prompt内容是：cat
输入的反向prompt内容是：
[参数] Adaptive CFG = 7
[参数] Sharpness = 2
[参数] ADM Scale = 1.5 : 0.8 : 0.3
[参数] CFG = 4.0
[参数] Seed = 5292702901020975515
[参数] 采样器 = dpmpp_2m_sde_gpu - karras
[参数] 步数 = 30 - 15
[Fooocus] 初始化 ...
[Fooocus] 加载模型中...
Refiner unloaded.
Request to load LoRAs [('sd_xl_offset_example-lora_1.0.safetensors', 0.1), ('None', 1), ('None', 1), ('None', 1), ('None', 1)] for model [D:\Fooocus_2.1.821\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [D:\Fooocus_2.1.821\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for model [D:\Fooocus_2.1.821\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Requested to load SDXLClipModel
Loading 1 new model
unload clone 1
[Fooocus] 处理提示词中...
[Fooocus] 准备Fooocus文本 #1 ...
[提示词扩展] cat, symmetry, perfect composition, detailed, dramatic, cinematic, artistic, extremely aesthetic, highly detail, intricate, stunning, color, beautiful, epic, surreal, inspired, vibrant, illuminated colors, winning, light, fine, full background, professional, historic, contemporary, creative, cool, wonderful, cute, great, pure, very coherent, colorful, ambient, iconic
[Fooocus] 准备Fooocus文本 #2 ...
[提示词扩展] cat, symmetry, mythical, magic, dramatic, sharp focus, extremely detailed, beautiful, intricate, cinematic, singular coherent, vivid color, illuminated, atmosphere, epic, stunning, highly enhanced, clear, artistic, light, novel, best, awesome, perfect, romantic, futuristic, cute, charming, surreal, creative, positive, unique, attractive, elegant, very stylish
[Fooocus] 编码正向 #1 ...
[Fooocus] 编码正向 #2 ...
[Fooocus] 编码反向 #1 ...
[Fooocus] 编码反向 #2 ...
准备时间: 11.35 秒
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Traceback (most recent call last):
  File "D:\Fooocus_2.1.821\Fooocus\modules\async_worker.py", line 755, in worker
    handler(task)
  File "D:\Fooocus_2.1.821\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_2.1.821\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_2.1.821\Fooocus\modules\async_worker.py", line 687, in handler
    imgs = pipeline.process_diffusion(
  File "D:\Fooocus_2.1.821\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_2.1.821\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_2.1.821\Fooocus\modules\default_pipeline.py", line 312, in process_diffusion
    modules.patch.BrownianTreeNoiseSamplerPatched.global_init(
  File "D:\Fooocus_2.1.821\Fooocus\modules\patch.py", line 173, in global_init
    BrownianTreeNoiseSamplerPatched.tree = BatchedBrownianTree(x, t0, t1, seed, cpu=cpu)
  File "D:\Fooocus_2.1.821\Fooocus\backend\headless\fcbh\k_diffusion\sampling.py", line 85, in __init__
    self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
  File "D:\Fooocus_2.1.821\Fooocus\backend\headless\fcbh\k_diffusion\sampling.py", line 85, in <listcomp>
    self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
  File "D:\Fooocus_2.1.821\python_embeded\lib\site-packages\torchsde\_brownian\derived.py", line 155, in __init__
    self._interval = brownian_interval.BrownianInterval(t0=t0,
  File "D:\Fooocus_2.1.821\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 540, in __init__
    W = self._randn(initial_W_seed) * math.sqrt(t1 - t0)
  File "D:\Fooocus_2.1.821\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 234, in _randn
    return _randn(size, self._top._dtype, self._top._device, seed)
  File "D:\Fooocus_2.1.821\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 32, in _randn    generator = torch.Generator(device).manual_seed(int(seed))
RuntimeError: Device type privateuseone is not supported for torch.Generator() api.
总时长: 11.59 秒

**Comment by ahamedzoha** [comment]
Facing the same issue. 
Using Windows 11, Conda env, Python 3.10.13
System: AMD 5600XT 6GB, Ryzen 3600 and 16GB Ram

Steps I did:
- git clone https://github.com/lllyasviel/Fooocus.git
- cd Fooocus
- pip3 install -r requirements_versions.txt
- pip uninstall torch torchvision torchaudio torchtext functorch xformers 
- pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.6
- python -s entry_with_update.py --directml


Log:
```
(image-gen) F:\Fooocus>python -s entry_with_update.py --directml
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--directml']
Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Using directml with device:
Total VRAM 1024 MB, total RAM 16335 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: privateuseone
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Refiner unloaded.
model_type EPS
adm 2816
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
extra keys {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: F:\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [F:\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [F:\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [F:\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cpu, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 1643540987255092422
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] boat on a pier, bright colors, highly detailed, cinematic, intricate, sharp focus, dramatic light, complimentary color, aesthetic, mushroom, vibrant, coherent, symmetry, extremely inspirational, located, shiny, epic, stunning, great composition, clear, beautiful, artistic, winning scenic, deep, inspiring, thought, contemporary, professional, best, novel, surreal, perfect
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] boat on a pier, romantic, cinematic, dramatic ambient light, detailed, relaxed, sharp focus, highly detail, intricate, beautiful, elegant, perfect, luxury, elite, enhanced, loving, attractive, delicate, coherent, lovely, novel, fancy, charming, peaceful, bright background, shiny, divine, wonderful, pretty, determined, pure, radiant, thought, colorful
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 19.44 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Traceback (most recent call last):
  File "F:\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "C:\Users\Zoha\miniconda3\envs\image-gen\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Zoha\miniconda3\envs\image-gen\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "C:\Users\Zoha\miniconda3\envs\image-gen\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Zoha\miniconda3\envs\image-gen\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus\modules\default_pipeline.py", line 354, in process_diffusion
    modules.patch.BrownianTreeNoiseSamplerPatched.global_init(
  File "F:\Fooocus\modules\patch.py", line 173, in global_init
    BrownianTreeNoiseSamplerPatched.tree = BatchedBrownianTree(x, t0, t1, seed, cpu=cpu)
  File "F:\Fooocus\backend\headless\fcbh\k_diffusion\sampling.py", line 85, in __init__
    self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
  File "F:\Fooocus\backend\headless\fcbh\k_diffusion\sampling.py", line 85, in <listcomp>
    self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
  File "C:\Users\Zoha\miniconda3\envs\image-gen\lib\site-packages\torchsde\_brownian\derived.py", line 155, in __init__
    self._interval = brownian_interval.BrownianInterval(t0=t0,
  File "C:\Users\Zoha\miniconda3\envs\image-gen\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 540, in __init__
    W = self._randn(initial_W_seed) * math.sqrt(t1 - t0)
  File "C:\Users\Zoha\miniconda3\envs\image-gen\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 234, in _randn
    return _randn(size, self._top._dtype, self._top._device, seed)
  File "C:\Users\Zoha\miniconda3\envs\image-gen\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 32, in _randn
    generator = torch.Generator(device).manual_seed(int(seed))
RuntimeError: Device type privateuseone is not supported for torch.Generator() api.
Total time: 19.93 seconds
```

**Comment by mashb1t** [comment]
This has already been fixed. Please use the latest version of Fooocus.
