### ISSUE TITLE
Can it support the ip-adapter-plus-face of the 1.5 refiner?

### ISSUE THREAD

**Issue by EvilBT** [lllyasviel/Fooocus#987]
Can it support the ip-adapter-plus-face of the 1.5 refiner? When using the 1.5 refiner, ip-adapter-plus-face will end early.

**Comment by mashb1t** [comment]
See https://github.com/lllyasviel/Fooocus/issues/1522, please check again with FaceSwap Image Prompt.

**Comment by mashb1t** [comment]
closing as stale, feel free to reopen when providing new information
