### ISSUE TITLE
Multi Prompts don't work

### ISSUE THREAD

**Issue by KappaMund** [lllyasviel/Fooocus#988]
I am using the latest version of Fooocus 2.1.822 at the moment.
I inserted a unique prompt into each line, but only 1 image is generated (all prompts in 1 image).
![image](https://github.com/lllyasviel/Fooocus/assets/140675665/ff42ad31-b379-42dd-a87c-9c62d63b5427)

There are no errors in the console.

```
Explorers cautiously navigate the labyrinth's twisting, metal corridors, dimly lit by flickering bulbs, echoing with the sounds of distant machinery.
In the depths of the labyrinth, survivors tread carefully on rusted platforms over gaping chasms, guided only by the sparse light of their torches.
A claustrophobic series of interconnected tunnels and chambers, filled with relics of forgotten technology, explored by scavengers in makeshift protective gear.
Silhouetted figures move stealthily through a maze of cold, concrete passageways, their breath visible in the chilly, damp air of the underground labyrinth.
An underground labyrinth where each turn reveals a new, complex puzzle of gears and levers, operated by inhabitants with a deep knowledge of ancient mechanics.
Abandoned industrial halls, repurposed into a maze of survival and cunning, where scavengers search for valuable scraps among the shadows.
A labyrinthine bunker, its walls lined with old, rusted pipes and faded maps, explored by those seeking shelter and secrets from a bygone era.
The labyrinth's vast, echoing chambers, once hubs of activity, now stand silent but for the sound of dripping water and cautious footsteps.
Creeping through a labyrinth of dark, narrow service tunnels, the labyrinth's dwellers navigate with a mix of fear and fascination.
In the heart of the labyrinth, a vast, abandoned control room, its screens and dials long dead, serves as a meeting point for the brave souls who traverse these depths.
```
![2023-11-20_12-09-58_4310](https://github.com/lllyasviel/Fooocus/assets/140675665/d6f0811c-f183-4c91-9c60-caebcf13aefc)

**Comment by Ambratolm** [comment]
I also tried the same in the past but neglected it, But when I saw your issue it just reminded to think how does mutli-prompt even work, what is it supposed to do ? Does it generate an image for every prompt (Should we increase `Image Number` accordingly ?) ? Does it stack content for every prompt on one image ? It did neither for me either.

**Comment by KappaMund** [comment]
![image](https://github.com/lllyasviel/Fooocus/assets/140675665/d4ebe5af-e4ef-44b1-a9d0-5d9165943061)

**Comment by lllyasviel** [comment]
Multi Prompts is semantic, not queue of tasks
https://docs.midjourney.com/docs/multi-prompts

**Comment by Ambratolm** [comment]
I tried it, it works but in some seeds it doesn't, so I guess you should just give it some more chance. I also think that the added styles may highly affect the result and make it easier or harder to achieve.
Left: `space ship` | Right: `space` <kbd>LineBreak</kbd> `ship` (same seed and settings)
![Honeyview_ss](https://github.com/lllyasviel/Fooocus/assets/27871399/1d36e5f2-02a9-423d-86cf-bdad8ada7d0f)
![Honeyview_spaceship](https://github.com/lllyasviel/Fooocus/assets/27871399/ffd24faf-20c8-4409-a246-57b925b193c2)

**Comment by regiellis** [comment]
Seems to work if you give it more of a descriptive prompt;
"deep space
cruise ship"
![ship](https://github.com/lllyasviel/Fooocus/assets/1148310/611ff67d-b401-4624-9925-a3b0f011e331)
